import type { ConceptLesson, DailyCourse, Exercise } from './types'

const conceptIds = [
  'ai-report-eval-scope',
  'ai-report-target-version',
  'ai-report-result-table',
  'ai-report-gate-threshold',
  'ai-report-failure-synthesis',
  'ai-report-risk-synthesis',
  'ai-report-launch-decision',
  'ai-report-evidence-boundary',
] as const

const prerequisiteConceptIds = [
  'ai-feature-system',
  'ai-request-context',
  'model-generation-boundary',
  'ai-capability-slots-overview',
  'ai-policy-orchestration',
  'ai-output-handoff',
  'ai-observation-audit',
  'tool-action-boundary',
  'tool-registry-schema',
  'tool-call-proposal',
  'tool-argument-validation',
  'tool-authorization',
  'tool-human-confirmation',
  'tool-execution-side-effect',
  'tool-result-receipt',
  'ai-eval-target-slice',
  'ai-eval-dimension-rubric',
  'ai-eval-case-schema',
  'ai-eval-behavior-oracle',
  'ai-eval-sample-strata',
  'ai-eval-safety-cases',
  'ai-eval-coverage-matrix',
  'ai-eval-set-gate',
  'ai-failure-observed-output',
  'ai-failure-knowledge-gap',
  'ai-failure-retrieval-gap',
  'ai-failure-source-conflict',
  'ai-failure-generation-overreach',
  'ai-failure-tool-chain',
  'ai-failure-expression-certainty',
  'ai-failure-classification-table',
  'ai-risk-token-cost',
  'ai-risk-unit-budget',
  'ai-risk-latency-budget',
  'ai-risk-critical-path',
  'ai-risk-safety-boundary',
  'ai-risk-safe-completion',
  'ai-risk-degradation-fallback',
  'ai-risk-human-escalation',
  'ai-risk-decision-table',
] as const

function concept(
  id: (typeof conceptIds)[number],
  prerequisiteConceptIds: readonly string[],
  term: string,
  english: string,
  definition: string,
  why: string,
  problemSolved: string,
  input: string,
  output: string,
  systemPosition: string,
  owner: string,
  notResponsibleFor: string,
  compareWith: string,
  pmUse: string,
  correctExample: string,
  incorrectExample: string,
  process: string[],
  evidence: string[],
  failureModes: string[],
): ConceptLesson {
  return {
    id,
    prerequisiteConceptIds: [...prerequisiteConceptIds],
    term,
    english,
    definition,
    why,
    problemSolved,
    input,
    output,
    systemPosition,
    process,
    owner,
    notResponsibleFor,
    compareWith,
    evidence,
    failureModes,
    pmUse,
    correctExample,
    incorrectExample,
  }
}

function exercise(
  id: string,
  categories: Exercise['categories'],
  conceptIds: string[],
  prompt: string,
  options: [string, string, string],
  answerIndex: number,
  referenceAnswer: string,
  remediationLabel: string,
): Exercise {
  return {
    id,
    kind: 'single-choice',
    categories,
    conceptIds,
    prompt,
    hint: '先确认报告范围和样本证据，再判断结论是否越过本地教学模拟边界。',
    options: options.map((label) => ({
      label,
      rationale: label === options[answerIndex] ? '这项把样本证据、门槛、风险和有限决策分开，没有把教学模拟写成生产审批。' : '这项要么缺少报告字段，要么把局部样本扩大成真实上线结论。',
      couldBeTrueWhen: label === options[answerIndex] ? '当目标版本、样本集、失败分类、风险建议和证据边界都可追溯时。' : '只有补充真实线上流量、生产日志、正式合规审核或发布审批后，才可能进一步判断。',
    })),
    answerIndex,
    referenceAnswer,
    reasoning: [
      '先固定 target_version、eval_set_id 和评测范围。',
      '再读取样本结果、失败分类和风险建议。',
      '最后给出有限 launch_decision 与后续补证计划。',
    ],
    rubric: ['报告范围清楚', '结论引用证据', '发布建议不过界'],
    commonErrors: [
      { error: '只写通过率，不写失败类型和风险建议。', reason: '综合评测报告必须把质量、失败原因、成本延迟安全和下一步动作连起来。' },
      { error: '把教学模拟写成真实上线批准。', reason: '本课没有真实生产流量、账单、P95、合规审查或审批记录。' },
    ],
    remediation: { label: remediationLabel, sectionId: 'concepts', anchor: `concept-${conceptIds[0]}` },
  }
}

export const w11d6: DailyCourse = {
  id: 'W11D6',
  contentVersion: 'w11d6-ai-service-eval-report-day01-v1',
  week: 11,
  day: 6,
  title: '评测 AI 客服',
  subtitle: '把最小评测集、失败分类、成本延迟安全风险建议合并成一份可审阅的 AI 客服综合评测报告，给出有限发布决策和补证计划。',
  duration: { core: 30, standard: 45, extension: 55, full: 105 },
  coreConceptGroups: [
    {
      id: 'report-scope',
      title: '报告先固定范围和版本',
      conceptIds: ['ai-report-eval-scope', 'ai-report-target-version'],
      summary: '综合评测必须说明评的是哪个功能、哪一版、哪一套样本和哪些不在范围内。',
      boundary: '本课只评 AI 客服教学模拟版本，不代表真实客服系统或生产上线审批。',
    },
    {
      id: 'result-gate',
      title: '结果表和门槛决定是否进入建议',
      conceptIds: ['ai-report-result-table', 'ai-report-gate-threshold'],
      summary: '报告不能只写感受；要有样本行、通过/失败、hard gate、阻断项和门槛判断。',
      boundary: '样本通过率只证明本地样本合同结果，不证明线上用户分布。',
    },
    {
      id: 'synthesis',
      title: '失败分类和风险建议必须合成',
      conceptIds: ['ai-report-failure-synthesis', 'ai-report-risk-synthesis'],
      summary: '失败分类回答哪里错，风险建议回答成本、延迟、安全如何处理；报告要把两者合成优先级。',
      boundary: '合成建议不能替代真实修复、监控或合规审查。',
    },
    {
      id: 'decision-boundary',
      title: '发布决策必须有限且可追溯',
      conceptIds: ['ai-report-launch-decision', 'ai-report-evidence-boundary'],
      summary: '最终只能给 allow_pilot、fix_before_pilot、block 或 manual_review 等有限建议，并写清还缺什么证据。',
      boundary: '本课不批准生产发布，不创建 W12 作品集或答辩材料。',
    },
  ],
  prerequisiteConceptIds: [...prerequisiteConceptIds],
  learningPaths: {
    '30': { guidedStepIndices: [0, 1, 2, 3, 4, 5], guidedRecordIndices: [0, 1, 2], exerciseCount: 3, deliverablePromptCount: 3, deliverableChecklistIndices: [0, 1, 2, 3], deliverableMinimumContributionCharacters: 180 },
    '45': { guidedStepIndices: [0, 1, 2, 3, 4, 5], guidedRecordIndices: [0, 1, 2, 3], exerciseCount: 4, deliverablePromptCount: 4, deliverableChecklistIndices: [0, 1, 2, 3, 4, 5], deliverableMinimumContributionCharacters: 260 },
  },
  primaryGoal: '产出一份 AI 客服综合评测报告：范围、结果摘要、失败分析、风险建议、发布决策和后续补证计划齐全，且每段写清教学模拟边界。',
  scenario: {
    role: '你是负责 AI 客服试点的产品经理。',
    situation: '团队已经有 20 条最小评测样本、失败分类表和成本延迟安全风险建议，但评审会需要一份能决定是否试点的综合报告。',
    question: '这版 AI 客服能不能进入有限试点？如果不能，应该先修什么、谁补证据、哪些结论不能说？',
    stakes: '报告写得过轻会放过安全和失败风险，写得过重会把教学模拟误当生产结论，导致团队误判上线节奏。',
  },
  objectives: [
    { id: 'scope', text: '固定评测范围、target_version、eval_set_id 与不在范围内的事项。', evidence: '报告 scope 行包含 target_version、eval_set_id、out_of_scope。' },
    { id: 'result', text: '把样本结果和 hard gate 转成可审阅结果摘要。', evidence: '报告 result_summary 行包含 pass_count、fail_count、hard_gate_status。' },
    { id: 'analysis', text: '把失败分类和风险建议合成为优先级。', evidence: '报告 failure_analysis 与 risk_recommendation 行引用失败类别和风险驱动。' },
    { id: 'decision', text: '给出有限发布决策和补证计划。', evidence: '报告 launch_decision 与 follow_up_plan 行写清教学模拟边界。' },
  ],
  prerequisites: [
    {
      id: 'w11d3-eval-set',
      conceptIds: [...prerequisiteConceptIds.slice(0, 23)],
      prompt: '你能把 W11D1 系统链、W11D2 工具调用和 W11D3 最小评测集接成报告输入吗？',
      passDescription: '能解释系统链位置、工具回执、副作用边界、样本字段、五类覆盖和安全 hard gate 分别给报告提供什么证据。',
      remediationLabel: '补 W11D1–W11D3：系统链、工具调用和最小评测集',
      remediationTarget: '#/lesson/W11D3',
      remediation: { purpose: '补齐报告输入中的系统对象、工具执行证据和样本合同。', steps: ['回看 W11D1 的 AI 系统链，标出请求、上下文、模型和审计。', '回看 W11D2 的工具调用链，区分 executorCalled=false、true 和回执未知。', '回看 W11D3 的 case schema、五类样本配额和 hard gate。'], successCheck: '能写出一行合格 eval case，并说明它引用的系统链和工具证据。' },
    },
    {
      id: 'w11d4-failure-table',
      conceptIds: [...prerequisiteConceptIds.slice(23, 31)],
      prompt: '你能把一次失败分到知识缺失、召回缺口、资料冲突、过度推断、工具链或表达过度确定吗？',
      passDescription: '能说明失败分类表的字段和证据边界。',
      remediationLabel: '补 W11D4：失败分类',
      remediationTarget: '#/lesson/W11D4',
      remediation: { purpose: '补齐报告中的失败分析。', steps: ['回看六类失败路径。', '说明 first_failed_stage。', '写出 evidence_limit。'], successCheck: '能写出一行失败分类 JSONL。' },
    },
    {
      id: 'w11d5-risk-table',
      conceptIds: [...prerequisiteConceptIds.slice(31)],
      prompt: '你能把成本、延迟、安全风险转成 watch/degrade/block/escalate 建议吗？',
      passDescription: '能说明风险建议表字段和不证明什么。',
      remediationLabel: '补 W11D5：成本延迟安全',
      remediationTarget: '#/lesson/W11D5',
      remediation: { purpose: '补齐报告中的风险建议。', steps: ['回看成本、延迟、安全三类风险。', '复述人工升级条件。', '写明教学模拟边界。'], successCheck: '能写出一行风险建议 JSONL。' },
    },
  ],
  concepts: [
    concept('ai-report-eval-scope', ['ai-eval-target-slice'], '评测报告范围', 'Evaluation report scope', '评测报告范围说明本报告评估哪个 AI 客服任务、哪些用户场景、哪些指标和哪些明确不评。', '没有范围，结论会被误用到没有测过的渠道、人群或功能。', '解决“报告看起来完整但没人知道适用哪里”的问题。', '功能名称、用户场景、样本来源、指标、排除项。', 'scope、in_scope、out_of_scope。', '位于综合报告最前面，限定后续所有结论。', '产品经理负责定义，评审人确认范围是否足够。', '不负责证明线上代表性或批准全量发布。', '区别于评测样本；样本是行级输入，范围是报告级边界。', '开评审会时先阻止团队把教学模拟结论扩展到所有客服场景。', '“仅评订单查询 AI 客服 v0.3 的 20 条教学样本。”', '“AI 客服整体已经可用。”', ['列出目标功能和用户场景。', '列出样本来源、指标和门槛。', '列出不在范围内事项。'], ['target_version。', 'eval_set_id。', 'out_of_scope。'], ['范围字段为空导致结论无法复现。', '范围写得大于样本真实覆盖。']),
    concept('ai-report-target-version', ['ai-eval-target-slice'], '目标版本锁定', 'Target version lock', '目标版本锁定是把评测结果绑定到某一版 prompt、工具目录、策略和样本时间点。', 'AI 系统变化快，不锁版本就无法复现报告。', '解决“这份报告到底评的是哪一版”的问题。', '版本号、配置摘要、样本时间、策略版本。', 'target_version 与 config_note。', '连接系统链、工具链和评测结果的复现锚点。', '产品经理和工程负责人共同维护版本记录。', '不负责证明新版本仍有同样结果。', '区别于发布时间；target_version 是被测对象，不是上线时间。', '评审报告时拒绝把旧版本结果套到新版本。', '“target_version=ai-cs-v0.3; policy=refund-safe-v2。”', '“昨天测过，所以今天这版也通过。”', ['锁定被测功能版本。', '锁定策略、工具目录与配置摘要。', '锁定样本集与评测时间点。'], ['target_version。', 'config_note。', 'evaluated_at。'], ['版本字段缺失导致复测无法对齐。', '评测后改配置但不重新测试。']),
    concept('ai-report-result-table', ['ai-eval-set-gate'], '评测结果表', 'Evaluation result table', '评测结果表把每条样本的通过/失败、失败类别、风险字段和证据链接压缩成可审阅摘要。', '报告需要能从结论追溯到样本，不能只有一句“效果不错”。', '解决评审无法定位问题样本的问题。', 'case_id、expected_action、observed_output、pass/fail、failure_category、risk_decision。', '样本结果摘要和失败分布。', '位于样本明细和报告结论之间。', '产品经理组织，研发或评测同学提供原始结果。', '不负责替代原始样本明细或自动评分系统。', '区别于失败分类表；结果表汇总通过/失败，失败分类表解释失败来源。', '把评审注意力拉回可复现样本。', '“20 条样本，14 通过、6 失败，其中 2 条 hard gate 失败。”', '“大部分回答看起来可以。”', ['读取样本结果。', '统计通过失败。', '关联失败类别和风险。'], ['pass_count。', 'fail_count。', 'hard_gate_status。'], ['只写百分比。', '不保留 case_id。']),
    concept('ai-report-gate-threshold', ['ai-eval-safety-cases', 'ai-eval-set-gate'], '报告门槛', 'Report gate threshold', '报告门槛定义什么情况允许试点、必须修复、必须阻断或必须人工复核。', '没有门槛，团队会用主观偏好替代评审标准。', '解决“通过率多少算够、安全失败怎么算”的问题。', '通过率、hard gate、关键失败、风险阻断项。', 'launch_gate_status。', '连接结果摘要和发布决策。', '产品、业务、安全共同确定。', '不负责证明门槛本身已经适合生产。', '区别于练习题分数；报告门槛决定产品动作。', '让评审会议先看阻断项，再谈优化。', '“hard_gate_failed>0 时不能 allow_pilot。”', '“80% 通过就一定上线。”', ['设定通过率门槛。', '设定 hard gate。', '设定风险阻断。'], ['pass_threshold。', 'hard_gate_failed。', 'decision_reason。'], ['用平均分掩盖安全失败。', '没有阻断规则。']),
    concept('ai-report-failure-synthesis', ['ai-failure-classification-table'], '失败合成', 'Failure synthesis', '失败合成把多条失败样本归纳成主要失效模式、优先修复对象和影响范围。', '单条失败只能定位局部，报告需要说明模式和优先级。', '解决“知道错了但不知道先修什么”的问题。', '失败分类表、case_id、first_failed_stage、evidence_seen。', 'top_failure_modes 与 fix_priority。', '位于结果摘要之后、风险建议之前。', '产品经理负责排序，工程和内容负责人确认可修复性。', '不负责证明真实根因已经修复。', '区别于根因复盘；失败合成是评测报告里的优先级判断。', '把知识缺失、工具链失败、安全越界分到不同负责人。', '“2 条工具链失败阻断退款场景，优先修回执和人工升级。”', '“模型不聪明，所以换大模型。”', ['按失败类别聚合同类样本。', '绑定 first_failed_stage 和负责人。', '写出修复优先级和影响范围。'], ['failure_category。', 'first_failed_stage。', 'fix_priority。'], ['不引用样本就下修复结论。', '直接跳到模型根因不保留证据。']),
    concept('ai-report-risk-synthesis', ['ai-risk-decision-table'], '风险合成', 'Risk synthesis', '风险合成把成本、延迟、安全建议接到失败模式和发布决策上。', '质量通过不代表可上线，风险过高也可能阻断试点。', '解决“报告只有质量，没有上线风险”的问题。', '风险建议表、成本驱动、延迟驱动、安全风险、人工升级条件。', 'risk_blockers 与 mitigation_plan。', '位于失败合成和发布决策之间。', '产品经理组织，安全/工程/运营共同评审。', '不负责替代真实账单、P95 或合规审查。', '区别于 W11D5 风险建议表；这里把风险建议接入综合报告。', '判断哪些失败可先试点观察，哪些必须先阻断。', '“安全阻断样本导致 fix_before_pilot，工具超时改后台降级。”', '“风险都能以后再说，不需要记录成本延迟安全字段。”', ['读取风险建议表。', '标出安全、延迟或成本阻断项。', '写出缓解动作和责任人。'], ['risk_blocker。', 'mitigation。', 'owner。'], ['成本/延迟/安全缺一类。', '不写缓解动作。']),
    concept('ai-report-launch-decision', ['ai-report-gate-threshold', 'ai-report-risk-synthesis'], '有限发布决策', 'Bounded launch decision', '有限发布决策是在证据范围内给出 allow_pilot、fix_before_pilot、block 或 manual_review 的建议。', '评测报告必须推动行动，但不能越权成上线审批。', '解决“报告结论不是太虚就是太满”的问题。', '门槛状态、失败合成、风险合成、业务影响。', 'launch_decision 与 decision_reason。', '位于综合报告结论段，连接门槛、风险和后续补证计划。', '产品经理提出有限建议，评审组决定是否采纳。', '不负责替代真实审批、法务合规或生产监控。', '区别于 product_action；launch_decision 是报告级建议，product_action 是行级动作。', '评审会最后用它决定是否进入有限试点或先修复。', '“fix_before_pilot：hard gate 失败 2 条，先修隐私拒答。”', '“可以全量上线，后续不用再补真实生产证据。”', ['检查报告门槛是否通过。', '检查安全、延迟和成本阻断风险。', '给出有限建议和下一责任人。'], ['launch_decision。', 'decision_reason。', 'next_owner。'], ['只写结论没有证据原因。', '越权批准全量发布。']),
    concept('ai-report-evidence-boundary', ['ai-report-eval-scope'], '报告证据边界', 'Report evidence boundary', '报告证据边界说明本地教学模拟能证明报告结构、字段和有限判断，不能证明真实生产表现。', '边界不写清，报告会被误读成生产证据。', '解决“评测报告被拿去当上线批准”的问题。', '样本来源、教学模拟声明、缺失证据、后续补证计划。', 'evidence_limit 与 follow_up_plan。', '贯穿报告每一段，约束范围、结果、失败、风险和发布建议。', '产品经理负责写清，评审人检查是否诚实。', '不负责补齐真实生产证据本身。', '区别于免责声明；证据边界必须具体列出缺什么。', '在每个结论后写“还不能证明什么”。', '“教学模拟只证明报告合同可用，不能证明生产转化、P95 或合规充分。”', '“本报告已证明可以上线。”', ['标注教学模拟来源。', '列出缺失的真实生产证据。', '安排补证责任人与复测计划。'], ['evidence_limit。', 'missing_evidence。', 'follow_up_plan。'], ['只写一句谨慎。', '缺少具体补证人和证据。']),
  ],
  diagram: {
    title: 'AI 客服综合评测报告链',
    caption: '报告从范围和版本开始，读取样本结果、失败分类和风险建议，最后形成有限发布决策和补证计划。',
    nodes: [
      { id: 'scope', label: '范围/版本', description: '锁定 AI 客服任务、target_version、eval_set_id 和排除项。', input: '功能与样本集', output: 'report_scope', owner: '产品经理', evidence: 'target_version、out_of_scope' },
      { id: 'results', label: '结果摘要', description: '汇总通过、失败、hard gate 和样本明细链接。', input: '20 条样本结果', output: 'result_summary', owner: '产品/评测' },
      { id: 'failures', label: '失败合成', description: '聚合失败类别和 first_failed_stage。', input: '失败分类表', output: 'top_failure_modes', owner: '产品/工程' },
      { id: 'risks', label: '风险合成', description: '合并成本、延迟、安全风险建议。', input: '风险建议表', output: 'risk_blockers', owner: '产品/安全/运营' },
      { id: 'decision', label: '有限决策', description: '给出 allow_pilot/fix_before_pilot/block/manual_review。', input: '门槛、失败、风险、边界', output: 'launch_decision', owner: '产品评审会' },
    ],
    branches: [
      { from: 'scope', to: 'results', label: '限定解释范围', kind: 'normal' },
      { from: 'results', to: 'failures', label: '失败样本进入分类', kind: 'failure' },
      { from: 'failures', to: 'risks', label: '失败模式叠加成本延迟安全', kind: 'failure' },
      { from: 'risks', to: 'decision', label: '阻断项影响发布建议', kind: 'failure' },
    ],
    evidenceNotes: ['所有结果来自本地教学模拟样本。', '报告不能证明真实线上代表性、生产 P95、账单或正式合规充分。'],
  },
  demonstration: {
    title: '教师示范：把三张表合成一份报告',
    businessProblem: 'AI 客服试点评审前，团队手里有样本集、失败分类和风险建议，但还没有能决策的综合报告。',
    finalConclusion: '教学模拟报告建议 fix_before_pilot：先修隐私拒答和工具超时降级，再用同一门槛复测。',
    conclusionLimit: '这只能证明报告合同、字段和有限判断可用，不能证明真实生产表现、合规充分或上线已获批准。',
    steps: [
      { title: '锁范围和版本', action: '写入 target_version=ai-cs-v0.3、eval_set_id=w11-teaching-20。', reason: '先限制报告适用范围。', evidence: 'scope 行含 target_version 和 out_of_scope。', proves: '报告对象可复现。', limitation: '不能证明新版本同样表现。' },
      { title: '汇总结果和门槛', action: '统计 20 条教学样本 14 pass、6 fail、2 hard gate fail。', reason: '发布建议必须先看阻断门槛。', evidence: 'result_summary 行含 pass_count、fail_count、hard_gate_status。', proves: '本地样本结果可审阅。', limitation: '不能证明线上用户分布。' },
      { title: '合成失败模式', action: '把失败聚成隐私拒答缺失、工具回执未知、过度确定三类。', reason: '报告要告诉团队先修什么。', evidence: 'failure_analysis 行引用 failure_category 和 case_id。', proves: '失败优先级可追溯。', limitation: '不能证明真实根因已修复。' },
      { title: '合成风险建议', action: '把安全阻断、超时降级和人工升级写入 risk_recommendation。', reason: '质量失败之外还要看成本、延迟、安全。', evidence: 'risk_recommendation 行引用 risk_driver。', proves: '风险建议进入报告。', limitation: '不能替代真实账单、P95 或合规。' },
      { title: '给有限发布决策', action: '写 launch_decision=fix_before_pilot，原因是 hard gate 未过。', reason: '报告必须能推动下一步。', evidence: 'launch_decision 行含 decision_reason。', proves: '建议与门槛一致。', limitation: '不是正式上线审批。' },
      { title: '写后续补证计划', action: '列出复测、线上灰度监控、账单、延迟和合规补证。', reason: '有限报告要说明下一轮证据。', evidence: 'follow_up_plan 行含 owner 和 missing_evidence。', proves: '补证计划可分派给明确责任人。', limitation: '不能证明补证已经完成。' },
    ],
  },
  guidedLab: {
    title: '综合评测报告六段教学模拟',
    goal: '运行六段本地教学模拟，观察范围、结果摘要、失败分析、风险建议、发布决策和补证计划如何组成一份 AI 客服综合评测报告。',
    safety: '不调用真实模型、工具、账号、Token、公司数据、生产日志、账单或合规系统；所有输出均为教学模拟。',
    conceptIds: [...conceptIds],
    predictionPrompt: '先预测：如果 20 条样本中有 2 条隐私 hard gate 失败，报告最终应 allow_pilot、fix_before_pilot、block 还是 manual_review？为什么？',
    steps: [
      { title: 'scope_version', action: '运行范围段，锁 target_version、eval_set_id、in_scope、out_of_scope。', observe: 'report_part=scope; target_version=ai-cs-v0.3。', explanation: '范围段限定报告可用边界。', proves: '能证明报告对象可复现。', cannotProve: '不能证明其他版本或真实生产场景。' },
      { title: 'result_summary', action: '运行结果段，读取 pass_count=14、fail_count=6、hard_gate_failed=2。', observe: 'report_part=result_summary; gate_status=failed。', explanation: 'hard gate 失败会阻断直接试点。', proves: '能证明本地样本门槛未过。', cannotProve: '不能证明线上通过率。' },
      { title: 'failure_analysis', action: '运行失败段，聚合 privacy_refusal_missing、tool_receipt_unknown、overcertainty。', observe: 'report_part=failure_analysis; top_failure_modes=3。', explanation: '失败模式决定修复优先级。', proves: '能证明教学样本存在可追溯失败簇。', cannotProve: '不能证明生产根因。' },
      { title: 'risk_recommendation', action: '运行风险段，合并 safety_policy_block、timeout_degradation、human_escalation。', observe: 'report_part=risk_recommendation; risk_blockers=privacy。', explanation: '风险建议影响发布决策。', proves: '能证明风险字段可进入报告。', cannotProve: '不能替代真实账单、P95 或合规审查。' },
      { title: 'launch_decision', action: '运行决策段，得到 launch_decision=fix_before_pilot。', observe: 'report_part=launch_decision; decision_reason=hard_gate_failed。', explanation: '有限决策必须引用门槛和阻断项。', proves: '能证明建议与教学门槛一致。', cannotProve: '不能代表正式上线审批。' },
      { title: 'follow_up_plan', action: '运行计划段，输出 owners、missing_evidence 和 retest_plan。', observe: 'report_part=follow_up_plan; owner=PM/Eng/Safety。', explanation: '报告结尾要能分派补证。', proves: '能证明下一步可执行。', cannotProve: '不能证明补证已经完成。' },
    ],
    recordPrompts: [
      '记录范围段：target_version、eval_set_id、out_of_scope、不能证明什么。',
      '记录结果段：pass/fail、hard gate、gate_status、不能证明什么。',
      '记录失败和风险段：top_failure_modes、risk_blockers、fix_priority、不能证明什么。',
      '记录决策和计划段：launch_decision、owner、missing_evidence、后续复测。',
    ],
    comparePrompt: '比较六段：哪一段限定范围，哪一段给门槛，哪一段给失败优先级，哪一段给发布建议？',
    passCriteria: [
      '六段报告模拟均运行并标注教学模拟。',
      '每段都写出能证明和不能证明的边界。',
      '发布决策引用 hard gate、失败分类和风险阻断项。',
      '没有声称真实生产表现、正式合规或上线审批已经证明。',
    ],
  },
  independentLab: {
    title: '退款 AI 客服综合评测变式',
    scenario: '把同一报告框架迁移到“退款进度 AI 客服”试点：样本中包含隐私拒答、工具回执未知、高价值争议和长上下文成本。',
    conceptIds: [...conceptIds],
    changedConditions: ['hard_gate_failed 从 2 条变成 0 条，需要重新判断是否仍阻断。', '工具回执未知集中在高价值退款场景，风险不能被平均通过率抵消。', '通过率达标但成本超单位预算，需要写出观察或降级建议。'],
    task: '写出一份 6 段报告草案，至少包含范围、结果摘要、失败分析、风险建议、发布决策和补证计划。',
    predictionPrompt: '先预测这次应 allow_pilot、fix_before_pilot、block 还是 manual_review，并写出证据。',
    evidenceRequirements: [
      '报告每段至少引用样本结果、失败分类或风险建议中的一种证据。',
      '每段写清教学模拟能证明的范围，以及还不能证明的真实生产证据。',
      '发布建议与 hard gate、风险阻断、成本延迟安全和补证计划一致。',
    ],
    passCriteria: [
      '六段报告齐全且每段 section_id 正确。',
      '发布建议不越过教学模拟证据边界。',
      '至少包含一个失败优先级和一个风险缓解动作。',
      '没有创建 W12 作品集、答辩或真实上线审批材料。',
    ],
    remediation: { label: '回到综合报告链重新补齐六段', sectionId: 'concepts', anchor: 'concept-ai-report-launch-decision' },
  },
  exercises: [
    exercise('w11d6-scope', ['概念与边界'], ['ai-report-eval-scope', 'ai-report-target-version'], '报告只写“AI 客服通过 70%”。最先缺哪一类信息？', ['target_version、eval_set_id、范围和排除项', '按钮颜色和页面视觉', '真实公司 Token'], 0, '没有范围和版本，70% 无法复现，也不能判断适用边界。', '回看报告范围和目标版本'),
    exercise('w11d6-gate', ['证据判断'], ['ai-report-result-table', 'ai-report-gate-threshold'], '20 条样本 18 条通过，但 1 条 privacy hard gate 失败。最克制的结论是？', ['仍需 fix_before_pilot 或 block，不能被平均通过率抵消', '通过率 90%，直接 allow_pilot', '忽略 privacy，因为只有 1 条'], 0, 'hard gate 是阻断门槛，不能被平均分或通过率抵消。', '回看报告门槛'),
    exercise('w11d6-synthesis', ['机制推演'], ['ai-report-failure-synthesis', 'ai-report-risk-synthesis'], '失败分类显示工具回执未知，风险建议表要求 human_escalation。报告应怎么写？', ['把它列为失败优先级和风险阻断/人工升级建议', '只写模型不稳定', '只写继续观察，不交接证据'], 0, '综合报告要把失败来源和风险动作合成，而不是只贴标签。', '回看失败合成与风险合成'),
    exercise('w11d6-decision', ['工作场景', '综合变式'], ['ai-report-launch-decision', 'ai-report-evidence-boundary'], '报告结尾写“本地教学模拟已证明可以全量上线”。问题在哪里？', ['越过证据边界，应改成有限建议和补证计划', '应该把“全量”改成“马上”', '只需要多写几条样本'], 0, '本课只能给有限发布建议，不证明真实生产表现或正式审批。', '回看有限发布决策与报告证据边界'),
  ],
  deliverable: {
    title: 'AI 客服综合评测报告',
    conceptIds: [...conceptIds],
    purpose: '把样本结果、失败分类和风险建议合并成可审阅报告，支持是否进入有限试点的产品决策。',
    whenToUse: '用于 W11D6 收口评审，判断 AI 客服是否 allow_pilot、fix_before_pilot、block 或 manual_review。',
    audience: '产品经理、工程负责人、安全/合规评审、运营负责人。',
    fields: [
      { name: 'section_id', meaning: '报告段落：scope/result_summary/failure_analysis/risk_recommendation/launch_decision/follow_up_plan', source: '报告结构' },
      { name: 'report_part', meaning: '段落中文说明', source: '本课报告链' },
      { name: 'evidence_used', meaning: '引用的样本、失败分类或风险建议证据', source: 'W11D3–W11D5 教学模拟' },
      { name: 'conclusion', meaning: '该段有限结论', source: '本课综合判断' },
      { name: 'recommendation', meaning: '行动建议、负责人或补证计划', source: 'PM 建议' },
      { name: 'evidence_limit', meaning: '教学模拟能证明与不能证明什么', source: '证据边界' },
    ],
    badExample: '{"section_id":"summary","conclusion":"AI 客服已经可全量上线","recommendation":"上线"}',
    badReasons: ['没有范围、版本、结果、失败、风险和补证段。', '没有引用样本或风险证据。', '把教学模拟写成生产上线审批。'],
    revisionSteps: ['改成六段 JSONL。', '每段引用 W11D3–W11D5 的一种证据。', 'launch_decision 只能使用 allow_pilot/fix_before_pilot/block/manual_review。', '每段写明 evidence_limit。'],
    goodExample: '{"section_id":"launch_decision","report_part":"有限发布决策","evidence_used":"hard_gate_failed=2; risk_blocker=privacy","conclusion":"fix_before_pilot","recommendation":"先修隐私拒答和工具超时降级，再用同一 eval_set 复测","evidence_limit":"教学模拟只证明本地报告合同和有限决策，不能证明真实生产表现、正式合规或上线审批"}',
    guidedPrompts: [
      '先写 scope：target_version、eval_set_id、out_of_scope。',
      '再写 result_summary：pass/fail、hard gate、门槛状态。',
      '再写 failure_analysis 和 risk_recommendation：失败簇、风险阻断、缓解动作。',
      '最后写 launch_decision 和 follow_up_plan：有限建议、负责人、缺失证据。',
    ],
    blankTemplate: [
      '{"section_id":"","report_part":"","evidence_used":"","conclusion":"","recommendation":"","evidence_limit":"教学模拟：能证明；不能证明"}',
    ].join('\n'),
    standardTemplate: [
      '{"section_id":"scope","report_part":"评测范围与版本","evidence_used":"target_version=ai-cs-v0.3; eval_set_id=w11-teaching-20; out_of_scope=真实生产流量/正式合规审批","conclusion":"本报告只评 AI 客服订单查询教学模拟版本","recommendation":"后续变更 prompt、工具目录或安全策略后必须重测","evidence_limit":"教学模拟只证明本地评测对象可复现，不能证明其他版本或真实生产场景"}',
      '{"section_id":"result_summary","report_part":"结果摘要与门槛","evidence_used":"pass_count=14; fail_count=6; hard_gate_failed=2; pass_threshold=16/20","conclusion":"本地样本未达到试点门槛","recommendation":"先处理 hard gate 失败，再复跑同一 eval_set","evidence_limit":"教学模拟只证明 20 条样本合同结果，不能证明线上用户分布或真实通过率"}',
      '{"section_id":"failure_analysis","report_part":"失败分类合成","evidence_used":"privacy_refusal_missing=2; tool_receipt_unknown=2; overcertainty=2","conclusion":"主要失败集中在隐私拒答、工具回执未知和表达过度确定","recommendation":"隐私拒答和工具回执优先修复，表达语气作为第二优先级","evidence_limit":"教学模拟只证明这些样本的失败分类，不能证明生产根因已修复"}',
      '{"section_id":"risk_recommendation","report_part":"成本延迟安全风险建议","evidence_used":"safety_policy_block; timeout_degradation; human_escalation; token_budget_exceeded","conclusion":"安全阻断和超时降级影响试点，成本风险需要观察","recommendation":"隐私类 block，工具超时 degrade，高价值争议 escalate，长上下文 watch","evidence_limit":"教学模拟只证明风险建议合同可用，不能替代真实账单、生产 P95 或正式合规审查"}',
      '{"section_id":"launch_decision","report_part":"有限发布决策","evidence_used":"gate_status=failed; hard_gate_failed=2; risk_blocker=privacy","conclusion":"fix_before_pilot","recommendation":"修复隐私拒答和工具超时降级后，允许小流量内部试点复测","evidence_limit":"教学模拟只支持有限产品建议，不能代表真实上线审批或全量发布批准"}',
      '{"section_id":"follow_up_plan","report_part":"后续补证计划","evidence_used":"missing_evidence=production_logs/billing/p95/compliance_review; owners=PM/Eng/Safety/Ops","conclusion":"需要补真实日志、账单、延迟、合规和人工处理结果","recommendation":"PM 维护报告，工程补日志和延迟，安全补合规审核，运营补人工升级记录","evidence_limit":"教学模拟只证明补证计划可分派，不能证明补证已经完成"}',
    ].join('\n'),
    checklist: [
      '恰好 6 行 JSONL，每行可解析。',
      '六段 scope、result_summary、failure_analysis、risk_recommendation、launch_decision、follow_up_plan 均出现。',
      '每行都有 evidence_used、conclusion、recommendation、evidence_limit。',
      'launch_decision 只能是 allow_pilot、fix_before_pilot、block 或 manual_review。',
      '每行 evidence_limit 都含“教学模拟”并写明不能证明什么。',
      '没有声称真实生产表现、正式合规或上线审批已证明。',
    ],
  },
  memory: {
    conceptIds: [...conceptIds],
    anchors: ['报告先锁范围和版本。', 'hard gate 不能被平均通过率抵消。', '失败分类和风险建议要合成优先级。', '发布决策必须有限，并写清还缺的真实证据。'],
    closedBookPrompt: '闭卷复述八个首次教学概念，并用一条 AI 客服样本说明如何从结果、失败、风险走到 launch_decision。',
    microOperation: '把一条风险建议表补进综合报告的 risk_recommendation 段。',
    unresolvedPrompt: '这份教学模拟报告还缺哪些真实生产证据，分别由谁补？',
    reviewStages: [
      { stage: 'D1', task: '闭卷写出综合评测报告六段结构。' },
      { stage: 'D3', task: '判断一份报告是否把教学模拟越界写成上线审批。' },
      { stage: 'D7', task: '把 hard gate 失败样本改写成 fix_before_pilot 决策。' },
      { stage: 'D14', task: '为一条工具回执未知样本写失败合成和风险合成。' },
      { stage: 'D30', task: '比较 allow_pilot、fix_before_pilot、block、manual_review。' },
      { stage: 'D60', task: '列出上线前还必须补的真实日志、账单、延迟、合规证据。' },
    ],
  },
  nextLesson: {
    id: 'W12D1',
    title: '作品集开题与证据整理',
    bridge: '下一阶段才把已完成课程证据整理成作品集与答辩材料；本轮只声明路线衔接，不创建或开放 W12D1。',
  },
}
