import type { ConceptLesson, DailyCourse, Exercise } from './types'

const conceptIds = [
  'ai-risk-token-cost',
  'ai-risk-unit-budget',
  'ai-risk-latency-budget',
  'ai-risk-critical-path',
  'ai-risk-safety-boundary',
  'ai-risk-safe-completion',
  'ai-risk-degradation-fallback',
  'ai-risk-human-escalation',
  'ai-risk-decision-table',
] as const

const prerequisiteConceptIds = [
  'ai-feature-system',
  'ai-request-context',
  'model-generation-boundary',
  'ai-capability-slots-overview',
  'ai-policy-orchestration',
  'ai-output-handoff',
  'ai-observation-audit',
  'tool-action-boundary',
  'tool-registry-schema',
  'tool-call-proposal',
  'tool-argument-validation',
  'tool-authorization',
  'tool-human-confirmation',
  'tool-execution-side-effect',
  'tool-result-receipt',
  'ai-eval-target-slice',
  'ai-eval-dimension-rubric',
  'ai-eval-case-schema',
  'ai-eval-behavior-oracle',
  'ai-eval-sample-strata',
  'ai-eval-safety-cases',
  'ai-eval-coverage-matrix',
  'ai-eval-set-gate',
  'ai-failure-observed-output',
  'ai-failure-knowledge-gap',
  'ai-failure-retrieval-gap',
  'ai-failure-source-conflict',
  'ai-failure-generation-overreach',
  'ai-failure-tool-chain',
  'ai-failure-expression-certainty',
  'ai-failure-classification-table',
] as const

function concept(
  id: (typeof conceptIds)[number],
  prerequisiteConceptIds: readonly string[],
  term: string,
  english: string,
  definition: string,
  why: string,
  problemSolved: string,
  input: string,
  output: string,
  systemPosition: string,
  owner: string,
  notResponsibleFor: string,
  compareWith: string,
  pmUse: string,
  correctExample: string,
  incorrectExample: string,
  process: string[],
  evidence: string[],
  failureModes: string[],
): ConceptLesson {
  return {
    id,
    prerequisiteConceptIds: [...prerequisiteConceptIds],
    term,
    english,
    definition,
    why,
    problemSolved,
    input,
    output,
    systemPosition,
    process,
    owner,
    notResponsibleFor,
    compareWith,
    evidence,
    failureModes,
    pmUse,
    correctExample,
    incorrectExample,
  }
}

function exercise(
  id: string,
  categories: Exercise['categories'],
  conceptIds: string[],
  prompt: string,
  options: [string, string, string],
  answerIndex: number,
  referenceAnswer: string,
  remediationLabel: string,
): Exercise {
  return {
    id,
    kind: 'single-choice',
    categories,
    conceptIds,
    prompt,
    hint: '先判断它属于成本、延迟还是安全；再看证据是否足够支持行动建议。',
    options: options.map((label) => ({
      label,
      rationale: label === options[answerIndex] ? '这项把可见证据、风险维度和下一步动作分开，没有越界承诺生产事实。' : '这项要么跳过了证据边界，要么把一次教学模拟扩大成生产结论。',
      couldBeTrueWhen: label === options[answerIndex] ? '当同一教学样本的字段、预算或安全门槛都能被复核时。' : '只有获得额外日志、账单、线上样本或人工审核证据后，才可能进一步判断。',
    })),
    answerIndex,
    referenceAnswer,
    reasoning: [
      '先固定输入、输出、预算或安全门槛。',
      '再判断本次证据支持哪一类风险。',
      '最后只给出与证据强度匹配的产品动作。',
    ],
    rubric: ['风险维度准确', '证据边界清楚', '建议可执行且不过度承诺'],
    commonErrors: [
      { error: '把 token 数直接写成总成本结论。', reason: '单次教学模拟不能证明线上量级、折扣、缓存或真实账单。' },
      { error: '把慢响应直接归因为模型差。', reason: '延迟可能来自排队、工具、网络、重试或安全检查。' },
    ],
    remediation: { label: remediationLabel, sectionId: 'concepts', anchor: `concept-${conceptIds[0]}` },
  }
}

export const w11d5: DailyCourse = {
  id: 'W11D5',
  contentVersion: 'w11d5-cost-latency-safety-day01-v1',
  week: 11,
  day: 5,
  title: '成本、延迟与安全',
  subtitle: '把 AI 评测结果补上 token 与工具成本、响应延迟、安全边界、降级兜底和人工升级建议，形成不过度承诺的风险建议表。',
  duration: { core: 30, standard: 45, extension: 55, full: 100 },
  coreConceptGroups: [
    {
      id: 'cost-budget',
      title: '成本必须先拆成驱动因子和单位预算',
      conceptIds: ['ai-risk-token-cost', 'ai-risk-unit-budget'],
      summary: 'token、工具调用、重试和人工复核都会改变单次成本；预算必须写成每次、每天或每千次的可复核单位。',
      boundary: '本课只用本地教学模拟估算相对风险，不证明真实账单、供应商报价或线上总成本。',
    },
    {
      id: 'latency-budget',
      title: '延迟必须绑定用户等待预算和关键路径',
      conceptIds: ['ai-risk-latency-budget', 'ai-risk-critical-path'],
      summary: '延迟不是单个模型耗时；模型、工具、检索、排队、安全检查和降级都会进入关键路径。',
      boundary: '本课只证明某条教学路径超出预算或需要降级，不证明生产 P95/P99 或真实基础设施瓶颈。',
    },
    {
      id: 'safety-control',
      title: '安全风险要有边界、拒答和升级动作',
      conceptIds: ['ai-risk-safety-boundary', 'ai-risk-safe-completion', 'ai-risk-degradation-fallback', 'ai-risk-human-escalation'],
      summary: '安全不是一句“加审核”；要定义不可回答、可安全完成、可降级和必须转人工的条件。',
      boundary: '本课不制定公司完整安全政策，只教如何把评测样本里的风险转成可审阅的控制建议。',
    },
    {
      id: 'risk-decision-table',
      title: '风险建议表把三类权衡落成行动',
      conceptIds: ['ai-risk-decision-table'],
      summary: '最终建议要同时写成本驱动、延迟驱动、安全风险、决策、产品动作和证据限制。',
      boundary: '风险建议表是进入 W11D6 综合评测的输入，不是完整综合评测报告。',
    },
  ],
  prerequisiteConceptIds: [...prerequisiteConceptIds],
  learningPaths: {
    '30': { guidedStepIndices: [0, 1, 2, 3, 4, 5], guidedRecordIndices: [0, 1, 2], exerciseCount: 3, deliverablePromptCount: 3, deliverableChecklistIndices: [0, 1, 2, 3], deliverableMinimumContributionCharacters: 180 },
    '45': { guidedStepIndices: [0, 1, 2, 3, 4, 5], guidedRecordIndices: [0, 1, 2, 3], exerciseCount: 4, deliverablePromptCount: 4, deliverableChecklistIndices: [0, 1, 2, 3, 4, 5], deliverableMinimumContributionCharacters: 280 },
  },
  primaryGoal: '能把 AI 评测中的失败或风险样本转成一张成本、延迟、安全风险建议表，并明确它能证明什么、不能证明什么。',
  scenario: {
    role: '你是产品经理，准备把会议纪要助手从内部试用推向小范围客户。',
    situation: 'W11D3 已有最小评测集，W11D4 已能分类失败来源；现在团队问：能不能上线、贵不贵、慢不慢、会不会有安全事故。',
    question: '如何在不运行真实生产系统的前提下，把本地评测样本转成成本、延迟和安全的有限风险建议？',
    stakes: '如果只写“效果不错”，团队会忽略预算、等待时间、拒答、降级和人工兜底，最后上线后才发现成本失控或安全边界不清。',
  },
  objectives: [
    { id: 'w11d5-objective-cost', text: '拆分 token、工具、重试和人工复核四类成本驱动。', evidence: '能写出每类成本在风险建议表中的字段和证据来源。' },
    { id: 'w11d5-objective-latency', text: '用用户等待预算和关键路径判断延迟风险。', evidence: '能把模型、工具、检索、安全检查和降级放入同一条耗时链。' },
    { id: 'w11d5-objective-safety', text: '区分安全边界、安全完成、拒答、降级和转人工。', evidence: '能为高风险样本写出不越界的处理动作。' },
    { id: 'w11d5-objective-deliverable', text: '提交 6 行成本延迟安全风险建议表。', evidence: '每行含风险维度、决策、产品动作、证据限制和教学模拟标记。' },
  ],
  prerequisites: [
    {
      id: 'w11d5-prereq-system-chain',
      conceptIds: [...prerequisiteConceptIds],
      prompt: '能否说明 AI 系统链、工具调用、最小评测集和失败分类表分别提供什么证据？',
      passDescription: '能把系统链、工具回执、样本合同和失败类别区分开。',
      remediationLabel: '回看 W11D1–W11D4 的系统链、工具调用、评测样本与失败分类',
      remediationTarget: '#/lesson/W11D4',
      remediation: {
        purpose: '补齐本课使用的风险输入来源，但不锁定 W11D5 全文。',
        steps: ['复述 W11D3 的 20 条样本字段。', '复述 W11D4 的六类失败来源。', '指出工具回执和模型输出的证据边界。'],
        successCheck: '能说出风险建议表不是完整综合评测报告，只是 W11D6 的输入。',
      },
    },
  ],
  concepts: [
    concept('ai-risk-token-cost', [], 'token 与生成成本驱动', 'Token cost driver', 'token 成本驱动是输入上下文、输出长度、模型档位、重试次数共同造成的单次生成成本风险。', '它让 PM 不再只问“模型多少钱”，而是能看到哪些产品设计会放大成本。', '解决“长上下文、长回答、重复生成会不会让单次服务变贵”的判断问题。', '上下文长度、输出长度、模型档位、重试策略和样本量。', '单次或单位样本的成本风险描述与优化方向。', '位于模型调用前后的预算评估层，连接上下文组装和输出交付。', '产品经理与工程共同定义预算字段，工程提供可度量计数。', '不负责证明真实账单、供应商折扣或线上流量总量。', '区别于延迟预算；成本关注资源消耗，延迟关注用户等待。', '决定是否压缩上下文、限制输出、分层模型或减少无效重试。', '“该样本 8k 输入、2k 输出、重试 2 次，成本风险高，应压缩上下文并限制复试。”', '“回答很好，所以成本一定可接受。”', ['收集 token 和重试字段。', '按单位预算判断风险等级。', '写出优化动作和证据限制。'], ['input_tokens/output_tokens/retry_count 教学模拟字段。', '单位预算或阈值是否被超过。'], ['只记录总金额不记录驱动因子。', '把一次样本估算当成真实账单。']),
    concept('ai-risk-unit-budget', ['ai-risk-token-cost'], '单位预算', 'Unit budget', '单位预算是把成本约束写成每次、每用户、每天或每千次请求的可复核上限。', '没有单位，成本讨论会在总预算、单次样本和线上流量之间混淆。', '解决“这个样本贵不贵”缺少参照的问题。', '业务场景、预计调用量、单位阈值和可接受退化策略。', '每个风险样本对应的预算状态：ok、watch、block 或需复核。', '位于产品上线门槛和评测报告之间，帮助决定是否进入试点。', '产品经理定义业务单位和门槛，财务或工程补充真实价格。', '不负责替代财务报价、采购合同或真实账单审核。', '区别于总预算；单位预算先让单个能力可被比较。', '把“高成本”改写成可执行门槛，例如每千次摘要不超过某个预算等级。', '“每千次超出教学预算，建议先降模型档位或裁剪上下文。”', '“总预算还有钱，所以单次调用不用管。”', ['选定计量单位。', '写明预算阈值。', '把样本指标映射到 ok/watch/block。'], ['unit_budget 字段。', 'budget_status 字段。'], ['预算单位不一致。', '只写贵或便宜不写阈值。']),
    concept('ai-risk-latency-budget', [], '延迟预算', 'Latency budget', '延迟预算是用户在某个场景可接受的等待上限，通常要写成首字响应、完整响应或后台完成时间。', 'AI 慢不慢必须回到用户动作和交付承诺，而不是只看模型耗时。', '解决“几秒算慢、是否需要流式、是否转后台”的产品判断问题。', '用户场景、等待上限、当前各阶段耗时和交付模式。', '延迟风险等级与推荐交付方式。', '位于用户体验验收和系统运行观察之间。', '产品经理定义等待体验，工程提供阶段耗时。', '不负责证明真实网络环境、线上 P95/P99 或基础设施容量。', '区别于成本预算；延迟关注等待和阻塞，成本关注资源消耗。', '决定是否采用流式、后台任务、缓存、并行或降级。', '“完整响应 9.8s 超出 6s 预算，应先流式给摘要并后台补引用。”', '“模型本身 2s，所以用户一定感觉快。”', ['写清用户等待上限。', '记录模型、工具和安全检查耗时。', '判断是否超预算。'], ['latency_budget_ms 与 total_latency_ms。', '各阶段耗时拆分。'], ['只看平均值。', '不区分首字和完整响应。']),
    concept('ai-risk-critical-path', ['ai-risk-latency-budget'], '关键路径', 'Critical path', '关键路径是决定用户最终等待的最长依赖链，包含必须串行完成的模型、工具、检索、安全检查和交付步骤。', '它让团队知道优化哪里才真正缩短用户等待。', '解决“哪个环节慢会拖住整次体验”的定位问题。', '阶段耗时、依赖关系、是否可并行、是否可缓存或跳过。', '最慢或最关键的延迟贡献项与优化建议。', '位于系统链观察和性能产品决策之间。', '工程识别依赖，产品经理决定是否降级或改变交付承诺。', '不负责证明数据库、网络或供应商的真实根因。', '区别于失败分类；关键路径看耗时结构，不等于失败原因。', '把“整体慢”拆成模型慢、工具慢、安全检查慢或等待串行。', '“工具回执必须等 4s 才能回答，应给等待提示或改为后台查询。”', '“总耗时长，所以一定是模型慢。”', ['画出串行和并行步骤。', '找出必须等待的最长链。', '提出缩短或降级动作。'], ['stage_latency_ms。', 'dependency=serial/parallel。'], ['把并行步骤加总。', '把一次慢样本当成生产根因。']),
    concept('ai-risk-safety-boundary', [], '安全边界', 'Safety boundary', '安全边界是产品明确不允许 AI 直接输出、执行或承诺的内容范围。', 'AI 能回答不代表产品应该交付；边界决定何时阻断、拒答或转人工。', '解决“哪些内容必须硬拦、哪些内容可以安全完成”的风险问题。', '样本类型、用户意图、敏感字段、政策等级和允许动作。', '安全风险等级、阻断规则和人工审核需求。', '位于业务规则、输出交付和审计之间。', '产品经理、法务/风控和工程共同维护边界。', '不负责制定公司完整合规政策或替代人工审核。', '区别于失败分类；安全边界即使输出正确也可能要求限制。', '定义隐私、财务、医疗、法律或不可逆动作的处理门槛。', '“用户索要他人联系方式，必须拒绝并给安全替代路径。”', '“评测集中没失败，所以安全边界可以不写。”', ['识别敏感意图。', '查边界等级。', '决定阻断、拒答、降级或人工。'], ['safety_level。', 'blocked_reason 或 allowed_scope。'], ['只靠模型自觉。', '把安全样本当作普通质量样本。']),
    concept('ai-risk-safe-completion', ['ai-risk-safety-boundary'], '安全拒答与安全完成', 'Safe completion', '安全拒答是在越界时明确不能帮助；安全完成是在边界内提供低风险、可执行的替代帮助。', '拒答不是一句“我不能”，安全完成能减少用户挫败并保留合规边界。', '解决“不能直接回答时如何仍然有帮助”的交付问题。', '安全边界、用户可接受替代路径、解释文案和下一步入口。', '拒答/安全完成策略与示例文案。', '位于输出交付层，受业务规则和安全边界约束。', '产品经理设计替代路径，审核角色确认边界。', '不负责绕过政策、判断真实身份或执行高风险动作。', '区别于人工升级；安全完成仍由系统可控交付，人工升级交给人处理。', '为隐私、危险建议、不可逆操作设计可接受回复。', '“不能提供他人隐私，但可以说明如何联系官方客服。”', '“越界请求只要换一种语气就回答。”', ['判断能否回答核心请求。', '写出拒答理由。', '提供边界内替代帮助。'], ['refusal_reason。', 'safe_alternative。'], ['拒答过于空泛。', '安全完成泄露敏感信息。']),
    concept('ai-risk-degradation-fallback', ['ai-risk-latency-budget', 'ai-risk-safety-boundary'], '降级兜底', 'Degradation fallback', '降级兜底是在成本、延迟或安全条件不满足时，改用更保守、更便宜或更可控的服务形态。', '它避免系统在风险超预算时仍强行交付高承诺结果。', '解决“不能完整回答时产品给什么”的可用性问题。', '风险类型、触发条件、备选能力、用户提示和恢复路径。', '降级策略，例如简版回答、后台处理、只给引用、关闭工具或转人工前置。', '位于输出交付前，是上线门槛和运行策略的一部分。', '产品经理定义体验，工程实现触发条件。', '不负责掩盖失败、删除审计或证明修复有效。', '区别于安全拒答；降级可用于成本、延迟和安全多种压力。', '把“失败或太慢”改成可预期的有限服务。', '“工具超时则提示后台处理中，并保留 callId 给人工复核。”', '“超预算也继续重试直到成功。”', ['检测触发条件。', '选择保守能力。', '记录用户提示和审计。'], ['fallback_trigger。', 'fallback_action。'], ['无上限重试。', '降级后仍承诺完整成功。']),
    concept('ai-risk-human-escalation', ['ai-risk-degradation-fallback', 'ai-risk-safe-completion'], '人工升级', 'Human escalation', '人工升级是把高风险、不确定或不可自动处理的请求交给具备权限和责任的人，并附带必要证据。', '它让 AI 系统在边界外停止自动决策，而不是继续生成看似确定的答案。', '解决“哪些样本必须由人接手、交接什么证据”的责任问题。', '风险等级、用户影响、可见证据、历史尝试和人工处理入口。', '升级条件、交接字段和 SLA 建议。', '位于输出交付和运营流程之间。', '产品经理定义升级门槛，运营和客服团队承接。', '不负责让模型自行执行人工权限或证明人工处理结果。', '区别于降级；降级仍自动交付，人工升级把责任转给人。', '为财务纠纷、隐私投诉和高价值客户异常设定转人工门槛。', '“涉及退款争议且工具回执未知，带 callId 和用户证据转人工。”', '“AI 生成一句‘已处理’就等于人工完成。”', ['判断自动处理是否越界。', '收集最小交接证据。', '提交人工队列并说明 SLA。'], ['escalation_reason。', 'handoff_evidence。'], ['没有证据就转人工。', '该转人工时继续自动承诺。']),
    concept('ai-risk-decision-table', ['ai-risk-token-cost', 'ai-risk-unit-budget', 'ai-risk-latency-budget', 'ai-risk-critical-path', 'ai-risk-safety-boundary', 'ai-risk-safe-completion', 'ai-risk-degradation-fallback', 'ai-risk-human-escalation'], '成本延迟安全风险建议表', 'Risk decision table', '风险建议表是把每条评测样本的成本驱动、延迟驱动、安全风险、决策、产品动作和证据限制写成可审阅记录。', '它把质量评测从“答得好不好”推进到“是否可上线、如何降级、何时转人工”。', '解决评测报告缺少风险建议和上线门槛的问题。', '样本事实、失败分类、成本字段、延迟字段、安全字段和业务优先级。', '每行风险分类、建议动作、阻断/观察/试点决策和证据限制。', '位于 W11D6 综合评测报告之前，作为风险建议输入。', '产品经理负责表格结构和建议，评审人确认是否进入试点。', '不负责替代 W11D6 综合评测、真实生产监控或最终上线审批。', '区别于失败分类表；失败分类说明哪里错，风险建议表说明成本、延迟、安全怎么处理。', '评审 AI 客服试点范围、风险门槛和上线前修正项。', '“latency_budget_breach + safety_policy_block → block，先安全拒答并转人工。”', '“通过 20 条样本，所以直接全量上线。”', ['合并样本与分类。', '填写三类风险字段。', '给出决策与证据限制。'], ['decision=allow/watch/block/escalate。', 'evidence_limit 含教学模拟边界。'], ['只写结论不写字段。', '把风险建议表当完整验收报告。']),
  ],
  diagram: {
    title: '成本延迟安全风险链',
    caption: '同一条 AI 评测样本先进入成本预算、延迟预算和安全边界，再决定允许、观察、降级、阻断或人工升级。',
    nodes: [
      { id: 'eval-case', label: '评测样本', description: '来自 W11D3/W11D4 的可复现样本和失败分类。', input: 'case_id、expected_behavior、observed_output、failure_category', output: '待评估风险行', owner: '产品经理', evidence: '教学模拟样本字段' },
      { id: 'cost', label: '成本预算', description: '读取 token、工具、重试和复核成本驱动。', input: 'tokens、tool_calls、retry_count', output: 'cost_status', owner: '产品与工程' },
      { id: 'latency', label: '延迟预算', description: '读取阶段耗时和用户等待上限。', input: 'stage_latency_ms、budget_ms', output: 'latency_status', owner: '产品与工程' },
      { id: 'safety', label: '安全边界', description: '判断是否需要拒答、安全完成、降级或转人工。', input: 'safety_level、policy_boundary', output: 'safety_status', owner: '产品、风控和审核' },
      { id: 'decision', label: '风险建议', description: '综合三类风险给出 allow/watch/block/escalate。', input: '三类状态与证据限制', output: 'risk_decision', owner: '产品经理' },
    ],
    branches: [
      { from: 'eval-case', to: 'cost', label: '估算成本驱动', kind: 'normal' },
      { from: 'eval-case', to: 'latency', label: '检查等待预算', kind: 'normal' },
      { from: 'eval-case', to: 'safety', label: '检查安全边界', kind: 'normal' },
      { from: 'cost', to: 'decision', label: '超单位预算则观察或阻断', kind: 'failure' },
      { from: 'latency', to: 'decision', label: '超等待预算则降级', kind: 'failure' },
      { from: 'safety', to: 'decision', label: '越界则拒答或转人工', kind: 'failure' },
    ],
    evidenceNotes: ['所有数字都是本地教学模拟字段。', '本图不能证明真实账单、线上 P95 或完整合规结论。'],
  },
  demonstration: {
    title: '教师示范：把 6 条风险样本转成建议',
    businessProblem: '会议纪要助手样本已经知道失败类别，但团队还不知道哪些要控成本、哪些要降级、哪些必须阻断或转人工。',
    finalConclusion: '6 条样本分别形成 allow、watch、degrade、block、escalate 等建议，但都保留教学模拟与生产证据限制。',
    conclusionLimit: '示范只能证明风险建议表结构可用，不能证明真实生产成本、延迟分布、安全政策充分或上线可批。',
    steps: [
      { title: '固定样本和分类', action: '选取 6 条教学模拟样本，保留 case_id 与 failure_category。', reason: '风险建议必须接在可复现样本后面。', evidence: 'case_id 与 failure_category 字段齐全。', proves: '输入可追溯。', limitation: '不能证明线上代表性。' },
      { title: '读取成本驱动', action: '记录 tokens、tool_calls、retry_count 和 review_minutes。', reason: '成本需要拆因子而不是只写“贵”。', evidence: 'cost_driver 字段完整。', proves: '能定位成本压力来源。', limitation: '不能证明真实账单。' },
      { title: '读取延迟关键路径', action: '比较 total_latency_ms 与 latency_budget_ms，标出最慢串行阶段。', reason: '延迟建议要知道用户等在哪里。', evidence: 'critical_path 字段写出模型、工具或安全检查。', proves: '能识别超预算样本。', limitation: '不能证明生产 P95。' },
      { title: '检查安全边界', action: '把隐私、不可逆操作和不确定工具回执标为安全风险。', reason: '安全风险可以阻断其他优化建议。', evidence: 'safety_risk 与 boundary_action 字段。', proves: '能把越界请求转成控制动作。', limitation: '不能替代正式合规审核。' },
      { title: '给出产品动作', action: '为每行写 allow、watch、degrade、block 或 escalate。', reason: '评测结论必须能推动下一步。', evidence: 'decision 与 product_action 字段。', proves: '建议可执行。', limitation: '不能证明修复已经发生。' },
      { title: '写清证据限制', action: '每行 evidence_limit 都写“教学模拟”，并列出还缺的真实证据。', reason: '避免把本地样本伪装成生产证据。', evidence: 'evidence_limit 字段含教学模拟和缺口。', proves: '报告边界诚实。', limitation: '不能替代 W11D6 综合评测报告。' },
    ],
  },
  guidedLab: {
    title: '成本延迟安全六路径教学模拟',
    goal: '通过六条本地教学模拟观察成本超预算、工具重试成本、延迟超预算、超时降级、安全阻断和人工升级。',
    safety: '不调用真实模型、工具、账号、Token、公司数据、生产账单或生产日志；所有输出都必须标注“教学模拟”。',
    conceptIds: [...conceptIds],
    predictionPrompt: '先预测六条路径里哪一条应该 allow、watch、degrade、block 或 escalate，并写出理由。',
    steps: [
      { title: 'token_budget_exceeded', action: '运行长上下文摘要样本，观察 input_tokens=9000、output_tokens=2200。', observe: 'cost_driver=token_over_budget，decision=watch。', explanation: 'token 成本驱动超过单位预算，但安全和延迟未阻断，可先压缩上下文。', proves: '能证明教学样本存在 token 成本风险。', cannotProve: '不能证明真实账单或线上平均成本。' },
      { title: 'tool_retry_cost', action: '运行工具重试样本，观察 tool_calls=3、retry_count=2。', observe: 'cost_driver=tool_retry_cost，decision=watch。', explanation: '工具重试会同时增加成本和延迟，应设置重试上限。', proves: '能证明本地路径展示重试成本压力。', cannotProve: '不能证明真实工具稳定性。' },
      { title: 'latency_budget_breach', action: '运行慢模型样本，观察 total_latency_ms=9800、latency_budget_ms=6000。', observe: 'latency_driver=model_generation，decision=degrade。', explanation: '用户等待超预算，应采用流式、简版或后台交付。', proves: '能证明教学路径超出设定等待预算。', cannotProve: '不能证明生产 P95/P99。' },
      { title: 'timeout_degradation', action: '运行工具超时样本，观察 receipt=TOOL_TIMEOUT_UNKNOWN、callId=sim-305。', observe: 'latency_driver=tool_timeout，decision=degrade。', explanation: '未知回执不能承诺成功，应降级为后台查询并保留 callId。', proves: '能证明降级兜底比继续承诺更安全。', cannotProve: '不能证明真实业务动作是否完成。' },
      { title: 'safety_policy_block', action: '运行隐私请求样本，观察 safety_level=high、policy_boundary=private_data。', observe: 'safety_risk=privacy_boundary，decision=block。', explanation: '越过安全边界时应拒答并给安全替代路径。', proves: '能证明教学样本触发安全阻断条件。', cannotProve: '不能替代正式合规政策。' },
      { title: 'human_escalation', action: '运行退款争议样本，观察 high_value=true、tool_receipt_unknown=true。', observe: 'safety_risk=financial_dispute，decision=escalate。', explanation: '高影响且工具回执不确定，应把证据交给人工处理。', proves: '能证明人工升级字段与交接证据完整。', cannotProve: '不能证明人工最终处理结果。' },
    ],
    recordPrompts: [
      '记录一条成本风险：cost_driver、unit_budget、decision、不能证明什么。',
      '记录一条延迟风险：latency_driver、critical_path、fallback_action、不能证明什么。',
      '记录一条安全风险：safety_risk、boundary_action、human_escalation 条件、不能证明什么。',
      '对比 watch、degrade、block、escalate 四种决策在产品动作上的区别。',
    ],
    comparePrompt: '比较六条路径：哪些由成本触发，哪些由延迟触发，哪些由安全直接阻断，哪些需要人工升级？',
    passCriteria: [
      '六条路径均运行并记录为教学模拟。',
      '每条路径都写出能证明和不能证明的边界。',
      '至少一条成本、一条延迟、一条安全、一条人工升级建议完整。',
      '没有把本地教学模拟写成真实生产账单、生产 P95 或正式合规结论。',
    ],
  },
  independentLab: {
    title: '会议纪要助手试点风险建议变式',
    scenario: '把同一套方法迁移到“客户会议纪要自动总结”的试点评审，样本中包含长录音摘要、工具超时、隐私字段和高价值客户投诉。',
    conceptIds: [...conceptIds],
    changedConditions: ['用户等待预算从 6 秒变成 3 秒。', '隐私字段从普通姓名变成手机号和合同金额。', '高价值客户投诉必须人工接手。'],
    task: '写出 3 条风险建议，至少覆盖成本、延迟、安全，并给出是否 allow/watch/degrade/block/escalate。',
    predictionPrompt: '先预测哪一条最可能阻断试点，哪一条可以通过降级继续推进。',
    evidenceRequirements: [
      '每条建议都有成本、延迟或安全的明确触发证据。',
      '每条建议都写清教学模拟能证明和不能证明什么。',
      '至少一条建议包含人工升级条件和交接证据。',
    ],
    passCriteria: [
      '三类风险至少各出现一次。',
      '决策与触发证据一致。',
      '没有提前写成 W11D6 综合评测报告。',
      '没有声称真实生产账单、线上延迟分布或正式合规结论已证明。',
    ],
    remediation: { label: '回到成本、延迟、安全边界重新拆分', sectionId: 'concepts', anchor: 'concept-ai-risk-decision-table' },
  },
  exercises: [
    exercise('w11d5-cost-driver', ['概念与边界', '证据判断'], ['ai-risk-token-cost', 'ai-risk-unit-budget'], '某样本 input_tokens=12000、retry_count=0、total_latency_ms 正常。最合理的风险建议是什么？', ['成本风险 watch，先压缩上下文或改分层模型；不能证明真实账单', '延迟风险 block，因为 token 多一定慢', '安全风险 escalate，因为上下文长一定泄露隐私'], 0, 'token 数直接进入成本驱动，但不自动证明延迟或安全事故。', '回看成本驱动与单位预算'),
    exercise('w11d5-latency-path', ['机制推演'], ['ai-risk-latency-budget', 'ai-risk-critical-path', 'ai-risk-degradation-fallback'], 'total_latency_ms=9800，budget=6000，最慢串行阶段是 tool_timeout。下一步最克制的是？', ['继续无限重试直到成功', '降级为后台处理，保留 callId，并说明不确定状态', '直接宣布业务动作失败'], 1, '工具超时未知应降级并保留证据，不能承诺成功或失败。', '回看关键路径与降级兜底'),
    exercise('w11d5-safety-boundary', ['工作场景'], ['ai-risk-safety-boundary', 'ai-risk-safe-completion'], '用户要求输出他人手机号，评测样本 response 很流畅。应如何处理？', ['标记安全阻断，拒绝泄露并提供合规联系路径', '因为回答流畅所以 allow', '只把温度调低再回答'], 0, '安全边界高于流畅度，越界内容必须阻断并安全完成。', '回看安全边界与安全完成'),
    exercise('w11d5-decision-table', ['综合变式'], ['ai-risk-decision-table', 'ai-risk-human-escalation'], '高价值退款争议，工具回执未知且用户影响大。风险建议表最关键字段是什么？', ['decision=escalate，handoff_evidence 包含 callId、用户影响和证据限制', 'decision=allow，因为模型可以安抚用户', '只写“需要优化体验”'], 0, '人工升级要有明确触发、证据交接和责任边界。', '回看人工升级与风险建议表'),
  ],
  deliverable: {
    title: '成本延迟安全风险建议表',
    conceptIds: [...conceptIds],
    purpose: '把评测样本从质量失败推进到上线风险建议，帮助团队决定 allow、watch、degrade、block 或 escalate。',
    whenToUse: '用于 W11D6 综合评测前，给成本、延迟、安全风险补齐门槛和行动建议。',
    audience: '产品经理、工程、审核/风控、运营负责人。',
    fields: [
      { name: 'case_id', meaning: '样本唯一标识', source: 'W11D3/W11D4 样本或本课教学模拟' },
      { name: 'cost_driver', meaning: 'token、工具、重试或人工复核成本来源', source: '本课成本字段' },
      { name: 'latency_driver', meaning: '模型、工具、检索、安全检查或排队耗时来源', source: '本课延迟字段' },
      { name: 'safety_risk', meaning: '隐私、不可逆动作、高影响争议或无安全风险', source: '本课安全边界判断' },
      { name: 'decision', meaning: 'allow、watch、degrade、block 或 escalate', source: '三类风险综合判断' },
      { name: 'product_action', meaning: '下一步产品动作', source: 'PM 建议' },
      { name: 'evidence_limit', meaning: '教学模拟能证明与不能证明什么', source: '证据边界' },
    ],
    badExample: '{"case_id":"sim-1","decision":"上线","product_action":"效果不错，可以全量上线"}',
    badReasons: ['没有成本、延迟、安全字段。', '没有教学模拟证据边界。', '把风险建议表写成完整上线审批。'],
    revisionSteps: ['补齐三类风险字段。', '把 decision 限定为 allow/watch/degrade/block/escalate。', '每行写出 evidence_limit 和教学模拟。', '把完整综合结论留给 W11D6。'],
    goodExample: '{"case_id":"risk-001","cost_driver":"token_budget_exceeded","latency_driver":"none","safety_risk":"none","decision":"watch","product_action":"压缩上下文并设置单次 token budget","evidence_limit":"教学模拟只证明该样本超出单位预算，不能证明真实账单或线上总成本"}',
    guidedPrompts: [
      '先写 2 行成本风险：token 超预算与工具重试成本。',
      '再写 2 行延迟风险：慢模型与工具超时降级。',
      '再写 1 行安全阻断与 1 行人工升级。',
      '逐行检查 evidence_limit 是否写明教学模拟和缺失的生产证据。',
    ],
    blankTemplate: [
      '{"case_id":"","cost_driver":"","latency_driver":"","safety_risk":"","decision":"","product_action":"","evidence_limit":"教学模拟：能证明；不能证明"}',
    ].join('\n'),
    standardTemplate: [
      '{"case_id":"risk-001","cost_driver":"token_budget_exceeded","latency_driver":"none","safety_risk":"none","decision":"watch","product_action":"压缩上下文并设置单次 token budget","evidence_limit":"教学模拟只证明该样本超出单位预算，不能证明真实账单或线上总成本"}',
      '{"case_id":"risk-002","cost_driver":"tool_retry_cost","latency_driver":"tool_retry","safety_risk":"none","decision":"watch","product_action":"设置工具重试上限并记录失败回执","evidence_limit":"教学模拟只证明重试会放大成本和延迟，不能证明真实工具稳定性"}',
      '{"case_id":"risk-003","cost_driver":"none","latency_driver":"latency_budget_breach","safety_risk":"none","decision":"degrade","product_action":"改为流式首答或后台补全","evidence_limit":"教学模拟只证明超出 6 秒等待预算，不能证明生产 P95"}',
      '{"case_id":"risk-004","cost_driver":"tool_retry_cost","latency_driver":"timeout_degradation","safety_risk":"uncertain_tool_receipt","decision":"degrade","product_action":"提示后台处理中并保留 callId","evidence_limit":"教学模拟只证明回执未知时不能承诺成功，不能证明真实业务动作结果"}',
      '{"case_id":"risk-005","cost_driver":"none","latency_driver":"none","safety_risk":"safety_policy_block","decision":"block","product_action":"拒绝泄露隐私并提供安全替代路径","evidence_limit":"教学模拟只证明触发隐私边界，不能替代正式合规审核"}',
      '{"case_id":"risk-006","cost_driver":"manual_review","latency_driver":"human_queue","safety_risk":"human_escalation","decision":"escalate","product_action":"携带证据转人工处理并说明 SLA","evidence_limit":"教学模拟只证明应转人工，不能证明人工处理结果"}',
    ].join('\n'),
    checklist: [
      '恰好 6 行 JSONL，每行可解析。',
      '六类路径 token_budget_exceeded、tool_retry_cost、latency_budget_breach、timeout_degradation、safety_policy_block、human_escalation 均出现。',
      'decision 只使用 allow/watch/degrade/block/escalate。',
      '每行都有 product_action。',
      '每行 evidence_limit 都含“教学模拟”并写明不能证明什么。',
      '没有写成 W11D6 综合评测报告或正式上线审批。',
    ],
  },
  memory: {
    conceptIds: [...conceptIds],
    anchors: ['成本看驱动因子和单位预算。', '延迟看用户等待预算和关键路径。', '安全边界可直接阻断成本和延迟优化。', '风险建议表是 W11D6 的输入，不是完整报告。'],
    closedBookPrompt: '闭卷复述九个首次教学概念，并用一条样本说明如何从成本、延迟、安全得出 decision。',
    microOperation: '把一个已有失败样本补成一行风险建议 JSONL。',
    unresolvedPrompt: '还有哪些真实生产证据需要在 W11D6 或上线前补齐？',
    reviewStages: [
      { stage: 'D1', task: '闭卷写出成本、延迟、安全三类风险各自至少两个字段。' },
      { stage: 'D3', task: '把一条工具超时样本改写成 degrade 或 escalate 建议。' },
      { stage: 'D7', task: '检查一行风险建议是否把教学模拟误写成生产证据。' },
      { stage: 'D14', task: '为一条隐私样本写安全拒答和安全完成动作。' },
      { stage: 'D30', task: '比较 watch、degrade、block、escalate 的使用条件。' },
      { stage: 'D60', task: '用风险建议表解释为什么 W11D6 还需要综合评测。' },
    ],
  },
  nextLesson: {
    id: 'W11D6',
    title: '评测 AI 客服',
    bridge: '下一课才把最小评测集、失败分类和风险建议合并成完整综合评测报告。',
  },
}
