import type { DailyCourse } from './types'

const conceptIds = [
  'ai-feature-system',
  'ai-request-context',
  'model-generation-boundary',
  'ai-capability-slots-overview',
  'ai-policy-orchestration',
  'ai-output-handoff',
  'ai-observation-audit',
] as const

const prerequisiteConceptIds = [
  'http-request',
  'http-response',
  'api-entry',
  'backend-service',
  'business-rule',
  'network-evidence-boundary',
]

export const w11d1: DailyCourse = {
  id: 'W11D1',
  contentVersion: 'w11d1-ai-system-chain-day01-v1',
  week: 11,
  day: 1,
  title: 'AI 功能不是一个 Prompt',
  subtitle: '把一次 AI 功能拆成输入、上下文、模型、能力槽位、业务规则、输出与审计，先看懂系统，再讨论局部优化。',
  duration: { core: 30, standard: 45, extension: 36, full: 84 },
  coreConceptGroups: [
    {
      id: 'ai-request-and-generation',
      title: '请求进入模型前，系统已经做了很多工作',
      conceptIds: ['ai-feature-system', 'ai-request-context', 'model-generation-boundary'],
      summary: 'AI 功能先接收产品请求、组装本次上下文，再让模型基于可见输入生成候选内容；Prompt 只是上下文包的一部分。',
      boundary: '模型输出是候选结果，不自动等于事实正确、业务允许或真实动作已经发生。',
    },
    {
      id: 'ai-capabilities-and-policy',
      title: '能力槽位与业务决策分开',
      conceptIds: ['ai-capability-slots-overview', 'ai-policy-orchestration'],
      summary: '知识来源槽位与外部动作槽位扩展系统能力，业务规则决定何时允许使用、何时拒绝、何时降级。',
      boundary: '本课只定位 RAG 与工具所在槽位；检索机制、工具鉴权、真实副作用分别留到后续课程首次教学。',
    },
    {
      id: 'ai-handoff-and-audit',
      title: '用户看到回复之前，还需要交付与追溯',
      conceptIds: ['ai-output-handoff', 'ai-observation-audit'],
      summary: '系统检查候选输出、选择展示或转人工，并为同一次运行留下可关联的阶段状态和有限结论。',
      boundary: '一条审计记录只能说明本次系统经过哪些阶段，不能凭单样本证明长期质量或模型掌握。',
    },
  ],
  prerequisiteConceptIds,
  learningPaths: {
    '30': {
      guidedStepIndices: [0, 1, 2, 3, 4, 5],
      guidedRecordIndices: [0, 1, 2],
      exerciseCount: 3,
      deliverablePromptCount: 4,
      deliverableChecklistIndices: [0, 1, 2, 3],
      deliverableMinimumContributionCharacters: 90,
    },
    '45': {
      guidedStepIndices: [0, 1, 2, 3, 4, 5],
      guidedRecordIndices: [0, 1, 2, 3],
      exerciseCount: 4,
      deliverablePromptCount: 6,
      deliverableChecklistIndices: [0, 1, 2, 3, 4, 5],
      deliverableMinimumContributionCharacters: 130,
    },
  },
  primaryGoal: '独立画出一条 AI 功能系统链，逐层写清输入、输出、责任、失败与证据边界，并提交可评审的 AI 系统链路说明。',
  scenario: {
    role: '你是负责“智能客服答疑”需求评审的产品经理，只使用脱敏教学模拟。',
    situation: '团队把需求写成“给模型一段 Prompt，让它回答用户并在需要时处理退款”。研发、客服和安全同学分别担心资料过期、越权动作、错误回复与无法追溯。',
    question: '如果 AI 功能不是一个 Prompt，它至少由哪些系统阶段协作？每一层失败时，产品经理应看到什么证据并把结论停在哪里？',
    stakes: '只讨论 Prompt 会遗漏资料、权限、规则、降级和审计；把模型说了什么当成系统做了什么，会造成错误上线判断和高风险副作用。',
  },
  objectives: [
    { id: 'w11d1-objective-map', text: '画出 AI 功能的端到端系统链', evidence: '按顺序标出请求、上下文、模型、能力槽位、规则、交付与审计。' },
    { id: 'w11d1-objective-own', text: '逐层说明责任与输入输出', evidence: '为每层写出负责什么、不负责什么，以及上下游交接对象。' },
    { id: 'w11d1-objective-fail', text: '用分层证据定位一次失败', evidence: '运行四类教学变式，记录最后成功阶段、首次失败阶段和有限结论。' },
    { id: 'w11d1-objective-deliver', text: '形成可评审的链路说明', evidence: '提交包含场景、链路、门槛、降级、审计和未知事项的独立成果。' },
  ],
  prerequisites: [
    {
      id: 'w11d1-request-service-readiness',
      conceptIds: ['http-request', 'http-response', 'api-entry', 'backend-service', 'business-rule'],
      prompt: '你能把一次产品请求从 HTTP Request 讲到 API、后端业务规则与 Response，并区分“进入处理”和“业务成功”吗？',
      passDescription: '能说清请求输入、服务端处理、规则决策与返回结果是不同阶段，且每层证据强度不同。',
      remediationLabel: '补学 W1D3–W1D4：请求与服务链',
      remediationTarget: '#/lesson/W1D4',
      remediation: {
        purpose: 'AI 功能仍然运行在普通软件系统中；先会读请求与业务服务，才能看懂模型只是其中一层。',
        steps: ['回到 W1D3 复述 Request 与 Response。', '回到 W1D4 画出 API、后端规则与返回链。', '用一次规则拒绝写出“到达了什么、还没发生什么”。'],
        successCheck: '闭卷讲出 Request → API → 业务服务／规则 → Response，并在三处主动保留证据边界。',
      },
    },
    {
      id: 'w11d1-evidence-readiness',
      conceptIds: ['network-evidence-boundary'],
      prompt: '你能把一次浏览器观察写成“看到／可以推断／还不能证明／下一步”，而不是直接猜内部根因吗？',
      passDescription: '能引用同一次运行的原始字段，说明有限判断，并给出需要补充的下一层证据。',
      remediationLabel: '补学 W1D5：证据边界',
      remediationTarget: '#/lesson/W1D5',
      remediation: {
        purpose: 'AI 系统失败跨越多个阶段，先守住证据边界，才不会把一次回复错误都归因给模型。',
        steps: ['回到 W1D5 复述四句有限结论。', '挑一条教学请求区分原始观察与推断。', '补写一个不需要生产权限的下一步证据。'],
        successCheck: '面对单条失败样本，能先定位最后成功与首次失败阶段，再提出下一步取证。',
      },
    },
  ],
  concepts: [
    {
      id: 'ai-feature-system', prerequisiteConceptIds: ['api-entry', 'backend-service'],
      term: 'AI 功能系统', english: 'AI-enabled Product System',
      definition: '围绕一个用户任务，把普通软件服务、上下文组装、模型生成、能力接入、业务规则、交付与审计组合起来的完整产品系统。',
      why: '用户体验来自整条链共同作用，任何一层都可能改变最终结果；只优化 Prompt 无法覆盖系统责任。',
      problemSolved: '把“模型回答不好”的模糊问题拆成可以定位、验证、分工和降级的系统问题。',
      input: '用户请求、产品状态、允许使用的上下文、业务策略以及可用能力配置。',
      output: '经过业务约束的回复、拒绝、澄清、降级或人工交接结果，以及对应运行记录。',
      systemPosition: '位于用户界面与多个后端能力之间，是一次 AI 产品请求的整体边界。',
      process: ['接收并识别一次用户任务。', '依次经过上下文、生成、能力、规则、交付与审计阶段。', '任一阶段失败时按策略拒绝、降级或转人工。'],
      owner: '跨产品、应用研发、算法、数据、安全与运营协作负责，不能只归给模型团队。',
      notResponsibleFor: '系统结构本身不保证回答正确，也不证明模型、资料或工具已经达到上线质量。',
      compareWith: 'Prompt 是系统向模型提供的一部分输入；AI 功能系统还包含模型前后的软件与业务控制。',
      evidence: ['同一次运行的阶段状态与关联标识。', '请求、候选输出、规则结果和最终交付之间的可追溯关系。'],
      failureModes: ['只记录最终文案，无法知道失败发生在哪一层。', '模型输出直接进入业务动作，绕过规则与确认。'],
      pmUse: '需求评审时先画系统链，再为每个阶段定义责任、门槛、失败与兜底。',
      correctExample: '客服请求经过上下文组装、模型候选、退款规则检查后只返回说明，并在高风险动作前要求人工确认。',
      incorrectExample: '把“写一个更强 Prompt”当成资料过期、越权动作和审计缺失的共同解决方案。',
    },
    {
      id: 'ai-request-context', prerequisiteConceptIds: ['ai-feature-system', 'http-request'],
      term: '请求与上下文包', english: 'Request and Context Package',
      definition: '系统在本次运行中交给模型的任务说明、对话片段、结构化状态、允许使用的资料摘要与输出约束集合。',
      why: '模型只能依据本次可见输入生成；缺字段、旧状态或冲突信息会在生成前就限制结果。',
      problemSolved: '把“用户说了什么”和“系统实际给模型看了什么”分开，方便检查输入完整性。',
      input: '用户本次问题、必要历史、脱敏产品状态、业务指令和允许的知识片段。',
      output: '一份有来源、有范围、有长度限制的本次模型输入包。',
      systemPosition: '位于产品请求进入模型之前，由应用层依据场景组装。',
      process: ['接收用户问题并识别所需字段。', '选择必要且获准的上下文。', '标记缺失、冲突或敏感内容后再交给模型。'],
      owner: '应用服务与产品规则负责选择和组装；模型只消费收到的输入。',
      notResponsibleFor: '上下文包不能保证来源真实、检索正确或模型一定遵守其中每条要求。',
      compareWith: '用户输入只是原始请求；上下文包是系统加工后真正提交给模型的完整输入。',
      evidence: ['脱敏后的上下文字段清单与来源标签。', '缺失字段、裁剪、冲突和敏感过滤的阶段记录。'],
      failureModes: ['订单状态未进入上下文，却要求模型解释退款结果。', '把无关长历史全部塞入，挤占关键任务信息。'],
      pmUse: '评审“答非所问”时，先确认本次模型到底看到了哪些可用输入。',
      correctExample: '请求包包含问题、脱敏订单状态和回复格式，并明确缺少付款渠道时先追问。',
      incorrectExample: '用户页面上能看到订单号，就默认模型也一定收到了同一个字段。',
    },
    {
      id: 'model-generation-boundary', prerequisiteConceptIds: ['ai-request-context'],
      term: '模型生成边界', english: 'Model Generation Boundary',
      definition: '模型基于本次上下文生成候选内容的阶段边界；它输出文本或结构化候选，不自动承担业务事实确认与动作提交。',
      why: '自然语言很像最终答案，容易让团队忽略它仍需规则检查、来源验证和交付控制。',
      problemSolved: '把“模型建议”与“系统决定／真实结果”分开，避免语言流畅掩盖证据不足。',
      input: '经过组装的上下文包和模型运行配置。',
      output: '候选回复、结构化字段或拒答信号，以及本次生成状态。',
      systemPosition: '位于上下文组装之后、业务规则与最终交付之前。',
      process: ['接收限定范围的上下文。', '生成候选内容或结构化结果。', '把候选交回应用层继续检查与决策。'],
      owner: '模型服务负责生成过程；应用系统负责决定候选是否可以使用。',
      notResponsibleFor: '不直接证明资料最新、业务规则满足、外部动作成功或用户问题已经解决。',
      compareWith: '模型输出像草稿；最终产品结果还要经过规则、动作结果与交付策略。',
      evidence: ['候选输出与生成状态。', '本次模型版本或配置的非敏感关联信息。'],
      failureModes: ['候选内容流畅但引用了上下文中不存在的事实。', '结构化字段缺失导致后续规则无法判断。'],
      pmUse: '验收时把生成质量单独测量，不用最终业务成功率替代模型层证据。',
      correctExample: '模型生成“可能符合退款条件”，系统随后检查订单状态并决定是否展示或转人工。',
      incorrectExample: '模型说“退款已完成”，团队就把它当成支付系统已经执行的证据。',
    },
    {
      id: 'ai-capability-slots-overview', prerequisiteConceptIds: ['ai-feature-system'],
      term: '知识与动作能力槽位（总览）', english: 'Knowledge and Action Slots Overview',
      definition: 'AI 系统中用于补充外部知识或请求外部动作的两个能力位置；本课只识别其所在阶段与风险方向。',
      why: '模型自身不等于企业知识库，也不等于能直接修改业务数据；两类能力必须在系统图上分开。',
      problemSolved: '防止把“查资料”和“做动作”混成一个模糊的 AI 能力，遗漏完全不同的证据与风险。',
      input: '知识槽位接收待补充的信息需求；动作槽位接收经过规则允许的结构化动作意图。',
      output: '知识槽位返回候选资料片段；动作槽位返回请求状态或结果，具体机制留待后续首教。',
      systemPosition: '作为模型前后可选能力接点，由应用编排而不是默认永久开启。',
      process: ['先判断本次任务是否需要外部知识或动作。', '把两类能力放到不同阶段并记录调用状态。', '失败时降级、追问或转人工。'],
      owner: '应用编排层决定是否接入；后续课程分别定义检索与工具的具体责任。',
      notResponsibleFor: '本总览不解释 RAG 召回排序，也不授予工具权限，更不执行任何真实业务动作。',
      compareWith: '知识槽位回答“给模型哪些外部材料”，动作槽位回答“是否请求外部系统做事”。',
      evidence: ['能力槽位是否被启用及返回状态。', '失败后系统采取的降级、拒绝或人工交接。'],
      failureModes: ['检索失败却继续生成确定性答案。', '没有业务确认就让模型发起高风险动作。'],
      pmUse: '在系统方案中先把 RAG 与工具分栏标注，后续再分别评审机制、权限和质量。',
      correctExample: '资料不足时进入知识槽位；退款动作进入独立动作槽位并等待后续权限与确认设计。',
      incorrectExample: '写“接入 RAG 和工具即可解决准确性”，却不区分资料、动作、规则和失败。',
    },
    {
      id: 'ai-policy-orchestration', prerequisiteConceptIds: ['business-rule', 'model-generation-boundary', 'ai-capability-slots-overview'],
      term: '业务规则与编排', english: 'Policy and Orchestration',
      definition: '应用系统依据风险、资料状态、候选输出和业务条件，决定继续、追问、拒绝、降级或转人工的控制阶段。',
      why: '模型擅长生成候选，但产品必须用确定性规则守住权限、必填字段与高风险动作门槛。',
      problemSolved: '把重要产品承诺写成可审核的决策点，而不是期待模型自行记住所有限制。',
      input: '候选输出、上下文完整性、能力返回状态、用户权限和场景风险等级。',
      output: '允许交付、需要澄清、明确拒绝、降级结果或人工接管决定。',
      systemPosition: '位于能力使用与最终输出之间，也可以在调用能力前执行前置门禁。',
      process: ['检查必填信息和允许范围。', '应用风险与权限门槛。', '选择交付、拒绝、降级或人工路径。'],
      owner: '业务产品、安全、法务与应用研发共同定义，应用服务可执行地落实。',
      notResponsibleFor: '规则不能修复模型所有表达错误，也不能代替后续评测与线上监控。',
      compareWith: 'Prompt 是给模型的指令；业务规则是系统必须执行、可测试和可审计的控制。',
      evidence: ['命中的规则编号与决策结果。', '拒绝、降级或转人工的明确原因码。'],
      failureModes: ['只在 Prompt 里写“不要退款”，没有系统动作门禁。', '规则失败后仍把候选内容直接展示给用户。'],
      pmUse: '把不可越过的上线要求写成系统门槛，并为每个门槛设计失败结果。',
      correctExample: '付款渠道缺失时系统先追问；高风险退款只生成说明并转人工，不发起真实动作。',
      incorrectExample: '候选回复包含“已退款”，应用层不检查任何业务状态就直接展示。',
    },
    {
      id: 'ai-output-handoff', prerequisiteConceptIds: ['ai-policy-orchestration'],
      term: '输出交付与人工兜底', english: 'Output Delivery and Human Handoff',
      definition: '系统把规则通过的候选转换成用户可见结果，或在资料、能力、风险不满足时交给人工继续处理的阶段。',
      why: '同一个候选在不同风险和证据条件下，可能应该展示、改写、拒绝或转人工。',
      problemSolved: '让失败不等于无响应，并让用户知道当前状态、下一步和责任人。',
      input: '候选输出、规则结果、能力状态、风险等级和可用人工通道。',
      output: '带状态的用户回复、澄清问题、拒绝说明、降级结果或人工工单引用。',
      systemPosition: '位于一次 AI 请求的产品交付端，连接用户体验与运营处理。',
      process: ['根据规则选择交付类型。', '说明当前能做与不能做的事项。', '必要时建立人工接管并返回可追踪状态。'],
      owner: '产品体验、客服运营与应用研发共同负责交付协议和人工承接。',
      notResponsibleFor: '转人工不自动证明问题解决，也不能掩盖前面阶段的系统性失败。',
      compareWith: '模型候选是内部中间结果；输出交付是用户实际收到、可继续行动的产品结果。',
      evidence: ['最终交付类型与展示内容。', '人工接管状态、原因与非敏感关联标识。'],
      failureModes: ['系统失败时只显示“未知错误”，没有恢复路径。', '转人工后没有状态，用户重复提交同一问题。'],
      pmUse: '为资料不足、能力失败和高风险场景分别设计可行动的兜底体验。',
      correctExample: '资料不足时明确说明缺少哪个字段，并提供补充入口或人工处理编号。',
      incorrectExample: '模型没回答就让页面空白，或用“已处理”掩盖仍待人工的状态。',
    },
    {
      id: 'ai-observation-audit', prerequisiteConceptIds: ['ai-feature-system', 'network-evidence-boundary'],
      term: '运行观察与审计关联', english: 'Run Observation and Audit Correlation',
      definition: '为同一次 AI 运行关联记录各阶段状态、关键决策、有限输入输出摘要与交付结果的可追溯机制。',
      why: 'AI 失败可能出现在上下文、生成、能力、规则或交付；没有关联记录就只能猜。',
      problemSolved: '支持复现一次失败、区分阶段责任、审查高风险决策并为后续评测提供样本。',
      input: '运行标识、阶段状态、非敏感摘要、规则结果、异常和最终交付。',
      output: '按同一运行串联的事件序列和“看到／推断／未知／下一步”记录。',
      systemPosition: '横跨整条链路，但不应把敏感 Prompt、账号、Token 或私有资料原样写入。',
      process: ['为请求建立关联标识。', '逐阶段追加状态而不覆盖原始记录。', '用有限结论交接下一步取证。'],
      owner: '平台与应用研发提供记录能力；产品、安全和运营定义必要字段与保留边界。',
      notResponsibleFor: '单次审计记录不能证明整体质量、因果根因或所有用户影响范围。',
      compareWith: '最终回复只展示结果；审计关联保留一次运行如何走到该结果的阶段证据。',
      evidence: ['相同 runId 下的阶段状态序列。', '规则、降级、人工交接和异常的追加记录。'],
      failureModes: ['不同阶段没有共同标识，无法串起同一次请求。', '记录了完整敏感上下文，制造新的隐私风险。'],
      pmUse: '定义最小审计字段，让失败样本可追溯，同时坚持脱敏和最小必要原则。',
      correctExample: 'run-ai-014 记录上下文缺失、模型未调用、规则要求追问、最终交付澄清问题。',
      incorrectExample: '只保存“回答失败”，或把真实用户对话与 Token 全量复制进缺陷单。',
    },
  ],
  diagram: {
    title: '一次 AI 产品请求的系统链',
    caption: '沿 runId 读取阶段输入、输出、责任与分叉；RAG 和工具在本课只作为能力槽位出现。',
    nodes: [
      { id: 'request', label: '产品请求', description: '接收用户任务与必要产品状态。', input: '用户问题与界面状态', output: '结构化任务', owner: '产品应用' },
      { id: 'context', label: '上下文组装', description: '选择本次允许且必要的输入。', input: '任务与可用信息', output: '上下文包', owner: '应用服务' },
      { id: 'model', label: '模型生成', description: '生成候选内容，不直接代表业务结果。', input: '上下文包', output: '候选输出', owner: '模型服务' },
      { id: 'capability', label: '能力槽位', description: '定位外部知识或动作接点，机制后续首教。', input: '知识／动作需求', output: '能力状态', owner: '应用编排' },
      { id: 'policy', label: '业务规则', description: '决定允许、追问、拒绝、降级或转人工。', input: '候选与系统状态', output: '交付决策', owner: '业务与安全' },
      { id: 'delivery', label: '交付与审计', description: '展示产品结果并追加本次运行记录。', input: '交付决策', output: '回复／兜底／记录', owner: '应用与运营' },
    ],
    branches: [
      { from: 'request', to: 'context', label: '任务可识别', kind: 'normal' },
      { from: 'context', to: 'model', label: '上下文满足最小条件', kind: 'normal' },
      { from: 'model', to: 'policy', label: '候选进入规则检查', kind: 'normal' },
      { from: 'capability', to: 'policy', label: '能力状态参与决策', kind: 'normal' },
      { from: 'context', to: 'delivery', label: '字段缺失 → 追问', kind: 'failure' },
      { from: 'capability', to: 'delivery', label: '能力不可用 → 降级／人工', kind: 'failure' },
      { from: 'policy', to: 'delivery', label: '高风险 → 拒绝／人工', kind: 'failure' },
    ],
    evidenceNotes: ['每次运行使用同一 runId 串联阶段状态。', '候选输出、规则决策与最终交付是三份不同证据。', '模拟结果不能证明真实模型、知识库、工具或生产系统行为。'],
  },
  demonstration: {
    title: '教师示范：把“自动处理退款”拆成可审查系统链',
    businessProblem: '用户问“这笔订单能退款吗，帮我直接退掉”。团队需要在不执行真实动作的前提下说明系统如何回答、阻断和留痕。',
    finalConclusion: '本次教学模拟中，系统可以组装脱敏状态、生成候选说明并由业务规则阻断真实退款，最终转人工并记录阶段结果。',
    conclusionLimit: '这只证明系统链设计与教学状态变化；不证明真实模型准确、RAG 可用、工具有权限或退款已经发生。',
    steps: [
      { title: '固定请求与 runId', action: '记录脱敏问题、环境和 run-ai-demo-01。', reason: '让后续阶段属于同一次可复现运行。', evidence: '请求摘要与唯一 runId。', proves: '本次教学任务已被固定。', limitation: '不能证明用户身份、订单真实或问题已解决。' },
      { title: '组装最小上下文', action: '加入订单状态=已发货、付款渠道=缺失，并标记资料来源。', reason: '模型只应看到必要且获准的输入。', evidence: '上下文字段清单与缺失标记。', proves: '本次模拟准备了哪些输入。', limitation: '不能证明来源系统实时或字段真实。' },
      { title: '生成候选说明', action: '让教学模拟返回“需要确认付款渠道后判断”。', reason: '先把模型层输出当候选，而非业务决定。', evidence: '候选输出与 generation=completed。', proves: '模拟生成阶段产生了候选。', limitation: '不能证明真实模型会稳定生成同样内容。' },
      { title: '定位能力槽位', action: '标注知识槽位未使用、动作槽位请求被暂挂。', reason: '区分查资料与做动作，避免把它们混为一个能力。', evidence: 'knowledge=not_requested、action=pending_policy。', proves: '系统图中两类能力位置不同。', limitation: '不教授或验证检索、鉴权与工具执行机制。' },
      { title: '应用业务规则', action: '命中“付款渠道缺失”和“退款需人工确认”门槛。', reason: '高风险动作不能由候选文本直接触发。', evidence: 'policy=blocked、reason=missing_payment_channel。', proves: '教学规则选择了阻断路径。', limitation: '不能证明真实退款政策或生产权限配置。' },
      { title: '交付兜底并审计', action: '向用户追问付款渠道，创建教学人工接管状态并追加各阶段记录。', reason: '失败也要给恢复路径与可追溯交接。', evidence: 'delivery=clarify、handoff=queued、阶段序列完整。', proves: '本次模拟完成有限交付与留痕。', limitation: '不能证明人工已经处理或真实工单存在。' },
    ],
  },
  guidedLab: {
    title: 'AI 系统链分层观察器',
    goal: '在完整链、上下文缺失、能力降级和规则阻断四种教学变式中，定位最后成功阶段、首次变化阶段与最终交付。',
    safety: '纯本地教学模拟；不调用真实模型、RAG、工具、账号、Token、公司数据或生产系统。',
    conceptIds: [...conceptIds],
    predictionPrompt: '如果付款渠道缺失或动作被规则阻断，哪一层应最先改变？最终交付应如何降级？',
    steps: [
      { title: '运行完整基线', action: '选择“完整链”并记录一次运行。', observe: '各阶段依次完成，最终只交付说明。', explanation: '基线帮助后续一次只改变一个条件。', proves: '教学链在当前配置下可走完整路径。', cannotProve: '真实模型质量或业务动作成功。' },
      { title: '移除必要上下文', action: '选择“上下文缺失”再运行。', observe: '模型前停止，交付改为澄清问题。', explanation: '缺失输入应在生成前被显式处理。', proves: '本次模拟的规则能识别缺字段。', cannotProve: '真实上下文服务一定正确。' },
      { title: '模拟能力降级', action: '选择“能力不可用”并运行。', observe: '能力槽位失败，系统给出有限说明并转人工。', explanation: '外部能力失败不应伪造成成功。', proves: '本次模拟存在降级路径。', cannotProve: 'RAG 或工具的具体失败机制。' },
      { title: '触发业务阻断', action: '选择“规则阻断”并运行。', observe: '候选已产生，但规则拒绝动作并转人工。', explanation: '候选输出与系统决定是两层证据。', proves: '教学规则能阻断高风险路径。', cannotProve: '真实权限或退款政策已配置。' },
      { title: '逐阶段对照', action: '比较四次 runId 的阶段序列和首次分叉。', observe: '不同条件改变不同阶段，最终交付也不同。', explanation: '分层记录比只看最终回复更可诊断。', proves: '四类失败可以按系统阶段区分。', cannotProve: '单次样本代表总体质量。' },
      { title: '写有限结论', action: '用四句式记录看到、推断、未知与下一步。', observe: '结论只引用本地模拟字段。', explanation: '证据边界阻止把模拟扩大成生产事实。', proves: '学习者能形成可交接的分层观察。', cannotProve: '已经掌握或通过后续评测。' },
    ],
    recordPrompts: ['记录四种变式的 runId、最后成功阶段与首次变化阶段。', '分别记录候选输出、规则结果与最终交付，不要合并。', '写出本模拟可以证明与不能证明的各两项事实。', '为一个未知事项提出不需要生产权限的下一步证据。'],
    comparePrompt: '保持用户问题一致，只改变上下文、能力状态或规则条件；比较首次分叉和最终交付。',
    passCriteria: ['完整覆盖四种教学变式并保留独立 runId。', '每次运行都指出最后成功与首次变化阶段。', '结论明确模拟不能证明真实模型、RAG、工具或生产动作。', '高风险动作路径最终为拒绝或人工接管，不显示已执行。'],
  },
  independentLab: {
    title: '独立变式：为另一个 AI 功能重画系统链',
    scenario: '把智能客服换成“会议纪要助手”，保持同一系统框架，但重新判断必要上下文、能力槽位、业务门槛与兜底。',
    conceptIds: [...conceptIds],
    changedConditions: ['缺少会议参与者与授权范围，系统必须先澄清。', '知识来源槽位不可用，只能基于本次会议文本回答。', '用户要求把纪要发送给外部联系人，动作必须阻断并转人工。'],
    task: '选择一个变化条件，先预测首次分叉，再写出逐层操作计划、观察证据、最终交付与四句有限结论。',
    predictionPrompt: '哪一层最先变化？模型是否应该运行？最终结果应展示、追问、拒绝还是转人工？',
    evidenceRequirements: ['至少记录请求、上下文、候选、规则、交付与审计六层状态。', '明确知识槽位与动作槽位分别是否需要、是否可用。', '写出一个模拟不能证明的真实系统事实。'],
    passCriteria: ['只改变一个主要条件并保留其他基线。', '首次分叉与最终交付之间的因果链完整。', '没有把模型候选写成真实发送或业务成功。', '包含可执行的恢复或人工接管路径。'],
    remediation: { label: '回看系统链教师示范', sectionId: 'demonstration', anchor: 'demonstration-conclusion' },
  },
  exercises: [
    {
      id: 'w11d1-system-vs-prompt', kind: 'single-choice', categories: ['概念与边界'], conceptIds: ['ai-feature-system', 'model-generation-boundary'],
      prompt: '团队说“模型已经生成退款成功文案，所以 AI 退款功能完成了”。最关键的遗漏是什么？',
      hint: '区分模型候选、业务规则、动作结果与最终交付。',
      options: [
        { label: '还缺业务规则、动作结果与交付审计，候选文案不是业务完成证据', rationale: '模型层只产生候选，系统仍需规则和真实结果。', couldBeTrueWhen: '只做无副作用的文案草稿时，候选可作为内部材料。' },
        { label: '只要把 Prompt 再写长一些就能覆盖所有系统责任', rationale: 'Prompt 不能替代确定性门禁、动作结果和审计。', couldBeTrueWhen: '补充任务格式时，Prompt 可能改善输入清晰度。' },
        { label: '模型回复流畅就说明订单与支付状态都正确', rationale: '语言流畅不是外部业务事实证据。', couldBeTrueWhen: '仅评价表达通顺时，流畅度是一个独立维度。' },
      ], answerIndex: 0,
      referenceAnswer: '模型候选只证明生成阶段有输出；还必须检查上下文来源、业务规则、动作权限与结果、最终交付和审计关联。',
      reasoning: ['候选内容与系统决定是不同证据。', '高风险动作必须经过应用门禁并引用真实结果。'],
      rubric: ['指出至少三层遗漏。', '没有把生成文案当作已退款。'],
      commonErrors: [{ error: '只谈 Prompt 质量', reason: '忽略模型前后软件系统的确定性责任。' }],
      remediation: { label: '回看模型生成边界', sectionId: 'concepts', anchor: 'concept-model-generation-boundary' },
    },
    {
      id: 'w11d1-first-fork', kind: 'single-choice', categories: ['机制推演'], conceptIds: ['ai-request-context', 'ai-policy-orchestration', 'ai-output-handoff'],
      prompt: '会议纪要助手缺少参与者授权范围，系统最稳妥的路径是什么？',
      hint: '缺失必要输入时，不必先让模型猜。',
      options: [
        { label: '在上下文阶段标记缺失，交付澄清问题，补齐后再继续', rationale: '必要输入缺失应尽早分叉，并给出恢复路径。', couldBeTrueWhen: '参与者信息与授权范围确实是该任务必填条件。' },
        { label: '让模型自行猜测授权范围并直接生成外发纪要', rationale: '模型猜测不能替代权限事实和业务确认。', couldBeTrueWhen: '只生成不外发的私人草稿且明确假设时风险较低。' },
        { label: '直接记录成功，再由用户发现问题后投诉', rationale: '虚假成功破坏交付状态和审计可信度。', couldBeTrueWhen: '不存在合理业务条件支持虚假成功。' },
      ], answerIndex: 0,
      referenceAnswer: '上下文阶段先暴露缺失，系统交付明确澄清问题；未补齐授权范围前，不进入外发动作。',
      reasoning: ['首次分叉应发生在缺失被发现的阶段。', '最终交付要告诉用户如何恢复。'],
      rubric: ['指出上下文分叉。', '说明不执行外发动作。'],
      commonErrors: [{ error: '把缺字段交给模型补全', reason: '模型生成不能创造可靠权限事实。' }],
      remediation: { label: '回看请求与上下文包', sectionId: 'concepts', anchor: 'concept-ai-request-context' },
    },
    {
      id: 'w11d1-evidence-boundary', kind: 'single-choice', categories: ['证据判断', '工作场景'], conceptIds: ['ai-observation-audit', 'ai-capability-slots-overview'],
      prompt: '教学运行显示 capability=unavailable、delivery=human_handoff。当前最多可以判断什么？',
      hint: '只引用本次模拟阶段字段。',
      options: [
        { label: '本次模拟能力槽位不可用，系统选择人工接管；真实失败机制仍未知', rationale: '结论与阶段证据同层且保留未知。', couldBeTrueWhen: '运行记录确实属于同一 runId 且字段未被篡改。' },
        { label: '生产 RAG 数据库已经宕机', rationale: '教学能力槽位不等于真实 RAG，更没有生产证据。', couldBeTrueWhen: '只有真实监控、日志和范围证据共同支持时才可能成立。' },
        { label: '模型一定出现了幻觉，所以必须永久下线', rationale: '能力不可用与模型幻觉不是同一失败层。', couldBeTrueWhen: '经过独立评测和风险决策后才可能讨论下线。' },
      ], answerIndex: 0,
      referenceAnswer: '只能说明本次本地教学模拟的能力槽位不可用并触发人工接管，不能归因真实 RAG、工具、模型或生产环境。',
      reasoning: ['先确认同一 runId 的原始阶段状态。', '模拟与真实系统之间必须保留证据边界。'],
      rubric: ['包含看到与有限判断。', '明确真实机制未知。'],
      commonErrors: [{ error: '把能力槽位等同 RAG', reason: '本课只定位槽位，不验证检索机制。' }],
      remediation: { label: '回看运行观察与审计', sectionId: 'concepts', anchor: 'concept-ai-observation-audit' },
    },
    {
      id: 'w11d1-transfer-review', kind: 'single-choice', categories: ['综合变式'], conceptIds: [...conceptIds],
      prompt: '评审“AI 自动发布营销文案”时，哪份方案最接近完整系统设计？',
      hint: '检查输入、生成、能力、规则、交付、审计与人工兜底。',
      options: [
        { label: '定义上下文来源、候选生成、素材与发布槽位、品牌／权限门槛、人工确认和审计', rationale: '覆盖端到端阶段、风险门槛和恢复路径。', couldBeTrueWhen: '字段与门槛还需要结合真实业务继续细化。' },
        { label: '只给模型一份品牌 Prompt，并默认生成后自动发布', rationale: '缺少事实来源、权限、动作结果、人工确认和追溯。', couldBeTrueWhen: '仅在内部草稿模式且不发布时可作为早期原型。' },
        { label: '只记录最终文案好不好，不记录任何阶段状态', rationale: '无法区分上下文、生成、规则或发布失败。', couldBeTrueWhen: '只做孤立表达偏好研究时可作为单一指标。' },
      ], answerIndex: 0,
      referenceAnswer: '完整方案要把模型放进产品系统中，并为高风险发布动作提供确定性门槛、人工确认、失败降级和审计关联。',
      reasoning: ['自动发布有真实副作用，需要动作边界。', '最终内容评价不能替代系统阶段证据。'],
      rubric: ['覆盖七层系统链。', '包含人工确认与审计。'],
      commonErrors: [{ error: '把生成等同发布', reason: '候选内容与真实动作之间缺少规则和结果。' }],
      remediation: { label: '回看系统链有限结论', sectionId: 'demonstration', anchor: 'demonstration-conclusion' },
    },
  ],
  deliverable: {
    title: 'AI 系统链路说明',
    conceptIds: [...conceptIds],
    purpose: '让产品、研发、算法、安全与运营围绕同一条 AI 功能链评审责任、门槛、失败、兜底和证据。',
    whenToUse: '在 AI 功能需求评审、技术方案对齐、灰度前风险检查或失败复盘时使用。',
    audience: '产品经理、应用研发、算法／平台、安全、客服运营与审核责任人。',
    fields: [
      { name: '场景与任务', meaning: '用户角色、触发动作、期望结果与高风险事项。', source: '脱敏需求与本次工作场景。' },
      { name: '系统链路', meaning: '请求、上下文、模型、能力槽位、规则、交付与审计顺序。', source: 'DailyCourse 概念图与独立变式。' },
      { name: '逐层责任', meaning: '每层输入、输出、负责与不负责事项。', source: '概念账本和教师示范。' },
      { name: '门槛与分叉', meaning: '何时继续、追问、拒绝、降级或转人工。', source: '业务规则与教学观察器。' },
      { name: '观察与审计', meaning: '同一 runId 下需要追加记录的阶段状态。', source: '四次教学运行与记录字段。' },
      { name: '未知与下一步', meaning: '当前证据不能证明什么，以及下一项安全验证。', source: '四句有限结论与成果自检。' },
    ],
    badExample: '场景与任务：做一个 AI 客服。系统链路：Prompt → 模型。逐层责任：模型负责回答。门槛与分叉：回答不好就重试。观察与审计：看最终答案。未知与下一步：继续调 Prompt。',
    badReasons: ['把产品系统缩成 Prompt 和模型，遗漏上下文、能力、业务规则与交付。', '没有高风险门槛、人工兜底、阶段证据和真实未知事项。'],
    revisionSteps: ['先把用户任务和真实副作用写清，再决定系统边界。', '补齐请求、上下文、模型、能力、规则、交付与审计七层。', '为每层写输入输出、责任、失败和阶段证据。', '为缺字段、能力失败和高风险动作增加分叉与人工兜底。', '最后用四句式收住未知，并指定下一项安全验证。'],
    goodExample: '场景与任务：已登录用户询问脱敏订单退款条件，只提供说明，不执行真实退款。\n系统链路：请求 → 上下文包 → 模型候选 → 知识／动作能力槽位 → 业务规则 → 输出交付 → 审计关联。\n逐层责任：应用组装必要状态；模型生成候选；规则检查必填字段与风险；交付层追问或转人工。\n门槛与分叉：付款渠道缺失先追问；任何真实退款动作均阻断并进入人工确认。\n观察与审计：同一 runId 追加上下文状态、生成状态、能力状态、规则原因和交付类型。\n未知与下一步：本说明不证明真实模型、RAG、工具或生产权限；下一步用脱敏固定样本验证每个分叉。',
    guidedPrompts: ['场景与任务：谁在什么动作后需要什么结果，哪项具有真实副作用？', '系统链路：七层按什么顺序协作，哪些是可选能力槽位？', '逐层责任：每层接收什么、输出什么、不负责什么？', '门槛与分叉：缺字段、能力失败和高风险动作分别走哪条路？', '观察与审计：同一 runId 最小需要记录哪些非敏感字段？', '未知与下一步：哪些事实仍未验证，下一项安全测试是什么？'],
    blankTemplate: '场景与任务：\n系统链路：\n逐层责任：\n门槛与分叉：\n观察与审计：\n未知与下一步：',
    standardTemplate: '场景与任务：〔角色／触发／期望／副作用〕\n系统链路：请求 → 上下文 → 模型 → 能力槽位 → 规则 → 交付 → 审计\n逐层责任：〔逐层输入／输出／负责／不负责〕\n门槛与分叉：〔继续／追问／拒绝／降级／人工〕\n观察与审计：〔runId／阶段状态／原因／交付〕\n未知与下一步：〔不能证明／安全验证〕',
    checklist: ['场景与任务明确区分用户目标和真实副作用。', '系统链路恰好覆盖请求到审计的端到端阶段。', '逐层责任包含输入、输出、负责与不负责事项。', '门槛与分叉至少覆盖缺字段、能力失败和高风险动作。', '观察与审计使用同一 runId 且不记录敏感原文。', '未知与下一步没有把教学模拟冒充生产事实。'],
  },
  memory: {
    conceptIds: [...conceptIds],
    anchors: ['Prompt 只是上下文包的一部分，不是完整 AI 功能。', '模型输出是候选，业务规则与真实动作是后续证据。', '知识来源槽位与外部动作槽位必须分开。', '失败要定位最后成功与首次变化阶段。', '审计记录追加历史，但单样本不代表整体质量。'],
    closedBookPrompt: '不看页面，从用户请求开始，完整讲到上下文、模型、能力槽位、规则、交付与审计，并在每层说出一个不能证明的事实。',
    microOperation: '为一个熟悉的 AI 功能写出 runId 下七层状态和一次高风险分叉。',
    unresolvedPrompt: '今天还有哪一层只有总览定位、必须留到 RAG、工具、安全或评测课程再验证？',
    reviewStages: [
      { stage: 'D1', task: '闭卷画出七层 AI 系统链，并解释 Prompt 所在位置。' },
      { stage: 'D3', task: '给出上下文缺失与规则阻断两个样本，定位首次分叉。' },
      { stage: 'D7', task: '把系统链迁移到会议纪要助手，写出人工兜底。' },
      { stage: 'D14', task: '对一份只写 Prompt 的 AI 方案做逐层缺口评审。' },
      { stage: 'D30', task: '用固定失败样本复核候选、规则、交付和审计是否分层。' },
      { stage: 'D60', task: '独立提交另一项 AI 功能链路说明并标注全部证据边界。' },
    ],
  },
  nextLesson: {
    id: 'W11D2',
    title: 'RAG 与工具调用：分开两种机制',
    bridge: '下一课才分别首次教学检索链与工具动作链；本课只负责建立它们在整体系统中的位置。',
  },
}
