import type { DailyCourse } from './types'

const conceptIds = [
  'ai-failure-observed-output',
  'ai-failure-knowledge-gap',
  'ai-failure-retrieval-gap',
  'ai-failure-source-conflict',
  'ai-failure-generation-overreach',
  'ai-failure-tool-chain',
  'ai-failure-expression-certainty',
  'ai-failure-classification-table',
] as const

const prerequisiteConceptIds = [
  'ai-feature-system',
  'ai-request-context',
  'model-generation-boundary',
  'ai-capability-slots-overview',
  'ai-policy-orchestration',
  'ai-output-handoff',
  'ai-observation-audit',
  'tool-action-boundary',
  'tool-registry-schema',
  'tool-call-proposal',
  'tool-argument-validation',
  'tool-authorization',
  'tool-human-confirmation',
  'tool-execution-side-effect',
  'tool-result-receipt',
  'ai-eval-target-slice',
  'ai-eval-dimension-rubric',
  'ai-eval-case-schema',
  'ai-eval-behavior-oracle',
  'ai-eval-sample-strata',
  'ai-eval-safety-cases',
  'ai-eval-coverage-matrix',
  'ai-eval-set-gate',
]

export const w11d4: DailyCourse = {
  id: 'W11D4',
  contentVersion: 'w11d4-failure-classification-day01-v1',
  week: 11,
  day: 4,
  title: '幻觉从哪里产生',
  subtitle: '把一次 AI 评测失败拆成可观察输出、证据位置、失败类别、首个断点和下一步产品动作，形成不过度归因的失败分类表。',
  duration: { core: 30, standard: 45, extension: 55, full: 100 },
  coreConceptGroups: [
    {
      id: 'failure-observation-first',
      title: '先固定观察，再开始分类',
      conceptIds: ['ai-failure-observed-output', 'ai-failure-classification-table'],
      summary: '失败分类必须先保存样本输入、期望行为、实际输出和可见证据，再决定类别、首个断点与行动。',
      boundary: '本课只做本地教学评测输出的分类，不运行真实模型，不证明线上故障原因。',
    },
    {
      id: 'failure-information-sources',
      title: '知识、召回与资料冲突是三种不同信息问题',
      conceptIds: ['ai-failure-knowledge-gap', 'ai-failure-retrieval-gap', 'ai-failure-source-conflict'],
      summary: '知识缺失是能力或资料本身没有支撑；召回缺口是应有资料未进入本次上下文；资料冲突是可见资料彼此不一致。',
      boundary: '本课不讲 RAG 内部检索算法，只训练产品经理按可见证据分层记录。',
    },
    {
      id: 'failure-generation-tool-expression',
      title: '生成、工具与表达分别对应不同修复人',
      conceptIds: ['ai-failure-generation-overreach', 'ai-failure-tool-chain', 'ai-failure-expression-certainty'],
      summary: '生成过度推断、工具链失败和表达过度确定会呈现相似坏结果，但对应不同证据、责任人和修复动作。',
      boundary: '不把一个流畅错误统一叫幻觉，也不把工具回执问题写成模型知识问题。',
    },
  ],
  prerequisiteConceptIds,
  learningPaths: {
    '30': {
      guidedStepIndices: [0, 1, 2, 3, 4, 5],
      guidedRecordIndices: [0, 1, 2],
      exerciseCount: 3,
      deliverablePromptCount: 5,
      deliverableChecklistIndices: [0, 1, 2, 3, 4],
      deliverableMinimumContributionCharacters: 150,
    },
    '45': {
      guidedStepIndices: [0, 1, 2, 3, 4, 5],
      guidedRecordIndices: [0, 1, 2, 3],
      exerciseCount: 4,
      deliverablePromptCount: 8,
      deliverableChecklistIndices: [0, 1, 2, 3, 4, 5, 6, 7],
      deliverableMinimumContributionCharacters: 250,
    },
  },
  primaryGoal: '提交一份 6 行失败分类表：每行绑定评测样本、实际输出、可见证据、失败类别、首个断点、产品动作和证据边界，并明确分类能与不能证明什么。',
  scenario: {
    role: '你是智能客服评测复盘的产品经理，只使用本地脱敏教学模拟输出。',
    situation: '团队跑完最小评测集后把所有错误都叫“幻觉”，有人建议直接换模型，有人建议补资料，有人怀疑工具。现在没有分类表，也没有证据边界。',
    question: '怎样把同样看起来“答错了”的输出，拆成知识缺失、召回缺口、资料冲突、生成过度推断、工具链失败和表达过度确定？',
    stakes: '分类错会直接带偏修复：该补资料时换模型，该查工具时改 Prompt，该降级表达时误判为业务知识缺失。',
  },
  objectives: [
    { id: 'w11d4-objective-observe', text: '先固定评测输出事实', evidence: '能写出 case_id、expected_behavior、observed_output 与 evidence_seen。' },
    { id: 'w11d4-objective-classify', text: '区分六类失败来源', evidence: '能按可见证据把失败归到唯一主类别，并写出首个断点。' },
    { id: 'w11d4-objective-action', text: '为每类失败给出不同产品动作', evidence: '分类表中包含补资料、改召回、仲裁资料、收紧生成、查工具、降级表达等行动。' },
    { id: 'w11d4-objective-boundary', text: '写清失败分类的证据边界', evidence: '明确本地教学分类不能证明真实生产根因、线上频率或最终安全性。' },
  ],
  prerequisites: [
    {
      id: 'w11d4-ai-system-readiness',
      conceptIds: ['ai-feature-system', 'ai-request-context', 'model-generation-boundary', 'ai-capability-slots-overview', 'ai-policy-orchestration', 'ai-output-handoff', 'ai-observation-audit'],
      prompt: '你能把一次 AI 输出拆回请求、上下文、模型候选、能力槽位、规则、交付和审计吗？',
      passDescription: '能说明输出失败可能发生在模型前、模型中或模型后，而不是一律归因 Prompt。',
      remediationLabel: '补学 W11D1：AI 系统链',
      remediationTarget: '#/lesson/W11D1',
      remediation: {
        purpose: '失败分类必须知道系统链位置，否则只能把所有坏结果混成幻觉。',
        steps: ['回到 W11D1 复述七层系统链。', '为上下文、模型、规则和交付各写一个可见证据。'],
        successCheck: '面对一条错误回答，能至少列出三种可能失败位置。',
      },
    },
    {
      id: 'w11d4-tool-readiness',
      conceptIds: ['tool-action-boundary', 'tool-registry-schema', 'tool-call-proposal', 'tool-argument-validation', 'tool-authorization', 'tool-human-confirmation', 'tool-execution-side-effect', 'tool-result-receipt'],
      prompt: '你能把工具提案、参数、权限、确认、执行和回执与最终回答分开吗？',
      passDescription: '能区分工具没有执行、执行失败、回执不确定和模型错误转述回执。',
      remediationLabel: '补学 W11D2：工具调用',
      remediationTarget: '#/lesson/W11D2',
      remediation: {
        purpose: '工具类失败不能被写成普通生成幻觉，否则会漏掉副作用和回执核验。',
        steps: ['回到 W11D2 复述六路径观察。', '写出 executorCalled=false 与 true 的差别。'],
        successCheck: '能说明 callId 超时未知为什么不能直接写成业务失败。',
      },
    },
    {
      id: 'w11d4-eval-readiness',
      conceptIds: ['ai-eval-target-slice', 'ai-eval-dimension-rubric', 'ai-eval-case-schema', 'ai-eval-behavior-oracle', 'ai-eval-sample-strata', 'ai-eval-safety-cases', 'ai-eval-coverage-matrix', 'ai-eval-set-gate'],
      prompt: '你能读懂一条评测样本的 expected_action、must_include、must_not_include 与 hard_gate 吗？',
      passDescription: '能把实际输出和样本预期对照，说明失败发生在哪个行为判据。',
      remediationLabel: '补学 W11D3：最小评测集',
      remediationTarget: '#/lesson/W11D3',
      remediation: {
        purpose: '失败分类发生在样本运行之后；如果预期行为不清，就无法判断哪里失败。',
        steps: ['回到 W11D3 复述 case schema。', '为一条 privacy 样本写 expected_action 与禁区。'],
        successCheck: '能指出实际输出违反了哪条 must_not_include 或 expected_action。',
      },
    },
  ],
  concepts: [
    {
      id: 'ai-failure-observed-output', prerequisiteConceptIds: ['ai-eval-behavior-oracle'],
      term: '评测输出事实', english: 'Observed Evaluation Output',
      definition: '评测输出事实是同一条 case 的输入、期望行为、实际输出和可见运行证据，不包含尚未证明的根因猜测。',
      why: '没有固定实际输出和期望对照，团队会把记忆中的坏体验、页面现象和猜测混成一个“幻觉”标签。',
      problemSolved: '回答“我们到底看到了哪条样本失败，输出违反了哪条预期”。',
      input: 'case_id、user_input、context、expected_action、must_include、must_not_include、运行输出和教学模拟日志。',
      output: '一条只描述事实的失败记录，包含 observed_output、violated_expectation 和 evidence_seen。',
      systemPosition: '位于任何失败类别判断之前，是分类表的第一层证据。',
      process: ['先引用 case_id 和预期行为。', '再摘录实际输出和可见日志。', '最后只写违反了哪条预期，不写猜测根因。'],
      owner: '评测执行者保存原始输出，产品经理确认它违反了哪条产品预期。',
      notResponsibleFor: '输出事实不解释为什么失败，也不能证明同类问题在线上频率。',
      compareWith: '失败类别是解释标签；输出事实是标签之前的原始观察。',
      evidence: ['case_id 与 expected_action。', 'observed_output 与 evidence_seen。'],
      failureModes: ['只写“答错了”不保存原输出。', '把“看起来像资料问题”直接写成根因。'],
      pmUse: '评审失败前先要求每条都能回到原 case 和原输出，避免争论建立在印象上。',
      correctExample: 'case privacy-03 期望 refuse，实际输出包含他人手机号，日志显示无工具执行。',
      incorrectExample: '模型又幻觉了，应该换一个更强模型。',
    },
    {
      id: 'ai-failure-knowledge-gap', prerequisiteConceptIds: ['ai-failure-observed-output'],
      term: '知识缺失', english: 'Knowledge Gap',
      definition: '知识缺失是系统当前获准知识或产品规则中没有足够依据回答，合格行为应澄清、拒答、转人工或说明未知。',
      why: '当事实根本不在获准资料或规则中时，继续要求模型回答会奖励编造。',
      problemSolved: '区分“系统没有依据”与“依据存在但没被带进上下文”或“依据冲突”。',
      input: '评测样本、获准资料清单、产品规则范围和实际输出。',
      output: 'knowledge_gap 分类、缺失依据说明和产品动作：补知识、缩小承诺或改为澄清/转人工。',
      systemPosition: '发生在系统可用知识范围层，早于召回和生成判断。',
      process: ['检查预期行为需要哪条依据。', '确认获准资料或规则中是否存在。', '不存在时把修复动作写成补知识或降级任务。'],
      owner: '产品与业务负责人定义知识范围，运营或知识库负责人补充资料。',
      notResponsibleFor: '知识缺失不证明召回链路坏，也不证明模型推理能力不足。',
      compareWith: '召回缺口是“有资料但没进本次上下文”；知识缺失是“当前范围内没有这条依据”。',
      evidence: ['资料目录未覆盖该事实。', '产品规则没有该任务承诺。'],
      failureModes: ['把未定义政策硬要求模型编出来。', '看到模型答错就直接归为召回失败。'],
      pmUse: '用它决定是否需要补充业务资料、改产品承诺，或把功能改成转人工。',
      correctExample: '用户问 2027 新政策，教学资料只到 2026；应说明未知并转人工。',
      incorrectExample: '资料范围没有政策仍要求模型给出确定日期。',
    },
    {
      id: 'ai-failure-retrieval-gap', prerequisiteConceptIds: ['ai-failure-observed-output', 'ai-eval-case-schema'],
      term: '召回缺口', english: 'Retrieval Gap',
      definition: '召回缺口是需要的资料在获准资料集中存在，但本次上下文或候选片段没有带入足够证据，导致模型只能猜或答不全。',
      why: '它的修复通常是资料索引、查询、过滤或上下文选择问题，不等于知识本身不存在。',
      problemSolved: '把“资料有但本次没看到”从知识缺失和生成错误中分出来。',
      input: '样本需要的依据、获准资料存在证据、本次上下文片段和实际输出。',
      output: 'retrieval_gap 分类、缺失片段标识和产品动作：调整资料命中、上下文选择或召回验收。',
      systemPosition: '位于知识来源和模型上下文之间；本课只看可见片段，不教学内部检索算法。',
      process: ['先确认资料集中存在正确依据。', '再检查本次上下文是否带入。', '若未带入，记录缺失片段和查询条件。'],
      owner: '检索/资料维护负责人提供片段记录，产品经理定义该样本需要的资料。',
      notResponsibleFor: '召回缺口不证明生成模型坏，也不解释具体检索算法根因。',
      compareWith: '知识缺失没有可用依据；召回缺口有依据但本次上下文没有带到。',
      evidence: ['source_exists=true。', 'context_missing 或 retrieved_docs 不含目标片段。'],
      failureModes: ['资料存在却只让模型凭记忆回答。', '把没进入上下文的片段当作模型应该天然知道。'],
      pmUse: '让研发或资料负责人复核查询和片段，不把问题错误派给 Prompt 文案。',
      correctExample: '退款规则文档存在，但本次上下文只带了物流规则，回答缺少退款时限。',
      incorrectExample: '资料在后台有，所以模型这次必然已经看到了。',
    },
    {
      id: 'ai-failure-source-conflict', prerequisiteConceptIds: ['ai-failure-observed-output'],
      term: '资料冲突', english: 'Source Conflict',
      definition: '资料冲突是本次可见证据中存在多个互相矛盾的来源、版本或规则，系统没有明确仲裁顺序。',
      why: '模型在冲突资料中选择任一方都可能看似有依据；真正缺的是版本优先级和冲突处理规则。',
      problemSolved: '把“有两个依据但互相打架”从知识缺失、召回缺口和生成过度中分出来。',
      input: '两个或多个可见资料片段、版本时间、优先级说明和实际输出。',
      output: 'source_conflict 分类、冲突来源对和产品动作：冻结权威源、版本优先级或人工仲裁。',
      systemPosition: '位于上下文资料层和规则编排层之间，决定模型可依据哪一份资料。',
      process: ['列出冲突片段。', '核对版本和权威顺序。', '没有仲裁时把失败标为资料冲突而非模型瞎编。'],
      owner: '业务资料 owner 和产品共同定义权威源，研发在系统中执行优先级。',
      notResponsibleFor: '资料冲突不证明模型没有理解，也不证明某一份资料天然正确。',
      compareWith: '召回缺口是少了资料；资料冲突是资料来了但互相矛盾。',
      evidence: ['两个片段给出不同规则。', '缺少 source_priority 或 effective_date。'],
      failureModes: ['新旧政策同时进入上下文。', '客服手册和活动规则冲突却无仲裁。'],
      pmUse: '在评审中推动业务先定权威源，再让模型回答。',
      correctExample: '手册写 7 天，活动页写 15 天，本次上下文同时包含且无优先级。',
      incorrectExample: '看到模型选了 7 天，就直接归为生成幻觉。',
    },
    {
      id: 'ai-failure-generation-overreach', prerequisiteConceptIds: ['ai-failure-observed-output', 'model-generation-boundary'],
      term: '生成过度推断', english: 'Generation Overreach',
      definition: '生成过度推断是上下文证据不足、缺失或不确定时，模型仍补出具体事实、承诺、状态或原因。',
      why: '这类失败的关键不是资料有没有，而是输出越过了可见证据支持的位置。',
      problemSolved: '区分“依据没有/没带到/冲突”和“依据有限但输出说得过满”。',
      input: '上下文证据、工具回执、预期行为中的未知处理规则和实际输出。',
      output: 'generation_overreach 分类、越界句子和产品动作：收紧提示、增加未知处理、强化负断言。',
      systemPosition: '发生在模型候选生成层，通常需要回到 must_not_include 与未知表达规则。',
      process: ['定位输出中多出来的事实。', '检查可见证据是否支持。', '没有支持时记录越界句和应改成的不确定表达。'],
      owner: '产品定义不可越界承诺，算法/Prompt 负责人调整生成约束。',
      notResponsibleFor: '生成过度不说明资料库缺失，也不说明工具真的执行成功或失败。',
      compareWith: '表达过度确定强调语气和确定性；生成过度推断强调新增了无依据事实。',
      evidence: ['输出包含 context 中没有的金额、日期、状态或原因。', 'must_not_include 被违反。'],
      failureModes: ['工具超时仍说订单已取消。', '资料只说可能延迟，回答写成一定明天到账。'],
      pmUse: '把越界句写进失败表，推动负断言和未知处理成为样本规则。',
      correctExample: '回执为 UNKNOWN，模型却写“已退款成功”。',
      incorrectExample: '因为回答很自信，所以一定是资料冲突。',
    },
    {
      id: 'ai-failure-tool-chain', prerequisiteConceptIds: ['tool-result-receipt', 'ai-failure-observed-output'],
      term: '工具链失败', english: 'Tool Chain Failure',
      definition: '工具链失败是工具提案、参数、权限、确认、执行、回执或回执转述中的某一层证据异常，影响最终交付。',
      why: '工具问题可能产生真实副作用或不确定状态，不能被简化成“回答幻觉”。',
      problemSolved: '把动作链路问题从纯文本生成问题里分出来，并要求保留 callId、executorCalled 和 receipt。',
      input: 'tool proposal、validation、authorization、confirmation、executorCalled、callId、receipt 和最终输出。',
      output: 'tool_chain 分类、首次失败层和产品动作：查参数、权限、确认、执行器或回执映射。',
      systemPosition: '位于 W11D2 工具调用链和 W11D4 输出分类之间。',
      process: ['按工具链顺序找第一个异常。', '区分执行前拒绝和执行后未知。', '检查最终回答是否正确转述回执。'],
      owner: '研发负责工具执行与回执，产品负责动作边界和用户交付文案。',
      notResponsibleFor: '工具链失败不证明模型知识缺失，也不允许重复执行高风险动作来试错。',
      compareWith: '生成过度可能编造工具结果；工具链失败则有工具阶段异常证据。',
      evidence: ['executorCalled、callId、receiptCode。', 'validation 或 authorization 失败字段。'],
      failureModes: ['参数缺字段仍执行。', '工具超时后输出写成成功。'],
      pmUse: '把问题派给正确责任层，并要求恢复路径而非简单重试。',
      correctExample: 'executorCalled=true、TOOL_TIMEOUT_UNKNOWN，有 callId；最终回答不能承诺业务已完成。',
      incorrectExample: '看到“已创建”就认为工具成功，无需看回执。',
    },
    {
      id: 'ai-failure-expression-certainty', prerequisiteConceptIds: ['ai-failure-observed-output', 'ai-output-handoff'],
      term: '表达过度确定', english: 'Overconfident Expression',
      definition: '表达过度确定是系统可能给出有限回答或恢复路径，但用确定、完整或已完成的语气掩盖了证据不足。',
      why: '这类失败会误导用户和运营判断，即使核心事实没有新增编造，也可能破坏风险沟通。',
      problemSolved: '把“说法太确定”从事实新增和工具失败中分出来，形成可修的交付语气问题。',
      input: '实际输出、可见证据强度、预期的 uncertain/clarify/handoff 表达规则。',
      output: 'expression_overcertainty 分类、需要降级的句子和产品动作：调整模板、语气和风险提示。',
      systemPosition: '位于输出交付层，常发生在候选内容到用户文案的最后一段。',
      process: ['先判断事实是否有新增。', '再看证据强度是否只支持有限表述。', '最后把绝对语气改为条件、未知或下一步。'],
      owner: '产品与内容设计定义风险表达，算法或前端交付层执行。',
      notResponsibleFor: '表达问题不证明底层资料错，也不证明工具链失败。',
      compareWith: '生成过度推断新增无依据事实；表达过度确定把有限证据包装得过满。',
      evidence: ['输出使用“一定、已经、保证、全部”等确定词。', '样本 expected_action 要求 report_uncertain 或 clarify。'],
      failureModes: ['证据只支持可能，文案写成必然。', '应转人工却用完整答案收口。'],
      pmUse: '把风险表达写进交付标准，不让一次不确定输出误导用户采取动作。',
      correctExample: '只能说“当前无法确认，请按 callId 查询”，不能说“已经处理完成”。',
      incorrectExample: '虽然资料不完整，但回答要显得确定一点。',
    },
    {
      id: 'ai-failure-classification-table', prerequisiteConceptIds: ['ai-failure-knowledge-gap', 'ai-failure-retrieval-gap', 'ai-failure-source-conflict', 'ai-failure-generation-overreach', 'ai-failure-tool-chain', 'ai-failure-expression-certainty'],
      term: '失败分类表', english: 'Failure Classification Table',
      definition: '失败分类表把每条失败样本记录为观察事实、主类别、首个断点、证据强度、产品动作和不能证明的事项。',
      why: '没有统一表格，复盘会变成争论模型好坏；有表格后，样本修复、资料修复、工具修复和表达修复才能分流。',
      problemSolved: '回答“这次失败应该由谁下一步处理，依据是什么，哪些结论还不能下”。',
      input: '失败输出事实、六类分类定义、系统链和工具链可见证据。',
      output: '可审核的失败分类表，至少覆盖六类各一条教学模拟，并附有限结论。',
      systemPosition: '位于评测输出之后、改进方案之前，是 W11D5 风险清单和 W11D6 综合报告的输入。',
      process: ['逐行先写观察事实。', '按可见证据选唯一主类别。', '写首个断点、下一步动作和证据限制。'],
      owner: '产品经理维护表格，研发、资料、安全和业务负责人按类别领取下一步。',
      notResponsibleFor: '分类表不自动修复问题，不证明真实生产根因或上线安全。',
      compareWith: '评测样本定义应当怎样表现；失败分类表记录实际没做到时该怎么分流。',
      evidence: ['failure_category、first_failed_stage、product_action 和 evidence_limit 字段。', '六类教学模拟各有记录。'],
      failureModes: ['一行写多个主类别但没有首个证据断点。', '把下一步写成“优化模型”而不说明证据。'],
      pmUse: '用它主持 AI 评测复盘，把问题分发到资料、召回、规则、工具、生成或交付表达。',
      correctExample: 'retrieval_gap：资料存在但本次上下文未带入；下一步检查片段命中与上下文选择。',
      incorrectExample: '失败原因：AI 不够聪明；下一步：换更强模型。',
    },
  ],
  diagram: {
    title: '从输出事实到失败分类表',
    caption: '先固定实际输出，再按资料是否存在、是否进入上下文、是否冲突、是否越界生成、工具链是否异常和交付表达是否过满逐层分类。',
    nodes: [
      { id: 'observed', label: '输出事实', description: '保存 case、预期、实际输出和可见日志', input: '评测运行结果', output: 'observed_output', owner: '评测执行者', evidence: '原始输出与日志' },
      { id: 'knowledge', label: '知识范围', description: '判断依据是否在获准资料或规则内', input: '资料清单与规则', output: 'knowledge_gap 或继续检查', owner: '产品/业务', evidence: '资料存在性' },
      { id: 'context', label: '上下文片段', description: '判断已存在资料是否进入本次上下文', input: 'retrieved/context 记录', output: 'retrieval_gap 或继续检查', owner: '资料/研发', evidence: '片段命中' },
      { id: 'sources', label: '资料仲裁', description: '判断可见资料是否冲突且缺少优先级', input: '多个来源与版本', output: 'source_conflict 或继续检查', owner: '业务 owner', evidence: '冲突片段' },
      { id: 'generation', label: '生成与交付', description: '判断是否越界生成、工具链异常或表达过满', input: '候选、工具回执与交付文案', output: '分类表行', owner: '产品/算法/研发', evidence: '越界句、callId、确定词' },
    ],
    branches: [
      { from: 'observed', to: 'knowledge', label: '先问依据是否存在', kind: 'normal' },
      { from: 'knowledge', to: 'context', label: '存在依据再看本次上下文', kind: 'normal' },
      { from: 'context', to: 'sources', label: '上下文齐全再看冲突', kind: 'normal' },
      { from: 'sources', to: 'generation', label: '资料可用后检查生成、工具与表达', kind: 'normal' },
      { from: 'knowledge', to: 'observed', label: '依据不存在：回到表格写知识缺失', kind: 'failure' },
      { from: 'generation', to: 'observed', label: '证据不足：不得写生产根因', kind: 'failure' },
    ],
    evidenceNotes: ['召回缺口只基于可见的资料存在与上下文缺失，不展开内部检索算法。', '分类表的 valid 只说明本地教学分类合同通过，不代表真实模型或线上系统已经修复。'],
  },
  demonstration: {
    title: '把“AI 又幻觉了”修成六类失败记录',
    businessProblem: '同一组评测输出中，有的缺资料、有的资料没进上下文、有的资料互相冲突、有的编造工具结果；团队却全部写成幻觉。',
    finalConclusion: '修订后每条失败都先引用观察事实，再给出唯一主类别、首个断点、下一步产品动作和证据限制。',
    conclusionLimit: '示范只能证明分类方法可复核，不能证明真实生产根因、问题频率或修复效果。',
    steps: [
      { title: '冻结输出事实', action: '把 case_id、expected_action、actual_output 和 teaching log 写入表格。', reason: '分类必须从同一条可复现失败开始。', evidence: 'observed_output 与 violated_expectation。', proves: '这条失败真实存在于本地教学运行。', limitation: '不证明失败原因。' },
      { title: '判断知识是否存在', action: '检查获准资料和规则是否包含所需政策。', reason: '没有依据时不能让模型凭空回答。', evidence: 'source_exists=false。', proves: '可归为 knowledge_gap。', limitation: '不证明召回链路坏。' },
      { title: '判断资料是否进入上下文', action: '资料存在时检查本次 context 是否包含目标片段。', reason: '资料有但未进入上下文，修复方向不同。', evidence: 'source_exists=true、context_missing=true。', proves: '可归为 retrieval_gap。', limitation: '不解释内部检索算法根因。' },
      { title: '检查资料是否冲突', action: '把两个可见片段并排比较有效期与优先级。', reason: '冲突资料需要业务仲裁，不是模型单独能解决。', evidence: '两个片段给出不同答案且无 source_priority。', proves: '可归为 source_conflict。', limitation: '不证明哪一份资料正确。' },
      { title: '拆开生成、工具与表达', action: '分别查看越界句、工具回执和确定性语气。', reason: '三者修复人不同，不能混成一个模型问题。', evidence: 'must_not_include 违反、callId/receipt、确定词。', proves: '能选出最先有证据支持的主类别。', limitation: '不证明全部次要因素。' },
      { title: '写有限下一步', action: '每行只写一个下一步：补知识、查上下文、仲裁资料、收紧生成、核验工具或降级表达。', reason: '分类表服务于分流修复。', evidence: 'product_action 与 evidence_limit。', proves: '团队知道下一步找谁补证据。', limitation: '不证明修复已完成。' },
    ],
  },
  guidedLab: {
    title: '六类失败来源观察台',
    goal: '对照知识缺失、召回缺口、资料冲突、生成过度推断、工具链失败和表达过度确定六种教学模拟，记录每条失败的首个证据断点。',
    safety: '全部为本地脱敏教学模拟；不调用真实模型、RAG、工具、账号、Token、公司数据或生产系统，也不把教学输出当真实生产证据。',
    conceptIds: [...conceptIds],
    predictionPrompt: '运行前先预测：哪些失败应该补资料，哪些应该查上下文或工具，哪些只是输出越界或表达过满？',
    steps: [
      { title: '运行知识缺失', action: '选择“知识缺失”并运行。', observe: 'source_exists=false，模型却给出具体政策。', explanation: '依据不在获准范围内时，正确动作是说明未知或转人工。', proves: '能把无依据问题归为 knowledge_gap。', cannotProve: '不能证明召回链路异常。' },
      { title: '运行召回缺口', action: '选择“召回缺口”并运行。', observe: 'source_exists=true，但 context_missing=true。', explanation: '资料存在但没进入本次上下文，修复方向是资料命中与上下文选择。', proves: '能区分知识缺失和召回缺口。', cannotProve: '不能解释内部检索算法细节。' },
      { title: '运行资料冲突', action: '选择“资料冲突”并运行。', observe: '两个来源给出不同期限且 priority=none。', explanation: '冲突需要业务仲裁或版本优先级。', proves: '能把冲突资料从生成错误中分离。', cannotProve: '不能证明哪份资料天然正确。' },
      { title: '运行生成过度推断', action: '选择“生成过度推断”并运行。', observe: 'context 中没有具体日期，输出却承诺明天到账。', explanation: '模型越过了可见证据。', proves: '能定位无依据新增事实。', cannotProve: '不能证明资料库缺失。' },
      { title: '运行工具链失败', action: '选择“工具链失败”并运行。', observe: 'executorCalled=true、receipt=TOOL_TIMEOUT_UNKNOWN，输出却写成功。', explanation: '工具回执和交付转述不一致，需要保留 callId 核验。', proves: '能把动作链路问题单独分类。', cannotProve: '不能证明真实业务对象已变化。' },
      { title: '运行表达过度确定', action: '选择“表达过度确定”并运行。', observe: '事实没有新增，但语气把可能写成一定。', explanation: '有限证据需要降级表达或转人工。', proves: '能把交付语气问题从生成事实错误中分离。', cannotProve: '不能证明底层资料或工具错误。' },
    ],
    recordPrompts: ['记录六条路径各自的 failure_category 和 first_failed_stage。', '解释知识缺失、召回缺口和资料冲突的证据差异。', '写出工具链失败为什么不能直接重复执行。', '写一条分类表 valid 后仍不能证明的结论。'],
    comparePrompt: '比较“召回缺口”和“生成过度推断”：两者都可能答错，但证据位置与下一步为什么不同？',
    passCriteria: ['已运行并保存六种教学路径。', '能区分知识、召回、资料冲突、生成、工具和表达六类。', '每条记录都有首个断点与下一步动作。', '明确教学模拟不能证明真实生产根因。', '记录中没有真实敏感信息或生产 Token。'],
  },
  independentLab: {
    title: '独立变式：给会议纪要助手做失败分类',
    scenario: '把智能客服换成会议纪要助手：它可能缺少会议资料、没带入正确片段、看到冲突纪要、编造决定、误报通知工具成功，或把不确定结论说得过满。',
    conceptIds: [...conceptIds],
    changedConditions: ['业务对象从订单客服改为会议纪要助手。', '工具从售后动作改为通知发送教学回执。', '资料冲突从政策版本改为会议纪要和任务清单不一致。'],
    task: '选择 3 条失败输出，分别写出观察事实、主类别、首个断点、下一步动作和证据边界。',
    predictionPrompt: '会议纪要助手最容易把哪类失败误写成“模型幻觉”？为什么？',
    evidenceRequirements: ['每条必须引用 expected_behavior 与 observed_output。', '至少一条覆盖资料/上下文问题，至少一条覆盖工具或表达问题。', '所有结论都标注教学模拟和不能证明的生产事实。'],
    passCriteria: ['三条变式都有唯一主类别。', '每条都有 first_failed_stage 和 product_action。', '没有把 RAG 内部机制或生产根因当作本课已证明内容。', '结论只说明本地教学分类质量。'],
    remediation: { label: '回看六类失败来源', sectionId: 'concepts', anchor: 'concept-ai-failure-knowledge-gap' },
  },
  exercises: [
    {
      id: 'w11d4-knowledge-vs-retrieval', kind: 'single-choice', categories: ['概念与边界'],
      conceptIds: ['ai-failure-knowledge-gap', 'ai-failure-retrieval-gap'],
      prompt: '资料库中确实有“7 天可退”规则，但本次上下文没有带入，模型回答“不确定”。最准确的分类是什么？',
      hint: '先判断依据是否存在，再判断本次是否进入上下文。',
      options: [
        { label: '召回缺口', rationale: '依据存在但没有进入本次上下文，下一步查资料命中和上下文选择。', couldBeTrueWhen: 'source_exists=true 且 context_missing=true。' },
        { label: '知识缺失', rationale: '知识缺失要求获准范围内没有该依据。', couldBeTrueWhen: '资料或规则本身确实不存在时。' },
        { label: '表达过度确定', rationale: '这里输出没有过度确定，只是缺少依据支撑。', couldBeTrueWhen: '输出把不确定写成确定承诺时。' },
      ],
      answerIndex: 0,
      referenceAnswer: '这是召回缺口：资料存在，但本次上下文没带入。分类表应记录缺失片段和下一步核查资料命中。',
      reasoning: ['知识存在性和上下文进入是两层证据。', '本课不需要展开内部检索算法。'],
      rubric: ['写出 source_exists=true', '写出 context_missing=true'],
      commonErrors: [{ error: '写成知识缺失', reason: '忽略了资料已存在。' }, { error: '写成模型不会回答', reason: '没有定位到上下文证据层。' }],
      remediation: { label: '回看召回缺口', sectionId: 'concepts', anchor: 'concept-ai-failure-retrieval-gap' },
    },
    {
      id: 'w11d4-tool-vs-generation', kind: 'single-choice', categories: ['机制推演', '证据判断'],
      conceptIds: ['ai-failure-generation-overreach', 'ai-failure-tool-chain'],
      prompt: '工具回执为 TOOL_TIMEOUT_UNKNOWN 且保留 callId，最终回答却写“工单已创建成功”。主类别应先写什么？',
      hint: '有工具阶段异常证据时，先按工具链定位。',
      options: [
        { label: '工具链失败', rationale: '执行后结果未知，交付文案又错误转述回执，应保留 callId 查询。', couldBeTrueWhen: '有 executorCalled、callId 或 receipt 异常证据。' },
        { label: '知识缺失', rationale: '这里不是缺政策知识，而是动作回执不确定。', couldBeTrueWhen: '没有获准资料支持回答时。' },
        { label: '资料冲突', rationale: '没有两个互相矛盾来源。', couldBeTrueWhen: '上下文里存在不同版本规则且无优先级时。' },
      ],
      answerIndex: 0,
      referenceAnswer: '主类别先写工具链失败，并记录 first_failed_stage=tool_receipt，下一步按 callId 查询状态而不是重复执行。',
      reasoning: ['工具回执是强证据。', '执行后未知不能当作成功，也不能盲目重试。'],
      rubric: ['引用 callId/receipt', '写出不能重复高风险动作'],
      commonErrors: [{ error: '写成普通幻觉', reason: '丢掉了工具链证据。' }, { error: '立即重试', reason: '可能造成重复副作用。' }],
      remediation: { label: '回看工具链失败', sectionId: 'concepts', anchor: 'concept-ai-failure-tool-chain' },
    },
    {
      id: 'w11d4-source-conflict', kind: 'single-choice', categories: ['工作场景'],
      conceptIds: ['ai-failure-source-conflict', 'ai-failure-classification-table'],
      prompt: '上下文同时包含旧手册“7 天退款”和活动页“15 天退款”，没有优先级。模型选择 7 天。分类表应怎样写？',
      hint: '有两份可见资料互相矛盾，先不要判断哪份正确。',
      options: [
        { label: 'source_conflict；下一步要求业务仲裁权威源和有效期', rationale: '冲突来源都可见，缺少的是优先级。', couldBeTrueWhen: '多个来源或版本给出不同规则。' },
        { label: 'retrieval_gap；下一步扩大上下文', rationale: '上下文不是缺少资料，而是资料互相冲突。', couldBeTrueWhen: '目标资料存在但未被带入时。' },
        { label: 'generation_overreach；下一步只改 Prompt', rationale: '模型选项可能有依据，真正缺的是仲裁规则。', couldBeTrueWhen: '上下文不支持输出新增事实时。' },
      ],
      answerIndex: 0,
      referenceAnswer: '应写 source_conflict，列出两个冲突来源与缺失的 priority/effective_date，下一步交给业务确认权威源。',
      reasoning: ['资料都可见但不一致。', '产品动作是仲裁资料，不是继续堆上下文。'],
      rubric: ['列出冲突来源', '写出业务仲裁动作'],
      commonErrors: [{ error: '写成召回缺口', reason: '资料没有缺席。' }, { error: '只改 Prompt', reason: '没有解决权威源冲突。' }],
      remediation: { label: '回看资料冲突', sectionId: 'concepts', anchor: 'concept-ai-failure-source-conflict' },
    },
    {
      id: 'w11d4-expression-boundary', kind: 'single-choice', categories: ['综合变式'],
      conceptIds: ['ai-failure-expression-certainty', 'ai-failure-generation-overreach'],
      prompt: '资料只支持“可能延迟 1–3 天”，回答写“你的包裹一定会在 3 天内到”。没有新增地点或状态。最合适的分类是什么？',
      hint: '看它是新增事实，还是把有限证据说得过满。',
      options: [
        { label: '表达过度确定', rationale: '核心事实来自资料，但确定性超过证据强度。', couldBeTrueWhen: '应使用可能、当前无法确认或下一步，而输出写成保证。' },
        { label: '知识缺失', rationale: '资料中已有延迟范围，不是完全缺知识。', couldBeTrueWhen: '没有任何获准规则可回答时。' },
        { label: '工具链失败', rationale: '没有工具提案、执行或回执证据。', couldBeTrueWhen: '存在 callId、executorCalled 或 receipt 异常时。' },
      ],
      answerIndex: 0,
      referenceAnswer: '这是表达过度确定。产品动作应降级交付模板，要求“可能延迟 1–3 天，具体以物流更新为准”。',
      reasoning: ['事实范围已有依据。', '问题在交付语气和确定性。'],
      rubric: ['区分事实新增与语气过满', '给出降级表达'],
      commonErrors: [{ error: '写成生成过度推断', reason: '没有新增无依据事实。' }, { error: '写成知识缺失', reason: '忽略资料已有范围。' }],
      remediation: { label: '回看表达过度确定', sectionId: 'concepts', anchor: 'concept-ai-failure-expression-certainty' },
    },
  ],
  deliverable: {
    title: '失败分类表',
    conceptIds: [...conceptIds],
    purpose: '把本地教学评测输出按可见证据分流到正确修复动作，避免把所有错误都写成幻觉或直接换模型。',
    whenToUse: '评测集运行后、版本回归失败后、上线评审发现 AI 输出问题时，用于复盘和分派下一步取证。',
    audience: '产品经理、算法/Prompt 负责人、资料 owner、研发、测试、安全和客服运营。',
    fields: [
      { name: 'case_id', meaning: '失败样本的稳定标识。', source: 'W11D3 评测样本。' },
      { name: 'expected_behavior', meaning: '本条样本原本要求的动作或边界。', source: 'expected_action、must_include、must_not_include。' },
      { name: 'observed_output', meaning: '教学运行中的实际输出摘录。', source: '本地教学模拟输出。' },
      { name: 'evidence_seen', meaning: '可见证据，如资料存在性、上下文片段、冲突来源或工具回执。', source: '教学日志和样本上下文。' },
      { name: 'failure_category', meaning: '六类主分类之一。', source: '本日分类定义。' },
      { name: 'first_failed_stage', meaning: '首个有证据支持的断点。', source: '系统链、工具链和评测输出事实。' },
      { name: 'product_action', meaning: '下一步产品或协作动作。', source: '分类对应的修复分流。' },
      { name: 'evidence_limit', meaning: '本行分类不能证明什么。', source: '教学模拟与生产边界。' },
    ],
    badExample: 'case-7：AI 幻觉了，建议换模型。',
    badReasons: ['没有 expected_behavior、observed_output 和 evidence_seen。', '没有主类别、首个断点、下一步动作和证据限制。', '把本地教学输出扩大成模型整体结论。'],
    revisionSteps: ['先补 case_id、期望行为和实际输出。', '按资料是否存在、是否进入上下文、是否冲突、是否越界生成、工具是否异常和表达是否过满判断主类别。', '每行只写一个首个断点和一个下一步动作。', '写清本地教学分类不能证明生产根因或线上频率。'],
    goodExample: '{"case_id":"tool-02","expected_behavior":"report_tool_uncertain","observed_output":"工单已创建成功","evidence_seen":"executorCalled=true; receipt=TOOL_TIMEOUT_UNKNOWN; callId=sim-204","failure_category":"tool_chain","first_failed_stage":"tool_receipt_delivery","product_action":"按 callId 查询状态并修正回执转述","evidence_limit":"只证明本地教学工具回执与输出不一致，不证明真实工单状态"}',
    guidedPrompts: ['写一行 knowledge_gap：依据不存在，不要求模型编造。', '写一行 retrieval_gap：依据存在但未进入本次上下文。', '写一行 source_conflict：两个来源冲突且无优先级。', '写一行 generation_overreach：输出新增无依据事实。', '写一行 tool_chain：工具回执或转述异常。', '写一行 expression_overcertainty：事实有限但语气过满。', '每行都写 first_failed_stage 和 product_action。', '每行都写 evidence_limit，不写生产根因。'],
    blankTemplate: '{"case_id":"","expected_behavior":"","observed_output":"","evidence_seen":"","failure_category":"","first_failed_stage":"","product_action":"","evidence_limit":""}',
    standardTemplate: [
      '{"case_id":"knowledge-01","expected_behavior":"report_unknown_or_handoff","observed_output":"待填写","evidence_seen":"source_exists=false","failure_category":"knowledge_gap","first_failed_stage":"knowledge_scope","product_action":"补充获准知识或改为转人工","evidence_limit":"只证明本地教学资料范围不足，不证明线上知识库缺失"}',
      '{"case_id":"retrieval-01","expected_behavior":"answer_with_source","observed_output":"待填写","evidence_seen":"source_exists=true; context_missing=true","failure_category":"retrieval_gap","first_failed_stage":"context_selection","product_action":"检查资料命中与上下文选择","evidence_limit":"只证明本次教学上下文缺片段，不解释内部检索算法"}',
      '{"case_id":"conflict-01","expected_behavior":"ask_for_handoff_or_apply_priority","observed_output":"待填写","evidence_seen":"source_a=7天; source_b=15天; priority=none","failure_category":"source_conflict","first_failed_stage":"source_arbitration","product_action":"确认权威源、有效期和优先级","evidence_limit":"只证明教学上下文资料冲突，不证明哪份资料正确"}',
      '{"case_id":"generation-01","expected_behavior":"report_uncertain","observed_output":"待填写","evidence_seen":"context lacks date; output adds date","failure_category":"generation_overreach","first_failed_stage":"model_candidate","product_action":"收紧未知处理和 must_not_include","evidence_limit":"只证明输出越过可见证据，不证明资料缺失"}',
      '{"case_id":"tool-01","expected_behavior":"report_tool_uncertain","observed_output":"待填写","evidence_seen":"executorCalled=true; receipt=TOOL_TIMEOUT_UNKNOWN; callId=sim-001","failure_category":"tool_chain","first_failed_stage":"tool_receipt_delivery","product_action":"按 callId 查询并修正回执转述","evidence_limit":"只证明教学工具回执不确定，不证明真实业务状态"}',
      '{"case_id":"expression-01","expected_behavior":"qualified_answer","observed_output":"待填写","evidence_seen":"source says maybe; output says guarantee","failure_category":"expression_overcertainty","first_failed_stage":"output_handoff","product_action":"降级确定性表达并补下一步","evidence_limit":"只证明教学交付语气过满，不证明底层资料错误"}',
    ].join('\n'),
    checklist: ['JSONL 恰好 6 行且每行可独立解析。', '六类 failure_category 各一行：knowledge_gap、retrieval_gap、source_conflict、generation_overreach、tool_chain、expression_overcertainty。', 'case_id 不重复，observed_output、evidence_seen 和 expected_behavior 非空。', '每行都有 first_failed_stage 和 product_action。', '每行都有 evidence_limit，且不能声称真实生产根因或线上频率。', '工具类行必须包含 callId 或 receipt。', '召回类行必须同时表达 source_exists=true 与 context_missing=true。', '所有行均标注为本地教学模拟证据。'],
  },
  memory: {
    conceptIds: [...conceptIds],
    anchors: ['先写输出事实，再写失败类别。', '知识缺失、召回缺口和资料冲突是三种信息问题。', '生成、工具和表达对应不同责任层。', '失败分类表服务于下一步取证，不证明生产根因。'],
    closedBookPrompt: '闭卷讲清评测输出事实、知识缺失、召回缺口、资料冲突、生成过度推断、工具链失败、表达过度确定和失败分类表。',
    microOperation: '不看模板，为一条“工具超时却回答成功”的输出写完整失败分类表行。',
    unresolvedPrompt: '记录一条仍需要真实日志、业务 owner 或资料负责人才能确认的后续证据，不自行猜测生产根因。',
    reviewStages: [
      { stage: 'D1', task: '闭卷写出六类 failure_category，并为每类各写一个 evidence_seen。' },
      { stage: 'D3', task: '给三条新失败输出分类，指出第一条可见证据断点。' },
      { stage: 'D7', task: '比较 knowledge_gap、retrieval_gap 和 source_conflict，写出不同产品动作。' },
      { stage: 'D14', task: '审阅一张失败分类表，找出过度归因和缺少 evidence_limit 的行。' },
      { stage: 'D30', task: '把一次工具失败输出拆成工具阶段、交付文案和不能证明的生产事实。' },
      { stage: 'D60', task: '闭卷重建一份六类失败分类表模板，并说明它怎样输入 W11D5 风险清单。' },
    ],
  },
  nextLesson: {
    id: 'W11D5',
    title: '成本、延迟与安全',
    bridge: '下一课才把失败分类接到成本、延迟、安全门槛、降级和人工兜底清单；本课只完成失败来源分类，不设计完整风险架构。',
  },
}
