import type { DailyCourse } from './types'

const conceptIds = [
  'tool-action-boundary',
  'tool-registry-schema',
  'tool-call-proposal',
  'tool-argument-validation',
  'tool-authorization',
  'tool-human-confirmation',
  'tool-execution-side-effect',
  'tool-result-receipt',
] as const

const prerequisiteConceptIds = [
  'http-request',
  'http-response',
  'business-rule',
  'ai-feature-system',
  'ai-request-context',
  'model-generation-boundary',
  'ai-capability-slots-overview',
  'ai-policy-orchestration',
  'ai-output-handoff',
  'ai-observation-audit',
]

export const w11d2: DailyCourse = {
  id: 'W11D2',
  contentVersion: 'w11d2-tool-calling-day01-v2',
  week: 11,
  day: 2,
  title: '工具调用',
  subtitle: '让 AI 只能提出结构化动作请求，再由确定性系统完成工具选择、参数、权限、确认、执行与回执闭环。',
  duration: { core: 30, standard: 45, extension: 38, full: 88 },
  coreConceptGroups: [
    {
      id: 'tool-boundary-and-contract',
      title: '先定义 AI 能提议什么，再定义工具接受什么',
      conceptIds: ['tool-action-boundary', 'tool-registry-schema'],
      summary: '模型产生的是候选文本或结构化动作意图；工具目录与参数 schema 才规定可用动作、必填字段和返回结构。',
      boundary: '模型说“我会执行”不是工具调用证据；目录中存在某个工具也不代表当前用户有权调用。',
    },
    {
      id: 'tool-proposal-and-validation',
      title: '把动作意图变成可拒绝的结构化提案',
      conceptIds: ['tool-call-proposal', 'tool-argument-validation'],
      summary: '模型或编排层从允许目录选择工具并填写参数，应用再用确定性 schema 与业务规则逐字段校验。',
      boundary: '提案与参数通过都发生在执行器之前，既不授予权限，也不证明任何业务副作用。',
    },
    {
      id: 'tool-authorization-and-confirmation',
      title: '有权操作与明确同意是两道不同门槛',
      conceptIds: ['tool-authorization', 'tool-human-confirmation'],
      summary: '系统根据真实身份、资源范围和动作风险决定权限，再为需要确认的动作取得可审计的明确同意。',
      boundary: '权限允许不等于用户已确认；自然语言中的模糊肯定也不能替代高风险动作的明确确认。',
    },
    {
      id: 'tool-execution-and-receipt',
      title: '执行器产生副作用，回执约束最终交付',
      conceptIds: ['tool-execution-side-effect', 'tool-result-receipt'],
      summary: '只有跨过全部门槛的调用才进入执行器；交付层必须依据 callId、结果代码和状态核验表达成功、失败或结果不确定。',
      boundary: '本课执行器只改动本地教学对象；教学成功、失败或超时都不能证明生产工具和真实业务状态。',
    },
  ],
  prerequisiteConceptIds,
  learningPaths: {
    '30': {
      guidedStepIndices: [0, 1, 2, 3, 4, 5],
      guidedRecordIndices: [0, 1, 2],
      exerciseCount: 3,
      deliverablePromptCount: 4,
      deliverableChecklistIndices: [0, 1, 2, 3],
      deliverableMinimumContributionCharacters: 100,
    },
    '45': {
      guidedStepIndices: [0, 1, 2, 3, 4, 5],
      guidedRecordIndices: [0, 1, 2, 3],
      exerciseCount: 4,
      deliverablePromptCount: 8,
      deliverableChecklistIndices: [0, 1, 2, 3, 4, 5, 6, 7],
      deliverableMinimumContributionCharacters: 160,
    },
  },
  primaryGoal: '独立画出一张 AI 调用图，标清工具合同、调用提案、四道执行门槛、失败停止点、真实副作用和结果回执的证据边界。',
  scenario: {
    role: '你是评审“售后动作助手”的产品经理，只使用脱敏、本地教学模拟。',
    situation: '用户要求助手为模拟订单 SIM-104 创建售后申请。团队只写了“让模型调 create_return_case”，没有说明工具是否允许、参数是否完整、当前用户是否有权、是否取得明确确认、执行失败怎样处理以及什么才算成功。',
    question: '怎样把一句动作请求变成逐层可拒绝、可恢复、可追溯的工具调用，并避免用模型文案冒充真实结果？',
    stakes: '任何缺失的确定性门槛都可能把模型的不确定输出放大为越权操作、重复副作用、虚假成功或无法恢复的业务事故。',
  },
  objectives: [
    { id: 'w11d2-objective-contract', text: '读懂工具目录与参数合同', evidence: '能从工具名、用途、参数 schema、风险等级和返回结构判断调用是否可进入提案阶段。' },
    { id: 'w11d2-objective-gates', text: '逐层判断调用是否可以继续', evidence: '能按提案、参数校验、权限、确认和执行顺序指出首次停止点。' },
    { id: 'w11d2-objective-evidence', text: '区分提案、门槛、执行与业务结果', evidence: '对六种教学模拟记录 executorCalled、receipt、首次分叉和有限结论。' },
    { id: 'w11d2-objective-deliver', text: '提交可评审的 AI 调用图', evidence: '成果包含八个关键阶段、失败恢复、runId／callId、责任人、证据和未知事项。' },
  ],
  prerequisites: [
    {
      id: 'w11d2-ai-chain-readiness',
      conceptIds: ['ai-feature-system', 'ai-request-context', 'model-generation-boundary', 'ai-capability-slots-overview', 'ai-policy-orchestration', 'ai-output-handoff', 'ai-observation-audit'],
      prompt: '你能从请求讲到上下文、模型候选、动作能力槽位、业务规则、交付与审计，并说明候选不等于动作吗？',
      passDescription: '能闭卷讲出 W11D1 七层系统链，并把模型候选、业务决定和动作结果分开。',
      remediationLabel: '补学 W11D1：AI 系统链',
      remediationTarget: '#/lesson/W11D1',
      remediation: {
        purpose: '本课只展开动作能力槽位；先会读整体系统链，才能把工具调用放回正确位置。',
        steps: ['回到 W11D1 复述七层系统链。', '各写一句模型候选、业务决定与动作结果。', '用同一 runId 写一次能力阻断的有限结论。'],
        successCheck: '不看页面说明模型为什么只能提出动作候选，以及工具为何仍要经过业务规则和审计。',
      },
    },
    {
      id: 'w11d2-request-rule-readiness',
      conceptIds: ['http-request', 'http-response', 'business-rule'],
      prompt: '你能区分 Request、确定性业务规则和 Response，并说明“发送了参数”不等于“服务端接受或完成”吗？',
      passDescription: '能把请求输入、规则判断和返回结果分成三层证据。',
      remediationLabel: '补学 W1D3–W1D4：请求与规则',
      remediationTarget: '#/lesson/W1D4',
      remediation: {
        purpose: '工具调用仍然是受控的软件请求；模型自然语言不能替代参数、规则和结构化返回。',
        steps: ['回到 W1D3 复述 Request 与 Response。', '回到 W1D4 观察一次规则拒绝。', '写一句“请求到达但业务未执行”的有限结论。'],
        successCheck: '面对一次工具请求，能分别指出输入、规则结果、执行回执和仍未知的业务事实。',
      },
    },
  ],
  concepts: [
    {
      id: 'tool-action-boundary', prerequisiteConceptIds: ['model-generation-boundary', 'ai-capability-slots-overview'],
      term: '工具调用的动作边界', english: 'Tool Calling Action Boundary',
      definition: '工具调用是 AI 应用把结构化动作请求交给受控软件能力的机制；模型最多提出调用候选，应用系统决定是否允许、怎样执行和如何交付结果。',
      why: '模型输出具有概率性，而发信、改订单、创建工单等动作可能改变外部状态，必须把语言生成和真实副作用隔开。',
      problemSolved: '把“AI 会做这件事”的模糊承诺拆成可观察、可拒绝、可追溯的动作流水线。',
      input: '用户任务、当前获准上下文、允许动作范围和模型生成的候选意图。',
      output: '继续形成工具调用提案，或停留在回答、澄清、拒绝和人工接管等非执行路径。',
      systemPosition: '位于模型候选与业务动作之间，是从生成层进入确定性控制层的边界。',
      process: ['识别请求是否真的需要外部动作。', '只让模型产生候选工具意图，不直接接触执行器。', '由应用层决定进入提案还是采用非执行交付。'],
      owner: '产品经理定义可用动作与风险边界，应用研发和安全负责人实现隔离，模型不拥有最终执行权。',
      notResponsibleFor: '动作边界本身不选择具体工具、不验证参数，也不证明任何外部状态已经改变。',
      compareWith: '普通文本生成只返回候选内容；工具调用可能触达外部系统，因此必须增加确定性门槛与结果核验。',
      evidence: ['本次任务的 actionNeeded 决定与允许能力范围。', '进入非执行路径或提案路径的明确分支记录。'],
      failureModes: ['模型生成“已完成”文案后系统直接当成动作结果。', '所有用户请求都默认进入工具执行路径。'],
      pmUse: '评审 AI 功能时先列出哪些请求只回答、哪些可提议动作、哪些动作永远需要人工处理。',
      correctExample: '用户说“帮我创建售后申请”时，系统只把它标为 action_candidate，等待后续工具门槛。',
      incorrectExample: '模型回复“已创建售后申请”，页面立即展示成功，却没有任何结构化调用记录。',
    },
    {
      id: 'tool-registry-schema', prerequisiteConceptIds: ['tool-action-boundary'],
      term: '工具目录与参数合同', english: 'Tool Registry and Schema',
      definition: '工具目录是应用允许 AI 提议的能力清单；每个工具合同写清用途、参数名称与类型、必填规则、风险等级和结构化返回。',
      why: '如果工具名和输入规则只存在于自然语言提示中，模型可能编造工具、漏填字段或把不同动作混为一谈。',
      problemSolved: '把无限的语言空间收敛成应用能够校验和拒绝的有限动作接口。',
      input: '已批准的业务能力、接口字段、参数类型、动作风险、权限要求和返回约定。',
      output: '带版本的工具定义，例如 toolName、description、argumentsSchema、riskLevel 与 resultSchema。',
      systemPosition: '位于调用提案之前，为工具选择、参数生成和后续校验提供唯一合同。',
      process: ['只注册业务明确允许的工具。', '为每项参数定义类型、必填、枚举和说明。', '为返回结果和风险等级建立可版本化约定。'],
      owner: '工具平台与服务端研发维护技术合同，业务产品定义用途与边界，安全负责人审阅风险和权限要求。',
      notResponsibleFor: '目录存在不等于当前用户获权；schema 完整也不能保证模型会填对或执行器会成功。',
      compareWith: 'Prompt 可以解释工具用途，但工具目录和 schema 才是应用可确定校验的机器合同。',
      evidence: ['registryVersion、允许工具名和风险等级。', 'argumentsSchema 与 resultSchema 的字段、类型和必填标记。'],
      failureModes: ['模型提出目录中不存在的 delete_all_orders。', 'schema 没定义必填字段，导致空参数进入后续流程。'],
      pmUse: '为每个工具评审“为何存在、谁能用、必要字段、失败返回、是否可逆和何时需要确认”。',
      correctExample: 'create_return_case 只接受 orderId 与 reasonCode，风险为 medium，返回 callId、caseId 和 resultCode。',
      incorrectExample: '只在系统提示中写“必要时调用售后工具”，没有工具名、参数结构和版本。',
    },
    {
      id: 'tool-call-proposal', prerequisiteConceptIds: ['tool-registry-schema'],
      term: '工具选择与调用提案', english: 'Tool Selection and Call Proposal',
      definition: '模型或编排层从允许目录中选择一个工具，并输出包含工具名、结构化参数和调用目的的待审提案；此时状态只是 proposed。',
      why: '把动作意图转成固定结构后，应用才能逐层检查，而不是从一段自然语言里猜测要执行什么。',
      problemSolved: '让“模型想做什么”成为独立可记录、可拒绝且尚未产生副作用的对象。',
      input: '用户动作意图、允许工具目录、工具说明、参数 schema 和本次获准上下文。',
      output: 'proposalId、toolName、arguments、reason 与 proposed 状态，或 unsupported_tool 拒绝。',
      systemPosition: '位于工具目录之后、所有确定性门槛之前，连接概率性模型与应用控制层。',
      process: ['从允许目录中选择满足任务的工具。', '按 schema 生成结构化参数。', '应用解析并保存提案，不在此阶段调用执行器。'],
      owner: '模型或编排层生成候选，应用研发负责解析与目录约束，产品经理定义允许出现提案的场景。',
      notResponsibleFor: '提案不保证参数正确、不授予权限、不代表用户确认，也不证明工具已经运行。',
      compareWith: '工具目录定义“可以提议什么”；调用提案记录“这一次模型具体想提议什么”。',
      evidence: ['proposalId、toolName、arguments 和 proposed 状态。', '本次提案引用的 registryVersion 与用户任务。'],
      failureModes: ['编造未注册工具或选择与任务不匹配的工具。', '用一句“已经完成”代替结构化调用提案。'],
      pmUse: '需求中明确模型最多可以提出哪种动作，并为 unsupported_tool 与歧义意图设计恢复路径。',
      correctExample: '模型提出 create_return_case({orderId:"SIM-104",reasonCode:"DAMAGED"})，状态仍为 proposed。',
      incorrectExample: '模型说“我来处理”，应用便绕过提案对象直接请求售后服务。',
    },
    {
      id: 'tool-argument-validation', prerequisiteConceptIds: ['tool-call-proposal', 'business-rule'],
      term: '工具参数校验', english: 'Tool Argument Validation',
      definition: '执行前用确定性 schema 与业务规则检查工具名、必填参数、类型、枚举、对象存在性和当前状态是否允许。',
      why: '模型可能漏字段、填错类型或引用不存在的对象；错误参数进入真实系统会把语言错误放大成业务副作用。',
      problemSolved: '在权限和执行之前拦截未知工具、缺字段、错误类型和不满足当前业务状态的调用。',
      input: '结构化调用提案、registryVersion、argumentsSchema 和当前业务状态摘要。',
      output: 'validated 或 rejected 结果，以及逐字段错误原因，不静默猜测或修正高风险参数。',
      systemPosition: '位于调用提案之后、身份权限判断之前，是应用层第一组确定性门槛。',
      process: ['核对工具名与合同版本。', '按 schema 检查必填、类型和枚举。', '按业务规则检查对象与当前状态，失败则返回可恢复错误。'],
      owner: '应用与工具平台研发实现，业务产品和服务端负责人共同定义 schema、业务状态与恢复提示。',
      notResponsibleFor: '参数通过不等于调用者有权，也不等于用户已经确认、执行器成功或业务最终完成。',
      compareWith: '模型按概率生成参数；确定性校验按固定合同判断输入能否进入下一门槛。',
      evidence: ['schemaVersion、逐字段校验结果和 rejectionReason。', '校验时引用的对象状态摘要。'],
      failureModes: ['缺少 orderId 仍交给执行器。', '把字符串数量当作数字且没有按合同拦截。'],
      pmUse: '为每个工具列出必填、类型、枚举、对象状态和用户可修复错误，并纳入验收矩阵。',
      correctExample: '缺少 reasonCode 时返回 ARGUMENT_MISSING，保留草稿并请求补充，不运行执行器。',
      incorrectExample: '参数不完整时让模型猜一个 reasonCode 后继续创建售后申请。',
    },
    {
      id: 'tool-authorization', prerequisiteConceptIds: ['tool-argument-validation', 'ai-policy-orchestration'],
      term: '工具身份与权限校验', english: 'Tool Authorization',
      definition: '系统依据经过验证的调用者身份、目标资源、动作类型和当前策略，决定这个主体此刻是否可以调用该工具。',
      why: '参数合法只说明输入符合合同；越权调用仍可能读取或改变不属于当前用户的业务对象。',
      problemSolved: '阻止模型、匿名用户或低权限角色借由合法参数访问不获准的资源与动作。',
      input: '可信 actorId 摘要、资源所有权、动作类型、policyVersion 和已经通过的参数。',
      output: 'authorized、denied 或 human_review 决定及 reason，不把页面按钮可见性当作服务端授权。',
      systemPosition: '位于参数校验之后、人工确认与执行器之前，是决定主体能否继续的安全门槛。',
      process: ['从可信会话获得调用者身份。', '检查资源范围、角色和动作权限。', '拒绝时记录原因并保证执行器未被调用。'],
      owner: '身份权限系统、服务端与安全负责人实现，业务产品定义角色资源动作矩阵和拒绝体验。',
      notResponsibleFor: '权限允许不代表用户同意本次高风险动作，也不保证执行器稳定或结果符合预期。',
      compareWith: '参数校验回答“输入是否合法”；权限校验回答“这个主体能否对这个对象做这件事”。',
      evidence: ['actorId 摘要、resourceScope、policyVersion、decision 与 reason。', '拒绝路径上的 executorCalled=false。'],
      failureModes: ['只在前端隐藏按钮，执行器仍接受越权请求。', '使用模型猜测的用户身份完成授权。'],
      pmUse: '用“谁、对什么、做什么、在什么条件下”评审每个工具，并覆盖匿名、非所有者和越权角色。',
      correctExample: '模拟订单不属于 actor-guest 时返回 AUTHORIZATION_DENIED，并停在执行器之前。',
      incorrectExample: '模型觉得用户语气可信，于是绕过所有权校验继续执行。',
    },
    {
      id: 'tool-human-confirmation', prerequisiteConceptIds: ['tool-authorization'],
      term: '风险分级与人工确认', english: 'Risk Gate and Human Confirmation',
      definition: '系统按动作副作用、可逆性和业务风险决定是否需要预览与明确确认，并把本次确认绑定到具体工具、对象和参数。',
      why: '即使用户有权，发信、提交申请或改变状态仍可能违背其真实意图；高风险动作不能由模型替用户同意。',
      problemSolved: '在执行前让人看见“将做什么、影响谁、关键参数是什么”，并保留可审计的同意或取消。',
      input: '已授权提案、riskLevel、动作摘要、关键参数、可逆性和当前确认状态。',
      output: 'confirmed、cancelled、preview_only 或 confirmation_required，以及与提案绑定的 confirmationId。',
      systemPosition: '位于身份权限之后、执行器之前，是产生副作用前的人类控制点。',
      process: ['根据风险等级决定是否需要确认。', '向用户展示工具、对象和关键参数的预览。', '只接受与当前提案绑定的明确确认，取消或缺失则停止。'],
      owner: '产品经理设计风险分级与交互，业务和安全负责人定义强制确认范围，用户完成最终同意。',
      notResponsibleFor: '确认不替代权限检查，也不证明执行器成功或外部系统已经完成动作。',
      compareWith: '权限说明主体可以做；人工确认说明主体对这一次具体动作明确同意。',
      evidence: ['riskLevel、预览内容、confirmationId、confirmedAt 与关联 proposalId。', '缺少确认时 executorCalled=false。'],
      failureModes: ['把“好的”绑定到错误或已经变化的提案。', '模型根据上下文自行补出用户确认。'],
      pmUse: '为不可逆、外部通知、资金和状态变更类工具定义预览、确认、取消与过期规则。',
      correctExample: '展示 SIM-104 与 DAMAGED 后，用户按“确认创建”，生成绑定当前 proposalId 的 confirmationId。',
      incorrectExample: '用户只说“了解”，模型便把它当作同意创建售后申请。',
    },
    {
      id: 'tool-execution-side-effect', prerequisiteConceptIds: ['tool-human-confirmation', 'http-request'],
      term: '工具执行器与副作用', english: 'Tool Executor and Side Effect',
      definition: '执行器是接收已通过全部门槛的调用并尝试改变外部或业务状态的软件组件；副作用是调用前后可观察的状态变化。',
      why: '真正风险发生在执行阶段；必须知道执行器是否被调用、是否返回失败，以及超时后业务状态是否仍不确定。',
      problemSolved: '把“准备执行”与“执行器已经收到调用”分开，并为失败、超时和未知结果保留恢复空间。',
      input: '已验证、已授权、必要时已确认的调用，callId 和执行前状态摘要。',
      output: '执行成功、明确失败或结果不确定状态，以及可能的业务对象变化。',
      systemPosition: '位于所有前置门槛之后、结果回执之前，是唯一可能产生真实业务副作用的阶段。',
      process: ['为获准调用分配 callId 并记录执行前状态。', '执行器尝试完成指定动作。', '区分成功、明确失败与超时未知，未知时先查状态而非盲目重做。'],
      owner: '工具执行服务负责动作与失败语义，应用层负责调用控制，业务系统负责最终对象状态。',
      notResponsibleFor: '执行器被调用不等于动作成功；超时也不能直接证明业务状态未变化。',
      compareWith: '确认发生在执行前并表达同意；执行器调用才可能产生副作用，但仍需结果回执核验。',
      evidence: ['callId、executorCalled、开始时间、执行状态和调用前后摘要。', '失败码或 timeout_unknown 标记。'],
      failureModes: ['执行器超时后页面直接宣布失败并立即重复调用。', '前置门槛失败却仍出现 executorCalled=true。'],
      pmUse: '把执行结果至少分成成功、明确失败和结果不确定，并为不确定状态设计查询与人工接管。',
      correctExample: '教学执行器超时后返回 TOOL_TIMEOUT_UNKNOWN，保持 callId 并提示先核对状态。',
      incorrectExample: '没有回执就认定未执行，再次创建同一个售后申请。',
    },
    {
      id: 'tool-result-receipt', prerequisiteConceptIds: ['tool-execution-side-effect', 'http-response', 'ai-output-handoff', 'ai-observation-audit'],
      term: '工具结果回执与交付审计', english: 'Tool Result Receipt and Audited Handoff',
      definition: '结果回执是与 callId 关联的结构化执行结果；交付层只依据回执和必要的业务状态核验，向用户表达成功、失败、待确认或人工接管。',
      why: '模型可以生成任何成功文案，但只有可关联回执才能说明工具走到了哪一步并支持后续追溯。',
      problemSolved: '防止虚假成功、丢失失败原因和无法关联提案、门槛决定、执行结果与最终用户提示。',
      input: 'callId、executorCalled、resultCode、对象标识、前后状态、门槛记录和交付规则。',
      output: '受证据约束的用户提示、审计记录和恢复动作；结果不确定时不得伪装成成功或未发生。',
      systemPosition: '位于执行器之后，连接业务状态、用户交付和同一 runId 下的审计追踪。',
      process: ['读取结构化 resultCode 与对象状态。', '按成功、明确失败、未知结果选择对应交付。', '把 proposalId、confirmationId、callId 与最终提示写入审计关联。'],
      owner: '工具服务提供回执，应用交付层负责诚实表达，审计系统负责关联记录，产品定义恢复体验。',
      notResponsibleFor: '本地教学回执不证明生产工具、真实账号或线上业务已变化，也不能说明长期稳定性。',
      compareWith: '模型候选描述可能发生什么；结果回执记录执行器实际返回什么，业务状态核验再确认最终结果。',
      evidence: ['callId、resultCode、objectId、before/after 和 deliveryState。', '同一 runId 下提案、门槛、执行与审计关联。'],
      failureModes: ['执行失败却沿用模型生成的成功文案。', '只保存最终提示，没有 callId 与上游门槛记录。'],
      pmUse: '把验收写到回执和最终业务状态层，并要求每种结果都有用户提示、恢复路径和审计关联。',
      correctExample: '本地模拟返回 SIM_CASE_CREATED、caseId=SIM-CASE-042，页面注明“教学模拟，不代表真实售后单”。',
      incorrectExample: '只要模型输出 tool_call，就把订单状态显示成“已创建售后”。',
    },
  ],
  diagram: {
    title: '受控工具调用链：模型提议，系统门槛决定，回执约束交付',
    caption: '沿同一 runId 从动作意图走到 proposalId、confirmationId 与 callId；任何失败都停在首次分叉，只有执行器可能产生副作用。',
    nodes: [
      { id: 'intent', label: '动作意图', description: '识别是否需要外部动作，不把模型文案当结果。', input: '脱敏用户请求', output: 'action_candidate', owner: '应用编排', evidence: 'runId、actionNeeded' },
      { id: 'registry', label: '工具目录／schema', description: '限定可提议工具及其参数与返回合同。', input: '已批准能力', output: 'tool definitions', owner: '工具平台', evidence: 'registryVersion' },
      { id: 'proposal', label: '选择／调用提案', description: '形成结构化工具名、参数和调用目的。', input: '意图与目录', output: 'proposalId', owner: '模型与编排', evidence: 'toolName、arguments' },
      { id: 'validation', label: '参数／业务校验', description: '按确定性合同检查字段、类型和对象状态。', input: '调用提案', output: 'validated／rejected', owner: '应用规则', evidence: 'schemaVersion、reason' },
      { id: 'authorization', label: '身份／权限', description: '确认主体是否能对目标对象执行动作。', input: 'actor、resource、policy', output: 'allow／deny', owner: '权限系统', evidence: 'policyVersion、decision' },
      { id: 'confirmation', label: '风险／人工确认', description: '向用户预览具体动作并取得绑定提案的明确确认。', input: '获准提案与风险', output: 'confirmationId／cancel', owner: '产品与用户', evidence: 'confirmedAt' },
      { id: 'executor', label: '执行器／副作用', description: '只接收跨过全部门槛的调用并尝试改变状态。', input: '获准且确认的 call', output: 'success／failure／unknown', owner: '工具服务', evidence: 'executorCalled、callId' },
      { id: 'receipt', label: '结果回执／交付审计', description: '依据结构化结果和状态核验表达最终交付。', input: 'resultCode 与状态', output: '有限提示与审计', owner: '交付与审计', evidence: 'receipt、deliveryState' },
    ],
    branches: [
      { from: 'intent', to: 'registry', label: '需要受控动作', kind: 'normal' },
      { from: 'registry', to: 'proposal', label: '工具已注册', kind: 'normal' },
      { from: 'proposal', to: 'validation', label: '结构化提案', kind: 'normal' },
      { from: 'validation', to: 'authorization', label: '参数与业务状态通过', kind: 'normal' },
      { from: 'authorization', to: 'confirmation', label: '主体获权', kind: 'normal' },
      { from: 'confirmation', to: 'executor', label: '必要确认完成', kind: 'normal' },
      { from: 'executor', to: 'receipt', label: '返回结构化结果', kind: 'normal' },
      { from: 'registry', to: 'proposal', label: '工具不支持则拒绝', kind: 'failure' },
      { from: 'validation', to: 'authorization', label: '参数失败则停止', kind: 'failure' },
      { from: 'authorization', to: 'confirmation', label: '越权则停止', kind: 'failure' },
      { from: 'confirmation', to: 'executor', label: '缺少确认则停止', kind: 'failure' },
      { from: 'executor', to: 'receipt', label: '失败或未知也必须回执', kind: 'failure' },
    ],
    evidenceNotes: ['提案证据看 registryVersion、proposalId、toolName 与 arguments，不能证明门槛通过。', '门槛证据分别看 validation、authorization 与 confirmation，不可合并成一句“系统允许”。', '执行与交付证据看 executorCalled、callId、resultCode、状态核验和审计关联；所有运行均为本地教学模拟。'],
  },
  demonstration: {
    title: '教师示范：受控创建一个本地教学售后申请',
    businessProblem: '用户明确要求为模拟订单 SIM-104 创建售后申请；系统必须从工具目录开始，逐层校验参数、身份权限和确认，再依据执行回执交付。',
    finalConclusion: '本次教学模拟通过工具合同、结构化提案、参数、权限与确认门槛后，执行器返回 SIM_CASE_CREATED，并用同一 runId 关联 proposalId、confirmationId 与 callId。',
    conclusionLimit: '不能证明真实模型选择稳定、生产权限正确、真实售后单已创建、外部副作用可恢复或线上系统可用。',
    steps: [
      { title: '固定动作与运行标识', action: '记录 actor-demo、模拟订单 SIM-104、动作目标和 run-tool-001。', reason: '先固定主体、对象和意图，避免后续记录来自不同请求。', evidence: 'actionNeeded=true、runId、actor 与 target。', proves: '本次教学模拟输入已经固定。', limitation: '不能证明真实用户、订单或账号存在。' },
      { title: '读取工具目录与合同', action: '确认 registry v2 只允许 create_return_case，并查看 orderId、reasonCode 与返回结构。', reason: '模型只能从获准工具和明确 schema 中提出动作。', evidence: 'registryVersion、toolName、argumentsSchema、riskLevel。', proves: '本次模拟有可校验的工具合同。', limitation: '不能证明模型会选对工具或当前用户有权限。' },
      { title: '形成结构化调用提案', action: '生成包含 SIM-104 与 DAMAGED 的 proposal-001，状态保持 proposed。', reason: '把动作意图变成独立可检查对象，同时确保执行器尚未运行。', evidence: 'proposalId、toolName、arguments、executorCalled=false。', proves: '系统准备了一个调用候选。', limitation: '不能证明参数、权限和确认已通过。' },
      { title: '校验参数与业务状态', action: '按 registry v2 核对必填、类型、枚举和模拟订单状态。', reason: '概率性参数必须经过确定性合同与业务规则。', evidence: 'validation=passed、schemaVersion、state=eligible。', proves: '本次提案的模拟参数和状态通过校验。', limitation: '不能证明调用主体获权或执行会成功。' },
      { title: '核验权限并取得确认', action: '确认 actor-demo 是模拟订单所有者，展示动作预览后生成 confirmation-001。', reason: '有权操作与同意本次具体动作是两道不同门槛。', evidence: 'authorization=allowed、policyVersion、confirmationId。', proves: '本次教学主体和确认满足模拟策略。', limitation: '不能证明生产身份系统或真实用户同意。' },
      { title: '执行并依据回执交付', action: '本地执行器把 no_case 改为 case_created，返回 SIM_CASE_CREATED 和 call-001。', reason: '只有结构化回执与状态变化才能约束最终成功提示。', evidence: 'executorCalled=true、callId、resultCode、before/after、audit=appended。', proves: '本地教学执行器返回成功并改变模拟状态。', limitation: '不能证明任何真实售后申请或外部系统副作用。' },
    ],
  },
  guidedLab: {
    title: '工具调用六路径门槛观察台',
    goal: '固定同一个售后动作，依次观察不支持的工具、参数缺失、权限拒绝、缺少确认、执行失败／结果不确定和教学成功。',
    safety: '纯本地教学模拟；不调用真实模型、工具、账号、Token、公司数据或生产系统，成功只修改内存中的模拟订单。',
    conceptIds: [...conceptIds],
    predictionPrompt: '六条路径各会在哪一层首次停止？哪些失败必须保持 executorCalled=false，哪条失败已经进入执行器但不能宣布状态未变？',
    steps: [
      { title: '拒绝不支持的工具', action: '选择“工具未注册”并运行。', observe: 'registry=unsupported_tool、proposal=rejected、executorCalled=false。', explanation: '模型只能从应用允许目录提出工具。', proves: '本次模拟在目录边界拒绝未知工具。', cannotProve: '生产目录已经覆盖全部正确工具。' },
      { title: '触发参数拒绝', action: '选择“工具参数缺失”并运行。', observe: 'proposal=created、validation=ARGUMENT_MISSING、executorCalled=false。', explanation: '提案必须跨过确定性 schema 门槛。', proves: '本次模拟在执行前拦截缺字段。', cannotProve: '真实 schema 已覆盖全部业务风险。' },
      { title: '触发权限拒绝', action: '选择“工具权限拒绝”并运行。', observe: '参数通过、authorization=denied、executorCalled=false。', explanation: '参数合法与主体获权是两件事。', proves: '本次模拟权限门槛阻止了副作用。', cannotProve: '生产权限策略配置正确。' },
      { title: '触发确认阻断', action: '选择“缺少人工确认”并运行。', observe: '权限通过、confirmation=required_missing、executorCalled=false。', explanation: '高风险动作不能由模型替用户确认。', proves: '本次模拟在执行前等待明确同意。', cannotProve: '真实确认交互不会被绕过或过期。' },
      { title: '观察执行失败／结果不确定', action: '选择“工具执行失败”并运行。', observe: 'executorCalled=true、receipt=TOOL_TIMEOUT_UNKNOWN+callId。', explanation: '进入执行器后，超时不等于业务状态未变化，必须保留 callId 核对。', proves: '本次模拟区分了执行前拒绝与执行后未知。', cannotProve: '真实工具一定未产生副作用。' },
      { title: '运行工具教学成功', action: '选择“工具教学成功”并运行。', observe: '全部门槛通过、executorCalled=true、返回 SIM_CASE_CREATED+callId。', explanation: '只有回执与模拟状态变化支持本地成功结论。', proves: '教学执行器成功修改内存状态。', cannotProve: '真实售后单、支付或物流状态改变。' },
    ],
    recordPrompts: ['记录六种变式的 runId、最后成功阶段、首次变化阶段与 executorCalled。', '分别摘录一条工具目录／提案证据、一道门槛证据和一条执行／回执证据。', '为不支持、参数拒绝、权限拒绝、确认缺失与超时未知分别写恢复路径。', '各写两项教学模拟能证明与不能证明的事实。'],
    comparePrompt: '保持用户动作、模拟订单与工具目标不变，只改变目录、参数、身份、确认或执行结果；比较首次分叉、执行器状态和最终交付。',
    passCriteria: ['六种工具调用教学变式全部运行并保留独立 runId。', '目录、参数、权限或确认失败时 executorCalled 均为 false。', '执行超时路径保留 callId 并标记结果不确定，不盲目宣称未发生。', '成功路径只声明内存教学状态变化，不冒充真实售后申请。'],
  },
  independentLab: {
    title: '独立变式：会议排期助手创建日历事件',
    scenario: '把售后助手换成会议排期助手。它可提议 create_calendar_event，但不能替用户邀请未获准联系人，也不能在时区、参会人或发送邀请确认缺失时执行。',
    conceptIds: [...conceptIds],
    changedConditions: ['把已注册工具改为模型编造的 send_private_summary。', '删掉必填 timezone，只保留模糊的“明天下午”。', '把 attendeeIds 改成当前用户无权邀请的外部联系人。', '保留完整参数和权限，但撤销“发送邀请”明确确认。', '让执行器返回 CALENDAR_TIMEOUT_UNKNOWN，但保留 callId。'],
    task: '画出从动作意图到结果回执的调用链，改变一个条件，预测首次停止点，记录 executorCalled 与回执，并用四句式说明有限结论和安全恢复。',
    predictionPrompt: '改变的条件会先影响工具目录、参数、权限、确认还是执行器？为什么后续步骤必须停止或进入状态核验？',
    evidenceRequirements: ['原始条件、工具合同版本、提案字段、首次分叉与 executorCalled。', '权限／确认决定或结构化结果回执，以及同一 runId／callId 关联。', '分别写明能证明、不能证明与下一步恢复证据。'],
    passCriteria: ['只改变一个条件，并保持用户任务和其余合同不变。', '预测先于操作，结果逐层引用真实教学字段。', '执行前失败明确 executorCalled=false；超时未知不声称业务未变化。', '结论明确标注教学模拟且不扩大到真实日历、联系人或外部通知。'],
    remediation: { label: '回看完整示范的有限结论', sectionId: 'demonstration', anchor: '#demonstration-conclusion' },
  },
  exercises: [
    {
      id: 'w11d2-tool-boundary', kind: 'single-choice', categories: ['概念与边界'], conceptIds: ['tool-action-boundary', 'tool-registry-schema', 'tool-call-proposal'],
      prompt: '模型生成“我已经帮你创建售后申请”，但没有 proposalId。当前最准确的判断是什么？',
      hint: '先区分候选文案、结构化提案与执行回执。',
      options: [
        { label: '工具已经成功执行', rationale: '文案不能替代结构化调用和结果证据。', couldBeTrueWhen: '只有存在执行回执和必要业务状态核验时才能说成功。' },
        { label: '目前只有候选文案，没有可核验的工具调用提案', rationale: '缺少 proposalId、工具名和参数，仍未进入确定性门槛。', couldBeTrueWhen: '这正符合题目给出的现有证据。' },
        { label: '当前用户一定没有权限', rationale: '缺少提案并不能反推出权限决定。', couldBeTrueWhen: '只有权限系统返回 denied 才能支持该说法。' },
      ],
      answerIndex: 1,
      referenceAnswer: '模型文案只是候选内容；没有结构化 proposalId 时，不能证明工具选择、参数、门槛或执行发生。',
      reasoning: ['工具调用从允许目录和结构化提案开始。', '提案仍不等于执行，当前证据甚至尚未到提案阶段。'],
      rubric: ['指出候选文案边界', '指出缺少 proposalId', '不推断权限或业务结果'],
      commonErrors: [{ error: '把自然语言当结果', reason: '语言看起来确定，也不能产生或证明业务副作用。' }],
      remediation: { label: '回看工具调用的动作边界', sectionId: 'concepts', anchor: '#concept-tool-action-boundary' },
    },
    {
      id: 'w11d2-gate-order', kind: 'single-choice', categories: ['机制推演', '工作场景'], conceptIds: ['tool-argument-validation', 'tool-authorization', 'tool-human-confirmation'],
      prompt: 'create_return_case 参数完整，但订单不属于当前用户。系统下一步最应该怎样处理？',
      hint: '参数合法和主体获权是两道门槛。',
      options: [
        { label: '先执行，再提醒用户无权查看结果', rationale: '越权动作不能通过事后提示补救。', couldBeTrueWhen: '不存在可以让越权执行合理的本课条件。' },
        { label: '权限拒绝并保持 executorCalled=false', rationale: '主体无权操作目标资源，应在执行器之前安全停止。', couldBeTrueWhen: '这正是身份与资源范围不匹配的处理。' },
        { label: '让模型修改 orderId 后继续', rationale: '模型不能猜测另一个业务对象来绕过权限。', couldBeTrueWhen: '只有用户重新选择且系统重新校验的对象才可形成新提案。' },
      ],
      answerIndex: 1,
      referenceAnswer: '参数通过只说明输入符合合同；资源不属于当前主体时应返回 AUTHORIZATION_DENIED，记录 reason 并保证 executorCalled=false。',
      reasoning: ['权限门槛独立于参数校验。', '拒绝后不得进入确认和执行阶段。'],
      rubric: ['首次分叉定位到权限', '执行器未调用', '提供可审计拒绝原因'],
      commonErrors: [{ error: '把参数通过当授权', reason: 'schema 只验证输入形状，不能证明主体对资源有权限。' }],
      remediation: { label: '回看身份与权限校验', sectionId: 'concepts', anchor: '#concept-tool-authorization' },
    },
    {
      id: 'w11d2-timeout-evidence', kind: 'single-choice', categories: ['证据判断', '综合变式'], conceptIds: ['tool-execution-side-effect', 'tool-result-receipt'],
      prompt: '执行器已收到调用，但返回 TOOL_TIMEOUT_UNKNOWN 与 callId。哪条结论最克制？',
      hint: '超时说明没有及时得到确定结果，不等于动作一定未发生。',
      options: [
        { label: '售后申请一定没有创建，可以立即重试', rationale: '超时未知不能证明业务状态未变化，盲目重试可能重复副作用。', couldBeTrueWhen: '只有状态核验明确未创建且恢复规则允许时才可安全重试。' },
        { label: '本次调用已进入执行器，结果仍不确定，应按 callId 核对状态', rationale: '该结论同时引用 executorCalled 和未知回执，没有扩大证据。', couldBeTrueWhen: '这正符合题目给出的教学证据。' },
        { label: '工具已经成功，只是页面没刷新', rationale: '没有成功 resultCode 或状态证据，不能宣布成功。', couldBeTrueWhen: '只有后续状态查询确认对象已创建时才可能成立。' },
      ],
      answerIndex: 1,
      referenceAnswer: '执行器已被调用，但结果不确定；保留 callId 查询状态或转人工，不能宣布成功、失败或直接重复执行。',
      reasoning: ['执行前拒绝与执行后未知的证据不同。', '未知结果需要状态核验而非语言猜测。'],
      rubric: ['引用 executorCalled=true', '保留 callId', '不盲目重试或宣布结果'],
      commonErrors: [{ error: '把超时等同失败', reason: '超时只说明客户端未及时取得确定回执，副作用可能未知。' }],
      remediation: { label: '回看执行器与副作用', sectionId: 'concepts', anchor: '#concept-tool-execution-side-effect' },
    },
    {
      id: 'w11d2-transfer-review', kind: 'single-choice', categories: ['工作场景', '综合变式'], conceptIds: ['tool-registry-schema', 'tool-human-confirmation', 'tool-result-receipt'],
      prompt: '会议助手要创建日历事件并向外部联系人发送邀请，需求评审最少还应补齐哪组合同？',
      hint: '覆盖工具输入、风险门槛、执行结果和用户恢复。',
      options: [
        { label: '只补一段更强的系统 Prompt', rationale: 'Prompt 不能充当参数、权限、确认和回执的确定性边界。', couldBeTrueWhen: 'Prompt 可辅助说明用途，但不能单独满足本题合同。' },
        { label: '参数与时区 schema、联系人权限、发送预览确认、结果回执和失败恢复', rationale: '这组内容覆盖执行前合同、主体与同意，以及执行后证据。', couldBeTrueWhen: '这正是有外部通知副作用的工具所需最小闭环。' },
        { label: '只记录模型回答是否流畅', rationale: '语言质量不证明邀请对象、权限和实际发送结果。', couldBeTrueWhen: '它只能作为文本体验的一项观察，不能替代工具合同。' },
      ],
      answerIndex: 1,
      referenceAnswer: '必须同时定义参数与时区 schema、联系人资源权限、发送预览与明确确认、结构化回执、未知结果和失败恢复。',
      reasoning: ['外部通知既有输入正确性风险，也有越权与误发副作用。', '执行后的交付必须引用回执而不是模型承诺。'],
      rubric: ['合同覆盖执行前后', '明确联系人权限和确认', '包含未知结果恢复'],
      commonErrors: [{ error: '只优化 Prompt', reason: '确定性权限、确认和结果核验不能交给概率性模型。' }],
      remediation: { label: '回看结果回执与交付审计', sectionId: 'concepts', anchor: '#concept-tool-result-receipt' },
    },
  ],
  deliverable: {
    title: 'AI 调用图',
    conceptIds: [...conceptIds],
    purpose: '把一个 AI 动作从语言意图画成团队可逐层评审、阻断、恢复和取证的受控工具调用链。',
    whenToUse: '用于评审 AI 可能读取外部系统、发出通知、创建对象或改变业务状态的功能。',
    audience: '产品、应用研发、服务端、算法、工具平台、安全、运营和人工审核责任人。',
    fields: [
      { name: '场景与主体', meaning: '谁在什么任务中请求哪个对象发生什么动作。', source: '脱敏用户任务、actor 摘要与业务对象。' },
      { name: '工具目录与合同', meaning: '允许工具、用途、schema、风险等级和返回结构。', source: 'registryVersion 与获准工具定义。' },
      { name: '调用提案', meaning: '本次 toolName、arguments、proposalId 与调用目的。', source: '结构化模型或编排输出。' },
      { name: '参数与业务校验', meaning: '逐字段、对象状态和 rejectionReason。', source: 'schemaVersion 与确定性业务规则结果。' },
      { name: '身份权限与确认', meaning: '主体资源范围、policyVersion、风险预览和 confirmationId。', source: '权限服务和明确人工确认记录。' },
      { name: '执行器与副作用', meaning: 'executorCalled、callId、执行前后状态和未知结果。', source: '教学执行器原始记录。' },
      { name: '结果回执与交付审计', meaning: 'resultCode、对象状态、最终提示与全链关联。', source: '结构化回执、状态核验和审计记录。' },
      { name: '失败恢复与证据边界', meaning: '首次分叉、恢复动作、能证明与不能证明的事实。', source: '六路径对照与独立变式记录。' },
    ],
    badExample: 'AI 调用图：用户说创建售后 → AI 调接口 → 成功。',
    badReasons: ['没有工具目录与合同，无法判断工具名和参数是否受控。', '把调用提案、权限、确认、执行和业务结果压成一个“成功”。', '没有 callId、失败恢复、教学模拟标签和不能证明的事项。'],
    revisionSteps: ['先补场景与主体，并写清真实副作用。', '加入工具目录与合同以及结构化调用提案。', '把参数、权限和确认拆成三道可拒绝门槛。', '加入执行器与副作用、结果回执与交付审计。', '为六类失败写首次分叉、恢复和证据边界。'],
    goodExample: `场景与主体：actor-demo 请求为 SIM-104 创建教学售后申请。
工具目录与合同：registry v2；create_return_case(orderId:string, reasonCode:enum)；risk=medium。
调用提案：proposal-001；toolName=create_return_case；arguments={orderId:SIM-104,reasonCode:DAMAGED}；status=proposed。
参数与业务校验：schema passed；模拟订单 state=eligible。
身份权限与确认：policy v4 allowed；confirmation-001 绑定 proposal-001。
执行器与副作用：executorCalled=true；call-001；before=no_case；after=case_created。
结果回执与交付审计：SIM_CASE_CREATED；SIM-CASE-042；runId/proposalId/confirmationId/callId 已关联。
失败恢复与证据边界：目录、参数、权限、确认失败均停在执行前；timeout_unknown 先查 callId。以上仅证明本地教学模拟，不证明真实账号、生产权限或售后单。`,
    guidedPrompts: ['场景与主体：写清 actor、对象、动作与真实副作用。', '工具目录与合同：列出 registryVersion、工具名、参数 schema、风险和返回。', '调用提案：记录 proposalId、toolName、arguments 与 proposed 状态。', '参数与业务校验：写逐字段结果、对象状态与拒绝原因。', '身份权限与确认：分开记录 policy 决定、风险预览与 confirmationId。', '执行器与副作用：记录 executorCalled、callId、before／after 或 unknown。', '结果回执与交付审计：写 resultCode、状态核验、用户提示和关联标识。', '失败恢复与证据边界：写首次分叉、恢复、能证明和不能证明。'],
    blankTemplate: `场景与主体：
工具目录与合同：
调用提案：
参数与业务校验：
身份权限与确认：
执行器与副作用：
结果回执与交付审计：
失败恢复与证据边界：`,
    standardTemplate: `场景与主体：actor=___；对象=___；动作=___；副作用=___。
工具目录与合同：registryVersion=___；toolName=___；argumentsSchema=___；riskLevel=___；resultSchema=___。
调用提案：proposalId=___；arguments=___；当前只证明___。
参数与业务校验：validation=___；objectState=___；rejectionReason=___。
身份权限与确认：authorization=___；policyVersion=___；confirmationId=___。
执行器与副作用：executorCalled=___；callId=___；before/after/unknown=___。
结果回执与交付审计：resultCode=___；deliveryState=___；关联标识=___。
失败恢复与证据边界：firstFork=___；恢复=___；能证明=___；不能证明=___。`,
    checklist: ['场景与主体明确到具体 actor、对象、动作和副作用。', '工具目录与合同包含版本、schema、风险和返回。', '调用提案保持 proposed，不冒充权限或执行结果。', '参数与业务校验、身份权限与确认逐层分开。', '执行器与副作用记录 executorCalled、callId 和状态。', '结果回执与交付审计约束最终用户提示。', '至少覆盖一条执行前拒绝和一条执行后未知路径。', '失败恢复与证据边界明确标注教学模拟和未知事项。'],
  },
  memory: {
    conceptIds: [...conceptIds],
    anchors: ['模型只能提出工具调用候选，不能自授执行权。', '工具目录和 schema 把语言意图收敛成有限合同。', '参数、权限和人工确认是三道不同门槛。', '只有执行器可能产生副作用，超时不等于未发生。', '最终交付必须引用回执与状态，教学模拟不代表生产事实。'],
    closedBookPrompt: '不看页面，按动作边界、目录合同、调用提案、参数校验、权限、确认、执行与回执画出工具调用链，每层说一项证据和一项不能证明的事实。',
    microOperation: '为一个熟悉的 AI 动作写出 toolName、argumentsSchema、proposal、三道门槛和 success／failure／unknown 三类回执。',
    unresolvedPrompt: '真实环境中，哪项工具合同、权限策略、确认交互、执行恢复或业务状态仍需要获准系统证据？',
    reviewStages: [
      { stage: 'D1', task: '闭卷重画八阶段工具调用链，并为每层补一个原始证据字段。' },
      { stage: 'D3', task: '解释参数通过为何不等于获权，获权又为何不等于用户确认。' },
      { stage: 'D7', task: '对照执行前拒绝与执行后超时未知，写出两种不同恢复路径。' },
      { stage: 'D14', task: '把调用图迁移到日历邀请工具，重写 schema、权限、确认和回执。' },
      { stage: 'D30', task: '审阅一个 AI 动作需求，找出至少三处提案、门槛或结果证据缺口。' },
      { stage: 'D60', task: '在新场景闭卷产出完整 AI 调用图，并由他人按证据边界复核。' },
    ],
  },
  nextLesson: {
    id: 'W11D3',
    title: '构建最小评测集',
    bridge: '下一课才首次教学评测样本、评分维度和通过门槛；本课只负责把工具调用的合同、门槛、结果和恢复画清。',
  },
}
