import type { DailyCourse, Exercise } from './types'

const conceptIds = [
  'portfolio-largest-unknown',
  'portfolio-validation-question',
  'portfolio-runnable-check',
  'portfolio-test-fixture',
  'portfolio-pass-fail-criterion',
  'portfolio-run-log',
  'portfolio-observation-boundary',
  'portfolio-validation-decision',
] as const

const prerequisiteConceptIds = [
  'portfolio-system-boundary',
  'portfolio-data-entity',
  'portfolio-data-source-owner',
  'portfolio-io-contract',
  'portfolio-state-lifecycle',
  'portfolio-integration-dependency',
  'portfolio-system-data-decision',
]

function exercise(
  id: string,
  categories: Exercise['categories'],
  conceptIdsForExercise: string[],
  prompt: string,
  options: string[],
  answerIndex: number,
  referenceAnswer: string,
  remediationLabel: string,
): Exercise {
  return {
    id,
    kind: 'single-choice',
    categories,
    conceptIds: conceptIdsForExercise,
    prompt,
    hint: '先看它是否围绕一个最大未知，再看是否有输入夹具、运行步骤、通过标准、观察结果和证据边界。',
    options: options.map((label, index) => ({
      label,
      rationale: index === answerIndex ? '这项把验证问题、运行材料、判定标准和有限结论连在一起，适合进入验证日志。' : '这项要么只是观点，要么缺少可运行步骤，或把一次教学模拟写成真实业务证明。',
      couldBeTrueWhen: index === answerIndex ? '当日志只记录本地教学模拟结果，并明确后续风险和评审仍未完成时。' : '只有补齐可运行记录、复核证据和后续评审后，才可能成为更强结论。',
    })),
    answerIndex,
    referenceAnswer,
    reasoning: ['验证日志回答“最大未知是否被一次可复核运行部分降低”。', '日志必须包含输入、步骤、观察、判定和证据边界。', 'W12D3 只产生验证证据，不提前关闭 W12D4 风险或 W12D5 评审。'],
    rubric: ['最大未知具体', '运行步骤可复核', '通过标准事先写明', '结论不越过教学模拟证据'],
    commonErrors: [
      { error: '把截图或感觉写成验证', reason: '没有输入、步骤、观察和标准，别人无法复核。' },
      { error: '一次通过就说项目可上线', reason: '一次本地教学模拟只能降低一个未知，不能证明真实系统稳定。' },
    ],
    remediation: { label: remediationLabel, sectionId: 'concepts', anchor: `#concept-${conceptIdsForExercise[0]}` },
  }
}

export const w12d3: DailyCourse = {
  id: 'W12D3',
  contentVersion: 'w12d3-runnable-validation-log-day01-v1',
  week: 12,
  day: 3,
  title: '最大未知的可运行验证日志',
  subtitle: '把 W12D2 的 validation_questions 转成一次有限、可复核、可记录的教学模拟运行：选择最大未知、准备测试夹具、写通过/失败标准、执行本地验证并交付 validation-log.csv；不写风险登记册、评审纪要或最终作品集。',
  duration: { core: 30, standard: 45, extension: 60, full: 118 },
  coreConceptGroups: [
    {
      id: 'unknown-question-check',
      title: '先把最大未知压成可验证问题',
      conceptIds: ['portfolio-largest-unknown', 'portfolio-validation-question', 'portfolio-runnable-check'],
      summary: '验证不是把项目全部跑一遍，而是选择当前最会阻断决策的未知，把它改写成可运行、可观察、可判定的问题。',
      boundary: '本组不证明真实系统上线，也不替代 W12D4 风险登记。',
    },
    {
      id: 'fixture-criterion-log',
      title: '用夹具、标准和日志保留运行证据',
      conceptIds: ['portfolio-test-fixture', 'portfolio-pass-fail-criterion', 'portfolio-run-log'],
      summary: '可运行验证需要固定输入材料、预先通过标准和逐项运行记录，否则只是一次不可复核的演示。',
      boundary: '教学夹具只能证明本地模拟路径是否符合预期，不能证明真实生产数据质量。',
    },
    {
      id: 'boundary-decision',
      title: '用观察边界和验证决策控制结论',
      conceptIds: ['portfolio-observation-boundary', 'portfolio-validation-decision'],
      summary: '观察结果必须区分事实、推断和不能证明；验证决策只决定继续、修订或带着风险进入 W12D4。',
      boundary: '本组不提前写风险矩阵、跨职能评审纪要或最终作品集。',
    },
  ],
  prerequisiteConceptIds,
  learningPaths: {
    '30': {
      guidedStepIndices: [0, 1, 2, 3, 4, 5],
      guidedRecordIndices: [0, 1, 2],
      exerciseCount: 3,
      deliverablePromptCount: 5,
      deliverableChecklistIndices: [0, 1, 2, 3, 4],
      deliverableMinimumContributionCharacters: 180,
    },
    '45': {
      guidedStepIndices: [0, 1, 2, 3, 4, 5],
      guidedRecordIndices: [0, 1, 2, 3],
      exerciseCount: 4,
      deliverablePromptCount: 8,
      deliverableChecklistIndices: [0, 1, 2, 3, 4, 5, 6, 7],
      deliverableMinimumContributionCharacters: 300,
    },
  },
  primaryGoal: '提交一份 `validation-log.csv`：至少包含 validation_id、brief_ref、unknown_to_test、validation_question、fixture_used、run_steps、expected_result、observed_result、pass_fail, evidence_collected、decision、cannot_prove、next_action。',
  scenario: {
    role: '你是准备作品集证据链的产品经理实习生。',
    situation: 'W12D2 已经写出系统与数据方案，但评审者不会因为方案完整就相信它有效。你需要选择一个最大未知，用本地教学模拟跑出可复核验证日志。',
    question: '怎样证明“我真的验证过一个关键未知”，同时不把一次教学模拟夸大成真实系统、真实数据或上线结论？',
    stakes: '没有验证日志，作品集停留在设计稿；验证结论越界，又会让面试官质疑证据诚实性。',
  },
  objectives: [
    { id: 'w12d3-objective-unknown', text: '从 W12D2 方案选择一个最大未知', evidence: '日志包含 unknown_to_test 与 validation_question。' },
    { id: 'w12d3-objective-runnable', text: '把未知改写成可运行检查', evidence: '日志包含 fixture_used、run_steps、expected_result。' },
    { id: 'w12d3-objective-log', text: '记录观察结果和通过/失败判定', evidence: '日志包含 observed_result、pass_fail、evidence_collected。' },
    { id: 'w12d3-objective-boundary', text: '写出验证能证明和不能证明什么', evidence: '日志包含 decision、cannot_prove、next_action，且 next_action 只指向 W12D4。' },
  ],
  prerequisites: [
    {
      id: 'w12d3-plan-readiness',
      conceptIds: ['portfolio-system-boundary', 'portfolio-data-entity', 'portfolio-io-contract', 'portfolio-system-data-decision'],
      prompt: '你能从 W12D2 的 system-data-plan.md 说出验证问题、数据对象和输入输出契约吗？',
      passDescription: '能指出一个 validation_question、一个 data_entity 和对应的 required_inputs / outputs。',
      remediationLabel: '补学 W12D2：系统与数据方案',
      remediationTarget: '#/lesson/W12D2',
      remediation: { purpose: 'W12D3 只能验证 W12D2 已提出的问题；没有方案会导致随便跑一次就叫验证。', steps: ['回看 W12D2 的 validation_questions。', '挑出一个 data_entity。', '写出它的输入、输出和错误边界。'], successCheck: '能说出一个可运行验证对象。' },
    },
    {
      id: 'w12d3-dependency-readiness',
      conceptIds: ['portfolio-data-source-owner', 'portfolio-state-lifecycle', 'portfolio-integration-dependency'],
      prompt: '你能区分教学模拟夹具、真实数据缺口和外部依赖吗？',
      passDescription: '能说明 fixture 是教学模拟，真实 owner 或权限仍可能缺失。',
      remediationLabel: '补学 W12D2：来源、状态与依赖',
      remediationTarget: '#/lesson/W12D2',
      remediation: { purpose: '验证日志必须诚实写出本次运行材料，不能把教学样本伪装成生产数据。', steps: ['复述 data_sources。', '标注当前状态和 fallback。', '说明哪些结论仍需要后续风险登记。'], successCheck: '能写出一个“本次不能证明”的句子。' },
    },
  ],
  concepts: [
    {
      id: 'portfolio-largest-unknown', prerequisiteConceptIds: ['portfolio-system-data-decision'],
      term: '最大未知', english: 'Largest Unknown',
      definition: '最大未知是当前最可能阻断下一步判断的问题；如果它不被验证，方案是否值得继续就无法被评审。',
      why: '作品集时间有限，验证要优先降低最关键的不确定性，而不是平均检查所有字段。',
      problemSolved: '回答“现在最需要先验证哪一个问题”。',
      input: 'W12D2 的 validation_questions、dependencies、data_sources 和 evidence_limit。',
      output: 'unknown_to_test，一句具体、有限、可运行的未知。',
      systemPosition: '位于验证日志开头，决定后续夹具、步骤、标准和结论范围。',
      process: ['列出所有验证问题。', '判断哪个最会阻断作品集可信度。', '把它限定成一次可运行检查。'],
      owner: '产品经理提出，导师或评审者可挑战优先级。',
      notResponsibleFor: '最大未知不负责覆盖全部风险，也不代表其他未知已经消失。',
      compareWith: '待办清单列很多任务；最大未知只选择当前最需要降低的不确定性。',
      evidence: ['W12D2 validation_questions。', '依赖和缺失证据清单。'],
      failureModes: ['把“项目是否成功”当成最大未知。', '选择一个不影响决策的小字段。'],
      pmUse: '用它解释为什么本次验证只跑一条关键路径，而不是假装完成全面验收。',
      correctExample: '最大未知：导入 3 条教学失败样本后，系统是否保留 evidence_limit 并生成 human_review_required 记录。',
      incorrectExample: '最大未知：整个 AI 客服项目能不能上线并赚钱。',
    },
    {
      id: 'portfolio-validation-question', prerequisiteConceptIds: ['portfolio-largest-unknown'],
      term: '验证问题', english: 'Validation Question',
      definition: '验证问题把最大未知改写成可以用输入、动作、观察和判定回答的句子。',
      why: '没有验证问题，运行日志会变成流水账；有问题，观察才知道该支持或反驳什么。',
      problemSolved: '回答“这次运行到底要回答哪个有限问题”。',
      input: 'unknown_to_test、系统边界和输入输出契约。',
      output: 'validation_question 字段。',
      systemPosition: '连接最大未知与可运行检查，是日志的判断目标。',
      process: ['写清验证对象。', '写清运行动作。', '写清可观察输出结果。', '写清通过和失败判定条件。'],
      owner: '产品经理撰写，执行者按它运行。',
      notResponsibleFor: '验证问题不负责证明全部业务价值或长期稳定性。',
      compareWith: '假设偏向“我认为”；验证问题偏向“运行后能看到什么”。',
      evidence: ['预期结果和通过标准。', '运行观察记录。'],
      failureModes: ['问题太宽，无法一次运行回答。', '问题没有可观察输出。'],
      pmUse: '把讨论从观点拉回可复核证据。',
      correctExample: '当导入 3 条教学样本时，是否能输出 3 条带 evidence_limit 的待复核记录？',
      incorrectExample: '这个系统是不是体验很好？',
    },
    {
      id: 'portfolio-runnable-check', prerequisiteConceptIds: ['portfolio-validation-question'],
      term: '可运行检查', english: 'Runnable Check',
      definition: '可运行检查是为了回答验证问题而设计的一组最小操作，必须能被别人按步骤复跑。',
      why: '产品验证不是口头确认；可运行检查让证据从“我觉得”变成“按这几步能看到”。',
      problemSolved: '回答“怎么跑，别人才能复核”。',
      input: 'validation_question、input_output_contracts 和 state_lifecycle。',
      output: 'run_steps 与执行前准备。',
      systemPosition: '位于验证日志中段，承接问题并产生观察结果。',
      process: ['固定本次输入材料。', '写出可复跑执行动作。', '写清运行后的观察点。', '限制运行次数和模拟环境。'],
      owner: '产品经理设计，执行者按日志执行。',
      notResponsibleFor: '可运行检查不是自动化测试套件，也不证明生产环境一致。',
      compareWith: '演示可以临场发挥；可运行检查必须可复跑。',
      evidence: ['可复跑步骤清单。', '运行后的追加日志行。'],
      failureModes: ['步骤依赖口头说明。', '输入材料每次变化导致不可复核。'],
      pmUse: '让导师和面试官能看懂验证怎么发生。',
      correctExample: '使用固定 3 条教学样本，依次导入、检查状态、导出记录。',
      incorrectExample: '我点了一遍页面，感觉流程能走通。',
    },
    {
      id: 'portfolio-test-fixture', prerequisiteConceptIds: ['portfolio-runnable-check'],
      term: '测试夹具', english: 'Test Fixture',
      definition: '测试夹具是本次验证固定使用的输入材料、初始状态和模拟环境说明。',
      why: '同一问题如果输入不固定，观察结果无法比较，也无法复查是否只是运气。',
      problemSolved: '回答“这次运行基于哪些材料”。',
      input: 'data_entities、data_sources、privacy_access_boundary 和教学模拟边界。',
      output: 'fixture_used 字段。',
      systemPosition: '在运行步骤之前，限定验证材料来源。',
      process: ['列输入记录。', '标注教学模拟或真实来源。', '写初始状态和脱敏边界。'],
      owner: '产品经理准备，数据或安全角色后续可审阅。',
      notResponsibleFor: '测试夹具不证明真实数据完整，也不代表生产样本分布。',
      compareWith: '样例数据可以随手造；测试夹具必须说明来源、字段和限制。',
      evidence: ['固定样本表。', '脱敏和 evidence_limit 标注。'],
      failureModes: ['用真实敏感数据但不说明权限。', '每次运行临时改输入。'],
      pmUse: '确保验证材料可复核，同时保护隐私和权限边界。',
      correctExample: 'fixture：3 条脱敏教学失败样本，字段含 case_id、input、expected_action、evidence_limit。',
      incorrectExample: '随便找几条客服记录试一下。',
    },
    {
      id: 'portfolio-pass-fail-criterion', prerequisiteConceptIds: ['portfolio-test-fixture'],
      term: '通过/失败标准', english: 'Pass/Fail Criterion',
      definition: '通过/失败标准是在运行前写好的判定规则，说明看到什么算通过，看到什么算失败或不可判定。',
      why: '如果运行后才改标准，验证会变成自我说服；事先标准让结论更可信。',
      problemSolved: '回答“观察结果怎样才算支持验证问题”。',
      input: 'validation_question、expected_result 和状态生命周期。',
      output: 'expected_result 与 pass_fail 判定规则。',
      systemPosition: '位于运行前，约束运行后的结论。',
      process: ['写可计数或可检查的结果。', '写失败条件。', '写不可判定条件。'],
      owner: '产品经理定义，评审者可质疑是否足够严格。',
      notResponsibleFor: '通过标准不代表商业成功，也不替代风险概率评估。',
      compareWith: '成功口号说“体验顺畅”；通过标准说“3/3 记录都含 required 字段”。',
      evidence: ['运行前预期结果。', '实际观察与标准对照记录。'],
      failureModes: ['只写“看起来正常”。', '失败时没有判定规则。'],
      pmUse: '防止团队把模糊演示包装成验证通过。',
      correctExample: '通过：3 条输出均有 case_id、state=human_review_required、evidence_limit 非空；否则失败。',
      incorrectExample: '只要页面没有报错就算成功。',
    },
    {
      id: 'portfolio-run-log', prerequisiteConceptIds: ['portfolio-pass-fail-criterion'],
      term: '运行日志', english: 'Run Log',
      definition: '运行日志是按时间记录本次验证输入、动作、观察、证据和判定的不可变行。',
      why: '作品集需要可审计证据；运行日志让别人看到验证不是事后编写的结论。',
      problemSolved: '回答“本次验证实际发生了什么”。',
      input: '测试夹具、运行步骤、观察结果和通过标准。',
      output: 'validation-log.csv 的一行或多行。',
      systemPosition: '位于验证执行后，是 W12D3 的核心成果。',
      process: ['记录验证 ID 和时间。', '记录输入夹具。', '记录观察和 pass_fail。', '追加不能证明和下一步。'],
      owner: '执行验证的产品经理维护，评审者检查字段完整性。',
      notResponsibleFor: '运行日志不自动代表掌握，也不删除历史失败记录。',
      compareWith: '总结只写结论；运行日志保留可复核过程。',
      evidence: ['CSV 行。', '运行截图或本地观察记录。'],
      failureModes: ['覆盖旧失败记录。', '只保留通过结果。'],
      pmUse: '用追加式日志展示诚实迭代。',
      correctExample: 'VAL-001,3-sample-fixture,observed 3 records,state OK,pass,cannot prove production quality。',
      incorrectExample: '验证完成，一切正常，真实系统可以上线并且风险已经消失。',
    },
    {
      id: 'portfolio-observation-boundary', prerequisiteConceptIds: ['portfolio-run-log'],
      term: '观察边界', english: 'Observation Boundary',
      definition: '观察边界说明本次运行结果能证明什么、不能证明什么，以及哪些仍只是推断。',
      why: '一次本地教学模拟最容易被夸大；边界写清楚才能保住作品集可信度。',
      problemSolved: '回答“这条证据到底到哪一层为止”。',
      input: 'observed_result、fixture_used、环境和教学模拟限制。',
      output: 'cannot_prove 与 evidence_collected。',
      systemPosition: '位于运行日志结论之前，限制验证决策。',
      process: ['写事实观察。', '写支持的有限判断。', '写不能证明的真实世界事项。'],
      owner: '产品经理负责诚实表达，导师可复核是否越界。',
      notResponsibleFor: '观察边界不负责解决风险，只把风险留给 W12D4。',
      compareWith: '证据边界说“能/不能”；风险登记说“概率、影响和预案”。',
      evidence: ['教学模拟标注。', '不能证明清单。'],
      failureModes: ['把教学样本结果写成生产稳定。', '忽略样本规模和权限限制。'],
      pmUse: '在作品集中展示证据诚实，而不是夸张成果。',
      correctExample: '能证明本地导入契约能保留 evidence_limit；不能证明真实工单权限、生产延迟或长期准确率。',
      incorrectExample: '3 条教学样本通过，所以真实客服场景没有风险。',
    },
    {
      id: 'portfolio-validation-decision', prerequisiteConceptIds: ['portfolio-observation-boundary'],
      term: '验证决策', english: 'Validation Decision',
      definition: '验证决策是基于运行日志选择继续、修订、补证据或带着明确未知进入 W12D4 风险登记。',
      why: '验证日志不是终点；它必须告诉后续作品集应该修哪里、保留什么风险、下一步找谁确认。',
      problemSolved: '回答“看到这条证据后，项目下一步怎么走”。',
      input: 'pass_fail、cannot_prove、dependencies 和最大未知。',
      output: 'decision 与 next_action。',
      systemPosition: '作为 W12D3 终点，衔接 W12D4，但不替代 W12D4。',
      process: ['对照通过标准。', '写有限决策。', '把剩余风险交给下一课。'],
      owner: '产品经理提出，后续风险登记和评审继续处理。',
      notResponsibleFor: '验证决策不关闭全部风险，不代表跨职能已同意，也不完成最终作品集。',
      compareWith: '通过/失败是运行结果；验证决策是基于结果的产品动作。',
      evidence: ['validation-log.csv。', '不能证明清单和 next_action。'],
      failureModes: ['把 pass 写成上线许可。', '失败后没有修订动作。'],
      pmUse: '把验证结果转成可执行的下一步，而不是停在“做过验证”。',
      correctExample: 'decision=revise_data_source；next_action=W12D4 登记真实工单权限风险和兜底。',
      incorrectExample: 'decision=launch；next_action=准备最终答辩，风险无需处理。',
    },
  ],
  diagram: {
    title: '可运行验证日志的证据链',
    caption: '从最大未知出发，经过验证问题、可运行检查、夹具、标准和运行日志，形成有限验证决策。',
    nodes: [
      { id: 'unknown', label: '最大未知', description: '当前最阻断判断的未知。', input: 'W12D2 validation_questions', output: 'unknown_to_test', owner: '产品经理', evidence: '方案决策' },
      { id: 'question', label: '验证问题', description: '把未知写成可回答问题。', input: 'unknown_to_test', output: 'validation_question', owner: '产品经理', evidence: '问题句' },
      { id: 'fixture', label: '测试夹具', description: '固定输入和初始状态。', input: 'data_entities / data_sources', output: 'fixture_used', owner: '产品经理', evidence: '教学样本' },
      { id: 'criterion', label: '通过标准', description: '运行前写明判定规则。', input: 'expected_result', output: 'pass_fail rule', owner: '产品经理', evidence: '预期结果' },
      { id: 'log', label: '运行日志', description: '追加记录实际观察。', input: 'run_steps', output: 'validation-log.csv', owner: '验证执行者', evidence: '日志行' },
      { id: 'decision', label: '验证决策', description: '决定修订或进入风险登记。', input: 'pass_fail / cannot_prove', output: 'next_action', owner: '产品经理', evidence: '有限结论' },
    ],
    branches: [
      { from: 'unknown', to: 'question', label: '未知改写成问题', kind: 'normal' },
      { from: 'question', to: 'fixture', label: '问题决定输入材料', kind: 'normal' },
      { from: 'fixture', to: 'criterion', label: '输入约束判定标准', kind: 'normal' },
      { from: 'criterion', to: 'log', label: '按标准记录运行', kind: 'normal' },
      { from: 'log', to: 'decision', label: '日志形成有限决策', kind: 'normal' },
      { from: 'question', to: 'decision', label: '问题过宽导致不可判定', kind: 'failure' },
    ],
    evidenceNotes: ['所有运行均为教学模拟，必须显式标注。', '验证日志只证明本地可复核运行，不证明真实生产表现。', '剩余风险进入 W12D4，不在 W12D3 关闭。'],
  },
  demonstration: {
    title: '教师示范：验证样本导入是否保留 evidence_limit',
    businessProblem: 'W12D2 方案提出要验证导入教学失败样本后是否生成待复核记录，但还没有一条可复核运行日志。',
    finalConclusion: '本地教学模拟通过：3 条样本都生成 human_review_required 记录且保留 evidence_limit；但不能证明真实工单权限、生产数据质量或长期稳定。',
    conclusionLimit: '示范只证明一条本地教学模拟路径可复核，不能提前完成 W12D4 风险登记、W12D5 评审纪要或 W12D6 最终作品集。',
    steps: [
      { title: '选择最大未知', action: '从 W12D2 validation_questions 选择“导入样本后是否保留 evidence_limit”。', reason: '这会影响后续证据链是否可信。', evidence: 'unknown_to_test 字段。', proves: '能证明验证优先级来自方案。', limitation: '不能证明其他未知不重要。' },
      { title: '写清验证问题', action: '写“3 条教学样本导入后，是否都生成 human_review_required 记录并保留 evidence_limit”。', reason: '问题必须一次运行可回答。', evidence: 'validation_question 字段。', proves: '能证明问题有限且可观察。', limitation: '不能证明真实用户场景。' },
      { title: '准备测试夹具', action: '固定 3 条脱敏教学失败样本，标注每条都是教学模拟。', reason: '输入固定才可复核。', evidence: 'fixture_used。', proves: '能证明材料来源清楚。', limitation: '不能证明生产样本覆盖。' },
      { title: '预写通过标准', action: '通过标准设为 3/3 输出 case_id、state=human_review_required、evidence_limit 非空。', reason: '标准必须早于观察结果。', evidence: 'expected_result。', proves: '能证明判定没有事后漂移。', limitation: '不能证明指标达成。' },
      { title: '运行教学模拟', action: '执行本地导入、检查记录、追加日志行。', reason: '验证必须留下过程证据。', evidence: 'observed_result 与 evidence_collected。', proves: '能证明本地路径按步骤运行。', limitation: '不能证明真实系统性能。' },
      { title: '写出有限决策', action: 'decision=proceed_to_risk_register，next_action 指向 W12D4 登记真实数据权限和样本代表性风险。', reason: '通过不等于风险关闭。', evidence: 'decision / cannot_prove / next_action。', proves: '能证明结论没有越界。', limitation: '不能替代风险登记。' },
    ],
  },
  guidedLab: {
    title: '可运行验证日志六路径观察器',
    goal: '用本地教学模拟观察六种验证日志质量路径：未知过宽、问题缺失、夹具缺失、标准缺失、日志不完整和合格验证。',
    safety: '教学模拟；不读取真实公司数据、不调用外部服务、不证明真实系统、真实数据、生产稳定性或上线可行性。',
    conceptIds: [...conceptIds],
    predictionPrompt: '先预测：一次验证日志最容易在哪里把“运行过”夸大成“证明有效”？',
    steps: [
      { title: '观察未知过宽', action: '选择 unknown-too-broad，记录为什么无法一次运行回答。', observe: '未知写成“整个项目是否成功”。', explanation: '最大未知必须压缩到一次可运行检查。', proves: '能证明 unknown_to_test 需要重写。', cannotProve: '不能证明项目未来一定失败。' },
      { title: '观察验证问题缺失', action: '选择 question-missing，补出对象、动作和可观察结果。', observe: '日志只有“跑一下流程”。', explanation: '没有验证问题，日志无法支持或反驳任何判断。', proves: '能证明 validation_question 不合格。', cannotProve: '不能证明流程本身没有价值。' },
      { title: '观察夹具缺失', action: '选择 fixture-missing，写明固定教学样本。', observe: '输入材料每次临时变化。', explanation: '夹具缺失会破坏复核。', proves: '能证明 fixture_used 不完整。', cannotProve: '不能证明真实样本无法获取。' },
      { title: '观察标准缺失', action: '选择 criterion-missing，补通过、失败和不可判定条件。', observe: '运行后才说“看起来通过”。', explanation: '通过标准必须先于运行。', proves: '能证明 expected_result 需要修订。', cannotProve: '不能证明结果一定无意义。' },
      { title: '观察日志不完整', action: '选择 log-incomplete，补 observed_result、evidence_collected 和 cannot_prove。', observe: '只有结论，没有过程。', explanation: '日志必须追加可复核行。', proves: '能证明 run log 证据不足。', cannotProve: '不能证明执行者没有运行。' },
      { title: '观察合格验证', action: '选择 qualified-validation，记录为什么能进入 W12D4。', observe: '未知、问题、夹具、标准、观察、边界和决策齐全。', explanation: '合格日志降低一个未知，并把剩余风险交给下一课。', proves: '能证明本地教学模拟中的验证日志合同质量。', cannotProve: '不能证明真实生产表现、风险关闭或跨职能已同意。' },
    ],
    recordPrompts: ['记录当前路径的最先失败字段。', '写出这条路径能证明什么。', '写出这条路径不能证明什么。', '写一句进入 W12D4 前的下一步。'],
    comparePrompt: '比较六条路径：哪一类是问题不可运行，哪一类是证据不可复核，哪一类是结论越界？',
    passCriteria: ['六条教学模拟路径都运行并记录。', '每条记录都写出能证明与不能证明。', '没有把教学模拟写成真实生产验证。', '合格路径只进入 W12D4 风险登记，不声称作品集完成。'],
  },
  independentLab: {
    title: '独立变式：验证知识库助手的权限未知',
    scenario: '假设 W12D2 方案选择内部知识库助手，最大未知是“没有真实知识库权限时，能否用脱敏教学夹具保留来源和缺口”。',
    conceptIds: [...conceptIds],
    changedConditions: ['数据对象从 FailureSample 换成 KnowledgeArticle', '最大未知从样本导入换成权限和来源保留', '通过标准从 3 条待复核记录换成 2 条来源标注完整'],
    task: '写一条 validation-log.csv 行，验证脱敏教学知识条目是否保留 source_owner、access_limit 和 cannot_prove。',
    predictionPrompt: '先预测：这次验证最可能失败在夹具、标准还是观察边界？',
    evidenceRequirements: ['明确 fixture 是教学模拟。', '写清不能证明真实知识库权限、更新频率或用户采用。'],
    passCriteria: ['unknown_to_test 只包含一个最大未知。', 'run_steps 可复跑。', 'pass_fail 由预先标准决定。', 'next_action 只指向 W12D4 风险登记。'],
    remediation: { label: '回到可运行检查和测试夹具', sectionId: 'concepts', anchor: '#concept-portfolio-runnable-check' },
  },
  exercises: [
    exercise('w12d3-unknown', ['概念与边界', '工作场景'], ['portfolio-largest-unknown', 'portfolio-validation-question'], '哪一句最适合作为 W12D3 的最大未知？', ['整个作品集是否能打动面试官', '导入 3 条教学失败样本后是否保留 evidence_limit 并生成待复核记录', '风险登记册和答辩稿是否已经完成'], 1, '最大未知必须有限、阻断决策且能被一次运行部分回答。', '回看最大未知'),
    exercise('w12d3-fixture', ['证据判断'], ['portfolio-runnable-check', 'portfolio-test-fixture'], '验证日志里的 fixture_used 最应该写什么？', ['3 条脱敏教学失败样本及字段、初始状态和教学模拟标注', '真实客服系统已接入但不写 owner', '不用输入材料，直接看最终结论'], 0, '夹具必须固定输入、初始状态和证据边界。', '回看测试夹具'),
    exercise('w12d3-criterion', ['机制推演'], ['portfolio-pass-fail-criterion', 'portfolio-run-log'], '哪一种通过标准最适合写进验证日志？', ['页面看起来顺畅', '3/3 输出均含 case_id、state=human_review_required、evidence_limit 非空，否则失败', '导师觉得可以就通过'], 1, '标准要在运行前写成可检查条件，运行日志再记录实际观察。', '回看通过标准'),
    exercise('w12d3-decision', ['综合变式'], ['portfolio-observation-boundary', 'portfolio-validation-decision'], '本地教学模拟通过后，最不越界的 decision 是什么？', ['上线并宣布真实系统稳定', 'proceed_to_risk_register，并在 W12D4 登记真实数据权限和样本代表性风险', '直接完成最终作品集'], 1, 'W12D3 的结论只能降低一个未知，把剩余风险带到 W12D4。', '回看验证决策'),
  ],
  deliverable: {
    title: '可运行验证日志',
    conceptIds: [...conceptIds],
    purpose: '用 `validation-log.csv` 记录一次可复核教学模拟运行，证明一个最大未知被有限降低，并公开不能证明的真实世界事项。',
    whenToUse: '在 W12D4 风险登记册之前，用来把系统与数据方案从纸面设计推进到有限验证证据。',
    audience: '导师、评审者、未来面试官，以及后续负责风险评估的角色。',
    fields: [
      { name: 'validation_id', meaning: '本次验证的唯一编号。', source: '运行日志' },
      { name: 'brief_ref', meaning: '引用 W12D1 Brief 和 W12D2 方案。', source: '前两日产物' },
      { name: 'unknown_to_test', meaning: '本次选择的最大未知。', source: '最大未知' },
      { name: 'validation_question', meaning: '可运行、可观察、可判定的问题。', source: '验证问题' },
      { name: 'fixture_used', meaning: '固定输入材料、初始状态和教学模拟标注。', source: '测试夹具' },
      { name: 'run_steps', meaning: '别人可以复跑的操作步骤。', source: '可运行检查' },
      { name: 'expected_result', meaning: '运行前写好的通过/失败标准。', source: '通过/失败标准' },
      { name: 'observed_result', meaning: '实际看到的输出、状态或错误。', source: '运行日志' },
      { name: 'pass_fail', meaning: 'pass、fail 或 inconclusive。', source: '通过/失败标准' },
      { name: 'evidence_collected', meaning: '日志、截图、字段或本地观察证据。', source: '运行日志' },
      { name: 'decision', meaning: '继续、修订、补证据或进入风险登记。', source: '验证决策' },
      { name: 'cannot_prove', meaning: '本次验证不能证明的事项。', source: '观察边界' },
      { name: 'next_action', meaning: '下一步动作，只能指向 W12D4 风险登记或修订验证。', source: '验证决策' },
    ],
    badExample: 'validation-log.csv\nVAL-1,项目成功,随便跑了一下,看起来可以,pass,证明真实系统可上线,下一步完成答辩',
    badReasons: ['没有最大未知和验证问题。', '没有 fixture、run_steps 和 expected_result。', '把教学模拟越界写成真实上线证明。'],
    revisionSteps: ['从 W12D2 选择一个 validation_question。', '压缩成 unknown_to_test。', '准备固定教学夹具。', '预写 expected_result。', '运行并追加 observed_result。', '写 cannot_prove 和 next_action。'],
    goodExample: 'validation_id,brief_ref,unknown_to_test,validation_question,fixture_used,run_steps,expected_result,observed_result,pass_fail,evidence_collected,decision,cannot_prove,next_action\nVAL-001,W12D1 Brief + W12D2 system-data-plan,导入教学失败样本后能否保留 evidence_limit,导入 3 条教学样本后是否生成 human_review_required 记录并保留 evidence_limit,3 条脱敏教学模拟 FailureSample,导入样本→检查状态→导出记录,3/3 记录含 case_id/state/evidence_limit,3/3 输出 human_review_required 且 evidence_limit 非空,pass,本地教学模拟日志与导出字段,proceed_to_risk_register,不能证明真实工单权限/生产延迟/长期准确率,W12D4 登记真实数据权限和样本代表性风险',
    guidedPrompts: ['写 validation_id 与 brief_ref。', '写 unknown_to_test。', '写 validation_question。', '写 fixture_used。', '写 run_steps。', '写 expected_result。', '写 observed_result / pass_fail / evidence_collected。', '写 decision / cannot_prove / next_action。'],
    blankTemplate: 'validation_id,brief_ref,unknown_to_test,validation_question,fixture_used,run_steps,expected_result,observed_result,pass_fail,evidence_collected,decision,cannot_prove,next_action\n',
    standardTemplate: 'validation_id,brief_ref,unknown_to_test,validation_question,fixture_used,run_steps,expected_result,observed_result,pass_fail,evidence_collected,decision,cannot_prove,next_action\nVAL-001,[引用 W12D1 Brief + W12D2 方案],[一个最大未知],[一次可运行验证问题],[固定教学夹具 + 教学模拟标注],[可复跑步骤],[运行前通过/失败标准],[实际观察],[pass/fail/inconclusive],[收集到的本地证据],[proceed/revise/collect_more_evidence],[本次不能证明什么],[只指向 W12D4 风险登记或修订验证]',
    checklist: ['引用了 W12D1 Brief 和 W12D2 方案。', 'unknown_to_test 只有一个最大未知。', 'validation_question 可运行、可观察、可判定。', 'fixture_used 固定且标注教学模拟。', 'run_steps 可复跑。', 'expected_result 在 observed_result 前定义。', 'pass_fail 只能由标准判定。', 'cannot_prove 写明真实数据、生产系统或长期效果边界。', 'next_action 不提前完成 W12D4–W12D6。'],
  },
  memory: {
    conceptIds: [...conceptIds],
    anchors: ['验证先选最大未知。', '可运行问题必须有夹具和标准。', '运行日志追加过程，不只写结论。', 'W12D3 只降低一个未知，把风险交给 W12D4。'],
    closedBookPrompt: '闭卷解释一条 validation-log.csv 如何从最大未知、验证问题、夹具、标准、观察走到有限决策。',
    microOperation: '把“我跑过了，项目可行”改写成 unknown_to_test + observed_result + cannot_prove。',
    unresolvedPrompt: '写出你当前验证日志里仍不能证明的最大真实世界事项，以及它应在 W12D4 如何登记风险。',
    reviewStages: [
      { stage: 'D1', task: '闭卷写出 validation-log.csv 的 13 个字段。' },
      { stage: 'D3', task: '把一个过宽未知改写成可运行验证问题。' },
      { stage: 'D7', task: '给一条验证补上固定 fixture 和 expected_result。' },
      { stage: 'D14', task: '检查一条 observed_result 是否能由 pass/fail 标准判定。' },
      { stage: 'D30', task: '复述 W12D3 与 W12D4 的边界。' },
      { stage: 'D60', task: '用 cannot_prove 解释为什么本地教学模拟不能证明生产上线。' },
    ],
  },
  nextLesson: {
    id: 'W12D4',
    title: '风险登记册编写',
    bridge: '下一课才把 W12D3 不能证明的事项写成概率、影响、预防、监控、触发、兜底和责任人；本课只交付验证日志。',
  },
}
