import type { DailyCourse, Exercise } from './types'

const conceptIds = [
  'portfolio-risk-source',
  'portfolio-risk-statement',
  'portfolio-risk-probability',
  'portfolio-risk-impact',
  'portfolio-risk-prevention',
  'portfolio-risk-monitoring',
  'portfolio-risk-trigger-fallback',
  'portfolio-risk-owner',
] as const

const prerequisiteConceptIds = [
  'portfolio-largest-unknown',
  'portfolio-validation-question',
  'portfolio-runnable-check',
  'portfolio-test-fixture',
  'portfolio-pass-fail-criterion',
  'portfolio-run-log',
  'portfolio-observation-boundary',
  'portfolio-validation-decision',
]

function exercise(
  id: string,
  categories: Exercise['categories'],
  conceptIdsForExercise: string[],
  prompt: string,
  options: string[],
  answerIndex: number,
  referenceAnswer: string,
  remediationLabel: string,
): Exercise {
  return {
    id,
    kind: 'single-choice',
    categories,
    conceptIds: conceptIdsForExercise,
    prompt,
    hint: '先看风险是否来自 W12D3 的 cannot_prove，再看是否写清概率、影响、预防、监控、触发、兜底和责任人。',
    options: options.map((label, index) => ({
      label,
      rationale: index === answerIndex ? '这项把风险来源、判断等级、日常预防和异常兜底连在一起，适合进入风险登记册。' : '这项要么只是担心，要么缺少概率/影响，或把风险登记册写成评审结论。',
      couldBeTrueWhen: index === answerIndex ? '当登记册只基于 W12D3 的有限验证边界，并明确后续评审仍未完成时。' : '只有补齐风险字段、后续评审和真实证据后，才可能成为更强结论。',
    })),
    answerIndex,
    referenceAnswer,
    reasoning: ['风险登记册回答“哪些不能证明的事项需要被跟踪和预案处理”。', '登记册必须包含概率、影响、预防、监控、触发、兜底和责任人。', 'W12D4 只登记和管理风险，不提前完成 W12D5 评审或 W12D6 最终作品集。'],
    rubric: ['风险来源可追溯', '概率和影响分开', '预防与监控可执行', '触发和兜底不过界'],
    commonErrors: [
      { error: '只写“有风险”', reason: '没有概率、影响、监控和责任人，团队无法处理。' },
      { error: '登记后就说风险关闭', reason: '登记册只能管理风险，不能替代真实评审或生产证明。' },
    ],
    remediation: { label: remediationLabel, sectionId: 'concepts', anchor: `#concept-${conceptIdsForExercise[0]}` },
  }
}

export const w12d4: DailyCourse = {
  id: 'W12D4',
  contentVersion: 'w12d4-risk-register-day01-v1',
  week: 12,
  day: 4,
  title: '风险登记册编写',
  subtitle: '把 W12D3 validation-log.csv 中“不能证明”的事项转成可跟踪风险：写清风险陈述、概率、影响、预防、监控、触发条件、兜底方案和责任人；不写跨职能评审纪要，也不装配最终作品集。',
  duration: { core: 30, standard: 45, extension: 60, full: 116 },
  coreConceptGroups: [
    {
      id: 'source-statement',
      title: '从证据边界生成风险',
      conceptIds: ['portfolio-risk-source', 'portfolio-risk-statement'],
      summary: '风险不是凭空担心，而是来自 W12D3 的 cannot_prove、依赖缺口和验证失败边界；风险陈述必须写成“如果……那么……”的可评审句子。',
      boundary: '本组只把风险写清楚，不判断跨职能是否接受。',
    },
    {
      id: 'probability-impact',
      title: '用概率和影响排序风险',
      conceptIds: ['portfolio-risk-probability', 'portfolio-risk-impact'],
      summary: '概率说明发生可能性，影响说明发生后的损害范围；二者分开，才能决定先管哪个风险。',
      boundary: '本地教学模拟只能给出初始等级，不能证明真实生产概率。',
    },
    {
      id: 'control-owner',
      title: '用预防、监控、触发、兜底和责任人管理风险',
      conceptIds: ['portfolio-risk-prevention', 'portfolio-risk-monitoring', 'portfolio-risk-trigger-fallback', 'portfolio-risk-owner'],
      summary: '预防减少发生，监控发现变化，触发条件决定何时启动兜底，责任人保证有人跟进。',
      boundary: '本组不替代 W12D5 跨职能评审和修订。',
    },
  ],
  prerequisiteConceptIds,
  learningPaths: {
    '30': {
      guidedStepIndices: [0, 1, 2, 3, 4, 5],
      guidedRecordIndices: [0, 1, 2],
      exerciseCount: 3,
      deliverablePromptCount: 5,
      deliverableChecklistIndices: [0, 1, 2, 3, 4],
      deliverableMinimumContributionCharacters: 180,
    },
    '45': {
      guidedStepIndices: [0, 1, 2, 3, 4, 5],
      guidedRecordIndices: [0, 1, 2, 3],
      exerciseCount: 4,
      deliverablePromptCount: 8,
      deliverableChecklistIndices: [0, 1, 2, 3, 4, 5, 6, 7],
      deliverableMinimumContributionCharacters: 300,
    },
  },
  primaryGoal: '提交一份 `risk-register.csv`：至少包含 risk_id、evidence_ref、risk_statement、probability、impact、prevention_action、monitoring_signal、trigger_condition、fallback_plan、owner、review_cadence、status、evidence_limit。',
  scenario: {
    role: '你是准备作品集风险证据链的产品经理实习生。',
    situation: 'W12D3 已经跑出一条 validation-log.csv，但日志里明确写了真实工单权限、样本代表性、生产延迟或长期效果仍不能证明。你需要把这些事项登记为可跟踪风险。',
    question: '怎样把“不能证明”改写成团队能监控、预防、触发兜底并分配责任人的风险登记册？',
    stakes: '没有风险登记册，作品集会像只展示成功结果；风险登记越界，又会把本地教学模拟伪装成真实评审通过。',
  },
  objectives: [
    { id: 'w12d4-objective-source', text: '从 W12D3 证据边界抽取风险来源', evidence: '登记册包含 evidence_ref 与 evidence_limit。' },
    { id: 'w12d4-objective-rank', text: '分别判断 probability 与 impact', evidence: '登记册包含概率、影响和排序理由。' },
    { id: 'w12d4-objective-control', text: '写出预防动作和监控信号', evidence: '登记册包含 prevention_action 与 monitoring_signal。' },
    { id: 'w12d4-objective-response', text: '写出触发条件、兜底方案和责任人', evidence: '登记册包含 trigger_condition、fallback_plan、owner，且不提前完成 W12D5。' },
  ],
  prerequisites: [
    {
      id: 'w12d4-validation-log-readiness',
      conceptIds: ['portfolio-largest-unknown', 'portfolio-validation-question', 'portfolio-runnable-check', 'portfolio-run-log', 'portfolio-observation-boundary', 'portfolio-validation-decision'],
      prompt: '你能从 W12D3 validation-log.csv 中指出 cannot_prove 和 next_action 吗？',
      passDescription: '能说出一条验证日志不能证明的真实世界事项，以及它为什么需要登记为风险。',
      remediationLabel: '补学 W12D3：观察边界与验证决策',
      remediationTarget: '#/lesson/W12D3',
      remediation: { purpose: 'W12D4 的风险必须来自 W12D3 的有限证据边界，不能凭空编写。', steps: ['找到 W12D3 的 cannot_prove。', '找到 next_action。', '把一条不能证明事项改写成风险候选。'], successCheck: '能写出一条 evidence_ref。' },
    },
    {
      id: 'w12d4-evidence-boundary-readiness',
      conceptIds: ['portfolio-test-fixture', 'portfolio-pass-fail-criterion', 'portfolio-observation-boundary'],
      prompt: '你能区分教学模拟通过、真实数据缺口和后续评审责任吗？',
      passDescription: '能说明本地教学模拟只能提供初始风险依据，不能证明生产概率和跨职能承诺。',
      remediationLabel: '补学 W12D3：测试夹具与证据边界',
      remediationTarget: '#/lesson/W12D3',
      remediation: { purpose: '风险等级必须诚实标注证据限制，不能把教学样本当真实统计。', steps: ['复述 fixture_used。', '复述 pass_fail 的依据。', '写出 evidence_limit。'], successCheck: '能写出“本登记不能证明真实发生概率”的句子。' },
    },
  ],
  concepts: [
    {
      id: 'portfolio-risk-source', prerequisiteConceptIds: ['portfolio-validation-decision'],
      term: '风险来源', english: 'Risk Source',
      definition: '风险来源是从 W12D3 的 cannot_prove、失败观察、依赖缺口或 next_action 中抽取出来的风险依据。',
      why: '风险必须可追溯到已有证据，否则登记册会变成主观担心清单。',
      problemSolved: '回答“这条风险为什么存在”。',
      input: 'validation-log.csv、cannot_prove、evidence_collected 和 next_action。',
      output: 'evidence_ref 与 evidence_limit。',
      systemPosition: '位于风险登记册开头，连接验证日志和风险条目。',
      process: ['读取 W12D3 日志。', '挑出不能证明事项。', '标注是教学模拟、真实缺口还是依赖。'],
      owner: '产品经理整理，后续评审者可追溯证据。',
      notResponsibleFor: '风险来源不证明风险一定发生，也不替代概率判断。',
      compareWith: '担心是主观描述；风险来源必须能回到一条证据或缺口。',
      evidence: ['W12D3 validation-log.csv。', '不能证明清单。'],
      failureModes: ['凭空写风险。', '引用了不存在的证据。'],
      pmUse: '让作品集展示“我知道成功路径之外还有什么未被证明”。',
      correctExample: '来源：W12D3 VAL-001 cannot_prove 写明真实工单权限和样本代表性未证明。',
      incorrectExample: '来源：我觉得项目可能有点风险。',
    },
    {
      id: 'portfolio-risk-statement', prerequisiteConceptIds: ['portfolio-risk-source'],
      term: '风险陈述', english: 'Risk Statement',
      definition: '风险陈述把来源改写为“如果某条件发生，那么会造成某影响”的可评审句子。',
      why: '清楚的风险句子让团队知道风险发生条件和后果，不再只看到抽象标签。',
      problemSolved: '回答“到底怕什么，发生后会怎样”。',
      input: '风险来源、系统目标、用户触点和依赖。',
      output: 'risk_statement。',
      systemPosition: '连接风险来源与概率/影响判断。',
      process: ['写清触发前提条件。', '写出受影响对象。', '写明发生后的后果。', '保留证据限制。'],
      owner: '产品经理撰写，相关 owner 后续确认。',
      notResponsibleFor: '风险陈述不负责给出概率、预案或批准结论。',
      compareWith: '“数据风险”是标签；“如果真实工单权限未获批，那么验证只能停留在教学样本”是风险陈述。',
      evidence: ['系统与数据方案依赖。', '验证日志不能证明项。'],
      failureModes: ['只写名词标签。', '把已经发生的问题写成未发生风险但不标注状态。'],
      pmUse: '让评审者快速理解风险的业务含义。',
      correctExample: '如果真实客服工单权限未获批，那么验证日志只能使用教学样本，样本代表性无法被评审。',
      incorrectExample: '风险：数据不好，但没有写清发生条件、受影响对象和后果。',
    },
    {
      id: 'portfolio-risk-probability', prerequisiteConceptIds: ['portfolio-risk-statement'],
      term: '概率', english: 'Probability',
      definition: '概率是对风险发生可能性的初始等级判断，通常用 low、medium、high 表示，并写出依据。',
      why: '不分概率，团队会把所有风险当同等紧急；初始等级帮助排序，但必须承认证据限制。',
      problemSolved: '回答“这条风险多可能发生，以及排序时为什么不能和影响混在一起”。',
      input: '风险来源、依赖状态、历史观察和当前权限。',
      output: 'probability 字段。',
      systemPosition: '与 impact 合在一起决定优先级。',
      process: ['查看是否已有真实证据。', '判断依赖是否可控。', '写 low/medium/high 与理由。'],
      owner: '产品经理初评，owner 和评审后续修订。',
      notResponsibleFor: '概率不是统计结论，不能由 3 条教学样本证明真实发生率。',
      compareWith: '概率看“可能发生吗”；影响看“发生后损害多大”。',
      evidence: ['教学模拟结果。', '依赖 owner 状态。'],
      failureModes: ['把教学通过写成概率为 0。', '没有依据地写 high。'],
      pmUse: '帮助把最可能发生的风险排到前面处理。',
      correctExample: 'probability=medium；依据是真实工单权限 owner 未确认，但有教学样本 fallback。',
      incorrectExample: 'probability=none，因为本地模拟通过了。',
    },
    {
      id: 'portfolio-risk-impact', prerequisiteConceptIds: ['portfolio-risk-probability'],
      term: '影响', english: 'Impact',
      definition: '影响是风险发生后对用户、作品集可信度、交付范围或安全合规造成的损害等级。',
      why: '低概率但高影响的风险仍需要预案；影响写清楚才能决定投入多少控制动作。',
      problemSolved: '回答“发生后会损害什么”。',
      input: '用户问题、成功指标、系统边界和风险陈述。',
      output: 'impact 字段，包含损害等级、受影响对象和业务后果。',
      systemPosition: '与 probability 共同决定风险优先级。',
      process: ['找受影响对象。', '判断损害范围。', '写 low/medium/high 与原因。'],
      owner: '产品经理初评，相关团队后续确认。',
      notResponsibleFor: '影响不是情绪严重程度，也不自动决定上线或暂停。',
      compareWith: '概率是可能性，影响是后果。',
      evidence: ['W12D1 成功指标。', 'W12D2 范围与非目标。'],
      failureModes: ['所有风险都写 high。', '只写技术影响，不写用户或作品集影响。'],
      pmUse: '说明为什么某条风险值得先预防或监控。',
      correctExample: 'impact=high；若真实工单权限缺失，作品集无法证明样本代表性。',
      incorrectExample: 'impact=high，因为我很担心。',
    },
    {
      id: 'portfolio-risk-prevention', prerequisiteConceptIds: ['portfolio-risk-impact'],
      term: '预防动作', english: 'Prevention Action',
      definition: '预防动作是在风险发生前降低发生概率或影响的具体行动。',
      why: '风险登记不是等事故发生；预防动作让风险管理前置到计划中。',
      problemSolved: '回答“现在能做什么减少风险”。',
      input: 'risk_statement、probability、impact 和可控依赖。',
      output: 'prevention_action。',
      systemPosition: '位于风险等级之后，先于监控和兜底。',
      process: ['找可控原因。', '写具体动作。', '写 owner 或协作对象。'],
      owner: '产品经理推动，具体 owner 执行或确认。',
      notResponsibleFor: '预防动作不能保证风险不发生，也不替代 fallback。',
      compareWith: '预防是事前降低风险；兜底是事后恢复路径。',
      evidence: ['依赖清单中的可控事项。', '当前 fallback 是否已经具备替代路径。'],
      failureModes: ['只写“加强沟通”。', '预防动作没有对象和完成标准。'],
      pmUse: '把风险从报告文字变成行动清单。',
      correctExample: '本周内向客服主管确认可用脱敏工单字段；若未获批，只使用教学样本并标注缺口。',
      incorrectExample: '大家注意一下数据风险，但没有指定确认对象、截止时间和完成标准。',
    },
    {
      id: 'portfolio-risk-monitoring', prerequisiteConceptIds: ['portfolio-risk-prevention'],
      term: '监控信号', english: 'Monitoring Signal',
      definition: '监控信号是用来观察风险是否变大、变小或接近触发条件的具体指标或事件。',
      why: '没有监控，风险条目会写完就沉没；监控让 owner 知道何时需要行动。',
      problemSolved: '回答“怎么知道风险正在发生”。',
      input: 'risk_statement、prevention_action 和可观察事件。',
      output: 'monitoring_signal。',
      systemPosition: '连接预防动作与触发条件。',
      process: ['选择可观察信号。', '写检查频率。', '写异常阈值。'],
      owner: '风险 owner 或产品经理定期检查。',
      notResponsibleFor: '监控信号不自动修复风险，也不能伪造真实生产指标。',
      compareWith: '监控是持续观察；触发是达到某条件后执行兜底。',
      evidence: ['邮件确认状态。', '样本字段完整率。', '评审反馈记录。'],
      failureModes: ['信号无法观察。', '没有检查频率。'],
      pmUse: '让评审者相信风险会被持续跟踪。',
      correctExample: 'monitoring_signal=每周检查真实工单权限 owner 回复状态和可用字段清单。',
      incorrectExample: 'monitoring_signal=感觉差不多了。',
    },
    {
      id: 'portfolio-risk-trigger-fallback', prerequisiteConceptIds: ['portfolio-risk-monitoring'],
      term: '触发条件与兜底方案', english: 'Trigger and Fallback',
      definition: '触发条件说明何时认为风险需要响应；兜底方案说明触发后如何降低损害或换路径。',
      why: '监控发现风险后必须有动作，否则风险登记册只是记录本。',
      problemSolved: '回答“什么时候启动预案，启动后怎么做”。',
      input: 'monitoring_signal、impact 和可用替代路径。',
      output: 'trigger_condition 与 fallback_plan。',
      systemPosition: '位于风险响应末端，保证风险出现时有恢复路径。',
      process: ['设定触发阈值。', '写出备用方案。', '说明兜底后的证据限制。'],
      owner: '产品经理协调，具体 owner 执行。',
      notResponsibleFor: '兜底方案不证明原风险已经消失，也不替代跨职能确认。',
      compareWith: '触发条件是“何时动”；兜底方案是“动什么”。',
      evidence: ['监控记录中的触发阈值。', '备用样本或替代访谈计划是否可执行。'],
      failureModes: ['触发条件太模糊。', '兜底方案等同于原方案。'],
      pmUse: '展示你不仅知道风险，还能给出可执行恢复路径。',
      correctExample: 'trigger=三天内未获得真实工单字段确认；fallback=使用教学样本完成作品集并在 evidence_limit 标注真实代表性缺口。',
      incorrectExample: 'trigger=感觉不妙；fallback=再看看。',
    },
    {
      id: 'portfolio-risk-owner', prerequisiteConceptIds: ['portfolio-risk-trigger-fallback'],
      term: '责任人', english: 'Risk Owner',
      definition: '责任人是负责跟踪风险、更新状态、推动预防或兜底动作的人或角色。',
      why: '没有 owner，风险登记册没有闭环；责任人让每条风险有明确跟进入口。',
      problemSolved: '回答“谁负责看着这条风险”。',
      input: '风险类型、依赖 owner、预防动作和兜底方案。',
      output: 'owner、review_cadence 与 status。',
      systemPosition: '作为风险登记册最后一组字段，保证后续评审可继续追踪。',
      process: ['选择最接近风险控制点的角色。', '写检查节奏。', '写当前状态。'],
      owner: '产品经理初分配，W12D5 后续评审中确认或修订。',
      notResponsibleFor: 'owner 字段不代表该角色已经正式承诺，除非有真实确认记录。',
      compareWith: 'stakeholder 可能受影响；risk owner 必须负责跟踪动作。',
      evidence: ['依赖清单中的控制点角色。', '后续确认记录里的 owner 变更或承诺状态。'],
      failureModes: ['owner 写成“大家”。', '没有 review_cadence。'],
      pmUse: '让风险能进入跨职能沟通，而不是停留在个人笔记。',
      correctExample: 'owner=产品经理先跟进；review_cadence=每周五更新；W12D5 评审时确认客服主管 owner。',
      incorrectExample: 'owner=团队所有人。',
    },
  ],
  diagram: {
    title: '风险登记册的管理链',
    caption: '从 W12D3 的不能证明事项出发，形成风险来源、风险陈述、概率、影响、预防、监控、触发、兜底和责任人。',
    nodes: [
      { id: 'source', label: '风险来源', description: '来自不能证明事项。', input: 'W12D3 cannot_prove', output: 'evidence_ref', owner: '产品经理', evidence: '验证日志' },
      { id: 'statement', label: '风险陈述', description: '如果……那么……。', input: 'evidence_ref', output: 'risk_statement', owner: '产品经理', evidence: '风险句子' },
      { id: 'rank', label: '概率/影响', description: '判断可能性和损害。', input: 'risk_statement', output: 'probability / impact', owner: '产品经理', evidence: '初始依据' },
      { id: 'control', label: '预防/监控', description: '降低风险并观察变化。', input: 'probability / impact', output: 'prevention_action / monitoring_signal', owner: '风险 owner', evidence: '检查记录' },
      { id: 'response', label: '触发/兜底', description: '达到条件后执行预案。', input: 'monitoring_signal', output: 'trigger_condition / fallback_plan', owner: '风险 owner', evidence: '预案' },
      { id: 'owner', label: '风险责任人', description: '持续跟踪并更新状态。', input: 'fallback_plan', output: 'owner / status', owner: '产品经理初分配', evidence: '登记册' },
    ],
    branches: [
      { from: 'source', to: 'statement', label: '证据边界改写为风险', kind: 'normal' },
      { from: 'statement', to: 'rank', label: '风险句子进入排序', kind: 'normal' },
      { from: 'rank', to: 'control', label: '高优先级决定控制动作', kind: 'normal' },
      { from: 'control', to: 'response', label: '监控接近触发条件', kind: 'normal' },
      { from: 'response', to: 'owner', label: '责任人更新状态', kind: 'normal' },
      { from: 'source', to: 'owner', label: '无来源导致无法分配', kind: 'failure' },
    ],
    evidenceNotes: ['所有风险等级均为教学模拟下的初始判断，必须显式标注。', '风险登记册能证明风险管理结构完整，不能证明真实概率或 owner 已正式承诺。', 'W12D5 才做跨职能评审与修订。'],
  },
  demonstration: {
    title: '教师示范：把真实工单权限缺口登记为风险',
    businessProblem: 'W12D3 验证日志通过了教学样本导入，但 cannot_prove 写明真实工单权限和样本代表性仍未证明。',
    finalConclusion: '这条风险可以登记为 medium probability / high impact：需要预防动作、监控信号、触发条件、兜底方案和临时 owner；但不能证明真实权限会失败或后续评审已同意。',
    conclusionLimit: '示范只证明风险登记册字段质量，不能提前完成 W12D5 跨职能评审、W12D6 最终作品集，也不能证明真实生产风险已经消除。',
    steps: [
      { title: '引用风险来源', action: '从 W12D3 VAL-001 的 cannot_prove 引用“真实工单权限未证明”。', reason: '风险必须来自已有证据边界。', evidence: 'evidence_ref 字段。', proves: '能证明风险不是凭空担心。', limitation: '不能证明风险一定会发生。' },
      { title: '改写风险陈述', action: '写“如果真实工单权限未获批，那么验证只能停留在教学样本，样本代表性无法被评审”。', reason: '如果/那么结构让风险可评审。', evidence: 'risk_statement 字段。', proves: '能证明风险条件和影响对象清楚。', limitation: '不能证明权限一定无法获批。' },
      { title: '判断概率和影响', action: 'probability=medium，impact=high，并写依据。', reason: '概率和影响要分开，便于排序。', evidence: 'probability / impact。', proves: '能证明有初始优先级。', limitation: '不能证明真实统计概率。' },
      { title: '设计预防动作', action: '预防动作为向客服主管确认可用脱敏字段和 owner。', reason: '预防在风险发生前降低不确定性。', evidence: 'prevention_action。', proves: '能证明有事前动作。', limitation: '不能保证对方一定回复。' },
      { title: '写监控与触发', action: '每周检查 owner 回复；三天无确认则触发兜底。', reason: '监控让风险不会沉没，触发让预案有启动条件。', evidence: 'monitoring_signal / trigger_condition。', proves: '能证明风险会被跟踪。', limitation: '不能替代真实项目管理工具。' },
      { title: '写兜底和责任人', action: 'fallback 使用教学样本并明确 evidence_limit；owner 暂为产品经理，W12D5 评审确认。', reason: '兜底降低作品集损害，责任人保证后续有人更新。', evidence: 'fallback_plan / owner / status。', proves: '能证明风险条目可执行。', limitation: '不能证明 owner 已正式承诺。' },
    ],
  },
  guidedLab: {
    title: '风险登记册六路径观察器',
    goal: '用本地教学模拟观察六种风险登记质量路径：风险过宽、概率缺失、影响缺失、预防缺失、触发/兜底缺失和合格风险登记。',
    safety: '教学模拟；不读取真实公司数据、不调用外部服务、不证明真实概率、真实影响、owner 承诺、评审通过或风险关闭。',
    conceptIds: [...conceptIds],
    predictionPrompt: '先预测：风险登记册最容易在哪个字段把“有风险”写成无法执行的担心？',
    steps: [
      { title: '观察风险过宽', action: '选择 risk-too-vague，记录为什么无法跟踪。', observe: '风险写成“项目可能失败”。', explanation: '风险必须来自证据边界并写成如果/那么。', proves: '能证明 risk_statement 需要重写。', cannotProve: '不能证明项目未来一定失败。' },
      { title: '观察概率缺失', action: '选择 probability-missing，补 low/medium/high 和依据。', observe: '登记册没有 probability。', explanation: '没有概率无法排序优先级。', proves: '能证明 probability 不完整。', cannotProve: '不能证明真实发生率。' },
      { title: '观察影响缺失', action: '选择 impact-missing，写受影响对象和损害等级。', observe: '登记册没有 impact。', explanation: '没有影响无法判断是否需要兜底。', proves: '能证明 impact 不完整。', cannotProve: '不能证明损害一定发生。' },
      { title: '观察预防缺失', action: '选择 prevention-missing，补事前动作。', observe: '只写监控，没有预防。', explanation: '预防动作降低发生概率或影响。', proves: '能证明 prevention_action 不完整。', cannotProve: '不能保证风险不发生。' },
      { title: '观察触发/兜底缺失', action: '选择 trigger-fallback-missing，补触发条件和 fallback。', observe: '监控到异常后没有动作。', explanation: '触发和兜底决定何时启动预案。', proves: '能证明 response 字段不完整。', cannotProve: '不能证明预案一定被执行。' },
      { title: '观察合格风险登记', action: '选择 qualified-risk-register，记录为什么只能进入 W12D5 评审。', observe: '来源、陈述、概率、影响、预防、监控、触发、兜底和 owner 齐全。', explanation: '合格登记册让风险可评审，但不代表已被跨职能接受。', proves: '能证明本地教学模拟中的风险登记册合同质量。', cannotProve: '不能证明真实概率、owner 承诺、风险已经消除或评审通过。' },
    ],
    recordPrompts: ['记录当前路径最先失败的风险字段。', '写出这条路径能证明什么。', '写出这条路径不能证明什么。', '写一句进入 W12D5 前需要评审或修订的点。'],
    comparePrompt: '比较六条路径：哪一类是风险来源不可追溯，哪一类是优先级不可排序，哪一类是响应不可执行？',
    passCriteria: ['六条教学模拟路径都运行并记录。', '每条记录都写出能证明与不能证明。', '没有把教学模拟写成真实概率或 owner 承诺。', '合格路径只进入 W12D5 评审与修订，不声称作品集完成。'],
  },
  independentLab: {
    title: '独立变式：登记知识库权限和更新频率风险',
    scenario: '假设 W12D3 对内部知识库助手的 validation-log.csv 写明 source_owner 和 access_limit 只能用教学夹具验证，真实知识库权限和更新频率仍未证明。',
    conceptIds: [...conceptIds],
    changedConditions: ['风险来源从客服工单权限换成知识库权限', '影响对象从样本代表性换成来源可信度和更新频率', 'owner 从客服主管候选换成知识库管理员候选'],
    task: '写一条 risk-register.csv 行，登记真实知识库权限或更新频率风险，并给出预防、监控、触发、兜底和 owner。',
    predictionPrompt: '先预测：这条风险最容易缺概率依据、影响对象还是触发条件？',
    evidenceRequirements: ['明确 evidence_ref 来自 W12D3 教学模拟。', '写清不能证明真实知识库权限、更新频率或 owner 承诺。'],
    passCriteria: ['risk_statement 使用如果/那么结构。', 'probability 与 impact 都有初始依据。', 'trigger_condition 和 fallback_plan 可执行。', 'status 只写 draft 或 pending_review，不提前完成 W12D5。'],
    remediation: { label: '回到风险来源和触发/兜底', sectionId: 'concepts', anchor: '#concept-portfolio-risk-source' },
  },
  exercises: [
    exercise('w12d4-source', ['概念与边界', '工作场景'], ['portfolio-risk-source', 'portfolio-risk-statement'], '哪一句最适合作为 W12D4 的风险条目来源？', ['W12D3 cannot_prove 写明真实工单权限和样本代表性未证明', '我感觉项目可能不够酷', 'W12D5 评审纪要已经完成'], 0, '风险来源必须可追溯到 W12D3 的证据边界或缺口。', '回看风险来源'),
    exercise('w12d4-rank', ['证据判断'], ['portfolio-risk-probability', 'portfolio-risk-impact'], '风险登记册里 probability 和 impact 最应该怎样写？', ['都写 high，这样显得重视', 'probability=medium 因 owner 未确认；impact=high 因作品集样本代表性会受损', '本地模拟通过，所以 probability=none 且 impact=none'], 1, '概率和影响要分开写，并且说明证据依据和限制。', '回看概率与影响'),
    exercise('w12d4-control', ['机制推演'], ['portfolio-risk-prevention', 'portfolio-risk-monitoring'], '哪组更像可执行的预防和监控？', ['预防：大家注意；监控：感觉是否还好', '预防：本周确认脱敏字段 owner；监控：每周检查权限回复和字段清单', '预防：等 W12D6 再说；监控：无'], 1, '预防和监控都必须有可观察动作和检查对象。', '回看预防与监控'),
    exercise('w12d4-response', ['综合变式'], ['portfolio-risk-trigger-fallback', 'portfolio-risk-owner'], '进入 W12D5 前，哪条状态最不越界？', ['status=pending_review，owner=产品经理临时跟进，W12D5 确认或修订 owner', 'status=closed，风险已完全消失', 'status=approved，跨职能已同意但没有记录'], 0, 'W12D4 只能形成待评审风险登记，不提前声称风险关闭或评审通过。', '回看责任人与状态'),
  ],
  deliverable: {
    title: '风险登记册',
    conceptIds: [...conceptIds],
    purpose: '用 `risk-register.csv` 把 W12D3 不能证明的事项登记为可跟踪、可预防、可监控、可兜底、有人负责的风险条目。',
    whenToUse: '在 W12D5 跨职能评审与修订之前，用来把验证日志中的不确定性转成评审材料。',
    audience: '导师、评审者、未来面试官，以及后续需要确认 owner 和预案的跨职能角色。',
    fields: [
      { name: 'risk_id', meaning: '风险条目的唯一编号。', source: '风险登记册字段' },
      { name: 'evidence_ref', meaning: '引用 W12D3 validation-log.csv 的验证 ID 或 cannot_prove。', source: '风险来源' },
      { name: 'risk_statement', meaning: '如果……那么……的风险陈述。', source: '风险陈述概念' },
      { name: 'probability', meaning: 'low、medium、high 及依据。', source: '概率初评概念' },
      { name: 'impact', meaning: 'low、medium、high 及受影响对象。', source: '影响评估概念' },
      { name: 'prevention_action', meaning: '风险发生前要做的降低动作。', source: '预防动作概念' },
      { name: 'monitoring_signal', meaning: '持续观察的信号、频率或阈值。', source: '监控信号概念' },
      { name: 'trigger_condition', meaning: '何时启动兜底或升级。', source: '触发条件概念' },
      { name: 'fallback_plan', meaning: '触发后的备用方案和证据限制。', source: '兜底方案概念' },
      { name: 'owner', meaning: '当前负责跟踪的人或角色。', source: '责任人概念' },
      { name: 'review_cadence', meaning: '多久更新一次风险状态。', source: '责任人检查节奏' },
      { name: 'status', meaning: 'draft、pending_review、monitoring、mitigating 等。', source: '风险状态字段' },
      { name: 'evidence_limit', meaning: '本风险登记能证明和不能证明什么。', source: '证据边界' },
    ],
    badExample: 'risk-register.csv\nR-1,项目风险,可能出问题,high,high,加强沟通,看看情况,感觉不对,再说,大家,随时,closed,风险已经消除',
    badReasons: ['没有引用 W12D3 证据来源。', '风险陈述不可评审。', '触发、兜底和 owner 不可执行。', '把登记册越界写成风险关闭。'],
    revisionSteps: ['引用 W12D3 validation-log.csv。', '把 cannot_prove 改写成风险陈述。', '分别写 probability 与 impact。', '补 prevention_action 与 monitoring_signal。', '写 trigger_condition 与 fallback_plan。', '指定临时 owner、review_cadence、status 和 evidence_limit。'],
    goodExample: 'risk_id,evidence_ref,risk_statement,probability,impact,prevention_action,monitoring_signal,trigger_condition,fallback_plan,owner,review_cadence,status,evidence_limit\nR-001,W12D3 VAL-001 cannot_prove:真实工单权限和样本代表性未证明,如果真实客服工单权限未获批那么验证只能停留在教学样本且样本代表性无法被评审,medium:owner未确认但有教学样本fallback,high:作品集证据可信度受损,本周向客服主管确认脱敏字段和可用样本范围,每周检查owner回复状态和可用字段清单,三天内未获得真实工单字段确认,使用教学样本完成展示并在evidence_limit标注真实代表性缺口,产品经理临时跟进;W12D5确认客服主管owner,每周五,pending_review,教学模拟登记只能证明风险管理结构完整不能证明真实概率/owner承诺/风险已经消除',
    guidedPrompts: ['写 risk_id 与 evidence_ref。', '写 risk_statement。', '写 probability。', '写 impact。', '写 prevention_action。', '写 monitoring_signal。', '写 trigger_condition 与 fallback_plan。', '写 owner / review_cadence / status / evidence_limit。'],
    blankTemplate: 'risk_id,evidence_ref,risk_statement,probability,impact,prevention_action,monitoring_signal,trigger_condition,fallback_plan,owner,review_cadence,status,evidence_limit\n',
    standardTemplate: 'risk_id,evidence_ref,risk_statement,probability,impact,prevention_action,monitoring_signal,trigger_condition,fallback_plan,owner,review_cadence,status,evidence_limit\nR-001,[引用 W12D3 validation-log.csv 的 cannot_prove],[如果...那么...],[low/medium/high + 依据],[low/medium/high + 影响对象],[事前预防动作],[监控信号 + 频率],[触发兜底的条件],[兜底方案 + 证据限制],[临时 owner 或待确认 owner],[检查节奏],[draft/pending_review/monitoring],[本登记能证明什么，不能证明什么]',
    checklist: ['引用了 W12D3 validation-log.csv。', 'risk_statement 使用如果/那么结构。', 'probability 有初始依据且不伪装成统计结论。', 'impact 写明受影响对象。', 'prevention_action 是具体动作。', 'monitoring_signal 可观察且有频率。', 'trigger_condition 明确。', 'fallback_plan 可执行且写明证据限制。', 'owner 不是“大家”。', 'status 不提前写 closed 或 approved。', 'evidence_limit 写明教学模拟边界和不能证明的真实事实。'],
  },
  memory: {
    conceptIds: [...conceptIds],
    anchors: ['风险必须来自证据边界。', '风险陈述用如果/那么。', '概率和影响分开判断。', '预防、监控、触发、兜底、owner 形成闭环。'],
    closedBookPrompt: '闭卷解释一条 risk-register.csv 如何从 W12D3 cannot_prove 走到概率、影响、预防、监控、触发、兜底和 owner。',
    microOperation: '把“真实数据可能有问题”改写成 risk_statement + probability + impact + trigger_condition + fallback_plan。',
    unresolvedPrompt: '写出你当前风险登记册里最需要 W12D5 跨职能评审确认的一项 owner 或预案。',
    reviewStages: [
      { stage: 'D1', task: '闭卷写出 risk-register.csv 的 13 个字段。' },
      { stage: 'D3', task: '把一个 cannot_prove 改写成如果/那么风险陈述。' },
      { stage: 'D7', task: '给一条风险分别补 probability 与 impact 依据。' },
      { stage: 'D14', task: '检查一条风险是否有预防、监控、触发和兜底。' },
      { stage: 'D30', task: '复述 W12D4 与 W12D5 的边界。' },
      { stage: 'D60', task: '用 evidence_limit 解释为什么风险登记册不能证明风险已经消除。' },
    ],
  },
  nextLesson: {
    id: 'W12D5',
    title: '跨职能评审与修订',
    bridge: '下一课才邀请或模拟跨职能视角审阅风险、owner 和预案并形成修订记录；本课只交付待评审风险登记册。',
  },
}
