import type { DailyCourse, Exercise } from './types'

const conceptIds = [
  'portfolio-system-boundary',
  'portfolio-user-journey-touchpoint',
  'portfolio-data-entity',
  'portfolio-data-source-owner',
  'portfolio-io-contract',
  'portfolio-state-lifecycle',
  'portfolio-integration-dependency',
  'portfolio-system-data-decision',
] as const

const prerequisiteConceptIds = [
  'portfolio-problem-statement',
  'portfolio-target-user',
  'portfolio-evidence-inventory',
  'portfolio-missing-evidence',
  'portfolio-success-metric',
  'portfolio-scope-non-goals',
  'portfolio-brief-decision',
]

function exercise(
  id: string,
  categories: Exercise['categories'],
  conceptIdsForExercise: string[],
  prompt: string,
  options: string[],
  answerIndex: number,
  referenceAnswer: string,
  remediationLabel: string,
): Exercise {
  return {
    id,
    kind: 'single-choice',
    categories,
    conceptIds: conceptIdsForExercise,
    prompt,
    hint: '先判断它是否从 W12D1 的问题和范围出发，再看系统边界、数据对象、输入输出、状态和依赖是否可追溯。',
    options: options.map((label, index) => ({
      label,
      rationale: index === answerIndex ? '这项把系统职责、数据字段和证据边界连接起来，适合进入系统与数据方案。' : '这项要么直接跳到实现，要么缺少数据责任或越过了 W12D2 的证据边界。',
      couldBeTrueWhen: index === answerIndex ? '当方案只服务已定义问题，并明确后续需要 W12D3 验证时。' : '只有在补齐系统方案、验证日志、风险评审或真实数据后，才可能成为后续判断。',
    })),
    answerIndex,
    referenceAnswer,
    reasoning: ['系统与数据方案回答“用哪些系统和数据支撑这个问题”。', '每个数据对象都要有来源、责任人、状态和输入输出边界。', 'W12D2 只设计方案，不证明方案已经运行有效。'],
    rubric: ['系统边界清楚', '数据对象和来源明确', '状态与输入输出可追踪', '没有提前交付 W12D3–W12D6'],
    commonErrors: [
      { error: '直接画全量架构图', reason: '架构图如果不回到 W12D1 的问题和范围，就无法判断哪些部分必要。' },
      { error: '只写“接数据库/接 AI”', reason: '没有数据对象、来源、字段和责任人，研发无法评审可行性。' },
    ],
    remediation: { label: remediationLabel, sectionId: 'concepts', anchor: `#concept-${conceptIdsForExercise[0]}` },
  }
}

export const w12d2: DailyCourse = {
  id: 'W12D2',
  contentVersion: 'w12d2-system-data-plan-day01-v1',
  week: 12,
  day: 2,
  title: '系统与数据方案',
  subtitle: '把 W12D1 的合格 Brief 转成一份有限的 system-data-plan.md：说明系统边界、用户触点、数据对象、来源责任、输入输出、状态生命周期和外部依赖；不运行验证、不写风险登记、不做最终作品集。',
  duration: { core: 30, standard: 45, extension: 60, full: 112 },
  coreConceptGroups: [
    {
      id: 'system-scope-touchpoint',
      title: '先把系统边界和用户触点限定住',
      conceptIds: ['portfolio-system-boundary', 'portfolio-user-journey-touchpoint'],
      summary: '系统方案不是把所有能力画进一张大图，而是从 Brief 的目标用户、场景和范围出发，标出本轮系统负责到哪里。',
      boundary: '本组不选择技术栈、不写研发排期，也不证明方案可上线。',
    },
    {
      id: 'data-object-responsibility',
      title: '把数据对象、来源和责任写成账本',
      conceptIds: ['portfolio-data-entity', 'portfolio-data-source-owner', 'portfolio-io-contract'],
      summary: '每个数据对象都要说明字段、来源、产生者、消费者、输入输出和不可用时的处理。',
      boundary: '教学方案只能证明字段思考完整，不能证明真实数据存在、质量达标或权限已批准。',
    },
    {
      id: 'state-dependency-decision',
      title: '用状态、依赖和决策控制后续验证',
      conceptIds: ['portfolio-state-lifecycle', 'portfolio-integration-dependency', 'portfolio-system-data-decision'],
      summary: '状态生命周期说明对象如何变化，集成依赖说明要向谁拿证据，方案决策说明是否进入 W12D3 验证日志。',
      boundary: '本日只交付 `system-data-plan.md`，不产出可运行验证日志、风险登记册、评审纪要或最终作品集。',
    },
  ],
  prerequisiteConceptIds,
  learningPaths: {
    '30': {
      guidedStepIndices: [0, 1, 2, 3, 4, 5],
      guidedRecordIndices: [0, 1, 2],
      exerciseCount: 3,
      deliverablePromptCount: 5,
      deliverableChecklistIndices: [0, 1, 2, 3, 4],
      deliverableMinimumContributionCharacters: 170,
    },
    '45': {
      guidedStepIndices: [0, 1, 2, 3, 4, 5],
      guidedRecordIndices: [0, 1, 2, 3],
      exerciseCount: 4,
      deliverablePromptCount: 8,
      deliverableChecklistIndices: [0, 1, 2, 3, 4, 5, 6, 7],
      deliverableMinimumContributionCharacters: 280,
    },
  },
  primaryGoal: '提交一份 `system-data-plan.md`：包含 brief_ref、system_goal、system_boundary、user_touchpoints、data_entities、data_sources、input_output_contracts、state_lifecycle、dependencies、privacy_access_boundary、validation_questions、non_goals、evidence_limit。',
  scenario: {
    role: '你是继续完善作品集的产品经理实习生。',
    situation: 'W12D1 已经定义了值得解决的问题，但评审者下一步会追问：这个问题需要哪些系统动作和数据证据支持？哪些数据真的存在？哪些只是教学模拟？',
    question: '怎样把 Brief 转成系统与数据方案，让研发、数据和安全可以评审边界，而不是看到一张无法落地的大架构图？',
    stakes: '方案过宽会把作品集拖成空泛平台；数据来源不清会让 W12D3 验证日志无法运行。边界写清楚，后续验证才有对象。',
  },
  objectives: [
    { id: 'w12d2-objective-boundary', text: '从 Brief 推出有限系统边界', evidence: '方案包含 system_goal、system_boundary 与 non_goals。' },
    { id: 'w12d2-objective-data', text: '列出数据对象、来源和责任人', evidence: '方案包含 data_entities、data_sources 与 privacy_access_boundary。' },
    { id: 'w12d2-objective-contract', text: '写出输入输出契约和状态生命周期', evidence: '方案包含 input_output_contracts 与 state_lifecycle。' },
    { id: 'w12d2-objective-decision', text: '形成进入验证日志的有限问题清单', evidence: 'validation_questions 只指向 W12D3 可验证问题，不提前声称已验证。' },
  ],
  prerequisites: [
    {
      id: 'w12d2-brief-readiness',
      conceptIds: ['portfolio-problem-statement', 'portfolio-target-user', 'portfolio-scope-non-goals', 'portfolio-brief-decision'],
      prompt: '你能用 W12D1 Brief 说明目标用户、问题、范围和下一步吗？',
      passDescription: '能说出 user_problem、target_user、scope、non_goals 与 next_step。',
      remediationLabel: '补学 W12D1：项目 Brief',
      remediationTarget: '#/lesson/W12D1',
      remediation: { purpose: '系统方案必须从合格 Brief 出发；没有 Brief 容易直接画空泛平台。', steps: ['回看 W12D1 的 13 个字段。', '写出当前 Brief 的目标用户和非目标。', '说明 W12D2 只做方案设计。'], successCheck: '能用一句话说清系统方案服务哪个问题。' },
    },
    {
      id: 'w12d2-evidence-readiness',
      conceptIds: ['portfolio-evidence-inventory', 'portfolio-missing-evidence', 'portfolio-success-metric'],
      prompt: '你能区分已有证据、缺失证据和后续成功指标吗？',
      passDescription: '能说明哪些数据来自教学成果，哪些真实生产数据还缺。',
      remediationLabel: '补学 W12D1：证据和指标边界',
      remediationTarget: '#/lesson/W12D1',
      remediation: { purpose: 'W12D2 会设计数据对象；如果证据边界不清，会把不存在的数据写成已接入。', steps: ['复述 evidence_used 与 missing_evidence。', '把 success_metric 改写成需要哪些数据字段。'], successCheck: '能列出至少一个已有数据对象和一个缺失数据对象。' },
    },
  ],
  concepts: [
    {
      id: 'portfolio-system-boundary', prerequisiteConceptIds: ['portfolio-brief-decision'],
      term: '系统边界', english: 'System Boundary',
      definition: '系统边界说明本方案负责处理哪些用户动作、数据对象和输出，不负责哪些外部流程或后续文档。',
      why: '没有边界，方案会无限膨胀成“平台”；有边界，研发才能判断第一版是否可做。',
      problemSolved: '回答“这个系统第一版到底承担哪段责任”。',
      input: 'W12D1 的目标用户、问题、范围、非目标和最大未知。',
      output: 'system_goal、system_boundary 与 non_goals。',
      systemPosition: '位于系统与数据方案开头，约束所有后续数据对象和依赖。',
      process: ['从 Brief 取出目标问题。', '写出系统负责的开始和结束点。', '列出本轮明确不处理的外部事项。'],
      owner: '产品经理提出边界，研发和数据角色在后续评审中确认。',
      notResponsibleFor: '系统边界不负责证明方案已经运行，也不替代技术架构评审。',
      compareWith: '产品范围描述做什么；系统边界描述系统责任从哪里开始到哪里结束。',
      evidence: ['W12D1 scope / non_goals。', '用户触点和数据对象清单。'],
      failureModes: ['把真实上线、运营流程和评审报告全画进系统。', '只写“做 AI 平台”没有起止点。'],
      pmUse: '用它阻止方案蔓延，并向研发解释第一版可评审范围。',
      correctExample: '本系统只负责接收失败样本、生成分类建议、输出可追溯复盘记录；不接生产客服系统。',
      incorrectExample: '系统负责所有客服、知识库、质检、上线和答辩。',
    },
    {
      id: 'portfolio-user-journey-touchpoint', prerequisiteConceptIds: ['portfolio-system-boundary'],
      term: '用户旅程触点', english: 'User Journey Touchpoint',
      definition: '用户旅程触点是目标用户在方案中实际输入、查看、确认或导出的关键步骤。',
      why: '系统方案必须服务用户动作；如果只有后台模块，评审者看不出方案怎样解决用户问题。',
      problemSolved: '回答“目标用户在系统里具体做哪几步”。',
      input: '目标用户、当前阻碍、系统边界和预期输出。',
      output: 'user_touchpoints 列表，每项包含用户动作、系统反馈和数据变化。',
      systemPosition: '连接 Brief 与数据对象，决定哪些数据字段真的需要。',
      process: ['列用户开始动作。', '列系统中间反馈。', '列用户确认或导出动作。'],
      owner: '产品经理负责设计，目标用户或导师后续验证是否合理。',
      notResponsibleFor: '触点不负责画高保真 UI，也不证明用户一定会使用。',
      compareWith: '页面清单只列屏幕；旅程触点必须说明用户动作和系统反馈。',
      evidence: ['W12D1 user_problem。', '待验证的工作流程假设。'],
      failureModes: ['只有“首页/列表/详情”屏幕名。', '忽略用户确认或修改动作。'],
      pmUse: '用触点推导必要字段，避免为了“看起来完整”堆模块。',
      correctExample: '评审产品经理导入失败样本，查看分类建议，修改错误分类，导出复盘记录。',
      incorrectExample: '用户打开平台，然后系统自动完成所有事情。',
    },
    {
      id: 'portfolio-data-entity', prerequisiteConceptIds: ['portfolio-user-journey-touchpoint'],
      term: '数据对象', english: 'Data Entity',
      definition: '数据对象是方案中需要被创建、读取、更新或导出的业务记录，例如失败样本、分类建议、证据来源和复盘记录。',
      why: '没有数据对象，系统方案无法落到字段、来源、状态和验证问题。',
      problemSolved: '回答“系统到底围绕哪些记录工作”。',
      input: '用户触点、成功指标、已有证据和缺失证据。',
      output: 'data_entities 列表，包含对象名、关键字段、用途和证据限制。',
      systemPosition: '位于用户触点之后，输入输出契约和状态生命周期之前。',
      process: ['从每个触点抽出被操作的名词。', '判断是否需要长期保存。', '写关键字段和用途。'],
      owner: '产品经理定义业务对象，研发/数据角色后续确认字段和存储。',
      notResponsibleFor: '数据对象不等于数据库表设计，也不证明字段已经存在。',
      compareWith: '数据字段是对象的属性；数据对象是字段聚合后的业务记录。',
      evidence: ['样本集字段。', '失败分类表。', 'Brief 中的 success_metric。'],
      failureModes: ['把“用户体验”当数据对象。', '只写数据库名不写业务用途。'],
      pmUse: '把需求从抽象功能落到可评审记录。',
      correctExample: 'FailureSample：case_id、input、expected_action、actual_output、evidence_limit。',
      incorrectExample: '接入一个万能数据中心，但不说明失败样本、分类建议或复盘记录这些业务对象。',
    },
    {
      id: 'portfolio-data-source-owner', prerequisiteConceptIds: ['portfolio-data-entity'],
      term: '数据来源与责任', english: 'Data Source and Owner',
      definition: '数据来源与责任说明每个数据对象来自哪里、由谁提供、谁维护，以及当前是否只是教学模拟。',
      why: '字段设计看起来完整不代表数据可用；来源和责任不清会阻断验证和评审。',
      problemSolved: '回答“这条数据谁给、谁负责、缺了怎么办”。',
      input: 'data_entities、已有证据、缺失证据、权限和脱敏边界。',
      output: 'data_sources 字段，包含 source_type、owner、freshness、access_boundary 和 missing_reason。',
      systemPosition: '连接数据对象与隐私/权限边界，决定 W12D3 是否能验证。',
      process: ['给每个对象标来源。', '写责任人或待确认 owner。', '标注教学模拟或真实数据缺口。'],
      owner: '产品经理维护来源账本，数据/安全/业务角色后续确认。',
      notResponsibleFor: '来源责任不负责授权真实生产访问，也不证明数据质量。',
      compareWith: '证据清单说明已有材料；数据来源说明未来方案从哪里取数。',
      evidence: ['W11D3/W11D4/W11D6 教学成果。', '缺失的真实工单、日志或访谈。'],
      failureModes: ['写“由系统提供”但没有 owner。', '把教学模拟样本写成生产日志。'],
      pmUse: '提前暴露数据可用性风险，避免 W12D3 才发现无法验证。',
      correctExample: '失败样本当前来自 W11D3 教学 JSONL；真实客服工单 owner 待客服主管确认。',
      incorrectExample: '所有数据都从后台自动同步，细节研发处理。',
    },
    {
      id: 'portfolio-io-contract', prerequisiteConceptIds: ['portfolio-data-source-owner'],
      term: '输入输出契约', english: 'Input/Output Contract',
      definition: '输入输出契约说明每个系统动作需要什么输入、产出什么结果、错误时返回什么信息和证据边界。',
      why: '没有契约，研发不知道接口或批处理要校验什么；产品也无法判断失败属于字段、权限还是模型输出。',
      problemSolved: '回答“动作发生时，系统收什么、给什么、怎么失败”。',
      input: '用户触点、数据对象、来源责任和系统边界。',
      output: 'input_output_contracts，包含 action、required_inputs、outputs、error_cases 和 evidence_limit。',
      systemPosition: '位于数据来源之后，状态生命周期之前。',
      process: ['选择一个用户动作。', '列必要输入和校验。', '列成功输出和失败输出。'],
      owner: '产品经理定义业务契约，研发后续转成接口或任务契约。',
      notResponsibleFor: '契约不是最终 API 文档，也不证明接口已经开发。',
      compareWith: '数据对象说明记录长什么样；输入输出契约说明动作如何使用记录。',
      evidence: ['W1D3/W1D4 的请求响应边界。', 'W12D2 教学模拟运行记录。'],
      failureModes: ['只写“上传文件成功”。', '没有错误输出或 evidence_limit。'],
      pmUse: '把系统方案转成研发可追问的字段和异常。',
      correctExample: '导入样本需要 case_id/input/expected_action；失败时返回 missing_field 与可修复字段。',
      incorrectExample: '用户提交后系统智能处理并给出最佳结果。',
    },
    {
      id: 'portfolio-state-lifecycle', prerequisiteConceptIds: ['portfolio-io-contract'],
      term: '状态生命周期', english: 'State Lifecycle',
      definition: '状态生命周期说明数据对象从创建、待分类、待复核、已导出到废弃的变化路径，以及谁可以触发变化。',
      why: '作品集项目往往不是一次性表单；没有状态，无法解释待处理、失败、复核和导出的责任。',
      problemSolved: '回答“记录在系统里如何变化，什么状态代表可交付”。',
      input: '数据对象、输入输出契约、用户确认动作和错误场景。',
      output: 'state_lifecycle，包含状态名、触发动作、进入条件、退出条件和不可越界结论。',
      systemPosition: '连接系统动作和后续验证日志，决定哪些路径需要被验证。',
      process: ['列初始状态。', '列成功和失败转移。', '标注人工复核或终态。'],
      owner: '产品经理定义状态语义，研发实现状态机或任务流。',
      notResponsibleFor: '状态生命周期不证明所有状态都已经可运行，也不替代 W12D3 验证。',
      compareWith: '流程图描述步骤；状态生命周期描述记录在每步后的可判断状态。',
      evidence: ['教学模拟状态路径。', '导出记录的自检结果。'],
      failureModes: ['只有“成功/失败”两种状态。', '没有待复核和不可判定状态。'],
      pmUse: '帮助评审者看到系统如何保留证据，而不是直接给结论。',
      correctExample: 'imported → classified_by_simulation → human_review_required → exported_for_portfolio。',
      incorrectExample: '提交后状态就是完成，完全没有 imported、待复核、已导出或异常修复路径。',
    },
    {
      id: 'portfolio-integration-dependency', prerequisiteConceptIds: ['portfolio-state-lifecycle'],
      term: '集成依赖', english: 'Integration Dependency',
      definition: '集成依赖是系统方案需要外部系统、数据源、人工角色或权限配合的地方，必须写出当前状态和替代方案。',
      why: '作品集方案如果不写依赖，会把无法访问的生产系统伪装成已接入能力。',
      problemSolved: '回答“这个方案哪些部分需要别人或外部系统支持”。',
      input: '数据来源、输入输出契约、权限边界和缺失证据。',
      output: 'dependencies 字段，包含 dependency、owner、current_status、fallback 和 validation_need。',
      systemPosition: '位于状态生命周期之后，方案决策之前。',
      process: ['列外部系统或角色。', '标当前是否可用。', '写本地教学替代或后续验证问题。'],
      owner: '产品经理维护依赖清单，后续 D5 再由跨职能角色评审。',
      notResponsibleFor: '依赖清单不代表对方已承诺，也不代表权限已批准。',
      compareWith: '数据来源是数据从哪里来；集成依赖还包括权限、流程、人和外部系统。',
      evidence: ['缺失证据列表。', '教学模拟替代路径。'],
      failureModes: ['写“已接生产系统”但无授权。', '没有 fallback。'],
      pmUse: '提前说明哪些能力只是教学模拟，哪些需要真实协作。',
      correctExample: '真实客服工单系统 owner 待确认；本课仅使用脱敏教学样本 fallback。',
      incorrectExample: '后续直接接入所有内部系统。',
    },
    {
      id: 'portfolio-system-data-decision', prerequisiteConceptIds: ['portfolio-integration-dependency'],
      term: '系统与数据方案决策', english: 'System/Data Plan Decision',
      definition: '系统与数据方案决策是在边界、数据、状态和依赖公开后，判断方案是否足以进入 W12D3 验证日志，以及先验证哪个最大未知。',
      why: '方案不是终点；它要产出下一步可运行验证问题，而不是假装已经有效。',
      problemSolved: '回答“现在能否进入验证，先验证什么”。',
      input: 'system_boundary、data_entities、contracts、state_lifecycle、dependencies 和 evidence_limit。',
      output: 'validation_questions 与 evidence_limit。',
      systemPosition: '作为 W12D2 终点，衔接 W12D3，但不替代 W12D3。',
      process: ['检查字段是否支撑 Brief 指标。', '找最大数据或系统未知。', '写进入 W12D3 的验证问题。'],
      owner: '产品经理提出，后续由实际验证日志复核。',
      notResponsibleFor: '方案决策不证明验证已经跑完、风险已经关闭、评审已经通过或作品集已经完成。',
      compareWith: 'Brief 决策决定是否设计方案；方案决策决定是否进入可运行验证。',
      evidence: ['完整 system-data-plan.md。', '明确的 validation_questions。'],
      failureModes: ['写“方案已验证”。', '没有验证问题。', '把风险登记或答辩稿提前完成。'],
      pmUse: '把方案交付转换成下一天可以执行的验证日志任务。',
      correctExample: '进入 W12D3：先验证失败样本导入后能否保留 evidence_limit 并生成可复核分类记录。',
      incorrectExample: '系统方案完成，风险和答辩都已通过。',
    },
  ],
  diagram: {
    title: '系统与数据方案的证据链',
    caption: '从 Brief 出发，经过系统边界、用户触点、数据对象、契约、状态和依赖，形成进入验证日志的问题。',
    nodes: [
      { id: 'brief', label: 'Brief', description: '问题、用户、范围和最大未知。', input: 'project-brief.md', output: 'system_goal', owner: '产品经理', evidence: 'W12D1 Brief' },
      { id: 'boundary', label: '系统边界', description: '系统负责和不负责的起止点。', input: 'scope / non_goals', output: 'system_boundary', owner: '产品经理', evidence: '边界说明' },
      { id: 'data', label: '数据对象', description: '失败样本、分类建议、复盘记录等记录。', input: '用户触点', output: 'data_entities', owner: '产品经理', evidence: '字段账本' },
      { id: 'contract', label: '输入输出契约', description: '动作需要的输入、输出和错误。', input: 'data_entities', output: 'input_output_contracts', owner: '产品经理/研发', evidence: '契约表' },
      { id: 'state', label: '状态生命周期', description: '记录从导入到复核再到导出的状态变化。', input: 'contract', output: 'state_lifecycle', owner: '产品经理/研发', evidence: '状态表' },
      { id: 'decision', label: '方案决策', description: '是否进入验证日志。', input: 'dependencies', output: 'validation_questions', owner: '产品经理', evidence: '有限决定' },
    ],
    branches: [
      { from: 'brief', to: 'boundary', label: '问题限定系统范围', kind: 'normal' },
      { from: 'boundary', to: 'data', label: '触点推导数据对象', kind: 'normal' },
      { from: 'data', to: 'contract', label: '字段进入输入输出', kind: 'normal' },
      { from: 'contract', to: 'state', label: '动作改变状态', kind: 'normal' },
      { from: 'state', to: 'decision', label: '状态决定验证问题', kind: 'normal' },
      { from: 'data', to: 'decision', label: '来源不明阻断验证', kind: 'failure' },
    ],
    evidenceNotes: ['教学模拟必须标注为教学模拟。', '方案字段不能伪装成真实生产系统已接入。', 'W12D2 只能证明方案结构质量，不能证明方案有效。'],
  },
  demonstration: {
    title: '教师示范：把 AI 客服复盘 Brief 转成系统与数据方案',
    businessProblem: 'W12D1 已定义 AI 客服失败复盘问题，但还不知道系统要处理哪些记录、字段、状态和依赖。',
    finalConclusion: '方案可以进入 W12D3，因为边界有限、数据对象可追踪、依赖和缺失证据公开，同时验证问题明确。',
    conclusionLimit: '示范只证明 system-data-plan.md 的字段组织合理，不能证明真实系统已开发、真实数据已接入、验证已运行或风险已关闭。',
    steps: [
      { title: '把 Brief 转成系统目标', action: '写 system_goal：帮助评审产品经理把失败样本转成可复核分类记录。', reason: '系统目标必须服务 user_problem。', evidence: 'system_goal 与 Brief 对齐。', proves: '能证明方案没有脱离问题。', limitation: '不能证明用户真实需要该系统。' },
      { title: '限定系统边界', action: '写系统只处理失败样本导入、分类建议、人工复核和导出。', reason: '第一版边界越清楚，后续验证越可运行。', evidence: 'system_boundary 与 non_goals。', proves: '能证明范围受控。', limitation: '不能证明边界最终正确。' },
      { title: '列出核心数据对象', action: '定义 FailureSample、ClassificationSuggestion、ReviewRecord。', reason: '系统动作必须围绕业务记录，而不是围绕口号。', evidence: 'data_entities 字段完整。', proves: '能证明方案有可评审对象。', limitation: '不能证明数据库表已存在。' },
      { title: '标来源和责任', action: '把教学样本标为教学模拟，把真实客服工单标为缺失并待 owner 确认。', reason: '来源边界决定验证是否可执行。', evidence: 'data_sources 标注 owner 和 missing_reason。', proves: '能证明方案没有伪造生产接入。', limitation: '不能替代权限审批。' },
      { title: '写输入输出和状态', action: '定义导入、分类、复核、导出的输入、输出、错误和状态转移。', reason: '契约和状态让研发能判断实现和异常。', evidence: 'contracts 与 lifecycle。', proves: '能证明动作边界可讨论。', limitation: '不能证明接口已开发。' },
      { title: '给出验证问题', action: '写 W12D3 先验证导入样本能否保留 evidence_limit 并生成待复核记录。', reason: 'W12D2 的终点是可运行验证问题。', evidence: 'validation_questions。', proves: '能证明下一步可执行。', limitation: '不能证明验证已经通过。' },
    ],
  },
  guidedLab: {
    title: '系统与数据方案六路径观察器',
    goal: '用本地教学模拟观察六种方案质量路径：系统边界缺失、数据对象缺失、来源未知、契约缺失、状态缺失和合格方案。',
    safety: '教学模拟；不读取真实公司数据、不调用外部服务、不证明真实系统、真实数据或上线可行性。',
    conceptIds: [...conceptIds],
    predictionPrompt: '先预测：系统与数据方案最容易在哪个字段越界，为什么？',
    steps: [
      { title: '观察系统边界缺失', action: '选择 boundary-missing，记录方案为什么像平台口号。', observe: '系统负责所有客服全流程。', explanation: '边界缺失会让数据对象、依赖和验证问题全部失焦。', proves: '能证明 system_boundary 需要重写。', cannotProve: '不能证明更大系统未来不值得做。' },
      { title: '观察数据对象缺失', action: '选择 entity-missing，补写 FailureSample 与 ReviewRecord。', observe: '方案只有模块名，没有被处理的业务记录。', explanation: '没有对象就没有字段、状态和验证。', proves: '能证明 data_entities 不合格。', cannotProve: '不能证明研发无法设计数据库。' },
      { title: '观察来源未知', action: '选择 source-unknown，拆分教学样本和真实缺口。', observe: '声称接入真实客服工单但没有 owner。', explanation: '来源未知必须写成 dependency 或 missing_evidence。', proves: '能证明 data_sources 不完整。', cannotProve: '不能证明真实系统无法授权。' },
      { title: '观察契约缺失', action: '选择 contract-missing，补输入、输出和错误。', observe: '只有“上传后分类”，没有 required_inputs 或 error_cases。', explanation: '契约缺失会导致研发无法评审动作边界。', proves: '能证明 input_output_contracts 需要修订。', cannotProve: '不能证明未来接口一定失败。' },
      { title: '观察状态缺失', action: '选择 state-missing，补待复核和已导出状态。', observe: '系统把一次提交直接写成完成。', explanation: '状态缺失会掩盖人工复核和证据边界。', proves: '能证明 state_lifecycle 不完整。', cannotProve: '不能证明复核流程最终不可用。' },
      { title: '观察合格方案', action: '选择 qualified-plan，记录为什么可以进入 W12D3。', observe: '边界、对象、来源、契约、状态、依赖和验证问题齐全。', explanation: '合格方案是验证日志入口，不是运行结果。', proves: '能证明本地教学模拟中的方案合同质量。', cannotProve: '不能证明真实系统已开发、真实数据已接入或验证已通过。' },
    ],
    recordPrompts: ['记录最先失败的方案字段。', '写出这一路径能证明什么。', '写出这一路径不能证明什么。', '写一句进入 W12D3 前的修订动作。'],
    comparePrompt: '比较六条路径：哪一类是系统边界失败，哪一类是数据责任失败，哪一类是验证入口失败？',
    passCriteria: ['六条教学模拟路径都运行并记录。', '每条记录都写出能证明与不能证明。', '没有把教学模拟写成真实系统证据。', '合格路径只进入 W12D3，不声称验证日志或作品集完成。'],
  },
  independentLab: {
    title: '独立变式：为内部知识库助手写系统与数据方案',
    scenario: '假设 W12D1 Brief 选择“内部知识库助手”，但目前只有教学模拟和少量课程成果，没有真实知识库权限或工单日志。',
    conceptIds: [...conceptIds],
    changedConditions: ['目标用户从产品经理换成客服主管', '核心数据对象从失败样本换成知识条目', '最大未知从样本覆盖换成权限和更新频率'],
    task: '写出系统边界、用户触点、数据对象、来源责任、输入输出、状态、依赖和验证问题，不提前运行验证。',
    predictionPrompt: '先预测：这个变式最大的系统或数据依赖是什么？',
    evidenceRequirements: ['至少引用一条 W12D1 Brief 字段或已完成教学成果。', '明确说明教学模拟不能证明真实知识库权限、数据质量或方案有效。'],
    passCriteria: ['系统边界只服务一个目标用户问题。', 'data_entities 至少包含两个业务对象。', 'data_sources 写明 owner 或 missing_reason。', 'validation_questions 只指向 W12D3，不提前完成验证。'],
    remediation: { label: '回到数据对象和来源责任', sectionId: 'concepts', anchor: '#concept-portfolio-data-entity' },
  },
  exercises: [
    exercise('w12d2-boundary', ['概念与边界', '工作场景'], ['portfolio-system-boundary', 'portfolio-user-journey-touchpoint'], '哪句话最适合写进 system_boundary？', ['系统覆盖全部客服、知识库、风控和上线流程', '本轮只处理失败样本导入、分类建议、人工复核和复盘记录导出', '系统会自动证明业务价值'], 1, '边界必须说明第一版负责的起止点，并保留非目标。', '回看系统边界'),
    exercise('w12d2-data-source', ['证据判断'], ['portfolio-data-entity', 'portfolio-data-source-owner'], '真实客服工单目前没有权限。data_sources 最稳妥的写法是什么？', ['写成已接入生产工单', '标为 missing_reason，并用教学样本作为本地 fallback', '删除所有数据来源'], 1, '来源未知必须公开写成缺口或依赖，不能伪装已接入。', '回看数据来源与责任'),
    exercise('w12d2-contract', ['机制推演'], ['portfolio-io-contract', 'portfolio-state-lifecycle'], '导入失败样本时最该进入契约的组合是什么？', ['required_inputs、outputs、error_cases 和状态变化', '按钮颜色和页面标题', '最终答辩评分'], 0, '输入输出契约要让动作、错误和状态可评审。', '回看输入输出契约'),
    exercise('w12d2-decision', ['综合变式'], ['portfolio-integration-dependency', 'portfolio-system-data-decision'], 'W12D2 结尾最不越界的 validation_questions 是什么？', ['进入 W12D3 验证导入样本后是否保留 evidence_limit 并生成待复核记录', '验证日志已经完成且系统上线', '风险登记册和答辩稿已通过'], 0, 'W12D2 只能提出进入 W12D3 的验证问题，不能提前完成后续交付。', '回看方案决策'),
  ],
  deliverable: {
    title: '系统与数据方案',
    conceptIds: [...conceptIds],
    purpose: '用 `system-data-plan.md` 把合格 Brief 转成可评审的系统边界、数据对象、契约、状态、依赖和验证问题。',
    whenToUse: '在 W12D3 可运行验证日志之前，用来判断验证对象和数据来源是否清楚。',
    audience: '导师、研发、数据、安全和未来面试官。',
    fields: [
      { name: 'brief_ref', meaning: '引用 W12D1 Brief 的项目标题、问题和范围。', source: 'W12D1 Brief' },
      { name: 'system_goal', meaning: '系统第一版要支撑的用户问题。', source: '系统边界' },
      { name: 'system_boundary', meaning: '系统负责与不负责的起止点。', source: '系统边界' },
      { name: 'user_touchpoints', meaning: '目标用户实际输入、查看、确认或导出的步骤。', source: '用户旅程触点' },
      { name: 'data_entities', meaning: '方案中的业务记录和关键字段。', source: '数据对象' },
      { name: 'data_sources', meaning: '每个对象的来源、owner、真实性和缺口。', source: '数据来源与责任' },
      { name: 'input_output_contracts', meaning: '动作输入、输出、错误和证据边界。', source: '输入输出契约' },
      { name: 'state_lifecycle', meaning: '对象状态、触发动作、进入和退出条件。', source: '状态生命周期' },
      { name: 'dependencies', meaning: '外部系统、角色、权限或数据依赖。', source: '集成依赖' },
      { name: 'privacy_access_boundary', meaning: '脱敏、权限、不能接触的真实数据。', source: '数据来源与责任' },
      { name: 'validation_questions', meaning: '进入 W12D3 的可运行验证问题。', source: '方案决策' },
      { name: 'non_goals', meaning: '本日不处理或不声称完成的事项。', source: '系统边界' },
      { name: 'evidence_limit', meaning: '本方案能证明与不能证明的边界。', source: '方案决策' },
    ],
    badExample: '系统：做一个 AI 客服平台。数据：接所有客服系统。验证：系统方案已证明有效，风险和答辩已完成。',
    badReasons: ['没有引用 Brief 的具体问题。', '数据来源和 owner 不清。', '提前声称验证、风险和答辩已完成。'],
    revisionSteps: ['先引用 W12D1 Brief。', '限定系统负责的用户触点。', '列数据对象和来源责任。', '写输入输出和状态。', '把下一步限制为 W12D3 验证问题。'],
    goodExample: '# system-data-plan.md\n\n- brief_ref: W12D1 AI 客服失败复盘证据链 Brief。\n- system_goal: 帮助试点评审产品经理把 AI 客服失败样本转成可复核分类记录。\n- system_boundary: 本轮只处理教学失败样本导入、分类建议、人工复核和复盘记录导出；不接生产客服系统。\n- user_touchpoints: 导入失败样本；查看分类建议；修改分类；导出复盘记录。\n- data_entities: FailureSample(case_id,input,expected_action,actual_output,evidence_limit)；ClassificationSuggestion(case_id,category,reason,confidence,needs_review)；ReviewRecord(case_id,final_category,reviewer_note,export_status)。\n- data_sources: FailureSample 当前来自 W11D3 教学样本；真实客服工单为 missing，owner 待客服主管确认；所有教学数据必须标注教学模拟。\n- input_output_contracts: import_samples 需要 case_id/input/expected_action，输出 imported_count 和 missing_field_errors；classify_sample 输出 category/reason/needs_review；export_review 输出 review_record_id。\n- state_lifecycle: drafted → imported → classified_by_simulation → human_review_required → reviewed → exported；异常进入 needs_fix。\n- dependencies: 真实工单系统、客服主管 owner、安全脱敏规则；当前 fallback 为本地教学样本。\n- privacy_access_boundary: 不写真实客户姓名、联系方式、生产日志、Token 或内部地址。\n- validation_questions: W12D3 先验证导入 3 条教学样本后，是否保留 evidence_limit 并生成 human_review_required 记录。\n- non_goals: 不运行真实模型，不接生产系统，不完成验证日志、风险登记册、评审纪要或最终作品集。\n- evidence_limit: 本方案只能证明系统与数据结构设计质量，不能证明真实数据存在、方案有效、验证通过或上线可行。',
    guidedPrompts: ['写 brief_ref。', '写 system_goal 与 system_boundary。', '写 user_touchpoints。', '写 data_entities。', '写 data_sources。', '写 input_output_contracts。', '写 state_lifecycle / dependencies / privacy_access_boundary。', '写 validation_questions / non_goals / evidence_limit。'],
    blankTemplate: '# system-data-plan.md\n\n- brief_ref: \n- system_goal: \n- system_boundary: \n- user_touchpoints: \n- data_entities: \n- data_sources: \n- input_output_contracts: \n- state_lifecycle: \n- dependencies: \n- privacy_access_boundary: \n- validation_questions: \n- non_goals: \n- evidence_limit: ',
    standardTemplate: '# system-data-plan.md\n\n- brief_ref: [引用 W12D1 Brief 的具体问题]\n- system_goal: [系统第一版支撑什么用户问题]\n- system_boundary: [负责什么 / 不负责什么]\n- user_touchpoints: [用户输入、查看、确认、导出的步骤]\n- data_entities: [对象名 + 关键字段 + 用途]\n- data_sources: [来源 + owner + 教学模拟/真实缺口]\n- input_output_contracts: [动作 + required_inputs + outputs + error_cases]\n- state_lifecycle: [状态 + 触发动作 + 进入/退出条件]\n- dependencies: [外部系统/角色/权限 + 当前状态 + fallback]\n- privacy_access_boundary: [脱敏、权限、不能写入的真实数据]\n- validation_questions: [进入 W12D3 的可运行验证问题]\n- non_goals: [不提前交付 W12D3-D6]\n- evidence_limit: [本方案能证明什么，不能证明什么]',
    checklist: ['引用了 W12D1 Brief。', 'system_boundary 与 non_goals 分开。', '至少两个 data_entities 有关键字段。', '每个核心数据对象都有 source 或 missing_reason。', 'input_output_contracts 包含错误情况。', 'state_lifecycle 不把一次提交直接写成完成。', 'validation_questions 只指向 W12D3。', 'evidence_limit 写明教学模拟边界和不能证明的真实事实。'],
  },
  memory: {
    conceptIds: [...conceptIds],
    anchors: ['系统方案先从 Brief 推出边界。', '数据对象必须有来源和 owner。', '输入输出契约要包含错误和 evidence_limit。', 'W12D2 只决定进入 W12D3 验证什么。'],
    closedBookPrompt: '闭卷解释一份系统与数据方案如何从 Brief、边界、触点、数据对象、来源、契约、状态、依赖走到验证问题。',
    microOperation: '把“接入全部客服数据”改写成 data_sources + dependencies + privacy_access_boundary。',
    unresolvedPrompt: '写出你当前方案最大的系统或数据未知，以及它应在 W12D3 如何验证。',
    reviewStages: [
      { stage: 'D1', task: '闭卷写出 system-data-plan.md 的 13 个字段。' },
      { stage: 'D3', task: '给一个 data_entity 补上 source、owner 和 evidence_limit。' },
      { stage: 'D7', task: '把一个过宽系统目标改成有限 system_boundary。' },
      { stage: 'D14', task: '检查一条 input_output_contract 是否包含错误输出。' },
      { stage: 'D30', task: '复述 W12D2 与 W12D3 的边界。' },
      { stage: 'D60', task: '用方案决策解释为什么不能把方案写成验证已通过。' },
    ],
  },
  nextLesson: {
    id: 'W12D3',
    title: '最大未知的可运行验证日志',
    bridge: '下一课才运行 W12D2 提出的最大未知验证；本课只交付系统与数据方案。',
  },
}
