import type { DailyCourse, Exercise } from './types'

const conceptIds = [
  'portfolio-review-role',
  'portfolio-review-question',
  'portfolio-review-evidence-response',
  'portfolio-review-gap',
  'portfolio-review-decision',
  'portfolio-review-revision-action',
  'portfolio-review-owner-confirmation',
  'portfolio-review-change-log',
] as const

const prerequisiteConceptIds = [
  'portfolio-risk-source',
  'portfolio-risk-statement',
  'portfolio-risk-probability',
  'portfolio-risk-impact',
  'portfolio-risk-prevention',
  'portfolio-risk-monitoring',
  'portfolio-risk-trigger-fallback',
  'portfolio-risk-owner',
]

function exercise(
  id: string,
  categories: Exercise['categories'],
  ids: string[],
  prompt: string,
  options: string[],
  answerIndex: number,
  referenceAnswer: string,
  remediationLabel: string,
): Exercise {
  return {
    id,
    kind: 'single-choice',
    categories,
    conceptIds: ids,
    prompt,
    hint: '先看评审角色是否明确，再看问题、证据回答、缺口、决策、修订动作、owner 和变更记录是否可追溯。',
    options: options.map((label, index) => ({
      label,
      rationale: index === answerIndex ? '这项把角色追问、证据回答、修订动作和责任边界连起来，适合进入评审纪要。' : '这项要么没有角色化追问，要么缺少证据和修订动作，或把评审纪要写成最终作品集批准。',
      couldBeTrueWhen: index === answerIndex ? '当结论只基于本地教学模拟与已有作品集材料，并明确 W12D6 仍未完成时。' : '只有补齐真实评审记录、owner 确认和后续作品集装配后，才可能成为更强结论。',
    })),
    answerIndex,
    referenceAnswer,
    reasoning: ['评审纪要回答“谁问了什么、我们用什么证据回答、还缺什么、下一步怎么修订”。', '评审纪要必须把风险登记册转成修订动作，而不是把风险直接关闭。', 'W12D5 只形成待复核修订记录，不提前完成 W12D6 作品集、答辩或真实审批。'],
    rubric: ['评审角色具体可追溯', '角色追问可以被证据回答', '证据引用指向真实成果', '修订动作具体可执行'],
    commonErrors: [
      { error: '只写“已评审”', reason: '没有问题、证据、缺口和修订动作，无法复盘评审质量。' },
      { error: '纪要写成全部通过', reason: '本课教学模拟不能证明真实跨职能批准或 W12D6 终稿交付。' },
    ],
    remediation: { label: remediationLabel, sectionId: 'concepts', anchor: `#concept-${ids[0]}` },
  }
}

export const w12d5: DailyCourse = {
  id: 'W12D5',
  contentVersion: 'w12d5-review-notes-day01-v1',
  week: 12,
  day: 5,
  title: '跨职能评审与修订',
  subtitle: '把 W12D4 risk-register.csv 带入角色化评审：记录评审角色、追问、证据回答、缺口反馈、决策、修订动作、owner 确认和变更记录；不装配 W12D6 最终作品集，也不宣称答辩通过。',
  duration: { core: 30, standard: 45, extension: 60, full: 118 },
  coreConceptGroups: [
    {
      id: 'role-question',
      title: '从角色视角提出可回答问题',
      conceptIds: ['portfolio-review-role', 'portfolio-review-question'],
      summary: '评审不是泛泛问“有没有问题”，而是让用户、研发、数据/安全、运营等角色提出可由证据回答的追问。',
      boundary: '本组只模拟跨职能视角，不伪造真实会议或真实审批。',
    },
    {
      id: 'evidence-gap-decision',
      title: '用证据回答并留下缺口',
      conceptIds: ['portfolio-review-evidence-response', 'portfolio-review-gap', 'portfolio-review-decision'],
      summary: '每个问题都要引用 W12D1–W12D4 的成果或风险登记，回答能证明什么、还缺什么，并形成 continue、revise、block、escalate 等有限决策。',
      boundary: '教学模拟的通过只证明纪要结构，不能证明真实干系人接受。',
    },
    {
      id: 'revision-owner-log',
      title: '把反馈转成修订动作和变更记录',
      conceptIds: ['portfolio-review-revision-action', 'portfolio-review-owner-confirmation', 'portfolio-review-change-log'],
      summary: '评审纪要必须把反馈落到修订动作、owner、截止时间和变更日志，保证 W12D6 装配前有可追溯修订链。',
      boundary: 'owner 字段可以是待确认或临时跟进，不能替代真实承诺记录。',
    },
  ],
  prerequisiteConceptIds,
  learningPaths: {
    '30': {
      guidedStepIndices: [0, 1, 2, 3, 4, 5],
      guidedRecordIndices: [0, 1, 2],
      exerciseCount: 3,
      deliverablePromptCount: 5,
      deliverableChecklistIndices: [0, 1, 2, 3, 4],
      deliverableMinimumContributionCharacters: 180,
    },
    '45': {
      guidedStepIndices: [0, 1, 2, 3, 4, 5],
      guidedRecordIndices: [0, 1, 2, 3],
      exerciseCount: 4,
      deliverablePromptCount: 8,
      deliverableChecklistIndices: [0, 1, 2, 3, 4, 5, 6, 7],
      deliverableMinimumContributionCharacters: 300,
    },
  },
  primaryGoal: '提交一份 `review-notes.md`：至少包含 review_id、artifact_ref、review_role、question、evidence_cited、answer_summary、gap_or_risk、decision、revision_action、owner、due_date、status、evidence_limit。',
  scenario: {
    role: '你是准备作品集评审材料的产品经理实习生。',
    situation: 'W12D4 已经产出 risk-register.csv，但风险是否被不同角色理解、哪些证据仍不足、哪些动作需要修订，都还没有形成可追溯记录。',
    question: '怎样把一场跨职能评审写成 review-notes.md，让每条追问、回答、缺口和修订动作都能被 W12D6 装配引用？',
    stakes: '没有评审纪要，作品集会缺少“接受反馈并修订”的证据；纪要越界，又会把教学模拟伪装成真实跨职能批准。',
  },
  objectives: [
    { id: 'w12d5-objective-role', text: '为每条评审问题标注具体角色', evidence: '纪要包含 review_role 与 question。' },
    { id: 'w12d5-objective-evidence', text: '用已有成果回答追问并写出证据缺口', evidence: '纪要包含 evidence_cited、answer_summary 和 gap_or_risk。' },
    { id: 'w12d5-objective-decision', text: '把反馈转成有限决策与修订动作', evidence: '纪要包含 decision、revision_action、owner、due_date、status。' },
    { id: 'w12d5-objective-boundary', text: '明确评审模拟不能证明真实批准或作品集完成', evidence: '纪要包含 evidence_limit 且不提前完成 W12D6。' },
  ],
  prerequisites: [
    {
      id: 'w12d5-risk-register-readiness',
      conceptIds: ['portfolio-risk-source', 'portfolio-risk-statement', 'portfolio-risk-probability', 'portfolio-risk-impact'],
      prompt: '你能从 W12D4 risk-register.csv 中指出一条待评审风险和它的来源吗？',
      passDescription: '能说出一条风险的 evidence_ref、risk_statement、probability 与 impact。',
      remediationLabel: '补学 W12D4：风险来源、风险陈述、概率与影响',
      remediationTarget: '#/lesson/W12D4',
      remediation: { purpose: 'W12D5 的评审追问必须围绕待评审风险和作品集证据展开，不能凭空模拟会议。', steps: ['找到一条 risk_id。', '复述它来自哪条 evidence_ref。', '说出这条风险的概率和影响依据。'], successCheck: '能把一个风险改写成评审问题。' },
    },
    {
      id: 'w12d5-risk-control-readiness',
      conceptIds: ['portfolio-risk-prevention', 'portfolio-risk-monitoring', 'portfolio-risk-trigger-fallback', 'portfolio-risk-owner'],
      prompt: '你能说出 W12D4 风险条目里哪些控制动作需要跨职能确认吗？',
      passDescription: '能指出 prevention、monitoring、trigger/fallback 或 owner 中至少一项需要评审确认或修订。',
      remediationLabel: '补学 W12D4：控制动作、触发兜底与责任人',
      remediationTarget: '#/lesson/W12D4',
      remediation: { purpose: '评审纪要必须把风险登记册中的待确认项转成修订动作。', steps: ['找出 prevention_action。', '找出 trigger_condition 与 fallback_plan。', '判断 owner 是否只是临时跟进。'], successCheck: '能写出一条“需要确认 owner/预案”的评审问题。' },
    },
  ],
  concepts: [
    {
      id: 'portfolio-review-role', prerequisiteConceptIds: ['portfolio-risk-owner'],
      term: '评审角色', english: 'Review Role',
      definition: '评审角色是对作品集材料提出不同责任视角问题的人或职能，例如用户代表、研发、数据/安全、运营或导师。',
      why: '同一份风险登记册在不同角色眼里关注点不同，角色明确后问题才不会变成泛泛意见。',
      problemSolved: '回答“这条追问代表谁的责任视角”。',
      input: '风险登记册、系统与数据方案、项目 Brief 和作品集目标。',
      output: 'review_role 字段。',
      systemPosition: '位于评审纪要开头，用来确定问题来源和责任边界。',
      process: ['选择一个具体职能。', '说明它为什么关心这条风险。', '避免写成“大家都觉得”。'],
      owner: '产品经理组织和记录；真实评审中由对应角色确认。',
      notResponsibleFor: '评审角色字段不证明该角色真实参加或同意。',
      compareWith: 'stakeholder 是受影响方；review_role 是本次提出问题或决策建议的视角。',
      evidence: ['W12D1 stakeholders。', 'W12D4 owner 或风险控制点。'],
      failureModes: ['角色写成“团队”。', '问题与角色责任不匹配。'],
      pmUse: '让面试官看到你能按职能拆解反馈，而不是只做个人自评。',
      correctExample: 'review_role=数据/安全；关注真实工单字段权限和脱敏边界。',
      incorrectExample: 'review_role=所有人；关注所有问题。',
    },
    {
      id: 'portfolio-review-question', prerequisiteConceptIds: ['portfolio-review-role'],
      term: '角色化追问', english: 'Role-based Question',
      definition: '角色化追问是某个评审角色针对证据、风险、可行性或责任边界提出的可回答问题。',
      why: '好问题必须能被已有证据部分回答，也能暴露下一步修订方向。',
      problemSolved: '回答“这位角色具体要确认什么”。',
      input: 'review_role、risk_statement、evidence_limit 和成果字段。',
      output: 'question 字段。',
      systemPosition: '连接评审角色与证据回答。',
      process: ['从风险或证据缺口出发。', '写成可回答的问题。', '避免把建议伪装成问题。'],
      owner: '产品经理整理，评审角色确认或补充。',
      notResponsibleFor: '问题本身不等于结论，也不等于修订已经完成。',
      compareWith: '“这个安全吗？”太泛；“真实工单字段是否经过脱敏审批？”可回答。',
      evidence: ['risk-register.csv。', 'system-data-plan.md。'],
      failureModes: ['问题过宽无法回答。', '问题无法由作品集证据回答。'],
      pmUse: '把评审从观点交流变成证据对话。',
      correctExample: '数据/安全问：真实工单字段是否已有脱敏范围和访问 owner？',
      incorrectExample: '有人问：这个项目是不是还行？',
    },
    {
      id: 'portfolio-review-evidence-response', prerequisiteConceptIds: ['portfolio-review-question'],
      term: '证据回答', english: 'Evidence-backed Response',
      definition: '证据回答是用 W12D1–W12D4 的具体成果、字段或风险条目回应评审问题，并标明回答强度。',
      why: '评审纪要不能只写“已解释”；必须让读者看到回答引用了哪份材料。',
      problemSolved: '回答“我们现在能用什么证据回答到哪一步”。',
      input: 'project-brief.md、system-data-plan.md、validation-log.csv、risk-register.csv。',
      output: 'evidence_cited 与 answer_summary。',
      systemPosition: '位于问题之后，是缺口和决策的依据。',
      process: ['引用成果文件和字段。', '概括能回答的部分。', '写出证据不能覆盖的部分。'],
      owner: '产品经理记录和维护证据引用。',
      notResponsibleFor: '证据回答不证明真实评审者已经接受该回答。',
      compareWith: '“已回复”是状态；证据回答必须包含引用和有限结论。',
      evidence: ['四份 W12 成果文件。', '教学模拟观察记录。'],
      failureModes: ['没有 artifact_ref。', '把教学模拟当生产证据。'],
      pmUse: '展示作品集材料如何支撑评审沟通。',
      correctExample: '引用 W12D3 validation-log.csv 的 VAL-001 和 W12D4 R-001，说明真实工单权限仍未证明。',
      incorrectExample: '回答：这个问题我们已经讲过了。',
    },
    {
      id: 'portfolio-review-gap', prerequisiteConceptIds: ['portfolio-review-evidence-response'],
      term: '缺口反馈', english: 'Gap Feedback',
      definition: '缺口反馈是评审后仍未被证据覆盖、需要补材料、修订范围或升级确认的事项。',
      why: '缺口写清楚，修订动作才有目标；不写缺口，评审纪要会变成空泛通过记录。',
      problemSolved: '回答“现有证据还差什么”。',
      input: 'answer_summary、evidence_limit、risk_register status。',
      output: 'gap_or_risk 字段。',
      systemPosition: '位于证据回答和决策之间，决定是否 revise、block 或 escalate。',
      process: ['比较问题与证据。', '列出未证明事项。', '判断缺口影响范围。'],
      owner: '产品经理整理，相关角色确认。',
      notResponsibleFor: '缺口反馈不等于失败，也不证明项目不可做。',
      compareWith: '风险是可能发生的损害；缺口是当前证据还没覆盖的事实。',
      evidence: ['W12D4 evidence_limit。', '评审问题与回答差距。'],
      failureModes: ['把缺口写成情绪评价。', '缺口没有指向修订动作。'],
      pmUse: '把评审意见转成可执行修订。',
      correctExample: 'gap_or_risk=真实工单脱敏范围没有 owner 确认，需补 owner 或改用教学样本边界说明。',
      incorrectExample: 'gap_or_risk=感觉不够完善。',
    },
    {
      id: 'portfolio-review-decision', prerequisiteConceptIds: ['portfolio-review-gap'],
      term: '有限评审决策', english: 'Limited Review Decision',
      definition: '有限评审决策是对一条问题的当前处理状态，例如 continue、revise、block、escalate，且必须说明证据边界。',
      why: '评审需要决定下一步，但 W12D5 不能把本地模拟写成正式批准。',
      problemSolved: '回答“这条反馈当前怎么处理”。',
      input: 'gap_or_risk、impact、owner 状态和后续装配要求。',
      output: 'decision 字段。',
      systemPosition: '连接缺口反馈与修订动作。',
      process: ['判断是否能继续。', '判断是否需要修订或升级。', '写出为什么不是最终批准。'],
      owner: '产品经理记录，真实审批由对应组织流程决定。',
      notResponsibleFor: '有限决策不证明真实上线、真实批准或答辩通过。',
      compareWith: 'decision=revise 是处理方向；approved_final 是 W12D5 不得伪造的结论。',
      evidence: ['评审纪要条目。', '风险登记状态字段。'],
      failureModes: ['所有问题都写 approved。', '没有说明 revise 的依据。'],
      pmUse: '让作品集展示你会做有限、诚实的产品判断。',
      correctExample: 'decision=revise；原因是真实工单权限仍无 owner 确认。',
      incorrectExample: 'decision=approved_final；作品集已经通过。',
    },
    {
      id: 'portfolio-review-revision-action', prerequisiteConceptIds: ['portfolio-review-decision'],
      term: '修订动作', english: 'Revision Action',
      definition: '修订动作是基于评审缺口对作品集材料、风险登记或验证计划要做的具体修改。',
      why: '评审价值不在会议本身，而在把反馈转成材料变化。',
      problemSolved: '回答“接下来改哪里、怎么改”。',
      input: 'decision、gap_or_risk、受影响 artifact。',
      output: 'revision_action 字段。',
      systemPosition: '位于有限决策之后，进入变更日志前。',
      process: ['指定要改的文件或字段。', '写出具体修改。', '说明验收标准。'],
      owner: '产品经理推动，相关角色协作。',
      notResponsibleFor: '修订动作不证明修订已经完成，除非有后续变更记录。',
      compareWith: '“继续优化”不是动作；“在 evidence_limit 增加真实工单权限缺口”是动作。',
      evidence: ['被修改的 artifact_ref。', '追加式变更日志。'],
      failureModes: ['动作不可执行。', '动作没有对应证据文件。'],
      pmUse: '把评审意见转成 W12D6 可装配的修改清单。',
      correctExample: 'revision_action=在 risk-register.csv R-001 增加“真实工单权限待 owner 确认”的 evidence_limit。',
      incorrectExample: 'revision_action=后面再完善一下。',
    },
    {
      id: 'portfolio-review-owner-confirmation', prerequisiteConceptIds: ['portfolio-review-revision-action'],
      term: 'owner 确认', english: 'Owner Confirmation',
      definition: 'owner 确认是为每条修订动作记录临时负责人、待确认负责人、截止时间和当前确认状态。',
      why: '没有 owner 和时间，评审反馈不会进入闭环；但 owner 字段必须诚实区分临时跟进和真实承诺。',
      problemSolved: '回答“谁负责推进这条修订”。',
      input: 'revision_action、review_role、risk owner 和协作对象。',
      output: 'owner、due_date 与 status。',
      systemPosition: '让修订动作具备跟踪责任。',
      process: ['指定临时 owner。', '写出待确认 owner。', '设定截止时间和状态。'],
      owner: '产品经理记录；真实 owner 承诺需要真实确认材料。',
      notResponsibleFor: 'owner 字段不等于真实承诺，也不代表跨职能已批准。',
      compareWith: 'owner=产品经理临时跟进是状态；owner=客服主管已承诺需要真实记录支持。',
      evidence: ['评审纪要状态。', '真实确认记录若存在。'],
      failureModes: ['owner 写大家。', '没有 due_date 或 status。'],
      pmUse: '让修订清单具备责任闭环。',
      correctExample: 'owner=产品经理临时跟进；due_date=2026-08-27；status=pending_owner_confirmation。',
      incorrectExample: 'owner=客服主管已承诺，但没有任何确认记录。',
    },
    {
      id: 'portfolio-review-change-log', prerequisiteConceptIds: ['portfolio-review-owner-confirmation'],
      term: '变更记录', english: 'Change Log',
      definition: '变更记录是把评审问题、决策和修订动作与后续材料变化连接起来的追加式历史。',
      why: '作品集需要展示“收到反馈—判断—修订”的过程，而不是只展示最终漂亮版本。',
      problemSolved: '回答“这次评审导致了什么材料变化”。',
      input: 'review_id、artifact_ref、revision_action、status。',
      output: 'change_log 或纪要末尾的变更记录。',
      systemPosition: '作为 W12D5 到 W12D6 的交接证据。',
      process: ['记录原始反馈。', '记录采用或拒绝原因。', '记录修改位置和版本。'],
      owner: '产品经理维护追加式历史。',
      notResponsibleFor: '变更记录不能删除旧证据，也不能证明最终答辩通过。',
      compareWith: '覆盖原文会丢失证据；追加式记录保留评审和修订链。',
      evidence: ['review-notes.md。', '被引用 artifact 的修订说明。'],
      failureModes: ['覆盖旧版本。', '只写“已改”没有原因。'],
      pmUse: '让 W12D6 能讲出作品集如何被审阅和改进。',
      correctExample: 'change_log=R-001 根据数据/安全追问修订 evidence_limit，状态 pending_owner_confirmation。',
      incorrectExample: 'change_log=全部改好了，作品集完成。',
    },
  ],
  diagram: {
    title: '跨职能评审的修订链',
    caption: '从评审角色提出问题，到证据回答、缺口反馈、有限决策、修订动作、owner 确认和追加式变更记录。',
    nodes: [
      { id: 'role', label: '评审角色', description: '确定责任视角。', input: 'stakeholder / owner', output: 'review_role', owner: '产品经理', evidence: '角色清单' },
      { id: 'question', label: '角色化追问', description: '提出可回答问题。', input: 'risk_register', output: 'question', owner: '评审角色', evidence: '问题记录' },
      { id: 'answer', label: '证据回答', description: '引用已有成果回答。', input: 'W12D1-W12D4', output: 'answer_summary', owner: '产品经理', evidence: 'artifact_ref' },
      { id: 'gap', label: '缺口反馈', description: '留下未证明事项。', input: 'answer_summary', output: 'gap_or_risk', owner: '产品经理', evidence: 'evidence_limit' },
      { id: 'decision', label: '有限决策', description: 'continue/revise/block/escalate。', input: 'gap_or_risk', output: 'decision', owner: '产品经理', evidence: '决策依据' },
      { id: 'revision', label: '修订闭环', description: '动作、owner、状态和变更记录。', input: 'decision', output: 'revision_action / owner / change_log', owner: '修订 owner', evidence: 'review-notes.md' },
    ],
    branches: [
      { from: 'role', to: 'question', label: '视角变成追问', kind: 'normal' },
      { from: 'question', to: 'answer', label: '追问用证据回答', kind: 'normal' },
      { from: 'answer', to: 'gap', label: '有限回答留下缺口', kind: 'normal' },
      { from: 'gap', to: 'decision', label: '缺口驱动决策', kind: 'normal' },
      { from: 'decision', to: 'revision', label: '决策落到修订', kind: 'normal' },
      { from: 'question', to: 'revision', label: '无证据直接承诺会越界', kind: 'failure' },
    ],
    evidenceNotes: ['所有评审路径均为教学模拟，必须显式标注。', '评审纪要能证明反馈和修订链完整，不能证明真实跨职能批准、owner 承诺或答辩通过。', 'W12D6 才装配最终作品集和答辩叙事。'],
  },
  demonstration: {
    title: '教师示范：把数据/安全追问写成修订纪要',
    businessProblem: 'W12D4 风险 R-001 写明真实客服工单权限和样本代表性待评审。数据/安全角色追问：字段脱敏范围和访问 owner 是否明确？',
    finalConclusion: '这条评审可以形成 decision=revise：补充 risk-register.csv 的 evidence_limit 与 owner 待确认状态，并在 W12D6 装配前保留变更记录；但不能证明真实数据/安全已经批准。',
    conclusionLimit: '示范只证明 review-notes.md 字段和修订链质量，不能提前完成 W12D6 最终作品集、真实跨职能承诺或答辩通过。',
    steps: [
      { title: '标注评审角色', action: '记录 review_role=数据/安全。', reason: '先明确问题来自哪个责任视角。', evidence: 'review_role 字段。', proves: '能证明追问不是泛泛意见。', limitation: '不能证明真实数据/安全已参会。' },
      { title: '写角色化追问', action: '写“真实工单字段是否已有脱敏范围和访问 owner？”', reason: '问题必须可由证据回答。', evidence: 'question 字段。', proves: '能证明评审目标清楚。', limitation: '不能证明问题已经被真实角色认可。' },
      { title: '引用证据回答', action: '引用 W12D3 VAL-001 与 W12D4 R-001。', reason: '回答必须能回到现有材料。', evidence: 'evidence_cited 与 answer_summary。', proves: '能证明已有证据回答到哪一步。', limitation: '不能证明真实工单权限存在。' },
      { title: '写清缺口反馈', action: '写 gap_or_risk=真实脱敏范围和 owner 仍未确认。', reason: '缺口决定后续修订。', evidence: 'gap_or_risk 字段里的缺口反馈。', proves: '能证明证据边界被保留。', limitation: '不能证明项目一定失败或不可交付。' },
      { title: '形成有限决策', action: '写 decision=revise，而不是 approved_final。', reason: '需要修订材料，但没有真实批准证据。', evidence: 'decision 字段。', proves: '能证明下一步判断克制。', limitation: '不能证明跨职能评审通过。' },
      { title: '落到修订动作', action: '写 revision_action、owner、due_date、status 和 change_log。', reason: '评审必须进入修订闭环。', evidence: 'review-notes.md。', proves: '能证明反馈可追踪。', limitation: '不能证明 owner 已正式承诺。' },
    ],
  },
  guidedLab: {
    title: '评审纪要六路径观察器',
    goal: '用本地教学模拟观察六种评审纪要质量路径：角色缺失、问题过宽、证据缺失、决策缺失、修订 owner 缺失和合格评审纪要。',
    safety: '教学模拟；不读取真实公司数据、不调用外部服务、不证明真实评审、owner 承诺、审批通过、答辩通过或 W12D6 终稿交付。',
    conceptIds: [...conceptIds],
    predictionPrompt: '先预测：一份评审纪要最容易在哪个字段把“有人提了意见”写成无法执行的记录？',
    steps: [
      { title: '观察角色缺失', action: '选择 role-missing，记录为什么问题没有责任视角。', observe: 'review_role 为空。', explanation: '没有角色就无法判断追问代表哪个职能责任。', proves: '能证明 review_role 不完整。', cannotProve: '不能证明真实会议无人负责。' },
      { title: '观察问题过宽', action: '选择 question-vague，改写为可回答问题。', observe: 'question=这个项目行不行。', explanation: '角色化追问必须能被证据回答。', proves: '能证明 question 需要重写。', cannotProve: '不能证明项目不可行。' },
      { title: '观察证据缺失', action: '选择 evidence-missing，补 artifact_ref 和回答强度。', observe: '没有 evidence_cited。', explanation: '没有证据引用，纪要无法支撑修订。', proves: '能证明 evidence_cited 不完整。', cannotProve: '不能证明材料完全无效。' },
      { title: '观察决策缺失', action: '选择 decision-missing，补 continue/revise/block/escalate。', observe: '有反馈但没有 decision。', explanation: '没有有限决策，修订动作没有依据。', proves: '能证明 decision 不完整。', cannotProve: '不能证明真实评审已失败。' },
      { title: '观察修订 owner 缺失', action: '选择 revision-owner-missing，补修订动作、owner 和 due_date。', observe: '只有意见，没有跟进人。', explanation: '评审反馈必须落到可执行修订闭环。', proves: '能证明 owner/status 不完整。', cannotProve: '不能证明 owner 已承诺。' },
      { title: '观察合格评审纪要', action: '选择 qualified-review-notes，记录为什么只能进入 W12D6 装配。', observe: '角色、问题、证据、缺口、决策、修订、owner 和边界齐全。', explanation: '合格纪要可作为 W12D6 材料，但不是最终作品集。', proves: '能证明本地教学模拟中的评审纪要合同质量。', cannotProve: '不能证明真实跨职能批准、答辩通过或作品集完成。' },
    ],
    recordPrompts: ['记录当前路径最先失败的评审纪要字段。', '写出这条路径能证明什么。', '写出这条路径不能证明什么。', '写一句进入 W12D6 前仍需装配或确认的点。'],
    comparePrompt: '比较六条路径：哪一类是角色不可追溯，哪一类是证据不足，哪一类是修订闭环不可执行？',
    passCriteria: ['六条教学模拟路径都运行并记录。', '每条记录都写出能证明与不能证明。', '没有把教学模拟写成真实评审批准或 owner 承诺。', '合格路径只进入 W12D6 装配和答辩准备，不声称作品集完成。'],
  },
  independentLab: {
    title: '独立变式：记录研发和运营对风险登记册的追问',
    scenario: '假设研发追问真实知识库权限是否影响接入范围，运营追问 fallback 后用户体验是否可接受；现有证据来自 W12D2 系统方案、W12D3 验证日志和 W12D4 风险登记。',
    conceptIds: [...conceptIds],
    changedConditions: ['评审角色从数据/安全换成研发', '追问对象从权限脱敏换成 fallback 用户体验', '决策从 revise 换成 escalate 或 continue_with_limit'],
    task: '写一条 review-notes.md 评审纪要，记录角色、问题、证据回答、缺口、有限决策、修订动作、owner、截止时间、状态和证据边界。',
    predictionPrompt: '先预测：这条评审最容易缺 evidence_cited、decision 还是 revision_action？',
    evidenceRequirements: ['明确 artifact_ref 来自 W12D1–W12D4 的教学成果。', '写清不能证明真实评审批准、owner 承诺或 W12D6 作品集完成。'],
    passCriteria: ['review_role 是具体职能。', 'question 能被证据部分回答。', 'decision 是 continue、revise、block 或 escalate 等有限状态。', 'revision_action、owner、due_date 和 status 可追踪。'],
    remediation: { label: '回到角色化追问与修订动作', sectionId: 'concepts', anchor: '#concept-portfolio-review-role' },
  },
  exercises: [
    exercise('w12d5-role-question', ['概念与边界', '工作场景'], ['portfolio-review-role', 'portfolio-review-question'], '哪一句最适合作为 W12D5 的评审问题？', ['数据/安全问：真实工单字段是否已有脱敏范围和访问 owner？', '有人觉得这个项目应该挺好', 'W12D6 答辩已经通过'], 0, '评审问题必须有具体角色和可回答对象。', '回看评审角色与追问'),
    exercise('w12d5-evidence-gap', ['证据判断'], ['portfolio-review-evidence-response', 'portfolio-review-gap'], '哪组更像证据回答和缺口反馈？', ['引用 W12D4 R-001；现有教学样本可说明结构，但真实权限 owner 未确认', '回答：已经讲过了，没问题', '因为感觉靠谱，所以无需补材料'], 0, '证据回答要引用成果，缺口要写明现有证据未覆盖什么。', '回看证据回答与缺口'),
    exercise('w12d5-decision-action', ['机制推演'], ['portfolio-review-decision', 'portfolio-review-revision-action'], '评审后发现真实权限 owner 未确认，哪条处理最克制？', ['decision=revise；在 risk-register.csv 和 review-notes.md 补 owner 待确认与 evidence_limit', 'decision=approved_final；全部通过', '直接删除这条风险'], 0, '有限决策应落到修订动作，不删除证据，也不伪造批准。', '回看有限决策与修订动作'),
    exercise('w12d5-owner-log', ['综合变式'], ['portfolio-review-owner-confirmation', 'portfolio-review-change-log'], '哪条最适合作为 W12D5 到 W12D6 的交接？', ['owner=产品经理临时跟进，status=pending_owner_confirmation，change_log 记录修订位置', 'owner=大家，status=done，作品集完成', '没有 owner，W12D6 再说'], 0, 'W12D5 需要追加式变更记录和责任状态，不能提前声称作品集完成。', '回看 owner 与变更记录'),
  ],
  deliverable: {
    title: '评审纪要',
    conceptIds: [...conceptIds],
    purpose: '用 `review-notes.md` 把 W12D4 风险登记册带入跨职能教学模拟评审，记录角色追问、证据回答、缺口、决策、修订动作、owner 和变更记录。',
    whenToUse: '在 W12D6 装配最终作品集前，用来证明材料经历了评审反馈与修订链。',
    audience: '导师、评审者、未来面试官，以及需要理解作品集如何被修订的跨职能角色。',
    fields: [
      { name: 'review_id', meaning: '评审纪要条目的唯一编号。', source: '评审纪要字段' },
      { name: 'artifact_ref', meaning: '引用被评审的 W12D1–W12D4 成果或 risk_id。', source: '作品集材料引用' },
      { name: 'review_role', meaning: '提出追问的角色或职能视角。', source: '评审角色概念' },
      { name: 'question', meaning: '该角色提出的可回答追问。', source: '角色化追问概念' },
      { name: 'evidence_cited', meaning: '回答问题引用的成果、字段或风险条目。', source: '证据回答概念' },
      { name: 'answer_summary', meaning: '当前证据能回答到哪一步。', source: '证据回答概念' },
      { name: 'gap_or_risk', meaning: '仍未被证据覆盖的缺口或风险。', source: '缺口反馈概念' },
      { name: 'decision', meaning: 'continue、revise、block、escalate 等有限决策。', source: '有限评审决策' },
      { name: 'revision_action', meaning: '要修订的文件、字段和动作。', source: '修订动作概念' },
      { name: 'owner', meaning: '临时负责人或待确认负责人。', source: 'owner 确认概念' },
      { name: 'due_date', meaning: '修订或确认的目标日期。', source: 'owner 跟进节奏' },
      { name: 'status', meaning: 'draft、pending_owner_confirmation、revising、ready_for_w12d6 等。', source: '评审状态字段' },
      { name: 'evidence_limit', meaning: '本评审纪要能证明和不能证明什么。', source: '证据边界' },
    ],
    badExample: 'review-notes.md\nREV-1,作品集,大家,这个项目行不行,已说明,没问题,无,approved_final,不用改,大家,今天,done,跨职能已批准且作品集完成',
    badReasons: ['没有具体评审角色。', '问题不可由证据回答。', '没有引用 W12D1–W12D4 成果。', '把教学模拟越界写成最终批准和作品集完成。'],
    revisionSteps: ['引用被评审 artifact_ref。', '写 review_role 与 question。', '补 evidence_cited 与 answer_summary。', '写 gap_or_risk。', '形成有限 decision。', '写 revision_action、owner、due_date、status 和 evidence_limit。'],
    goodExample: 'review_id: REV-001\nartifact_ref: W12D4 risk-register.csv R-001；相关 W12D2 system-data-plan.md 数据来源责任\nreview_role: 数据/安全\nquestion: 真实工单字段是否已有脱敏范围和访问 owner？\nevidence_cited: W12D2 system-data-plan.md data_sources + W12D3 VAL-001 cannot_prove + W12D4 R-001 evidence_limit\nanswer_summary: 教学模拟已经说明字段结构和风险管理链，但真实工单权限与样本代表性仍未证明\ngap_or_risk: 真实脱敏范围和访问 owner 未确认，可能影响作品集证据可信度\ndecision: revise\nrevision_action: 在 risk-register.csv R-001 和作品集说明中补充真实权限待确认边界\nowner: 产品经理临时跟进；数据/安全 owner 待确认\ndue_date: 2026-08-27\nstatus: pending_owner_confirmation\nevidence_limit: 教学模拟评审只能证明反馈和修订链完整，不能证明真实跨职能批准、owner 承诺、答辩通过或 W12D6 终稿交付',
    guidedPrompts: ['写 review_id 与 artifact_ref。', '写 review_role。', '写 question。', '写 evidence_cited。', '写 answer_summary 与 gap_or_risk。', '写 decision。', '写 revision_action。', '写 owner / due_date / status / evidence_limit。'],
    blankTemplate: 'review_id:\nartifact_ref:\nreview_role:\nquestion:\nevidence_cited:\nanswer_summary:\ngap_or_risk:\ndecision:\nrevision_action:\nowner:\ndue_date:\nstatus:\nevidence_limit:\n',
    standardTemplate: 'review_id: REV-001\nartifact_ref: [引用 W12D1-W12D4 成果或 risk_id]\nreview_role: [用户/研发/数据安全/运营/导师]\nquestion: [角色化追问]\nevidence_cited: [引用 project-brief.md / system-data-plan.md / validation-log.csv / risk-register.csv]\nanswer_summary: [当前证据能回答到哪一步]\ngap_or_risk: [仍未证明的缺口或风险]\ndecision: [continue/revise/block/escalate]\nrevision_action: [要修订的文件、字段和动作]\nowner: [临时 owner 或待确认 owner]\ndue_date: [目标日期]\nstatus: [draft/pending_owner_confirmation/revising/ready_for_w12d6]\nevidence_limit: [本纪要能证明什么，不能证明什么，必须写明教学模拟边界]',
    checklist: ['artifact_ref 引用了 W12D1–W12D4 的真实课程成果。', 'review_role 是具体职能。', 'question 能被证据部分回答。', 'evidence_cited 指向具体成果或 risk_id。', 'answer_summary 写出当前证据强度。', 'gap_or_risk 写出仍未证明事项。', 'decision 是有限状态，不写 approved_final。', 'revision_action 可执行且指向文件或字段。', 'owner 不是“大家”。', 'due_date 与 status 可跟踪。', 'evidence_limit 写明教学模拟边界和不能证明的真实事实。'],
  },
  memory: {
    conceptIds: [...conceptIds],
    anchors: ['评审必须先区分具体角色。', '问题必须可由已有证据回答。', '回答后要留下缺口和有限决策。', '修订动作、owner 和变更记录形成闭环。'],
    closedBookPrompt: '闭卷解释一条 review-notes.md 如何从评审角色走到问题、证据回答、缺口、决策、修订动作、owner 和变更记录。',
    microOperation: '把“研发觉得接入风险不清楚”改写成 review_role + question + evidence_cited + decision + revision_action。',
    unresolvedPrompt: '写出你当前评审纪要里最需要 W12D6 装配前确认的一项 owner、证据或修订动作。',
    reviewStages: [
      { stage: 'D1', task: '闭卷写出 review-notes.md 的 13 个字段。' },
      { stage: 'D3', task: '把一个泛泛评审意见改写成角色化追问。' },
      { stage: 'D7', task: '给一条追问补 evidence_cited、answer_summary 与 gap_or_risk。' },
      { stage: 'D14', task: '检查一条纪要是否有 decision、revision_action、owner、due_date。' },
      { stage: 'D30', task: '复述 W12D5 与 W12D6 的边界。' },
      { stage: 'D60', task: '用 evidence_limit 解释为什么评审纪要不能证明真实批准或答辩通过。' },
    ],
  },
  nextLesson: {
    id: 'W12D6',
    title: '作品集装配、10 分钟答辩和复盘',
    bridge: '下一课才把 Brief、系统方案、验证日志、风险登记册和评审修订记录装配成最终作品集，并准备答辩与复盘；本课只交付评审纪要和修订链。',
  },
}
