import type { DailyCourse, Exercise } from './types'

const conceptIds = [
  'portfolio-problem-statement',
  'portfolio-target-user',
  'portfolio-stakeholder-outcome',
  'portfolio-evidence-inventory',
  'portfolio-missing-evidence',
  'portfolio-success-metric',
  'portfolio-scope-non-goals',
  'portfolio-brief-decision',
] as const

const prerequisiteConceptIds = [
  'network-evidence-boundary',
  'ai-eval-set-gate',
  'ai-failure-classification-table',
  'ai-risk-decision-table',
  'ai-report-evidence-boundary',
]

function exercise(
  id: string,
  categories: Exercise['categories'],
  conceptIdsForExercise: string[],
  prompt: string,
  options: string[],
  answerIndex: number,
  referenceAnswer: string,
  remediationLabel: string,
): Exercise {
  return {
    id,
    kind: 'single-choice',
    categories,
    conceptIds: conceptIdsForExercise,
    prompt,
    hint: '先看它是否固定用户、问题、证据和边界；不要被“看起来宏大”的表述带走。',
    options: options.map((label, index) => ({
      label,
      rationale: index === answerIndex ? '这项把问题、证据和下一步判断绑定在一起，适合进入项目 Brief。' : '这项要么太泛，要么越过了当前证据，不能作为 W12D1 的可靠 Brief 判断。',
      couldBeTrueWhen: index === answerIndex ? '当引用的证据确实来自已完成教学成果或明确标注缺失时。' : '只有后续补齐真实用户访谈、生产日志、系统方案或验证结果后，才可能重新判断。',
    })),
    answerIndex,
    referenceAnswer,
    reasoning: ['项目 Brief 首先回答“为什么值得做”，不是先画方案。', '所有证据必须可追溯；没有证据的部分要写成 missing_evidence。', 'W12D1 的结论只能决定是否值得进入 D2 方案设计。'],
    rubric: ['用户与问题具体', '证据和缺证据分开', '成功指标可观察', '没有提前交付 D2–D6 文档'],
    commonErrors: [
      { error: '只写愿景口号', reason: '口号不能让评审者判断问题是否真实、重要或可验证。' },
      { error: '把缺失证据写成已证明', reason: '这会污染后续作品集证据链，也让项目看起来不可信。' },
    ],
    remediation: { label: remediationLabel, sectionId: 'concepts', anchor: `#concept-${conceptIdsForExercise[0]}` },
  }
}

export const w12d1: DailyCourse = {
  id: 'W12D1',
  contentVersion: 'w12d1-project-brief-day01-v1',
  week: 12,
  day: 1,
  title: '定义值得解决的问题',
  subtitle: '把前 11 周已有教学成果和明确缺失的证据整理成一份项目 Brief，只判断问题是否值得进入作品集，不提前写系统方案、验证日志、风险登记册或答辩稿。',
  duration: { core: 30, standard: 45, extension: 60, full: 110 },
  coreConceptGroups: [
    {
      id: 'brief-problem-user',
      title: '先锁定问题、用户和影响',
      conceptIds: ['portfolio-problem-statement', 'portfolio-target-user', 'portfolio-stakeholder-outcome'],
      summary: '项目 Brief 的开头必须把谁遇到什么问题、为什么现在值得解决、会影响谁写清楚。',
      boundary: '本组不设计系统架构，也不承诺解决方案已经成立。',
    },
    {
      id: 'brief-evidence-boundary',
      title: '把已有证据和缺失证据分开',
      conceptIds: ['portfolio-evidence-inventory', 'portfolio-missing-evidence'],
      summary: '作品集可信度来自可追溯证据；没有完成的周成果或真实业务材料必须明确写成缺失，不用模板空格伪装。',
      boundary: '教学模拟只能证明学习场景中的理解和操作，不能证明真实生产数据、用户访谈或上线效果。',
    },
    {
      id: 'brief-decision-scope',
      title: '用指标、范围和决定约束下一步',
      conceptIds: ['portfolio-success-metric', 'portfolio-scope-non-goals', 'portfolio-brief-decision'],
      summary: 'Brief 最后要写出可观察成功指标、当前范围、非目标和是否进入 D2 的有限决定。',
      boundary: '本日只交付 `project-brief.md`，不产出系统与数据方案、验证日志、风险登记册、评审纪要或最终作品集。',
    },
  ],
  prerequisiteConceptIds,
  learningPaths: {
    '30': {
      guidedStepIndices: [0, 1, 2, 3, 4, 5],
      guidedRecordIndices: [0, 1, 2],
      exerciseCount: 3,
      deliverablePromptCount: 5,
      deliverableChecklistIndices: [0, 1, 2, 3, 4],
      deliverableMinimumContributionCharacters: 160,
    },
    '45': {
      guidedStepIndices: [0, 1, 2, 3, 4, 5],
      guidedRecordIndices: [0, 1, 2, 3],
      exerciseCount: 4,
      deliverablePromptCount: 8,
      deliverableChecklistIndices: [0, 1, 2, 3, 4, 5, 6, 7],
      deliverableMinimumContributionCharacters: 260,
    },
  },
  primaryGoal: '提交一份 `project-brief.md`：包含项目标题、用户问题、目标用户、利益相关方、已用证据、缺失证据、成功指标、范围、非目标、假设、最大未知、下一步和证据限制。',
  scenario: {
    role: '你是准备整理作品集的产品经理实习生。',
    situation: '前面已经做过请求链、Network 证据和 AI 评测相关教学成果，但 72 天课程尚未全部完成，很多跨周证据并不存在。',
    question: '怎样诚实地定义一个值得解决的问题，让评审者知道项目为什么值得进入后续方案设计，而不是看到一份空模板或夸大的作品集？',
    stakes: 'Brief 写虚会让后续系统方案、验证日志和答辩都失去可信度；证据边界写清楚，反而能显示产品判断成熟。',
  },
  objectives: [
    { id: 'w12d1-objective-problem', text: '写出具体用户问题和受影响角色', evidence: 'Brief 中包含 user_problem、target_user 与 stakeholders。' },
    { id: 'w12d1-objective-evidence', text: '区分已用证据和缺失证据', evidence: 'evidence_used 只引用已完成教学成果；missing_evidence 明确列出缺口。' },
    { id: 'w12d1-objective-metric', text: '给出可观察成功指标和范围边界', evidence: 'Brief 包含 success_metric、scope 与 non_goals。' },
    { id: 'w12d1-objective-decision', text: '形成进入下一步的有限决定', evidence: 'next_step 指向 W12D2 方案设计准备，不提前交付方案。' },
  ],
  prerequisites: [
    {
      id: 'w12d1-evidence-readiness',
      conceptIds: ['network-evidence-boundary'],
      prompt: '你能区分“看到的证据”和“还不能证明的结论”吗？',
      passDescription: '能用 Network 或页面证据写出看到、可以判断、不能判断。',
      remediationLabel: '补学 W1D5：Network 证据边界',
      remediationTarget: '#/lesson/W1D5',
      remediation: { purpose: 'Brief 需要诚实引用证据，不能把观察扩大成生产结论。', steps: ['回看 Network 观察记录字段。', '写一条“看到/不能证明”的例子。'], successCheck: '能把教学模拟证据和真实生产证据分开。' },
    },
    {
      id: 'w12d1-eval-readiness',
      conceptIds: ['ai-eval-set-gate', 'ai-failure-classification-table', 'ai-risk-decision-table', 'ai-report-evidence-boundary'],
      prompt: '你能说明 W11D3–W11D6 的样本、失败、风险和报告分别证明到哪里吗？',
      passDescription: '能说明 AI 评测报告是教学模拟综合报告，不代表真实上线审批。',
      remediationLabel: '补学 W11D3–W11D6：AI 评测证据链',
      remediationTarget: '#/lesson/W11D6',
      remediation: { purpose: 'W12D1 会调用前序真实成果；缺少这条边界会把作品集写成过度宣传。', steps: ['复述最小评测集的 valid 边界。', '复述失败分类和风险建议的证据限制。', '说明综合报告还缺哪些生产证据。'], successCheck: '能写出一个 evidence_used 和一个 missing_evidence。' },
    },
  ],
  concepts: [
    {
      id: 'portfolio-problem-statement', prerequisiteConceptIds: [],
      term: '问题陈述', english: 'Problem Statement',
      definition: '问题陈述是用一句可检查的话说明谁在什么情境下遇到什么阻碍，以及这个阻碍为什么值得现在解决。',
      why: '没有问题陈述，作品集会变成技术堆料；评审者看不出你为什么选择这个项目。',
      problemSolved: '回答“这个项目到底解决哪一个具体问题，而不是展示一堆功能”。',
      input: '目标场景、用户原话或教学观察、当前影响、已知证据和证据缺口。',
      output: '一段包含用户、情境、阻碍、影响和证据来源的 problem statement。',
      systemPosition: '位于作品集所有文档之前，决定 D2–D6 是否值得继续展开。',
      process: ['先写用户和场景。', '再写当前阻碍和影响。', '最后绑定一条已有证据或明确缺失。'],
      owner: '产品经理负责组织，用户、业务或教学成果提供证据输入。',
      notResponsibleFor: '问题陈述不负责画系统方案、证明方案有效或批准上线。',
      compareWith: '需求标题是标签；问题陈述必须解释为什么这个标签值得解决。',
      evidence: ['教学成果记录。', '用户访谈或业务材料。', '明确标注的缺失证据。'],
      failureModes: ['写成“提升体验”这种口号。', '没有用户对象。', '把未来方案当成已经成立的问题证据。'],
      pmUse: '在作品集开头用它限定评审讨论范围，避免一上来争论方案细节。',
      correctExample: '一线客服在退款争议场景中无法快速判断 AI 回答是否有证据边界，导致复盘只能说“模型幻觉”。',
      incorrectExample: '做一个很强的 AI 客服系统，提升业务效率。',
    },
    {
      id: 'portfolio-target-user', prerequisiteConceptIds: ['portfolio-problem-statement'],
      term: '目标用户', english: 'Target User',
      definition: '目标用户是当前 Brief 优先服务和验证的人群，不是所有可能受益的人。',
      why: '用户过宽会让指标、范围和证据都失焦，后续方案也无法判断优先级。',
      problemSolved: '回答“这份作品集首先为谁判断问题和价值”。',
      input: '角色、任务、使用频率、风险承担方式和可访问证据。',
      output: '一个具体目标用户描述和暂不覆盖的人群边界。',
      systemPosition: '位于问题陈述之后，成功指标和范围之前。',
      process: ['选一个最需要解决该问题的角色。', '写出其任务和约束。', '说明暂不覆盖谁。'],
      owner: '产品经理负责聚焦，业务或导师帮助校准是否真实。',
      notResponsibleFor: '目标用户不等于最终商业市场规模，也不证明所有用户都需要该方案。',
      compareWith: '利益相关方会影响评审；目标用户直接经历问题。',
      evidence: ['角色任务描述。', '样本或教学案例中的具体行为。'],
      failureModes: ['把“所有产品经理”都写进去。', '只写公司部门不写实际任务。'],
      pmUse: '用目标用户决定哪些证据进入 Brief，哪些只能放到后续扩展。',
      correctExample: '负责 AI 客服试点评审的产品经理，需要把样本失败转成可分派动作。',
      incorrectExample: '所有互联网用户都会用 AI。',
    },
    {
      id: 'portfolio-stakeholder-outcome', prerequisiteConceptIds: ['portfolio-target-user'],
      term: '利益相关方与影响', english: 'Stakeholder Outcome',
      definition: '利益相关方与影响说明问题解决或不解决会影响哪些角色、协作成本、风险或决策。',
      why: '项目值得做不只因为用户痛，还因为它会改变评审、研发、运营或安全的工作结果。',
      problemSolved: '回答“为什么评审者应该关心这个问题”。',
      input: '目标用户、协作角色、当前摩擦、潜在风险和可观察影响。',
      output: 'stakeholders 列表和 outcome 描述。',
      systemPosition: '连接问题陈述与成功指标，帮助确定项目优先级。',
      process: ['列直接用户。', '列需要接收成果的协作方。', '写出问题造成的影响。'],
      owner: '产品经理负责梳理，跨职能角色在 D5 评审中确认或修正。',
      notResponsibleFor: '不负责替代正式跨职能评审，也不证明影响量级已经统计。',
      compareWith: '目标用户是直接使用者；利益相关方可能只消费结论或承担风险。',
      evidence: ['评测报告受众。', '风险建议中的 owner。', '明确缺失的真实评审反馈。'],
      failureModes: ['只写“老板关注”。', '把所有部门列进去但不写影响。'],
      pmUse: '让 Brief 的问题价值可被研发、安全、运营共同理解。',
      correctExample: '研发需要可复现样本修复，安全需要知道 hard gate，运营需要知道转人工边界。',
      incorrectExample: '所有团队都会受益，所以项目重要。',
    },
    {
      id: 'portfolio-evidence-inventory', prerequisiteConceptIds: ['portfolio-stakeholder-outcome'],
      term: '证据清单', english: 'Evidence Inventory',
      definition: '证据清单是把已经真实完成、可追溯到课程或工作材料的成果列出来，并说明它支持 Brief 中哪一句判断。',
      why: '作品集不是填空模板；每个判断都要知道来自哪份成果、哪次尝试或哪条观察。',
      problemSolved: '回答“这句话凭什么写进 Brief”。',
      input: '已 available 的课程成果、历史 attempt、教学模拟输出、脱敏工作材料和缺失说明。',
      output: 'evidence_used 字段，包含来源、支持的判断和限制。',
      systemPosition: '位于问题价值判断之前，为后续项目叙事提供可追溯依据。',
      process: ['只选择真实存在的成果。', '写它支持哪条判断。', '同步写不能证明什么。'],
      owner: '产品经理维护，证据账本和课程 registry 提供可核验来源。',
      notResponsibleFor: '证据清单不负责把缺失证据补齐，也不把教学模拟升级成生产事实。',
      compareWith: '附件列表只说明文件存在；证据清单说明文件支持哪条判断。',
      evidence: ['W1D5 Network 观察记录。', 'W11D3 样本集。', 'W11D6 综合评测报告。'],
      failureModes: ['引用未完成课程。', '只写文件名不写支持哪条判断。', '把模拟结果写成线上数据。'],
      pmUse: '在作品集评审中快速回答“你怎么知道这个问题存在”。',
      correctExample: 'W11D4 失败分类表支持“复盘需要把幻觉拆成可分派类别”，但不证明线上频率。',
      incorrectExample: '前 11 周都做完了，所以证据充分。',
    },
    {
      id: 'portfolio-missing-evidence', prerequisiteConceptIds: ['portfolio-evidence-inventory'],
      term: '缺失证据', english: 'Missing Evidence',
      definition: '缺失证据是当前还没有、但会影响项目判断可信度的信息，必须明写为未知或后续补证任务。',
      why: '诚实列缺口比假装完整更可靠；后续 D2–D6 的工作也需要从缺口出发安排。',
      problemSolved: '回答“当前 Brief 还不能证明哪些关键事项”。',
      input: '未完成课程、没有真实用户访谈、缺生产日志、缺真实指标或缺跨职能确认。',
      output: 'missing_evidence 和 evidence_limit 字段。',
      systemPosition: '与证据清单并列，防止 Brief 过度承诺。',
      process: ['识别影响判断的未知。', '写明为什么缺。', '给出后续补证方向但不提前完成。'],
      owner: '产品经理负责公开缺口，后续 owner 在 D2–D5 逐步确认。',
      notResponsibleFor: '缺失证据不是失败，也不等于本日必须补齐所有证据。',
      compareWith: '风险是可能发生的坏事；缺失证据是当前不知道的事实。',
      evidence: ['inventory 中尚未 available 的 Day。', '未取得的真实业务材料。'],
      failureModes: ['把缺失写成“待优化”但不说明影响。', '为了好看删掉未知。'],
      pmUse: '用它保护作品集可信度，并为后续验证和评审安排问题清单。',
      correctExample: '缺少真实客服工单分布，因此不能证明教学 20 条样本代表线上分布。',
      incorrectExample: '证据完整，后续只需包装一下。',
    },
    {
      id: 'portfolio-success-metric', prerequisiteConceptIds: ['portfolio-missing-evidence'],
      term: '成功指标', english: 'Success Metric',
      definition: '成功指标是后续能观察项目是否改善问题的具体衡量方式，可以是评审效率、分类准确、复现率或风险阻断率。',
      why: '没有指标，项目只剩“做出来了”；评审者无法判断它是否真的解决了问题。',
      problemSolved: '回答“如果继续做，什么变化算有进展”。',
      input: '用户问题、影响、已有证据、缺失证据和可获得数据。',
      output: 'success_metric 字段，包含观察对象、方向、最低判断标准和证据来源。',
      systemPosition: '连接 Brief 与 D3 验证日志，但 W12D1 不实际运行验证。',
      process: ['选一个与问题直接相关的结果。', '写明如何观察。', '承认证据当前是否缺失。'],
      owner: '产品经理定义，后续数据或研发角色帮助验证可采集性。',
      notResponsibleFor: '成功指标不等于已经达到目标，也不等于完整实验设计。',
      compareWith: '目标是想达到的状态；指标是用来观察状态变化的证据。',
      evidence: ['评测通过率或失败分类一致性。', '评审任务耗时记录。', '当前缺失的真实数据项。'],
      failureModes: ['只写“提升效率”。', '指标和问题无关。', '把没有测过的数写成已达成。'],
      pmUse: '让项目从“想法”变成后续可以验证的判断。',
      correctExample: '复盘时 6 类失败分类的一致率达到 80%，且每行能追溯 evidence_limit。',
      incorrectExample: '让 AI 客服变得更智能。',
    },
    {
      id: 'portfolio-scope-non-goals', prerequisiteConceptIds: ['portfolio-success-metric'],
      term: '范围与非目标', english: 'Scope and Non-goals',
      definition: '范围说明 W12D1 Brief 之后优先处理什么，非目标说明本轮明确不处理什么。',
      why: '没有范围，项目会从问题定义滑向全量系统建设；没有非目标，评审会把缺失证据误读成失败。',
      problemSolved: '回答“本项目第一版做什么、不做什么”。',
      input: '目标用户、成功指标、证据清单、缺失证据和时间约束。',
      output: 'scope 与 non_goals 字段。',
      systemPosition: '位于成功指标之后，限制 D2 方案设计的入口。',
      process: ['写入本轮必须覆盖的场景。', '列出明确排除项。', '说明排除原因。'],
      owner: '产品经理负责取舍，后续跨职能评审可调整。',
      notResponsibleFor: '范围不负责证明排除项不重要，也不替代完整路线图。',
      compareWith: '假设是暂时相信的前提；非目标是当前明确不做的内容。',
      evidence: ['项目时间预算。', '可用证据范围。', '课程完成状态。'],
      failureModes: ['把所有后续文档都写成已完成。', '非目标只写“暂无”。'],
      pmUse: '在评审中阻止范围蔓延，保护第一版可交付质量。',
      correctExample: '本轮只做 AI 客服评测复盘 Brief，不做真实上线审批、不接生产系统。',
      incorrectExample: '第一版同时完成系统、数据、验证、风险、评审和上线。',
    },
    {
      id: 'portfolio-brief-decision', prerequisiteConceptIds: ['portfolio-scope-non-goals'],
      term: 'Brief 决策', english: 'Brief Decision',
      definition: 'Brief 决策是在证据和缺口都公开的前提下，判断项目是否值得进入下一步方案设计，以及下一步要解决哪个最大未知。',
      why: '作品集需要展示产品判断：不是所有想法都值得继续，也不是所有证据不足都要停止。',
      problemSolved: '回答“现在是否进入 W12D2，以及进入前最大未知是什么”。',
      input: '问题陈述、目标用户、影响、证据清单、缺失证据、成功指标和范围。',
      output: 'next_step、largest_unknown 与 evidence_limit。',
      systemPosition: '作为 W12D1 终点，衔接 W12D2，但不替代 W12D2。',
      process: ['汇总支持继续的证据。', '列出最大未知。', '给出进入 D2、暂停或补证的有限决定。'],
      owner: '产品经理提出，导师或跨职能评审后续复核。',
      notResponsibleFor: 'Brief 决策不代表方案已经设计好、验证已经跑完、风险已经关闭或答辩已经通过。',
      compareWith: '上线决策决定发布；Brief 决策只决定是否继续做作品集项目。',
      evidence: ['完整 Brief 字段。', '明确下一步和缺失证据。'],
      failureModes: ['直接写“项目完成”。', '没有最大未知。', '把下一步写成全量上线。'],
      pmUse: '用它把作品集从问题定义带入后续方案，而不是用漂亮文档替代判断。',
      correctExample: '进入 W12D2：先设计系统与数据方案；最大未知是真实客服样本是否覆盖教学失败类型。',
      incorrectExample: 'Brief 通过，整个作品集已经结束，可以开始答辩。',
    },
  ],
  diagram: {
    title: '项目 Brief 的证据链',
    caption: '从用户问题出发，经过证据清单与缺口，形成成功指标、范围和下一步决定。',
    nodes: [
      { id: 'problem', label: '问题陈述', description: '用户、场景和阻碍。', input: '观察与教学成果', output: 'user_problem 字段', owner: '产品经理', evidence: '问题陈述' },
      { id: 'evidence', label: '证据清单', description: '已完成成果与可追溯来源。', input: 'attempt 与 deliverable', output: 'evidence_used 字段', owner: '产品经理', evidence: '证据清单' },
      { id: 'missing', label: '缺失证据', description: '当前还不能证明的事实。', input: '未完成课程或缺业务材料', output: 'missing_evidence 字段', owner: '产品经理', evidence: '缺失证据' },
      { id: 'metric', label: '成功指标', description: '后续观察是否改善问题。', input: '问题和证据边界', output: 'success_metric 字段', owner: '产品经理', evidence: '指标定义' },
      { id: 'decision', label: 'Brief 决策', description: '是否进入下一步以及最大未知。', input: '完整 Brief 字段', output: 'next_step 字段', owner: '产品经理', evidence: '有限决定' },
    ],
    branches: [
      { from: 'problem', to: 'evidence', label: '用证据支撑问题', kind: 'normal' },
      { from: 'evidence', to: 'metric', label: '把证据转成可观察指标', kind: 'normal' },
      { from: 'missing', to: 'decision', label: '缺口约束下一步', kind: 'normal' },
      { from: 'problem', to: 'decision', label: '问题太泛会导致暂停或重写', kind: 'failure' },
      { from: 'evidence', to: 'decision', label: '伪造证据会污染作品集', kind: 'failure' },
    ],
    evidenceNotes: ['教学模拟必须标注为教学模拟。', '未 available 的课程不能被当成已完成证据。', 'Brief 只能证明问题定义质量，不能证明方案有效。'],
  },
  demonstration: {
    title: '教师示范：把 AI 客服复盘混乱改写成项目 Brief',
    businessProblem: '团队已有教学样本、失败分类和综合报告，但作品集开头不能只写“做一个 AI 客服评测系统”。',
    finalConclusion: '这个项目值得进入 W12D2，因为问题具体、已有教学证据能支撑一部分判断，同时最大未知和缺失证据被公开。',
    conclusionLimit: '示范只证明 Brief 字段组织合理，不能证明真实用户需求、生产指标、系统方案、验证结果或答辩通过。',
    steps: [
      { title: '固定目标用户', action: '把“所有使用 AI 的人”改成“负责 AI 客服试点评审的产品经理”。', reason: '只有角色具体，才能判断证据和指标是否匹配。', evidence: 'target_user 字段变得可审阅。', proves: '能证明用户对象更聚焦。', limitation: '不能证明该角色真实规模或预算。' },
      { title: '改写用户问题', action: '写成“复盘失败时无法把错误转成可分派动作”。', reason: '问题要描述阻碍，不直接跳到系统方案。', evidence: 'user_problem 包含场景、阻碍和影响。', proves: '能证明问题陈述可讨论。', limitation: '不能证明这是最高优先级问题。' },
      { title: '引用已有证据', action: '引用 W11D3 样本、W11D4 分类和 W11D6 教学报告。', reason: 'Brief 需要证据支撑，而不是空模板。', evidence: 'evidence_used 每条都有来源和限制。', proves: '能证明教学成果支持问题存在的某些判断。', limitation: '不能证明真实线上分布。' },
      { title: '公开缺失证据', action: '写出缺真实客服工单、真实评审耗时和生产日志。', reason: '缺口决定后续方案和验证重点。', evidence: 'missing_evidence 与 evidence_limit 清楚。', proves: '能证明 Brief 没有伪造完整性。', limitation: '不能替代补证工作。' },
      { title: '定义成功指标', action: '把“提升体验”改成“失败分类一致率和可追溯证据覆盖”。', reason: '指标必须能让后续验证日志判断进展。', evidence: 'success_metric 可观察。', proves: '能证明后续验证方向存在。', limitation: '不能证明指标已经达成。' },
      { title: '给出有限下一步', action: '写“进入 W12D2，先设计系统与数据方案；最大未知是真实样本覆盖”。', reason: 'Brief 决策只决定是否继续，不提前完成后续交付。', evidence: 'next_step 和 largest_unknown。', proves: '能证明项目有合理下一步。', limitation: '不能证明 D2–D6 已完成。' },
    ],
  },
  guidedLab: {
    title: '项目 Brief 六路径观察器',
    goal: '用本地教学模拟观察六种 Brief 质量路径：问题过宽、用户缺失、证据缺失、指标不可测、范围蔓延和合格 Brief。',
    safety: '教学模拟；不读取真实公司数据、不调用外部服务、不证明真实业务价值。',
    conceptIds: [...conceptIds],
    predictionPrompt: '先预测：一份 Brief 最容易在哪个字段越界，为什么？',
    steps: [
      { title: '观察问题过宽', action: '选择 problem-too-broad，记录为什么无法进入方案设计。', observe: '问题没有目标用户和具体阻碍。', explanation: '过宽问题会让范围和指标全部失焦。', proves: '能证明当前 Brief 需要重写问题陈述。', cannotProve: '不能证明真实用户不存在这个需求。' },
      { title: '观察用户缺失', action: '选择 user-missing，补写 target_user。', observe: '利益相关方很多但直接用户不清。', explanation: '没有目标用户，成功指标无法定义。', proves: '能证明 Brief 用户字段不合格。', cannotProve: '不能证明所有利益相关方都不重要。' },
      { title: '观察证据缺失', action: '选择 evidence-missing，拆分 evidence_used 与 missing_evidence。', observe: '声称“已证明”但没有来源。', explanation: '证据缺失应公开写入缺口。', proves: '能证明证据链不完整。', cannotProve: '不能证明项目不值得继续。' },
      { title: '观察指标不可测', action: '选择 metric-not-measurable，把“体验更好”改成可观察指标。', observe: '指标没有对象、方向或采集方式。', explanation: '不可测指标无法支撑后续验证日志。', proves: '能证明指标定义需要修订。', cannotProve: '不能证明方案未来一定无效。' },
      { title: '观察范围蔓延', action: '选择 scope-creep，标出 D2–D6 被提前写成已完成的位置。', observe: 'Brief 同时承诺方案、验证、风险和答辩。', explanation: 'W12D1 只定义问题和 Brief。', proves: '能证明范围越界。', cannotProve: '不能证明这些后续文档不需要做。' },
      { title: '观察合格 Brief', action: '选择 qualified-brief，记录为什么它可以进入下一步。', observe: '字段齐全，证据和缺口分开，下一步有限。', explanation: '合格 Brief 是继续设计的入口，不是作品集完成。', proves: '能证明本地教学模拟中的 Brief 合同质量。', cannotProve: '不能证明真实业务价值、用户需求或最终答辩通过。' },
    ],
    recordPrompts: ['记录最先失败的 Brief 字段。', '写出这一路径能证明什么。', '写出这一路径不能证明什么。', '写一句下一步修订动作。'],
    comparePrompt: '比较六条路径：哪一类是问题定义失败，哪一类是证据边界失败，哪一类是范围控制失败？',
    passCriteria: ['六条教学模拟路径都运行并记录。', '每条记录都写出能证明与不能证明。', '没有把教学模拟写成真实业务证据。', '合格路径只进入 W12D2，不声称作品集完成。'],
  },
  independentLab: {
    title: '独立变式：把内部知识库助手改写成 Brief',
    scenario: '假设你要把“内部知识库助手”作为作品集项目，但目前只有教学模拟和少量课程成果，没有真实内部工单。',
    conceptIds: [...conceptIds],
    changedConditions: ['目标用户从产品经理换成客服主管', '证据从 AI 评测报告换成 Network 观察记录', '最大未知从样本覆盖换成真实使用频率'],
    task: '写出问题、证据、缺失证据、成功指标、范围、非目标和下一步，不提前写系统方案。',
    predictionPrompt: '先预测：这个变式最大的证据缺口是什么？',
    evidenceRequirements: ['至少引用一条已完成教学成果或明确写出缺失证据。', '明确说明教学模拟不能证明真实业务价值、方案有效或作品集完成。'],
    passCriteria: ['目标用户具体到角色和任务。', 'evidence_used 与 missing_evidence 清楚分开。', 'success_metric 包含可观察对象、方向和标准。', 'next_step 不提前完成 W12D2–W12D6。'],
    remediation: { label: '回到证据清单和缺失证据', sectionId: 'concepts', anchor: '#concept-portfolio-evidence-inventory' },
  },
  exercises: [
    exercise('w12d1-problem', ['概念与边界', '工作场景'], ['portfolio-problem-statement', 'portfolio-target-user'], '哪句话最适合进入项目 Brief 的 user_problem？', ['做一个领先的 AI 平台', '负责 AI 客服试点评审的产品经理无法把失败样本转成可分派修复动作', '把所有客服工作自动化'], 1, '合格问题必须包含具体用户、场景、阻碍和影响。', '回看问题陈述'),
    exercise('w12d1-evidence', ['证据判断'], ['portfolio-evidence-inventory', 'portfolio-missing-evidence'], 'W11D6 是教学模拟综合报告。写进 Brief 时最稳妥的方式是什么？', ['写成已经证明真实生产表现', '作为教学评测证据引用，并同步写出缺真实日志和线上分布', '完全删除所有证据'], 1, '教学模拟可以支持学习作品集叙事，但必须公开不能证明生产事实。', '回看证据清单'),
    exercise('w12d1-metric', ['机制推演'], ['portfolio-success-metric', 'portfolio-scope-non-goals'], '哪条 success_metric 更可观察？', ['体验明显更好', '6 类失败分类表中每行都有 case_id、evidence_limit，复盘一致率达到 80%', '大家觉得 AI 更聪明'], 1, '可观察指标要有对象、判断方式和方向。', '回看成功指标'),
    exercise('w12d1-decision', ['综合变式'], ['portfolio-brief-decision', 'portfolio-scope-non-goals'], 'Brief 结尾最不越界的 next_step 是什么？', ['进入 W12D2，先设计系统与数据方案，并验证最大未知是否可采集', '整个作品集已经结束，准备答辩', '真实上线已批准'], 0, 'W12D1 只能决定进入下一步方案设计，不能提前完成后续交付。', '回看 Brief 决策'),
  ],
  deliverable: {
    title: '项目 Brief',
    conceptIds: [...conceptIds],
    purpose: '用 `project-brief.md` 定义一个值得进入作品集后续设计的问题，并诚实记录已有证据、缺失证据和下一步。',
    whenToUse: '在 W12D2 系统与数据方案之前，用来判断项目是否值得继续。',
    audience: '导师、面试官、研发/数据/安全协作方，以及未来的自己。',
    fields: [
      { name: 'project_title', meaning: '项目名称，必须具体到问题场景。', source: '问题陈述' },
      { name: 'user_problem', meaning: '目标用户在具体情境中的阻碍和影响。', source: '问题陈述与目标用户' },
      { name: 'target_user', meaning: '第一优先服务和验证的人群。', source: '目标用户教学' },
      { name: 'stakeholders', meaning: '会消费成果或承担风险的角色。', source: '利益相关方与影响' },
      { name: 'evidence_used', meaning: '已完成且可追溯的教学成果或脱敏材料。', source: '证据清单' },
      { name: 'missing_evidence', meaning: '当前还不能证明但影响判断的信息。', source: '缺失证据' },
      { name: 'success_metric', meaning: '后续可观察的成功判断方式。', source: '成功指标' },
      { name: 'scope', meaning: '本轮会处理的边界。', source: '范围教学' },
      { name: 'non_goals', meaning: '本轮明确不处理的事项。', source: '非目标教学' },
      { name: 'assumptions', meaning: '继续进入 D2 前暂时接受的前提。', source: 'Brief 决策' },
      { name: 'largest_unknown', meaning: '下一步最需要验证的不确定问题。', source: '缺失证据与指标' },
      { name: 'next_step', meaning: '有限下一步，只能指向 W12D2 准备。', source: 'Brief 决策' },
      { name: 'evidence_limit', meaning: '本 Brief 能证明与不能证明的边界。', source: '证据边界' },
    ],
    badExample: '项目：AI 客服平台。目标：提升体验。证据：前面都学过，所以已经证明可行。下一步：做完整作品集并上线。',
    badReasons: ['用户、问题和影响都过泛。', '把教学经历写成已证明生产可行。', '提前承诺 D2–D6 和上线结果。'],
    revisionSteps: ['先把目标用户缩小到一个评审角色。', '把已有证据和缺失证据拆开。', '用可观察指标替代口号。', '把下一步限制为 W12D2 方案准备。'],
    goodExample: '# AI 客服评测复盘项目 Brief\n\n- project_title: AI 客服失败复盘证据链\n- user_problem: 负责试点评审的产品经理无法把 AI 客服失败样本转成可分派修复动作，复盘只停在“模型幻觉”。\n- target_user: AI 客服试点评审产品经理。\n- stakeholders: 研发、运营、安全审核、客服主管。\n- evidence_used: W11D3 教学最小评测集、W11D4 教学失败分类表、W11D6 教学综合评测报告；均为教学模拟证据。\n- missing_evidence: 真实客服工单分布、生产日志、真实评审耗时、正式合规审核。\n- success_metric: 失败样本复盘中 6 类主分类一致率达到 80%，每行都能追溯 evidence_limit。\n- scope: 第一版只处理 AI 客服评测复盘中的失败分类与证据交接。\n- non_goals: 不做真实上线审批，不接生产系统，不生成完整系统与数据方案。\n- assumptions: 教学样本能代表复盘方法练习，但不能代表线上分布。\n- largest_unknown: 真实客服样本是否覆盖教学失败类型。\n- next_step: 进入 W12D2，设计系统与数据方案并标注需要补证的数据来源。\n- evidence_limit: 本 Brief 只能证明问题定义和证据组织质量，不能证明真实业务价值、方案有效或最终作品集已经合格。',
    guidedPrompts: ['写 project_title。', '写 user_problem。', '写 target_user。', '写 stakeholders。', '写 evidence_used。', '写 missing_evidence。', '写 success_metric。', '写 scope / non_goals / assumptions / largest_unknown / next_step / evidence_limit。'],
    blankTemplate: '# project-brief.md\n\n- project_title: \n- user_problem: \n- target_user: \n- stakeholders: \n- evidence_used: \n- missing_evidence: \n- success_metric: \n- scope: \n- non_goals: \n- assumptions: \n- largest_unknown: \n- next_step: \n- evidence_limit: ',
    standardTemplate: '# project-brief.md\n\n- project_title: [具体项目名称]\n- user_problem: [谁在什么场景遇到什么阻碍，造成什么影响]\n- target_user: [第一优先验证对象]\n- stakeholders: [研发/运营/安全/导师等]\n- evidence_used: [只引用已完成成果；教学模拟必须标注]\n- missing_evidence: [真实数据、用户访谈、生产日志、未完成课程等缺口]\n- success_metric: [可观察对象 + 判断方向 + 最低标准]\n- scope: [本轮处理什么]\n- non_goals: [本轮不处理什么，尤其不提前交付 D2-D6]\n- assumptions: [继续进入下一步前暂时接受的前提]\n- largest_unknown: [最大未知]\n- next_step: [进入 W12D2 前要准备什么]\n- evidence_limit: [本 Brief 能证明什么，不能证明什么]',
    checklist: ['问题包含目标用户、场景、阻碍和影响。', 'evidence_used 只引用真实已有成果。', 'missing_evidence 明确写出至少两类缺口。', 'success_metric 可观察。', 'scope 与 non_goals 分开。', 'next_step 只指向 W12D2 准备。', 'evidence_limit 写明教学模拟边界。', '没有声称作品集、方案、验证、风险登记或答辩已完成。'],
  },
  memory: {
    conceptIds: [...conceptIds],
    anchors: ['Brief 先定义值得解决的问题。', '证据和缺失证据必须分开写。', '成功指标要可观察。', 'W12D1 只决定是否进入 W12D2。'],
    closedBookPrompt: '闭卷解释一份项目 Brief 如何从问题、用户、证据、缺口、指标、范围走到有限下一步。',
    microOperation: '把一个“提升体验”的口号改写成 user_problem + success_metric + evidence_limit。',
    unresolvedPrompt: '写出你当前 Brief 最大的未知，以及它应在 W12D2 还是 W12D3 继续处理。',
    reviewStages: [
      { stage: 'D1', task: '闭卷写出 project-brief.md 的 13 个字段。' },
      { stage: 'D3', task: '给一条 evidence_used 补上 evidence_limit。' },
      { stage: 'D7', task: '把一个过宽项目标题改成问题陈述。' },
      { stage: 'D14', task: '检查 success_metric 是否可观察并写出缺失数据。' },
      { stage: 'D30', task: '复述 W12D1 与 W12D2 的边界。' },
      { stage: 'D60', task: '用 Brief 决策解释为什么不能伪造作品集证据。' },
    ],
  },
  nextLesson: {
    id: 'W12D2',
    title: '系统与数据方案',
    bridge: '下一课才把合格 Brief 转成系统与数据方案；本课不提前画方案蓝图。',
  },
}
