import type { DailyCourse, Exercise } from './types'

const conceptIds = [
  'portfolio-artifact-index',
  'portfolio-evidence-thread',
  'portfolio-storyline',
  'portfolio-ten-minute-pitch',
  'portfolio-demo-boundary',
  'portfolio-reviewer-qna',
  'portfolio-retrospective-insight',
  'portfolio-redaction-evidence-limit',
] as const

const prerequisiteConceptIds = [
  'portfolio-problem-statement',
  'portfolio-system-boundary',
  'portfolio-validation-decision',
  'portfolio-risk-owner',
  'portfolio-review-change-log',
]

function exercise(
  id: string,
  categories: Exercise['categories'],
  ids: string[],
  prompt: string,
  options: string[],
  answerIndex: number,
  referenceAnswer: string,
  remediationLabel: string,
): Exercise {
  return {
    id,
    kind: 'single-choice',
    categories,
    conceptIds: ids,
    prompt,
    hint: '先看作品集是否有 artifact 索引，再看证据线、叙事、10 分钟答辩、演示边界、Q&A、复盘和脱敏边界是否连成同一条可审核链。',
    options: options.map((label, index) => ({
      label,
      rationale: index === answerIndex ? '这项把成果、证据、答辩与边界连起来，适合进入最终作品集包。' : '这项要么缺少证据索引，要么把教学模拟写成真实业务结果，或遗漏答辩/脱敏边界。',
      couldBeTrueWhen: index === answerIndex ? '当结论明确只证明课程作品集装配质量，并区分真实证据、教学模拟和缺失证据时。' : '只有补齐真实生产证据、真实评审记录或外部录用/上线结果后，才可能支撑更强结论。',
    })),
    answerIndex,
    referenceAnswer,
    reasoning: ['W12D6 的作品集包回答“我解决了什么问题、用哪些证据支持、怎么答辩、哪些边界不能越过”。', '完整作品集必须引用 W12D1–W12D5 的真实课程成果与追加历史，而不是覆盖旧证据。', 'W12D6 是 12 周核心课程终点，但不证明真实上线、真实业务价值、招聘成功或真实跨职能批准。'],
    rubric: ['artifact 索引完整', '证据线可追溯', '10 分钟答辩可执行', '脱敏与证据边界诚实'],
    commonErrors: [
      { error: '只贴最终漂亮稿', reason: '没有 artifact 索引、修订记录和证据边界，无法证明学习过程。' },
      { error: '答辩稿写成真实上线成功', reason: '课程作品集只能证明课程内证据链质量，不能替代生产数据或招聘结果。' },
    ],
    remediation: { label: remediationLabel, sectionId: 'concepts', anchor: `#concept-${ids[0]}` },
  }
}

export const w12d6: DailyCourse = {
  id: 'W12D6',
  contentVersion: 'w12d6-portfolio-package-day01-v1',
  week: 12,
  day: 6,
  title: '作品集装配、10 分钟答辩和复盘',
  subtitle: '把 W12D1–W12D5 的 Brief、系统方案、验证日志、风险登记册和评审纪要装配成 portfolio-checklist.md：形成成果索引、证据线、10 分钟答辩、演示边界、Q&A、复盘和脱敏说明；本课是 12 周核心课程终点，不伪造 W13D1。',
  duration: { core: 30, standard: 45, extension: 70, full: 126 },
  coreConceptGroups: [
    {
      id: 'index-evidence-story',
      title: '从成果索引到证据叙事',
      conceptIds: ['portfolio-artifact-index', 'portfolio-evidence-thread', 'portfolio-storyline'],
      summary: '先把 W12D1–W12D5 的成果和版本列成索引，再把问题、方案、验证、风险、评审修订串成一条可讲的证据线。',
      boundary: '索引和叙事只能引用已有课程成果；缺失证据必须写成缺口，不能补成虚构生产数据。',
    },
    {
      id: 'pitch-demo-qna',
      title: '把作品集压缩成 10 分钟答辩',
      conceptIds: ['portfolio-ten-minute-pitch', 'portfolio-demo-boundary', 'portfolio-reviewer-qna'],
      summary: '10 分钟答辩只讲关键问题、方案、证据和边界；演示说明必须标注教学模拟，Q&A 预案提前准备证据不足的回答。',
      boundary: '答辩脚本不证明真实评审通过、真实业务价值或招聘结果。',
    },
    {
      id: 'retro-redaction-limit',
      title: '复盘、脱敏和证据边界',
      conceptIds: ['portfolio-retrospective-insight', 'portfolio-redaction-evidence-limit'],
      summary: '最终作品集要写出学到了什么、下次怎么做、哪些内容已脱敏、哪些结论仍然不能证明。',
      boundary: '复盘是学习迁移证据，不是外部业务成功声明。',
    },
  ],
  prerequisiteConceptIds,
  learningPaths: {
    '30': {
      guidedStepIndices: [0, 1, 2, 3, 4, 5],
      guidedRecordIndices: [0, 1, 2],
      exerciseCount: 3,
      deliverablePromptCount: 5,
      deliverableChecklistIndices: [0, 1, 2, 3, 4],
      deliverableMinimumContributionCharacters: 220,
    },
    '45': {
      guidedStepIndices: [0, 1, 2, 3, 4, 5],
      guidedRecordIndices: [0, 1, 2, 3],
      exerciseCount: 4,
      deliverablePromptCount: 8,
      deliverableChecklistIndices: [0, 1, 2, 3, 4, 5, 6, 7],
      deliverableMinimumContributionCharacters: 340,
    },
  },
  primaryGoal: '提交一份 `portfolio-checklist.md`：至少包含 portfolio_id、artifact_index、problem_story、solution_summary、evidence_thread、risk_review_summary、revision_log、ten_minute_pitch、demo_boundary、reviewer_qna、retrospective_insight、redaction_boundary、evidence_limit。',
  scenario: {
    role: '你是要把 12 周学习成果整理成面试作品集的产品经理实习生。',
    situation: 'W12D1–W12D5 已分别产出 Brief、系统与数据方案、验证日志、风险登记册和评审纪要，但它们还分散在多个文件、版本和教学模拟证据里。',
    question: '怎样把这些材料装配成一份能 10 分钟讲清楚、能回答追问、又不夸大证据的完整作品集包？',
    stakes: '没有装配，面试官只能看到碎片；装配越界，又会把教学模拟、缺失证据或未批准事项伪装成真实业务结果。',
  },
  objectives: [
    { id: 'w12d6-objective-index', text: '建立 W12D1–W12D5 artifact 索引和证据线', evidence: '作品集包含 artifact_index 与 evidence_thread。' },
    { id: 'w12d6-objective-pitch', text: '把作品集压缩成可执行的 10 分钟答辩', evidence: '作品集包含 ten_minute_pitch 与 demo_boundary。' },
    { id: 'w12d6-objective-qna-retro', text: '准备评审追问和复盘洞察', evidence: '作品集包含 reviewer_qna 与 retrospective_insight。' },
    { id: 'w12d6-objective-boundary', text: '明确脱敏和证据边界', evidence: '作品集包含 redaction_boundary 与 evidence_limit，且不伪造 W13D1。' },
  ],
  prerequisites: [
    {
      id: 'w12d6-artifact-readiness',
      conceptIds: ['portfolio-problem-statement', 'portfolio-system-boundary', 'portfolio-validation-decision'],
      prompt: '你能列出 W12D1–W12D3 三份核心成果，并说出每份证明什么、不能证明什么吗？',
      passDescription: '能说出 project-brief.md、system-data-plan.md、validation-log.csv 的作用和证据边界。',
      remediationLabel: '补学 W12D1–W12D3：问题、方案与验证证据',
      remediationTarget: '#/lesson/W12D3',
      remediation: { purpose: 'W12D6 不是重新写项目，而是引用已有成果并装配成可讲证据线。', steps: ['列出 W12D1 Brief 的问题与成功指标。', '列出 W12D2 系统边界和数据来源。', '列出 W12D3 验证日志的 cannot_prove。'], successCheck: '能写出一条“问题 → 方案 → 验证”的证据线。' },
    },
    {
      id: 'w12d6-review-readiness',
      conceptIds: ['portfolio-risk-owner', 'portfolio-review-change-log'],
      prompt: '你能从 W12D4–W12D5 中找出风险、修订动作和仍未确认的 owner/证据边界吗？',
      passDescription: '能说出 risk-register.csv 与 review-notes.md 如何进入作品集答辩。',
      remediationLabel: '补学 W12D4–W12D5：风险、评审和修订记录',
      remediationTarget: '#/lesson/W12D5',
      remediation: { purpose: '作品集需要展示接受反馈并修订，而不是只展示终稿。', steps: ['找到一条 risk_id。', '找到一条 review_id。', '说明它们如何改变答辩边界或后续动作。'], successCheck: '能把一条评审修订写入作品集 evidence_thread。' },
    },
  ],
  concepts: [
    {
      id: 'portfolio-artifact-index', prerequisiteConceptIds: ['portfolio-review-change-log'],
      term: '成果索引', english: 'Artifact Index',
      definition: '成果索引是作品集里列出每份材料、版本、来源 Day、用途和当前状态的清单。',
      why: '没有索引，作品集只是几份散落文件；有索引，读者才能知道每份材料如何支撑叙事。',
      problemSolved: '回答“这份作品集由哪些证据构成”。',
      input: 'W12D1–W12D5 的 deliverable、attempt 和修订记录。',
      output: 'artifact_index 字段。',
      systemPosition: '位于作品集开头，作为后续证据线的目录。',
      process: ['列出文件名和来源 Day。', '标注版本或状态。', '写明每份材料支持的论点。'],
      owner: '产品经理维护；真实材料来源需按权限脱敏。',
      notResponsibleFor: '索引不证明材料都已被真实业务方批准。',
      compareWith: '文件夹目录只列文件；成果索引还写用途、版本和证据边界。',
      evidence: ['project-brief.md。', 'system-data-plan.md。', 'validation-log.csv。', 'risk-register.csv。', 'review-notes.md。'],
      failureModes: ['只写“作品集材料”。', '没有版本或来源 Day。'],
      pmUse: '让面试官快速判断作品集证据是否完整、可追踪。',
      correctExample: 'artifact_index=W12D3 validation-log.csv VAL-001，用于证明最大未知的本地验证路径。',
      incorrectExample: 'artifact_index=一些截图和文档。',
    },
    {
      id: 'portfolio-evidence-thread', prerequisiteConceptIds: ['portfolio-artifact-index'],
      term: '证据线', english: 'Evidence Thread',
      definition: '证据线是把问题、方案、验证、风险、评审和修订按因果顺序连接起来的作品集主线。',
      why: '作品集不是材料堆叠，而是证明你如何从问题走到可审查结论。',
      problemSolved: '回答“这些成果之间有什么因果关系”。',
      input: 'artifact_index、Brief、方案、验证日志、风险登记和评审纪要。',
      output: 'evidence_thread 字段。',
      systemPosition: '连接所有成果，是答辩和 Q&A 的主骨架。',
      process: ['从问题和目标用户开始。', '接到系统与数据方案。', '用验证、风险和评审修订限制结论。'],
      owner: '产品经理负责组织并维护证据叙事。',
      notResponsibleFor: '证据线不能把教学模拟升格为生产证据。',
      compareWith: '时间线只讲先后；证据线还讲每步能证明什么、不能证明什么。',
      evidence: ['W12D1–W12D5 成果字段。', '追加式 attempt 与 review task。'],
      failureModes: ['跳过验证直接讲成果。', '风险和评审没有进入主线。'],
      pmUse: '把“我做了文档”变成“我如何用证据推进产品判断”。',
      correctExample: '问题来自 Brief，方案定义边界，验证降低最大未知，风险登记和评审纪要保留不能证明事项。',
      incorrectExample: '先讲背景，再说我做了很多工作。',
    },
    {
      id: 'portfolio-storyline', prerequisiteConceptIds: ['portfolio-evidence-thread'],
      term: '作品集叙事', english: 'Portfolio Storyline',
      definition: '作品集叙事是用一条清楚的产品故事解释用户问题、方案取舍、证据强度和修订过程。',
      why: '面试官通常没有时间读所有原始材料，叙事决定他们能否快速理解你的产品判断。',
      problemSolved: '回答“这份作品集想让读者相信什么”。',
      input: '目标用户、问题、方案、证据线和边界。',
      output: 'problem_story 与 solution_summary。',
      systemPosition: '位于成果索引之后，进入答辩脚本之前。',
      process: ['一句话说问题。', '一句话说方案。', '一句话说证据与限制。'],
      owner: '产品经理负责撰写、复核并保留证据边界。',
      notResponsibleFor: '叙事不能删除不利证据或风险。',
      compareWith: '宣传稿强调亮点；作品集叙事必须保留证据限制。',
      evidence: ['Brief 成功指标。', '方案非目标。', '验证 cannot_prove。'],
      failureModes: ['故事太散，读者看不出主线。', '只讲价值不讲证据，容易变成宣传稿。'],
      pmUse: '在短时间内展示结构化表达和证据意识。',
      correctExample: '为客服知识库检索降低新人工单查询成本；当前只证明本地样本路径，真实权限仍待确认。',
      incorrectExample: '这是一个改变行业的 AI 客服平台。',
    },
    {
      id: 'portfolio-ten-minute-pitch', prerequisiteConceptIds: ['portfolio-storyline'],
      term: '10 分钟答辩结构', english: 'Ten-minute Pitch Structure',
      definition: '10 分钟答辩结构是把作品集压缩成固定时间段：问题、用户、方案、证据、风险、修订、下一步。',
      why: '没有时间结构，答辩容易前面讲太久，关键证据和边界来不及说。',
      problemSolved: '回答“10 分钟内按什么顺序讲”。',
      input: '作品集叙事、证据线、风险和修订记录。',
      output: 'ten_minute_pitch 字段。',
      systemPosition: '把文档装配转成口头答辩。',
      process: ['分配每段分钟数。', '每段只放一个核心论点。', '最后留出边界和下一步。'],
      owner: '产品经理准备；导师或评审者可给反馈。',
      notResponsibleFor: '答辩结构不证明答辩已真实通过。',
      compareWith: '长文目录按阅读组织；10 分钟结构按听众注意力组织。',
      evidence: ['10 分钟答辩脚本。', '计时演练记录和修订痕迹。'],
      failureModes: ['超过 10 分钟。', '没有风险和证据限制。'],
      pmUse: '训练把复杂项目压缩成可评审表达。',
      correctExample: '1 分钟问题、2 分钟方案、3 分钟证据、2 分钟风险评审、1 分钟复盘、1 分钟下一步。',
      incorrectExample: '先把每个文档从头到尾念一遍。',
    },
    {
      id: 'portfolio-demo-boundary', prerequisiteConceptIds: ['portfolio-ten-minute-pitch'],
      term: '演示边界', english: 'Demo Boundary',
      definition: '演示边界是说明答辩中展示的样本、流程、截图或模拟能证明什么、不能证明什么。',
      why: '演示最容易让听众误以为已经接入真实系统或真实数据，所以边界必须紧邻演示出现。',
      problemSolved: '回答“我演示的到底是什么证据”。',
      input: '教学模拟路径、验证日志、脱敏样本和材料截图。',
      output: 'demo_boundary 字段。',
      systemPosition: '位于答辩脚本的演示段，保护证据诚实。',
      process: ['标注教学模拟。', '说明样本来源和脱敏。', '写出不能证明的真实事实。'],
      owner: '产品经理维护；真实演示需数据/安全确认。',
      notResponsibleFor: '演示边界不证明真实环境可用。',
      compareWith: 'Demo 是展示动作；demo_boundary 是证据限制说明。',
      evidence: ['validation-log.csv。', 'review-notes.md evidence_limit。'],
      failureModes: ['把本地样本说成真实生产。', '没有说明脱敏。'],
      pmUse: '避免面试中被追问“这是真数据吗”时失去可信度。',
      correctExample: '演示使用教学模拟样本，只证明字段链路和判断逻辑，不证明真实工单权限。',
      incorrectExample: '演示跑通，所以生产可以上线。',
    },
    {
      id: 'portfolio-reviewer-qna', prerequisiteConceptIds: ['portfolio-demo-boundary'],
      term: '评审追问预案', english: 'Reviewer Q&A Prep',
      definition: '评审追问预案是提前为证据不足、方案取舍、风险 owner、下一步等问题准备有限回答。',
      why: '作品集答辩的质量常在 Q&A 暴露；预案能让你诚实回答不知道和下一步。',
      problemSolved: '回答“被追问时如何引用证据而不过界”。',
      input: 'review-notes.md、risk-register.csv、cannot_prove 和 evidence_limit。',
      output: 'reviewer_qna 字段。',
      systemPosition: '连接答辩脚本与评审现场。',
      process: ['列出高概率追问。', '为每题引用证据。', '写明不能证明和下一步。'],
      owner: '产品经理准备；真实评审者可追加问题。',
      notResponsibleFor: 'Q&A 预案不代表真实评审已通过。',
      compareWith: 'FAQ 常是解释功能；Q&A 预案重点是证据、边界和取舍。',
      evidence: ['W12D5 review-notes.md。', 'W12D4 risk-register.csv。'],
      failureModes: ['所有问题都回答“已解决”。', '没有引用 artifact。'],
      pmUse: '展示你能接受质疑并用证据回答。',
      correctExample: '问：真实权限是否确认？答：没有；当前证据只到教学模拟，下一步需要数据/安全 owner 确认。',
      incorrectExample: '所有追问都回答“没问题”，但不引用任何 artifact 或 evidence_limit。',
    },
    {
      id: 'portfolio-retrospective-insight', prerequisiteConceptIds: ['portfolio-reviewer-qna'],
      term: '复盘洞察', english: 'Retrospective Insight',
      definition: '复盘洞察是总结本作品集过程中最大的判断变化、错误修正和下一次会怎样更早验证。',
      why: '作品集不只是展示结果，也要展示你如何从证据和反馈中改进。',
      problemSolved: '回答“这段学习改变了你的产品判断方式什么”。',
      input: '验证日志、风险登记、评审纪要、复习与重做记录。',
      output: 'retrospective_insight 字段。',
      systemPosition: '位于作品集末尾，作为学习迁移证据。',
      process: ['说出一个原判断。', '说出证据如何改变它。', '说出下次提前做什么。'],
      owner: '学习者本人负责记录判断变化和后续验证动作。',
      notResponsibleFor: '复盘洞察不证明外部业务成功。',
      compareWith: '总结是复述发生了什么；洞察要说判断如何改变。',
      evidence: ['追加式 attempt 历史。', 'review-notes 修订记录。', '六阶段复习任务。'],
      failureModes: ['只写“收获很多”。', '不连接具体证据。'],
      pmUse: '让作品集体现成长性和反思能力。',
      correctExample: '我原以为先做完整方案更重要，验证后发现最大未知应提前用本地夹具降低。',
      incorrectExample: '我学会了很多技术，但没有说明哪条证据改变了判断。',
    },
    {
      id: 'portfolio-redaction-evidence-limit', prerequisiteConceptIds: ['portfolio-retrospective-insight'],
      term: '脱敏与证据边界', english: 'Redaction and Evidence Limit',
      definition: '脱敏与证据边界是说明哪些信息被隐藏、替换或模拟，以及整份作品集不能证明的真实事实。',
      why: '最终作品集最容易被外部传播，必须同时保护隐私和保护结论不被夸大。',
      problemSolved: '回答“这份作品集哪些地方不能被当作真实生产证明”。',
      input: '所有 artifact、演示样本、公司数据边界和教学模拟标签。',
      output: 'redaction_boundary 与 evidence_limit。',
      systemPosition: '作为终稿最后一道诚信门槛。',
      process: ['列出脱敏对象。', '列出教学模拟对象。', '列出不能证明的外部结论。'],
      owner: '产品经理负责初稿；真实公开前需遵守公司政策。',
      notResponsibleFor: '边界说明不等于获得公开授权。',
      compareWith: '脱敏处理保护信息；证据边界保护结论。',
      evidence: ['脱敏对象和替换清单。', 'evidence_limit 字段中的不能证明事项。'],
      failureModes: ['泄露真实数据。', '把课程成果说成真实上线证明。'],
      pmUse: '建立可信、可公开、可复核的作品集底线。',
      correctExample: '所有工单均为教学模拟或脱敏样本；作品集不能证明真实生产稳定性、真实业务价值或录用结果。',
      incorrectExample: '因为不能写公司数据，所以就不写边界。',
    },
  ],
  diagram: {
    title: '最终作品集装配链',
    caption: '从 artifact 索引开始，把问题、方案、验证、风险、评审修订、10 分钟答辩、Q&A、复盘和脱敏边界接成一条证据链。',
    nodes: [
      { id: 'index', label: '成果索引', description: '列出 W12D1–W12D5 成果与版本。', input: 'deliverables / attempts', output: 'artifact_index', owner: '产品经理', evidence: '成果清单' },
      { id: 'thread', label: '证据主线', description: '连接问题、方案、验证、风险和评审。', input: 'artifact_index', output: 'evidence_thread', owner: '产品经理', evidence: '引用链' },
      { id: 'story', label: '作品集叙事', description: '形成听众能理解的产品故事。', input: 'evidence_thread', output: 'problem_story / solution_summary', owner: '产品经理', evidence: '叙事草稿' },
      { id: 'pitch', label: '10 分钟答辩', description: '压缩成可计时表达。', input: 'story', output: 'ten_minute_pitch', owner: '产品经理', evidence: '答辩脚本' },
      { id: 'qna', label: '追问预案', description: '准备有限回答和下一步。', input: 'risk / review notes', output: 'reviewer_qna', owner: '产品经理', evidence: 'Q&A 清单' },
      { id: 'boundary', label: '脱敏与边界', description: '标注教学模拟、脱敏和不能证明。', input: 'all artifacts', output: 'redaction_boundary / evidence_limit', owner: '产品经理', evidence: '边界说明' },
    ],
    branches: [
      { from: 'index', to: 'thread', label: '成果变成证据链', kind: 'normal' },
      { from: 'thread', to: 'story', label: '证据链变成叙事', kind: 'normal' },
      { from: 'story', to: 'pitch', label: '叙事压缩为答辩', kind: 'normal' },
      { from: 'pitch', to: 'qna', label: '答辩准备追问', kind: 'normal' },
      { from: 'qna', to: 'boundary', label: '追问暴露证据边界', kind: 'normal' },
      { from: 'story', to: 'boundary', label: '只讲亮点会越界', kind: 'failure' },
    ],
    evidenceNotes: ['所有演示和模拟必须显式标注“教学模拟”。', '完整作品集能证明课程成果被装配成可答辩材料，不能证明真实上线、真实业务价值、招聘结果或真实跨职能批准。', 'W12D6 是 12 周核心课程终点，不设置 W13D1。'],
  },
  demonstration: {
    title: '教师示范：把五份 W12 成果装配成 10 分钟答辩',
    businessProblem: '你准备展示“客服知识库查询体验优化”作品集。已有 W12D1 Brief、W12D2 系统与数据方案、W12D3 验证日志、W12D4 风险登记册和 W12D5 评审纪要。',
    finalConclusion: '合格装配会形成一份 portfolio-checklist.md：先列 artifact 索引，再讲问题—方案—验证—风险—修订—答辩—复盘，并在最后写清教学模拟、脱敏和不能证明的真实事实。',
    conclusionLimit: '示范只证明课程作品集装配链完整，不能证明真实生产上线、真实业务价值、真实评审批准、真实答辩通过或招聘结果。',
    steps: [
      { title: '建立 artifact 索引', action: '列出 W12D1–W12D5 五份成果、版本和用途。', reason: '先让读者知道证据来自哪里。', evidence: 'artifact_index 字段。', proves: '能证明作品集材料可追踪。', limitation: '不能证明每份材料已被真实业务批准。' },
      { title: '串联证据主线', action: '把 Brief、方案、验证、风险和评审修订按因果顺序连接。', reason: '作品集需要证明产品判断过程。', evidence: 'evidence_thread 字段。', proves: '能证明材料之间有逻辑关系。', limitation: '不能证明真实生产效果。' },
      { title: '写 10 分钟答辩', action: '为问题、方案、证据、风险、复盘和下一步分配时间。', reason: '答辩需要可执行时间结构。', evidence: 'ten_minute_pitch 字段。', proves: '能证明表达准备充分。', limitation: '不能证明答辩已真实通过。' },
      { title: '标注演示边界', action: '写明演示使用教学模拟或脱敏样本。', reason: '避免把本地样本说成生产证据。', evidence: 'demo_boundary 字段。', proves: '能证明演示证据边界清楚。', limitation: '不能证明真实系统可用。' },
      { title: '准备追问预案', action: '为真实权限、样本代表性、风险 owner 和下一步准备有限回答。', reason: 'Q&A 是作品集可信度测试。', evidence: 'reviewer_qna 字段。', proves: '能证明你能用证据回答质疑。', limitation: '不能证明真实评审者已经接受回答。' },
      { title: '完成复盘和脱敏', action: '写 retrospective_insight、redaction_boundary 和 evidence_limit。', reason: '终稿必须保护信息和结论边界。', evidence: 'portfolio-checklist.md。', proves: '能证明学习迁移与边界意识。', limitation: '不能证明录用、上线或真实业务价值。' },
    ],
  },
  guidedLab: {
    title: '作品集装配六路径观察器',
    goal: '用本地教学模拟观察六种最终作品集质量路径：成果缺失、证据线断裂、答辩超时、演示边界缺失、追问无准备和合格作品集包。',
    safety: '教学模拟；不读取真实公司数据、不调用外部服务、不证明真实上线、真实业务价值、真实答辩通过、招聘结果或真实跨职能批准。',
    conceptIds: [...conceptIds],
    predictionPrompt: '先预测：最终作品集最容易在哪个环节把“课程材料”误写成“真实业务成功”？',
    steps: [
      { title: '观察成果缺失', action: '选择 artifact-missing，记录缺少哪份 W12 成果。', observe: 'artifact_index 未覆盖 W12D1–W12D5。', explanation: '缺成果索引会让证据线不可追踪。', proves: '能证明 artifact_index 不完整。', cannotProve: '不能证明该成果在真实项目中不存在。' },
      { title: '观察证据线断裂', action: '选择 evidence-thread-broken，补问题—方案—验证—风险—评审链。', observe: 'evidence_thread 跳过验证或风险。', explanation: '作品集必须展示判断如何被证据约束。', proves: '能证明证据叙事断裂。', cannotProve: '不能证明项目没有价值。' },
      { title: '观察答辩超时', action: '选择 pitch-too-long，把脚本压缩到 10 分钟。', observe: 'ten_minute_pitch 超过 10 分钟且没有边界段。', explanation: '答辩结构要为证据边界留时间。', proves: '能证明答辩结构不可执行。', cannotProve: '不能证明表达能力永远不足。' },
      { title: '观察演示边界缺失', action: '选择 demo-boundary-missing，补教学模拟和脱敏说明。', observe: 'demo_boundary 为空。', explanation: '演示必须说明能/不能证明什么。', proves: '能证明演示边界不完整。', cannotProve: '不能证明真实系统已上线。' },
      { title: '观察追问无准备', action: '选择 qna-unprepared，补高概率追问和有限回答。', observe: 'reviewer_qna 没有 evidence_limit。', explanation: '追问回答必须引用 artifact 并保留缺口。', proves: '能证明 Q&A 预案不完整。', cannotProve: '不能证明真实评审失败。' },
      { title: '观察合格作品集包', action: '选择 qualified-portfolio-package，记录为什么它是课程终点而不是生产证明。', observe: '13 字段齐全，教学模拟、脱敏和不能证明均可见。', explanation: '合格作品集可用于课程收口和面试准备，但不等于外部业务成功。', proves: '能证明课程作品集装配合同质量。', cannotProve: '不能证明真实上线、真实业务价值、真实答辩通过或招聘结果。' },
    ],
    recordPrompts: ['记录当前路径最先失败的作品集字段。', '写出这条路径能证明什么。', '写出这条路径不能证明什么。', '写一句 12 周核心课程终点后的真实下一步。'],
    comparePrompt: '比较六条路径：哪一类是材料缺失，哪一类是叙事/答辩不可执行，哪一类是证据边界缺失？',
    passCriteria: ['六条教学模拟路径都运行并记录。', '每条记录都写出能证明与不能证明。', '没有把课程作品集写成真实上线、真实业务价值或招聘结果。', '合格路径明确 W12D6 是核心课程终点，不伪造 W13D1。'],
  },
  independentLab: {
    title: '独立变式：把作品集改成面试答辩版本',
    scenario: '假设面试官只给你 10 分钟，你需要展示客服知识库项目的证据线、风险和复盘，并准备回答“这是真实生产数据吗？”和“为什么还值得做？”',
    conceptIds: [...conceptIds],
    changedConditions: ['受众从导师换成面试官', '演示材料从完整文档换成 3 张关键页', '追问重点从字段质量换成真实证据边界'],
    task: '写一段 portfolio-checklist.md 的答辩版本，包含 artifact 索引、证据线、10 分钟结构、演示边界、Q&A、复盘、脱敏和 evidence_limit。',
    predictionPrompt: '先预测：这版答辩最容易漏 artifact_index、demo_boundary 还是 reviewer_qna？',
    evidenceRequirements: ['明确引用 W12D1–W12D5 的课程成果。', '写清不能证明真实上线、真实业务价值、真实答辩通过、招聘结果或真实跨职能批准。'],
    passCriteria: ['artifact_index 覆盖 W12D1–W12D5。', 'ten_minute_pitch 有时间结构。', 'demo_boundary 标注教学模拟和脱敏。', 'reviewer_qna 与 evidence_limit 能回答证据不足。'],
    remediation: { label: '回到成果索引与证据线', sectionId: 'concepts', anchor: '#concept-portfolio-artifact-index' },
  },
  exercises: [
    exercise('w12d6-artifact-index', ['概念与边界', '工作场景'], ['portfolio-artifact-index', 'portfolio-evidence-thread'], '哪一句最适合作为 W12D6 的 artifact_index？', ['列出 W12D1 Brief、W12D2 方案、W12D3 验证日志、W12D4 风险登记、W12D5 评审纪要及用途', '作品集材料很多，略', '真实项目已上线并产生业务价值'], 0, '成果索引必须列出来源、用途和边界，不能把课程材料写成上线证明。', '回看成果索引与证据线'),
    exercise('w12d6-pitch', ['机制推演'], ['portfolio-storyline', 'portfolio-ten-minute-pitch'], '哪条 10 分钟答辩结构最稳妥？', ['1 分钟问题、2 分钟方案、3 分钟证据、2 分钟风险评审、1 分钟复盘、1 分钟下一步', '10 分钟都讲背景和愿景', '直接展示最终结论并说全部通过'], 0, '答辩必须留时间讲证据、风险、复盘和边界。', '回看 10 分钟答辩结构'),
    exercise('w12d6-demo-boundary', ['证据判断'], ['portfolio-demo-boundary', 'portfolio-redaction-evidence-limit'], '演示使用教学样本时，哪条边界最诚实？', ['本演示只证明字段链路和判断逻辑，不能证明真实工单权限、生产稳定性或业务价值', '演示跑通，所以生产可上线', '因为是作品集，所以不用说明数据来源'], 0, '演示边界要紧邻演示出现，说明能/不能证明什么。', '回看演示边界与脱敏'),
    exercise('w12d6-qna-retro', ['综合变式'], ['portfolio-reviewer-qna', 'portfolio-retrospective-insight'], '面试官问“这个项目最大的不足是什么”，哪条回答最好？', ['真实权限和样本代表性仍未证明；我用风险登记和评审纪要保留了缺口，下一步先确认数据 owner', '没有不足，已经完成', '这个问题 W13D1 再说'], 0, 'Q&A 应引用风险和评审记录，复盘下一步，不能伪造 W13D1。', '回看追问预案与复盘洞察'),
  ],
  deliverable: {
    title: '完整作品集包',
    conceptIds: [...conceptIds],
    purpose: '用 `portfolio-checklist.md` 把 W12D1–W12D5 成果装配为可 10 分钟答辩的最终课程作品集，并写清教学模拟、脱敏和证据边界。',
    whenToUse: '在课程收口、导师复核或面试准备时，用来快速展示问题、方案、证据、风险、评审修订、答辩和复盘。',
    audience: '导师、评审者、未来面试官，以及需要判断作品集证据链是否可信的人。',
    fields: [
      { name: 'portfolio_id', meaning: '作品集包唯一编号。', source: '作品集元信息' },
      { name: 'artifact_index', meaning: 'W12D1–W12D5 成果、版本、用途和状态索引。', source: '成果索引概念' },
      { name: 'problem_story', meaning: '目标用户、问题和为什么值得解决。', source: '作品集叙事概念' },
      { name: 'solution_summary', meaning: '系统与数据方案的核心取舍。', source: '方案装配' },
      { name: 'evidence_thread', meaning: '问题、方案、验证、风险、评审和修订的证据线。', source: '证据线概念' },
      { name: 'risk_review_summary', meaning: '风险登记与评审纪要如何限制结论。', source: '风险/评审成果' },
      { name: 'revision_log', meaning: '收到反馈后的修订记录和当前状态。', source: '变更记录' },
      { name: 'ten_minute_pitch', meaning: '10 分钟答辩时间结构和关键话术。', source: '答辩结构概念' },
      { name: 'demo_boundary', meaning: '演示、样本、截图或模拟能/不能证明什么。', source: '演示边界概念' },
      { name: 'reviewer_qna', meaning: '高概率追问、证据回答、缺口和下一步。', source: '追问预案概念' },
      { name: 'retrospective_insight', meaning: '最大判断变化、错误修正和下次提前验证动作。', source: '复盘洞察概念' },
      { name: 'redaction_boundary', meaning: '脱敏、替换、隐藏和公开限制。', source: '脱敏边界' },
      { name: 'evidence_limit', meaning: '整份作品集能证明和不能证明什么。', source: '证据边界' },
    ],
    badExample: 'portfolio-checklist.md\n作品集：客服 AI 项目\n材料：都在文件夹里\n答辩：讲一下项目很好\n结果：已经上线成功，业务价值已证明，评审已通过，后续 W13D1 继续优化',
    badReasons: ['没有 artifact_index。', '没有证据线和答辩时间结构。', '没有演示边界、Q&A、复盘和脱敏。', '把课程作品集越界写成真实上线、业务价值和 W13D1。'],
    revisionSteps: ['列出 portfolio_id 与 artifact_index。', '写 problem_story 与 solution_summary。', '串 evidence_thread。', '写 risk_review_summary 与 revision_log。', '写 ten_minute_pitch 与 demo_boundary。', '写 reviewer_qna 与 retrospective_insight。', '补 redaction_boundary 与 evidence_limit。'],
    goodExample: 'portfolio_id: PORT-W12-001\nartifact_index: W12D1 project-brief.md 定义用户问题；W12D2 system-data-plan.md 定义系统与数据边界；W12D3 validation-log.csv 记录本地教学模拟验证；W12D4 risk-register.csv 记录权限与样本代表性风险；W12D5 review-notes.md 记录评审追问和修订动作\nproblem_story: 客服新人需要更快找到知识库答案，当前目标是降低查询路径不确定性\nsolution_summary: 方案只覆盖知识库检索辅助和人工兜底，不接真实生产工单写入\nevidence_thread: Brief 提出问题和指标；方案定义边界；验证日志降低一个最大未知；风险登记保留真实权限和样本代表性；评审纪要把缺口转成修订动作\nrisk_review_summary: R-001 与 REV-001 指出真实工单权限、脱敏范围和 owner 仍待确认\nrevision_log: 根据 W12D5 评审在作品集说明中补充 demo_boundary 与 evidence_limit，status=ready_for_course_review\nten_minute_pitch: 1 分钟问题；2 分钟方案；3 分钟证据；2 分钟风险和评审修订；1 分钟复盘；1 分钟下一步\ndemo_boundary: 演示为教学模拟和脱敏样本，只证明字段链路和判断逻辑，不能证明真实系统可用\nreviewer_qna: 问真实数据是否接入？答：没有，当前 evidence_limit 保留为数据/安全 owner 待确认\nretrospective_insight: 我原以为终稿越完整越好，后来发现越早写 cannot_prove 和风险 owner，答辩越可信\nredaction_boundary: 不含真实公司数据、Token、生产地址、真实用户信息或未授权截图；样本均为教学模拟或脱敏描述\nevidence_limit: 本作品集能证明 12 周课程成果被装配成可答辩证据链，不能证明真实上线、真实业务价值、真实跨职能批准、真实答辩通过、招聘结果或 W13D1 后续课程',
    guidedPrompts: ['写 portfolio_id 与 artifact_index。', '写 problem_story。', '写 solution_summary。', '写 evidence_thread。', '写 risk_review_summary 与 revision_log。', '写 ten_minute_pitch。', '写 demo_boundary 与 reviewer_qna。', '写 retrospective_insight / redaction_boundary / evidence_limit。'],
    blankTemplate: 'portfolio_id:\nartifact_index:\nproblem_story:\nsolution_summary:\nevidence_thread:\nrisk_review_summary:\nrevision_log:\nten_minute_pitch:\ndemo_boundary:\nreviewer_qna:\nretrospective_insight:\nredaction_boundary:\nevidence_limit:\n',
    standardTemplate: 'portfolio_id: PORT-W12-001\nartifact_index: [列出 W12D1 project-brief.md / W12D2 system-data-plan.md / W12D3 validation-log.csv / W12D4 risk-register.csv / W12D5 review-notes.md]\nproblem_story: [用户、问题、成功指标]\nsolution_summary: [系统与数据方案核心取舍]\nevidence_thread: [问题 → 方案 → 验证 → 风险 → 评审修订]\nrisk_review_summary: [风险和评审如何限制结论]\nrevision_log: [收到反馈后改了什么，当前状态]\nten_minute_pitch: [10 分钟分段脚本]\ndemo_boundary: [演示能证明什么，不能证明什么，必须标注教学模拟]\nreviewer_qna: [高概率追问、证据回答、缺口和下一步]\nretrospective_insight: [判断变化、错误修正、下次提前验证]\nredaction_boundary: [脱敏、隐藏、替换和公开限制]\nevidence_limit: [整份作品集能证明什么，不能证明什么；不得伪造 W13D1]\n',
    checklist: ['artifact_index 覆盖 W12D1–W12D5。', 'problem_story 和 solution_summary 可在 3 分钟内讲清。', 'evidence_thread 包含验证、风险和评审修订。', 'ten_minute_pitch 有明确时间分配。', 'demo_boundary 标注教学模拟和不能证明事项。', 'reviewer_qna 能回答证据不足。', 'retrospective_insight 连接具体证据。', 'redaction_boundary 与 evidence_limit 不含真实敏感信息、不伪造外部结果。'],
  },
  memory: {
    conceptIds: [...conceptIds],
    anchors: ['最终作品集先建 artifact 索引。', '证据线必须包含验证、风险和评审修订。', '10 分钟答辩要为边界和 Q&A 留时间。', '课程终点不等于真实上线、业务价值或招聘结果。'],
    closedBookPrompt: '闭卷解释一份 portfolio-checklist.md 如何从 artifact 索引走到证据线、10 分钟答辩、Q&A、复盘、脱敏和 evidence_limit。',
    microOperation: '把“我的项目已经成功”改写成 problem_story + evidence_thread + evidence_limit 的诚实表述。',
    unresolvedPrompt: '写出课程结束后你最需要真实确认的一项数据、owner、业务指标或公开权限。',
    reviewStages: [
      { stage: 'D1', task: '闭卷写出 portfolio-checklist.md 的 13 个字段。' },
      { stage: 'D3', task: '把五份 W12 成果按 artifact_index 重新排序。' },
      { stage: 'D7', task: '用 10 分钟结构复述作品集，不看稿说出证据边界。' },
      { stage: 'D14', task: '回答三条评审追问，每条引用一个 artifact。' },
      { stage: 'D30', task: '重写 retrospective_insight，说明一个产品判断变化。' },
      { stage: 'D60', task: '用 evidence_limit 解释为什么作品集不能证明真实上线、业务价值或招聘结果。' },
    ],
  },
}
