import type { DailyCourse } from './types'

const objectives: DailyCourse['objectives'] = [
  {
    id: 'read-url-as-address',
    text: '能把一个完整 URL 拆成协议、域名、端口、路径和查询参数，并说明每一部分给浏览器什么线索。',
    evidence: '在实验记录中标注一个课程 URL 的五个部分，并写出缺少某一部分时会发生的可观察变化。',
  },
  {
    id: 'explain-dns-resolution',
    text: '能用“域名 → DNS 查询 → IP 地址 → 服务器入口”的顺序解释浏览器如何找到目标机器。',
    evidence: '按顺序完成关系图说明，并用一次教学模拟的解析结果指出哪一步只说明寻址、哪一步仍未证明业务成功。',
  },
  {
    id: 'separate-location-and-content',
    text: '能区分地址定位与网页内容：知道 URL/DNS 负责找到入口，不负责决定页面最终显示的业务数据。',
    evidence: '针对“域名可解析但页面打不开”和“页面打开但内容错误”各写一条不同排查假设。',
  },
  {
    id: 'record-address-evidence',
    text: '能用产品经理可交接的格式记录一次寻址实验的输入、解析结果、失败点和证据边界。',
    evidence: '提交一份包含域名、解析地址、端口、时间和限制说明的寻址记录，字段齐全且没有把教学模拟写成生产事实。',
  },
]

const prerequisites: DailyCourse['prerequisites'] = [
  {
    id: 'w1d2-browser-webpage',
    conceptIds: ['browser', 'webpage'],
    prompt: '你能指出浏览器和网页内容区的边界，并说明“页面显示出来”只代表一次浏览器运行结果吗？',
    passDescription: '能用自己的话区分浏览器外壳、网页内容和页面临时状态即可。',
    remediationLabel: '补看：浏览器与网页的边界',
    remediationTarget: '#concept-browser',
    remediation: {
      purpose: 'W1D2 要从地址栏和网络入口开始，先确认你不会把浏览器工具误写成网页或服务器。',
      steps: [
        '回到 W1D1 的浏览器概念卡，指出地址栏、标签页和网页正文分别属于什么对象。',
        '刷新课程页，记录一个仍保留和一个被重置的页面状态。',
        '用一句话写出“浏览器能显示结果，但不等于业务服务器”的原因。',
      ],
      successCheck: '你能把地址栏、网页内容和页面临时状态分别归位，并说明刷新不会改变域名的含义。',
    },
  },
  {
    id: 'w1d2-front-end-material',
    conceptIds: ['front-end-code'],
    prompt: '你能解释前端代码是实现材料，而不是浏览器已经运行后的唯一事实吗？',
    passDescription: '能说出源代码、浏览器运行结果和正式发布版本之间至少一处区别。',
    remediationLabel: '补看：前端材料与运行结果',
    remediationTarget: '#concept-front-end-code',
    remediation: {
      purpose: '寻址只负责把请求送到入口；页面内容还要由前端与服务端共同产生，先把这条边界说清。',
      steps: [
        '阅读 W1D1 前端代码卡的输入、输出和不负责事项。',
        '比较 Elements 中临时节点与项目源文件，写出它们为什么不是同一个层次。',
        '在本课记录中补一句“找到服务器之后还没有证明什么”。',
      ],
      successCheck: '你能说明寻址成功只证明入口可被定位，不能单独证明前端内容或业务数据正确。',
    },
  },
]

const coreConceptGroups: DailyCourse['coreConceptGroups'] = [
  {
    id: 'address-language',
    title: '地址语言：URL、协议与路径',
    conceptIds: ['url', 'transport-protocol', 'path-query'],
    summary: 'URL 把访问协议、目标主机和资源位置写进一个可复制的地址；协议决定沟通方式，路径与查询参数进一步限定资源或筛选条件。',
    boundary: '地址描述“去哪里以及带什么定位线索”，不直接承诺资源存在、权限通过或业务数据正确。',
  },
  {
    id: 'name-resolution',
    title: '名称解析：域名、DNS 与 IP',
    conceptIds: ['domain-name', 'dns', 'server-address'],
    summary: '域名是给人和产品团队使用的稳定名称，DNS 把它解析成网络可路由的地址；服务器地址是某次解析得到的入口信息。',
    boundary: '解析得到 IP 只证明名称到地址的链路有结果，不能证明目标服务健康或请求会返回业务成功。',
  },
  {
    id: 'entry-routing',
    title: '入口约束：端口与服务边界',
    conceptIds: ['port'],
    summary: '端口把同一台机器上的不同网络服务分开，协议与端口共同决定浏览器应向哪个入口发起连接。',
    boundary: '端口开放不等于应用逻辑可用；连接被接受也不等于页面内容符合产品要求。',
  },
]

const concepts: DailyCourse['concepts'] = [
  {
    id: 'url', prerequisiteConceptIds: ['browser', 'webpage'], term: '统一资源定位符', english: 'URL',
    definition: 'URL 是一串可复制的资源定位表达式，它把访问协议、目标主机、可选端口、路径和查询参数组合在一起，让浏览器知道要以什么方式寻找哪个入口以及请求哪一类资源。它不是“页面本身”，而是通往页面或数据的地址说明。',
    why: '产品经理在需求、埋点、Bug 和验收记录中经常只拿到一条地址。若不能拆开 URL，就无法判断问题发生在协议、主机定位、路径路由还是参数传递。',
    problemSolved: '它解决“怎样用一个稳定、可分享的文本指向网络资源”的问题，使浏览器、研发和测试可以围绕同一地址复现操作。',
    input: 'URL 的输入来自产品路由设计、服务部署信息、资源路径和需要传递的查询条件；浏览器还会结合当前页面上下文补全相对地址。',
    output: '输出是一组供浏览器使用的定位线索，包括连接方式、目标主机、端口、路径和查询字符串；这些线索随后会进入连接和 HTTP 阶段。',
    systemPosition: 'URL 位于用户动作与网络寻址之间：用户点击链接或输入地址，浏览器先解析 URL，再决定下一步连接哪个入口。',
    process: ['浏览器读取地址中的协议和主机部分，确定连接语义。', '它把域名交给 DNS 或本地缓存寻找可路由地址。', '它组合端口、路径和查询参数，形成后续请求的目标。', '连接与请求阶段再根据服务端实际响应决定页面能否出现。'],
    owner: '前端、后端和基础设施共同约定 URL 结构；产品经理负责确保用户任务、资源命名和可复现记录之间一致。',
    notResponsibleFor: 'URL 不保证资源一定存在、用户一定有权限，也不说明服务端会返回正确内容；地址可打开仍需要后续证据。',
    compareWith: 'URL 常与域名混淆。域名只是主机名称的一部分，URL 还可能包含协议、端口、路径和查询参数；把二者混为一谈会漏掉路由与筛选条件。',
    evidence: ['地址栏中可直接复制的完整字符串是 URL 的运行证据。', '浏览器在导航前会显示或保留协议、主机和路径的不同部分。', '实验记录把同一域名换成不同路径后，目标资源线索会发生变化。'],
    failureModes: ['路径拼写错误导致 404 或进入错误页面。', '查询参数编码错误导致筛选条件丢失。', '把内部开发地址复制给外部用户造成不可达。'],
    pmUse: '写需求或提 Bug 时记录完整 URL 与触发条件，避免只写“打开某页面”；评审路由时检查路径和查询参数是否表达了真实任务。',
    correctExample: '“在 https://learn.example.test:8443/catalog?week=1 中，https 是协议，learn.example.test 是域名，8443 是端口，/catalog 是路径，week=1 是查询条件；它只说明访问目标，不证明课程数据已加载。”',
    incorrectExample: '“这个域名就是整个 URL，能解析就代表页面和数据都正常。”这同时漏掉协议、路径与查询，并越过了内容和业务证据边界。',
  },
  {
    id: 'domain-name', prerequisiteConceptIds: ['url'], term: '域名', english: 'Domain Name',
    definition: '域名是面向人和组织的分层名称，例如 api.example.test。它把服务入口从难以记忆的数字地址中抽象出来，并为环境、业务边界和证书配置提供可读的命名空间。',
    why: '数字地址可能变化，团队却需要稳定地讨论“生产 API”“测试站点”或“图片服务”。域名让产品文档、监控和协作记录可以围绕清晰的名称展开。',
    problemSolved: '它解决“人如何稳定称呼一组可能变化的网络入口”的问题，并允许不同子域名承载不同服务职责。',
    input: '域名由注册与基础设施配置、环境命名和服务拆分共同产生；浏览器从 URL 中读到它，再请求解析系统给出当前地址。',
    output: '输出是一个可被 DNS 查询的名称以及团队可读的环境线索；它本身不是服务器内存中的页面或数据库记录。',
    systemPosition: '域名位于 URL 的主机位置，是浏览器寻找服务器地址前的名称层；它把产品概念映射到网络入口，但不执行业务逻辑。',
    process: ['产品与基础设施约定域名层级和环境后缀。', '用户从链接或地址栏进入，浏览器提取主机名。', 'DNS 根据缓存与权威记录返回一个或多个地址。', '浏览器再使用这些地址建立连接并继续请求。'],
    owner: '域名注册、DNS 和证书通常由基础设施或平台团队维护，业务团队负责命名语义和环境使用边界。',
    notResponsibleFor: '域名不等于某台永远不变的机器，也不保证子域名背后的应用有健康实例、正确证书或可用数据。',
    compareWith: '域名与 IP 地址不同：域名是可读名称，IP 是一次解析得到的网络地址；域名可以指向多个 IP，IP 也可能被多个域名共享。',
    evidence: ['地址栏显示的主机名是用户侧可见证据。', '解析实验能把同一域名映射到一个或多个教学地址。', '不同环境使用不同子域名时，页面入口和证书名称会随之变化。'],
    failureModes: ['测试域名误写到生产文档。', '子域名记录缺失导致 NXDOMAIN。', '证书覆盖的域名与实际访问名称不一致。'],
    pmUse: '在验收、埋点和灰度沟通中写清环境域名；看到“线上打不开”时先核对是否使用了正确域名和环境。',
    correctExample: '“staging-api.example.test 是测试 API 的域名；它解析到教学地址并不代表生产接口也可用，需继续核对环境和服务状态。”',
    incorrectExample: '“域名就是服务器 IP 的别名，换成任何数字都一样。”这忽略了 DNS、证书和环境命名对访问行为的影响。',
  },
  {
    id: 'dns', prerequisiteConceptIds: ['domain-name'], term: '域名系统', english: 'DNS',
    definition: 'DNS 是把域名查询成网络地址的分布式命名系统。浏览器可能先查看本机、浏览器或递归解析器缓存；若没有结果，再沿层级向权威记录查询，并把结果在一段时间内缓存。',
    why: '用户更容易记住名称，网络连接却需要地址。DNS 把这两种语言接起来，也解释了为什么刚改记录后不同用户可能在一段时间内看到不同解析结果。',
    problemSolved: '它解决“如何在地址会变化、服务会扩展的情况下，把人类名称转换成可连接地址”的问题。',
    input: '输入是域名、查询类型和当前解析环境；缓存、TTL、递归服务与权威记录都会影响本次查询路径。',
    output: '输出可能是一个或多个 IP、别名记录、错误状态或暂时没有结果；这些结果只代表名称解析层的观察。',
    systemPosition: 'DNS 位于 URL 主机名和建立网络连接之间，是寻址链路中的名称解析层，不负责 HTTP 内容和业务权限。',
    process: ['浏览器判断本地是否有仍在有效期内的缓存。', '没有缓存时向配置的递归解析器发出查询。', '递归解析器沿根、顶级域和权威记录寻找答案。', '结果连同 TTL 返回并在允许范围内缓存。'],
    owner: '基础设施或平台团队维护解析记录与 TTL；应用团队提供服务入口需求，产品经理负责在验收中确认环境和变更窗口。',
    notResponsibleFor: 'DNS 不验证页面文案、用户权限、接口状态码或数据库写入；解析成功后仍可能连接超时或返回应用错误。',
    compareWith: 'DNS 解析不同于 HTTP 请求：DNS 只回答“这个名字当前对应哪些网络入口”，HTTP 才携带资源路径、方法和业务数据。',
    evidence: ['教学解析器会展示查询名称、命中记录和 TTL。', '换用未登记的子域名时会得到明确的解析失败结果。', '等待或清除缓存后，同一名称可能出现新的地址。'],
    failureModes: ['TTL 过长使故障修复后的旧地址继续被使用。', '权威记录漏配导致部分环境无法解析。', '把 DNS 失败误写成页面业务逻辑失败。'],
    pmUse: '发布切换、灰度和跨环境验收时记录解析时间、名称、结果和 TTL，协助研发区分“找不到入口”与“应用已收到请求”。',
    correctExample: '“api.example.test 在教学递归器中解析到 203.0.113.18，TTL 60 秒；这证明当前名称有解析结果，不证明该地址上的订单服务已健康。”',
    incorrectExample: '“DNS 返回 IP，所以接口一定返回 200。”名称解析和应用响应属于不同层，不能用前者替代后者。',
  },
  {
    id: 'server-address', prerequisiteConceptIds: ['dns'], term: '服务器地址', english: 'Server Address',
    definition: '服务器地址是一次寻址结果中可用于建立连接的网络入口，常见表达包括 IPv4、IPv6 或由代理、负载均衡对外提供的地址。它是当前路径中的可连接目标，不一定等于最终处理请求的物理机器。',
    why: '产品团队看到域名解析结果后，还需要知道“请求将被送到哪个地址层”。理解这一点有助于解释多实例、负载均衡和地址变更带来的现象。',
    problemSolved: '它解决“浏览器拿到名称后，下一步向哪个网络目标发起连接”的问题。',
    input: '输入来自 DNS、服务发现、代理或本地 hosts 配置；地址类型、网络环境和端口共同决定连接是否可达。',
    output: '输出是连接尝试的目标地址以及可能的连接成功、拒绝、超时或不可达结果。',
    systemPosition: '服务器地址位于 DNS 结果和传输连接之间；它提供网络层入口，但不代表应用实例一定接受或正确处理请求。',
    process: ['解析系统返回候选地址，浏览器选择可用目标。', '浏览器按协议和端口建立连接或交给代理。', '网络路径上的防火墙、负载均衡和服务监听共同决定是否到达应用。', '连接建立后才进入 HTTP 或其他应用层交换。'],
    owner: '网络与基础设施团队负责地址分配、路由和入口稳定性，应用团队负责服务监听和健康检查。',
    notResponsibleFor: '服务器地址不负责解释路径、鉴权、返回内容或完成数据库操作；连接成功也可能被应用层拒绝。',
    compareWith: '服务器地址与域名互相配合：域名是稳定名称，地址是一次解析可用于连接的目标；前者适合协作，后者适合网络传输。',
    evidence: ['解析结果面板显示目标地址和地址族。', '连接测试会区分“地址不可达”“端口拒绝”和“应用层返回错误”。', '同一域名在不同网络环境可能选择不同地址。'],
    failureModes: ['只在公司内网可达却被误报为全网服务。', 'IPv6 地址可解析但客户端没有可用路由。', '负载均衡地址可连接但后端实例全部不健康。'],
    pmUse: '在跨网络验收和线上故障沟通中记录解析地址、网络位置与连接结果，为研发提供比“打不开”更可复现的上下文。',
    correctExample: '“域名解析到了 203.0.113.18，但 8443 端口连接被拒绝；目前只能定位到入口层，不应直接写成页面逻辑报错。”',
    incorrectExample: '“看到 IP 就知道是哪台服务器和哪个业务模块。”地址可能是代理或负载均衡入口，不能越界推断责任归属。',
  },
  {
    id: 'port', prerequisiteConceptIds: ['server-address'], term: '端口', english: 'Port',
    definition: '端口是同一网络地址上区分不同传输服务的编号。协议、服务器地址和端口共同构成连接入口；常见的 HTTPS 默认端口是 443，但实际部署也可能使用其他端口。',
    why: '同一台机器可以同时承载多个服务。只知道地址而不知道端口，仍无法判断浏览器应把连接交给哪个监听程序。',
    problemSolved: '它解决“一个网络地址上如何把连接分派给正确服务”的问题，并让开发、测试和生产入口可以并存。',
    input: '端口来自 URL 显式配置、协议默认值或基础设施约定；防火墙、代理和应用监听会共同影响它是否可用。',
    output: '输出是连接目标上的一个服务入口，可能表现为接受、拒绝、超时或被策略拦截。',
    systemPosition: '端口位于地址与应用连接之间，是传输层到具体服务监听的分派线索；它还没有进入 HTTP 字段或业务处理。',
    process: ['浏览器从 URL 或协议默认值得到端口。', '它向服务器地址的该端口发起连接。', '网络策略和目标程序判断是否接受。', '接受后才继续进行应用层协议交换。'],
    owner: '基础设施负责开放策略和入口规划，服务团队负责监听和协议配置；产品经理在验收中关注环境是否提供可达入口。',
    notResponsibleFor: '端口开放不代表 URL 路由、认证或业务数据有效，也不能单独证明服务已经准备好处理请求。',
    compareWith: '端口和路径不同：端口决定进入哪类服务，路径决定服务内部要访问哪种资源；二者在故障定位中不能互换。',
    evidence: ['完整 URL 中出现的 :8443 等片段是显式端口证据。', '连接探测可以区分端口拒绝和 HTTP 404。', '去掉非默认端口后，浏览器可能连接到另一套入口。'],
    failureModes: ['本地开发端口写进生产文档。', '安全策略只开放 443，却要求用户访问 8443。', '端口可连接但监听的是错误服务。'],
    pmUse: '写环境地址、联调说明和验收步骤时记录端口；看到连接层错误时先确认协议默认端口与部署端口是否一致。',
    correctExample: '“测试入口使用 https://api.example.test:8443；8443 只说明连接分派到这个端口，仍需继续验证 TLS、HTTP 路由和业务响应。”',
    incorrectExample: '“443 端口打开，所以 API 一定正常。”端口只完成入口分派，不能替代应用层验收。',
  },
  {
    id: 'transport-protocol', prerequisiteConceptIds: ['url', 'port'], term: '访问协议', english: 'Access Protocol',
    definition: '访问协议规定浏览器与目标入口如何开始通信以及如何保护这段通信。对网页最常见的是 HTTP 或 HTTPS；HTTPS 在 HTTP 之上增加了 TLS 加密与身份校验过程。',
    why: '同一个主机和路径，用不同协议访问时可能得到完全不同的安全边界、端口默认值和浏览器行为。产品验收不能只看地址文字是否相似。',
    problemSolved: '它解决“客户端与服务端以什么共同规则建立应用通信”的问题，并为加密、证书和错误恢复提供入口条件。',
    input: '输入是 URL 协议前缀、浏览器支持能力、证书与服务端监听配置。',
    output: '输出是可继续进行 HTTP 交换的安全或非安全连接，以及证书错误、协议不匹配或连接失败等结果。',
    systemPosition: '访问协议位于 URL 解析和 HTTP 消息交换之间；它先建立通信语境，再让请求和响应承载资源信息。',
    process: ['浏览器读取 http 或 https 前缀并选择默认端口。', 'HTTPS 场景先协商 TLS 并校验证书名称。', '连接建立后双方按 HTTP 语义传递消息。', '浏览器根据协议安全等级决定是否允许混合内容等行为。'],
    owner: '平台和服务端负责协议、证书与加密配置，前端负责资源引用和安全兼容，产品经理负责定义用户可接受的安全边界。',
    notResponsibleFor: 'HTTPS 加密传输不能保证应用逻辑正确、权限校验正确或数据库内容真实；它只保护一段通信链路。',
    compareWith: '访问协议不同于 DNS：DNS 负责名称解析，协议负责连接与消息交换；先有可达地址，仍要用正确协议才能继续。',
    evidence: ['地址栏锁形图标、协议前缀和证书详情是浏览器侧证据。', '实验可记录协议、默认端口和证书匹配结果。', '切换 http/https 后，浏览器可能显示重定向或安全警告。'],
    failureModes: ['证书域名与访问域名不匹配。', '页面引用了不安全的混合资源。', '服务只监听 HTTP 却被要求使用 HTTPS。'],
    pmUse: '在发布和验收文档中写清协议与证书要求，避免把“能连上”与“满足安全要求”混为一谈。',
    correctExample: '“https://learn.example.test 的证书覆盖该域名，浏览器完成 TLS 后才进入 HTTP；这证明传输链路满足当前证书校验，不证明课程内容无误。”',
    incorrectExample: '“有锁就是业务安全，服务器不会返回错误。”锁只表达通信保护与身份校验的一部分。',
  },
  {
    id: 'path-query', prerequisiteConceptIds: ['url'], term: '路径与查询参数', english: 'Path & Query',
    definition: '路径标识主机内的资源层级，查询参数在同一个路径上附加筛选、分页或实验条件。两者都属于 URL 的资源定位部分，但参数的具体含义由应用路由约定。',
    why: '同一域名可能承载首页、课程、图片和接口。产品经理需要知道路径和查询怎样改变资源定位，才能写出可复现的入口与验收条件。',
    problemSolved: '它解决“在同一个服务入口中进一步指向哪类资源、哪一页或哪组筛选结果”的问题。',
    input: '输入是路由设计、资源层级、分页规则和筛选条件；浏览器会按编码规则把它们放入 URL。',
    output: '输出是服务端可解析的资源定位线索，最终由应用路由决定返回页面、数据或错误。',
    systemPosition: '路径与查询位于 URL 主机定位之后、HTTP 请求发送之前；它们告诉目标服务“希望处理什么资源”。',
    process: ['浏览器先解析路径和查询的分隔符与编码。', '它把路径交给目标服务的资源路由。', '服务端读取查询参数并应用筛选、分页或实验条件。', '响应返回后再验证这些条件是否真的生效。'],
    owner: '前端与后端共同约定路由和参数，产品经理负责保证用户任务与地址语义一致，测试负责覆盖边界值。',
    notResponsibleFor: '路径正确不代表资源存在，查询参数也不保证服务端接受或正确过滤；需要响应证据进一步确认。',
    compareWith: '路径通常表达资源层级，查询参数通常表达同一资源的视图或条件；二者都不是 DNS，也不是服务器地址。',
    evidence: ['修改路径后页面标题或资源类型变化。', '修改查询参数后列表筛选、分页或实验分支变化。', '错误路径可能返回 404，而错误参数可能返回 400 或空结果。'],
    failureModes: ['大小写或尾斜杠规则不一致。', '查询参数未编码导致值被截断。', '把需要放在请求体的内容塞进 URL 造成泄露或长度限制。'],
    pmUse: '写可复现步骤时保留完整路径和参数；评审路由时明确哪些参数是用户可见筛选，哪些属于内部实现细节。',
    correctExample: '“/catalog?week=1&page=2 仍指向课程目录资源，只是筛选第 1 周并请求第 2 页；参数被服务端忽略时不能把页面结果误判为已生效。”',
    incorrectExample: '“只要域名正确，任意路径和参数都会打开同一页面。”这忽略了路由、编码和参数校验。',
  },
]

const diagram: DailyCourse['diagram'] = {
  title: '从地址栏到连接入口：名称如何变成可达目标',
  caption: '先读 URL，再解析名称，最后核对地址、端口和协议；每一步都有自己的失败边界。',
  nodes: [
    { id: 'url', label: 'URL 地址', description: '写出协议、域名、端口、路径和查询条件。', input: '用户链接或地址栏文本', output: '资源定位线索', owner: '浏览器与产品路由' },
    { id: 'dns', label: 'DNS 解析', description: '把域名查询为当前可用的网络地址。', input: '主机名与查询环境', output: 'IP、别名或错误', owner: '基础设施团队', evidence: '记录地址与 TTL' },
    { id: 'entry', label: '服务器入口', description: '按地址、端口和协议建立连接。', input: '候选地址与端口', output: '连接结果', owner: '网络与服务监听', evidence: '接受、拒绝或超时' },
    { id: 'resource', label: '资源路由', description: '连接建立后才由应用解释路径与查询。', input: '路径、查询与后续请求', output: '页面或数据响应', owner: '前后端应用', evidence: '需进入 W1D3 HTTP 证据' },
  ],
  branches: [
    { from: 'url', to: 'dns', label: '提取主机名', kind: 'normal' },
    { from: 'dns', to: 'entry', label: '返回可用地址', kind: 'normal' },
    { from: 'entry', to: 'resource', label: '连接建立', kind: 'normal' },
    { from: 'dns', to: 'entry', label: '无记录 / 解析失败', kind: 'failure' },
    { from: 'entry', to: 'resource', label: '端口拒绝 / 连接超时', kind: 'failure' },
  ],
  evidenceNotes: ['解析结果只能证明名称层有答案。', '端口连接结果只能定位入口层，不等于页面或业务响应。', '路径和查询的语义要在后续 HTTP 课程中用请求证据确认。'],
}

const demonstration: DailyCourse['demonstration'] = {
  title: '教师示范：排查“测试页面打不开”到底卡在哪一层',
  businessProblem: '设计同学反馈测试课程入口打不开。产品经理需要在不改服务器配置的前提下，先给研发一份能区分地址、端口和应用层的最小证据记录。',
  finalConclusion: '该次失败发生在名称解析之后的端口连接层：域名有答案，但 8443 入口拒绝连接，因此不能继续判断路径和页面内容。',
  conclusionLimit: '这条结论不能证明服务端代码或课程数据有问题；要进入 HTTP 层，需要先恢复可连接入口。',
  steps: [
    { title: '固定复现地址', action: '复制完整测试 URL，并保留协议、域名、端口和路径。', reason: '避免把不同环境或不同入口混在一起。', evidence: '记录得到一条带 :8443 的 https 地址。', proves: '问题有稳定输入。', limitation: '还不知道域名是否能解析。' },
    { title: '检查域名名称', action: '在教学解析器中查询 api.staging.example.test。', reason: '先分开名称层和连接层。', evidence: '返回 203.0.113.20，TTL 60 秒。', proves: '域名当前存在解析结果。', limitation: '不证明该地址上的服务健康。' },
    { title: '核对协议与端口', action: '从 URL 读出 https 与 8443，并与测试环境约定对照。', reason: '错误端口会在应用层之前阻断请求。', evidence: '协议为 HTTPS，端口明确不是默认 443。', proves: '连接测试应指向 8443。', limitation: '不代表该端口真的监听。' },
    { title: '执行入口探测', action: '对 203.0.113.20:8443 做一次受限连接测试。', reason: '观察是否到达服务监听，而不是直接猜页面代码。', evidence: '结果为 connection refused。', proves: '入口主动拒绝连接。', limitation: '不能判断路径、权限或数据。' },
    { title: '写出分层结论', action: '把解析成功、端口拒绝和未进入 HTTP 三件事分开记录。', reason: '研发需要知道下一步修复的是入口配置而不是页面文案。', evidence: '记录含输入、结果、时间和未证明事项。', proves: '问题定位停在可证据支持的层。', limitation: '恢复端口后仍需重新验证 HTTP 响应。' },
    { title: '提出安全下一步', action: '请基础设施确认 8443 监听、网络策略和证书，不直接要求前端改 URL。', reason: '动作必须对应当前证据指向的责任边界。', evidence: '工单包含目标地址、端口与失败时间。', proves: '跨团队交接可复现。', limitation: '工单提交不等于故障已修复。' },
  ],
}

const guidedLab: DailyCourse['guidedLab'] = {
  title: '教学寻址台：把域名解析成可解释的入口记录',
  goal: '在本地教学模拟中比较一个正常域名、一个未登记域名和一个带非默认端口的 URL，并把每一步的证据边界写清。',
  safety: '这是教学模拟，不会查询真实公司域名，也不会对互联网发起扫描；所有地址均为文档保留示例。',
  conceptIds: ['url', 'domain-name', 'dns', 'server-address', 'port', 'transport-protocol', 'path-query'],
  predictionPrompt: '如果域名解析成功但端口被拒绝，页面会不会已经进入 HTTP？请先写出你的判断和依据。',
  steps: [
    { title: '输入完整 URL', action: '在左侧解析器输入 https://api.example.test:8443/catalog?week=1。', observe: '观察解析器拆出的协议、域名、端口、路径和查询。', explanation: '浏览器先把地址分成定位线索，再决定名称查询和连接目标。', proves: '你能从 URL 找出后续实验输入。', cannotProve: '拆分正确不证明服务存在。' },
    { title: '运行正常解析', action: '点击“解析域名”，记录返回地址与 TTL。', observe: '右侧日志出现 203.0.113.18 和 TTL 60s。', explanation: 'DNS 输出是名称层答案，可能来自缓存或权威记录。', proves: '该教学名称当前有解析结果。', cannotProve: '不证明端口监听或页面内容。' },
    { title: '对照未登记名称', action: '把域名改成 missing.example.test 再解析。', observe: '状态变为 NXDOMAIN，未生成服务器地址。', explanation: '没有名称答案时，浏览器没有可继续连接的目标。', proves: '失败发生在 DNS 层。', cannotProve: '不代表原域名对应的应用有故障。' },
    { title: '核对端口入口', action: '把端口从 8443 改为 443，观察连接预检结果。', observe: '教学台显示“端口可达性待 HTTP 验证”，并保留协议差异。', explanation: '端口是服务分派线索，默认端口与显式端口可能指向不同入口。', proves: '你能指出地址与端口的关系。', cannotProve: '端口可达不等于请求返回业务成功。' },
  ],
  recordPrompts: [
    '记录正常域名的完整 URL、解析地址和 TTL。',
    '记录未登记域名的错误状态，并注明它停在哪一层。',
    '解释把 8443 改为 443 后，哪些证据改变、哪些结论仍未知。',
    '写出一个研发可以复现的下一步检查动作。',
  ],
  comparePrompt: '比较“有 DNS 结果”和“页面能正常使用”之间的差距，至少写出两个仍需验证的层。',
  passCriteria: ['能准确拆出 URL 的关键部分。', '能用名称层、连接层和应用层三个词说明证据边界。', '记录中包含输入、结果、时间或 TTL，并标记教学模拟。'],
}

const independentLab: DailyCourse['independentLab'] = {
  title: '独立变式：多环境域名切换记录',
  scenario: '同一课程功能在预发布环境可打开，切到灰度域名后出现“找不到服务器”。你需要判断是名称、地址、端口还是后续应用层问题。',
  conceptIds: ['url', 'domain-name', 'dns', 'server-address', 'port', 'transport-protocol', 'path-query'],
  changedConditions: ['把 staging.example.test 换成 canary.example.test，两个域名的 TTL 不同。', '灰度入口使用 9443 端口，而不是预发布的 8443。', '路径从 /catalog 改为 /catalog/preview，并增加 region=cn 查询参数。'],
  task: '先写预测，再用教学寻址台完成两次解析和一次端口对照，提交一份按层定位的排查记录。',
  predictionPrompt: '如果灰度域名有解析结果但 9443 连接超时，你会把问题先交给谁？为什么还不能让前端确认页面逻辑？',
  evidenceRequirements: ['两条完整 URL 与拆分结果。', '每个域名的解析地址、TTL、端口结果和观察时间。', '至少一个失败分支的证据边界与下一步责任建议。'],
  passCriteria: ['没有把 DNS 结果写成页面成功。', '能区分解析失败、端口失败和路径未知。', '记录足够让另一位同事在同一教学台重做。'],
  remediation: { label: '回到 URL 与 DNS 概念卡', sectionId: 'concepts', anchor: '#concept-dns' },
}

const exercises: DailyCourse['exercises'] = [
  {
    id: 'w1d2-exercise-url-parts', kind: 'single-choice', categories: ['概念与边界'], conceptIds: ['url', 'path-query'],
    prompt: '在 https://app.example.test:8443/course?week=1 中，哪一项最准确地描述 :8443？', hint: '先区分主机名称、端口与路径。', options: [
      { label: '端口，提示浏览器连接该主机上的特定服务入口', rationale: '端口承担服务分派，位于域名之后、路径之前。', couldBeTrueWhen: '只要 URL 显式写出非默认端口，这个解释就成立。' },
      { label: '路径，表示课程资源的层级', rationale: '路径是 /course，不是 :8443。', couldBeTrueWhen: '看到 /course 片段时才成立。' },
      { label: 'DNS 记录，表示域名对应的 IP', rationale: 'DNS 记录不会以端口写法出现在 URL 主机段中。', couldBeTrueWhen: '你在解析器结果中看到 A/AAAA 记录时才相关。' },
      { label: '查询参数，筛选第 8443 周课程', rationale: '查询参数从 ? 开始，:8443 没有筛选语义。', couldBeTrueWhen: '只有 ?week=1 这类片段才是查询参数。' },
    ], answerIndex: 0, referenceAnswer: '正确答案是端口。:8443 指向目标主机上的特定服务入口；它不等于 DNS、路径或查询参数。', reasoning: ['先识别协议与主机结束位置。', '冒号后的数字在 URL 中表示显式端口。', '路径和查询分别从 / 与 ? 开始。'], rubric: ['能指出 URL 组成', '能解释端口的服务分派作用'], commonErrors: [{ error: '把端口当路径', reason: '没有按 URL 分隔符读取结构。' }], remediation: { label: '回看 URL 概念卡', sectionId: 'concepts', anchor: '#concept-url' },
  },
  {
    id: 'w1d2-exercise-dns-boundary', kind: 'open', categories: ['机制推演', '证据判断'], conceptIds: ['dns', 'server-address'],
    prompt: '教学解析器返回 203.0.113.18，但浏览器随后连接超时。请按顺序写出已知事实、尚未知事实和下一步检查。', hint: '至少分成名称层、连接层、应用层三段。', referenceAnswer: '已知域名解析得到地址；未知该地址的端口是否可达、服务是否监听以及应用是否返回内容。下一步应记录目标端口并做受限连接或服务健康检查。', reasoning: ['DNS 有结果说明名称层完成。', '连接超时说明不能把结果直接当成应用可用。', '下一步要继续验证端口和监听。'], rubric: ['名称、连接、应用三层分开写清', '下一步与当前证据严格对应'], commonErrors: [{ error: '直接判定服务器代码错误', reason: '跳过连接层，结论越过当前证据。' }], remediation: { label: '回看 DNS 与服务器地址', sectionId: 'concepts', anchor: '#concept-server-address' },
  },
  {
    id: 'w1d2-exercise-environment', kind: 'open', categories: ['工作场景'], conceptIds: ['domain-name', 'transport-protocol'],
    prompt: '请为“预发布课程入口打不开”写一条研发可复现的最小记录，至少包含环境域名、协议、端口、时间和不能证明的事项。', hint: '不要只写“页面打不开”。', referenceAnswer: '2026-08-17 14:20，预发布 https://staging.example.test:8443/catalog 打不开；域名解析结果为 203.0.113.20，端口连接拒绝；当前只定位到入口层，不能证明页面代码或课程数据有误。', reasoning: ['先固定环境和完整地址。', '再写解析、端口和时间证据。', '最后明确尚未证明的应用层事实。'], rubric: ['环境、时间和地址字段完整', '证据边界与未证明事项诚实'], commonErrors: [{ error: '省略环境', reason: '研发无法知道应在哪个入口复现。' }], remediation: { label: '回到教师示范结论', sectionId: 'demonstration', anchor: '#demonstration-conclusion' },
  },
  {
    id: 'w1d2-exercise-branch', kind: 'single-choice', categories: ['证据判断', '工作场景'], conceptIds: ['dns', 'port'],
    prompt: '下面哪条观察最能支持“失败发生在 DNS 层”，而不是端口或路径层？', hint: '寻找还没有生成服务器地址的情况。', options: [
      { label: '返回 NXDOMAIN，且没有任何候选地址', rationale: '名称没有解析答案，浏览器没有可继续连接的目标。', couldBeTrueWhen: '查询名称未在当前解析环境登记时成立。' },
      { label: '端口连接被拒绝', rationale: '这已经进入服务器地址与端口层。', couldBeTrueWhen: '地址存在但服务监听或策略不接受连接时成立。' },
      { label: 'HTTP 返回 404', rationale: '404 是应用资源路由阶段的响应。', couldBeTrueWhen: '连接和 HTTP 已经成功建立时成立。' },
      { label: '页面显示空列表', rationale: '空列表需要应用数据和响应证据才能判断。', couldBeTrueWhen: '接口返回成功但筛选结果为空时可能成立。' },
    ], answerIndex: 0, referenceAnswer: 'NXDOMAIN 且没有地址说明名称解析没有完成；其余选项都依赖后续连接或应用层证据。', reasoning: ['先看是否生成可连接地址。', '没有地址时不可能进入端口或路径。', '错误状态的层次要与产生它的系统对应。'], rubric: ['能按名称、连接和应用层定位', '不把后续状态倒推为 DNS'], commonErrors: [{ error: '把 404 当 DNS 错误', reason: '忽略了 HTTP 已经建立的事实。' }], remediation: { label: '回看概念关系图', sectionId: 'diagram', anchor: '#w1d2-diagram' },
  },
  {
    id: 'w1d2-exercise-transfer', kind: 'open', categories: ['综合变式'], conceptIds: ['url', 'path-query', 'port'],
    prompt: '产品把 /catalog?week=1 改成 /catalog/preview?week=1&region=cn，并将端口从 8443 改为 443。请写出你会比较的三组证据。', hint: '比较地址结构、入口和资源路由三层。', referenceAnswer: '比较完整 URL 拆分、443/8443 的连接结果、以及两个路径和查询在应用响应中的差异；不能只看到页面打开就断言筛选和环境都正确。', reasoning: ['记录 URL 结构变化。', '分别验证端口入口。', '进入 HTTP 后再核对路径和查询语义。'], rubric: ['覆盖三组证据', '说明层次顺序和限制'], commonErrors: [{ error: '只比较页面截图', reason: '截图不能说明端口和查询是否按预期生效。' }], remediation: { label: '回到路径与查询概念卡', sectionId: 'concepts', anchor: '#concept-path-query' },
  },
]

const deliverable: DailyCourse['deliverable'] = {
  title: '网络寻址故障记录单', conceptIds: ['url', 'domain-name', 'dns', 'server-address', 'port', 'transport-protocol', 'path-query'],
  purpose: '把“打不开”拆成可复现的地址、解析和入口证据，帮助研发从正确层开始排查。',
  whenToUse: '环境切换、域名变更、发布灰度或页面完全无法进入时使用。',
  audience: '前端、后端、基础设施、测试和需要判断优先级的产品经理。',
  fields: [
    { name: '完整 URL', meaning: '固定协议、域名、端口、路径和查询输入。', source: '地址栏、链接或复现脚本。' },
    { name: '解析结果', meaning: '记录域名是否有地址、地址值与 TTL。', source: '教学解析器或可信网络工具。' },
    { name: '入口结果', meaning: '说明端口连接是接受、拒绝还是超时。', source: '受限连接测试或浏览器错误。' },
    { name: '当前结论', meaning: '只写证据能支持的层级判断。', source: '把观察映射到 URL、DNS、连接或应用层。' },
    { name: '下一步动作', meaning: '指定责任团队与最小补充证据。', source: '当前失败点和环境约定。' },
  ],
  badExample: '页面打不开，请研发看一下。',
  badReasons: ['没有环境和完整地址，别人无法复现。', '没有区分解析、端口和应用层，责任方向不明确。', '把页面现象当成服务器或数据结论。'],
  revisionSteps: ['补上完整 URL、环境和时间。', '补做解析与端口记录，标出失败层。', '写出尚未证明的事实和下一步责任。'],
  goodExample: '【预发布寻址记录】\n时间：2026-08-17 14:20\n完整 URL：https://staging.example.test:8443/catalog?week=1\n解析结果：203.0.113.20，TTL 60s\n入口结果：8443 connection refused\n当前结论：域名有解析，但连接未进入 HTTP；不能据此判断页面代码或课程数据。\n下一步动作：请基础设施确认 8443 监听与网络策略。',
  guidedPrompts: ['这次输入的完整 URL 是什么？', '解析层返回了什么，缓存或 TTL 有什么意义？', '失败停在哪一层，哪些事实仍未知？', '下一步谁需要提供哪条证据？'],
  blankTemplate: '【环境】\n【时间】\n【完整 URL】\n【DNS 结果】\n【端口/连接结果】\n【当前结论】\n【不能证明】\n【下一步】\n',
  standardTemplate: '【环境】待填写\n【时间】待填写\n【完整 URL】协议://域名:端口/路径?查询\n【解析结果】地址：；TTL：；错误：\n【入口结果】端口/连接：\n【当前结论】\n【不能证明】\n【下一步动作】\n',
  checklist: ['完整 URL 的协议、域名、端口、路径和查询已核对。', 'DNS 结果包含地址、错误或 TTL 等可观察信息。', '入口结果与 DNS 结果分开记录，没有跨层推断。', '文档明确标注教学模拟与未证明事项。', '下一步动作对应当前失败层和责任团队。'],
}

const memory: DailyCourse['memory'] = {
  conceptIds: ['url', 'domain-name', 'dns', 'server-address', 'port', 'transport-protocol', 'path-query'],
  anchors: ['URL 是定位线索，不是页面或业务事实。', 'DNS 把名称解析为地址，解析成功不等于服务可用。', '地址、端口和协议共同决定入口，路径与查询要到应用层再验证。', '每条寻址记录都要写证据边界和下一步。'],
  closedBookPrompt: '闭卷解释：从用户输入一个 HTTPS URL 开始，依次说明浏览器如何经过域名、DNS、服务器地址和端口找到入口，并写出至少两条不能越界的结论。',
  microOperation: '再次在教学寻址台输入一个带路径和查询的 URL，记录拆分、解析结果和端口变化。',
  unresolvedPrompt: '哪一个寻址现象仍容易和 HTTP 或业务数据混淆？请写出你会在下一课追问的证据。',
  reviewStages: [
    { stage: 'D1', task: '不看笔记拆分一个 URL，并说出 DNS 只负责哪一层。' },
    { stage: 'D3', task: '比较两个环境域名和端口，指出哪条证据尚未进入 HTTP。' },
    { stage: 'D7', task: '从“打不开”描述中识别名称、连接和资源路由的不同假设。' },
    { stage: 'D14', task: '解释为什么解析地址变化不一定意味着产品路由变化。' },
    { stage: 'D30', task: '为一次灰度域名切换写出可交接的寻址证据清单。' },
    { stage: 'D60', task: '在新业务场景中迁移使用 URL、DNS、端口和协议边界。' },
  ],
}

export const w1d2: DailyCourse = {
  id: 'W1D2', contentVersion: 'w1d2-addressing-day01-v2', week: 1, day: 2,
  title: 'URL、域名、DNS 与服务器地址',
  subtitle: '从地址栏开始，读懂浏览器如何找到网络入口',
  duration: { core: 30, standard: 45, extension: 35, full: 160 },
  coreConceptGroups, prerequisiteConceptIds: ['browser', 'webpage', 'front-end-code'],
  learningPaths: {
    '30': { guidedStepIndices: [0, 1, 2, 3], guidedRecordIndices: [0, 1, 2], exerciseCount: 3, deliverablePromptCount: 3, deliverableChecklistIndices: [0, 1, 2], deliverableMinimumContributionCharacters: 80 },
    '45': { guidedStepIndices: [0, 1, 2, 3], guidedRecordIndices: [0, 1, 2, 3], exerciseCount: 5, deliverablePromptCount: 4, deliverableChecklistIndices: [0, 1, 2, 3, 4], deliverableMinimumContributionCharacters: 140 },
  },
  primaryGoal: '能把一个“打不开”的页面拆成 URL、DNS、地址、端口和协议证据，并把排查停在当前证据真正支持的层。',
  scenario: { role: '你是负责课程发布验收的产品经理。', situation: '预发布课程入口突然打不开，设计、前端和基础设施都在问“到底是页面、域名还是服务器的问题”。', question: '你如何从地址栏开始，把这次故障拆成研发可以复现的寻址记录？', stakes: '如果把解析失败写成前端 Bug，团队会在错误层级上浪费时间，也可能误改生产入口。' },
  objectives, prerequisites, concepts, diagram, demonstration, guidedLab, independentLab, exercises, deliverable, memory,
  nextLesson: { id: 'W1D3', title: 'HTTP 请求与响应', bridge: '今天你已经能解释浏览器如何从 URL 找到入口。下一课将在入口可达后，逐字段学习 HTTP 请求与响应，以及哪些信息才是真正的应用层证据。' },
}
