import type { DailyCourse } from './types'

const objectives: DailyCourse['objectives'] = [
  {
    id: 'map-http-message',
    text: '能把一次 HTTP 交换分成请求与响应，并说明 Method、URL、Header、Body、Status 和 Response 各自回答什么问题。',
    evidence: '完成一张请求/响应双栏表，逐字段写出来源、作用和一个不能越界的结论。',
  },
  {
    id: 'read-request-context',
    text: '能解释 Query、Cookie、Payload 与 Header 的差异，知道它们如何共同描述一次请求上下文。',
    evidence: '在教学 HTTP 台中修改一个字段，记录服务端可观察到的变化与未被证明的业务事实。',
  },
  {
    id: 'interpret-response-evidence',
    text: '能用 Status、Response、Timing 和 Size 判断请求是到达、被拒绝、返回错误还是只是响应很慢。',
    evidence: '对三组模拟响应写出分层结论，不把状态码或响应文本单独当成业务成功。',
  },
  {
    id: 'write-http-handoff',
    text: '能提交一份研发可复现的 HTTP 观察记录，包含请求上下文、响应证据和限制说明。',
    evidence: '成果记录至少包含方法、URL、关键 Header/Cookie/Query/Payload、状态、响应、耗时与大小。',
  },
]

const prerequisites: DailyCourse['prerequisites'] = [
  {
    id: 'w1d3-addressing',
    conceptIds: ['url', 'domain-name', 'dns', 'server-address', 'port'],
    prompt: '你能从 URL 找出域名、端口和路径，并说明 DNS/入口成功后才有条件进入 HTTP 吗？',
    passDescription: '能用上一课的寻址关系解释“先找到入口，再交换应用消息”。',
    remediationLabel: '补看：URL 到服务器入口',
    remediationTarget: '#concept-server-address',
    remediation: {
      purpose: 'HTTP 是进入服务入口后的应用层协议，先确认你不会把状态码当 DNS 或端口结果。',
      steps: [
        '回到 W1D2 的 URL、DNS 和服务器地址概念卡。',
        '在关系图中指出哪一步还没有出现请求方法和响应状态。',
        '用一句话写出“端口连接成功但 HTTP 仍可能返回什么”。',
      ],
      successCheck: '你能把寻址层与 HTTP 消息层分开，并说明应用层证据从请求/响应开始。',
    },
  },
  {
    id: 'w1d3-path-query',
    conceptIds: ['path-query'],
    prompt: '你能区分 URL 的路径和查询参数，并说明它们会进入后续请求目标而不是 DNS 名称吗？',
    passDescription: '能举出一个路径与查询同时变化的 URL，并说出需要在响应中验证什么。',
    remediationLabel: '补看：路径与查询参数',
    remediationTarget: '#concept-path-query',
    remediation: {
      purpose: 'HTTP 请求会携带 URL 目标，先把资源定位和请求字段的边界对齐。',
      steps: [
        '写出 /orders/preview 与 ?coupon=NEW 的不同作用。',
        '说明同一域名、不同路径为什么可能进入不同路由。',
        '补充一句“查询参数生效仍要看响应证据”。',
      ],
      successCheck: '你能把 URL 目标、HTTP 方法和响应结果放在连续链路中解释。',
    },
  },
]

const coreConceptGroups: DailyCourse['coreConceptGroups'] = [
  {
    id: 'http-envelope',
    title: '消息外壳：HTTP 请求与响应',
    conceptIds: ['http-message', 'http-request', 'http-response'],
    summary: 'HTTP 用一来一回的消息交换表达客户端意图与服务端结果；请求描述想做什么，响应说明服务端如何回应。',
    boundary: '消息格式和网络返回是可观察证据，但不能自动等同于业务规则已正确执行。',
  },
  {
    id: 'request-fields',
    title: '请求上下文：Method、URL、Header、Cookie、Query、Payload',
    conceptIds: ['method-url', 'header-cookie-query', 'payload'],
    summary: '请求方法和 URL 表达目标与动作，Header/Cookie/Query/Payload 携带上下文、筛选条件或提交数据。',
    boundary: '字段出现只证明客户端发出了某种信息；是否被服务端接受，要结合状态与响应正文判断。',
  },
  {
    id: 'response-evidence',
    title: '响应读法：Status、Response、Timing 与 Size',
    conceptIds: ['status-response', 'timing-size'],
    summary: '状态码给出粗粒度结果，响应正文提供内容，Timing 和 Size 帮助判断性能与传输现象；四者要联合阅读。',
    boundary: '200、正文“成功”或耗时较短都不能独立证明订单、权限或库存等业务事实。',
  },
]

const concepts: DailyCourse['concepts'] = [
  {
    id: 'http-message', prerequisiteConceptIds: ['url', 'port'], term: 'HTTP 消息交换', english: 'HTTP Message Exchange',
    definition: 'HTTP 是应用层的请求—响应协议。客户端发送一条结构化请求，服务端返回一条结构化响应；两条消息共同表达一次资源访问或业务操作的可观察过程。',
    why: '产品经理看到页面“加载失败”时，真正需要追问的是浏览器发了什么、服务端回了什么，而不是只看最终截图。HTTP 提供了可记录的中间证据。',
    problemSolved: '它解决“不同程序如何用统一格式表达资源访问、提交动作和返回结果”的问题。',
    input: '输入是可达的服务器入口、请求方法、URL 目标、字段和可选请求体；服务端还会结合自己的路由和规则。',
    output: '输出是状态码、响应头、响应正文以及耗时和大小等传输观察；客户端据此更新页面或提示错误。',
    systemPosition: 'HTTP 位于寻址层之后、页面状态更新之前，是浏览器与服务端交换资源和业务消息的应用层。',
    process: ['浏览器准备请求行、Header、Cookie、Query 和 Payload。', '请求通过已建立的连接送到服务端入口。', '服务端解析消息、执行路由和业务处理。', '服务端生成状态、Header 和 Response，浏览器再决定如何呈现。'],
    owner: '前后端共同遵守 HTTP 语义，网关和平台负责连接与转发，产品经理负责定义可验证的请求结果和错误体验。',
    notResponsibleFor: 'HTTP 格式不保证业务规则正确，也不替代数据库事务、权限策略或前端状态管理。',
    compareWith: 'HTTP 消息不同于 URL：URL 只给出目标线索，HTTP 请求还要带方法和上下文，响应则由服务端产生。',
    evidence: ['浏览器开发者工具可显示请求与响应的字段。', '教学 HTTP 台会把一次交换分成请求摘要和响应摘要。', '刷新或重试可能产生不同请求 ID 与耗时。'],
    failureModes: ['入口可达但请求格式不符合服务契约。', '请求成功到达但服务端执行超时。', '响应返回却被前端错误地解释为成功。'],
    pmUse: '写接口验收和 Bug 时把“请求证据”和“页面现象”并列记录，方便研发判断是发送、处理还是呈现阶段的问题。',
    correctExample: '“请求 POST /checkout/preview 返回 422，响应正文指出 coupon 无效；这证明服务端收到了请求并拒绝了字段，不证明页面展示层没有其他问题。”',
    incorrectExample: '“页面没弹成功提示，所以 HTTP 一定没发出去。”页面表现不足以替代请求面板证据。',
  },
  {
    id: 'http-request', prerequisiteConceptIds: ['http-message'], term: 'HTTP 请求', english: 'HTTP Request',
    definition: 'HTTP 请求是客户端发给服务端的一组结构化信息，至少包含方法和目标 URL，还可能包含 Header、Cookie、Query 与 Payload。它表达“我想对哪个资源做什么，以及带哪些上下文”。',
    why: '只说“发起请求”仍然太模糊。把请求拆开，才能判断是目标地址、动作、会话上下文还是提交数据造成了差异。',
    problemSolved: '它解决“客户端如何明确表达资源目标、操作意图和必要上下文”的问题。',
    input: '输入来自用户动作、页面状态、URL 路由、登录会话和表单或代码生成的数据。',
    output: '输出是一条可发送、可重放、可比较的消息记录，供网关和应用解析。',
    systemPosition: '请求位于浏览器动作和服务端处理之间；它是客户端证据，不等于服务端已经接受业务意图。',
    process: ['用户动作触发前端准备目标和方法。', '浏览器附加需要的 Header、Cookie、Query 与 Payload。', '请求被发送并获得唯一的时间与网络上下文。', '服务端解析后返回响应或连接层错误。'],
    owner: '前端负责生成用户侧请求，后端定义可接受的字段与语义，网关可能补充或过滤部分 Header。',
    notResponsibleFor: '请求存在不等于服务端执行成功；客户端也不能仅凭自己发送的 Payload 推断数据库已经写入。',
    compareWith: '请求和响应是相邻但不同的证据：请求说明客户端意图，响应说明服务端回报；二者不能互换。',
    evidence: ['请求面板中的 Method、URL、Header 和 Payload。', '网络日志中的请求时间和请求 ID。', '重放同一请求时可以比较字段和结果是否一致。'],
    failureModes: ['Method 与后端路由不匹配。', 'Cookie 过期导致服务端认为未登录。', 'Payload 缺字段或类型错误。'],
    pmUse: '验收表单、登录和筛选时记录请求方法、目标、关键上下文与发送内容，避免只凭 UI 复述问题。',
    correctExample: '“点击预览时发送 POST /checkout/preview，Cookie 带有教学会话，Payload 含 sku 与 quantity；这描述请求，不代表库存已扣减。”',
    incorrectExample: '“请求里有 userId，所以服务端肯定按这个用户授权。”权限仍需服务端返回与审计证据。',
  },
  {
    id: 'http-response', prerequisiteConceptIds: ['http-request'], term: 'HTTP 响应', english: 'HTTP Response',
    definition: 'HTTP 响应是服务端针对请求返回的一组结构化信息，通常包含状态码、响应 Header 和响应正文。它告诉客户端请求在协议和应用路由层发生了什么，以及可供页面使用的数据或错误。',
    why: '同一个页面提示可能来自 200 空数据、401 未登录、422 参数错误或 500 服务异常。只有读响应结构，才能把这些情况区分开。',
    problemSolved: '它解决“服务端如何把处理结果、元信息和可消费内容交还给客户端”的问题。',
    input: '输入是服务端对请求的解析结果、权限判断、业务计算和错误处理。',
    output: '输出是状态、Header、正文以及传输耗时和大小，浏览器或前端再据此更新界面。',
    systemPosition: '响应位于服务端处理之后、页面反馈之前；它是重要证据，但不自动等于最终业务事实。',
    process: ['服务端选择状态码和响应头。', '它序列化数据、错误或空结果为响应正文。', '网关和网络层传回客户端并记录耗时与大小。', '前端根据响应决定显示成功、错误或重试。'],
    owner: '后端负责响应语义与数据契约，前端负责正确呈现，网关负责传输与公共 Header。',
    notResponsibleFor: '响应 200 不保证业务结果满足产品规则，正文中的“success”字段也需要对应服务端逻辑和数据证据。',
    compareWith: '响应不同于页面提示：页面是前端处理后的体验，响应是服务端返回的原始协议证据。',
    evidence: ['状态码、响应 Header 和 Response 预览。', '响应正文中的字段、错误码和服务器时间。', '页面显示与响应内容的前后对照。'],
    failureModes: ['状态码始终 200，错误只藏在正文。', '响应字段缺失导致前端显示空白。', '前端把旧响应缓存当成最新结果。'],
    pmUse: '评审接口和错误体验时同时看状态、正文和页面表现，明确哪些是协议结果、哪些是前端翻译。',
    correctExample: '“响应为 409，正文说明库存版本冲突；页面显示‘请刷新后重试’。这证明服务端拒绝了本次写入，不证明库存系统整体不可用。”',
    incorrectExample: '“返回 JSON 就是成功响应。”JSON 只是格式，真正语义还要看状态、字段和业务规则。',
  },
  {
    id: 'method-url', prerequisiteConceptIds: ['http-request', 'path-query'], term: 'Method 与请求 URL', english: 'Method & Request URL',
    definition: 'Method 表达客户端对目标资源的动作意图，如 GET 读取、POST 提交、PUT 更新或 DELETE 删除；请求 URL 则定位动作作用的资源和查询条件。二者要一起阅读。',
    why: '相同路径用不同方法可能代表完全不同的风险和副作用。产品经理需要能判断一个按钮究竟是在读取预览、创建记录还是请求删除。',
    problemSolved: '它解决“客户端如何明确表达对哪个资源采取哪种动作”的问题，并为缓存、幂等和权限提供语义基础。',
    input: '输入来自页面交互、资源路径与 HTTP 字段约定；客户端把用户意图编码为方法和 URL。',
    output: '输出是服务端可路由、可审计的动作目标。',
    systemPosition: 'Method 与 URL 位于请求最前部，是网关和应用决定路由的首要线索。',
    process: ['用户动作选择资源和操作意图。', '前端把意图编码为方法与完整 URL。', '网关按方法和路径选择路由与策略。', '服务端返回结果，客户端再判断动作是否达成。'],
    owner: '前后端共同约定方法语义与路由，产品经理负责确认动作是否符合用户意图和风险等级。',
    notResponsibleFor: '方法名本身不证明权限通过、数据已写入或操作具有预期副作用；仍需响应和后续数据证据。',
    compareWith: 'Method 是动作语义，URL 是目标定位；把 POST 说成“某个接口地址”会漏掉副作用和幂等差异。',
    evidence: ['请求表格中的 Method 与 Request URL。', '同一路径切换 GET/POST 后，状态或响应结构变化。', '重复发送同一方法时，可观察是否产生重复副作用。'],
    failureModes: ['读取按钮误用 POST 造成不必要写入。', '路径正确但方法不被路由接受。', '把查询条件误放在错误位置导致服务端忽略。'],
    pmUse: '评审交互与接口契约时写清动作方法、资源 URL、是否改变数据和重复点击的预期。',
    correctExample: '“点击‘预览’发送 POST /checkout/preview，因为需要提交商品组合计算价格；它不等于订单已经创建。”',
    incorrectExample: '“只要 URL 对，GET 和 POST 的结果一样。”方法承载动作与安全语义，不能随意替换。',
  },
  {
    id: 'header-cookie-query', prerequisiteConceptIds: ['http-request', 'method-url'], term: 'Header、Cookie 与 Query', english: 'Headers, Cookies & Query',
    definition: 'Header 是请求或响应的元信息，Cookie 是浏览器按域名保存并附带的会话小片段，Query 是 URL 中的筛选或定位参数。三者都能影响服务端判断，但位置、生命周期和隐私边界不同。',
    why: '登录状态、语言、实验分组和筛选条件经常同时出现。若不区分三者，产品经理很难判断问题来自会话、路由还是业务参数。',
    problemSolved: '它解决“如何在不把所有信息混在正文里的情况下，携带请求上下文和资源条件”的问题。',
    input: '输入包括浏览器会话、页面选择、环境配置和前端代码添加的元信息。',
    output: '输出是服务端可读取的上下文、筛选条件或协商信息。',
    systemPosition: '它们都位于 HTTP 请求内部，但 Header/Cookie 偏向上下文，Query 偏向 URL 资源定位；服务端仍需校验。',
    process: ['浏览器从会话和页面状态收集上下文。', '前端把条件放入 Header、Cookie 或 Query。', '服务端解析字段并结合策略做判断。', '响应返回后再验证上下文是否真正生效。'],
    owner: '浏览器、前端、网关和后端共同决定字段；安全团队负责 Cookie 属性与敏感信息边界。',
    notResponsibleFor: '字段出现不代表服务端信任它；客户端可修改，服务端必须独立校验身份、权限和业务规则。',
    compareWith: 'Cookie 不等同于 Header：Cookie 会以请求 Header 的特定形式发送，但它有浏览器保存和域路径规则；Query 直接属于 URL。',
    evidence: ['请求面板显示 Header、Cookie 和 Query 的位置。', '删除 Cookie 后状态从登录变为未登录。', '改变 Query 后资源筛选变化，但需响应确认。'],
    failureModes: ['Cookie 域或 SameSite 属性导致会话未发送。', '把 Token 放进 URL 查询造成泄露。', 'Header 大小写或格式错误被网关拒绝。'],
    pmUse: '验收登录、实验分组和筛选时分别记录上下文来源，避免把敏感 Cookie 写进公共文档。',
    correctExample: '“请求带有实验分组 Header 与会话 Cookie，Query 为 ?page=2；这解释了请求上下文，但仍需看响应确认分组和分页是否生效。”',
    incorrectExample: '“Cookie 里有 userId，所以客户端可以决定用户权限。”Cookie 是可被伪造的输入，权限必须由服务端裁决。',
  },
  {
    id: 'payload', prerequisiteConceptIds: ['http-request'], term: 'Payload（请求体）', english: 'Payload / Request Body',
    definition: 'Payload 是请求体中承载的业务数据，例如 JSON、表单或文件。它通常用于提交创建、更新或计算所需的字段，格式和校验规则由服务端契约定义。',
    why: '很多“点击后报错”不是按钮没工作，而是请求体缺字段、类型不对或携带了过期状态。能读 Payload 才能把问题交给正确的接口责任人。',
    problemSolved: '它解决“客户端如何把结构化业务输入交给服务端处理”的问题。',
    input: '输入来自表单、页面状态、用户选择和前端序列化逻辑。',
    output: '输出是服务端可以校验和计算的字段集合，或明确的格式错误。',
    systemPosition: 'Payload 位于 HTTP 请求消息内部，通常在方法和 URL 之后；它比 Query 更适合承载较大的提交数据，但不是权限裁决。',
    process: ['页面把输入值整理成契约要求的结构。', '浏览器按 Content-Type 序列化请求体。', '服务端解析并校验字段、类型和边界。', '响应反馈接受、拒绝或修正建议。'],
    owner: '前端负责收集和序列化，后端负责 schema、校验、默认值与错误响应，产品经理负责字段业务含义。',
    notResponsibleFor: '请求体写入成功不等于数据库事务提交；客户端也不能用隐藏字段代替服务端校验。',
    compareWith: 'Payload 与 Query 都能携带业务条件，但 Query 常用于定位或筛选，Payload 常用于提交复杂输入；实际语义仍以契约为准。',
    evidence: ['请求面板中的 Request Payload。', '响应错误字段指出缺失或类型不合法。', '修改一个字段后，响应计算或校验结果随之改变。'],
    failureModes: ['JSON 结构与接口契约不匹配。', '数字被序列化成字符串。', '把敏感信息放进可被日志记录的 URL。'],
    pmUse: '评审表单和接口时把字段、类型、必填、边界与错误响应写成可验收条目。',
    correctExample: '“Payload 中 quantity=2，服务端返回 422 指出 sku 缺失；这证明校验收到并指出字段问题，不证明库存已被读取。”',
    incorrectExample: '“请求体里写了 price，所以服务端必须按这个价格结算。”价格等关键规则必须由后端重新计算。',
  },
  {
    id: 'status-response', prerequisiteConceptIds: ['http-response'], term: 'Status 与 Response', english: 'Status & Response',
    definition: 'Status 是响应的数字状态码，提供粗粒度的协议和处理结果；Response 通常指响应正文及其可读字段。两者联合起来，才能判断请求是成功、拒绝、找不到资源、限流还是服务异常。',
    why: '只看状态码会漏掉业务错误，只看正文又可能忽略缓存、重定向或鉴权边界。产品验收需要把两类证据放在一起。',
    problemSolved: '它解决“服务端如何用稳定的结果类别和具体内容回答客户端”的问题。',
    input: '输入是服务端路由、鉴权、校验、业务计算和异常处理。',
    output: '输出是状态码、响应头、正文和供前端消费的错误或数据字段。',
    systemPosition: 'Status/Response 位于 HTTP 响应阶段，是页面决定显示和恢复动作的主要输入。',
    process: ['服务端根据路由和校验结果选择状态码。', '它把业务数据或错误序列化为响应正文。', '网关传回响应并记录必要的测量。', '前端结合状态和正文决定提示或下一步。'],
    owner: '后端定义状态和正文契约，前端负责按类别呈现，产品经理负责把错误体验与恢复路径写清。',
    notResponsibleFor: '200 不保证数据正确，500 也不一定代表所有用户都失败；需要结合请求、时间和服务日志。',
    compareWith: 'Status 是分类信号，Response 是详细内容；页面提示则是前端对二者的再表达。',
    evidence: ['响应面板中的状态码和正文。', '错误码、字段级 message 与页面提示的对照。', '同一请求在不同输入下状态和正文的变化。'],
    failureModes: ['所有业务错误都返回 200。', '前端只显示“失败”不展示可恢复原因。', '服务端返回敏感堆栈到 Response。'],
    pmUse: '写验收时同时列状态码、正文字段和页面恢复动作；评审异常时要求状态、错误码和用户文案一致。',
    correctExample: '“Status 401，Response code=SESSION_EXPIRED，页面提供重新登录；这证明会话被拒绝，不证明用户没有购买权限。”',
    incorrectExample: '“Status 200 就是订单成功。”若正文是空结果或业务 code=FAILED，结论仍需收紧。',
  },
  {
    id: 'timing-size', prerequisiteConceptIds: ['http-response'], term: 'Timing 与 Size', english: 'Timing & Size',
    definition: 'Timing 记录请求在排队、连接、等待和下载等阶段耗费的时间，Size 记录传输数据量。它们帮助判断慢在哪里、响应是否异常膨胀，但不直接表达业务正确性。',
    why: '用户说“页面卡住”时，状态和正文可能最终都正确；耗时与大小能帮助团队判断是连接慢、服务计算慢还是返回内容过大。',
    problemSolved: '它解决“如何把一次请求的速度和传输规模变成可比较证据”的问题。',
    input: '输入是网络路径、服务处理、缓存命中、响应正文和浏览器加载行为。',
    output: '输出是毫秒、字节或 KB 等测量值，以及可以进一步拆分的阶段信息。',
    systemPosition: 'Timing/Size 属于 HTTP 交换的观测元数据，位于响应传输和性能判断之间。',
    process: ['浏览器记录排队、连接、等待和下载等时间段。', '它统计响应头、正文和缓存带来的传输大小。', '团队用相同条件重复测量并比较分位数。', '再把性能变化与状态和业务结果分开解释。'],
    owner: '浏览器、网关、后端和性能平台共同产出测量；产品经理负责把体验阈值与业务影响联系起来。',
    notResponsibleFor: '耗时短不代表业务正确，响应小也不代表信息完整；单次测量不能代表所有网络环境。',
    compareWith: 'Timing 是时间维度，Size 是传输量维度；二者都不同于 Status，不能用来替代结果类别。',
    evidence: ['网络面板显示总耗时和响应大小。', '多次重复请求的 P50/P95 对比。', '改变 Payload 或筛选条件后大小和耗时变化。'],
    failureModes: ['只看总耗时而不拆阶段。', '把缓存命中造成的快速结果当成服务端始终健康。', '响应体异常变大却没有告警。'],
    pmUse: '在性能验收中同时记录状态、关键字段、Timing 和 Size，并说明网络条件与样本范围。',
    correctExample: '“同一 POST 请求返回 200，但 P95 Timing 从 180ms 升至 2.4s，Size 不变；这支持处理耗时变长的假设，不直接证明价格计算错误。”',
    incorrectExample: '“响应只有 20KB，所以内容一定完整且正确。”大小只能说明传输了多少，不说明业务语义。',
  },
]

const diagram: DailyCourse['diagram'] = {
  title: '一次 HTTP 交换的证据链',
  caption: '请求描述意图，响应给出结果，状态、正文、耗时和大小要一起读。',
  nodes: [
    { id: 'request', label: 'Request', description: 'Method、URL、Header、Cookie、Query、Payload。', input: '用户动作与页面状态', output: '结构化请求', owner: '浏览器与前端', evidence: '请求面板' },
    { id: 'route', label: 'Route & Validate', description: '服务端路由、鉴权、参数校验和业务处理。', input: '请求上下文', output: '处理结果', owner: '网关与后端', evidence: '服务日志/错误码' },
    { id: 'response', label: 'Response 结果', description: 'Status、Header、Response 正文。', input: '服务端处理结果', output: '客户端可消费结果', owner: '后端服务', evidence: '响应面板' },
    { id: 'measure', label: 'Timing / Size', description: '记录交换的时间和传输规模。', input: '网络与序列化过程', output: '性能测量', owner: '浏览器与平台', evidence: '耗时与字节数' },
  ],
  branches: [
    { from: 'request', to: 'route', label: '发送并到达', kind: 'normal' },
    { from: 'route', to: 'response', label: '生成响应', kind: 'normal' },
    { from: 'response', to: 'measure', label: '记录传输', kind: 'normal' },
    { from: 'request', to: 'route', label: '格式/鉴权拒绝', kind: 'failure' },
    { from: 'route', to: 'response', label: '超时/服务错误', kind: 'failure' },
  ],
  evidenceNotes: ['请求存在只证明客户端发送了意图。', 'Status 与 Response 要联合阅读，200 不自动等于业务成功。', 'Timing/Size 说明性能与规模，不承担业务正确性证明。'],
}

const demonstration: DailyCourse['demonstration'] = {
  title: '教师示范：为什么“预览价格不对”不能只看页面',
  businessProblem: '用户在结算页点击“预览价格”后看到金额异常。产品经理需要判断是请求参数、会话、服务端规则还是页面格式化造成的。',
  finalConclusion: '请求确实发送并到达服务端，Payload 中 quantity 被序列化为字符串，服务端返回 422 并说明类型错误；页面金额异常是错误处理缺口，不是一次成功计算。',
  conclusionLimit: '这条结论只覆盖本次教学请求和响应；仍需在真实环境核对后端日志、接口契约和其他客户端。',
  steps: [
    { title: '记录用户动作', action: '固定商品、数量和点击时间，不先改页面文案。', reason: '需要让后续请求与页面现象一一对应。', evidence: '得到一条可复现的预览动作。', proves: '问题有明确触发点。', limitation: '还不知道请求是否生成。' },
    { title: '读取 Method 与 URL', action: '查看请求是 POST /checkout/preview。', reason: '确认动作和资源路由符合预期。', evidence: '请求方法与 URL 正确。', proves: '前端选择了预览路由。', limitation: '不能证明 Payload 类型正确。' },
    { title: '检查 Header 与 Cookie', action: '核对 Content-Type、实验分组和会话 Cookie 是否存在。', reason: '上下文缺失会让服务端走不同分支。', evidence: 'Content-Type 为 application/json，Cookie 存在。', proves: '请求携带基本上下文。', limitation: 'Cookie 存在不等于会话仍有效。' },
    { title: '检查 Query 与 Payload', action: '展开 ?currency=CNY 和 JSON 请求体，比较 quantity 的类型。', reason: '金额计算依赖数量和币种，类型错误可能在服务端校验阶段暴露。', evidence: 'quantity 为字符串“2”，不是数字 2。', proves: '请求数据与契约不一致。', limitation: '还要看服务端实际返回。' },
    { title: '读 Status 与 Response', action: '查看返回的 422 和字段错误。', reason: '状态和正文共同说明服务端拒绝了输入。', evidence: 'Status 422，Response code=INVALID_TYPE。', proves: '请求到达并被校验拒绝。', limitation: '不能证明数据库或价格规则本身损坏。' },
    { title: '对照 Timing 与 Size', action: '记录 96ms 和 416B，并与正常样例比较。', reason: '测量帮助排除“慢导致空白”，但不替代业务判断。', evidence: '响应很快且体积小，符合错误响应特征。', proves: '异常不是等待很久未返回。', limitation: '单次测量不能代表性能基线。' },
    { title: '写出恢复建议', action: '把字段类型问题交给前后端共同修复，并要求页面展示可理解错误。', reason: '输入契约和错误体验都需要闭环。', evidence: '记录包含请求、响应、页面和下一步。', proves: '问题可以被复现和分工。', limitation: '提交工单不等于修复完成。' },
  ],
}

const guidedLab: DailyCourse['guidedLab'] = {
  title: '教学 HTTP 观察台：逐字段对照一次请求和响应',
  goal: '在本地模拟中切换 Method、Query、Cookie 和 Payload，观察 Status、Response、Timing 与 Size 的联动，并写出不能越界的结论。',
  safety: '这是教学模拟，不会发送真实订单或账号数据；输入只在当前页面保存，所有响应均为固定教学样例。',
  conceptIds: ['http-message', 'http-request', 'http-response', 'method-url', 'header-cookie-query', 'payload', 'status-response', 'timing-size'],
  predictionPrompt: '如果把 quantity 从数字改成字符串，预计会出现什么 Status 和 Response？请先写出判断依据。',
  steps: [
    { title: '选择请求动作', action: '在左侧请求台选择 POST /checkout/preview。', observe: '请求摘要显示 Method 与 URL。', explanation: '方法表达动作意图，URL 定位资源。', proves: '你能识别请求的首要路由线索。', cannotProve: '不证明服务端已经接受动作。' },
    { title: '检查上下文', action: '打开 Header/Cookie/Query 区，保留 Content-Type、教学会话和 currency=CNY。', observe: '上下文字段出现在请求记录中。', explanation: '不同字段位置承担不同语义与生命周期。', proves: '你能按位置读取请求上下文。', cannotProve: '字段存在不代表服务端信任。' },
    { title: '提交正确 Payload', action: '发送 quantity=2 的数字版本。', observe: '返回 200、预览金额和约 120ms 的教学响应。', explanation: '服务端按契约解析并返回结果。', proves: '请求/响应闭环在模拟中完成。', cannotProve: '不证明真实库存或订单已改变。' },
    { title: '制造类型错误', action: '把 quantity 改成字符串“2”后再次发送。', observe: '返回 422、INVALID_TYPE，Size 变小。', explanation: '服务端校验拒绝了与契约不符的输入。', proves: '状态与正文能揭示字段级错误。', cannotProve: '不证明所有客户端都存在同样问题。' },
    { title: '比较性能测量', action: '切换“慢响应”教学开关，观察 Timing 变化而不是只看 Status。', observe: 'Status 仍为 200，但 Timing 显著增加。', explanation: '性能测量和业务结果是不同维度。', proves: '你能把慢与失败分开。', cannotProve: '单次测量不能形成生产性能结论。' },
  ],
  recordPrompts: [
    '记录正确请求的 Method、URL、关键上下文和 Payload。',
    '记录类型错误的 Status、Response code 与 Size。',
    '解释 Cookie 存在为什么仍不能证明权限通过。',
    '比较正常与慢响应的 Timing，并写出结论边界。',
  ],
  comparePrompt: '比较“200 + 预览金额”“422 + 字段错误”“200 + 慢响应”三种结果，分别说明它们证明什么、还缺什么。',
  passCriteria: ['能准确把请求字段与响应字段分开。', '能联合 Status/Response 解释错误类型。', '能用 Timing/Size 说明性能现象而不越界成业务结论。'],
}

const independentLab: DailyCourse['independentLab'] = {
  title: '独立变式：优惠券预览请求验收',
  scenario: '结算页新增 coupon 查询参数和可选优惠券 Payload。部分用户看到价格不变，研发怀疑是 Cookie、Query 或请求体没有被正确携带。',
  conceptIds: ['http-message', 'http-request', 'http-response', 'method-url', 'header-cookie-query', 'payload', 'status-response', 'timing-size'],
  changedConditions: ['把 coupon 从 Query 移到 JSON Payload。', '移除教学会话 Cookie，模拟未登录用户。', '让响应保持 200，但正文 code 改为 COUPON_IGNORED。', '打开慢响应开关，观察 Timing 与 Size 的独立变化。'],
  task: '先预测每个变式会影响请求哪一部分，再逐一发送并提交请求/响应对照记录。',
  predictionPrompt: '如果 Status 保持 200 但 Response code=COUPON_IGNORED，你会把它写成“优惠券成功”还是“业务被忽略”？请说明证据。',
  evidenceRequirements: ['至少三组不同请求的 Method/URL/Context/Payload 记录。', '每组包含 Status、Response、Timing、Size。', '说明页面展示、协议结果和业务结论之间的边界。'],
  passCriteria: ['能指出 Query、Cookie 与 Payload 的位置变化。', '不把 200 或页面金额单独当成优惠生效。', '记录能让同事按相同条件重放。'],
  remediation: { label: '回到 Status 与 Response 概念卡', sectionId: 'concepts', anchor: '#concept-status-response' },
}

const exercises: DailyCourse['exercises'] = [
  {
    id: 'w1d3-exercise-fields', kind: 'single-choice', categories: ['概念与边界'], conceptIds: ['header-cookie-query', 'payload'],
    prompt: '下面哪项最准确地描述 Cookie 与 Query 的区别？', hint: '一个与浏览器会话和域路径有关，一个直接出现在 URL 中。', options: [
      { label: 'Cookie 是浏览器保存并按规则附带的会话片段，Query 是 URL 中的资源条件', rationale: '二者位置、生命周期和隐私边界不同。', couldBeTrueWhen: '描述登录会话与筛选参数时成立。' },
      { label: 'Cookie 是响应状态码，Query 是请求体 JSON', rationale: '状态码属于响应，JSON 请求体属于 Payload。', couldBeTrueWhen: '只有在讨论其他字段时才相关。' },
      { label: 'Cookie 与 Query 都是服务器地址的一部分', rationale: '服务器地址属于寻址层，二者属于 HTTP 请求上下文。', couldBeTrueWhen: '都可能影响服务端处理，但不属于地址本身。' },
      { label: 'Query 只能用于登录，Cookie 只能用于分页', rationale: '实际语义由应用契约决定，不能这样固定。', couldBeTrueWhen: '某个特定产品恰好如此约定时才可能成立。' },
    ], answerIndex: 0, referenceAnswer: 'Cookie 是浏览器按域和路径规则保存、附带的会话片段；Query 直接位于 URL 中，通常表达筛选或定位条件。', reasoning: ['先看字段出现的位置。', '再看浏览器保存与生命周期差异。', '最后回到应用契约，不把用途绝对化。'], rubric: ['能说清位置与生命周期', '不把上下文混成地址'], commonErrors: [{ error: '把 Cookie 当状态码', reason: '混淆请求上下文和响应分类。' }], remediation: { label: '回看 Header、Cookie 与 Query', sectionId: 'concepts', anchor: '#concept-header-cookie-query' },
  },
  {
    id: 'w1d3-exercise-status', kind: 'single-choice', categories: ['证据判断'], conceptIds: ['status-response'],
    prompt: '请求返回 Status 200，Response 中 code=COUPON_IGNORED，页面显示原价。最稳妥的结论是什么？', hint: '联合状态码和正文，不只看 200。', options: [
      { label: 'HTTP 交换成功返回，但优惠券业务没有生效', rationale: '200 说明协议层返回，正文明确表达业务被忽略。', couldBeTrueWhen: '正文 code 由服务契约定义且页面与之对应时成立。' },
      { label: '优惠券已经成功写入数据库', rationale: '没有写入或订单证据，不能这样判断。', couldBeTrueWhen: '只有额外的持久化审计证据才能支持。' },
      { label: '请求一定没有发送', rationale: '有响应就说明请求至少到达了可返回结果的层。', couldBeTrueWhen: '网络完全失败时才可能没有响应。' },
      { label: '200 永远代表所有业务成功', rationale: '业务 code 可以进一步表达失败或忽略。', couldBeTrueWhen: '某个严格契约明确 200 只用于成功时才成立。' },
    ], answerIndex: 0, referenceAnswer: '最稳妥的结论是协议交换返回成功，但正文表明优惠券未生效；还需要业务持久化证据才能判断是否写入。', reasoning: ['读取 Status 的协议层含义。', '再读取 Response code 的业务层提示。', '最后写出仍缺失的持久化证据。'], rubric: ['联合两类响应证据', '保持业务边界'], commonErrors: [{ error: '看到 200 就写成功', reason: '忽略正文中的业务 code。' }], remediation: { label: '回看 Status 与 Response', sectionId: 'concepts', anchor: '#concept-status-response' },
  },
  {
    id: 'w1d3-exercise-payload', kind: 'open', categories: ['机制推演', '工作场景'], conceptIds: ['method-url', 'payload'],
    prompt: '请解释 quantity=2 与 quantity="2" 为什么可能得到不同响应，并写出产品经理应要求研发补充的证据。', hint: '从序列化、服务端契约和状态/正文三层回答。', referenceAnswer: '前端序列化后数据类型不同，服务端 schema 可能拒绝字符串版本；应补充请求 Payload、Content-Type、Status、Response 错误字段和服务端校验日志。', reasoning: ['比较请求体的真实类型。', '再看服务端契约与校验。', '用响应与日志确认拒绝位置。'], rubric: ['说明类型差异', '提出可验证证据'], commonErrors: [{ error: '认为页面输入相同就代表请求相同', reason: '忽略了序列化和请求体格式。' }], remediation: { label: '回看 Payload 概念卡', sectionId: 'concepts', anchor: '#concept-payload' },
  },
  {
    id: 'w1d3-exercise-timing', kind: 'open', categories: ['证据判断', '综合变式'], conceptIds: ['timing-size', 'http-response'],
    prompt: '同一请求两次都返回 200：第一次 180ms/2KB，第二次 2.4s/2KB。你能支持什么结论，又不能支持什么结论？', hint: '把性能测量与业务正确性分开。', referenceAnswer: '可以支持第二次请求耗时明显增加、传输大小未变，需继续拆分等待/处理阶段；不能仅凭这两次测量判断价格、权限或数据正确性。', reasoning: ['比较同一请求的时间与大小。', '指出性能异常假设。', '明确没有业务正文或持久化证据。'], rubric: ['正确解释测量', '不越界到业务结论'], commonErrors: [{ error: '把慢写成失败', reason: 'Status 和 Response 仍然是 200，慢与错误需分开。' }], remediation: { label: '回看 Timing 与 Size', sectionId: 'concepts', anchor: '#concept-timing-size' },
  },
  {
    id: 'w1d3-exercise-transfer', kind: 'open', categories: ['综合变式'], conceptIds: ['http-request', 'http-response', 'header-cookie-query', 'status-response'],
    prompt: '为“移动端用户看不到优惠券”设计一组最小 HTTP 对照实验，至少改变 Cookie、Query 或 Payload 中的一项。', hint: '先固定请求，再只改变一个变量。', referenceAnswer: '固定 Method/URL 和商品，分别保留或移除会话 Cookie，再固定 Cookie 比较 coupon Query；记录请求字段、Status、Response code、Timing 和页面结果，避免同时修改多个变量。', reasoning: ['固定基线减少混杂变量。', '每次只改变一个请求上下文。', '联合协议与页面证据判断差异。'], rubric: ['实验变量可控', '记录字段完整', '说明业务边界'], commonErrors: [{ error: '一次改 Cookie、Query、Payload', reason: '无法判断是哪一个变量造成结果变化。' }], remediation: { label: '回到引导实验记录', sectionId: 'guided-lab', anchor: '#w1d3-guided-lab' },
  },
]

const deliverable: DailyCourse['deliverable'] = {
  title: 'HTTP 观察与交接记录', conceptIds: ['http-message', 'http-request', 'http-response', 'method-url', 'header-cookie-query', 'payload', 'status-response', 'timing-size'],
  purpose: '把一次页面动作还原为请求与响应证据，帮助研发定位字段、状态、性能和业务解释之间的断点。',
  whenToUse: '接口验收、页面错误、登录状态异常、优惠计算和性能回归时使用。',
  audience: '前端、后端、测试、网关/平台和需要做范围判断的产品经理。',
  fields: [
    { name: '请求摘要', meaning: '记录 Method、Request URL 与触发动作。', source: '浏览器请求面板和复现步骤。' },
    { name: '请求上下文', meaning: '列出关键 Header、Cookie、Query 与 Payload。', source: '请求详情，敏感值需脱敏。' },
    { name: '响应结果', meaning: '记录 Status、Response code/正文与页面表现。', source: '响应详情和页面截图或文字。' },
    { name: '性能测量', meaning: '记录 Timing、Size 与网络条件。', source: '浏览器面板或教学 HTTP 台。' },
    { name: '证据边界', meaning: '说明已证明、未证明和下一步。', source: '把协议证据与业务审计分开。' },
  ],
  badExample: '优惠券不生效，接口应该有问题。',
  badReasons: ['没有 Method、URL 和输入，研发无法重放。', '没有状态和正文，无法区分校验、权限或业务忽略。', '把页面现象直接归因于接口。'],
  revisionSteps: ['固定动作和请求目标，记录关键上下文。', '补充 Status、Response、Timing、Size 和页面表现。', '写出协议证据、业务结论与尚未验证的持久化事实。'],
  goodExample: '【HTTP 观察记录】\n请求摘要：点击优惠券预览，POST /checkout/preview?currency=CNY\n请求上下文：Content-Type=application/json；教学 Cookie 已脱敏\nPayload：quantity="2"\n响应结果：422 / INVALID_TYPE；页面提示“数量格式错误”\n性能测量：Timing 96ms / Size 416B\n证据边界：请求已到达并被字段校验拒绝；不能证明库存或价格数据库异常\n下一步：核对前端序列化与后端 schema，并补做数字 2 的对照。',
  guidedPrompts: ['这次动作对应哪一个 Method 和 Request URL？', '哪些 Header、Cookie、Query、Payload 会改变服务端判断？', 'Status 和 Response 分别告诉你什么？', 'Timing/Size 有什么变化，不能支持什么业务结论？'],
  blankTemplate: '【触发动作】\n【Method + Request URL】\n【Header/Cookie/Query】\n【Payload】\n【Status + Response】\n【Timing + Size】\n【页面表现】\n【已证明】\n【未证明】\n【下一步】\n',
  standardTemplate: '【请求摘要】触发动作；Method + Request URL\n【请求上下文】Header/Cookie/Query：\n【Payload】\n【响应结果】Status + Response：\n【性能测量】Timing + Size：\n【页面表现】\n【证据边界】已证明：；未证明：\n【下一步】\n',
  checklist: ['Method 与 Request URL 已固定并能被重放。', '关键 Header/Cookie/Query/Payload 已记录且完成脱敏。', 'Status 与 Response 正文/错误码同时出现。', 'Timing 与 Size 带有测量条件。', '文档区分协议结果、页面表现和业务持久化证据。'],
}

const memory: DailyCourse['memory'] = {
  conceptIds: ['http-message', 'http-request', 'http-response', 'method-url', 'header-cookie-query', 'payload', 'status-response', 'timing-size'],
  anchors: ['请求表达客户端意图，响应表达服务端回报。', 'Method/URL 定位动作，Header/Cookie/Query/Payload 携带上下文和输入。', 'Status、Response、Timing、Size 要联合阅读，任何单项都不能独立授予业务成功。', 'HTTP 观察记录必须脱敏并写出未证明事项。'],
  closedBookPrompt: '闭卷解释：从一次按钮点击开始，完整说出 HTTP 请求如何带着 Method、URL、Header、Cookie、Query 和 Payload 到达服务端，再如何通过 Status、Response、Timing 和 Size返回；至少写出两条证据边界。',
  microOperation: '在教学 HTTP 台中先发送正确 Payload，再制造一次类型错误，记录请求与响应的差异。',
  unresolvedPrompt: '哪一个请求字段或响应测量仍容易被你误判为业务事实？写出下一次复测要看的证据。',
  reviewStages: [
    { stage: 'D1', task: '不看笔记画出 Request/Response 双栏，并解释 200 仍可能业务失败。' },
    { stage: 'D3', task: '只改变 Cookie 或 Query 中一个变量，预测响应差异。' },
    { stage: 'D7', task: '从一条错误请求记录中找出字段、状态和页面表现的断点。' },
    { stage: 'D14', task: '比较 Timing 变慢与 Status 失败的不同证据。' },
    { stage: 'D30', task: '为一个新接口写完整 HTTP 观察与脱敏清单。' },
    { stage: 'D60', task: '把请求/响应证据迁移到新的产品动作和异常场景。' },
  ],
}

export const w1d3: DailyCourse = {
  id: 'W1D3', contentVersion: 'w1d3-http-day01-v2', week: 1, day: 3,
  title: 'HTTP 请求与响应',
  subtitle: '从 Method 到 Timing，读懂一次应用层交换',
  duration: { core: 30, standard: 45, extension: 45, full: 180 },
  coreConceptGroups, prerequisiteConceptIds: ['url', 'domain-name', 'dns', 'server-address', 'port', 'path-query'],
  learningPaths: {
    '30': { guidedStepIndices: [0, 1, 2, 3, 4], guidedRecordIndices: [0, 1, 2], exerciseCount: 3, deliverablePromptCount: 3, deliverableChecklistIndices: [0, 1, 2], deliverableMinimumContributionCharacters: 90 },
    '45': { guidedStepIndices: [0, 1, 2, 3, 4], guidedRecordIndices: [0, 1, 2, 3], exerciseCount: 5, deliverablePromptCount: 4, deliverableChecklistIndices: [0, 1, 2, 3, 4], deliverableMinimumContributionCharacters: 150 },
  },
  primaryGoal: '能把页面动作还原成 HTTP 请求与响应，并用字段、状态、正文、耗时和大小形成诚实的应用层证据。',
  scenario: { role: '你是负责结算体验验收的产品经理。', situation: '用户反馈优惠券没有生效，页面只显示“请求失败”，研发需要知道是请求没发、字段不对、服务端拒绝还是响应太慢。', question: '你如何读一次 HTTP 交换，既给出可执行判断，又不把 200 或页面提示写成业务成功？', stakes: '如果只看页面或只看状态码，团队可能错误修改前端、漏掉鉴权问题，或把未持久化的预览结果当成订单事实。' },
  objectives, prerequisites, concepts, diagram, demonstration, guidedLab, independentLab, exercises, deliverable, memory,
  nextLesson: { id: 'W1D4', title: 'API、后端与数据库', bridge: '今天你已经能读懂一次 HTTP 请求/响应及其证据边界。下一课把应用层消息放进更完整的系统职责中，区分 API、后端服务、数据库和真正的持久化结果。' },
}
