import type { DailyCourse } from './types'

const conceptIds = [
  'api-entry',
  'request-handler',
  'backend-service',
  'business-rule',
  'database-read-write',
  'persistence-boundary',
  'response-assembly',
] as const

export const w1d4: DailyCourse = {
  id: 'W1D4',
  contentVersion: 'w1d4-api-backend-db-day01-v1',
  week: 1,
  day: 4,
  title: 'API、后端与数据库如何处理一次请求',
  subtitle: '沿着“HTTP → API → 后端业务处理 → 数据库读写 → Response”，分清入口、规则、持久化与可证明的结果。',
  duration: { core: 30, standard: 45, extension: 38, full: 83 },
  coreConceptGroups: [
    {
      id: 'api-to-backend',
      title: '从 API 入口进入后端处理',
      conceptIds: ['api-entry', 'request-handler', 'backend-service'],
      summary: 'API 入口把 HTTP 请求交给匹配的请求处理器，处理器再调用后端服务完成这次业务用例。',
      boundary: '找到 API 入口只说明请求进入了某条处理路径，不能证明规则通过、数据库写入或用户目标完成。',
    },
    {
      id: 'rules-and-data',
      title: '业务规则决定是否读写数据',
      conceptIds: ['business-rule', 'database-read-write'],
      summary: '后端服务先依据当前输入和已有数据执行规则，再决定查询、创建或更新哪一条教学模拟记录。',
      boundary: '执行了读操作不代表发生写入；准备了写入内容也不代表持久化已经成功。',
    },
    {
      id: 'persistence-and-response',
      title: '持久化结果与 Response 分开判断',
      conceptIds: ['persistence-boundary', 'response-assembly'],
      summary: '数据库确认写入后才形成持久化结果，后端再根据真实处理结果组装 Response，交还给客户端。',
      boundary: '本课只验证教学模拟中的处理链；模拟记录与模拟 Response 都不是生产系统证据。',
    },
  ],
  prerequisiteConceptIds: ['http-request', 'http-response', 'method-url', 'status-response'],
  learningPaths: {
    '30': {
      guidedStepIndices: [0, 1, 2, 3, 4, 5],
      guidedRecordIndices: [0, 1, 2],
      exerciseCount: 3,
      deliverablePromptCount: 3,
      deliverableChecklistIndices: [0, 1, 2, 3],
      deliverableMinimumContributionCharacters: 60,
    },
    '45': {
      guidedStepIndices: [0, 1, 2, 3, 4, 5],
      guidedRecordIndices: [0, 1, 2, 3],
      exerciseCount: 4,
      deliverablePromptCount: 5,
      deliverableChecklistIndices: [0, 1, 2, 3, 4, 5],
      deliverableMinimumContributionCharacters: 90,
    },
  },
  primaryGoal: '能按真实职责顺序解释一次请求如何从 HTTP 进入 API 与后端，经过业务规则和数据库读写，再形成有限且可核验的 Response。',
  scenario: {
    role: '你是阅读产品的产品经理，正在验收“保存阅读进度”功能。',
    situation: '用户把一本 36 页的材料读到第 12 页，页面随后提示“进度已保存”。研发希望你说明这次请求在 API、后端和数据库中分别发生了什么。',
    question: '怎样确认请求进入了正确 API、业务规则允许保存、数据库记录真的改变，并让 Response 诚实表达结果？',
    stakes: '如果把页面提示、API 命中或准备写入误当成持久化成功，刷新后的进度丢失会被错误归因，交接也无法指出缺少哪一层证据。',
  },
  objectives: [
    {
      id: 'trace-api-entry',
      text: '能说明 API 入口、请求处理器和后端服务的分工，并按顺序指出它们的输入与输出。',
      evidence: '在七章练习和最终链路说明中，把 HTTP 请求接到正确 API，再写出处理器调用的业务用例。',
    },
    {
      id: 'explain-business-rule',
      text: '能解释业务规则为何必须在后端执行，以及规则通过与拒绝怎样改变后续数据库动作。',
      evidence: '完成合法页码与越界页码的教学模拟对照，记录哪条路径会写入、哪条路径必须跳过写入。',
    },
    {
      id: 'separate-write-persistence',
      text: '能区分计划写入、数据库执行与持久化确认，不用“已经调用保存”替代记录变化证据。',
      evidence: '对照教学数据库写入成功与写入失败，写出运行前记录、运行后记录和有限结论。',
    },
    {
      id: 'write-processing-chain',
      text: '能提交一份研发可复核的“请求处理链路说明”，明确每层职责、证据与未证明事项。',
      evidence: '成果同时包含 HTTP 输入、API 入口、后端规则、数据库读写、Response、页面反馈边界与下一步。',
    },
  ],
  prerequisites: [
    {
      id: 'w1d4-http-exchange',
      conceptIds: ['http-request', 'http-response'],
      prompt: '你能把 HTTP Request 与 HTTP Response 分开，并说明请求表达客户端意图、响应表达服务端回报吗？',
      passDescription: '能从一次保存动作中指出请求在前、响应在后，且两者都不自动等于数据库持久化成功。',
      remediationLabel: '补看：Request 与 Response',
      remediationTarget: '#/lesson/W1D3',
      remediation: {
        purpose: '本课从 HTTP 消息继续向服务端内部推进，先确保你不会把请求字段课与后端处理职责混在一起。',
        steps: ['回到 W1D3 找到 Request 与 Response 的定义。', '用一句话写出两者的先后关系。', '补充“Response 出现仍不自动证明什么”。'],
        successCheck: '你能闭卷说出 Request 是输入证据、Response 是返回证据，并主动保留数据库事实边界。',
      },
    },
    {
      id: 'w1d4-target-and-result',
      conceptIds: ['method-url', 'status-response'],
      prompt: '你能从 Method 与 URL 找到请求目标，并联合 Status 与 Response 读取服务端回报，而不是只看页面提示吗？',
      passDescription: '能指出 POST /api/reading-progress 是请求入口线索，而具体保存结果仍要继续看后端和数据层证据。',
      remediationLabel: '补看：目标与返回结果',
      remediationTarget: '#/lesson/W1D3',
      remediation: {
        purpose: 'API 会接住某个方法与路径，但入口匹配和最终业务结果属于不同阶段。',
        steps: ['写下方法与路径共同回答的两个问题。', '再写下 Status 与 Response 各提供的结果线索。', '加一句“这些字段还没有直接展示哪条数据库记录”。'],
        successCheck: '你能从 HTTP 目标走到服务端回报，同时不跳过 API、规则和数据库处理。',
      },
    },
  ],
  concepts: [
    {
      id: 'api-entry',
      prerequisiteConceptIds: ['method-url'],
      term: 'API 入口',
      english: 'API Entry',
      definition: 'API 入口是后端对外暴露的一条可调用边界，通常由方法与路径共同匹配。它接收结构化请求，并把请求交给对应的服务端处理路径。',
      why: '页面按钮不会直接调用数据库。API 入口把客户端能发送的 HTTP 消息与后端内部实现隔开，让双方通过稳定的输入输出边界协作。',
      problemSolved: '它解决客户端如何找到一个明确服务能力，以及后端如何把不同请求分流到正确处理路径的问题。',
      input: '输入是已经到达服务端的 HTTP 请求，包括方法、路径和这次业务操作需要的数据。',
      output: '输出是匹配到的请求处理器，或一条明确的入口不匹配结果；它还不是最终业务 Response。',
      systemPosition: '位于 HTTP 到达服务端之后、后端业务处理之前，是外部消息进入内部职责链的第一道应用边界。',
      process: ['服务端读取请求的方法与路径。', '路由表寻找与该组合匹配的 API 入口。', '入口把解析后的输入交给指定请求处理器。'],
      owner: '后端团队定义和维护 API 入口，前端按约定调用，产品经理确认入口表达的用户动作与业务目标一致。',
      notResponsibleFor: 'API 入口不直接证明业务规则通过，也不代表数据库已经读写或 Response 已经送达页面。',
      compareWith: 'API 入口不是整个后端；它像接待窗口，只负责识别请求并交给正确内部流程，真正裁决和持久化发生在后面。',
      evidence: ['教学模拟中可以看到方法与路径匹配到“保存阅读进度”入口。', '入口未匹配时处理器和数据库阶段不会被执行。'],
      failureModes: ['方法或路径没有匹配到任何入口。', '入口把请求交给了错误的处理器。'],
      pmUse: '评审需求时确认每个用户动作进入哪个 API 能力，并把“入口是否匹配”与“业务是否成功”写成不同验收点。',
      correctExample: '教学模拟显示 POST /api/reading-progress 命中保存入口，因此可以继续观察处理器；这还不能证明第 12 页已经保存。',
      incorrectExample: '“API 调通了，所以数据已经落库。”入口可用只说明路径被接住，后续规则和数据库仍可能失败。',
    },
    {
      id: 'request-handler',
      prerequisiteConceptIds: ['api-entry'],
      term: '请求处理器',
      english: 'Request Handler',
      definition: '请求处理器是 API 入口后负责组织一次请求处理的代码单元：读取已解析输入、调用对应后端服务，并把处理结果交给 Response 组装阶段。',
      why: '如果入口、业务规则和数据库访问都挤在一起，责任难以定位。处理器用清楚的调用顺序把外部请求接到内部业务用例。',
      problemSolved: '它解决一次 API 调用由谁启动业务处理、如何传递输入，以及如何收集内部结果的问题。',
      input: '输入是 API 入口解析后的页码、材料标识等业务参数，以及本次请求的处理上下文。',
      output: '输出是后端服务返回的业务结果或错误，供 Response 组装器转换为客户端可读回报。',
      systemPosition: '位于 API 入口与后端业务服务之间，负责协调调用，但不拥有最终业务规则或数据持久化。',
      process: ['接收入口交来的结构化输入。', '调用保存阅读进度的后端服务。', '接收服务结果并交给 Response 组装阶段。'],
      owner: '后端应用层维护请求处理器，产品经理可通过链路说明确认用户动作是否进入正确业务用例。',
      notResponsibleFor: '处理器不应自行假设记录已写入，也不应绕过业务服务直接把客户端输入当成数据库事实。',
      compareWith: 'API 入口负责匹配，处理器负责协调，后端服务负责业务用例；三个角色连续但职责不同。',
      evidence: ['教学模拟阶段日志显示处理器已启动指定服务。', '处理器收到的是规则拒绝或数据库结果，而不是页面最终呈现。'],
      failureModes: ['入口命中但处理器没有调用正确服务。', '处理器忽略服务错误并误组装成功结果。'],
      pmUse: '排查时询问请求是否进入了正确 handler、handler 调用了哪个业务用例，避免把所有服务端问题统称为“接口挂了”。',
      correctExample: '教学模拟显示 SaveReadingProgressHandler 调用阅读进度服务；这证明调用链向后推进，不证明服务已经持久化。',
      incorrectExample: '“处理器执行结束就代表保存成功。”处理器结束时可能拿到规则拒绝或写入失败。',
    },
    {
      id: 'backend-service',
      prerequisiteConceptIds: ['request-handler'],
      term: '后端业务服务',
      english: 'Backend Service',
      definition: '后端业务服务把一个用户目标组织成可信的处理过程，协调业务规则、已有数据读取、必要写入和结果返回。',
      why: '用户说“保存进度”只描述目标，真正处理还要判断页码是否合法、当前记录是什么、是否允许更新以及写入结果如何。',
      problemSolved: '它解决如何把外部请求转换为受业务规则约束、可持久化并能明确返回结果的一次业务用例。',
      input: '输入是请求处理器交来的结构化参数，以及完成判断所需的已有教学模拟数据。',
      output: '输出是成功、规则拒绝或数据操作失败等业务结果，并携带 Response 组装所需的信息。',
      systemPosition: '位于请求处理器之后，连接业务规则与数据访问，是后端职责链的业务核心。',
      process: ['确认本次业务用例所需输入。', '读取必要记录并执行规则。', '规则允许时发起写入。', '根据写入结果返回有限业务结果。'],
      owner: '后端业务团队维护服务流程，产品经理负责把规则、成功标准和失败体验定义为可验收条件。',
      notResponsibleFor: '业务服务不直接呈现页面，也不能把数据库尚未确认的写入意图包装成持久化成功。',
      compareWith: '处理器负责接住一次调用，业务服务负责完成一个业务用例；数据库只负责按指令读写数据，不替代业务裁决。',
      evidence: ['教学模拟链路显示服务依次调用规则检查与数据读写。', '服务结果会区分规则拒绝和写入失败。'],
      failureModes: ['业务服务遗漏必要规则。', '数据操作失败后仍返回成功结果。'],
      pmUse: '写需求时把“保存”拆成输入、规则、读取、写入和失败结果，让后端服务职责可讨论、可测试。',
      correctExample: '阅读进度服务先核对页码，再读取旧记录，规则允许后更新并根据写入结果返回。',
      incorrectExample: '“后端就是数据库。”后端服务负责业务过程，数据库只承担数据存取。',
    },
    {
      id: 'business-rule',
      prerequisiteConceptIds: ['backend-service'],
      term: '业务规则',
      english: 'Business Rule',
      definition: '业务规则是后端对业务输入和当前事实执行的约束或决策，例如阅读页码必须大于零且不能超过材料总页数。',
      why: '客户端可以发出任意输入，后端必须独立判断哪些状态允许写入，避免无效数据变成长期业务事实。',
      problemSolved: '它解决什么输入在当前业务状态下可以被接受、拒绝或转换，以及拒绝后是否应跳过数据库写入的问题。',
      input: '输入是请求参数、已有记录和服务端掌握的材料总页数等可信业务事实。',
      output: '输出是规则通过或带明确原因的拒绝，并决定后续是否允许进入写入阶段。',
      systemPosition: '位于后端业务服务内部、数据库写入之前，是从外部意图走向持久化事实的裁决边界。',
      process: ['读取本次页码和材料总页数。', '检查页码范围与业务状态。', '通过则允许继续，拒绝则停止写入并返回原因。'],
      owner: '产品与业务共同定义规则，后端负责可信执行，测试负责覆盖边界输入和拒绝路径。',
      notResponsibleFor: '规则通过不等于数据库写入成功，也不证明 Response 已经被客户端正确展示。',
      compareWith: '业务规则不同于输入格式校验；格式正确只说明数据可读取，业务规则还要判断这个值在当前场景是否允许。',
      evidence: ['教学模拟中第 41 页超过 36 页时规则明确拒绝。', '拒绝路径显示数据库写入阶段被跳过。'],
      failureModes: ['遗漏边界值导致无效页码被接受。', '规则拒绝后仍错误执行写入。'],
      pmUse: '把规则写成输入条件、允许结果、拒绝原因和数据副作用四部分，便于研发与测试对齐。',
      correctExample: '教学模拟对 page=41、totalPages=36 返回规则拒绝，并保持原记录不变。',
      incorrectExample: '“页面输入框限制到 36，所以后端不用再判断。”客户端限制不能替代服务端规则。',
    },
    {
      id: 'database-read-write',
      prerequisiteConceptIds: ['business-rule'],
      term: '数据库读写',
      english: 'Database Read & Write',
      definition: '数据库读写是后端按业务需要查询现有记录，并在规则允许时创建或更新记录的操作；读和写是两类不同动作。',
      why: '保存进度通常要先知道旧值，再决定写入新值。只看到查询结果不能声称更新发生，只看到写入意图也不能声称记录已经变化。',
      problemSolved: '它解决后端如何取得当前业务事实，以及如何把经过规则允许的新状态交给数据存储的问题。',
      input: '读取输入是材料和用户的记录标识；写入输入是规则允许的新页码以及需要保存的记录字段。',
      output: '读取输出是当前记录或空结果；写入输出是成功确认或失败信息，以及可供后端判断的受影响记录。',
      systemPosition: '位于后端业务处理与持久化存储之间，是业务规则转化为数据操作的执行层。',
      process: ['按业务标识读取旧进度。', '业务服务结合旧值执行规则。', '规则通过后提交创建或更新。', '数据库返回写入结果。'],
      owner: '后端数据访问层发起读写，数据库系统执行并返回结果，产品经理关注字段含义、规则与可观察结果。',
      notResponsibleFor: '数据库不理解完整产品体验，也不自行决定什么业务输入应该被接受。',
      compareWith: '读取回答“现在是什么”，写入尝试改变“之后是什么”；两者不能用同一条日志或同一句“查库了”代替。',
      evidence: ['教学模拟分别展示运行前记录与运行后记录。', '写入失败时旧记录保持不变并返回失败结果。'],
      failureModes: ['读取了错误记录。', '写入目标字段错误或存储返回失败。'],
      pmUse: '验收保存类功能时把“读到什么”“准备写什么”“写后记录是什么”分三步记录。',
      correctExample: '教学模拟先读到 page=9，规则通过后写入 page=12，并显示更新后的模拟记录。',
      incorrectExample: '“查询到了旧进度，所以新进度已经保存。”读取没有改变记录。',
    },
    {
      id: 'persistence-boundary',
      prerequisiteConceptIds: ['database-read-write'],
      term: '持久化边界',
      english: 'Persistence Boundary',
      definition: '持久化边界是数据从后端内存中的计划或临时结果，变成数据库确认保存记录的分界；只有跨过这条边界才能声称本次存储已成立。',
      why: '代码可以算出新页码、准备写入对象甚至调用数据层，但任一步失败都可能让刷新后的记录仍是旧值。',
      problemSolved: '它解决什么时候可以把“准备保存”升级为“已经保存”，以及写入失败时结论必须退回哪一层的问题。',
      input: '输入是经过规则允许的写入内容，以及数据库执行这次写入所需的上下文。',
      output: '输出是数据库确认后的新记录或明确失败；失败时不能生成持久化成功结论。',
      systemPosition: '位于数据库写操作与后端成功结果之间，是本课最关键的证据边界。',
      process: ['后端提交写入内容。', '数据库执行并返回结果。', '后端只在确认成功后采用新记录。', '失败则保留旧事实并返回错误结果。'],
      owner: '数据库系统负责存储结果，后端负责正确解释写入返回并避免把失败包装成成功。',
      notResponsibleFor: '教学模拟的持久化成功只存在于本地课程状态，不代表任何真实服务或生产数据库发生变化。',
      compareWith: '业务规则通过是“允许写”，持久化确认是“已经写”；Response 成功还要以这条确认作为依据。',
      evidence: ['教学模拟记录在成功路径由 page=9 变为 page=12。', '写入失败路径保持 page=9 并标记未持久化。'],
      failureModes: ['数据库拒绝或无法完成写入。', '后端忽略失败并错误返回已保存。'],
      pmUse: '写保存类验收结论时明确证据是否已经越过持久化边界，不用页面提示代替数据结果。',
      correctExample: '模拟数据库返回 WRITE_CONFIRMED 且运行后记录为 page=12，因此只可说明本次教学模拟持久化成立。',
      incorrectExample: '“后端调用了 save，所以已经持久化。”函数被调用不等于数据库确认。',
    },
    {
      id: 'response-assembly',
      prerequisiteConceptIds: ['persistence-boundary', 'http-response'],
      term: 'Response 组装',
      english: 'Response Assembly',
      definition: 'Response 组装是后端把业务处理结果转换成 HTTP Response 的阶段，选择结果类别、业务信息和客户端需要的数据。',
      why: '客户端只能根据返回结果更新体验，因此 Response 必须忠实表达规则拒绝、写入失败或持久化成功，不能把不同结果都包装成同一句成功。',
      problemSolved: '它解决后端如何把内部处理结果转成稳定、可理解、可供客户端处理的外部回报。',
      input: '输入是业务服务产生的规则结果、数据库写入结果和允许返回的业务数据。',
      output: '输出是一条教学模拟 HTTP Response，包含有限结果和下一步所需的信息。',
      systemPosition: '位于后端业务处理之后、客户端页面更新之前，是服务端职责链的出口。',
      process: ['读取业务与持久化结果。', '选择与真实结果一致的返回类别。', '组装业务代码和允许返回的数据。', '把 Response 交回客户端。'],
      owner: '后端负责 Response 语义，前端负责把不同结果呈现成可恢复体验，产品经理负责定义用户可理解的结果。',
      notResponsibleFor: 'Response 已组装不等于客户端一定收到或页面一定正确展示，也不自动证明生产数据库状态。',
      compareWith: 'Response 是后端对处理结果的外部表达，数据库记录是持久化事实；两者应一致，但不能互相替代。',
      evidence: ['教学模拟会显示 PROGRESS_SAVED、PAGE_OUT_OF_RANGE 或 SAVE_UNAVAILABLE。', '每条模拟 Response 与规则和写入阶段结果对应。'],
      failureModes: ['写入失败却返回成功业务代码。', '规则拒绝没有提供可理解原因。'],
      pmUse: '评审接口时为成功、规则拒绝和系统失败分别定义 Response 与页面恢复动作。',
      correctExample: '教学模拟写入失败时组装 SAVE_UNAVAILABLE，并保留旧记录；结果与持久化证据一致。',
      incorrectExample: '“Response 是 200，所以数据库一定写入。”Response 必须与独立数据证据对照。',
    },
  ],
  diagram: {
    title: '请求处理链：从 HTTP 到持久化与 Response',
    caption: '按职责顺序读链路；异常分支会提前结束或改变后续数据动作。所有节点和记录均为教学模拟。',
    nodes: [
      { id: 'http', label: 'HTTP Request', description: '客户端提交保存阅读进度的意图。', input: '方法、路径、页码', output: '到达服务端的请求', owner: '客户端与 HTTP 层', evidence: '教学模拟请求摘要' },
      { id: 'api', label: 'API 入口', description: '匹配保存进度能力并选择处理器。', input: '方法与路径', output: '处理器调用', owner: '后端路由', evidence: '教学模拟入口命中记录' },
      { id: 'backend', label: '后端业务服务', description: '组织规则检查和数据操作。', input: '结构化业务参数', output: '业务处理结果', owner: '后端服务', evidence: '教学模拟阶段日志' },
      { id: 'rule', label: '业务规则', description: '判断页码是否在允许范围内。', input: '页码与材料总页数', output: '通过或拒绝', owner: '后端业务层', evidence: '教学模拟规则结果' },
      { id: 'database', label: '数据库读写', description: '读取旧记录并在允许时尝试更新。', input: '记录标识与新页码', output: '运行后记录或失败', owner: '数据访问层与数据库', evidence: '教学模拟前后记录' },
      { id: 'response', label: 'HTTP Response', description: '忠实表达规则与持久化结果。', input: '业务与数据结果', output: '客户端可处理的回报', owner: '后端响应层', evidence: '教学模拟 Response' },
    ],
    branches: [
      { from: 'http', to: 'api', label: '到达入口', kind: 'normal' },
      { from: 'api', to: 'backend', label: '交给处理器', kind: 'normal' },
      { from: 'backend', to: 'rule', label: '执行用例', kind: 'normal' },
      { from: 'rule', to: 'database', label: '规则通过才读写', kind: 'normal' },
      { from: 'database', to: 'response', label: '返回持久化结果', kind: 'normal' },
      { from: 'rule', to: 'response', label: '拒绝并跳过写入', kind: 'failure' },
      { from: 'database', to: 'response', label: '写入失败返回错误', kind: 'failure' },
    ],
    evidenceNotes: ['入口命中、规则通过、写入确认和 Response 是四层不同证据。', '业务规则拒绝时，数据库写入应明确显示“未执行”。', '模拟记录只证明课程内状态变化，不是任何真实生产记录。'],
  },
  demonstration: {
    title: '教师示范：把第 12 页保存成持久化记录',
    businessProblem: '用户已读到第 12 页；系统需要在页码合法时保存，并让返回结果与真实写入结果一致。',
    finalConclusion: '教学模拟中，请求命中 API、规则通过、数据库确认把 page 从 9 更新到 12，随后 Response 返回 PROGRESS_SAVED。',
    conclusionLimit: '这只能证明课程内模拟链路自洽，不证明真实服务器、生产数据库、跨设备同步或页面最终呈现。',
    steps: [
      { title: '固定 HTTP 输入', action: '记录教学模拟请求 POST /api/reading-progress，输入 documentId=guide-01、page=12。', reason: '链路必须从可复现的客户端意图开始。', evidence: '教学模拟请求摘要显示目标与业务输入。', proves: '本次模拟准备了一个明确请求。', limitation: '尚未证明 API 命中或后端执行。' },
      { title: '匹配 API 入口', action: '让路由匹配保存阅读进度入口并选择 SaveReadingProgressHandler。', reason: '入口负责把外部消息接到正确内部流程。', evidence: '教学模拟入口阶段显示 MATCHED。', proves: '请求进入了指定处理路径。', limitation: '尚未执行规则和数据库动作。' },
      { title: '启动后端服务', action: '处理器调用阅读进度业务服务，并传入材料与页码。', reason: '业务服务负责组织规则和数据操作。', evidence: '教学模拟处理阶段显示 SERVICE_STARTED。', proves: '正确业务用例开始处理。', limitation: '服务启动不等于业务成功。' },
      { title: '执行业务规则', action: '用 page=12 与 totalPages=36 检查页码范围。', reason: '外部输入必须先经过服务端业务裁决。', evidence: '教学模拟规则结果为 ALLOWED。', proves: '该页码在本次规则中允许继续。', limitation: '规则允许仍不等于写入成功。' },
      { title: '读取运行前旧记录', action: '读取教学模拟数据库中的现有 page=9 记录。', reason: '更新前先固定原始事实，才能比较写入结果。', evidence: '教学模拟运行前记录为 page=9。', proves: '模拟数据层返回了旧记录。', limitation: '读取没有改变持久化状态。' },
      { title: '提交写入并确认', action: '提交 page=12 更新，并等待教学数据库返回 WRITE_CONFIRMED。', reason: '只有数据库确认后才跨过持久化边界。', evidence: '教学模拟运行后记录为 page=12。', proves: '本次课程模拟中的记录已改变。', limitation: '不是任何真实生产数据库证据。' },
      { title: '组装 Response', action: '根据写入确认组装 PROGRESS_SAVED，并返回保存后的 page=12。', reason: 'Response 必须忠实表达业务与数据结果。', evidence: '教学模拟 Response 与运行后记录一致。', proves: '模拟服务端回报与模拟持久化结果对齐。', limitation: '不证明客户端已收到或页面展示正确。' },
    ],
  },
  guidedLab: {
    title: '教学请求处理台：对照允许、拒绝与写入失败',
    goal: '串起 HTTP → API → 后端业务处理 → 数据库读写 → Response，并比较三条路径在哪一层停止。',
    safety: '本地教学模拟；不发送真实请求，不连接真实服务器或数据库，不产生生产证据。',
    conceptIds: [...conceptIds],
    predictionPrompt: '先预测：合法页码、越界页码、教学数据库写入失败三种条件下，规则、数据库记录和 Response 各会怎样？',
    steps: [
      { title: '锁定请求与旧记录', action: '确认教学模拟请求目标、page 输入与运行前数据库记录。', observe: '请求摘要与旧记录分别显示，尚未运行任何后端阶段。', explanation: '把输入和原始事实分开，才能判断是哪一步改变了结果。', proves: '模拟起点可复现。', cannotProve: '真实请求已经发送。' },
      { title: '运行合法保存', action: '选择“合法页码 12/36”和“教学写入成功”，运行一次完整链路。', observe: 'API、处理器、规则、读取、写入、Response 依次完成。', explanation: '正常路径需要每一层都产生与职责一致的结果。', proves: '模拟正常链路能完整串起。', cannotProve: '真实服务实现相同。' },
      { title: '核对持久化边界', action: '比较教学模拟数据库运行前 page=9 与运行后 page=12。', observe: '只有 WRITE_CONFIRMED 路径显示运行后记录改变。', explanation: '记录前后差异把“准备写入”与“持久化确认”分开。', proves: '课程内模拟记录变化。', cannotProve: '生产数据库存在这条记录。' },
      { title: '运行规则拒绝', action: '改为越界页码 41/36，再运行并观察写入阶段。', observe: '规则拒绝，数据库写入显示“未执行”，Response 为 PAGE_OUT_OF_RANGE。', explanation: '业务规则在写入前终止不合法请求。', proves: '模拟拒绝路径没有改变记录。', cannotProve: '其他所有规则都正确。' },
      { title: '运行写入失败', action: '恢复合法页码，但选择“教学数据库写入失败”后运行。', observe: '规则通过、读取完成、写入失败，运行后记录仍为旧值，Response 为 SAVE_UNAVAILABLE。', explanation: '规则通过与持久化成功是两道不同门槛。', proves: '模拟能把数据失败传递到 Response。', cannotProve: '真实失败原因或影响范围。' },
      { title: '写出有限对照', action: '记录三条路径各自最后成功的阶段、数据库结果和 Response。', observe: '结论停在教学模拟证据范围，并明确下一步需要真实系统取证。', explanation: '同一功能的不同失败点必须产生不同交接结论。', proves: '学习者能按职责层解释模拟结果。', cannotProve: '已经掌握或完成生产验收。' },
    ],
    recordPrompts: ['记录合法路径中每一层的输入、动作与输出。', '记录规则拒绝时最后成功阶段和未执行的数据动作。', '记录写入失败时运行前后教学模拟数据库记录。', '比较三条教学模拟 Response 与各自内部结果是否一致。'],
    comparePrompt: '比较入口命中、规则通过、写入确认与 Response 四层证据，哪一层缺失时不能声称“已保存”？',
    passCriteria: ['至少运行合法路径与一种失败路径。', '每条请求、数据库记录和 Response 都标明教学模拟。', '能指出规则拒绝与写入失败的不同停止点。', '有限结论没有越过课程模拟范围。'],
  },
  independentLab: {
    title: '独立变式：定位保存链路在哪一层停止',
    scenario: '另一位同事只说“阅读进度没有保存”，并给出一条教学模拟 Response。你需要改变一个条件，自己推演规则、数据库与返回结果。',
    conceptIds: [...conceptIds],
    changedConditions: ['把请求改为页码超过总页数，验证业务规则拒绝且数据库记录不变。', '保持合法页码，但让教学数据库写入返回失败，验证 Response 不宣称保存成功。', '把运行前记录改为空记录，验证首次写入仍必须跨过同一持久化边界。'],
    task: '先预测每一层状态，再运行或按教学台记录结果，最后提交“看到／可以判断／不能判断／下一步”的有限结论。',
    predictionPrompt: '改变这个条件后，API、后端规则、数据库读写和 Response 中哪一层会首次出现不同？',
    evidenceRequirements: ['保留教学模拟请求输入、各处理阶段和 Response。', '对照运行前后教学模拟数据库记录或明确写入未执行。', '写出能证明与不能证明的边界。'],
    passCriteria: ['改变条件与原正常路径实质不同。', '预测先于结果记录。', '数据库结论引用前后记录或明确失败证据。', '没有把教学模拟写成生产事实。'],
    remediation: { label: '补学：持久化与返回边界', sectionId: 'concepts', anchor: '#concept-persistence-boundary' },
  },
  exercises: [
    {
      id: 'w1d4-api-boundary',
      kind: 'single-choice',
      categories: ['概念与边界'],
      conceptIds: ['api-entry', 'request-handler', 'backend-service'],
      prompt: '教学模拟显示 POST /api/reading-progress 已匹配 API 入口。此时最稳妥的结论是什么？',
      hint: '入口只负责把外部请求接入内部处理。',
      options: [
        { label: '请求进入了指定处理路径，后续规则与数据结果仍待观察', rationale: '入口命中只把请求交给处理器，尚未形成业务与持久化结果。', couldBeTrueWhen: '教学模拟路由阶段明确显示 MATCHED。' },
        { label: '阅读进度已经写入数据库', rationale: '缺少规则和写入确认，结论跨过了多个处理阶段。', couldBeTrueWhen: '还同时存在运行后数据库记录与写入确认。' },
        { label: '页面已经向用户显示保存成功', rationale: '入口证据发生在服务端前段，未覆盖 Response 送达与页面呈现。', couldBeTrueWhen: '另有客户端呈现证据与可访问反馈。' },
      ],
      answerIndex: 0,
      referenceAnswer: 'API 入口命中只证明请求进入指定处理路径；规则、数据库持久化、Response 与页面反馈都需要后续证据。',
      reasoning: ['入口匹配先于业务服务。', '处理器仍可能收到规则拒绝或写入失败。', '页面结果属于 Response 之后的客户端阶段。'],
      rubric: ['指出入口作用', '列出至少两个未证明阶段', '不声称持久化成功'],
      commonErrors: [{ error: '把 API 当成整个后端', reason: 'API 入口只是后端对外边界，内部还有处理器、规则与数据操作。' }],
      remediation: { label: '补看 API 入口', sectionId: 'concepts', anchor: '#concept-api-entry' },
    },
    {
      id: 'w1d4-chain-order',
      kind: 'single-choice',
      categories: ['机制推演', '工作场景'],
      conceptIds: [...conceptIds],
      prompt: '哪条顺序最接近“保存阅读进度”的完整服务端处理链？',
      hint: '从客户端意图进入应用边界，再到业务裁决和数据结果。',
      options: [
        { label: 'HTTP → API → 处理器/后端服务 → 业务规则 → 数据库读写 → Response', rationale: '该顺序保持入口、处理、裁决、持久化和返回职责连续。', couldBeTrueWhen: '本课正常路径与两种失败路径都从这条主链分支。' },
        { label: 'HTTP → 数据库 → API → 页面', rationale: '客户端请求不会绕过 API 与后端业务直接操作数据库。', couldBeTrueWhen: '仅可能是独立数据库工具操作，不是本课应用请求链。' },
        { label: 'Response → 业务规则 → Request → 数据库', rationale: 'Response 是服务端处理后的结果，不会先于 Request。', couldBeTrueWhen: '没有符合本课时序的情形。' },
      ],
      answerIndex: 0,
      referenceAnswer: '正确主链是 HTTP → API → 请求处理器/后端服务 → 业务规则 → 数据库读写 → Response；失败会在规则或写入阶段提前转向不同 Response。',
      reasoning: ['API 是服务端入口。', '后端先裁决规则再决定数据动作。', 'Response 必须依据实际内部结果组装。'],
      rubric: ['处理链顺序完整无跳步', '业务规则发生在数据库写入之前', 'Response 位于内部处理结果之后'],
      commonErrors: [{ error: '让页面直接写数据库', reason: '这跳过了服务端业务边界，也无法可信执行规则。' }],
      remediation: { label: '补看完整示范', sectionId: 'demonstration', anchor: '#demonstration-conclusion' },
    },
    {
      id: 'w1d4-persistence-evidence',
      kind: 'single-choice',
      categories: ['证据判断'],
      conceptIds: ['business-rule', 'database-read-write', 'persistence-boundary', 'response-assembly'],
      prompt: '合法页码通过规则，但教学数据库返回 WRITE_FAILED。哪条结论没有越界？',
      hint: '规则允许写与数据库确认写是两件事。',
      options: [
        { label: '规则允许本次输入，但教学模拟未完成持久化，旧记录应保持不变', rationale: '结论同时尊重规则结果和写入失败证据。', couldBeTrueWhen: '运行后记录仍与运行前一致。' },
        { label: '规则通过，所以阅读进度已经保存', rationale: '把允许写误写成已经写，越过持久化边界。', couldBeTrueWhen: '还需 WRITE_CONFIRMED 和运行后记录。' },
        { label: '数据库失败说明 API 入口没有命中', rationale: '数据失败发生在入口之后，不能倒推入口未命中。', couldBeTrueWhen: '没有进入任何后端阶段且路由明确未匹配。' },
      ],
      answerIndex: 0,
      referenceAnswer: '规则通过只允许继续；WRITE_FAILED 说明本次教学模拟没有跨过持久化边界，旧记录应保持不变，Response 也不应宣称已保存。',
      reasoning: ['业务规则和持久化是两道门槛。', '数据失败发生在 API 与服务启动之后。', 'Response 必须与失败结果一致。'],
      rubric: ['区分允许与完成', '引用运行前后记录', '不倒推入口失败'],
      commonErrors: [{ error: '把规则通过当作保存完成', reason: '规则只决定是否允许尝试写入，不能代替数据库确认。' }],
      remediation: { label: '补看持久化边界', sectionId: 'concepts', anchor: '#concept-persistence-boundary' },
    },
    {
      id: 'w1d4-failure-handoff',
      kind: 'open',
      categories: ['综合变式', '工作场景'],
      conceptIds: [...conceptIds],
      prompt: '同事给出教学模拟结果：API 命中、规则通过、读取 page=9、写入失败、Response=SAVE_UNAVAILABLE。请写四句交接结论。',
      hint: '按看到、可以判断、不能判断、下一步组织。',
      referenceAnswer: '看到：教学模拟中请求命中保存入口，规则通过，旧记录为 page=9，写入失败，Response 为 SAVE_UNAVAILABLE。可以判断：本次模拟到达数据写入阶段但未持久化。不能判断：真实服务失败原因、影响范围和生产数据状态。下一步：在获准测试环境获取同一请求对应的数据层错误与运行后记录。',
      reasoning: ['原始阶段证据先于归因。', '持久化失败结论由写入结果与记录支持。', '生产范围必须另取真实证据。'],
      rubric: ['四句结构完整', '明确教学模拟', '区分规则与持久化', '下一步可执行且不涉及敏感数据'],
      commonErrors: [{ error: '直接写数据库坏了', reason: '单次教学模拟只能说明当前模拟写入失败，不能证明真实故障原因与影响范围。' }],
      remediation: { label: '补看证据边界', sectionId: 'independent-lab', anchor: '#w1d4-chapter-6' },
    },
  ],
  deliverable: {
    title: '请求处理链路说明',
    conceptIds: [...conceptIds],
    purpose: '把一次保存类请求从外部输入写到内部持久化和返回结果，让研发、测试和产品能沿同一职责链复核。',
    whenToUse: '用于需求评审、接口联调前的机制对齐，或保存结果与页面提示不一致时的分层交接。',
    audience: '后端研发、前端研发、测试与负责验收的产品经理。',
    fields: [
      { name: 'HTTP 输入', meaning: '写明触发动作、方法、API 路径与关键业务输入。', source: '教学模拟请求摘要或获准测试记录' },
      { name: 'API 与处理器', meaning: '说明入口匹配结果以及交给哪个请求处理器。', source: '教学模拟入口阶段或测试环境路由证据' },
      { name: '后端业务处理', meaning: '写出调用的业务服务和本次执行的核心业务规则。', source: '教学模拟阶段日志或服务端获准证据' },
      { name: '数据库读写', meaning: '分别记录运行前读取、写入动作与运行后记录。', source: '教学模拟前后记录或脱敏测试数据' },
      { name: '持久化结论', meaning: '只在写入确认与运行后记录一致时说明本次存储成立。', source: '教学模拟 WRITE_CONFIRMED 与前后记录对照' },
      { name: 'Response 与边界', meaning: '记录返回结果、能证明什么、不能证明什么和下一步证据。', source: '教学模拟 Response 与本次各阶段对照' },
    ],
    badExample: '点了保存，API 正常，后端处理完成，数据库应该已经有了，页面也成功。',
    badReasons: ['没有写 HTTP 输入与 API 入口，别人无法复现是哪次调用。', '把“应该写入”当成持久化事实，没有运行前后记录。', '没有区分规则拒绝、写入失败与 Response 呈现。'],
    revisionSteps: ['先补齐 HTTP 输入、API 入口和处理器，固定这次调用。', '按后端服务、业务规则、数据库读取、数据库写入逐层写证据。', '用运行前后记录决定是否跨过持久化边界。', '最后写 Response、证据限制与下一步，不替真实系统下结论。'],
    goodExample: `【教学模拟】请求处理链路说明
HTTP 输入：点击“保存进度”；POST /api/reading-progress；documentId=guide-01；page=12。
API 与处理器：入口 MATCHED，交给 SaveReadingProgressHandler。
后端业务处理：阅读进度服务检查 1 ≤ page ≤ 36，结果 ALLOWED。
数据库读写：运行前 page=9；提交更新 page=12；返回 WRITE_CONFIRMED；运行后 page=12。
持久化结论：仅本次教学模拟记录已从 9 更新到 12。
Response 与边界：教学模拟 Response=PROGRESS_SAVED，返回 page=12；它不证明真实生产数据库、客户端送达或页面展示。
下一步：在获准测试环境对照同一次调用的脱敏数据结果与页面反馈。`,
    guidedPrompts: ['本次 HTTP 输入是什么，进入哪条 API？', '请求处理器调用了哪个后端业务服务？', '哪条业务规则决定是否允许写入？', '教学模拟数据库运行前、写入结果和运行后记录分别是什么？', 'Response 与持久化结果是否一致，当前还不能证明什么？'],
    blankTemplate: `【教学模拟】请求处理链路说明
HTTP 输入：
API 与处理器：
后端业务处理：
数据库读写：
持久化结论：
Response 与边界：
下一步：`,
    standardTemplate: `【教学模拟】请求处理链路说明
HTTP 输入：[触发动作]；[Method] [API 路径]；[关键业务输入]
API 与处理器：[入口匹配结果]；[处理器]
后端业务处理：[业务服务]；[规则与结果]
数据库读写：运行前[记录]；写入[动作]；返回[结果]；运行后[记录]
持久化结论：[只写证据支持的模拟结果]
Response 与边界：[教学模拟 Response]；能证明[ ]；不能证明[ ]
下一步：[需要补取的真实或测试证据]`,
    checklist: ['HTTP 输入、API 入口和处理器都可定位。', '业务服务与业务规则写清输入和裁决结果。', '数据库读取与写入分开记录。', '持久化结论引用写入确认和运行后记录。', 'Response 与内部真实结果一致。', '全篇明确标注教学模拟并保留生产证据边界。'],
  },
  memory: {
    conceptIds: [...conceptIds],
    anchors: ['API 入口只负责接入和分流，不等于整个后端。', '后端业务服务先执行规则，再决定数据库动作。', '读取、计划写入与持久化确认是三种不同证据。', 'Response 必须忠实表达规则与数据库结果。', '教学模拟不能被写成真实生产证据。'],
    closedBookPrompt: '闭卷从一次 HTTP Request 开始，按 API、处理器、后端服务、业务规则、数据库读写、持久化边界和 Response 顺序讲完整链路。',
    microOperation: '任选“保存草稿”或“收藏内容”，写出一条同结构的请求处理链，并标出数据库写入失败时 Response 应怎样变化。',
    unresolvedPrompt: '当前还有哪一层需要在获准测试环境补取证据，才能从教学模拟走向真实功能验收？',
    reviewStages: [
      { stage: 'D1', task: '闭卷画出 HTTP → API → 后端规则 → 数据库 → Response，并为每个箭头写一个动词。' },
      { stage: 'D3', task: '看到“API 正常但进度未保存”时，写出至少四个分层追问和证据来源。' },
      { stage: 'D7', task: '把阅读进度迁移到保存草稿，说明规则拒绝时为什么不应执行数据库写入。' },
      { stage: 'D14', task: '对照一次成功路径与数据写入失败路径，写出两条不同的有限结论。' },
      { stage: 'D30', task: '独立审阅一份请求处理链路说明，找出入口、规则、持久化或 Response 的越界表述。' },
      { stage: 'D60', task: '闭卷提交一份新场景链路说明，并由他人按职责顺序、证据完整性和边界克制性复核。' },
    ],
  },
  nextLesson: {
    id: 'W1D5',
    title: '使用 Network 读取请求证据',
    bridge: '今天已经建立 API、后端规则与数据库持久化链路。下一课才进入真实 Network 请求条目，学习如何从浏览器侧读取能支持这些判断的证据。',
  },
}
