import type { DailyCourse } from './types'

const conceptIds = [
  'network-request-entry',
  'network-name-url',
  'network-method-status-type',
  'network-initiator',
  'network-headers',
  'network-payload-response',
  'network-timing',
  'network-size-cache',
  'network-evidence-boundary',
] as const

const prerequisiteConceptIds = [
  'http-request',
  'http-response',
  'method-url',
  'header-cookie-query',
  'payload',
  'status-response',
  'timing-size',
]

export const w1d5: DailyCourse = {
  id: 'W1D5',
  contentVersion: 'w1d5-network-evidence-day01-v1',
  week: 1,
  day: 5,
  title: '使用 Network 读取请求证据',
  subtitle: '从浏览器请求条目逐字段取证，把观察、有限推断与未知事实严格分开。',
  duration: { core: 30, standard: 45, extension: 35, full: 82 },
  coreConceptGroups: [
    {
      id: 'network-list-columns',
      title: '请求列表先回答“是哪一条”',
      conceptIds: ['network-request-entry', 'network-name-url', 'network-method-status-type', 'network-initiator'],
      summary: 'Network 列表把页面活动拆成独立请求条目，并用 Name／URL、Method、Status、Type 与 Initiator 帮你定位目标。',
      boundary: '列表列只描述浏览器记录到的这次请求，不能单独证明业务正确、后端实现或数据库事实。',
    },
    {
      id: 'network-detail-fields',
      title: '详情页回答“发送了什么、收到了什么”',
      conceptIds: ['network-headers', 'network-payload-response'],
      summary: 'Headers 固定元信息，Payload 固定请求输入，Response 固定浏览器收到的响应内容；来源和方向必须分开。',
      boundary: '浏览器侧详情可以支持消息层观察，不能替代服务端日志、代码、真实持久化或用户影响范围证据。',
    },
    {
      id: 'network-measurement-boundary',
      title: '测量与证据边界',
      conceptIds: ['network-timing', 'network-size-cache', 'network-evidence-boundary'],
      summary: 'Timing、Size 与缓存线索描述本次加载的时间、体积和复用迹象；最后用四句式控制结论强度。',
      boundary: '一次慢、一次大或一次命中缓存都只是样本；没有对照、服务端证据和范围数据时不能归因。',
    },
  ],
  prerequisiteConceptIds,
  learningPaths: {
    '30': {
      guidedStepIndices: [0, 1, 2, 3, 4, 5, 6],
      guidedRecordIndices: [0, 1, 2],
      exerciseCount: 3,
      deliverablePromptCount: 4,
      deliverableChecklistIndices: [0, 1, 2, 3],
      deliverableMinimumContributionCharacters: 80,
    },
    '45': {
      guidedStepIndices: [0, 1, 2, 3, 4, 5, 6],
      guidedRecordIndices: [0, 1, 2, 3],
      exerciseCount: 4,
      deliverablePromptCount: 6,
      deliverableChecklistIndices: [0, 1, 2, 3, 4, 5],
      deliverableMinimumContributionCharacters: 120,
    },
  },
  primaryGoal: '独立定位一个 Network 请求条目，逐字段记录浏览器证据，并提交可复现、不过度归因的观察记录。',
  scenario: {
    role: '你是参与“读取课程摘要”功能验收的产品经理，只能使用脱敏教学模拟。',
    situation: '页面有时能显示摘要，有时提示失败，也有人报告加载偏慢；团队需要一份可以复现的浏览器侧证据，而不是一句“接口有问题”。',
    question: 'Network 到底记录了什么？这些字段分别能支持哪些判断，又有哪些后端、数据库与影响范围事实仍不能证明？',
    stakes: '如果把单条请求直接归因给后端或数据库，交接会误导排查；如果记录不完整，研发也无法重放同一次观察。',
  },
  objectives: [
    { id: 'w1d5-objective-locate', text: '从请求列表定位目标条目', evidence: '准确记录 Name／URL、Method、Status、Type 与 Initiator。' },
    { id: 'w1d5-objective-read', text: '按方向读取请求与响应详情', evidence: '分别抄录 Headers、Payload 与 Response 的脱敏关键字段。' },
    { id: 'w1d5-objective-measure', text: '解释时间、体积与缓存线索', evidence: '记录 Timing、Size 与缓存变式，并写清对照条件。' },
    { id: 'w1d5-objective-boundary', text: '形成不过度归因的有限结论', evidence: '提交“看到／可以推断／还不能证明／下一步”四句式记录。' },
  ],
  prerequisites: [
    {
      id: 'w1d5-http-readiness',
      conceptIds: prerequisiteConceptIds,
      prompt: '你能把一次 HTTP Request 与 Response 分开，并解释 Method、Header、Payload、Status、Timing、Size 各在消息中承担什么吗？',
      passDescription: '能从用户动作讲到 Request，再讲到 Response；知道 200、Timing 或 Size 只是字段证据，不自动等于业务成功。',
      remediationLabel: '补学 W1D3：HTTP 请求与响应',
      remediationTarget: '#/lesson/W1D3',
      remediation: {
        purpose: 'Network 是浏览器收集 HTTP 证据的界面；先理解消息方向，才能避免把列表列名当成结论。',
        steps: ['回到 W1D3 复述 Request 与 Response 的输入输出。', '闭卷解释 Method、Header、Payload、Status、Timing 与 Size。', '用一条 422 示例写出能证明与不能证明的边界。'],
        successCheck: '不看答案，能把请求侧字段、响应侧字段和测量字段放回正确方向。',
      },
    },
  ],
  concepts: [
    {
      id: 'network-request-entry',
      prerequisiteConceptIds: ['http-request', 'http-response'],
      term: 'Network 请求条目',
      english: 'Network Request Entry',
      definition: '浏览器开发者工具 Network 面板里的一行记录，代表浏览器观察到的一次资源请求及其当前或最终结果。',
      why: '一个页面会同时加载文档、脚本、图片和数据；请求条目把这些活动拆开，避免把整页现象混成一件事。',
      problemSolved: '帮助你把“页面有问题”缩小为某个触发动作后、某个时间点出现的具体浏览器请求。',
      input: '浏览器发起或接管的一次资源加载，以及开发者工具在本机观察到的请求过程。',
      output: '一行可选择的请求记录，并关联请求详情、响应详情、时间测量与缓存线索。',
      systemPosition: '位于浏览器开发者工具的 Network 观察界面，是客户端侧证据入口。',
      process: ['先打开 Network 并清空旧记录，再执行一次明确动作。', '浏览器为新产生的资源活动追加条目。', '选择目标条目后读取列表列和详情标签。'],
      owner: '浏览器开发者工具负责记录与展示；学习者负责固定环境、动作和目标条目。',
      notResponsibleFor: '不负责证明服务端内部实现、数据库写入、全体用户影响或业务规则一定正确。',
      compareWith: '它不是页面截图，也不是服务端日志；三者观察位置不同，能回答的问题也不同。',
      evidence: ['清空列表后执行动作出现的新行。', '条目时间与操作时间相邻且目标特征一致。'],
      failureModes: ['没有先清空导致选中旧请求。', '后台轮询产生相似条目而被误认为用户动作触发。'],
      pmUse: '复现加载、提交或页面异常时，先固定要交接的那一次浏览器请求。',
      correctExample: '先清空教学列表，再点击“读取摘要”，记录新出现的 summary.json 条目和发生时间。',
      incorrectExample: '看到列表里有一条红色请求，就断言用户刚才的操作一定触发了它。',
    },
    {
      id: 'network-name-url',
      prerequisiteConceptIds: ['network-request-entry', 'method-url'],
      term: 'Name 与 Request URL',
      english: 'Name / Request URL',
      definition: 'Name 是列表中便于快速识别的资源名称或路径尾部；Request URL 是详情里这次请求实际指向的完整地址。',
      why: '相同文件名可能来自不同域名、路径或查询条件，只看 Name 容易把目标请求认错。',
      problemSolved: '让观察记录既能快速定位条目，又能用脱敏完整 URL 固定环境、路径与查询。',
      input: '浏览器准备请求的目标地址，以及 Network 界面为列表生成的简短显示名。',
      output: '一个列表定位线索 Name 和一个可复核目标 Request URL。',
      systemPosition: 'Name 位于请求列表；Request URL 通常位于所选条目的 Headers / General 区域。',
      process: ['先用 Name 在列表缩小范围。', '再打开 Headers 核对完整 Request URL。', '记录环境、路径与必要的脱敏查询条件。'],
      owner: '浏览器根据请求目标展示；记录者负责脱敏并保留足够的复现信息。',
      notResponsibleFor: '地址一致不能证明响应内容正确，也不能证明它由哪个内部服务或数据库生成。',
      compareWith: 'Name 是缩略定位线索，Request URL 是完整目标证据；两者不能互相替代。',
      evidence: ['列表中的资源名称。', 'Headers / General 中的完整 Request URL。'],
      failureModes: ['只写 summary.json 而遗漏不同环境。', '复制 URL 时带出真实账号、Token 或敏感查询值。'],
      pmUse: '同名请求较多或需要让研发重放时，用完整且脱敏的目标地址消除歧义。',
      correctExample: 'Name=summary.json；Request URL=https://training.invalid/api/summary?doc=demo-17，并明确这是教学模拟。',
      incorrectExample: '只写“summary 请求失败”，不说明环境、路径或是哪一个条目。',
    },
    {
      id: 'network-method-status-type',
      prerequisiteConceptIds: ['network-request-entry', 'method-url', 'status-response'],
      term: 'Method、Status 与 Type',
      english: 'Method / Status / Type',
      definition: 'Method 记录请求动作，Status 记录本次 HTTP 响应状态，Type 是浏览器对资源种类或加载方式的分类。',
      why: '三列分别回答“怎样请求”“得到哪类响应”“浏览器把资源看成什么”，联合后才能准确描述条目。',
      problemSolved: '避免把 GET、200 或 fetch 单独写成“接口正常”，也避免忽略 4xx/5xx 的响应类别。',
      input: '请求方法、收到的 HTTP 状态，以及浏览器根据请求上下文与响应信息生成的资源分类。',
      output: '可并排观察的动作、响应类别和资源类型线索。',
      systemPosition: '通常作为 Network 列表的独立列；更完整值可在所选条目详情中复核。',
      process: ['先记录 Method，确认观察的是读取还是提交类动作。', '再记录 Status，区分成功类、客户端错误类与服务端错误类。', '最后记录 Type，辅助排除图片、脚本和数据请求混淆。'],
      owner: '客户端选择 Method，服务端响应产生 Status，浏览器展示 Type 分类。',
      notResponsibleFor: '200 不保证业务字段正确；4xx/5xx 不自动说明具体责任人；Type 也不是后端技术栈证明。',
      compareWith: 'Method 描述请求意图，Status 描述协议结果，Type 描述浏览器分类，三者方向不同。',
      evidence: ['列表列中的 GET/POST。', '200/404/422/503 等状态。', 'fetch/xhr/document 等类型。'],
      failureModes: ['把 200 当成业务成功。', '把所有 4xx 都写成前端问题，或把所有 5xx 都写成数据库问题。'],
      pmUse: '快速分组正常、客户端错误和服务端错误样本，再进入详情读取正文和边界。',
      correctExample: '教学模拟条目显示 GET、503、fetch；记录为“本次数据请求收到 503 类响应”，不直接归因。',
      incorrectExample: '看到 Type=fetch 就断言后端使用了某个框架。',
    },
    {
      id: 'network-initiator',
      prerequisiteConceptIds: ['network-request-entry'],
      term: 'Initiator',
      english: 'Initiator',
      definition: 'Network 中用于提示哪类页面解析、脚本调用或其他加载链条触发了这次请求的浏览器侧线索。',
      why: '同一个 URL 可能由用户点击后的脚本、页面解析、预取或轮询触发，来源不同会改变复现方式。',
      problemSolved: '帮助区分目标请求与后台活动，并为“从哪个客户端动作继续检查”提供起点。',
      input: '浏览器掌握的资源依赖与调用栈线索，例如 parser、script、click handler 或 prefetch。',
      output: '一个触发来源标签，部分浏览器还提供可展开的调用链。',
      systemPosition: '位于 Network 列表 Initiator 列或所选条目的 Initiator 详情。',
      process: ['先确认请求发生在目标动作附近。', '再读取 Initiator 标签。', '必要时展开调用栈并记录脱敏脚本位置。'],
      owner: '浏览器依据客户端加载与执行关系生成；前端调用路径提供原始触发上下文。',
      notResponsibleFor: 'Initiator 不能证明服务端根因、数据库操作或用户主观意图。',
      compareWith: 'Initiator 说明客户端侧触发线索，Request URL 说明目标，两者不是因果根因证明。',
      evidence: ['列表中的 script/parser/prefetch 标签。', '可展开的客户端调用栈或资源依赖链。'],
      failureModes: ['把预取请求误认成点击请求。', '看到脚本文件名就断言该行代码必然是根因。'],
      pmUse: '当点击后出现多条相似请求时，用触发线索锁定更可能与复现动作相关的条目。',
      correctExample: '教学模拟显示 Initiator=click-handler，支持“本次请求与点击处理链有关联”，仍不证明错误来自该处理器。',
      incorrectExample: 'Initiator 显示 app.js，所以 app.js 一定写错了。',
    },
    {
      id: 'network-headers',
      prerequisiteConceptIds: ['network-request-entry', 'header-cookie-query'],
      term: 'Headers',
      english: 'Request / Response Headers',
      definition: '所选请求详情中的元信息集合，通常分为 General、Request Headers 与 Response Headers，来源方向必须分别记录。',
      why: '内容类型、缓存协商、请求目标和响应控制常出现在 Headers；混合方向会把客户端发送与服务端返回写反。',
      problemSolved: '让观察记录说明某个关键字段来自请求还是响应，并保留可核对的字段名与脱敏值。',
      input: '浏览器发送的请求元信息、收到的响应元信息，以及工具展示的通用请求摘要。',
      output: '按方向分组的字段名和值，例如 Content-Type、Cache-Control、ETag 与 Request URL。',
      systemPosition: '位于所选 Network 条目的 Headers 详情标签，不是独立请求本身。',
      process: ['先确认 General 中的 URL、Method、Status。', '再读取 Request Headers 中的必要字段。', '最后读取 Response Headers，并对敏感值脱敏。'],
      owner: '浏览器与客户端代码形成请求 Headers；响应 Headers 由服务端响应返回；工具负责展示。',
      notResponsibleFor: '出现某个 Header 不能证明中间代理、服务端或客户端最终怎样使用它。',
      compareWith: 'Headers 是元信息，Payload 是请求内容，Response 是响应内容，三者不能混写。',
      evidence: ['General 区中的 Request URL/Method/Status。', 'Request Headers 与 Response Headers 的明确分组标题。'],
      failureModes: ['复制真实 Authorization/Cookie。', '把 Response Header 当作客户端提交字段。'],
      pmUse: '检查内容类型、缓存指令或关键请求元信息时，只记录任务需要且已脱敏的字段。',
      correctExample: '记录 Response Headers 的 Cache-Control: max-age=60，并注明它只是本次响应声明。',
      incorrectExample: '把 Authorization 原值粘贴到缺陷单，或凭 Cache-Control 断言所有缓存层均已命中。',
    },
    {
      id: 'network-payload-response',
      prerequisiteConceptIds: ['network-headers', 'payload', 'http-response'],
      term: 'Payload 与 Response',
      english: 'Payload / Response',
      definition: 'Payload 是浏览器展示的请求输入内容；Response 是浏览器收到并可查看的响应正文或可解析结果，两者分属相反方向。',
      why: '同一字段在请求和响应中可能取值不同，只有分开记录才能判断“发出了什么”和“收到了什么”。',
      problemSolved: '支持核对关键输入类型、响应错误码和脱敏业务字段，同时避免用客户端输入替代服务端回报。',
      input: '请求体、表单或查询展开结果，以及浏览器收到的响应字节或解析后的内容。',
      output: '请求侧关键字段与响应侧关键字段的可复核对照。',
      systemPosition: '位于所选条目的 Payload 与 Response/Preview 详情标签。',
      process: ['先记录 Payload 中最小必要输入。', '再切到 Response 记录状态对应的正文。', '最后对照字段方向并删除账号、Token 和私有数据。'],
      owner: '客户端组织 Payload；服务端生成 Response；浏览器开发者工具展示本机看到的结果。',
      notResponsibleFor: '响应正文不证明数据已持久化、页面已正确渲染或所有用户都收到相同结果。',
      compareWith: 'Payload 说明提交了什么，Response 说明浏览器收到了什么；Status 只是响应类别摘要。',
      evidence: ['Payload 中的脱敏字段与类型。', 'Response 中的 code/message/data 等脱敏内容。'],
      failureModes: ['把请求体写成服务端接受结果。', '只看 200 而不读取正文里的失败 code。'],
      pmUse: '联调输入与结果不一致时，固定本次请求侧和响应侧的最小证据对。',
      correctExample: 'Payload 记录 docId=demo-17；Response 记录 code=SUMMARY_READY，明确两者方向。',
      incorrectExample: '因为 Payload 有 docId，就写“后端已经查到该文档”。',
    },
    {
      id: 'network-timing',
      prerequisiteConceptIds: ['network-request-entry', 'timing-size'],
      term: 'Timing',
      english: 'Timing',
      definition: 'Network 为单次请求提供的阶段时间测量，常包含排队、连接、发送、等待首字节与内容下载等片段。',
      why: '总耗时变慢只是现象，阶段拆分能指出时间主要落在哪一段，并为下一步取证排序。',
      problemSolved: '把“很慢”改写为可比较的单次测量，同时保留样本、环境与测量边界。',
      input: '浏览器本机记录的请求生命周期时间点与阶段持续时间。',
      output: '总耗时和多个阶段耗时，可用于同条件样本之间对照。',
      systemPosition: '位于所选 Network 条目的 Timing 详情以及列表 Time/Waterfall 列。',
      process: ['先记录总耗时和发生时间。', '再找占比最大的阶段。', '最后与相同环境、相同条件的另一次请求对照。'],
      owner: '浏览器负责客户端侧测量；记录者负责固定条件、单位和样本范围。',
      notResponsibleFor: '单次 Timing 不能独立证明服务端代码慢、网络故障或数据库查询耗时。',
      compareWith: 'Timing 是时间测量，Status 是结果类别，Response 是内容；速度与正确性是不同问题。',
      evidence: ['总耗时毫秒数。', '等待首字节或下载等阶段的持续时间。'],
      failureModes: ['只记“慢”不写数值。', '用一次慢请求推断所有用户或某个内部组件都慢。'],
      pmUse: '性能问题交接时记录时间分布，并明确需要服务端日志或更多样本才能继续归因。',
      correctExample: '教学模拟总耗时 1840ms，其中等待阶段 1600ms；支持“本次等待占比高”，不直接归因后端。',
      incorrectExample: 'Timing 1.8s，所以数据库查询一定用了 1.8s。',
    },
    {
      id: 'network-size-cache',
      prerequisiteConceptIds: ['network-timing'],
      term: 'Size 与缓存线索',
      english: 'Size / Cache Clues',
      definition: 'Size 表示列表中传输或资源体积的浏览器测量；memory cache、disk cache、304 与响应缓存 Headers 是复用或协商的线索。',
      why: '相同 URL 的传输体积可能因压缩、响应内容和缓存路径变化；Size 变化必须与缓存和响应条件一起读。',
      problemSolved: '区分“本次传输了多少”与“资源本身多大”，并记录可能的缓存变式而不把线索当成完整实现证明。',
      input: '本次响应字节、压缩信息、缓存命中显示、304 状态或缓存相关响应 Headers。',
      output: '传输大小、资源大小或缓存来源等浏览器侧线索。',
      systemPosition: '位于 Network 列表 Size 列、Headers 和可能的缓存来源提示。',
      process: ['先记录 Size 显示及单位。', '再记录是否出现 memory/disk cache、304 或缓存 Header。', '最后用相同 URL 的另一次加载做对照。'],
      owner: '浏览器与响应共同形成展示；缓存策略可能跨浏览器、代理和服务端多层。',
      notResponsibleFor: '一条 memory cache 或 304 不能证明所有缓存层配置，也不能直接解释业务数据是否最新。',
      compareWith: 'Size 是体积测量，缓存是复用线索；体积变小可能由缓存、压缩或内容变化等多种条件造成。',
      evidence: ['Size 列显示 2.4 kB 或 memory cache。', 'Status 304 与 Response Headers 的 ETag/Cache-Control。'],
      failureModes: ['把 0B 当成请求没有发生。', '看到缓存命中就断言服务端没有收到任何相关请求。'],
      pmUse: '排查资源体积、重复下载或新旧内容问题时，记录具体缓存线索并保留多层未知。',
      correctExample: '同一教学 URL 第二次显示 memory cache、传输 Size 下降；只能支持浏览器本次复用了本地缓存。',
      incorrectExample: 'Size 变小，所以后端一定做了数据库优化。',
    },
    {
      id: 'network-evidence-boundary',
      prerequisiteConceptIds: ['network-request-entry', 'network-payload-response', 'network-size-cache'],
      term: 'Network 证据边界',
      english: 'Network Evidence Boundary',
      definition: '把浏览器实际看到的字段、基于这些字段的有限推断、仍缺失的事实和下一步取证严格分开的记录规则。',
      why: 'Network 信息丰富，最常见错误却是从单条客户端记录跳到后端实现、数据库状态或全量用户影响。',
      problemSolved: '让观察可复现、可交接，并让责任判断停在现有证据支持的位置。',
      input: '目标请求的原始字段、触发条件、对照样本，以及任务真正要回答的问题。',
      output: '“看到／可以推断／还不能证明／下一步”四段有限结论。',
      systemPosition: '位于观察流程末端，负责约束结论而不是制造新的系统事实。',
      process: ['先逐字记录浏览器可见字段。', '再写不跨层的有限推断。', '列出后端、数据库与范围未知。', '指定下一位角色和需要补取的证据。'],
      owner: '证据记录者负责结论强度；后续责任人用服务端、数据或范围证据继续验证。',
      notResponsibleFor: '不凭措辞本身判定根因，也不把教学模拟升级成真实生产事件。',
      compareWith: '观察是原始字段，推断是有限解释，归因需要额外机制证据，三者不能混成一句。',
      evidence: ['记录中每个判断都能回指具体字段。', '未知事项与下一步证据明确且可执行。'],
      failureModes: ['把“看到 500”写成“数据库坏了”。', '只写未知不写下一步，导致记录无法继续行动。'],
      pmUse: '提交联调记录、缺陷说明或性能观察时，避免过度承诺和无证据甩锅。',
      correctExample: '看到 503 与 ERROR_UPSTREAM；可推断本次请求收到服务端错误类响应；不能证明具体内部依赖；下一步补同一请求的脱敏 request id 日志。',
      incorrectExample: 'Network 红了，所以后端和数据库都有问题。',
    },
  ],
  diagram: {
    title: 'Network 取证路径：先定位，再读详情，最后限制结论',
    caption: '所有箭头都发生在浏览器侧观察流程；它们组织证据，不代表服务端内部处理链。',
    nodes: [
      { id: 'request-list', label: '请求列表', description: '用 Name/URL、Method、Status、Type 与 Initiator 锁定条目。', input: '清空后的新请求记录', output: '目标条目', owner: '浏览器 Network 列表', evidence: '列表列值与发生时间' },
      { id: 'request-details', label: '条目详情', description: '分方向读取 Headers、Payload、Response。', input: '选中的目标条目', output: '请求侧与响应侧字段', owner: '浏览器详情面板', evidence: '详情标签与脱敏字段' },
      { id: 'measurements', label: '测量与缓存', description: '记录 Timing、Size 与缓存线索并建立对照。', input: '同条件单次或多次加载', output: '时间、体积和复用线索', owner: '浏览器测量界面', evidence: '毫秒、字节、缓存来源' },
      { id: 'evidence-record', label: '有限观察记录', description: '把原始观察、推断、未知与下一步分开。', input: '字段与对照样本', output: '可复现交接记录', owner: '产品经理或测试记录者', evidence: '每个结论可回指字段' },
    ],
    branches: [
      { from: 'request-list', to: 'request-details', label: '锁定正确条目后继续', kind: 'normal' },
      { from: 'request-details', to: 'measurements', label: '联合读取内容与测量', kind: 'normal' },
      { from: 'request-list', to: 'evidence-record', label: '选错旧条目会污染结论', kind: 'failure' },
      { from: 'measurements', to: 'evidence-record', label: '单样本直接归因会越界', kind: 'failure' },
    ],
    evidenceNotes: ['Name 用于定位但必须用 Request URL 复核。', 'Headers、Payload 与 Response 必须保留方向。', 'Timing、Size 与缓存线索需要相同条件对照。', 'Network 只能支持有限判断，不能单条证明后端实现或数据库事实。'],
  },
  demonstration: {
    title: '教师示范：完整记录一次“读取摘要”请求',
    businessProblem: '教学页面点击“读取摘要”后显示结果，但团队需要确认本次浏览器到底请求了什么、收到了什么，并保留性能与缓存未知。',
    finalConclusion: '本次脱敏教学模拟中，点击后产生 GET summary.json 请求，浏览器收到 200 / fetch 与 SUMMARY_READY；Timing 为 180ms，Size 为 2.4kB，未显示缓存复用。',
    conclusionLimit: '这些字段只支持本次浏览器观察；它们不能证明真实后端实现、数据库状态、页面渲染正确性或全体用户体验。',
    steps: [
      { title: '清空并固定动作', action: '清空教学 Network 列表，记录环境与时间，只执行一次“读取摘要”。', reason: '隔离旧请求和后台活动。', evidence: '动作后新出现一条 summary.json。', proves: '目标条目与本次动作在时间上相关。', limitation: '尚未证明触发原因或业务结果。' },
      { title: '核对 Name 与 URL', action: '用 Name 定位，再在 Headers 核对脱敏完整 Request URL。', reason: '防止同名资源来自不同环境。', evidence: 'summary.json 与 training.invalid/api/summary?doc=demo-17 对应。', proves: '本次观察目标被固定。', limitation: '地址正确不证明响应正确。' },
      { title: '逐项记录列表列', action: '抄录 Method、Status、Type 与 Initiator。', reason: '先形成条目摘要再读正文。', evidence: 'GET、200、fetch、click-handler。', proves: '本次请求动作、响应类别、资源分类和触发线索。', limitation: '200 与 click-handler 都不是业务成功或根因证明。' },
      { title: '分开读取详情', action: '在 Headers、Payload、Response 中分别记录最小必要字段。', reason: '避免把客户端输入写成服务端回报。', evidence: 'Payload 无请求体；Response code=SUMMARY_READY。', proves: '浏览器收到的本次脱敏响应内容。', limitation: '不证明数据库、页面呈现或用户范围。' },
      { title: '记录 Timing 与 Size', action: '读取总时间、主要阶段和传输体积。', reason: '把“快慢”和“大小”变成可比较测量。', evidence: '总耗时 180ms，Size 2.4kB。', proves: '本次浏览器测量值。', limitation: '单样本不能归因或代表所有用户。' },
      { title: '检查缓存线索', action: '核对 Size 列与缓存相关 Headers 是否显示复用。', reason: '缓存会改变传输体积和加载路径。', evidence: '本次显示 network，无 memory/disk cache。', proves: '本次未显示浏览器本地缓存复用。', limitation: '不证明其他缓存层不存在。' },
      { title: '写四句有限结论', action: '按看到、可以推断、还不能证明、下一步组织记录。', reason: '把原始证据与判断分开。', evidence: '每句均回指具体 Network 字段。', proves: '记录可复核且结论强度受控。', limitation: '记录质量仍需人工或量规审核。' },
    ],
  },
  guidedLab: {
    title: 'Network 教学观察器：运行七类证据变式',
    goal: '在同一脱敏请求上对照正常、4xx、5xx、慢 Timing、Size、Initiator 与缓存变化，并逐字段记录边界。',
    safety: '完全本地教学模拟；不发送真实请求，不使用账号、Token、私有接口、公司数据或生产日志。',
    conceptIds: [...conceptIds],
    predictionPrompt: '先预测：当 Status、Timing、Size、Initiator 或缓存线索改变时，哪些 Network 字段会变，哪些后端与数据库事实仍然不知道？',
    steps: [
      { title: '运行正常基线', action: '选择 200 正常、快速、小体积、点击触发、network 后运行。', observe: '得到一条完整正常请求条目与详情。', explanation: '基线固定后，变式才有可比较对象。', proves: '本次模拟基线字段可复现。', cannotProve: '真实功能基线或生产可用性。' },
      { title: '对照 4xx', action: '切换为 422 再运行，读取 Status 与 Response。', observe: '状态与错误正文改变，请求目标仍可保持相同。', explanation: '4xx 是本次响应类别线索，仍需正文解释具体条件。', proves: '本次模拟收到客户端错误类响应。', cannotProve: '责任一定在前端或用户。' },
      { title: '对照 5xx', action: '切换为 503 再运行，保留其他条件。', observe: '状态变为服务端错误类，Response 提供脱敏错误码。', explanation: '5xx 说明本次服务端错误类响应，不说明内部哪一层失败。', proves: '本次模拟收到 5xx 类结果。', cannotProve: '后端实现或数据库根因。' },
      { title: '制造慢 Timing', action: '只把时间变式切到 1840ms 后运行。', observe: 'Timing 总值与等待阶段显著增加。', explanation: '单变量对照支持本次时间差，尚不支持根因。', proves: '本次模拟慢样本与基线不同。', cannotProve: '真实网络、服务或数据库谁慢。' },
      { title: '改变 Size', action: '保持状态一致，分别运行小体积与大体积。', observe: 'Size 从 2.4kB 变为 84kB，Response 业务码保持不变。', explanation: '体积变化必须记录条件，不能直接解释成性能根因。', proves: '本次模拟传输体积发生变化。', cannotProve: '内容冗余或压缩策略的真实原因。' },
      { title: '改变 Initiator', action: '把 click-handler 改为 prefetch 再运行。', observe: 'Request URL 可相同，但触发来源线索改变。', explanation: 'Initiator 有助于区分点击请求与预取活动。', proves: '本次模拟触发线索不同。', cannotProve: '哪段代码存在缺陷。' },
      { title: '改变缓存路径并记录边界', action: '运行 memory cache 或 304 revalidated 变式，再写四句有限记录。', observe: 'Status、Size 或缓存来源显示变化。', explanation: '缓存线索需要与同 URL 基线一起解释。', proves: '本次模拟出现浏览器缓存或协商线索。', cannotProve: '所有缓存层、内容新鲜度或真实服务命中情况。' },
    ],
    recordPrompts: ['记录目标条目的 Name／URL、Method、Status、Type、Initiator。', '分别记录 Headers、Payload 与 Response 的脱敏关键字段。', '对照基线与变式的 Timing、Size 和缓存线索。', '写出看到、可以推断、还不能证明与下一步证据。'],
    comparePrompt: '比较七类运行：哪些字段是原始观察，哪些只是线索，缺少什么证据时不能归因后端或数据库？',
    passCriteria: ['正常、4xx、5xx、慢 Timing、Size、Initiator 与缓存七类覆盖全部运行。', '每次记录都明确标注教学模拟且没有敏感字段。', '请求侧、响应侧与测量字段没有混写。', '最终结论包含明确未知与可执行下一步。'],
  },
  independentLab: {
    title: '独立变式：为相同 URL 写一份不过度归因的对照记录',
    scenario: '同事给出两个相同 Request URL 的脱敏教学样本：一个由点击触发并从 network 加载，另一个由 prefetch 触发并命中 memory cache。',
    conceptIds: [...conceptIds],
    changedConditions: ['保持 URL 与 200 不变，只把 Initiator 从 click-handler 改为 prefetch。', '保持 URL 与 Initiator 不变，只把 network 改为 memory cache。', '保持状态与缓存不变，只把 Size 从 2.4kB 改为 84kB。'],
    task: '先预测列表和详情哪些字段会变，再执行观察器对照，最后提交四句式有限结论。',
    predictionPrompt: '改变这个条件后，Name／URL、Status、Initiator、Timing、Size 与缓存线索中哪几项应该变化？',
    evidenceRequirements: ['保留两条教学模拟请求的字段快照和变更条件。', '明确区分浏览器线索、有限推断与仍未知的服务端事实。', '下一步只要求脱敏测试证据，不要求生产权限或私有数据。'],
    passCriteria: ['改变条件与基线只保留一个主要变量。', '预测先于运行结果且差异字段逐项记录。', '没有把缓存、Initiator 或 Status 直接写成后端根因。', '记录足以让另一位同事按同条件复现。'],
    remediation: { label: '补学：Network 证据边界', sectionId: 'concepts', anchor: '#concept-network-evidence-boundary' },
  },
  exercises: [
    {
      id: 'w1d5-field-direction', kind: 'single-choice', categories: ['概念与边界'], conceptIds: ['network-headers', 'network-payload-response'],
      prompt: '哪组配对正确表达了 Network 详情字段的方向？', hint: '先问“由客户端发送，还是由浏览器收到”。',
      options: [
        { label: 'Payload 是请求输入；Response 是响应正文', rationale: '两者方向相反，必须分开记录。', couldBeTrueWhen: '所选条目同时展示请求内容与响应内容。' },
        { label: 'Payload 是服务端处理结果；Response 是客户端输入', rationale: '方向完全颠倒，会把发送与接收写反。', couldBeTrueWhen: '没有符合标准 Network 语义的情况。' },
        { label: 'Headers 只包含响应字段，不包含请求字段', rationale: 'Headers 通常同时区分 General、Request 和 Response。', couldBeTrueWhen: '某些条目可能没有可展示的请求 Header，但这不是字段定义。' },
      ], answerIndex: 0,
      referenceAnswer: 'Payload 记录请求侧输入，Response 记录浏览器收到的响应内容；Headers 还要继续区分请求和响应方向。',
      reasoning: ['方向决定字段能支持什么判断。', '客户端发送不等于服务端接受。', '响应正文不等于数据库持久化。'],
      rubric: ['Payload 方向正确', 'Response 方向正确', '没有越界到数据库事实'],
      commonErrors: [{ error: '把发送写成接受', reason: '请求侧只能证明浏览器准备或发送了什么，不能替代响应结果。' }],
      remediation: { label: '补看 Payload 与 Response', sectionId: 'concepts', anchor: '#concept-network-payload-response' },
    },
    {
      id: 'w1d5-list-reading', kind: 'single-choice', categories: ['机制推演', '证据判断'], conceptIds: ['network-name-url', 'network-method-status-type', 'network-initiator'],
      prompt: '教学模拟显示 Name=summary.json、GET、503、fetch、Initiator=click-handler。最稳妥的结论是哪一条？', hint: '只写浏览器这次真正记录到的层。',
      options: [
        { label: '点击处理链关联的一次数据请求收到 503 类响应，内部失败位置仍未知', rationale: '联合列值形成有限描述，没有跳到内部根因。', couldBeTrueWhen: '条目与目标动作已通过时间和 URL 复核。' },
        { label: '点击代码写错导致数据库宕机', rationale: 'Initiator 与 503 都不足以证明客户端代码和数据库根因。', couldBeTrueWhen: '还需要客户端异常、服务端链路与数据库证据共同支持。' },
        { label: 'fetch 类型说明后端框架加载失败', rationale: 'Type 是浏览器资源分类，不是后端框架证据。', couldBeTrueWhen: '没有这种直接推断。' },
      ], answerIndex: 0,
      referenceAnswer: '可以描述为目标点击处理链关联的一次 fetch 请求收到 503 类响应；Network 仍不能告诉你具体后端组件或数据库是否失败。',
      reasoning: ['Name/URL 固定目标。', 'Status 描述本次响应类别。', 'Initiator 只给出客户端触发线索。'],
      rubric: ['联合读取至少四列', '保留内部未知', '没有把 Type 当技术栈证明'],
      commonErrors: [{ error: '红色状态直接归因', reason: '错误类响应是排查起点，不是后端内部根因结论。' }],
      remediation: { label: '补看列表列与 Initiator', sectionId: 'concepts', anchor: '#concept-network-initiator' },
    },
    {
      id: 'w1d5-timing-size-cache', kind: 'single-choice', categories: ['证据判断', '工作场景'], conceptIds: ['network-timing', 'network-size-cache'],
      prompt: '同一教学 URL 第二次显示 memory cache、Size 变小、Timing 变快。当前最多能判断什么？', hint: '把浏览器本地线索与服务端事实分开。',
      options: [
        { label: '本次浏览器显示复用本地缓存，传输与时间测量较基线减少', rationale: '结论逐字对应缓存、Size 与 Timing 字段。', couldBeTrueWhen: '两次运行条件和 URL 已固定。' },
        { label: '后端数据库已经完成性能优化', rationale: '浏览器本地缓存可能绕过完整传输，不能证明数据库变化。', couldBeTrueWhen: '另有服务端与数据库对照证据。' },
        { label: '所有用户今后都会更快', rationale: '单浏览器单样本不能代表用户范围。', couldBeTrueWhen: '需要多环境、多样本和范围统计支持。' },
      ], answerIndex: 0,
      referenceAnswer: '只能说本次浏览器显示 memory cache，并且 Size 与 Timing 较同条件基线减少；服务端、数据库和全体用户体验仍未知。',
      reasoning: ['缓存来源是浏览器侧线索。', 'Size 与 Timing 是本次测量。', '范围结论需要更多样本。'],
      rubric: ['写明本次浏览器', '包含对照条件', '不归因后端或扩大范围'],
      commonErrors: [{ error: '速度变化等于根因', reason: '测量差异需要更多层证据才能解释为什么发生。' }],
      remediation: { label: '补看 Size 与缓存线索', sectionId: 'concepts', anchor: '#concept-network-size-cache' },
    },
    {
      id: 'w1d5-evidence-record', kind: 'open', categories: ['工作场景', '综合变式'], conceptIds: [...conceptIds],
      prompt: '请为一条 422、540ms、12kB、script 触发、network 加载的教学请求写四句式 Network 观察记录。', hint: '每句分别写看到、可以推断、还不能证明、下一步。',
      referenceAnswer: '看到：教学模拟中目标 URL 的 GET/fetch 请求由 script 触发，收到 422，Response 为 INVALID_FILTER，总 Timing 540ms、Size 12kB、来源为 network。可以推断：本次浏览器收到客户端错误类响应，错误正文指向筛选输入。还不能证明：具体责任代码、服务端实现、数据库状态和用户影响范围。下一步：在获准测试环境用同一脱敏输入复现，并补取同一请求的服务端校验日志。',
      reasoning: ['先列原始字段再做判断。', '422 与错误正文支持有限输入线索。', '下一步证据必须能验证竞争假设。'],
      rubric: ['四句结构完整', '至少覆盖八个 Network 字段', '所有数据标注教学模拟', '不凭单条请求证明后端或数据库事实'],
      commonErrors: [{ error: '直接写筛选接口有 Bug', reason: '当前只能确认本次响应类别和正文，根因与范围仍需复现和服务端证据。' }],
      remediation: { label: '补看 Network 证据边界', sectionId: 'concepts', anchor: '#concept-network-evidence-boundary' },
    },
  ],
  deliverable: {
    title: 'Network 观察记录', conceptIds: [...conceptIds],
    purpose: '让研发、测试和产品能够按同一环境、动作和目标条目复现浏览器观察，并清楚知道现有证据停在哪里。',
    whenToUse: '用于页面加载、请求错误、性能波动、体积变化或缓存疑问的浏览器侧初步交接。',
    audience: '前端研发、后端研发、测试和负责验收的产品经理。',
    fields: [
      { name: '环境、动作与时间', meaning: '固定教学环境、单次触发动作和发生时间。', source: '教学模拟操作记录' },
      { name: '请求条目与目标', meaning: '记录 Name 与脱敏 Request URL，确保选中正确条目。', source: 'Network 列表与 Headers / General' },
      { name: '列表列证据', meaning: '记录 Method、Status、Type 与 Initiator。', source: 'Network 请求列表' },
      { name: '详情字段证据', meaning: '分开记录 Headers、Payload 与 Response。', source: '所选条目详情标签' },
      { name: '测量与缓存线索', meaning: '记录 Timing、Size、缓存来源或协商字段与对照条件。', source: 'Timing、Size 列与缓存相关 Headers' },
      { name: '四句有限结论', meaning: '分别写看到、可以推断、还不能证明和下一步。', source: '全部原始字段与任务问题' },
    ],
    badExample: '页面很慢，Network 红了，后端接口和数据库肯定有问题，请尽快修复。',
    badReasons: ['没有环境、动作、目标 URL 和字段快照，别人无法复现。', '把颜色、一次慢请求和错误状态直接升级为后端与数据库根因。', '没有写未知事实与下一步取证路径。'],
    revisionSteps: ['先补环境、时间、单次动作与目标 Name／Request URL。', '逐项补 Method、Status、Type、Initiator、Headers、Payload 与 Response。', '加入 Timing、Size、缓存线索和相同条件对照。', '最后拆成看到、可以推断、还不能证明与下一步。'],
    goodExample: `【教学模拟】Network 观察记录
环境、动作与时间：本地教学页；2026-08-21 10:20；清空列表后点击一次“读取摘要”。
请求条目与目标：Name=summary.json；Request URL=https://training.invalid/api/summary?doc=demo-17。
列表列证据：Method=GET；Status=503；Type=fetch；Initiator=click-handler。
详情字段证据：Response Headers: Content-Type=application/json；Payload=无请求体；Response={code:"UPSTREAM_UNAVAILABLE"}。
测量与缓存线索：Timing=1840ms，其中等待=1600ms；Size=1.2kB；来源=network；对照基线=180ms/2.4kB。
四句有限结论：看到：本次教学请求收到503且等待占比高。可以推断：本次浏览器收到服务端错误类响应。还不能证明：具体后端组件、数据库状态与影响范围。下一步：在获准测试环境补同一请求的脱敏request id日志。`,
    guidedPrompts: ['环境、动作、时间与清空步骤是什么？', 'Name 与完整脱敏 Request URL 是什么？', 'Method、Status、Type、Initiator 分别显示什么？', 'Headers、Payload、Response 来自哪个方向？', 'Timing、Size 与缓存线索怎样相对基线变化？', '看到、推断、未知与下一步能否逐项回指证据？'],
    blankTemplate: `【教学模拟】Network 观察记录
环境、动作与时间：
请求条目与目标：
列表列证据：
详情字段证据：
测量与缓存线索：
四句有限结论：`,
    standardTemplate: `【教学模拟】Network 观察记录
环境、动作与时间：[环境]；[时间]；[清空后执行的单次动作]
请求条目与目标：Name=[ ]；Request URL=[脱敏地址]
列表列证据：Method=[ ]；Status=[ ]；Type=[ ]；Initiator=[ ]
详情字段证据：Headers=[请求/响应方向与关键字段]；Payload=[ ]；Response=[ ]
测量与缓存线索：Timing=[总值/主要阶段]；Size=[ ]；缓存=[ ]；对照条件=[ ]
四句有限结论：看到=[ ]；可以推断=[ ]；还不能证明=[ ]；下一步=[ ]`,
    checklist: ['环境、动作、时间与目标条目足以复现。', 'Name／URL、Method、Status、Type、Initiator 完整。', 'Headers、Payload、Response 方向明确且已脱敏。', 'Timing、Size 与缓存线索包含单位和对照条件。', '看到、推断、未知与下一步彼此分开。', '没有把单条 Network 请求写成后端实现或数据库事实。'],
  },
  memory: {
    conceptIds: [...conceptIds],
    anchors: ['先清空再执行一次动作，目标请求才有可复现起点。', 'Name 用于定位，Request URL 用于复核完整目标。', 'Headers、Payload、Response 必须按请求与响应方向分开。', 'Timing、Size 与缓存是本次测量和线索，不是根因。', 'Network 结论使用看到、推断、未知、下一步四句式。'],
    closedBookPrompt: '闭卷讲清从请求列表定位到详情、测量和四句有限结论的完整 Network 观察流程，并逐字段解释 Name／URL、Method、Status、Type、Initiator、Headers、Payload、Response、Timing、Size 与缓存线索。',
    microOperation: '任选一条脱敏教学请求，写出最小可复现字段快照，再删掉任何无法由 Network 直接支持的归因。',
    unresolvedPrompt: '当前还缺哪一类服务端、数据或用户范围证据，才能把浏览器线索升级为更强结论？',
    reviewStages: [
      { stage: 'D1', task: '闭卷画出请求列表、详情、测量、有限记录四步，并为每步写两个字段。' },
      { stage: 'D3', task: '对一条 422 教学请求写四句记录，解释为什么不能直接归因前端。' },
      { stage: 'D7', task: '比较 200/network 与 200/memory cache 两条同 URL 请求，写出有限差异结论。' },
      { stage: 'D14', task: '看到 503 与慢 Timing 时，列出三个竞争假设和各自需要补取的证据。' },
      { stage: 'D30', task: '审阅一份 Network 观察记录，找出字段方向错误、敏感信息与过度归因。' },
      { stage: 'D60', task: '独立完成一个新脱敏场景的 Network 观察记录，并由他人按复现性与证据边界复核。' },
    ],
  },
  nextLesson: {
    id: 'W1D6',
    title: '完整请求链路与综合诊断',
    bridge: '今天只学会从浏览器 Network 收集有限证据；下一课才把页面、寻址、HTTP、服务端职责与浏览器证据整合为分层诊断。',
  },
}
