import type { DailyCourse, Exercise } from './types'

const conceptIds = [
  'terminal-shell',
  'working-directory',
  'file-path',
  'safe-lab-copy',
  'sqlite-database-file',
  'sqlite3-session',
  'setup-sql-script',
  'table-row-column-preview',
] as const

function exercise(
  id: string,
  categories: Exercise['categories'],
  ids: string[],
  prompt: string,
  options: string[],
  answerIndex: number,
  referenceAnswer: string,
  remediationLabel: string,
): Exercise {
  return {
    id,
    kind: 'single-choice',
    categories,
    conceptIds: ids,
    prompt,
    hint: '先判断当前证据停在终端、路径、文件安全、SQLite 数据库、sqlite3 会话、setup.sql 脚本还是表结构预览哪一层。',
    options: options.map((label, index) => ({
      label,
      rationale: index === answerIndex ? '这项把操作前置、文件安全和证据边界连起来，适合作为 W3D1 的有限结论。' : '这项要么跳过终端/路径前置，要么把环境检查越界写成 SQL 查询或业务结论。',
      couldBeTrueWhen: index === answerIndex ? '当学习者只证明本地教学实验环境可安全打开和复现，不声称已经会写业务 SQL。' : '只有后续 W3D2–W3D6 完成 SELECT、条件、排序、聚合和业务查询后，才可能支撑更强结论。',
    })),
    answerIndex,
    referenceAnswer,
    reasoning: [
      'W3D1 的目标是把 SQL 实验运行前置补齐：终端、当前目录、路径、只读/副本安全、SQLite 数据库文件、sqlite3 会话和 setup.sql。',
      '能打开数据库或看到表结构，只能证明环境和数据入口可用；不能证明筛选、排序、聚合、JOIN 或业务结论正确。',
      '所有教学模拟都必须写清能证明什么、不能证明什么，避免把本地样本当成真实生产证据。',
    ],
    rubric: ['路径与当前目录清楚', '只读源和工作副本分开', 'sqlite3 会话可复现', '证据边界不过界'],
    commonErrors: [
      { error: '直接打开 answers.sql 或复制答案', reason: 'W3D1 还没有进入查询答案，本日先证明环境和文件安全。' },
      { error: '看到表名就宣布业务结论', reason: '表结构预览不是筛选、去重、金额或渠道统计证据。' },
    ],
    remediation: { label: remediationLabel, sectionId: 'concepts', anchor: `#concept-${ids[0]}` },
  }
}

export const w3d1: DailyCourse = {
  id: 'W3D1',
  contentVersion: 'w3d1-sqlite-environment-day01-v1',
  week: 3,
  day: 1,
  title: '打开 SQLite 实验环境',
  subtitle: '先补 SQL 运行前置：终端、当前目录、路径、只读源与工作副本、SQLite 数据库文件、sqlite3 会话、setup.sql 和表/行/列最小预览；本日只交付 sql-lab-runlog.md，不提前教学 SELECT 执行顺序、筛选、排序、聚合或 JOIN。',
  duration: { core: 30, standard: 45, extension: 66, full: 118 },
  coreConceptGroups: [
    {
      id: 'terminal-path-safety',
      title: '终端、路径与文件安全',
      conceptIds: ['terminal-shell', 'working-directory', 'file-path', 'safe-lab-copy'],
      summary: '先知道命令在哪里执行、目标文件在哪里、哪些文件只读、哪些文件可以复制后修改。',
      boundary: '路径和副本安全只能证明操作不会直接覆盖素材；不能证明 SQL 结果正确。',
    },
    {
      id: 'sqlite-runtime',
      title: 'SQLite 文件与会话',
      conceptIds: ['sqlite-database-file', 'sqlite3-session', 'setup-sql-script'],
      summary: 'SQLite 把数据库放在一个本地 .db 文件里；sqlite3 会话负责打开文件并执行脚本建立实验表。',
      boundary: '会话能打开和脚本能执行，只证明本地教学数据库被建立；不能证明真实生产库状态。',
    },
    {
      id: 'table-preview-boundary',
      title: '表结构预览与证据边界',
      conceptIds: ['table-row-column-preview'],
      summary: '第一次只预览表、行、列和字段含义，确认后续查询要面对的对象。',
      boundary: '预览不是查询分析，不提前替代 W3D2–W3D6 的 SELECT、筛选、聚合和业务问题回答。',
    },
  ],
  prerequisiteConceptIds: [],
  learningPaths: {
    '30': {
      guidedStepIndices: [0, 1, 2, 3, 4, 5],
      guidedRecordIndices: [0, 1, 2],
      exerciseCount: 3,
      deliverablePromptCount: 5,
      deliverableChecklistIndices: [0, 1, 2, 3, 4],
      deliverableMinimumContributionCharacters: 180,
    },
    '45': {
      guidedStepIndices: [0, 1, 2, 3, 4, 5],
      guidedRecordIndices: [0, 1, 2, 3],
      exerciseCount: 4,
      deliverablePromptCount: 7,
      deliverableChecklistIndices: [0, 1, 2, 3, 4, 5, 6],
      deliverableMinimumContributionCharacters: 280,
    },
  },
  primaryGoal: '提交 `sql-lab-runlog.md`：包含 lab_root、source_package、working_copy、terminal_command、current_directory、database_file、setup_script、sqlite3_check、schema_preview、first_row_preview、safety_boundary、cannot_prove、next_step。',
  scenario: {
    role: '你是准备进入 SQL 学习的产品经理实习生。',
    situation: '你拿到了 `public/labs/W3-SQL基础`，里面有 setup.sql、exercises.sql、answers.sql、README 和自检脚本；但你还不会在终端进入正确目录，也不知道 SQLite 数据库文件和安全副本怎么处理。',
    question: '怎样在不覆盖素材、不偷看答案、不伪造业务结论的前提下，把本地 SQLite 实验环境打开并留下可复现运行记录？',
    stakes: '如果路径和副本没搞清，后续 SQL 失败时无法复现；如果直接进入查询或答案，学习者会把环境问题误判成 SQL 能力问题。',
  },
  objectives: [
    { id: 'w3d1-objective-terminal', text: '能说明终端、当前目录和路径如何决定命令作用位置', evidence: '`sql-lab-runlog.md` 写出 terminal_command、current_directory 和 lab_root。' },
    { id: 'w3d1-objective-copy', text: '能把只读素材和可修改工作副本分开', evidence: '记录 source_package、working_copy 与不能覆盖 answers.sql 的安全边界。' },
    { id: 'w3d1-objective-sqlite', text: '能打开 SQLite 数据库文件并执行 setup.sql 建表', evidence: '记录 database_file、setup_script 和 sqlite3_check。' },
    { id: 'w3d1-objective-preview', text: '能预览 orders 表结构和一行样本但不越界解释业务', evidence: '记录 schema_preview、first_row_preview、cannot_prove 和 next_step。' },
  ],
  prerequisites: [
    {
      id: 'w3d1-computer-readiness',
      conceptIds: [],
      prompt: '你能打开本机终端，并确认自己不会在公司真实目录、真实数据库或生产数据上练习吗？',
      passDescription: '能使用本地教学目录，知道本日只处理教学模拟资料包，不碰真实公司数据。',
      remediationLabel: '先准备本地教学实验目录',
      remediationTarget: '#/course',
      remediation: {
        purpose: 'W3D1 可以提前观看；前置不足只影响实操结论，不锁全文。',
        steps: ['确认使用 `/Users/mac/Desktop/产品技术实验室/public/labs/W3-SQL基础`。', '不要在公司仓库、真实数据库或含隐私数据目录中练习。', '把本日结论限定为教学模拟环境。'],
        successCheck: '能说出本日所有证据只来自本地教学模拟资料包。',
      },
    },
  ],
  concepts: [
    {
      id: 'terminal-shell',
      prerequisiteConceptIds: [],
      term: '终端', english: 'Terminal / Shell',
      definition: '终端是输入命令并让系统执行的文本入口，shell 负责解释你输入的命令。',
      why: 'SQL 实验包的初始化、自检和脚本执行都要通过命令触发，不能只靠浏览器阅读。',
      problemSolved: '回答“我在哪里输入命令，命令由谁执行”。',
      input: '用户输入的命令文本，例如 pwd、cd、sqlite3。',
      output: '命令输出、错误信息、退出状态或新生成文件。',
      systemPosition: '位于学习者和本机文件/程序之间，是本地实验的操作入口。',
      process: ['打开本机终端窗口。', '输入一条可复现命令。', '读取输出和错误提示。'],
      owner: '学习者负责输入和记录；系统负责执行命令。',
      notResponsibleFor: '终端不判断 SQL 语义是否正确，也不证明业务结论。',
      compareWith: '浏览器展示页面；终端执行本机命令并返回文本结果。',
      evidence: ['完整命令文本。', '终端返回输出。', '错误提示原文。'],
      failureModes: ['把网页地址当成命令。', '忽略错误输出直接写通过。'],
      pmUse: '在和研发沟通 SQL 自检失败时，能提供具体命令和输出，而不是只说“跑不了”。',
      correctExample: '在终端运行 `pwd` 后记录当前路径。',
      incorrectExample: '只截图文件夹图标就说命令已经运行。',
    },
    {
      id: 'working-directory',
      prerequisiteConceptIds: ['terminal-shell'],
      term: '当前目录', english: 'Working Directory',
      definition: '当前目录是终端命令默认寻找文件和创建文件的位置。',
      why: '同一条 sqlite3 命令在不同目录执行，读取到的 setup.sql 和生成的 w3_lab.db 可能完全不同。',
      problemSolved: '回答“这条命令到底作用在哪个文件夹”。',
      input: '终端会话当前所在文件夹。',
      output: '相对路径命令的实际文件目标。',
      systemPosition: '夹在命令和文件系统之间，决定相对路径如何解析。',
      process: ['用 pwd 查看当前位置。', '用 cd 进入实验目录。', '再运行文件相关命令。'],
      owner: '学习者负责确认路径并记录证据。',
      notResponsibleFor: '当前目录不保证文件内容正确。',
      compareWith: '绝对路径直接从根目录定位；相对路径依赖当前目录。',
      evidence: ['pwd 输出。', 'ls 中出现 setup.sql。'],
      failureModes: ['在项目根目录运行实验脚本。', '复制命令但没有先进入实验目录。'],
      pmUse: '排查“我的脚本找不到文件”时，先问当前目录和文件是否同处一层。',
      correctExample: '`pwd` 显示 `.../public/labs/W3-SQL基础` 后再运行 sqlite3。',
      incorrectExample: '不看目录，直接执行 `sqlite3 w3_lab.db < setup.sql`。',
    },
    {
      id: 'file-path',
      prerequisiteConceptIds: ['working-directory'],
      term: '文件路径', english: 'File Path',
      definition: '文件路径是定位文件或文件夹的地址，可以是从根开始的绝对路径，也可以是相对当前目录的相对路径。',
      why: 'setup.sql、exercises.sql、notes-template.md 和 w3_lab.db 都靠路径被命令找到。',
      problemSolved: '回答“命令读的是哪个文件，写的是哪个文件”。',
      input: '文件名、相对路径或绝对路径。',
      output: '被打开、读取、复制或创建的具体文件。',
      systemPosition: '连接终端命令与文件系统对象。',
      process: ['确认文件名。', '判断相对还是绝对。', '用 ls 或测试命令验证存在。'],
      owner: '学习者记录路径；系统按路径解析。',
      notResponsibleFor: '路径存在不代表文件内容适合执行。',
      compareWith: 'URL 定位网络资源；文件路径定位本机文件。',
      evidence: ['ls 输出。', '命令中出现的文件名。', '错误提示 no such file。'],
      failureModes: ['中文目录或空格路径未处理。', '把压缩包路径当成已解压目录。'],
      pmUse: '向研发描述本地复现环境时，能交代实验包目录和数据库文件位置。',
      correctExample: '`public/labs/W3-SQL基础/setup.sql` 是项目内实验脚本路径。',
      incorrectExample: '只说“在那个 SQL 文件里”。',
    },
    {
      id: 'safe-lab-copy',
      prerequisiteConceptIds: ['file-path'],
      term: '安全副本', english: 'Safe Working Copy',
      definition: '安全副本是从只读素材复制出来、允许学习者修改和重跑的工作文件。',
      why: '练习时应修改 exercises.sql 或 notes.md 的副本，不能覆盖 setup.sql、answers.sql 或原始资料包。',
      problemSolved: '回答“哪些文件可以改，哪些文件必须保留原样”。',
      input: '只读源文件、复制命令和目标工作文件。',
      output: '可修改工作副本与可追溯来源。',
      systemPosition: '位于实验开始前，保护资料包和答案不被误改。',
      process: ['识别只读源。', '复制模板或练习文件。', '只在副本上记录或修改。'],
      owner: '学习者负责执行；课程门禁负责检查是否保留边界。',
      notResponsibleFor: '副本安全不证明 SQL 答案正确。',
      compareWith: '直接改源文件速度快但不可恢复；副本可重做、可对照。',
      evidence: ['cp notes-template.md notes.md。', 'runlog 中写明 answers.sql 不提前打开。'],
      failureModes: ['修改 answers.sql。', '重跑 setup.sql 前没有知道会覆盖哪一个 .db 文件。'],
      pmUse: '在真实工作中先复制脱敏样本或只读导出，避免污染原始证据。',
      correctExample: '把 notes-template.md 复制成 notes.md 后填写。',
      incorrectExample: '直接在 answers.sql 中练习并说自己完成了任务。',
    },
    {
      id: 'sqlite-database-file',
      prerequisiteConceptIds: ['safe-lab-copy'],
      term: 'SQLite 数据库文件', english: 'SQLite Database File',
      definition: 'SQLite 数据库通常就是一个本地 `.db` 文件，表和数据被存放在这个文件内部。',
      why: 'W3 实验不连接真实数据库服务器，而是在本地 w3_lab.db 中练习 SQL。',
      problemSolved: '回答“数据到底存在一个本地文件里，还是远程服务里”。',
      input: 'sqlite3 打开的 `.db` 文件名和 setup.sql。',
      output: '包含 orders 表的本地教学数据库文件。',
      systemPosition: '位于 sqlite3 会话和数据表之间，是本地数据库容器。',
      process: ['指定数据库文件名。', '执行脚本建表写入样本。', '后续查询都读取这个文件。'],
      owner: '学习者管理本地文件；课程素材定义教学数据。',
      notResponsibleFor: '本地 .db 不代表真实生产库或实时业务数据。',
      compareWith: '服务端数据库通常要连接地址、账号和权限；SQLite 本课只打开本地文件。',
      evidence: ['w3_lab.db 文件出现。', 'sqlite3 能打开。'],
      failureModes: ['把 w3_lab.db 当成真实公司数据库。', '在错误目录生成另一个同名 .db。'],
      pmUse: '理解为什么本课可以离线练习 SQL，同时知道它不能证明生产系统状态。',
      correctExample: '`sqlite3 w3_lab.db < setup.sql` 在本地生成教学数据库。',
      incorrectExample: 'w3_lab.db 有表，所以线上订单也一样。',
    },
    {
      id: 'sqlite3-session',
      prerequisiteConceptIds: ['sqlite-database-file'],
      term: 'sqlite3 会话', english: 'sqlite3 Session',
      definition: 'sqlite3 会话是命令行工具打开某个 SQLite 文件后接收 SQL 或点命令的运行现场。',
      why: '学习者需要知道自己是在工具会话里执行脚本，而不是在浏览器或真实数据库控制台里操作。',
      problemSolved: '回答“SQL 是在哪个工具、哪个数据库文件上运行”。',
      input: 'sqlite3 命令、数据库文件和输入脚本。',
      output: '执行结果、表结构、错误信息或退出状态。',
      systemPosition: '连接终端命令和 SQLite 数据库文件。',
      process: ['启动 sqlite3。', '确认打开目标 .db。', '执行脚本或预览命令。'],
      owner: '学习者负责命令和记录；sqlite3 工具负责执行。',
      notResponsibleFor: '会话成功不证明后续查询逻辑正确。',
      compareWith: '终端是外层命令入口；sqlite3 是专门执行 SQLite 的程序。',
      evidence: ['sqlite3 版本或执行输出。', '.tables 或 .schema 的返回。'],
      failureModes: ['未安装 sqlite3。', '打开了空数据库但以为已经导入数据。'],
      pmUse: '能向研发说明“我是在本地 sqlite3 会话复现，不是线上 SQL 客户端”。',
      correctExample: '`sqlite3 -header -column w3_lab.db` 后查看 `.tables`。',
      incorrectExample: '双击 .db 文件失败就认为数据库坏了。',
    },
    {
      id: 'setup-sql-script',
      prerequisiteConceptIds: ['sqlite3-session'],
      term: 'setup.sql 初始化脚本', english: 'Setup SQL Script',
      definition: 'setup.sql 是一次性建立教学表并插入样本数据的脚本。',
      why: '没有初始化脚本，后续 exercises.sql 找不到 orders 表；脚本可重跑也意味着本地数据库会回到教学初始状态。',
      problemSolved: '回答“orders 表和样本数据从哪里来”。',
      input: 'setup.sql 文件和目标 .db 文件。',
      output: 'orders 表、字段和固定教学样本。',
      systemPosition: '位于数据库文件创建之后、查询练习之前。',
      process: ['确认脚本在当前目录。', '把脚本输入 sqlite3。', '读取是否有错误输出。'],
      owner: '课程素材定义脚本；学习者负责在正确副本目录执行。',
      notResponsibleFor: 'setup.sql 不完成练习答案，也不做业务筛选。',
      compareWith: 'setup.sql 建环境；exercises.sql 才是后续要补的查询练习。',
      evidence: ['命令无错误。', '.schema orders 能看到字段。'],
      failureModes: ['把 answers.sql 当初始化脚本。', '跳过 setup 直接运行 exercises。'],
      pmUse: '在复现实验失败时先确认初始化是否成功，而不是直接质疑 SQL 题目。',
      correctExample: '`sqlite3 w3_lab.db < setup.sql` 后看到 orders 表。',
      incorrectExample: '运行 answers.sql 后说自己已经完成环境初始化。',
    },
    {
      id: 'table-row-column-preview',
      prerequisiteConceptIds: ['setup-sql-script'],
      term: '表/行/列预览', english: 'Table / Row / Column Preview',
      definition: '表/行/列预览是用最小读取确认表存在、字段含义和一行代表什么。',
      why: '第一次接触数据表时，先确认对象和粒度，再进入后续 SELECT、条件和聚合。',
      problemSolved: '回答“我要查询的对象长什么样，一行大概代表什么”。',
      input: 'orders 表结构和少量样本行。',
      output: 'schema_preview、first_row_preview 和一行代表的初步说明。',
      systemPosition: '位于环境验证之后、正式 SQL 查询教学之前。',
      process: ['查看表名是否存在。', '查看字段和字段含义。', '读取一行教学样本。', '写出不能证明事项。'],
      owner: '学习者负责记录和边界；后续课程负责查询逻辑。',
      notResponsibleFor: '预览不负责筛选、排序、聚合、去重、金额计算或 JOIN。',
      compareWith: '预览是认识对象；查询是按问题提取和计算证据。',
      evidence: ['.schema orders。', 'SELECT * FROM orders LIMIT 1 的教学模拟输出。'],
      failureModes: ['把第一行当全量统计。', '看到 paid_amount 字段就计算业务收入。'],
      pmUse: '在提取数据前先确认粒度和字段，不把未知表直接拿来下业务判断。',
      correctExample: '一行可能代表一条订单记录，但是否唯一要后续验证。',
      incorrectExample: '第一行 paid，所以全部订单都 paid。',
    },
  ],
  diagram: {
    title: 'W3D1 SQL 实验环境链路',
    caption: '命令从终端进入当前目录，读取安全副本和 setup.sql，生成本地 SQLite 数据库，再预览 orders 表；证据必须停在环境可复现层。',
    nodes: [
      { id: 'terminal', label: '终端命令入口', description: '输入命令并读取输出。', input: 'pwd、cd、sqlite3 等命令', output: '文本输出或错误提示', owner: '学习者本人', evidence: '命令和输出' },
      { id: 'path', label: '当前目录与路径', description: '决定命令读写哪个文件。', input: '当前目录和文件名', output: '实际读写文件目标', owner: '学习者本人', evidence: 'pwd、ls' },
      { id: 'copy', label: '安全副本', description: '保护只读素材和答案文件。', input: '模板和练习源文件', output: '可修改工作副本文件', owner: '学习者本人', evidence: 'notes.md 与 runlog' },
      { id: 'sqlite', label: 'SQLite 数据库文件', description: '本地教学数据容器。', input: 'setup.sql', output: 'w3_lab.db / orders 表', owner: 'sqlite3 工具', evidence: '.tables、.schema' },
      { id: 'preview', label: '表结构预览', description: '确认表、行、列和证据边界。', input: 'orders 教学表', output: 'schema_preview 与 first_row_preview', owner: '学习者本人', evidence: '有限预览记录' },
    ],
    branches: [
      { from: 'terminal', to: 'path', label: '先确认位置', kind: 'normal' },
      { from: 'path', to: 'copy', label: '保护素材', kind: 'normal' },
      { from: 'copy', to: 'sqlite', label: '初始化教学库', kind: 'normal' },
      { from: 'sqlite', to: 'preview', label: '只预览对象', kind: 'normal' },
      { from: 'path', to: 'sqlite', label: '目录错误生成空库', kind: 'failure' },
      { from: 'preview', to: 'preview', label: '预览越界成业务结论', kind: 'failure' },
    ],
    evidenceNotes: [
      '所有命令和结果都是本地教学模拟证据。',
      '能证明实验目录、SQLite 文件和 orders 表可打开；不能证明真实订单、真实收入或后续 SQL 正确。',
      '本日不提前教授 SELECT 执行顺序、WHERE、ORDER BY、COUNT、GROUP BY 或 JOIN。',
    ],
  },
  demonstration: {
    title: '教师示范：从实验包到本地 SQLite 环境记录',
    businessProblem: 'W3 SQL 查询练习要从实验包开始，但第一天先证明环境和文件安全可复现。',
    finalConclusion: '可以说“我在教学目录中建立了本地 w3_lab.db，并预览了 orders 表结构”。',
    conclusionLimit: '不能说“我已经完成业务查询”“金额正确”或“生产数据也如此”。',
    steps: [
      { title: '确认实验目录', action: '运行 pwd 与 ls，看到 README.md、setup.sql、exercises.sql。', reason: '先证明命令作用位置正确。', evidence: 'current_directory 指向 W3-SQL基础。', proves: '终端当前目录和实验包位置可复现。', limitation: '不证明 SQLite 已可用。' },
      { title: '建立安全副本', action: '复制 notes-template.md 为 notes.md，并声明 answers.sql 不提前打开。', reason: '保护原始素材和答案边界。', evidence: 'working_copy=notes.md。', proves: '记录文件可修改且来源可追溯。', limitation: '不证明查询答案正确。' },
      { title: '检查 sqlite3', action: '运行 sqlite3 版本检查或打开本地会话。', reason: '确认本机有执行 SQLite 的工具。', evidence: 'sqlite3_check 有版本或可执行结果。', proves: '工具入口可用。', limitation: '不证明数据库文件已有表。' },
      { title: '执行初始化脚本', action: '运行 sqlite3 w3_lab.db < setup.sql。', reason: '把教学样本写入本地数据库文件。', evidence: '命令无错误并生成 w3_lab.db。', proves: 'setup.sql 可在本地建立教学库。', limitation: '不证明 exercises.sql 已完成。' },
      { title: '预览 orders 表结构', action: '查看 orders 表字段和一行教学样本。', reason: '先认识对象和记录粒度。', evidence: 'schema_preview、first_row_preview。', proves: 'orders 表存在且字段可读。', limitation: '不证明筛选、排序、聚合或业务结论。' },
    ],
  },
  guidedLab: {
    title: 'SQLite 环境六路径观察器',
    goal: '用六条教学模拟路径判断 W3D1 环境记录是否合格：wrong-directory 目录错误、source-overwritten 素材被改、sqlite-missing sqlite3 缺失、setup-not-run setup 未执行、preview-overclaim 只预览却越界、qualified-sqlite-environment 合格环境。',
    safety: '教学模拟 · 不连接真实数据库、不读取真实公司数据、不打开生产环境、不提前查看 answers.sql。',
    conceptIds: [...conceptIds],
    predictionPrompt: '预测：如果当前目录错误或 setup.sql 没执行，后续 SQL 学习会先在哪一层失败？',
    steps: [
      { title: '记录当前目录', action: '确认命令运行位置并写入 current_directory。', observe: '目录是否含 README.md、setup.sql。', explanation: '目录决定相对路径读取对象。', proves: '命令作用位置可复现。', cannotProve: '不证明数据库内容正确。' },
      { title: '标记只读与副本', action: '写出 source_package、working_copy 和 answers.sql 边界。', observe: '工作副本是否与源文件分开。', explanation: '副本保护原始资料和答案。', proves: '文件安全策略可执行。', cannotProve: '不证明 SQL 题目已完成。' },
      { title: '检查 SQLite 工具', action: '记录 sqlite3_check。', observe: '工具可用或缺失。', explanation: '工具缺失时应先修环境。', proves: '本机执行入口状态。', cannotProve: '不证明 setup.sql 成功。' },
      { title: '运行 setup.sql', action: '记录 setup_script 和 database_file。', observe: 'w3_lab.db 是否可打开。', explanation: '初始化脚本建立教学表。', proves: '本地教学库可建立。', cannotProve: '不证明查询逻辑。' },
      { title: '预览表结构', action: '记录 schema_preview 和 first_row_preview。', observe: 'orders 字段和一行样本。', explanation: '预览只认识对象。', proves: '表/行/列可读。', cannotProve: '不证明业务答案。' },
      { title: '写出证据边界', action: '记录 can_prove、cannot_prove、next_step。', observe: '结论是否停在 W3D1 范围。', explanation: '环境证据不能冒充分析证据。', proves: '学习者理解本日边界。', cannotProve: '不证明 W3D2+ 内容已掌握。' },
    ],
    recordPrompts: [
      '记录 lab_root、current_directory 和你如何确认不是 wrong-directory。',
      '记录 source_package、working_copy，以及如何避免 source-overwritten 与提前打开 answers.sql。',
      '记录 database_file、setup_script、sqlite3_check 和表结构预览，用来区分 sqlite-missing 与 setup-not-run。',
      '用“能证明/不能证明/下一步”三句写出本日有限结论，避免 preview-overclaim，只在满足字段后标记 qualified-sqlite-environment。',
    ],
    comparePrompt: '对照 README 中的运行环境说明：你的记录是否只证明环境可复现，而没有提前声明 SQL 业务答案？',
    passCriteria: ['六条教学模拟路径都运行并记录。', '明确写出只读素材、工作副本和 answers.sql 边界。', 'schema_preview 与 first_row_preview 都存在。', 'cannot_prove 不包含真实生产或后续 SQL 结论。'],
  },
  independentLab: {
    title: '独立变式：换一个错误前置重新判断',
    scenario: '同学说“SQLite 题目坏了”，但只给出一张报错截图。你要先判断是路径、工具、setup、文件安全还是表预览问题。',
    conceptIds: [...conceptIds],
    changedConditions: ['当前目录是项目根目录，不是 W3-SQL基础。', 'w3_lab.db 是空文件，setup.sql 没执行。', 'notes.md 直接由 answers.sql 复制而来。', '只看到第一行 paid 订单就声称订单都已支付。'],
    task: '选择一个变式，写出先预测、检查计划、观察证据、有限结果和下一步补救。',
    predictionPrompt: '先预测这个失败最可能停在哪一层，并说明你要看哪条证据。',
    evidenceRequirements: ['必须引用终端命令、路径或 sqlite3 输出。', '必须写清不能证明真实业务结果或后续 SQL 正确。'],
    passCriteria: ['能定位到终端/路径/副本/sqlite3/setup/预览之一。', '有可执行补救动作。', '没有直接跳到 SELECT、聚合或 JOIN。', '历史尝试以追加方式保留。'],
    remediation: { label: '回看 W3D1 环境链路', sectionId: 'diagram', anchor: 'demonstration-conclusion' },
  },
  exercises: [
    exercise('w3d1-terminal-path', ['概念与边界', '工作场景'], ['terminal-shell', 'working-directory', 'file-path'], '同一条 `sqlite3 w3_lab.db < setup.sql` 在错误目录执行，最可能的问题是什么？', ['可能在错误位置生成或读取 w3_lab.db/setup.sql', 'SQLite 一定坏了', '业务订单一定为空'], 0, '当前目录决定相对路径。先用 pwd/ls 证明位置，再判断 sqlite3 或 SQL。', '回看终端、当前目录与路径'),
    exercise('w3d1-safe-copy', ['证据判断'], ['safe-lab-copy'], '哪条文件安全记录最合格？', ['source=README/setup.sql；working_copy=notes.md；answers.sql 不提前打开', '直接修改 answers.sql，能跑通就行', '把 zip 当工作目录'], 0, 'W3D1 要保护素材和答案边界，只在可修改副本里记录。', '回看安全副本'),
    exercise('w3d1-sqlite-setup', ['机制推演'], ['sqlite-database-file', 'sqlite3-session', 'setup-sql-script'], '`.tables` 看不到 orders 表，当前最稳妥的下一步是什么？', ['确认是否在正确目录对目标 w3_lab.db 执行了 setup.sql', '立刻开始写 GROUP BY', '直接宣布没有订单'], 0, '先排查数据库文件和初始化脚本，不能把环境缺失当业务结论。', '回看 SQLite 与 setup.sql'),
    exercise('w3d1-preview-boundary', ['综合变式'], ['table-row-column-preview'], '看到第一行订单 status=paid 后，哪条结论不越界？', ['orders 表可读，第一行样本为 paid；全量状态和金额还要后续查询验证', '所有订单已支付', '业务指标已经算完'], 0, '表预览只认识对象和样本，不承担全量筛选、聚合或业务回答。', '回看表/行/列预览'),
  ],
  deliverable: {
    title: 'SQL 实验环境记录',
    conceptIds: [...conceptIds],
    purpose: '让任何同学或未来的你能复现 W3 SQL 实验环境，并知道当前证据只到本地教学环境可用。',
    whenToUse: '在进入 W3D2 SELECT 执行逻辑和 W3D3 查询练习前，用来确认路径、SQLite 文件和实验边界。',
    audience: '未来继续学习 SQL 的自己、协助排查环境问题的研发同事或导师。',
    fields: [
      { name: 'lab_root', meaning: '实验包根目录和本地位置。', source: 'pwd 输出或项目路径' },
      { name: 'source_package', meaning: '只读素材来源和答案边界。', source: 'README/setup.sql/exercises.sql/answers.sql' },
      { name: 'working_copy', meaning: '可修改记录或练习副本。', source: 'notes.md 或 exercises.sql 副本' },
      { name: 'terminal_command', meaning: '关键终端命令文本。', source: '终端输入命令' },
      { name: 'current_directory', meaning: '命令执行所在文件夹。', source: 'pwd 命令输出' },
      { name: 'database_file', meaning: '本地 SQLite 数据库文件。', source: 'w3_lab.db 文件' },
      { name: 'setup_script', meaning: '初始化教学数据的脚本。', source: 'setup.sql 文件' },
      { name: 'sqlite3_check', meaning: 'sqlite3 工具或会话检查。', source: 'sqlite3 输出或错误提示' },
      { name: 'schema_preview', meaning: 'orders 表字段和类型预览。', source: '.schema orders 或等效教学输出' },
      { name: 'first_row_preview', meaning: '一行教学样本预览。', source: 'LIMIT 1 教学输出' },
      { name: 'safety_boundary', meaning: '只读、工作副本和答案边界。', source: '文件安全说明' },
      { name: 'cannot_prove', meaning: '本日环境证据不能证明的事项。', source: '证据边界说明' },
      { name: 'next_step', meaning: '下一步只进入 W3D2。', source: '课程路线说明' },
    ],
    badExample: '我已经把 SQL 都跑通了，订单数据没问题，后面可以直接算业务指标。数据库就是 w3_lab.db，答案也看过了。',
    badReasons: ['把环境打开越界写成 SQL 全部跑通。', '没有路径、当前目录和副本信息。', '提前打开答案并声称订单数据没问题。', '没有写不能证明真实业务或后续查询。'],
    revisionSteps: ['补 lab_root/current_directory。', '补 source_package 与 working_copy。', '补 sqlite3_check、setup_script、database_file。', '补 schema_preview 与 first_row_preview。', '补 safety_boundary、cannot_prove 与 W3D2 next_step。'],
    goodExample: 'lab_root: /Users/mac/Desktop/产品技术实验室/public/labs/W3-SQL基础\nsource_package: README.md、setup.sql、exercises.sql、notes-template.md；answers.sql 只作后续对照，不提前打开\nworking_copy: notes.md，由 notes-template.md 复制\nterminal_command: pwd；ls；sqlite3 w3_lab.db < setup.sql；sqlite3 -header -column w3_lab.db\ncurrent_directory: .../public/labs/W3-SQL基础\ndatabase_file: w3_lab.db，本地教学 SQLite 文件\nsetup_script: setup.sql，用于创建 orders 表和教学样本\nsqlite3_check: 教学模拟中 sqlite3 可打开 w3_lab.db\nschema_preview: orders(row_id, order_id, user_id, status, coupon_type, channel, paid_amount, paid_at, is_test)\nfirst_row_preview: 第一行是教学订单样本，不代表全量统计\nsafety_boundary: 不改 setup.sql/answers.sql；只在 notes.md 和后续 exercises.sql 副本中练习\ncannot_prove: 不能证明真实生产订单、收入、全量筛选、排序、聚合或 JOIN 结论\nnext_step: W3D2 学 SELECT 执行逻辑',
    guidedPrompts: ['写出 lab_root 和 current_directory。', '写出 source_package 和 working_copy。', '写出 terminal_command。', '写出 database_file 和 setup_script。', '写出 sqlite3_check。', '写出 schema_preview 和 first_row_preview。', '写出 safety_boundary、cannot_prove、next_step。'],
    blankTemplate: 'lab_root:\nsource_package:\nworking_copy:\nterminal_command:\ncurrent_directory:\ndatabase_file:\nsetup_script:\nsqlite3_check:\nschema_preview:\nfirst_row_preview:\nsafety_boundary:\ncannot_prove:\nnext_step:\n',
    standardTemplate: 'lab_root: public/labs/W3-SQL基础\nsource_package: README.md、setup.sql、exercises.sql、notes-template.md；answers.sql 不提前打开\nworking_copy: notes.md\nterminal_command: pwd；ls；sqlite3 w3_lab.db < setup.sql；sqlite3 -header -column w3_lab.db\ncurrent_directory: [填写 pwd 输出]\ndatabase_file: w3_lab.db\nsetup_script: setup.sql\nsqlite3_check: [填写 sqlite3 可用或缺失]\nschema_preview: [填写 orders 表字段]\nfirst_row_preview: [填写一行教学样本]\nsafety_boundary: [写清只读素材、工作副本、答案边界]\ncannot_prove: [写清不能证明真实生产、筛选、排序、聚合、JOIN 或业务结论]\nnext_step: W3D2 SELECT 执行逻辑\n',
    checklist: ['路径与当前目录可复现。', '只读源与工作副本分开。', 'answers.sql 没有提前作为答案来源。', 'sqlite3_check 与 setup_script 已记录。', 'schema_preview 和 first_row_preview 已记录。', 'cannot_prove 写清真实生产和后续 SQL 边界。', 'next_step 只指向 W3D2。'],
  },
  memory: {
    conceptIds: [...conceptIds],
    anchors: ['命令先问当前目录。', '路径决定读写对象。', '先复制安全副本再练习。', 'SQLite 本课是本地 .db 文件。', '预览不等于业务查询。'],
    closedBookPrompt: '闭卷解释：从打开终端到看到 orders 表预览，按顺序说明每一步输入、输出、能证明什么、不能证明什么。',
    microOperation: '不看正文，写出一条安全运行链：pwd → cd 实验目录 → cp 模板 → sqlite3 w3_lab.db < setup.sql → 预览 schema → 写 cannot_prove。',
    unresolvedPrompt: '写出你进入 W3D2 前最担心的一处环境风险，以及要用哪条证据先排除。',
    reviewStages: [
      { stage: 'D1', task: '复述终端、当前目录和路径的区别，并给出一个错误目录导致的失败。' },
      { stage: 'D3', task: '闭卷写出只读素材、工作副本和 answers.sql 边界。' },
      { stage: 'D7', task: '解释 SQLite 本地 .db 文件与真实生产数据库的区别。' },
      { stage: 'D14', task: '给出 setup.sql 能证明和不能证明的三句话。' },
      { stage: 'D30', task: '看到 orders 第一行样本后，写出两个不能越界的结论。' },
      { stage: 'D60', task: '重新写一份 SQL 实验环境记录字段清单，不看模板。' },
    ],
  },
  nextLesson: { id: 'W3D2', title: 'SELECT 执行逻辑', bridge: '下一课才进入 SELECT 语句如何读取列、行和结果顺序；W3D1 只负责环境、路径、SQLite 和预览边界。' },
}
