import type { DailyCourse, Exercise } from './types'

const conceptIds = [
  'sql-statement',
  'select-clause',
  'from-clause',
  'where-gate',
  'order-by-stage',
  'limit-stage',
  'execution-order',
  'result-boundary',
] as const

function exercise(
  id: string,
  categories: Exercise['categories'],
  ids: string[],
  prompt: string,
  options: string[],
  answerIndex: number,
  referenceAnswer: string,
  remediationLabel: string,
): Exercise {
  return {
    id,
    kind: 'single-choice',
    categories,
    conceptIds: ids,
    prompt,
    hint: '先按 FROM → WHERE → SELECT → ORDER BY → LIMIT 判断阶段，再写出结果能证明和不能证明什么。',
    options: options.map((label, index) => ({
      label,
      rationale: index === answerIndex ? '这项把 SQL 语句阶段、执行顺序和证据边界连起来，符合 W3D2 范围。' : '这项要么跳过执行顺序，要么提前进入聚合、GROUP BY、JOIN 或业务指标结论。',
      couldBeTrueWhen: index === answerIndex ? '当学习者只解释单表 SELECT 结果如何产生，不声称已经会完成业务查询集。' : '只有后续课程完成筛选练习、聚合、分组或 JOIN 后，才可能支撑更强结论。',
    })),
    answerIndex,
    referenceAnswer,
    reasoning: [
      'W3D2 首教 SQL 语句、SELECT 清单、FROM 数据源、WHERE 行过滤、ORDER BY 排序阶段、LIMIT 样本限制、执行顺序和结果边界。',
      '解释顺序时要从数据源开始，不按书写顺序误以为 SELECT 最先执行。',
      '本日不完成聚合、GROUP BY、JOIN 或真实业务指标，只交付 SQL 执行顺序图。',
    ],
    rubric: ['执行顺序正确', '字段与行的阶段分开', 'LIMIT 样本边界清楚', '不越界到聚合或 JOIN'],
    commonErrors: [
      { error: '按书写顺序解释 SELECT 最先执行', reason: 'SQL 文本先写 SELECT，但数据库通常先确定 FROM 数据源，再应用行级条件。' },
      { error: '把 LIMIT 5 当成全量结论', reason: 'LIMIT 只限制展示行数，不能证明全表数量或业务规模。' },
    ],
    remediation: { label: remediationLabel, sectionId: 'concepts', anchor: `#concept-${ids[0]}` },
  }
}

export const w3d2: DailyCourse = {
  id: 'W3D2',
  contentVersion: 'w3d2-select-execution-order-day01-v1',
  week: 3,
  day: 2,
  title: 'SELECT 执行逻辑',
  subtitle: '把一条单表 SELECT 拆成 FROM 数据源、WHERE 行过滤、SELECT 列清单、ORDER BY 排序和 LIMIT 样本边界；本日只交付 SQL 执行顺序图，不提前教学聚合、GROUP BY、JOIN 或指标计算。',
  duration: { core: 30, standard: 45, extension: 62, full: 112 },
  coreConceptGroups: [
    {
      id: 'select-source-and-shape',
      title: '语句、列清单与数据源',
      conceptIds: ['sql-statement', 'select-clause', 'from-clause'],
      summary: '先把 SQL 看成给数据库的取数说明：从哪张表来，最后输出哪些列。',
      boundary: '列清单和数据源能解释结果长什么样；不能证明条件、排序或全量业务结论。',
    },
    {
      id: 'row-order-window',
      title: '行过滤、排序与样本限制',
      conceptIds: ['where-gate', 'order-by-stage', 'limit-stage'],
      summary: 'WHERE 先决定哪些行留下，ORDER BY 再排结果，LIMIT 只截取展示窗口。',
      boundary: '这些阶段只覆盖单表基础执行逻辑，不进入聚合、GROUP BY、JOIN 或指标口径。',
    },
    {
      id: 'execution-evidence-boundary',
      title: '执行顺序与结果证据边界',
      conceptIds: ['execution-order', 'result-boundary'],
      summary: '用顺序图解释结果从哪里来，并写清看到的行数、列和排序最多能支持什么。',
      boundary: '执行顺序图证明你理解结果生成链，不代表业务查询集或生产数据已经验证。',
    },
  ],
  prerequisiteConceptIds: [
    'terminal-shell',
    'working-directory',
    'file-path',
    'safe-lab-copy',
    'sqlite-database-file',
    'sqlite3-session',
    'setup-sql-script',
    'table-row-column-preview',
  ],
  learningPaths: {
    '30': {
      guidedStepIndices: [0, 1, 2, 3, 4, 5],
      guidedRecordIndices: [0, 1, 2],
      exerciseCount: 3,
      deliverablePromptCount: 5,
      deliverableChecklistIndices: [0, 1, 2, 3, 4],
      deliverableMinimumContributionCharacters: 180,
    },
    '45': {
      guidedStepIndices: [0, 1, 2, 3, 4, 5],
      guidedRecordIndices: [0, 1, 2, 3],
      exerciseCount: 4,
      deliverablePromptCount: 7,
      deliverableChecklistIndices: [0, 1, 2, 3, 4, 5, 6],
      deliverableMinimumContributionCharacters: 280,
    },
  },
  primaryGoal: '提交 `sql-execution-order.md`：包含 business_question、base_table、source_rows、where_gate、select_columns、sort_rule、limit_window、execution_order、observed_result、can_prove、cannot_prove、next_sql_task。',
  scenario: {
    role: '你是开始写第一条 SQL 的产品经理实习生。',
    situation: 'W3D1 已经能打开本地 SQLite 教学库并预览 orders 表。现在同事给你一条查询样例，你需要解释每一段在结果生成中承担什么职责。',
    question: '怎样把一条单表 SELECT 从“看起来像咒语”拆成可检查的执行顺序图，并说明结果证据最多到哪里？',
    stakes: '如果把书写顺序误当执行顺序，后续筛选、排序、聚合和 JOIN 都会出现错误归因；如果把 LIMIT 样本当全量结论，产品判断会越界。',
  },
  objectives: [
    { id: 'w3d2-objective-order', text: '能闭卷画出 FROM → WHERE → SELECT → ORDER BY → LIMIT 的顺序', evidence: '`sql-execution-order.md` 写出 execution_order。' },
    { id: 'w3d2-objective-clause', text: '能说明每个子句的输入、输出和责任边界', evidence: '成果中逐项填写 base_table、where_gate、select_columns、sort_rule、limit_window。' },
    { id: 'w3d2-objective-evidence', text: '能把查询结果写成有限证据，不冒充业务指标', evidence: '成果中包含 observed_result、can_prove 和 cannot_prove。' },
    { id: 'w3d2-objective-next', text: '能把下一步限定到 W3D3 基础查询练习', evidence: 'next_sql_task 只指向 W3D3，不提前完成聚合、GROUP BY 或 JOIN。' },
  ],
  prerequisites: [
    {
      id: 'w3d2-sqlite-readiness',
      conceptIds: [
        'terminal-shell',
        'working-directory',
        'file-path',
        'safe-lab-copy',
        'sqlite-database-file',
        'sqlite3-session',
        'setup-sql-script',
        'table-row-column-preview',
      ],
      prompt: '你能打开 W3D1 建好的教学库，确认 orders 表存在，并说清本地教学模拟和真实生产数据的边界吗？',
      passDescription: '能提供 W3D1 的路径、w3_lab.db、setup.sql、orders 表预览和 cannot_prove 记录。',
      remediationLabel: '回到 W3D1 补环境记录',
      remediationTarget: '#/lesson/W3D1',
      remediation: {
        purpose: 'W3D2 可提前阅读；但没有 W3D1 环境证据时，不能把本日实操结果写成可复现证据。',
        steps: ['打开 W3D1，补齐 sql-lab-runlog.md 的 13 个字段。', '确认当前目录是 W3-SQL基础，orders 表可预览。', '确认不使用真实公司数据，也不提前打开 answers.sql。'],
        successCheck: '能说出 orders 表来自本地教学 setup.sql，且预览不等于业务查询正确。',
      },
    },
  ],
  concepts: [
    {
      id: 'sql-statement',
      prerequisiteConceptIds: ['sqlite3-session'],
      term: 'SQL 语句', english: 'SQL Statement',
      definition: 'SQL 语句是写给数据库的结构化请求，告诉它从哪张表取数据、留下哪些行、输出哪些列以及如何呈现结果。',
      why: '产品经理不一定要背所有语法，但必须能看出一条查询在问什么、依赖什么、结果从哪里来。',
      problemSolved: '回答“这段 SQL 想让数据库做哪件取数动作”。',
      input: '业务问题、数据表、字段、条件和展示要求。',
      output: '数据库返回的结果表或错误提示。',
      systemPosition: '位于 sqlite3 会话和数据表之间，是学习者向本地教学库发出的请求。',
      process: ['把业务问题改写成取数目标。', '按子句写出数据源、条件、列和展示要求。', '读取结果并写出证据边界。'],
      owner: '学习者负责提出语句；SQLite 负责解析和执行。',
      notResponsibleFor: 'SQL 语句本身不保证业务口径正确，也不代表真实生产数据。',
      compareWith: 'setup.sql 建立实验表；SELECT 语句从已存在的表读取结果。',
      evidence: ['完整 SQL 文本。', '本地执行输出。', '数据库错误提示。'],
      failureModes: ['复制答案但说不出每段作用。', '把 SQL 跑通误写成业务结论正确。'],
      pmUse: '评审数据需求时，能追问这条查询回答的是哪个问题、依赖哪些字段。',
      correctExample: '用一条 SELECT 读取 orders 表的 order_id、status 和 paid_at。',
      incorrectExample: '只说“跑一下 SQL”但没有业务问题、表或字段。',
    },
    {
      id: 'select-clause',
      prerequisiteConceptIds: ['sql-statement', 'table-row-column-preview'],
      term: 'SELECT 列清单', english: 'SELECT Clause',
      definition: 'SELECT 列清单说明最终结果要展示哪些列或表达式。',
      why: '同一批行可以输出全部字段，也可以只输出订单号、状态和支付时间；列清单决定结果形状。',
      problemSolved: '回答“结果表里要出现哪些列”。',
      input: '表中可用字段或后续已教学的表达式。',
      output: '结果集中的列名、列顺序和对应列值。',
      systemPosition: '在单表查询链路的输出成形阶段，通常晚于数据源和行过滤。',
      process: ['确认字段来自哪张表。', '只列出当前问题需要看的列。', '执行后检查输出列是否符合问题。'],
      owner: '学习者选择列；数据库返回列值。',
      notResponsibleFor: 'SELECT 列清单不负责决定从哪张表来，也不负责过滤行。',
      compareWith: 'WHERE 决定哪些行留下；SELECT 决定留下的行展示哪些列。',
      evidence: ['结果表列头。', '字段名是否存在的错误。'],
      failureModes: ['选择不存在的字段。', '输出过多字段导致证据噪声。'],
      pmUse: '把“给我订单数据”改成“需要订单号、用户、金额、支付时间这些列”。',
      correctExample: 'SELECT order_id, status, paid_at FROM orders。',
      incorrectExample: '以为 SELECT 写在最前面，所以它最先从全库找数据。',
    },
    {
      id: 'from-clause',
      prerequisiteConceptIds: ['sql-statement', 'table-row-column-preview'],
      term: 'FROM 数据源', english: 'FROM Clause',
      definition: 'FROM 指定这条查询从哪张表开始读取行。',
      why: '数据库必须先知道读取对象，后面的字段、条件和排序才有上下文。',
      problemSolved: '回答“这条查询面对的是哪张表”。',
      input: '表名或视图名，例如 orders。',
      output: '待处理的初始候选行集合和可引用字段范围。',
      systemPosition: '位于 SELECT 执行逻辑的起点，承接 W3D1 的表预览。',
      process: ['确认表存在。', '从表中形成候选行集合。', '把候选行交给后续 WHERE 或 SELECT 阶段。'],
      owner: '学习者指定数据源；SQLite 打开对应表。',
      notResponsibleFor: 'FROM 不负责业务筛选、排序、聚合或 JOIN。',
      compareWith: '文件路径定位本机文件；FROM 定位数据库里的表。',
      evidence: ['orders 表名存在。', '字段能被后续子句引用。'],
      failureModes: ['表名拼写错误。', '把 orders 表当成生产全量订单。'],
      pmUse: '追问数据来源是否正确，避免在错误表上讨论结果。',
      correctExample: 'FROM orders 表示本查询先从教学订单表读取候选行。',
      incorrectExample: '没有 FROM 却要求数据库知道订单字段来自哪里。',
    },
    {
      id: 'where-gate',
      prerequisiteConceptIds: ['from-clause'],
      term: 'WHERE 行过滤', english: 'WHERE Gate',
      definition: 'WHERE 是行级过滤门，按条件决定初始行集合中哪些行继续往后走。',
      why: '产品问题常常只关心某一天、某个状态或某类订单；WHERE 让结果从“全表”变成“符合条件的行”。',
      problemSolved: '回答“哪些行应该被留下，哪些行应先排除”。',
      input: 'FROM 给出的候选行和一个行级判断条件。',
      output: '通过条件后的结果行集合。',
      systemPosition: '在 FROM 之后、SELECT 输出列之前。',
      process: ['逐行判断条件。', '保留条件为真的行。', '把保留行交给输出列阶段。'],
      owner: '学习者写条件；数据库逐行判断。',
      notResponsibleFor: 'WHERE 不负责排序、分组、聚合或解释业务因果。',
      compareWith: 'SELECT 选列；WHERE 选行。',
      evidence: ['结果行少于或等于候选行。', '条件写错时结果为空或过多。'],
      failureModes: ['漏掉测试数据排除。', '把 WHERE 之后的样本行当成完整指标。'],
      pmUse: '把“只看已支付订单”翻译成可检查的行过滤要求。',
      correctExample: 'WHERE status = "paid" 表示只保留支付状态行。',
      incorrectExample: '用 SELECT status 以为就能过滤出 paid。',
    },
    {
      id: 'order-by-stage',
      prerequisiteConceptIds: ['where-gate'],
      term: 'ORDER BY 排序阶段', english: 'ORDER BY',
      definition: 'ORDER BY 决定结果行按哪个字段升序或降序展示。',
      why: '排序不改变哪些行符合条件，但会改变学习者最先看到哪几行。',
      problemSolved: '回答“结果展示顺序由什么决定”。',
      input: '已经留下并成形的结果行，以及排序字段和方向。',
      output: '按指定规则排列后的结果行集合。',
      systemPosition: '通常在行过滤和列输出之后、LIMIT 截取之前。',
      process: ['确认排序字段。', '选择 ASC 或 DESC。', '检查第一行是否符合排序预期。'],
      owner: '学习者指定排序规则；数据库排序。',
      notResponsibleFor: 'ORDER BY 不过滤行，也不计算汇总值。',
      compareWith: 'WHERE 改变行集合；ORDER BY 只改变展示顺序。',
      evidence: ['第一行和最后一行的排序字段。', '排序字段为空时的位置异常。'],
      failureModes: ['忘记排序却把默认顺序当时间顺序。', '把排序后前 5 行当全量最高结论。'],
      pmUse: '在看最新订单、最高金额或最早记录前，先确认排序规则。',
      correctExample: 'ORDER BY paid_at DESC 让较新的支付时间先显示。',
      incorrectExample: '没有 ORDER BY 却说第一行一定是最新订单。',
    },
    {
      id: 'limit-stage',
      prerequisiteConceptIds: ['order-by-stage'],
      term: 'LIMIT 样本窗口', english: 'LIMIT',
      definition: 'LIMIT 限制最终展示的行数，常用于先看样本或避免一次输出太多行。',
      why: '初学者需要先看少量结果确认查询方向，但 LIMIT 只能证明样本窗口，不证明全量。',
      problemSolved: '回答“这次只看多少行”。',
      input: '已经排序或未排序的结果集合，以及行数上限。',
      output: '被截取后的样本结果窗口。',
      systemPosition: '位于单表 SELECT 展示链路的末端。',
      process: ['先确认前面阶段结果。', '设置展示上限。', '记录 LIMIT 不能代表全量。'],
      owner: '学习者设置样本窗口；数据库截取结果。',
      notResponsibleFor: 'LIMIT 不负责判断总数、去重、金额或业务趋势。',
      compareWith: 'WHERE 过滤数据；LIMIT 只截断已经生成的结果窗口。',
      evidence: ['结果最多显示 N 行。', '去掉 LIMIT 后可能有更多行。'],
      failureModes: ['看到 LIMIT 10 的 10 行就认为只有 10 行。', '未排序时把 LIMIT 第一行当最新记录。'],
      pmUse: '先看样本验证字段含义，同时主动声明不能作为全量统计。',
      correctExample: 'LIMIT 5 只表示展示前 5 行样本。',
      incorrectExample: 'LIMIT 5 返回 5 行，所以当天只有 5 笔订单。',
    },
    {
      id: 'execution-order',
      prerequisiteConceptIds: ['limit-stage'],
      term: 'SELECT 执行顺序', english: 'SELECT Execution Order',
      definition: 'SELECT 执行顺序是数据库生成结果时各子句的大致工作顺序：先确定数据源，再过滤行，再形成输出列，随后排序并限制展示。',
      why: '理解顺序后，错误结果可以拆成“表错、条件错、列错、排序错、样本窗口错”几类。',
      problemSolved: '回答“结果为什么会长成现在这样”。',
      input: '一条单表 SELECT 查询和 orders 教学表。',
      output: '可解释的阶段图和阶段证据。',
      systemPosition: '把 SQL 文本、数据库表和结果证据连成一条可复述链路。',
      process: ['从 FROM 找数据源。', '用 WHERE 留行。', '用 SELECT 输出列。', '用 ORDER BY 排序。', '用 LIMIT 截取样本。'],
      owner: '学习者负责解释；数据库负责执行。',
      notResponsibleFor: '执行顺序图不覆盖聚合、GROUP BY、JOIN 或真实指标口径。',
      compareWith: '书写顺序是给人读的文本顺序；执行顺序是结果生成的机制顺序。',
      evidence: ['FROM 到 LIMIT 阶段图。', '每阶段输入输出。', '错误归因能落到具体阶段。'],
      failureModes: ['把 SELECT 写在前当成最先执行。', '把后续 GROUP BY 或 JOIN 混入本日图。'],
      pmUse: '和数据同事沟通时，能指出疑问停在数据源、条件、列、排序还是样本窗口。',
      correctExample: 'FROM orders → WHERE status="paid" → SELECT order_id,status → ORDER BY paid_at DESC → LIMIT 5。',
      incorrectExample: 'SELECT order_id 最先执行，然后才知道有没有 orders 表。',
    },
    {
      id: 'result-boundary',
      prerequisiteConceptIds: ['execution-order'],
      term: '查询结果证据边界', english: 'Result Evidence Boundary',
      definition: '查询结果证据边界说明一次结果能支持哪些有限判断，以及还不能支持哪些更强结论。',
      why: '产品工作里最危险的不是 SQL 报错，而是把样本、条件不全或教学数据包装成业务结论。',
      problemSolved: '回答“我看到了结果，但最多能说到哪一步”。',
      input: 'SQL 文本、执行输出、样本窗口和已知限制。',
      output: 'can_prove、cannot_prove 和 next_sql_task。',
      systemPosition: '位于结果解释阶段，连接本日学习证据和后续 W3D3 查询练习。',
      process: ['记录看到的行和列。', '说明结果来自本地教学模拟。', '列出未覆盖的全量、口径、聚合和 JOIN。'],
      owner: '学习者负责结论边界；后续课程负责增强证据。',
      notResponsibleFor: '边界声明不替代后续基础查询、聚合或对账。',
      compareWith: '运行成功是技术状态；证据边界是产品判断能否成立。',
      evidence: ['成果中的 can_prove。', '成果中的 cannot_prove。', '下一步任务不越界。'],
      failureModes: ['把教学模拟当生产证明。', '把单条 SELECT 当完整业务分析。'],
      pmUse: '在需求评审或数据沟通中，把“结果显示”改写成“当前证据只能说明”。',
      correctExample: '能证明这条样例查询按顺序生成了 5 行样本；不能证明当天真实收入。',
      incorrectExample: '查询返回 paid，所以业务增长已经成立。',
    },
  ],
  diagram: {
    title: '单表 SELECT 执行顺序图',
    caption: '从 orders 表出发，先确定数据源，再过滤行、选择列、排序和截取样本，最后写出有限证据。',
    nodes: [
      { id: 'business-question', label: '业务问题', description: '先明确想看什么。', input: '一个具体取数问题', output: '查询目标', owner: '学习者本人', evidence: 'business_question' },
      { id: 'from', label: 'FROM orders', description: '确定数据源和候选行。', input: 'orders 表', output: 'source_rows', owner: 'SQLite', evidence: 'base_table' },
      { id: 'where', label: 'WHERE 行过滤', description: '只留下符合条件的行。', input: 'FROM 候选行', output: 'filtered_rows 结果行', owner: 'SQLite', evidence: 'where_gate' },
      { id: 'select', label: 'SELECT 列清单', description: '决定输出哪些字段。', input: '留下的行', output: 'result_columns', owner: 'SQLite', evidence: 'select_columns' },
      { id: 'order-limit', label: 'ORDER BY + LIMIT', description: '排序并截取样本窗口。', input: 'SELECT 结果行', output: 'observed_result 样本', owner: 'SQLite', evidence: 'sort_rule 与 limit_window' },
      { id: 'boundary', label: '证据边界', description: '说明能/不能证明什么。', input: 'SQL 与结果', output: 'can_prove/cannot_prove', owner: '学习者本人', evidence: 'next_sql_task' },
    ],
    branches: [
      { from: 'business-question', to: 'from', label: '把问题落到表', kind: 'normal' },
      { from: 'from', to: 'where', label: '形成候选行', kind: 'normal' },
      { from: 'where', to: 'select', label: '留下行后选列', kind: 'normal' },
      { from: 'select', to: 'order-limit', label: '展示结果窗口', kind: 'normal' },
      { from: 'order-limit', to: 'boundary', label: '写有限结论', kind: 'normal' },
      { from: 'order-limit', to: 'boundary', label: 'LIMIT 样本越界成全量结论', kind: 'failure' },
    ],
    evidenceNotes: [
      '所有查询结果来自本地教学模拟 orders 表。',
      '能证明一条单表 SELECT 的结果生成路径；不能证明生产数据、业务指标、聚合、GROUP BY 或 JOIN。',
      '本日允许认识 WHERE、ORDER BY、LIMIT 的阶段职责，但不完成 W3D3 的 6 道基础查询集。',
    ],
  },
  demonstration: {
    title: '教师示范：把一条样例 SELECT 拆成执行顺序图',
    businessProblem: '想先查看 2026-08-31 教学订单中已支付记录的几个关键字段，确认查询结果如何被生成。',
    finalConclusion: '可以说“这条样例从 orders 表开始，经行过滤、列输出、排序和 LIMIT 形成 5 行教学样本”。',
    conclusionLimit: '不能说“已经算出当天收入”，也不能声称聚合、GROUP BY、JOIN 或真实生产订单已经被验证。',
    steps: [
      { title: '写出业务问题', action: '把“看订单”改成“看 2026-08-31 已支付教学订单样本”。', reason: 'SQL 必须服务一个具体问题。', evidence: 'business_question 明确。', proves: '查询意图不是泛泛而谈。', limitation: '不证明字段和条件已经正确。' },
      { title: '先确认 FROM 数据源', action: '从 FROM orders 开始解释候选行来自 orders 表。', reason: '没有数据源，字段和条件都没有上下文。', evidence: 'base_table=orders。', proves: '查询对象已定位。', limitation: '不证明全量数据或真实生产数据。' },
      { title: '再过 WHERE 行门', action: '说明 status="paid" 或日期条件会保留部分行。', reason: '过滤行发生在输出列之前。', evidence: 'where_gate 写出保留条件。', proves: '结果行来自条件判断。', limitation: '不证明后续所有筛选题都已掌握。' },
      { title: '输出 SELECT 列', action: '只输出 order_id、user_id、paid_at 等样本字段。', reason: '列清单决定结果形状。', evidence: 'select_columns 与结果列头一致。', proves: '输出字段可追溯。', limitation: '不证明排序或样本窗口。' },
      { title: '最后排序和截取', action: '用 ORDER BY paid_at DESC 和 LIMIT 5 解释看到的前 5 行。', reason: '排序改变展示顺序，LIMIT 改变展示窗口。', evidence: 'sort_rule、limit_window、observed_result。', proves: '结果窗口形成方式可解释。', limitation: '不证明只有 5 行，也不证明金额汇总。' },
      { title: '写清证据边界', action: '用 can_prove、cannot_prove、next_sql_task 收束结论。', reason: '运行成功不能自动变成业务判断。', evidence: 'cannot_prove 包含聚合/GROUP BY/JOIN/生产边界。', proves: '学习者能守住 W3D2 范围。', limitation: '不替代 W3D3 基础查询练习。' },
    ],
  },
  guidedLab: {
    title: 'SELECT 顺序六路径观察器',
    goal: '用六条教学模拟路径判断 SQL 执行顺序图是否合格：missing-from、where-before-source、select-column-mismatch、order-without-rule、limit-overclaim、qualified-select-order。',
    safety: '教学模拟 · 只读取本地 SQLite 教学表 orders，不连接真实数据库、不读取公司数据、不打开 answers.sql。',
    conceptIds: [...conceptIds],
    predictionPrompt: '预测：如果一条查询结果不对，先从数据源、行过滤、列清单、排序还是 LIMIT 哪一阶段查？',
    steps: [
      { title: '明确查询问题', action: '写出 business_question。', observe: '问题是否能落到 orders 表和一个样本结果。', explanation: '问题决定 SQL 是否有目标。', proves: '查询目标可复述。', cannotProve: '不证明结果正确。' },
      { title: '确认 FROM 数据源', action: '记录 base_table 与 source_rows。', observe: '是否从 orders 开始。', explanation: 'FROM 是执行逻辑起点。', proves: '字段和条件有来源。', cannotProve: '不证明筛选完整。' },
      { title: '检查 WHERE 行门', action: '记录 where_gate。', observe: '条件保留哪些行。', explanation: 'WHERE 改变行集合。', proves: '过滤阶段可解释。', cannotProve: '不证明聚合或分组。' },
      { title: '核对 SELECT 列', action: '记录 select_columns。', observe: '输出列头是否符合问题。', explanation: 'SELECT 决定结果形状。', proves: '结果列可追溯。', cannotProve: '不证明行顺序。' },
      { title: '观察 ORDER BY 与 LIMIT', action: '记录 sort_rule、limit_window、observed_result。', observe: '排序方向和样本行数。', explanation: '末端展示不能冒充全量。', proves: '结果窗口可解释。', cannotProve: '不证明总数或金额。' },
      { title: '收束证据边界', action: '记录 can_prove、cannot_prove、next_sql_task。', observe: '下一步是否只到 W3D3。', explanation: '边界阻止把样例查询说成业务分析。', proves: '结论没有越界。', cannotProve: '不证明后续 SQL 已掌握。' },
    ],
    recordPrompts: [
      '记录 business_question、base_table 和 source_rows，解释为什么 FROM 先于字段输出。',
      '记录 where_gate 与 select_columns，说明“选行”和“选列”的差别。',
      '记录 sort_rule、limit_window 和 observed_result，说明 LIMIT 为什么只是样本窗口。',
      '用 can_prove/cannot_prove/next_sql_task 写出 W3D2 的有限结论。',
    ],
    comparePrompt: '对照 W3D1 的 orders 表预览：你的顺序图是否只解释单表 SELECT 机制，没有提前完成 W3D3 查询集或 W4/W5 内容？',
    passCriteria: ['六条教学模拟路径都运行并记录。', '执行顺序必须包含 FROM → WHERE → SELECT → ORDER BY → LIMIT。', '明确 LIMIT 不是全量统计。', 'cannot_prove 不包含真实生产、聚合、GROUP BY 或 JOIN 已完成。'],
  },
  independentLab: {
    title: '独立变式：修正一张错误执行顺序图',
    scenario: '同学把 SELECT 写在第一步，并把 LIMIT 5 解释成“当天只有 5 笔订单”。你要只用本日概念修正，不提前给出完整业务查询答案。',
    conceptIds: [...conceptIds],
    changedConditions: ['漏写 FROM，却直接引用 order_id。', '把 SELECT 列清单画在 WHERE 之前。', '没有 ORDER BY，却把第一行说成最新订单。', 'LIMIT 5 返回 5 行，就声称全表只有 5 行。'],
    task: '选择一个错误图，写出错误阶段、正确顺序、可观察证据、不能证明事项和下一步练习。',
    predictionPrompt: '先预测这张图最可能在哪个阶段误导后续排查。',
    evidenceRequirements: ['必须引用 FROM/WHERE/SELECT/ORDER BY/LIMIT 中至少三个阶段。', '必须写清不能证明聚合、GROUP BY、JOIN、真实生产或完整业务指标。'],
    passCriteria: ['能把错误落到具体阶段。', '能画出正确执行顺序。', '写出 LIMIT 或排序的证据边界。', '下一步只进入 W3D3 基础查询练习。'],
    remediation: { label: '回看 SELECT 执行顺序图', sectionId: 'diagram', anchor: 'demonstration-conclusion' },
  },
  exercises: [
    exercise('w3d2-from-first', ['概念与边界', '机制推演'], ['from-clause', 'execution-order'], '解释 `SELECT order_id FROM orders` 时，哪一步应先发生？', ['先确认 FROM orders 作为数据源', '先把 order_id 输出给用户', '先计算每个渠道的订单数'], 0, '数据库要先确定 orders 表，才知道 order_id 字段来自哪里；聚合不是本日范围。', '回看 FROM 与执行顺序'),
    exercise('w3d2-row-vs-column', ['机制推演', '证据判断'], ['where-gate', 'select-clause'], 'WHERE 和 SELECT 最关键的区别是什么？', ['WHERE 决定留下哪些行，SELECT 决定输出哪些列', 'WHERE 负责排序，SELECT 负责连接表', 'SELECT 负责过滤行，WHERE 负责计算总金额'], 0, 'WHERE 是行门，SELECT 是列清单；排序、连接和金额计算都不是这两个概念的本日职责。', '回看选行与选列'),
    exercise('w3d2-limit-boundary', ['证据判断', '工作场景'], ['limit-stage', 'result-boundary'], '`LIMIT 5` 返回 5 行后，哪条结论最稳妥？', ['当前只看到 5 行样本，不能判断全表只有 5 行', '当天只有 5 笔订单', '收入已经计算完成'], 0, 'LIMIT 限制展示窗口，不是总数、收入或指标证明。', '回看 LIMIT 样本窗口'),
    exercise('w3d2-order-boundary', ['工作场景', '综合变式'], ['order-by-stage', 'execution-order', 'result-boundary'], '没有 ORDER BY 时，PM 说“第一行就是最新订单”，你应如何修正？', ['要求补排序规则，再把第一行结论限定为当前展示顺序', '直接认可，因为数据库默认按时间倒序', '改写成 GROUP BY channel'], 0, '没有排序规则时，第一行不能被解释为最新；GROUP BY 属于后续聚合课程。', '回看 ORDER BY 与证据边界'),
  ],
  deliverable: {
    title: 'SQL 执行顺序图',
    conceptIds: [...conceptIds],
    purpose: '让学习者用 sql-execution-order.md 解释一条单表 SELECT 结果如何产生，并把结果证据限制在本地教学模拟和本日机制范围。',
    whenToUse: '在进入 W3D3 的 6 道基础查询前，用来检查自己是否理解 FROM、WHERE、SELECT、ORDER BY、LIMIT 的职责和顺序。',
    audience: '未来继续写 SQL 的自己、协助检查查询思路的数据同事或导师。',
    fields: [
      { name: 'business_question', meaning: '这条查询要回答的具体问题。', source: '练习题或脱敏工作问题' },
      { name: 'base_table', meaning: 'FROM 阶段读取的数据源。', source: 'orders 表预览' },
      { name: 'source_rows', meaning: '进入 WHERE 前的候选行范围。', source: 'FROM orders 的解释' },
      { name: 'where_gate', meaning: '行过滤条件和留下/排除逻辑。', source: 'WHERE 子句' },
      { name: 'select_columns', meaning: '最终结果展示的列。', source: 'SELECT 列清单' },
      { name: 'sort_rule', meaning: '结果排序字段和方向。', source: 'ORDER BY 子句或“未指定”声明' },
      { name: 'limit_window', meaning: '样本窗口大小和限制。', source: 'LIMIT 子句' },
      { name: 'execution_order', meaning: 'FROM → WHERE → SELECT → ORDER BY → LIMIT 顺序图。', source: '本日概念关系图' },
      { name: 'observed_result', meaning: '这次看到的列、行数和样本。', source: '本地 SQLite 教学模拟输出' },
      { name: 'can_prove', meaning: '当前结果能支持的有限判断。', source: 'SQL 文本和输出' },
      { name: 'cannot_prove', meaning: '当前结果不能支持的业务、聚合、分组或连接结论。', source: '证据边界自检' },
      { name: 'next_sql_task', meaning: '下一步进入 W3D3 基础查询练习。', source: '课程路线' },
    ],
    badExample: 'SELECT 写在最前，所以先选列再从 orders 取数。LIMIT 5 返回 5 行，说明当天只有 5 笔订单。这个结果已经足够判断收入，后面可以直接讨论 GROUP BY 和 JOIN。',
    badReasons: ['把书写顺序当执行顺序。', '把 LIMIT 样本窗口冒充全量结论。', '提前声明聚合、GROUP BY 和 JOIN 已完成。', '没有写本地教学模拟和真实生产边界。'],
    revisionSteps: ['把执行顺序改成 FROM → WHERE → SELECT → ORDER BY → LIMIT。', '补 business_question、base_table 和 where_gate。', '补 observed_result，但只描述看到的样本。', '把 can_prove 限定为单表 SELECT 机制。', '把 cannot_prove 写清聚合/GROUP BY/JOIN/真实生产未证明。'],
    goodExample: 'business_question: 查看本地教学 orders 表中已支付订单的 5 行样本，理解结果如何产生\nbase_table: orders\nsource_rows: FROM orders 先形成候选行，来自 W3D1 setup.sql 建立的教学表\nwhere_gate: WHERE status = "paid" 只保留支付状态行；本日只解释行门作用\nselect_columns: order_id、user_id、status、paid_at\nsort_rule: ORDER BY paid_at DESC，较新的教学支付时间先显示；若未指定排序不能声称最新\nlimit_window: LIMIT 5，只展示 5 行样本，不代表全量\nexecution_order: FROM orders → WHERE status="paid" → SELECT order_id,user_id,status,paid_at → ORDER BY paid_at DESC → LIMIT 5\nobserved_result: 教学模拟中看到 5 行结果和 4 个输出列\ncan_prove: 能证明这条单表 SELECT 样例的阶段职责和结果窗口形成方式\ncannot_prove: 不能证明真实生产订单、当天收入、全量订单数、聚合、GROUP BY、JOIN 或业务指标正确\nnext_sql_task: W3D3 基础查询练习',
    guidedPrompts: ['写出 business_question。', '写出 base_table 和 source_rows。', '写出 where_gate。', '写出 select_columns。', '写出 sort_rule 和 limit_window。', '写出 execution_order 和 observed_result。', '写出 can_prove、cannot_prove、next_sql_task。'],
    blankTemplate: 'business_question:\nbase_table:\nsource_rows:\nwhere_gate:\nselect_columns:\nsort_rule:\nlimit_window:\nexecution_order:\nobserved_result:\ncan_prove:\ncannot_prove:\nnext_sql_task:\n',
    standardTemplate: 'business_question: 查看本地教学 orders 表的一条单表 SELECT 样例如何产生结果\nbase_table: orders\nsource_rows: FROM orders 形成候选行\nwhere_gate: [填写 WHERE 行过滤条件或“未设置”]\nselect_columns: [填写 SELECT 输出列]\nsort_rule: [填写 ORDER BY 字段/方向或“未指定，不能声称最新/最高”]\nlimit_window: [填写 LIMIT 样本窗口]\nexecution_order: FROM → WHERE → SELECT → ORDER BY → LIMIT\nobserved_result: [填写本地教学模拟看到的行数、列和样本]\ncan_prove: [写清能证明单表 SELECT 阶段职责]\ncannot_prove: [写清不能证明真实生产、全量、聚合、GROUP BY、JOIN 或业务指标]\nnext_sql_task: W3D3 基础查询练习\n',
    checklist: ['执行顺序是 FROM → WHERE → SELECT → ORDER BY → LIMIT。', '选行和选列没有混写。', '排序未指定时不声称最新或最高。', 'LIMIT 被写成样本窗口，不是全量结论。', 'observed_result 来自本地教学模拟。', 'cannot_prove 写清聚合、GROUP BY、JOIN 和真实生产边界。', 'next_sql_task 只指向 W3D3。'],
  },
  memory: {
    conceptIds: [...conceptIds],
    anchors: ['FROM 先定数据源。', 'WHERE 选行，SELECT 选列。', 'ORDER BY 只改展示顺序。', 'LIMIT 是样本窗口。', '结果必须写 cannot_prove。'],
    closedBookPrompt: '闭卷解释：一条单表 SELECT 如何从 orders 表生成结果？请按 FROM、WHERE、SELECT、ORDER BY、LIMIT 顺序说明输入、输出、证据和限制。',
    microOperation: '不看正文，写出一个顺序图：业务问题 → FROM orders → WHERE 行门 → SELECT 列 → ORDER BY → LIMIT → can_prove/cannot_prove。',
    unresolvedPrompt: '写出你进入 W3D3 前最容易混淆的一处：选行、选列、排序还是样本窗口？准备用哪条证据校正？',
    reviewStages: [
      { stage: 'D1', task: '闭卷写出 FROM → WHERE → SELECT → ORDER BY → LIMIT，并说明书写顺序为什么容易误导。' },
      { stage: 'D3', task: '给一条 LIMIT 5 结果写出 can_prove 和 cannot_prove。' },
      { stage: 'D7', task: '区分 WHERE 选行和 SELECT 选列，各举一个错误例子。' },
      { stage: 'D14', task: '解释没有 ORDER BY 时为什么不能声称第一行最新。' },
      { stage: 'D30', task: '把一条单表 SELECT 错误结果拆到数据源、条件、列、排序或 LIMIT 阶段。' },
      { stage: 'D60', task: '重新写一份 SQL 执行顺序图字段清单，不看模板。' },
    ],
  },
  nextLesson: { id: 'W3D3', title: '用户与订单基础查询', bridge: '下一课才把 WHERE、ORDER BY、日期条件和基础查询练成 6 道题；W3D2 只负责解释单表 SELECT 结果如何产生。' },
}
