import type { DailyCourse, Exercise } from './types'

const conceptIds = [
  'query-question',
  'where-condition',
  'comparison-operator',
  'text-value-filter',
  'date-range-boundary',
  'order-direction',
  'column-alias',
  'distinct-result',
] as const

const prerequisiteConceptIds = [
  'terminal-shell',
  'working-directory',
  'file-path',
  'safe-lab-copy',
  'sqlite-database-file',
  'sqlite3-session',
  'setup-sql-script',
  'table-row-column-preview',
  'sql-statement',
  'select-clause',
  'from-clause',
  'where-gate',
  'order-by-stage',
  'limit-stage',
  'execution-order',
  'result-boundary',
] as const

function exercise(
  id: string,
  categories: Exercise['categories'],
  ids: string[],
  prompt: string,
  options: string[],
  answerIndex: number,
  referenceAnswer: string,
  remediationLabel: string,
): Exercise {
  return {
    id,
    kind: 'single-choice',
    categories,
    conceptIds: ids,
    prompt,
    hint: '先把业务问题落到字段、WHERE 条件、日期边界、ORDER BY、别名或 DISTINCT，再判断结果能证明什么。',
    options: options.map((label, index) => ({
      label,
      rationale: index === answerIndex ? '这项把基础查询动作和证据边界连起来，符合 W3D3 的 6 道单表查询范围。' : '这项要么缺少可执行条件，要么提前进入聚合、GROUP BY、JOIN、指标或生产结论。',
      couldBeTrueWhen: index === answerIndex ? '当学习者只完成本地教学 orders 表的筛选、排序、别名、DISTINCT 和日期条件练习。' : '只有后续课程补齐数据质量、取数评审、聚合或 JOIN 后，才可能支持更强结论。',
    })),
    answerIndex,
    referenceAnswer,
    reasoning: [
      'W3D3 把 W3D2 的执行顺序练成 6 道基础查询：问题、条件、比较、文本值、日期边界、排序、别名和 DISTINCT。',
      '每条查询都必须写 observed_result、can_prove 和 cannot_prove，不能把本地教学模拟说成生产结论。',
      '本日不教学聚合、GROUP BY、JOIN、指标口径或数据质量诊断，只形成基础查询练习成果。',
    ],
    rubric: ['业务问题具体', 'SQL 动作和字段可追溯', '日期/排序/去重边界清楚', '不越界到后续主题'],
    commonErrors: [
      { error: '只写“查支付订单”但没有字段和条件', reason: 'SQL 需要可执行的表、列和值，模糊问题不能直接验证。' },
      { error: '把 DISTINCT 当成用户数或指标口径', reason: 'W3D3 只观察去重后的行或值，不计算指标分母。' },
    ],
    remediation: { label: remediationLabel, sectionId: 'concepts', anchor: `#concept-${ids[0]}` },
  }
}

export const w3d3: DailyCourse = {
  id: 'W3D3',
  contentVersion: 'w3d3-basic-sql-queries-day01-v6',
  week: 3,
  day: 3,
  title: '用户与订单基础查询',
  subtitle: '今天学的是单表基础查询：先看 orders 表的字段和样本行，再把“只看已支付订单、只看 app 渠道、看某一天支付订单”翻译成 6 条可运行 SQL；本日不提前教学数据质量诊断、聚合、GROUP BY、JOIN 或指标。',
  duration: { core: 30, standard: 45, extension: 68, full: 118 },
  coreConceptGroups: [
    {
      id: 'question-to-condition',
      title: '从业务问题到 WHERE 条件',
      conceptIds: ['query-question', 'where-condition', 'comparison-operator', 'text-value-filter', 'date-range-boundary'],
      summary: '先把“想看什么”改成具体字段、比较符和值，再把日期写成清楚的起止边界。',
      boundary: '能形成单表筛选证据；不能诊断空值、重复、时区或测试数据质量问题。',
    },
    {
      id: 'result-shape-and-order',
      title: '结果形状、排序和别名',
      conceptIds: ['order-direction', 'column-alias'],
      summary: 'ORDER BY 控制展示先后，AS 别名让结果列能被业务读懂。',
      boundary: '能说明展示规则；不能把排序后的样本当全量排名或趋势。',
    },
    {
      id: 'basic-dedup-boundary',
      title: 'DISTINCT 的基础去重观察',
      conceptIds: ['distinct-result'],
      summary: 'DISTINCT 只观察某些列组合去重后的结果行或取值，帮助发现重复展示。',
      boundary: '本日不把 DISTINCT 扩展成 COUNT DISTINCT、用户数口径、分母定义或指标计算。',
    },
  ],
  prerequisiteConceptIds: [...prerequisiteConceptIds],
  learningPaths: {
    '30': {
      guidedStepIndices: [0, 1, 2, 3, 4, 5],
      guidedRecordIndices: [0, 1, 2, 3, 4, 5],
      exerciseCount: 3,
      deliverablePromptCount: 6,
      deliverableChecklistIndices: [0, 1, 2, 3, 4],
      deliverableMinimumContributionCharacters: 220,
    },
    '45': {
      guidedStepIndices: [0, 1, 2, 3, 4, 5],
      guidedRecordIndices: [0, 1, 2, 3, 4, 5],
      exerciseCount: 4,
      deliverablePromptCount: 8,
      deliverableChecklistIndices: [0, 1, 2, 3, 4, 5, 6],
      deliverableMinimumContributionCharacters: 320,
    },
  },
  primaryGoal: '提交 `basic-sql-queries.sql` 与 `basic-query-log.md`：先把 Q1–Q6 六条 SQL 保存下来，再按题生成查询记录。每完成一题，只先写这题的业务问题、SQL、预期留下哪些行、实际看到什么、能证明什么和不能证明什么；完整字段只作为写完后的核验清单。',
  scenario: {
    role: '你是刚能解释 SELECT 顺序的产品经理实习生。',
    situation: '数据同事给了 orders 教学表。今天不从术语开始，而是先看字段和样本：order_id 是订单、user_id 是用户、status 是状态、channel 是渠道、paid_at 是支付时间；样本里同时有 paid、cancelled、refunded、app、web、miniapp 和具体到秒的 paid_at。',
    question: '怎样把一个用户与订单问题写成可执行的单表基础查询，并记录结果能证明和不能证明什么？',
    stakes: '如果条件、日期边界、排序或别名写错，后续数据质量判断、取数需求和指标讨论都会建立在不稳的查询证据上。',
  },
  objectives: [
    { id: 'w3d3-objective-six', text: '能完成 6 道本地教学基础查询并逐条记录', evidence: '`basic-query-log.md` 每条都有 query_id、sql_text 和 observed_result。' },
    { id: 'w3d3-objective-condition', text: '能把文本值、比较符和日期边界写成明确 WHERE 条件', evidence: '成果中包含 filter_condition 与 date_boundary，且不过早打开 answers.sql。' },
    { id: 'w3d3-objective-shape', text: '能使用 ORDER BY、AS 别名和 DISTINCT 说明结果展示', evidence: '成果中包含 sort_rule、alias_used、distinct_rule。' },
    { id: 'w3d3-objective-boundary', text: '能为每条查询写出有限结论和下一步', evidence: 'can_prove、cannot_prove、self_check_result、next_sql_task 均完整。' },
  ],
  prerequisites: [
    {
      id: 'w3d3-sql-foundation-readiness',
      conceptIds: [...prerequisiteConceptIds],
      prompt: '你能打开 W3D1 的本地 SQLite 教学库，并按 W3D2 解释 FROM → WHERE → SELECT → ORDER BY → LIMIT 吗？',
      passDescription: '能说明 orders 表来自 setup.sql，本地 sqlite3 会话可用，并能区分选行、选列、排序和样本窗口。',
      remediationLabel: '回到 W3D1/W3D2 补环境和 SELECT 顺序',
      remediationTarget: '#/lesson/W3D2',
      remediation: {
        purpose: 'W3D3 可提前阅读；但没有环境和执行顺序前置时，6 道查询只能当阅读练习，不能写成可复现实操证据。',
        steps: ['补齐 W3D1 的 sql-lab-runlog.md，确认 w3_lab.db 和 orders 表。', '补齐 W3D2 的 sql-execution-order.md，确认 FROM/WHERE/SELECT/ORDER BY/LIMIT 顺序。', '确认只使用 setup.sql、exercises.sql 与 self_check.sql；answers.sql 不提前打开。'],
        successCheck: '能说出每条 W3D3 查询先从 orders 表开始，再用条件、列、排序或 DISTINCT 形成有限结果。',
      },
    },
  ],
  concepts: [
    {
      id: 'query-question',
      prerequisiteConceptIds: ['sql-statement', 'result-boundary'],
      term: '查询问题', english: 'Query Question',
      definition: '查询问题是把业务疑问压成一条 SQL 能回答的具体问题，通常包含对象、范围、条件和期望看到的结果列。',
      why: '没有查询问题，SQL 很容易变成“随便看表”，结果也无法判断是否回答了需求。',
      problemSolved: '回答“这条 SQL 到底要验证哪个有限问题”。',
      input: '业务疑问、orders 表字段、需要观察的用户或订单范围。',
      output: '可执行的 business_question 和后续 SQL 草稿。',
      systemPosition: '位于写 SQL 之前，承接 W3D2 的执行顺序图，并决定本日 6 道查询的目标。',
      process: ['写清要看订单、用户、状态、渠道或时间。', '确认能落到 orders 表现有字段。', '把不能回答的部分放进 cannot_prove。'],
      owner: '学习者负责把业务话翻译成查询问题；SQLite 只执行明确语句。',
      notResponsibleFor: '查询问题不负责计算指标、诊断数据质量或证明生产业务结果。',
      compareWith: 'W3D2 的 business_question 用于解释样例；W3D3 的 query-question 要驱动 6 条可执行查询。',
      evidence: ['business_question 字段。', '对应的 sql_text。', 'cannot_prove 中被剔除的越界问题。'],
      failureModes: ['问题只写“看一下数据”。', '问题要求计算指标但本日没有教学聚合。'],
      pmUse: '当业务同事说“帮我查用户订单”时，先追问要看哪类订单、哪一天、哪些列。今天可执行的版本是“查看本地 orders 表中已支付订单的 order_id、user_id 和 paid_at”。',
      correctExample: '查看 2026-08-31 已支付教学订单的 order_id、user_id 和 paid_at。',
      incorrectExample: '算出真实业务 GMV 并判断活动效果。',
    },
    {
      id: 'where-condition',
      prerequisiteConceptIds: ['query-question', 'where-gate'],
      term: 'WHERE 条件', english: 'WHERE Condition',
      definition: 'WHERE 条件是写在 WHERE 后面的行级判断，用字段、比较符和值决定哪些订单行留下。',
      why: '产品问题通常只关心某类订单；条件不清楚时，结果会混入无关行。',
      problemSolved: '回答“哪些行应该进入这次结果，哪些行应该排除”。',
      input: 'orders 候选行、字段名、比较符和目标值。',
      output: '通过条件后的结果行集合。',
      systemPosition: '位于 FROM orders 之后、SELECT 输出列之前，是本日筛选练习的核心。',
      process: ['选择要判断的字段。', '写出比较符和值。', '执行后检查结果是否只保留目标行。'],
      owner: '学习者写条件；SQLite 逐行判断。',
      notResponsibleFor: 'WHERE 不负责排序、别名、去重观察、聚合、分组或连接。',
      compareWith: 'SELECT 决定输出列；WHERE 决定哪些行留下。',
      evidence: ['filter_condition 字段。', '结果中状态或日期列是否符合条件。'],
      failureModes: ['把 SELECT status 当成筛选。', '条件值漏引号导致文本比较失败。'],
      pmUse: '产品经理说“只看已支付订单”，数据库听不懂这句中文；你必须翻译成 WHERE status = "paid"，让 SQLite 逐行判断 status 是否等于 paid。',
      correctExample: 'WHERE status = "paid"。',
      incorrectExample: 'SELECT status FROM orders 后说已经筛掉未支付订单。',
    },
    {
      id: 'comparison-operator',
      prerequisiteConceptIds: ['where-condition'],
      term: '比较符', english: 'Comparison Operator',
      definition: '比较符把字段和值连接成判断，例如 =、!=、>=、<，让 SQLite 知道怎样逐行判断真假。',
      why: '筛选不是自然语言，必须把“等于、不是、晚于、早于”写成可执行符号。',
      problemSolved: '回答“字段和值之间是什么判断关系”。',
      input: '字段、目标值和业务边界。',
      output: '一段可执行的判断表达式。',
      systemPosition: '嵌在 WHERE 条件中，是文本值和日期边界都要依赖的基础部件。',
      process: ['先说中文判断。', '选择 =、!=、>=、< 等符号。', '用结果样本检查是否符合预期。'],
      owner: '学习者选择符号；SQLite 按符号计算真假。',
      notResponsibleFor: '比较符不负责解释为什么业务要选这个范围，也不负责修复脏数据。',
      compareWith: '= 看某个精确值；>= 和 < 常用来写时间闭开边界。',
      evidence: ['sql_text 中的符号。', 'observed_result 中被留下或排除的样本。'],
      failureModes: ['把中文“之后”写成错误方向。', '日期范围只写一边导致结果过宽。'],
      pmUse: '产品经理说“查 2026-08-31 当天支付订单”时，必须把“当天”翻译成 paid_at >= "2026-08-31" AND paid_at < "2026-09-01"，再用 status = "paid" 把支付状态说清。',
      correctExample: 'paid_at >= "2026-08-31" AND paid_at < "2026-09-01"。',
      incorrectExample: 'paid_at = "昨天"。',
    },
    {
      id: 'text-value-filter',
      prerequisiteConceptIds: ['comparison-operator'],
      term: '文本值筛选', english: 'Text Value Filter',
      definition: '文本值筛选是对 status、channel 这类文本字段使用引号包住的目标值进行行过滤。',
      why: '订单状态、渠道和来源经常是文本；少写引号或写错值会让结果为空或混入错误行。',
      problemSolved: '回答“只看某个文本状态或渠道的订单”。',
      input: '文本字段名、准确枚举值和比较符。',
      output: '符合文本值条件的订单行。',
      systemPosition: '属于 WHERE 条件的一种具体写法，常出现在基础查询第 1、2 题。',
      process: ['确认字段是文本枚举。', '使用引号写目标值。', '检查结果列中的值是否一致。'],
      owner: '学习者确认值和引号；SQLite 执行文本比较。',
      notResponsibleFor: '文本筛选不负责发现全部合法枚举，也不负责数据质量诊断。',
      compareWith: '文本值通常要引号；数字比较和日期边界需要另看字段含义。',
      evidence: ['filter_condition 中的 status 或 channel。', 'observed_result 中对应列的值。'],
      failureModes: ['把 paid 写成 PAID 却不确认数据值。', '漏引号导致执行错误或结果异常。'],
      pmUse: '产品经理说“只看 app 渠道订单”时，数据库不会理解“渠道”这句业务话；你要写成 WHERE channel = "app"，并检查结果里的 channel 是否都是 app。',
      correctExample: 'WHERE channel = "app"。',
      incorrectExample: 'WHERE channel = app。',
    },
    {
      id: 'date-range-boundary',
      prerequisiteConceptIds: ['comparison-operator'],
      term: '日期范围边界', english: 'Date Range Boundary',
      definition: '日期范围边界用明确的开始和结束条件限定时间窗口，常用“>= 起点 且 < 下一天/下一段起点”的写法。',
      why: '“当天”“昨天”“本周”如果没有边界，查询结果会被时间格式、时区或末尾时刻误导。',
      problemSolved: '回答“这次时间范围从哪里开始，到哪里停止”。',
      input: '时间字段、起始日期、结束边界和比较符。',
      output: '落在指定日期范围内的订单行。',
      systemPosition: '属于 WHERE 条件的时间版本，连接本日基础查询和后续数据质量课。',
      process: ['选择时间字段。', '写开始边界。', '写不包含的结束边界。', '在记录里说明本日不处理时区诊断。'],
      owner: '学习者声明边界；SQLite 按文本时间样本比较。',
      notResponsibleFor: '日期边界不负责时区换算、延迟刷新、NULL 处理或历史回溯。',
      compareWith: '文本筛选看一个枚举值；日期范围看一段连续窗口。',
      evidence: ['date_boundary 字段。', 'sql_text 中的 >= 与 <。', 'observed_result 的日期样本。'],
      failureModes: ['只写 paid_at = "2026-08-31" 但样本包含具体时间。', '没有结束边界导致跨天。'],
      pmUse: '产品经理说“查 8 月 31 日订单”时，数据库不会自动理解全天边界。你要把它写成 paid_at >= "2026-08-31" AND paid_at < "2026-09-01"，这样 2026-09-01 00:00:00 不会被误放进来。',
      correctExample: 'paid_at >= "2026-08-31" AND paid_at < "2026-09-01"。',
      incorrectExample: 'paid_at = "8月31日"。',
    },
    {
      id: 'order-direction',
      prerequisiteConceptIds: ['order-by-stage'],
      term: '排序方向', english: 'Order Direction',
      definition: '排序方向说明 ORDER BY 后结果按字段升序 ASC 还是降序 DESC 展示。',
      why: '“最新、最早、最高、最低”都依赖排序方向；没有方向就不能解释第一行代表什么。',
      problemSolved: '回答“结果先后顺序由哪个字段和方向决定”。',
      input: '排序字段和 ASC/DESC 方向。',
      output: '按指定字段和方向排列后的结果行集合。',
      systemPosition: '位于 WHERE 与 SELECT 结果形成之后，影响样本展示顺序。',
      process: ['选排序字段。', '写 ASC 或 DESC。', '检查第一行和最后一行是否符合预期。'],
      owner: '学习者写排序规则；SQLite 排列结果。',
      notResponsibleFor: '排序不改变哪些行留下，也不计算排名指标或趋势。',
      compareWith: 'WHERE 改变结果集合；ORDER BY 只改变展示顺序。',
      evidence: ['sort_rule 字段。', '结果首尾行的排序字段。'],
      failureModes: ['忘记 DESC 却说最新在前。', '未排序就把第一行当业务第一名。'],
      pmUse: '产品经理说“看最近订单”时，不能只加 LIMIT 5。必须写 ORDER BY paid_at DESC，才能说明第一行为什么代表更晚支付的订单。',
      correctExample: 'ORDER BY paid_at DESC。',
      incorrectExample: '没有 ORDER BY 却说第一行一定最新。',
    },
    {
      id: 'column-alias',
      prerequisiteConceptIds: ['select-clause'],
      term: '列别名', english: 'Column Alias',
      definition: '列别名用 AS 给结果列起一个更适合业务阅读的名字，不改变原表字段本身。',
      why: '查询结果要给人看；别名能让 order_id、paid_at 这类字段在记录中更容易交接。',
      problemSolved: '回答“结果列要用什么可读名称展示”。',
      input: 'SELECT 列清单和目标展示名称。',
      output: '带业务化列名的查询结果表。',
      systemPosition: '属于 SELECT 输出形状的一部分，发生在结果列展示阶段。',
      process: ['保留原字段来源。', '用 AS 写可读列名。', '记录别名不改变原始数据。'],
      owner: '学习者定义展示名；SQLite 返回别名列头。',
      notResponsibleFor: '别名不负责筛选、排序、去重或修改数据库表。',
      compareWith: '字段名是数据源里的原名；别名是这次结果里的展示名。',
      evidence: ['alias_used 字段。', '结果列头是否出现别名。'],
      failureModes: ['以为 AS 会改掉表结构。', '别名脱离业务含义导致交接不清。'],
      pmUse: '把 paid_at 展示为 paid_time，方便把查询结果贴进需求文档；同时记录它只是这次结果的列头，不是让研发改表字段。',
      correctExample: 'SELECT paid_at AS paid_time FROM orders。',
      incorrectExample: '用 AS 后声称数据库字段已经改名。',
    },
    {
      id: 'distinct-result',
      prerequisiteConceptIds: ['select-clause', 'result-boundary'],
      term: 'DISTINCT 结果去重', english: 'DISTINCT Result',
      definition: 'DISTINCT 让结果中相同的所选列组合只展示一次，用来观察有哪些不同取值或避免重复展示。',
      why: '初学者常把重复行看成多个事实；DISTINCT 可以先观察结果显示层的重复，但不能自动变成指标。',
      problemSolved: '回答“这次输出的列组合有哪些不重复结果”。',
      input: 'SELECT 中选择的列和 DISTINCT 关键字。',
      output: '按所选列组合去重后的结果行。',
      systemPosition: '属于 SELECT 结果形状控制，和 WHERE、ORDER BY 配合形成基础查询结果。',
      process: ['先决定要观察哪些列。', '在 SELECT 后加 DISTINCT。', '记录去重依据和不能证明的指标边界。'],
      owner: '学习者选择去重列；SQLite 返回不重复展示结果。',
      notResponsibleFor: 'DISTINCT 不负责计算用户数、定义分母、处理重复脏数据或完成指标口径。',
      compareWith: 'DISTINCT 去除结果展示重复；数据质量课才讨论重复来源和修复。',
      evidence: ['distinct_rule 字段。', 'observed_result 中不重复的列组合。'],
      failureModes: ['把 DISTINCT channel 说成渠道订单数。', '没有说明按哪些列组合去重。'],
      pmUse: '产品经理想知道“渠道字段里都有什么值”时，可以先用 SELECT DISTINCT channel FROM orders 看 app、miniapp、web；但这不是渠道订单数，也不是渠道转化指标。',
      correctExample: 'SELECT DISTINCT channel FROM orders。',
      incorrectExample: 'SELECT DISTINCT user_id 后直接说这就是活跃用户指标。',
    },
  ],
  diagram: {
    title: '6 道基础查询生成链',
    caption: '把业务问题依次落到 orders 表、WHERE 条件、日期边界、结果列、排序/别名/DISTINCT 和有限结论。',
    nodes: [
      { id: 'question', label: 'query_id + 业务问题', description: '每题先写清要回答的单表问题。', input: '练习题或脱敏问题', output: 'business_question', owner: '学习者本人', evidence: 'query_id' },
      { id: 'source', label: 'FROM orders', description: '所有练习只读取本地教学 orders 表。', input: 'W3D1 教学库', output: 'base_table', owner: 'SQLite', evidence: 'base_table=orders' },
      { id: 'filter', label: 'WHERE 条件', description: '用文本值、比较符和日期边界留下目标行。', input: 'FROM orders 形成的候选行', output: '通过条件的订单行', owner: 'SQLite 执行器', evidence: 'filter_condition/date_boundary' },
      { id: 'shape', label: 'SELECT + AS + DISTINCT', description: '决定输出列、业务别名和基础去重观察。', input: '留下的行', output: 'selected_columns', owner: 'SQLite', evidence: 'alias_used/distinct_rule' },
      { id: 'order', label: 'ORDER BY', description: '控制结果展示先后。', input: '已形成的结果行集合', output: '按规则排列的结果行', owner: 'SQLite 执行器', evidence: 'sort_rule' },
      { id: 'boundary', label: '查询记录边界', description: '写出观察结果、自检和不能证明事项。', input: 'SQL 与输出', output: 'can_prove/cannot_prove', owner: '学习者本人', evidence: 'basic-query-log.md' },
    ],
    branches: [
      { from: 'question', to: 'source', label: '落到本地表', kind: 'normal' },
      { from: 'source', to: 'filter', label: '筛选目标行', kind: 'normal' },
      { from: 'filter', to: 'shape', label: '输出结果列', kind: 'normal' },
      { from: 'shape', to: 'order', label: '决定展示顺序', kind: 'normal' },
      { from: 'order', to: 'boundary', label: '记录有限结论', kind: 'normal' },
      { from: 'shape', to: 'boundary', label: '把 DISTINCT 越界成指标', kind: 'failure' },
    ],
    evidenceNotes: [
      '所有 SQL 都来自本地教学模拟的 orders 表、exercises.sql 和 self_check.sql。',
      '能证明 6 道基础查询的字段、条件、排序、别名和 DISTINCT 结果可复核；不能证明生产数据、指标、聚合、GROUP BY 或 JOIN。',
      'answers.sql 只用于完成自检后对照，不能在预测和首次操作前暴露。',
    ],
  },
  demonstration: {
    title: '教师示范：把“查看已支付订单”写成基础查询记录',
    businessProblem: '想查看 2026-08-31 本地教学 orders 表中已支付订单的订单号、用户、支付时间，并让结果按支付时间倒序展示。',
    finalConclusion: '实际前 3 行为 O1018、O1018、O1013，paid_time 都在 2026-08-31 且按 paid_at 倒序排列。可以说“这条基础查询能在本地教学 orders 表中筛出指定日期已支付订单样本，并按 paid_at DESC 展示”。',
    conclusionLimit: '不能说真实生产订单、收入、用户数、数据质量、GROUP BY、JOIN 或指标已经被验证。',
    steps: [
      { title: '固定 query_id 与问题', action: '写 query_id=demo-paid-orders-on-20260831，并把问题限定到本地教学 orders 表。', reason: '每条查询需要可追溯编号和可执行问题，示范编号不要和 Q1–Q6 练习题混在一起。', evidence: 'query_id 与 business_question。', proves: '查询目标明确。', limitation: '不证明 SQL 已正确。' },
      { title: '写 WHERE 文本条件', action: '使用 WHERE status = "paid"。', reason: 'status 是文本值，必须写成明确比较。', evidence: 'filter_condition。', proves: '已支付订单行门可检查。', limitation: '不证明状态字段没有脏值。' },
      { title: '补齐日期边界', action: '写 paid_at >= "2026-08-31" AND paid_at < "2026-09-01"。', reason: '闭开边界比模糊“当天”更可复核。', evidence: 'date_boundary 字段完整。', proves: '时间范围有明确起止。', limitation: '不证明时区和延迟刷新。' },
      { title: '选择列并设置别名', action: '输出 order_id、user_id、status、paid_at AS paid_time。', reason: '列清单和别名让结果可读。', evidence: 'selected_columns 与 alias_used。', proves: '结果形状可追溯。', limitation: 'AS 不修改表字段。' },
      { title: '写清排序规则', action: '用 ORDER BY paid_at DESC。', reason: '只有排序规则才能解释最新样本为什么在前。', evidence: 'sort_rule 与首行 paid_at 样本。', proves: '结果展示顺序可以解释。', limitation: '排序不代表全量趋势。' },
      { title: '对照 self_check 后记录边界', action: '实际看到 O1018、O1018、O1013 后，运行 self_check.sql 或手工对照列/行/边界，再写 can_prove、cannot_prove。', reason: '操作完成后必须收束证据；O1018 出现两次只先记录为现象，重复来源留到 W3D4。', evidence: 'self_check_result、can_prove、cannot_prove。', proves: '本地基础查询可复核。', limitation: 'answers.sql 不能提前暴露，且不替代后续课程。' },
    ],
  },
  guidedLab: {
    title: '6 道基础查询练习台',
    goal: '用六道正向查询完成 W3D3 主线：q1-paid-orders、q2-app-channel-orders、q3-orders-on-20260831、q4-recent-paid-orders、q5-paid-time-alias、q6-distinct-channels。每题都写业务问题、SQL、预期留下哪些行、实际看到什么、能证明什么、不能证明什么。',
    safety: '教学模拟 · 只读取本地 SQLite 教学表 orders、exercises.sql 和 self_check.sql；不连接真实数据库、不读取公司数据、不提前打开 answers.sql。',
    conceptIds: [...conceptIds],
    predictionPrompt: '预测：先看 orders 表样本后，Q1–Q6 中哪一题最容易写错：paid 筛选、app 文本值、日期边界、倒序排序、paid_time 别名还是 DISTINCT channel？',
    steps: [
      { title: 'Q1 查已支付订单', action: '运行 SELECT order_id, user_id, status, paid_at FROM orders WHERE status = "paid" LIMIT 5;。', observe: '实际看到 O1001、O1002、O1004、O1006、O1007。', explanation: '把“只看已支付订单”翻译成 WHERE 文本条件。', proves: '能证明 paid 文本筛选可复核。', cannotProve: '不证明真实支付订单数、收入或 status 字段没有脏值。' },
      { title: 'Q2 查 app 渠道订单', action: '运行 SELECT order_id, channel, status FROM orders WHERE channel = "app" LIMIT 5;。', observe: '实际看到 O1001、O1003、O1004、O1007、O1009。', explanation: 'channel 是文本值，app 需要引号。', proves: '能证明 app 渠道筛选可复核。', cannotProve: '不证明渠道指标或测试订单是否应排除。' },
      { title: 'Q3 查 2026-08-31 当天支付订单', action: '运行 SELECT order_id, user_id, status, paid_at FROM orders WHERE status = "paid" AND paid_at >= "2026-08-31" AND paid_at < "2026-09-01" LIMIT 5;。', observe: '实际看到 O1001、O1002、O1004、O1006、O1007。', explanation: '“当天支付订单”同时需要 status 文本条件和 paid_at 起止边界。', proves: '能证明 paid 状态和日期窗口可以组合成可复核筛选。', cannotProve: '不证明时区、延迟刷新、NULL paid_at、重复或测试数据是否应排除。' },
      { title: 'Q4 按支付时间倒序看最近订单', action: '运行 SELECT order_id, user_id, paid_at FROM orders WHERE status = "paid" ORDER BY paid_at DESC LIMIT 5;。', observe: '实际看到 O1019、O1014、O1018、O1018、O1013。', explanation: 'ORDER BY paid_at DESC 才能支撑“最近”这个展示判断。', proves: '能证明排序规则可复核。', cannotProve: '不证明业务趋势，也不解释重复来源。' },
      { title: 'Q5 给 paid_at 起业务别名 paid_time', action: '运行 SELECT order_id, paid_at AS paid_time FROM orders WHERE status = "paid" ORDER BY paid_at DESC LIMIT 3;。', observe: '实际看到 O1019、O1014、O1018，列头为 paid_time。', explanation: 'AS 让结果列头可读，但不改表结构。', proves: '能证明结果展示列头可复核。', cannotProve: '不证明数据库字段已经改名。' },
      { title: 'Q6 用 DISTINCT channel 观察出现过的渠道取值', action: '运行 SELECT DISTINCT channel FROM orders ORDER BY channel;。', observe: '实际看到 app、miniapp、web。', explanation: 'DISTINCT 只观察不重复展示值。', proves: '能证明本地样本里出现过哪些 channel。', cannotProve: '不证明每个渠道订单数、渠道用户数或指标口径。' },
    ],
    recordPrompts: [
      '记录 Q1：query_id=q1-paid-orders；预期只留下 status = "paid" 的行；实际看到 O1001、O1002、O1004、O1006、O1007；补 filter_condition、sql_text、can_prove、cannot_prove。',
      '记录 Q2：query_id=q2-app-channel-orders；预期只留下 channel = "app" 的行；实际看到 O1001、O1003、O1004、O1007、O1009；补 filter_condition、date_boundary=本题不涉及日期、cannot_prove。',
      '记录 Q3：query_id=q3-orders-on-20260831；预期留下 status = "paid" 且 paid_at 在 2026-08-31 起止边界内的行；实际看到 O1001、O1002、O1004、O1006、O1007；补 date_boundary。',
      '记录 Q4：query_id=q4-recent-paid-orders；预期 paid 行按 paid_at DESC 展示；实际看到 O1019、O1014、O1018、O1018、O1013；补 sort_rule，并说明 LIMIT 5 不代表全量趋势。',
      '记录 Q5：query_id=q5-paid-time-alias；预期结果列头出现 paid_time；实际看到 O1019、O1014、O1018 三行的 paid_time；补 alias_used，并说明 AS 不修改原表字段。',
      '记录 Q6：query_id=q6-distinct-channels；预期相同 channel 只展示一次；实际看到 app、miniapp、web；补 distinct_rule，并说明 DISTINCT 不等于渠道订单数。',
    ],
    comparePrompt: '对照 exercises.sql 与 self_check.sql：你的 6 道查询是否完成预测、操作、观察、记录、解释和对照，并且没有提前打开 answers.sql？',
    passCriteria: ['Q1–Q6 六道正向查询都运行并记录。', '每道题都有业务问题、SQL、预期留下哪些行、实际看到什么、能证明什么、不能证明什么。', '日期边界必须有开始和结束。', 'DISTINCT 只写去重观察，不写成指标、聚合、GROUP BY 或 JOIN。'],
  },
  independentLab: {
    title: '独立变式：修正一组基础查询差稿',
    scenario: '同学完成了 6 道题，但其中有模糊问题、日期只写一天字符串、未排序却声称最新、别名无意义和 DISTINCT 越界成指标。你要只用 W3D3 概念修正。',
    conceptIds: [...conceptIds],
    changedConditions: ['business_question 只有“查订单”。', 'paid_at = "2026-08-31" 但样本时间带小时分钟。', '没有 ORDER BY 却把第一行说成最新订单。', 'SELECT paid_at AS x 导致业务读不懂。', 'SELECT DISTINCT channel 后声称已经算出渠道指标。'],
    task: '任选两处差稿，写出错误字段、修正 SQL、观察结果、能证明事项、不能证明事项和自检方式。',
    predictionPrompt: '先预测这组差稿最可能让后续 W3D4 误诊哪类问题。',
    evidenceRequirements: ['必须引用 WHERE、日期边界、ORDER BY、AS 或 DISTINCT 中至少三个动作。', '必须写清不能证明数据质量诊断、聚合、GROUP BY、JOIN、真实生产或业务指标。'],
    passCriteria: ['能把差稿错误落到具体字段。', '修正 SQL 仍为单表基础查询。', '写出 self_check_result 或对照方法。', '下一步只进入 W3D4 数据质量检查。'],
    remediation: { label: '回看 6 道基础查询生成链', sectionId: 'diagram', anchor: 'demonstration-conclusion' },
  },
  exercises: [
    exercise('w3d3-text-filter', ['概念与边界', '机制推演'], ['where-condition', 'text-value-filter'], '只看 app 渠道订单时，哪条条件最可执行？', ['WHERE channel = "app"', 'SELECT channel FROM orders', 'WHERE channel = app 并直接看结果'], 0, '文本值需要写成可执行比较，SELECT channel 只输出列，不筛选行。', '回看文本值筛选'),
    exercise('w3d3-date-boundary', ['机制推演', '证据判断'], ['date-range-boundary', 'comparison-operator'], '查看 2026-08-31 的支付时间，哪种日期写法边界最清楚？', ['paid_at >= "2026-08-31" AND paid_at < "2026-09-01"', 'paid_at = "8月31日"', 'paid_at LIKE "%31%" 并直接判断全天'], 0, '起点加不包含的结束边界更容易复核；模糊日期和字符串片段都容易误读。', '回看日期范围边界'),
    exercise('w3d3-order-alias', ['工作场景', '综合变式'], ['order-direction', 'column-alias'], '同事要“最近支付订单，列名能看懂”，哪组最稳妥？', ['paid_at AS paid_time，并 ORDER BY paid_at DESC', 'paid_at AS x，不写排序', '只 LIMIT 5 就说最新'], 0, '别名要表达业务含义，最近必须有 DESC 排序规则；LIMIT 不是排序。', '回看排序方向与别名'),
    exercise('w3d3-distinct-boundary', ['证据判断', '综合变式'], ['distinct-result', 'query-question'], '`SELECT DISTINCT channel FROM orders` 最多能证明什么？', ['本地教学结果中展示了哪些不重复 channel 取值', '已经算出各渠道订单数', '已经完成渠道指标口径'], 0, 'DISTINCT channel 只展示不同渠道取值，不计算数量、指标或分母。', '回看 DISTINCT 边界'),
  ],
  deliverable: {
    title: '6 道基础查询',
    conceptIds: [...conceptIds],
    purpose: '让学习者用 basic-sql-queries.sql 保存可执行 SQL，用 basic-query-log.md 按 Q1 到 Q6 逐题生成记录：完成一题就生成一条，不先要求面对 15 个字段。每条记录先写业务问题和 SQL，再写预期留下哪些行、实际看到什么、能证明什么和不能证明什么；写完后再补 selected_columns、filter_condition、date_boundary、sort_rule、alias_used、distinct_rule 等自检字段。',
    whenToUse: '在进入 W3D4 数据质量检查前，用来确认自己能把用户与订单问题写成可执行且不过界的基础 SQL。',
    audience: '未来继续做数据质量诊断的自己、协助检查 SQL 的数据同事或导师。',
    fields: [
      { name: 'query_id', meaning: '6 道基础查询的编号。', source: 'exercises.sql' },
      { name: 'business_question', meaning: '这条查询要回答的有限问题。', source: '题目或脱敏工作问题' },
      { name: 'base_table', meaning: '本日只允许使用 orders。', source: 'W3D1 setup.sql' },
      { name: 'selected_columns', meaning: 'SELECT 输出列。', source: 'SQL 文本' },
      { name: 'filter_condition', meaning: 'WHERE 条件。', source: 'SQL 文本' },
      { name: 'date_boundary', meaning: '日期起点和结束边界。', source: 'SQL 文本与题目' },
      { name: 'sort_rule', meaning: 'ORDER BY 字段和方向。', source: 'SQL 文本或边界声明' },
      { name: 'alias_used', meaning: 'AS 别名及其业务含义。', source: '结果列头' },
      { name: 'distinct_rule', meaning: 'DISTINCT 按哪些列组合去重展示。', source: 'SQL 文本与结果' },
      { name: 'sql_text', meaning: '完整可执行 SQL。', source: 'basic-sql-queries.sql' },
      { name: 'observed_result', meaning: '本地教学模拟看到的列、行或样本。', source: 'sqlite3 输出' },
      { name: 'can_prove', meaning: '当前查询能证明的有限判断。', source: 'SQL 和输出' },
      { name: 'cannot_prove', meaning: '当前查询不能证明的生产、质量、指标或后续主题。', source: '证据边界自检' },
      { name: 'self_check_result', meaning: 'self_check.sql 或人工对照结果。', source: '自检输出' },
      { name: 'next_sql_task', meaning: '下一步只进入 W3D4 数据质量检查。', source: '课程路线' },
    ],
    badExample: 'query_id: Q1\nbusiness_question: 查订单\nsql_text: SELECT DISTINCT user_id FROM orders LIMIT 5;\nobserved_result: 有 5 行，所以说明用户数是 5，渠道指标也完成了。下一步直接做 GROUP BY 和 JOIN。',
    badReasons: ['业务问题不可执行。', '没有 WHERE、日期边界、排序、别名或自检记录。', '把 DISTINCT 和 LIMIT 越界成用户数或指标。', '提前进入 GROUP BY 和 JOIN。'],
    revisionSteps: ['先把差稿拆成 Q1–Q6 六条记录，每条只回答一个具体问题。', '每条先补 query_id、business_question、sql_text、预期留下哪些行和实际看到什么。', '再补 selected_columns、filter_condition、date_boundary、sort_rule、alias_used、distinct_rule；本题没用到就写“本题不使用”。', '运行或对照 self_check.sql 后记录 observed_result 和 self_check_result。', '把 can_prove/cannot_prove 限定到本地教学基础查询，并把 next_sql_task 指向 W3D4。'],
    goodExample: 'query_id: Q3_orders_on_20260831\nbusiness_question: 查看 2026-08-31 当天已支付的本地 orders 订单样本\nbase_table: orders\nselected_columns: order_id、user_id、status、paid_at\nfilter_condition: status = "paid"\ndate_boundary: paid_at >= "2026-08-31" AND paid_at < "2026-09-01"\nsort_rule: 本题未指定排序，不能声称最新或最早\nalias_used: 本题不使用别名\ndistinct_rule: 本题不使用 DISTINCT\nsql_text: SELECT order_id, user_id, status, paid_at FROM orders WHERE status = "paid" AND paid_at >= "2026-08-31" AND paid_at < "2026-09-01" LIMIT 5;\nobserved_result: 看到 O1001、O1002、O1004、O1006、O1007，status 均为 paid，paid_at 均落在边界内\ncan_prove: 能证明这条基础查询把 paid 状态和日期起止边界组合成可复核筛选\ncannot_prove: 不能证明真实生产收入、时区正确、NULL paid_at、重复行、测试数据、聚合、GROUP BY、JOIN 或指标正确\nself_check_result: self_check.sql 对照通过；未提前打开 answers.sql\nnext_sql_task: W3D4 数据质量检查',
    guidedPrompts: ['Q1：先写“查已支付订单”的业务问题和 SQL。', 'Q2：先写“查 app 渠道订单”的业务问题和 SQL。', 'Q3：先写“查 2026-08-31 当天支付订单”的日期边界和 SQL。', 'Q4：先写“按支付时间倒序看最近订单”的排序规则和 SQL。', 'Q5：先写 paid_at AS paid_time 的别名说明。', 'Q6：先写 DISTINCT channel 的去重观察。', '每题都补 observed_result、can_prove、cannot_prove。', '最后统一用 15 个字段做自检，不提前打开 answers.sql。'],
    blankTemplate: 'query_id:\nbusiness_question:\nbase_table:\nselected_columns:\nfilter_condition:\ndate_boundary:\nsort_rule:\nalias_used:\ndistinct_rule:\nsql_text:\nobserved_result:\ncan_prove:\ncannot_prove:\nself_check_result:\nnext_sql_task:\n',
    standardTemplate: '每完成一题，就复制一段记录；不要先面对整张验收清单。\n\nquery_id: q1-paid-orders\nbusiness_question: 查看本地教学 orders 表中已支付订单样本\nbase_table: orders\nselected_columns: order_id、user_id、status、paid_at\nfilter_condition: status = "paid"\ndate_boundary: 本题不涉及日期\nsort_rule: 本题未指定排序，不能声称最新或最高\nalias_used: 本题不使用别名\ndistinct_rule: 本题不使用 DISTINCT\nsql_text: SELECT order_id, user_id, status, paid_at FROM orders WHERE status = "paid" LIMIT 5;\nobserved_result: 教学模拟看到 O1001、O1002、O1004、O1006、O1007\ncan_prove: 能证明 status = "paid" 这个基础筛选条件可复核\ncannot_prove: 不能证明真实生产、数据质量、聚合、GROUP BY、JOIN、业务指标或收入\nself_check_result: self_check.sql 对照通过；未提前打开 answers.sql\nnext_sql_task: W3D4 数据质量检查\n\n继续逐题生成：\nq2-app-channel-orders：先填 business_question、sql_text、filter_condition=channel = "app"，observed_result=O1001、O1003、O1004、O1007、O1009。\nq3-orders-on-20260831：先填 date_boundary=paid_at >= "2026-08-31" AND paid_at < "2026-09-01"，再写 observed_result。\nq4-recent-paid-orders：先填 sort_rule=ORDER BY paid_at DESC，说明 LIMIT 5 只是展示窗口。\nq5-paid-time-alias：先填 alias_used=paid_at AS paid_time，说明 AS 不修改表字段。\nq6-distinct-channels：先填 distinct_rule=SELECT DISTINCT channel，observed_result=app、miniapp、web，说明它不是渠道订单数。\n每题都保留 can_prove、cannot_prove、self_check_result、next_sql_task。\n',
    checklist: ['6 道查询都有 query_id 和 sql_text。', 'base_table 均为 orders。', 'WHERE 文本值使用引号，日期边界有起点和结束。', 'ORDER BY 写明字段和 ASC/DESC；未排序时不声称最新或最高。', 'AS 别名只改变结果列头，不声称修改表结构。', 'DISTINCT 只写去重观察，不写成指标或用户数口径。', 'self_check_result 完成，且 answers.sql 没有提前暴露。', 'next_sql_task 只指向 W3D4 数据质量检查。'],
  },
  memory: {
    conceptIds: [...conceptIds],
    anchors: ['先写 query_id 和业务问题。', 'WHERE 需要字段、比较符和值。', '日期边界写起点和结束。', 'ORDER BY 才能解释最新/最高。', 'AS 改展示列名，DISTINCT 只做去重观察。'],
    closedBookPrompt: '闭卷解释：怎样把一个用户与订单问题写成基础 SQL？请按 query_id、WHERE、比较符、文本值、日期边界、ORDER BY、AS、DISTINCT 和 evidence boundary 复述。',
    microOperation: '不看正文，写一条查询：从 orders 查某天 paid 订单，输出 3 个列，给 paid_at 起别名，按 paid_at DESC 排序，并写 cannot_prove。',
    unresolvedPrompt: '写出你进入 W3D4 前最容易混淆的一处：日期边界、排序方向、别名还是 DISTINCT？准备怎么用 self_check 校正？',
    reviewStages: [
      { stage: 'D1', task: '闭卷写出一条 status 文本筛选查询，并说明 SELECT 和 WHERE 的差别。' },
      { stage: 'D3', task: '写出 2026-08-31 的日期起止边界，并说明为什么不用模糊“当天”。' },
      { stage: 'D7', task: '解释 ORDER BY DESC 和 LIMIT 的边界：哪个决定顺序，哪个只截取样本。' },
      { stage: 'D14', task: '给一条 SELECT 结果补 AS 别名，并说明它不修改表结构。' },
      { stage: 'D30', task: '解释 SELECT DISTINCT channel FROM orders 能证明和不能证明什么。' },
      { stage: 'D60', task: '不看模板，按 Q1 到 Q6 逐题复原 basic-query-log.md：每题先写业务问题、SQL、观察结果，再补边界字段。' },
    ],
  },
  nextLesson: { id: 'W3D4', title: '为什么查询结果不可信', bridge: '下一课才诊断 NULL、重复行、状态遗漏、时区和测试数据；W3D3 只把 6 道单表基础查询写成可复核记录。' },
}
