import type { DailyCourse, Exercise } from './types'

const conceptIds = [
  'quality-question',
  'null-value',
  'duplicate-row',
  'status-coverage',
  'test-data-flag',
  'time-boundary-risk',
  'amount-anomaly',
  'quality-evidence-boundary',
] as const

const prerequisiteConceptIds = [
  'terminal-shell',
  'working-directory',
  'file-path',
  'safe-lab-copy',
  'sqlite-database-file',
  'sqlite3-session',
  'setup-sql-script',
  'table-row-column-preview',
  'sql-statement',
  'select-clause',
  'from-clause',
  'where-gate',
  'order-by-stage',
  'limit-stage',
  'execution-order',
  'result-boundary',
  'query-question',
  'where-condition',
  'comparison-operator',
  'text-value-filter',
  'date-range-boundary',
  'order-direction',
  'column-alias',
  'distinct-result',
] as const

function exercise(
  id: string,
  categories: Exercise['categories'],
  ids: string[],
  prompt: string,
  options: string[],
  answerIndex: number,
  referenceAnswer: string,
): Exercise {
  return {
    id,
    kind: 'single-choice',
    categories,
    conceptIds: ids,
    prompt,
    hint: '先问这条查询结果要被谁使用，再检查哪些行会让结论不可信，最后写清能证明和不能证明什么。',
    options: options.map((label, index) => ({
      label,
      rationale: index === answerIndex ? '这项把质量问题落到具体订单行和有限证据，符合 W3D4 的单表诊断范围。' : '这项要么只是在复述结果，要么提前进入聚合、GROUP BY、JOIN、指标或真实生产结论。',
      couldBeTrueWhen: index === answerIndex ? '当学习者只用本地 orders 表做行级质量检查，并把结论限定在教学模拟。' : '只有后续课程补齐聚合、指标口径、JOIN 对账或真实数据审计后，才可能支持更强结论。',
    })),
    answerIndex,
    referenceAnswer,
    reasoning: [
      'W3D4 不是重新写基础查询，而是问基础查询结果里哪些行会破坏信任。',
      'NULL、重复、测试数据、时间边界和金额异常都要落到具体行、字段和 SQL 证据。',
      '本日不计算指标、不使用 GROUP BY、不做 JOIN，也不把教学表结论外推到生产系统。',
    ],
    rubric: ['质量对象具体', 'SQL 只做单表行级检查', '观察行可追溯', '证据边界不过界'],
    commonErrors: [
      { error: '只写“数据有问题”', reason: '质量检查必须指出字段、行和会影响哪条查询结论。' },
      { error: '用异常行直接计算业务损失', reason: 'W3D4 只识别可信度风险，不教学金额聚合或指标影响。' },
    ],
    remediation: { label: '回看数据质量检查的能/不能证明', sectionId: 'concepts', anchor: `concept-${ids[0]}` },
  }
}

export const w3d4: DailyCourse = {
  id: 'W3D4',
  contentVersion: 'w3d4-data-quality-checklist-day01-v1',
  week: 3,
  day: 4,
  title: '查询为何不可信',
  subtitle: '在 W3D3 的 6 道基础查询之后，用同一张 orders 表检查 NULL、重复订单、测试数据、时间边界和金额异常；本日只形成数据质量检查表，不提前教学聚合、GROUP BY、JOIN 或指标。',
  duration: { core: 30, standard: 45, extension: 70, full: 120 },
  coreConceptGroups: [
    {
      id: 'quality-risk-entry',
      title: '先问结果为什么会不可信',
      conceptIds: ['quality-question', 'quality-evidence-boundary'],
      summary: '数据质量检查不是挑错游戏，而是保护查询结论：先说哪条结论会被哪些行影响。',
      boundary: '能定位本地教学表的行级风险；不能证明真实生产质量、修复方案或业务影响金额。',
    },
    {
      id: 'row-level-quality-signals',
      title: '五类行级风险',
      conceptIds: ['null-value', 'duplicate-row', 'test-data-flag', 'time-boundary-risk', 'amount-anomaly'],
      summary: 'NULL、重复、测试数据、跨边界时间和 0/空金额都会让基础查询结果需要被标注。',
      boundary: '只用 SELECT 与 WHERE 观察可疑行，不使用 COUNT、SUM、GROUP BY、JOIN。',
    },
    {
      id: 'coverage-and-status',
      title: '状态覆盖与口径提醒',
      conceptIds: ['status-coverage'],
      summary: 'paid、cancelled、refunded、pending 代表不同业务状态，遗漏状态会让“只看 paid”的结论被误读。',
      boundary: '能说明状态覆盖风险；不能定义最终指标口径或分母。',
    },
  ],
  prerequisiteConceptIds: [...prerequisiteConceptIds],
  learningPaths: {
    '30': {
      guidedStepIndices: [0, 1, 2, 3, 4, 5],
      guidedRecordIndices: [0, 1, 2],
      exerciseCount: 3,
      deliverablePromptCount: 6,
      deliverableChecklistIndices: [0, 1, 2, 3, 4],
      deliverableMinimumContributionCharacters: 220,
    },
    '45': {
      guidedStepIndices: [0, 1, 2, 3, 4, 5],
      guidedRecordIndices: [0, 1, 2, 3],
      exerciseCount: 4,
      deliverablePromptCount: 8,
      deliverableChecklistIndices: [0, 1, 2, 3, 4, 5, 6],
      deliverableMinimumContributionCharacters: 320,
    },
  },
  primaryGoal: '提交 `data-quality-checklist.md`：逐条记录 check_id、business_question、suspect_field、check_sql、expected_risk、observed_rows、risk_type、affected_query、can_prove、cannot_prove、recommended_fix、reviewer_note、self_check_result、next_sql_task。',
  scenario: {
    role: '你是刚完成 W3D3 6 道基础查询的产品经理实习生。',
    situation: 'Q4 最近订单里出现了两个 O1018；Q1 已支付订单里混入 TEST1 和 0 元订单；Q3 当天查询旁边有 2026-08-30 23:59:59 与 2026-09-01 00:00:00；orders 表还存在 NULL user_id、NULL paid_amount 和 NULL paid_at。',
    question: '怎样判断一条基础查询结果是否可以被产品讨论直接引用，哪些地方必须先贴上数据质量风险标签？',
    stakes: '如果不先检查质量，产品经理会把测试订单、重复订单、跨天边界和空字段当成真实用户行为，后续指标和需求判断都会被污染。',
  },
  objectives: [
    { id: 'w3d4-objective-risk', text: '能把“不可信”拆成具体字段和订单行', evidence: '`data-quality-checklist.md` 每条都有 suspect_field、observed_rows 和 risk_type。' },
    { id: 'w3d4-objective-sql', text: '能写出 6 条单表行级质量检查 SQL', evidence: 'check_sql 只使用 orders、SELECT、WHERE、ORDER BY、LIMIT、IS NULL、LIKE 等基础查询动作。' },
    { id: 'w3d4-objective-impact', text: '能说明每个风险会影响 W3D3 哪条查询', evidence: 'affected_query 指向 q1-paid-orders、q3-orders-on-20260831 或 q4-recent-paid-orders 等。' },
    { id: 'w3d4-objective-boundary', text: '能写出质量检查能证明和不能证明什么', evidence: 'can_prove、cannot_prove、self_check_result、next_sql_task 均完整。' },
  ],
  prerequisites: [
    {
      id: 'w3d4-basic-query-readiness',
      conceptIds: [...prerequisiteConceptIds],
      prompt: '你是否已经能打开 W3 教学库，并解释 W3D3 六道基础查询的 SQL、输出和证据边界？',
      passDescription: '能说出 orders 表字段，能复述 q1-paid-orders、q3-orders-on-20260831、q4-recent-paid-orders 的 SQL 和 cannot_prove。',
      remediationLabel: '回到 W3D3 补 6 道基础查询',
      remediationTarget: '#/lesson/W3D3',
      remediation: {
        purpose: 'W3D4 可以提前阅读；但没有 W3D3 的基础查询记录时，数据质量检查会变成抽象挑错。',
        steps: ['先补 basic-sql-queries.sql 与 basic-query-log.md。', '确认 q1、q3、q4 的业务问题、SQL、实际结果和 cannot_prove。', '再回到本课，把“不可信”贴回具体查询和订单行。'],
        successCheck: '能说明 W3D4 检查的是 W3D3 查询结果的可信度，不是重新定义指标。',
      },
    },
  ],
  concepts: [
    {
      id: 'quality-question',
      prerequisiteConceptIds: ['query-question', 'result-boundary'],
      term: '数据质量问题', english: 'Data Quality Question',
      definition: '数据质量问题是问“哪些字段或行会让这条查询结论不可靠”，它必须绑定具体查询、字段和可疑行。',
      why: '产品经理不能只问“查出来了吗”，还要问“这些行能不能被相信”。',
      problemSolved: '回答“这条查询结果引用前要先排查什么风险”。',
      input: 'W3D3 的 SQL、orders 表字段和输出样本。',
      output: 'check_id、suspect_field、risk_type 与 affected_query。',
      systemPosition: '位于基础查询之后、指标计算之前，是查询结果进入产品讨论前的可信度闸门。',
      process: ['选择一条 W3D3 查询。', '指出可能破坏结论的字段。', '写一条只查可疑行的 SQL。', '记录能/不能证明。'],
      owner: '产品经理负责提出质量问题；数据库只按 SQL 返回行。',
      notResponsibleFor: '不负责修复数据、计算损失、定义指标或连接多表。',
      compareWith: 'W3D3 查询问题问“要查什么”；W3D4 质量问题问“查到的结果哪里可能不可信”。',
      evidence: ['check_id。', 'affected_query。', 'observed_rows。'],
      failureModes: ['只写“数据脏”。', '不说明影响哪条查询。'],
      pmUse: '在评审“最近支付订单”前，先标注 O1018 重复、TEST1 测试订单和跨天 paid_at 风险。',
      correctExample: '检查 q4-recent-paid-orders 里 O1018 是否重复出现。',
      incorrectExample: '说“数据库不准”，但没有 SQL 和具体行。',
    },
    {
      id: 'null-value',
      prerequisiteConceptIds: ['where-condition'],
      term: 'NULL 值', english: 'NULL Value',
      definition: 'NULL 表示该字段没有值，不等于 0、空字符串或“未知用户”文本。',
      why: 'NULL 会让用户、支付时间、金额这些关键字段缺证据，查询结果看起来有行，但业务解释缺口很大。',
      problemSolved: '回答“哪些关键字段缺值，不能直接用于解释”。',
      input: 'user_id、paid_at、paid_amount 等字段。',
      output: '包含 NULL 的可疑订单行。',
      systemPosition: '属于 WHERE 行级检查，常用 IS NULL 定位。',
      process: ['确认关键字段。', '用 IS NULL 查可疑行。', '说明缺值会影响什么解释。'],
      owner: '学习者识别字段缺口；SQLite 返回 NULL 行。',
      notResponsibleFor: 'NULL 检查不负责判断为什么缺值，也不负责补值。',
      compareWith: '0.00 是明确数值；NULL 是没有金额值。',
      evidence: ['O1016 user_id=NULL。', 'O1017 paid_amount=NULL。', 'O1003/O1010 paid_at=NULL。'],
      failureModes: ['把 NULL 当成 0。', '用 = NULL 而不是 IS NULL。'],
      pmUse: '看到 paid 订单 O1016 缺 user_id 时，不能直接说这条订单能证明某个用户已支付。',
      correctExample: 'WHERE user_id IS NULL OR paid_amount IS NULL OR paid_at IS NULL。',
      incorrectExample: 'WHERE paid_amount = NULL。',
    },
    {
      id: 'duplicate-row',
      prerequisiteConceptIds: ['distinct-result'],
      term: '重复行', english: 'Duplicate Row',
      definition: '重复行是同一个业务对象以相同或高度相似字段出现多次，导致结果展示和后续判断被重复引用。',
      why: 'Q4 里 O1018 出现两次，如果不标注重复，产品讨论可能把同一订单当成两个事实。',
      problemSolved: '回答“这是不是同一个订单被重复展示”。',
      input: 'order_id、user_id、paid_amount、paid_at 等字段。',
      output: '带 row_id 和关键字段的疑似重复订单行。',
      systemPosition: '位于 DISTINCT 观察之后；本日只行级确认重复样本，不计算重复数量。',
      process: ['锁定可疑 order_id。', '查询完整行。', '比较关键字段是否相同。', '记录不能证明根因。'],
      owner: '学习者提出重复风险；SQLite 展示候选行。',
      notResponsibleFor: '不负责 dedupe 规则、去重指标、生产修复或 GROUP BY 统计。',
      compareWith: 'DISTINCT 可隐藏展示重复；质量检查要说明重复可能来自数据源而不是展示规则。',
      evidence: ['O1018 出现两行。', '两行 user_id、paid_amount、paid_at 相同。'],
      failureModes: ['用 DISTINCT 掩盖重复来源。', '看到两行就直接计算影响金额。'],
      pmUse: '在“最近订单”列表里标注 O1018 疑似重复，避免把它当两笔订单讲给业务方。',
      correctExample: 'SELECT row_id, order_id, user_id, paid_amount, paid_at FROM orders WHERE order_id = "O1018";',
      incorrectExample: 'SELECT DISTINCT order_id 后说重复问题已经解决。',
    },
    {
      id: 'status-coverage',
      prerequisiteConceptIds: ['text-value-filter'],
      term: '状态覆盖', english: 'Status Coverage',
      definition: '状态覆盖是确认查询是否只看了某个状态，以及被排除的状态是否会影响业务解释。',
      why: '只看 paid 适合支付样本，但 cancelled、refunded、pending 仍可能影响“订单表现”的完整讨论。',
      problemSolved: '回答“这次状态范围是有意限定，还是漏看了重要状态”。',
      input: 'status 字段和业务问题。',
      output: '状态边界说明与被排除状态样本。',
      systemPosition: '承接 W3D3 文本值筛选，提醒 WHERE status = "paid" 只是一个业务口径。',
      process: ['写明目标状态。', '观察非目标状态样本。', '把不能覆盖的解释写进 cannot_prove。'],
      owner: '产品经理说明状态范围；SQLite 只执行筛选。',
      notResponsibleFor: '不负责计算各状态占比或最终订单指标。',
      compareWith: 'WHERE status="paid" 是筛选动作；状态覆盖是对这个筛选动作的业务边界说明。',
      evidence: ['cancelled O1003。', 'refunded O1005。', 'pending O1010。'],
      failureModes: ['只查 paid 后说“所有订单表现”。', '忽略退款和待支付状态。'],
      pmUse: '需求评审时说清“本次只看 paid，退款和待支付不在这条结论内”。',
      correctExample: 'SELECT order_id, status, paid_at FROM orders WHERE status != "paid";',
      incorrectExample: 'WHERE status = "paid" 后直接评价全部订单质量。',
    },
    {
      id: 'test-data-flag',
      prerequisiteConceptIds: ['text-value-filter'],
      term: '测试数据标记', english: 'Test Data Flag',
      definition: '测试数据标记是用 is_test 或 user_id 规则识别教学/测试行，避免把测试行为当真实业务行为。',
      why: 'O1009 的 TEST1 与 is_test=1、9999.00 金额会强烈干扰基础查询观察。',
      problemSolved: '回答“这行是否应该进入真实业务解释”。',
      input: 'is_test、user_id、paid_amount 等字段。',
      output: '带 is_test 标记和用户规则的测试或疑似测试订单行。',
      systemPosition: '位于 WHERE 文本筛选之后，是引用查询结果前的排除提醒。',
      process: ['检查 is_test。', '检查 user_id 是否像 TEST。', '记录是否应在真实解释中排除。'],
      owner: '产品经理提出排除规则；SQLite 返回标记行。',
      notResponsibleFor: '不负责真实生产测试账号治理或权限审计。',
      compareWith: '测试数据不是 SQL 错误；它是业务解释的排除边界。',
      evidence: ['O1009 user_id=TEST1。', 'is_test=1。', 'paid_amount=9999.00。'],
      failureModes: ['把测试订单当真实大额支付。', '只看 status=paid 不看 is_test。'],
      pmUse: '汇报 paid 样本前先说“TEST1 是测试行，不能当真实用户订单”。',
      correctExample: 'WHERE is_test = 1 OR user_id LIKE "TEST%"。',
      incorrectExample: '看到 9999.00 就说高客单订单成立。',
    },
    {
      id: 'time-boundary-risk',
      prerequisiteConceptIds: ['date-range-boundary'],
      term: '时间边界风险', english: 'Time Boundary Risk',
      definition: '时间边界风险是指日期条件把临界时刻错误包含或排除，导致“当天”结果被跨天行污染。',
      why: 'orders 表同时有 2026-08-30 23:59:59、2026-09-01 00:00:00 和 2026-09-01 09:10:00，边界不清会直接改变样本。',
      problemSolved: '回答“临界时间行是否被正确处理”。',
      input: 'paid_at 字段、开始边界、结束边界。',
      output: '跨边界或临界 paid_at 行。',
      systemPosition: '承接 W3D3 日期范围边界，专门检查临界样本。',
      process: ['列出起点前、终点时刻和终点后的行。', '确认闭开边界。', '记录不能证明时区或延迟刷新。'],
      owner: '学习者声明边界；SQLite 返回临界行。',
      notResponsibleFor: '不负责时区换算、服务端延迟或跨系统对账。',
      compareWith: '日期查询写边界；时间边界风险检查边界附近是否有会误入的行。',
      evidence: ['O1015=2026-08-30 23:59:59。', 'O1014=2026-09-01 00:00:00。', 'O1019=2026-09-01 09:10:00。'],
      failureModes: ['使用 <= "2026-09-01 00:00:00" 把下一天 0 点误算进 8 月 31 日。', '没有说明 NULL paid_at。'],
      pmUse: '当产品说“8 月 31 日当天”，必须保护结束边界不包含 9 月 1 日 0 点。',
      correctExample: 'paid_at >= "2026-08-31" AND paid_at < "2026-09-01"。',
      incorrectExample: 'paid_at <= "2026-09-01 00:00:00" 后仍说只看 8 月 31 日。',
    },
    {
      id: 'amount-anomaly',
      prerequisiteConceptIds: ['comparison-operator'],
      term: '金额异常', english: 'Amount Anomaly',
      definition: '金额异常是指 paid_amount 出现 0、NULL 或明显不合业务预期的数值，需要在引用结果前标注。',
      why: '0 元、空金额和测试大额都会让“支付订单”看起来成立，但金额解释不稳。',
      problemSolved: '回答“这条订单金额是否能支持支付金额相关解释”。',
      input: 'paid_amount、status、is_test。',
      output: '0、NULL 或测试大额订单样本。',
      systemPosition: '属于行级质量检查，不进入 SUM、AVG 或收入计算。',
      process: ['查 paid_amount IS NULL。', '查 paid_amount = 0。', '结合 is_test 标注测试大额。'],
      owner: '学习者标注金额风险；SQLite 返回可疑行。',
      notResponsibleFor: '不负责判断优惠规则、退款金额或收入指标。',
      compareWith: '金额异常识别可疑行；指标课程才定义分子、分母和计算方式。',
      evidence: ['O1008 paid_amount=0.00。', 'O1017 paid_amount=NULL。', 'O1009 paid_amount=9999.00 且 is_test=1。'],
      failureModes: ['把 NULL 当 0。', '直接把可疑金额相加。'],
      pmUse: '在给数据同事提问时写清“paid 里有 0 元和空金额，先确认是否可纳入口径”。',
      correctExample: 'WHERE paid_amount IS NULL OR paid_amount = 0 OR is_test = 1。',
      incorrectExample: '把 O1009 当真实高价值订单结论。',
    },
    {
      id: 'quality-evidence-boundary',
      prerequisiteConceptIds: ['result-boundary'],
      term: '质量证据边界', english: 'Quality Evidence Boundary',
      definition: '质量证据边界说明一次本地行级检查能证明什么、不能证明什么，以及下一步应该请谁确认。',
      why: '发现异常不等于知道原因，更不等于已经完成业务修复。',
      problemSolved: '回答“这份检查表能被怎样使用”。',
      input: '检查 SQL、观察行、风险解释。',
      output: 'can_prove、cannot_prove、recommended_fix、reviewer_note。',
      systemPosition: '位于所有质量检查之后，是成果交接和后续课程的边界。',
      process: ['写能证明的本地观察。', '写不能证明的根因/生产/指标。', '写建议找数据同事确认的规则。'],
      owner: '学习者写边界；导师或数据同事复核。',
      notResponsibleFor: '不负责替代真实数据审计、修复脚本或指标验收。',
      compareWith: 'W3D3 的 result boundary 针对查询动作；W3D4 的 quality boundary 针对查询结果可信度。',
      evidence: ['can_prove。', 'cannot_prove。', 'reviewer_note。'],
      failureModes: ['发现异常后直接宣布数据不可用。', '没有写下一步确认人或问题。'],
      pmUse: '把检查结果交给数据同事时说“我发现了这些风险，先请确认是否应排除或修复”。',
      correctExample: '能证明本地教学表存在 O1018 重复样本；不能证明重复来自真实生产或已影响指标。',
      incorrectExample: 'O1018 重复，所以真实订单指标一定错了。',
    },
  ],
  diagram: {
    title: '基础查询结果可信度检查链',
    caption: '从 W3D3 的查询结果出发，按可疑字段、检查 SQL、观察行、影响查询和证据边界形成数据质量检查表。',
    nodes: [
      { id: 'source-query', label: 'W3D3 基础查询', description: '先选一条已运行查询，不抽象谈质量。', input: 'basic-query-log.md', output: 'affected_query', owner: '学习者本人', evidence: 'q1/q3/q4 等编号' },
      { id: 'suspect-field', label: '可疑字段', description: '把风险落到 user_id、paid_at、paid_amount、order_id、is_test 或 status。', input: 'orders 表字段', output: 'suspect_field', owner: '学习者本人', evidence: '字段名' },
      { id: 'check-sql', label: '检查 SQL', description: '只用单表 SELECT/WHERE 查可疑行。', input: 'risk_type', output: 'check_sql', owner: 'SQLite', evidence: '可执行 SQL' },
      { id: 'observed-rows', label: '观察订单行', description: '记录 O1008、O1009、O1016、O1017、O1018 等实际行。', input: 'SQL 输出样本', output: 'observed_rows', owner: '学习者本人', evidence: '订单样本' },
      { id: 'boundary', label: '证据边界', description: '说明能证明、不能证明和建议确认事项。', input: '观察行样本', output: 'can_prove/cannot_prove', owner: '学习者本人', evidence: 'data-quality-checklist.md' },
    ],
    branches: [
      { from: 'source-query', to: 'suspect-field', label: '定位风险对象', kind: 'normal' },
      { from: 'suspect-field', to: 'check-sql', label: '写行级检查', kind: 'normal' },
      { from: 'check-sql', to: 'observed-rows', label: '查看可疑行', kind: 'normal' },
      { from: 'observed-rows', to: 'boundary', label: '收束证据', kind: 'normal' },
      { from: 'observed-rows', to: 'boundary', label: '直接声称生产指标错误', kind: 'failure' },
    ],
    evidenceNotes: [
      '所有检查只读取本地教学 orders 表。',
      '能证明本地教学样本中存在特定质量风险；不能证明生产根因、真实业务影响、聚合、GROUP BY、JOIN 或指标口径。',
      'answers.sql 只在完成自检后对照，不在预测和首次操作前打开。',
    ],
  },
  demonstration: {
    title: '教师示范：为什么 Q4 最近订单不能直接引用',
    businessProblem: 'W3D3 的 Q4 用 ORDER BY paid_at DESC 查看最近已支付订单，实际前 5 行包含 O1019、O1014、O1018、O1018、O1013。现在要判断这份结果能否直接拿去说“最近订单”。',
    finalConclusion: '可以证明本地教学表中 Q4 结果存在至少三类可信度风险：O1018 重复展示、O1009 测试高金额可能混入 paid 查询、O1014/O1019 属于 2026-09-01 不应被 2026-08-31 当天结论引用。',
    conclusionLimit: '不能证明生产订单重复、真实收入受影响、测试账号治理失败、时区正确、聚合指标错误、GROUP BY 或 JOIN 结果正确。',
    steps: [
      { title: '固定受影响查询', action: '写 affected_query=q4-recent-paid-orders。', reason: '质量检查必须绑定一个基础查询结果。', evidence: 'affected_query。', proves: '检查对象明确。', limitation: '不证明风险已经存在。' },
      { title: '查 O1018 重复行', action: '运行 SELECT row_id, order_id, user_id, paid_amount, paid_at FROM orders WHERE order_id = "O1018";。', reason: 'Q4 里 O1018 出现两次，先看完整行。', evidence: 'row_id 18 与 19。', proves: '能证明本地样本存在疑似重复订单行。', limitation: '不证明真实根因或应如何去重。' },
      { title: '查测试订单标记', action: '运行 SELECT order_id, user_id, paid_amount, is_test FROM orders WHERE is_test = 1 OR user_id LIKE "TEST%";。', reason: '测试行会污染 paid 查询和金额解释。', evidence: 'O1009 TEST1 is_test=1。', proves: '能证明本地样本存在测试订单。', limitation: '不证明生产测试治理情况。' },
      { title: '查金额异常样本', action: '运行 SELECT order_id, paid_amount, is_test FROM orders WHERE paid_amount IS NULL OR paid_amount = 0 OR is_test = 1;。', reason: '支付订单不一定能支持金额结论。', evidence: 'O1008 0.00、O1017 NULL、O1009 9999.00。', proves: '能证明本地样本存在金额解释风险。', limitation: '不证明收入指标或优惠规则。' },
      { title: '查时间临界行', action: '运行 SELECT order_id, paid_at FROM orders WHERE paid_at < "2026-08-31" OR paid_at >= "2026-09-01" ORDER BY paid_at;。', reason: '当天结论要保护前后边界。', evidence: 'O1015、O1014、O1019。', proves: '能证明边界附近存在会改变当天解释的行。', limitation: '不证明时区或延迟刷新。' },
      { title: '写质量证据边界', action: '把每类风险写入 data-quality-checklist.md，并为 can_prove/cannot_prove/recommended_fix 留出复核问题。', reason: '质量检查的价值在于让结论被谨慎引用。', evidence: '检查表字段齐全。', proves: '能形成可交接的可信度诊断。', limitation: '不替代后续指标、聚合、JOIN 或生产数据审计。' },
    ],
  },
  guidedLab: {
    title: '6 条数据质量检查台',
    goal: '围绕 W3D3 的基础查询结果完成六条正向质量检查：null-user-id、null-paid-at、duplicate-order-id、test-order-included、zero-or-null-amount、boundary-cross-day。每条都有业务问题、SQL、预期风险、实际看到什么、能证明什么、不能证明什么。',
    safety: '教学模拟 · 只读取本地 SQLite 教学表 orders、exercises.sql 和 self_check.sql；不连接真实数据库、不写入数据、不提前打开 answers.sql。',
    conceptIds: [...conceptIds],
    predictionPrompt: '预测：在 orders 表里，哪类风险最容易让 W3D3 的 Q1/Q3/Q4 被误读：NULL、重复、测试数据、金额异常还是时间边界？',
    steps: [
      { title: 'C1 查缺用户的 paid 订单', action: '运行 SELECT order_id, user_id, status FROM orders WHERE status = "paid" AND user_id IS NULL;。', observe: '实际看到 O1016，user_id 为 NULL。', explanation: 'paid 行存在，但无法直接解释为某个用户完成支付。', proves: '能证明本地 paid 样本存在缺用户风险。', cannotProve: '不能证明真实用户丢失、账号系统故障或应如何补值。' },
      { title: 'C2 查缺支付时间的订单', action: '运行 SELECT order_id, status, paid_at FROM orders WHERE paid_at IS NULL;。', observe: '实际看到 O1003 cancelled、O1010 pending。', explanation: '空 paid_at 需要和 status 一起解释，不能硬放进支付时间窗口。', proves: '能证明本地样本存在无支付时间行。', cannotProve: '不能证明时区、延迟刷新或真实支付链路。' },
      { title: 'C3 查重复订单号 O1018', action: '运行 SELECT row_id, order_id, user_id, paid_amount, paid_at FROM orders WHERE order_id = "O1018";。', observe: '实际看到 row_id 18 和 19 两行，关键字段相同。', explanation: '同一 order_id 重复出现会影响最近订单列表引用。', proves: '能证明本地样本存在疑似重复行。', cannotProve: '不能证明重复根因或去重后指标。' },
      { title: 'C4 查测试订单是否混入 paid 查询', action: '运行 SELECT order_id, user_id, status, paid_amount, is_test FROM orders WHERE is_test = 1 OR user_id LIKE "TEST%";。', observe: '实际看到 O1009、TEST1、paid_amount=9999.00、is_test=1。', explanation: '测试订单可以出现在 paid 查询里，但不应直接当真实业务行为。', proves: '能证明本地样本存在测试数据标记。', cannotProve: '不能证明生产环境测试数据治理。' },
      { title: 'C5 查 0 元或空金额', action: '运行 SELECT order_id, status, paid_amount FROM orders WHERE paid_amount IS NULL OR paid_amount = 0;。', observe: '实际看到 O1008 paid_amount=0.00，O1017 paid_amount=NULL。', explanation: 'paid 状态和金额可解释性不是一回事。', proves: '能证明本地样本存在金额异常风险。', cannotProve: '不能证明优惠、退款或收入指标。' },
      { title: 'C6 查日期边界外和临界行', action: '运行 SELECT order_id, paid_at FROM orders WHERE paid_at < "2026-08-31" OR paid_at >= "2026-09-01" ORDER BY paid_at;。', observe: '实际看到 O1015、O1014、O1019。', explanation: '当天查询必须说明不包含 2026-09-01 00:00:00 及之后。', proves: '能证明边界附近有会影响日期解释的行。', cannotProve: '不能证明时区换算或延迟入库。' },
    ],
    recordPrompts: [
      '记录 C1/C2：写出 NULL 字段、SQL、observed_rows 和 affected_query。',
      '记录 C3：写出 O1018 两行、重复风险、能证明和不能证明。',
      '记录 C4/C5：写出 TEST1、9999.00、0.00、NULL amount 对 paid 查询的影响边界。',
      '记录 C6：写出 O1015、O1014、O1019 分别在日期边界里的位置。',
    ],
    comparePrompt: '对照 exercises.sql 与 self_check.sql：你的检查表是否只做行级质量诊断，并且没有提前打开 answers.sql、COUNT、GROUP BY、JOIN 或指标计算？',
    passCriteria: ['六条质量检查都运行并记录。', '每条都有业务问题、SQL、预期风险、实际看到什么、能证明什么、不能证明什么。', '检查结果必须绑定 W3D3 的 affected_query。', '不能把教学模拟写成真实生产、聚合、GROUP BY、JOIN 或指标结论。'],
  },
  independentLab: {
    title: '独立变式：给 Q1 已支付订单补质量标签',
    scenario: '同学拿 Q1 paid 订单样本准备给业务方看，但里面可能有 TEST1、0 元、NULL user_id、NULL paid_amount、重复订单和跨天时间。你要先补数据质量检查表。',
    conceptIds: [...conceptIds],
    changedConditions: ['只看 paid，但未排除 is_test=1。', '只看 paid，但没有标注 paid_amount=0 或 NULL。', '只看最近订单，但没有标注 O1018 重复。', '只看 2026-08-31，但结束边界写成 <= 2026-09-01 00:00:00。', '只写“数据质量差”，没有 affected_query 和 observed_rows。'],
    task: '任选两类风险，写出 check_sql、observed_rows、affected_query、can_prove、cannot_prove 和 recommended_fix。',
    predictionPrompt: '先预测这组 paid 订单最容易被误读成哪类业务结论。',
    evidenceRequirements: ['必须引用 NULL、重复、测试数据、金额异常或时间边界中至少三类。', '必须写明只证明本地教学表行级风险，不证明真实生产、聚合、GROUP BY、JOIN 或指标。'],
    passCriteria: ['能把风险落到具体字段和订单行。', '检查 SQL 仍为单表行级查询。', '每条风险都有 affected_query 和 recommended_fix。', '下一步只进入 W3D5 的后续 SQL 学习说明，不创建 W3D5 内容。'],
    remediation: { label: '回看基础查询结果可信度检查链', sectionId: 'diagram', anchor: 'demonstration-conclusion' },
  },
  exercises: [
    exercise('w3d4-null-boundary', ['概念与边界', '机制推演'], ['null-value', 'quality-question'], '发现 O1016 的 user_id 为 NULL，最稳妥的质量结论是什么？', ['这条 paid 行缺用户字段，不能直接证明某个用户完成支付', '把 user_id 当成字符串 NULL 正常使用', '说明真实账号系统已经故障'], 0, 'NULL 是缺值证据，只能证明本地样本缺用户字段，不能外推生产根因。'),
    exercise('w3d4-duplicate-risk', ['证据判断', '工作场景'], ['duplicate-row', 'distinct-result'], 'Q4 最近订单里 O1018 出现两次，第一步该怎么处理？', ['查询 O1018 的完整行并标注疑似重复风险', '直接 SELECT DISTINCT 隐藏它并说问题解决', '计算重复订单收入影响'], 0, 'W3D4 先查看和记录重复行，不做去重指标或收入影响。'),
    exercise('w3d4-test-amount', ['工作场景', '综合变式'], ['test-data-flag', 'amount-anomaly'], 'O1009 是 TEST1 且金额 9999.00，哪句不过界？', ['本地样本存在测试数据和金额解释风险，应先确认是否排除', '说明真实高客单用户出现', '可以直接算入收入增长'], 0, '测试标记和异常金额会影响解释，但不证明真实业务增长。'),
    exercise('w3d4-time-boundary', ['机制推演', '证据判断'], ['time-boundary-risk', 'quality-evidence-boundary'], '查看 2026-08-31 当天时，为什么 `<= "2026-09-01 00:00:00"` 有风险？', ['它会把 2026-09-01 00:00:00 的 O1014 包进 8 月 31 日结论', '它能自动处理时区', '它能证明 9 月订单无关'], 0, '当天查询应使用 < 下一天起点，临界时刻需要在检查表里标注。'),
  ],
  deliverable: {
    title: '数据质量检查表',
    conceptIds: [...conceptIds],
    purpose: '让学习者用 data-quality-checklist.md 把 W3D3 基础查询结果中的可疑行、字段、SQL、影响范围和证据边界逐条写清。',
    whenToUse: '在把 SQL 查询结果放进需求评审、数据同事沟通或后续指标学习之前，用来先标注可信度风险。',
    audience: '未来继续做 SQL、指标或对账的自己，以及协助复核数据质量的数据同事。',
    fields: [
      { name: 'check_id', meaning: '质量检查编号，例如 C1-null-user-id。', source: '本课六条检查任务' },
      { name: 'business_question', meaning: '这条检查保护哪一句业务解释。', source: 'W3D3 query log' },
      { name: 'suspect_field', meaning: '可疑字段，如 user_id、paid_at、paid_amount、order_id、is_test。', source: 'orders 表结构' },
      { name: 'check_sql', meaning: '只读单表行级检查 SQL。', source: 'sqlite3 操作记录' },
      { name: 'expected_risk', meaning: '运行前预测会看到什么风险。', source: '实验预测' },
      { name: 'observed_rows', meaning: '实际看到的订单行或样本。', source: 'sqlite3 输出' },
      { name: 'risk_type', meaning: 'NULL、duplicate、test_data、time_boundary、amount_anomaly、status_coverage。', source: '本课概念' },
      { name: 'affected_query', meaning: '受影响的 W3D3 查询编号。', source: 'basic-query-log.md' },
      { name: 'can_prove', meaning: '本地教学表能证明的有限质量事实。', source: 'SQL 与输出' },
      { name: 'cannot_prove', meaning: '不能证明的生产、根因、修复、聚合、GROUP BY、JOIN 或指标事项。', source: '证据边界自检' },
      { name: 'recommended_fix', meaning: '建议后续确认或标注的动作，不直接修库。', source: '产品经理复核问题' },
      { name: 'reviewer_note', meaning: '要交给数据同事或导师确认的问题。', source: '人工复核准备' },
      { name: 'self_check_result', meaning: 'self_check.sql 或人工对照结果。', source: '自检输出' },
      { name: 'next_sql_task', meaning: '下一步只进入后续 SQL 学习，不提前完成 W3D5。', source: '课程路线' },
    ],
    badExample: 'check_id: C1\nbusiness_question: 数据不准\ncheck_sql: SELECT * FROM orders;\nobserved_rows: 有很多异常，所以真实生产指标错了，应该马上 GROUP BY 重新算收入。',
    badReasons: ['业务问题太空泛。', '没有 suspect_field、risk_type、affected_query。', '没有写具体可疑订单行。', '把本地教学模拟越界成生产指标和 GROUP BY 结论。'],
    revisionSteps: ['把检查绑定到 W3D3 的某条查询。', '写出 suspect_field 和 risk_type。', '用只读单表 SQL 查可疑行。', '记录 observed_rows、can_prove 和 cannot_prove。', '把 recommended_fix 写成“请确认是否排除/标注”，不要直接声称修复完成。'],
    goodExample: 'check_id: C3-duplicate-order-id\nbusiness_question: 保护 q4-recent-paid-orders，避免把同一订单当成两笔最近订单\nsuspect_field: order_id、paid_at、paid_amount\ncheck_sql: SELECT row_id, order_id, user_id, paid_amount, paid_at FROM orders WHERE order_id = "O1018";\nexpected_risk: Q4 中 O1018 出现两次，可能是重复行\nobserved_rows: row_id 18 与 19 都是 O1018、U015、89.00、2026-08-31 23:30:30\nrisk_type: duplicate\naffected_query: q4-recent-paid-orders\ncan_prove: 能证明本地教学 orders 表存在两条关键字段相同的 O1018 行\ncannot_prove: 不能证明真实生产重复、重复根因、去重后指标、GROUP BY、JOIN 或收入影响\nrecommended_fix: 在引用 Q4 前标注 O1018 疑似重复，请数据同事确认去重规则\nreviewer_note: 是否应按 order_id 去重展示，还是保留 row_id 级明细\nself_check_result: self_check.sql 对照通过；未提前打开 answers.sql\nnext_sql_task: 继续后续 SQL 学习，不提前完成 W3D5\n',
    guidedPrompts: ['写出 6 个 check_id。', '为每条检查写 business_question。', '写 suspect_field 和 risk_type。', '写 check_sql。', '写 expected_risk 与 observed_rows。', '写 affected_query。', '写 can_prove 与 cannot_prove。', '写 recommended_fix、reviewer_note、self_check_result 和 next_sql_task。'],
    blankTemplate: 'check_id:\nbusiness_question:\nsuspect_field:\ncheck_sql:\nexpected_risk:\nobserved_rows:\nrisk_type:\naffected_query:\ncan_prove:\ncannot_prove:\nrecommended_fix:\nreviewer_note:\nself_check_result:\nnext_sql_task:\n',
    standardTemplate: 'check_id: C1-null-user-id\nbusiness_question: 保护 q1-paid-orders，避免把缺用户字段的 paid 行解释成某个用户完成支付\nsuspect_field: user_id\ncheck_sql: SELECT order_id, user_id, status FROM orders WHERE status = "paid" AND user_id IS NULL;\nexpected_risk: paid 查询里可能存在 user_id 为空的行\nobserved_rows: O1016 的 user_id 为 NULL，status 为 paid\nrisk_type: NULL\naffected_query: q1-paid-orders\ncan_prove: 能证明本地教学 orders 表存在 paid 但 user_id 缺值的订单行\ncannot_prove: 不能证明真实生产用户丢失、账号系统故障、数据已修复、聚合、GROUP BY、JOIN 或指标正确\nrecommended_fix: 引用 q1 前标注 user_id 缺值风险，请数据同事确认是否排除或补充来源\nreviewer_note: NULL user_id 是否来自匿名下单、同步缺失还是教学样本设置\nself_check_result: self_check.sql 对照通过；未提前打开 answers.sql\nnext_sql_task: 继续后续 SQL 学习，不提前完成 W3D5\n',
    checklist: ['6 条检查都有 check_id 和 check_sql。', '每条都写 suspect_field、risk_type 和 observed_rows。', '每条都绑定 affected_query。', 'NULL、重复、测试数据、金额异常和时间边界至少各出现一次。', 'cannot_prove 明确排除真实生产、根因、聚合、GROUP BY、JOIN 和指标。', 'self_check_result 完成，且 answers.sql 没有提前暴露。', 'next_sql_task 不得宣称 W3D5 已完成。'],
  },
  memory: {
    conceptIds: [...conceptIds],
    anchors: ['质量问题必须绑定查询和字段。', 'NULL 不是 0 或空字符串。', '重复、测试、金额和时间边界都要贴回具体行。', '发现风险不等于证明生产根因。'],
    closedBookPrompt: '闭卷解释：为什么一条 W3D3 基础查询结果仍可能不可信？请按质量问题、NULL、重复、状态覆盖、测试数据、时间边界、金额异常和证据边界复述。',
    microOperation: '不看正文，写一条检查 O1018 重复的 SQL，并写 can_prove/cannot_prove。',
    unresolvedPrompt: '写出你进入后续 SQL 学习前最容易混淆的一处：NULL、重复、测试数据、金额异常还是时间边界？准备怎么用 self_check 校正？',
    reviewStages: [
      { stage: 'D1', task: '闭卷写出 IS NULL 与 = NULL 的区别，并举 O1016 或 O1017 例子。' },
      { stage: 'D3', task: '解释 O1018 重复行能证明和不能证明什么。' },
      { stage: 'D7', task: '解释 TEST1 与 is_test=1 为什么不能直接当真实订单。' },
      { stage: 'D14', task: '写出 2026-08-31 当天边界，并说明 O1014 为什么不能被包含。' },
      { stage: 'D30', task: '给一条 paid 查询补金额异常检查和 cannot_prove。' },
      { stage: 'D60', task: '不看模板重写 data-quality-checklist.md 的 14 个字段。' },
    ],
  },
  nextLesson: { id: 'W3D5', title: '后续 SQL 查询扩展', bridge: '下一课之后才继续扩展 SQL 能力；W3D4 只把基础查询结果的可信度风险写成数据质量检查表，不提前教学聚合、GROUP BY、JOIN 或指标。' },
}
