import type { DailyCourse, Exercise } from './types'

const conceptIds = [
  'data-request-purpose',
  'business-question-scope',
  'field-source-assumption',
  'filter-rule-contract',
  'time-window-contract',
  'exclusion-rule-contract',
  'expected-output-shape',
  'review-question-boundary',
] as const

const prerequisiteConceptIds = [
  'terminal-shell',
  'working-directory',
  'file-path',
  'safe-lab-copy',
  'sqlite-database-file',
  'sqlite3-session',
  'setup-sql-script',
  'table-row-column-preview',
  'sql-statement',
  'select-clause',
  'from-clause',
  'where-gate',
  'order-by-stage',
  'limit-stage',
  'execution-order',
  'result-boundary',
  'query-question',
  'where-condition',
  'comparison-operator',
  'text-value-filter',
  'date-range-boundary',
  'order-direction',
  'column-alias',
  'distinct-result',
  'quality-question',
  'null-value',
  'duplicate-row',
  'status-coverage',
  'test-data-flag',
  'time-boundary-risk',
  'amount-anomaly',
  'quality-evidence-boundary',
] as const

function exercise(
  id: string,
  categories: Exercise['categories'],
  ids: string[],
  prompt: string,
  options: string[],
  answerIndex: number,
  referenceAnswer: string,
): Exercise {
  return {
    id,
    kind: 'single-choice',
    categories,
    conceptIds: ids,
    prompt,
    hint: '先看数据同事能不能复现：业务问题、表和字段、筛选规则、时间窗口、排除规则、输出形状、复核问题是否齐全。',
    options: options.map((label, index) => ({
      label,
      rationale: index === answerIndex ? '这项把需求写成可执行、可复核、不过界的取数契约。' : '这项缺少可复现输入，或把本日需求单越界写成指标计算、生产结论或数据修复。',
      couldBeTrueWhen: index === answerIndex ? '当学习者只基于本地 orders 教学表和 W3D4 质量风险提出确认问题。' : '只有后续课程完成业务查询、指标口径或生产评审后，才可能支持更强结论。',
    })),
    answerIndex,
    referenceAnswer,
    reasoning: [
      '取数需求单的第一性原理是让别人按同一输入复现同一数据口径。',
      '业务问题、字段来源、筛选、时间、排除、输出形状和复核问题必须同时出现。',
      '本日不计算指标、不使用 GROUP BY、不做 JOIN，也不声称真实生产数据已经正确。',
    ],
    rubric: ['业务问题具体', '数据源和字段可复核', '口径规则可执行', '证据边界不过界'],
    commonErrors: [
      { error: '只写“帮我取订单数据”', reason: '数据同事不知道取哪张表、哪些字段、哪些状态、哪个时间窗口。' },
      { error: '把需求单写成最终业务结论', reason: 'W3D5 只是确认口径和取数输入，不替代后续业务查询和指标判断。' },
    ],
    remediation: { label: '回看取数需求的字段和边界', sectionId: 'concepts', anchor: `concept-${ids[0]}` },
  }
}

export const w3d5: DailyCourse = {
  id: 'W3D5',
  contentVersion: 'w3d5-data-request-day01-v1',
  week: 3,
  day: 5,
  title: '向数据研发确认口径',
  subtitle: '把 W3D3 的基础查询和 W3D4 的质量风险，整理成数据同事能复核的取数需求单；本日只写 data-request.md，不提前教学聚合、GROUP BY、JOIN、指标计算或 W3D6 业务查询集。',
  duration: { core: 30, standard: 45, extension: 70, full: 120 },
  coreConceptGroups: [
    {
      id: 'request-intent-and-scope',
      title: '先说明为什么取数',
      conceptIds: ['data-request-purpose', 'business-question-scope'],
      summary: '取数需求不是字段清单，而是把业务问题限定到一个可复核范围。',
      boundary: '能说明要回答什么和不回答什么；不能替代业务决策或真实生产结论。',
    },
    {
      id: 'source-rule-and-output',
      title: '把口径变成可执行规则',
      conceptIds: ['field-source-assumption', 'filter-rule-contract', 'time-window-contract', 'exclusion-rule-contract', 'expected-output-shape'],
      summary: '数据同事需要知道表、字段、筛选、时间、排除和输出形状，才能判断这份需求是否可取数。',
      boundary: '只定义取数规则和预期输出，不做聚合、分组、连接或指标计算。',
    },
    {
      id: 'review-and-evidence-boundary',
      title: '留下确认问题和证据边界',
      conceptIds: ['review-question-boundary'],
      summary: '一份合格需求单必须主动暴露未知：TEST1 是否排除、O1018 如何处理、NULL 如何标注、时间边界是否按北京时间。',
      boundary: '能形成给数据研发的复核问题；不能证明数据质量已修复或生产口径已批准。',
    },
  ],
  prerequisiteConceptIds: [...prerequisiteConceptIds],
  learningPaths: {
    '30': {
      guidedStepIndices: [0, 1, 2, 3, 4, 5],
      guidedRecordIndices: [0, 1, 2],
      exerciseCount: 3,
      deliverablePromptCount: 6,
      deliverableChecklistIndices: [0, 1, 2, 3, 4],
      deliverableMinimumContributionCharacters: 220,
    },
    '45': {
      guidedStepIndices: [0, 1, 2, 3, 4, 5],
      guidedRecordIndices: [0, 1, 2, 3],
      exerciseCount: 4,
      deliverablePromptCount: 8,
      deliverableChecklistIndices: [0, 1, 2, 3, 4, 5, 6],
      deliverableMinimumContributionCharacters: 320,
    },
  },
  primaryGoal: '提交 `data-request.md`：逐条写清 request_id、business_question、decision_context、base_table、required_fields、filter_rules、time_window、status_scope、quality_exclusions、expected_output、sample_sql_or_pseudocode、review_questions、can_prove、cannot_prove、next_sql_task。',
  scenario: {
    role: '你是完成 W3D3 基础查询和 W3D4 数据质量检查的产品经理实习生。',
    situation: '团队想看 2026-08-31 当天 app 渠道已支付订单，用来准备一次运营复盘。但你已经知道 orders 表里有 TEST1、O1018 重复、NULL user_id、NULL paid_amount、0 元订单和 9 月 1 日边界行。',
    question: '怎样把“帮我取一下订单数据”改写成数据研发能判断、能复现、能指出口径风险的取数需求单？',
    stakes: '如果需求单只写字段名，数据同事会按自己的默认理解取数；产品经理随后拿到的结果看似准确，其实状态、时间、排除和质量边界都可能不一致。',
  },
  objectives: [
    { id: 'w3d5-objective-purpose', text: '能把模糊取数请求改写成明确业务问题', evidence: '`data-request.md` 写出 business_question、decision_context 和 cannot_prove。' },
    { id: 'w3d5-objective-rules', text: '能把字段、筛选、时间和排除规则写成可复核口径', evidence: 'base_table、required_fields、filter_rules、time_window、quality_exclusions 齐全。' },
    { id: 'w3d5-objective-review', text: '能向数据研发提出需要确认的口径问题', evidence: 'review_questions 覆盖 TEST1、O1018、NULL、0 元和时间边界。' },
    { id: 'w3d5-objective-boundary', text: '能说明取数需求单能证明和不能证明什么', evidence: 'can_prove、cannot_prove、next_sql_task 均不过界。' },
  ],
  prerequisites: [
    {
      id: 'w3d5-query-quality-readiness',
      conceptIds: [...prerequisiteConceptIds],
      prompt: '你是否已经能说明 W3D3 的 6 道基础查询，以及 W3D4 发现的 NULL、重复、测试数据、金额和时间边界风险？',
      passDescription: '能复述 orders 表字段，能解释 q1/q3/q4 的 SQL 边界，并能举出 TEST1、O1018、O1016、O1017、O1008 和 O1014 的风险。',
      remediationLabel: '回到 W3D3/W3D4 补查询和质量检查',
      remediationTarget: '#/lesson/W3D4',
      remediation: {
        purpose: 'W3D5 可以提前阅读；但没有 W3D3 查询和 W3D4 质量风险，取数需求会只剩字段清单。',
        steps: ['先补 basic-query-log.md：至少能解释 q1、q3、q4。', '再补 data-quality-checklist.md：至少记录 NULL、重复、测试数据、金额异常和时间边界。', '回到本课，把这些风险转成取数需求单里的确认问题。'],
        successCheck: '能说明 W3D5 不是重新查数据，而是把取数口径交给数据研发复核。',
      },
    },
  ],
  concepts: [
    {
      id: 'data-request-purpose',
      prerequisiteConceptIds: ['quality-evidence-boundary'],
      term: '取数需求目的', english: 'Data Request Purpose',
      definition: '取数需求目的说明为什么要取这份数据、要支持哪一次讨论，以及这份数据不能直接支持什么结论。',
      why: '数据同事先判断目的，才能判断字段、口径和输出形状是否匹配。',
      problemSolved: '回答“这次取数到底服务哪一个产品问题”。',
      input: '运营复盘、需求评审或问题排查中的一句业务诉求。',
      output: 'business_question、decision_context、can_prove、cannot_prove。',
      systemPosition: '位于 SQL 查询之前，是把产品问题交给数据研发的入口。',
      process: ['写出要支持的会议或决策。', '把问题限制为一张表能观察的范围。', '写清不能直接证明的业务结论。'],
      owner: '产品经理负责说明目的；数据研发负责判断取数可行性。',
      notResponsibleFor: '不负责替数据研发计算指标、修数据或批准最终口径。',
      compareWith: 'W3D3 的 query-question 是自己跑查询；W3D5 的 purpose 是让别人理解为什么要这份数据。',
      evidence: ['business_question。', 'decision_context。', 'cannot_prove。'],
      failureModes: ['只写“帮我取订单数据”。', '没有说明要支持哪次产品讨论。'],
      pmUse: '把“我要看订单”改写成“为 8 月 31 日 app 渠道支付复盘，确认可引用的 paid 订单明细”。',
      correctExample: '为运营复盘确认 2026-08-31 app 渠道 paid 订单明细，暂不判断收入增长原因。',
      incorrectExample: '帮我导一份所有订单，后面我再自己看看有没有用。',
    },
    {
      id: 'business-question-scope',
      prerequisiteConceptIds: ['query-question'],
      term: '业务问题范围', english: 'Business Question Scope',
      definition: '业务问题范围把取数问题限定到对象、时间、状态、渠道和不回答的问题，避免同一句话被不同人理解成不同口径。',
      why: '“看订单表现”可能表示 paid 明细、所有状态、某渠道、某日期或真实收入指标，必须先收窄。',
      problemSolved: '回答“这次取数包含谁、不包含谁”。',
      input: '业务诉求、W3D3 查询编号、W3D4 风险记录。',
      output: '清楚的 include/exclude 说明。',
      systemPosition: '位于取数需求的顶部，决定后续字段和筛选规则。',
      process: ['写入要看的订单对象。', '写入要排除的对象。', '写入不做的分析。'],
      owner: '产品经理定义问题范围；数据研发指出范围是否可取。',
      notResponsibleFor: '不负责定义 Week 4 的指标分子分母。',
      compareWith: '筛选规则是 SQL 条件；问题范围是为什么这些条件成立。',
      evidence: ['status_scope。', 'filter_rules。', 'cannot_prove。'],
      failureModes: ['范围同时包含明细、指标、用户画像和渠道结论。', '没有说明退款和待支付是否包含。'],
      pmUse: '需求单中写“本次只要 paid 明细，不纳入 cancelled/refunded/pending，也不计算 GMV”。',
      correctExample: '只取 status=paid 且 channel=app 的订单明细，用于人工检查样本。',
      incorrectExample: '看一下当天订单好不好，顺便判断活动效果。',
    },
    {
      id: 'field-source-assumption',
      prerequisiteConceptIds: ['table-row-column-preview', 'select-clause'],
      term: '字段与来源假设', english: 'Field Source Assumption',
      definition: '字段与来源假设说明数据来自哪张表、需要哪些列，以及这些列为什么能回答业务问题。',
      why: '字段名不是天然共享语言；产品经理必须写出 order_id、user_id、status、channel、paid_amount、paid_at、is_test 的用途。',
      problemSolved: '回答“数据同事应该从哪张表取哪些列”。',
      input: 'orders 表结构和要交付的分析视图。',
      output: 'base_table、required_fields 与字段用途说明。',
      systemPosition: '承接 W3D1 的表/行/列和 W3D3 的 SELECT 列清单。',
      process: ['指定 base_table=orders。', '列出必需字段。', '说明每个字段服务的口径或检查。'],
      owner: '产品经理提出字段假设；数据研发确认真实来源和字段含义。',
      notResponsibleFor: '不负责确认生产库最终表名、血缘或权限策略。',
      compareWith: 'SELECT 列清单是查询输出；字段来源假设是给数据同事复核的取数字段清单。',
      evidence: ['base_table。', 'required_fields。', 'review_questions。'],
      failureModes: ['只写“订单字段”。', '没说明 is_test 和 paid_at 为什么必须出现。'],
      pmUse: '写清 paid_at 用于时间窗口，is_test 用于排除测试订单，order_id 用于识别 O1018 重复。',
      correctExample: 'base_table: orders；required_fields: order_id,user_id,status,channel,paid_amount,paid_at,is_test。',
      incorrectExample: '字段让数据同事自己看着取。',
    },
    {
      id: 'filter-rule-contract',
      prerequisiteConceptIds: ['where-condition', 'comparison-operator', 'text-value-filter'],
      term: '筛选规则契约', english: 'Filter Rule Contract',
      definition: '筛选规则契约把产品口径翻译成可执行条件，例如 status="paid"、channel="app"，并说明为什么这样筛。',
      why: '数据研发不能执行“只看有效订单”这种口语，必须知道具体字段和值。',
      problemSolved: '回答“哪些行应该留下”。',
      input: 'status、channel、is_test 等字段与目标范围。',
      output: 'filter_rules 和 status_scope。',
      systemPosition: '承接 W3D3 的 WHERE 和文本值筛选，进入取数需求的可执行规则。',
      process: ['写出字段名。', '写出比较符和值。', '说明被排除值。'],
      owner: '产品经理提出业务筛选；数据研发确认字段枚举和可行性。',
      notResponsibleFor: '不负责计算筛选后的数量或指标。',
      compareWith: 'WHERE 是 SQL 语法；筛选契约是产品经理和数据研发对字段值的共同约定。',
      evidence: ['filter_rules。', 'status_scope。', 'sample_sql_or_pseudocode。'],
      failureModes: ['写“有效订单”但不写 status。', '把 paid、refunded、cancelled 混为一类。'],
      pmUse: '把“只看已支付 app 订单”写成 status="paid" AND channel="app"。',
      correctExample: 'filter_rules: status="paid"; channel="app"。',
      incorrectExample: 'filter_rules: 正常订单。',
    },
    {
      id: 'time-window-contract',
      prerequisiteConceptIds: ['date-range-boundary', 'time-boundary-risk'],
      term: '时间窗口契约', english: 'Time Window Contract',
      definition: '时间窗口契约用起点和终点说明“当天”的闭开边界，并写出时间字段和时区未知。',
      why: 'paid_at 的 2026-09-01 00:00:00 是否包含，会直接改变 2026-08-31 当天样本。',
      problemSolved: '回答“这次取数是哪段时间，边界点怎么算”。',
      input: 'paid_at 字段、日期要求和边界风险。',
      output: 'time_window 与 review_questions。',
      systemPosition: '承接 W3D3 日期范围和 W3D4 时间边界风险。',
      process: ['指定时间字段。', '写起点 >=。', '写终点 <。', '标注时区需要确认。'],
      owner: '产品经理写边界；数据研发确认时区、延迟和入库时间含义。',
      notResponsibleFor: '不负责时区换算实现或跨系统延迟分析。',
      compareWith: '日期查询只让自己跑通；时间契约让其他人知道临界行该如何处理。',
      evidence: ['time_window。', 'sample_sql_or_pseudocode。', 'review_questions。'],
      failureModes: ['写 paid_at="2026-08-31"。', '使用 <= "2026-09-01 00:00:00"。'],
      pmUse: '写 paid_at >= "2026-08-31 00:00:00" AND paid_at < "2026-09-01 00:00:00"，并询问是否按北京时间。',
      correctExample: 'time_window: paid_at >= 2026-08-31 00:00:00 and paid_at < 2026-09-01 00:00:00, timezone 待确认。',
      incorrectExample: 'time_window: 8 月 31 日当天。',
    },
    {
      id: 'exclusion-rule-contract',
      prerequisiteConceptIds: ['test-data-flag', 'duplicate-row', 'null-value', 'amount-anomaly'],
      term: '排除与标注规则', english: 'Exclusion Rule Contract',
      definition: '排除与标注规则说明测试订单、重复订单、NULL、0 元或异常金额该排除、保留还是单独标注。',
      why: 'W3D4 发现的风险不能停留在检查表里，取数时必须让数据研发知道希望如何处理。',
      problemSolved: '回答“风险行进入结果时该如何被处理”。',
      input: 'TEST1、O1018、O1016、O1017、O1008 等风险样本。',
      output: 'quality_exclusions 与 review_questions。',
      systemPosition: '位于筛选和时间之后，是把质量风险转成取数口径的关键步骤。',
      process: ['列出风险类型。', '写默认处理建议。', '写需要数据研发确认的问题。'],
      owner: '产品经理提出处理意图；数据研发确认真实规则和可执行性。',
      notResponsibleFor: '不负责直接删除数据、修复重复或补齐 NULL。',
      compareWith: 'W3D4 标注风险；W3D5 把风险写进取数需求供复核。',
      evidence: ['quality_exclusions。', 'review_questions。', 'cannot_prove。'],
      failureModes: ['只说“清洗一下”。', '直接要求删除所有异常数据但没有依据。'],
      pmUse: '写“is_test=1 默认排除；O1018 重复先保留并请确认去重规则；NULL amount 先标注”。',
      correctExample: 'quality_exclusions: exclude is_test=1; flag duplicate O1018 and NULL/0 amount for review。',
      incorrectExample: '把脏数据处理掉，不用说明排除还是标注。',
    },
    {
      id: 'expected-output-shape',
      prerequisiteConceptIds: ['column-alias', 'order-direction'],
      term: '期望输出形状', english: 'Expected Output Shape',
      definition: '期望输出形状说明要明细还是样本、要哪些列名、是否排序、是否需要别名和文件格式。',
      why: '同样的口径可以输出明细、去重列表或汇总表；本日只要求可复核明细，不要求指标汇总。',
      problemSolved: '回答“数据同事交付什么样的结果才算满足需求”。',
      input: '要复核的字段、排序需求和交付场景。',
      output: 'expected_output 与 sample_sql_or_pseudocode。',
      systemPosition: '承接 W3D3 的 SELECT、AS 和 ORDER BY。',
      process: ['说明输出粒度。', '列出列名和别名。', '写排序规则。', '写交付格式。'],
      owner: '产品经理定义可用输出；数据研发确认是否能导出。',
      notResponsibleFor: '不负责做可视化、指标看板或自动报表。',
      compareWith: '列别名是 SQL 展示动作；输出形状是协作交付标准。',
      evidence: ['expected_output。', 'required_fields。', 'sample_sql_or_pseudocode。'],
      failureModes: ['没说明明细还是汇总。', '没说明排序却要求看最近。'],
      pmUse: '写“输出订单明细 CSV，列为 order_id,user_id,channel,paid_amount,paid_time,is_test，按 paid_time 倒序”。',
      correctExample: 'expected_output: order-level CSV, paid_at AS paid_time, ORDER BY paid_at DESC。',
      incorrectExample: '给我一个结果就行，列名和排序你们自己决定。',
    },
    {
      id: 'review-question-boundary',
      prerequisiteConceptIds: ['quality-evidence-boundary', 'result-boundary'],
      term: '复核问题与证据边界', english: 'Review Questions and Evidence Boundary',
      definition: '复核问题与证据边界把未知口径、需要确认的人和不能证明的事项写在需求单结尾。',
      why: '取数需求单的价值不是装作确定，而是把不确定暴露给能确认的人。',
      problemSolved: '回答“哪些地方必须由数据研发确认，当前结果不能被怎样使用”。',
      input: '所有口径假设、质量风险和输出要求。',
      output: 'review_questions、can_prove、cannot_prove、next_sql_task。',
      systemPosition: '位于取数需求单结尾，是交接和后续 W3D6 的边界。',
      process: ['列出至少四个复核问题。', '写本需求单能证明的协作事实。', '写不能证明的业务结论。', '下一步只指向 W3D6。'],
      owner: '产品经理负责提问；数据研发或导师负责口径复核。',
      notResponsibleFor: '不负责替代真实审批、数据授权、生产数据审计或 W3D6 查询答案。',
      compareWith: 'can_prove 是需求单是否完整；cannot_prove 是业务结论还未成立。',
      evidence: ['review_questions。', 'can_prove。', 'cannot_prove。', 'next_sql_task。'],
      failureModes: ['不写任何待确认问题。', '把本地教学样本写成真实生产口径已批准。'],
      pmUse: '在需求单最后问：TEST1 是否排除、O1018 是否按 order_id 去重、NULL amount 如何标注、paid_at 是否北京时间。',
      correctExample: '不能证明真实生产口径已批准、真实数据质量已修复、指标或 W3D6 查询答案正确。',
      incorrectExample: '数据同事按这个取就一定是最终结论。',
    },
  ],
  diagram: {
    title: '取数需求单口径确认链',
    caption: '从业务目的出发，经数据源、筛选、时间、排除、输出和复核问题，形成 data-request.md。',
    nodes: [
      { id: 'purpose', label: '取数目的', description: '说明要支持哪次产品讨论。', input: '业务诉求', output: 'business_question/decision_context', owner: '产品经理', evidence: 'data-request.md 顶部' },
      { id: 'source-fields', label: '表与字段', description: '指定 orders 和必需字段。', input: 'orders 表结构', output: 'base_table/required_fields', owner: '产品经理+数据研发', evidence: '字段清单' },
      { id: 'rules', label: '筛选与时间', description: '把状态、渠道和 paid_at 边界写成可执行规则。', input: 'W3D3 SQL', output: 'filter_rules/time_window/status_scope', owner: '产品经理', evidence: '伪 SQL' },
      { id: 'quality', label: '排除与标注', description: '把 TEST1、O1018、NULL 和 0 元写成确认项。', input: 'W3D4 检查表', output: 'quality_exclusions', owner: '产品经理+数据研发', evidence: 'review_questions' },
      { id: 'handoff', label: '输出与边界', description: '定义交付形状并写 can/cannot prove。', input: '口径假设', output: 'expected_output/cannot_prove', owner: '产品经理', evidence: 'data-request.md 结尾' },
    ],
    branches: [
      { from: 'purpose', to: 'source-fields', label: '确定对象', kind: 'normal' },
      { from: 'source-fields', to: 'rules', label: '转成条件', kind: 'normal' },
      { from: 'rules', to: 'quality', label: '加入质量风险', kind: 'normal' },
      { from: 'quality', to: 'handoff', label: '形成交接', kind: 'normal' },
      { from: 'purpose', to: 'handoff', label: '只说帮我取数', kind: 'failure' },
    ],
    evidenceNotes: [
      '需求单必须能让数据同事复现表、字段、筛选、时间、排除和输出。',
      '能证明取数口径已被清楚提出；不能证明真实生产数据、指标、GROUP BY、JOIN 或 W3D6 查询答案正确。',
      '所有 SQL 片段只作为 sample_sql_or_pseudocode，用于口径沟通，不替代数据研发复核。',
    ],
  },
  demonstration: {
    title: '教师示范：把“帮我取订单数据”改成可复核需求单',
    businessProblem: '运营要复盘 2026-08-31 app 渠道已支付订单，但 orders 表存在 TEST1、O1018 重复、NULL 和日期边界风险。现在要把模糊请求改成 data-request.md。',
    finalConclusion: '一份合格取数需求单能说明：本次要取 orders 的订单明细，筛选 status=paid、channel=app、paid_at 闭开窗口；测试、重复、NULL、0 元和边界行需要排除或标注；输出按 paid_at 倒序，并把待确认问题交给数据研发。',
    conclusionLimit: '不能证明真实生产口径已批准、数据质量已修复、收入或用户指标正确，也不能提前完成聚合、GROUP BY、JOIN 或 W3D6 业务查询集。',
    steps: [
      { title: '改写业务问题', action: '把“帮我取订单数据”改成“为 2026-08-31 app paid 订单复盘取明细”。', reason: '先限定目的和范围，字段才有依据。', evidence: 'business_question、decision_context。', proves: '能证明需求目的清楚。', limitation: '不证明取数结果已经正确。' },
      { title: '指定表和字段', action: '写 base_table=orders；required_fields=order_id,user_id,status,channel,paid_amount,paid_at,is_test。', reason: '数据同事要知道从哪里取、取什么。', evidence: 'base_table 与 required_fields 字段清单。', proves: '能证明取数输入可复核。', limitation: '不证明生产表名或字段血缘。' },
      { title: '写筛选和时间窗口', action: '写 status="paid" AND channel="app"，paid_at >= "2026-08-31" AND paid_at < "2026-09-01"。', reason: '把口语口径转成可执行条件。', evidence: 'filter_rules、time_window。', proves: '能证明口径边界明确。', limitation: '不证明时区、延迟或真实数据完整性。' },
      { title: '加入质量排除与标注', action: '写 is_test=1 默认排除；O1018 重复、NULL user_id/paid_amount、0 元订单先标注并请确认。', reason: 'W3D4 的质量风险必须进入取数需求。', evidence: 'quality_exclusions、review_questions。', proves: '能证明风险已暴露给复核人。', limitation: '不证明风险已修复。' },
      { title: '定义输出形状', action: '写输出订单明细 CSV，paid_at AS paid_time，按 paid_time DESC。', reason: '同一口径可能输出不同形状，必须说清交付物。', evidence: 'expected_output。', proves: '能证明交付格式明确。', limitation: '不证明汇总指标。' },
      { title: '收束复核问题和边界', action: '写 review_questions、can_prove、cannot_prove、next_sql_task=W3D6。', reason: '把未知留给能确认的人，并防止过度结论。', evidence: 'data-request.md 字段齐全。', proves: '能形成可交接需求单。', limitation: '不替代真实审批、生产数据取数或后续业务查询。' },
    ],
  },
  guidedLab: {
    title: '6 条取数需求确认台',
    goal: '围绕同一个 orders 取数请求，依次修正六类常见缺口：scope-missing、field-source-missing、filter-rule-missing、time-window-ambiguous、quality-exclusion-missing、qualified-data-request。',
    safety: '教学模拟 · 只基于本地 orders 表、W3D3 查询记录和 W3D4 质量检查表写需求单；不连接真实数据库、不提交真实工单、不打开生产数据。',
    conceptIds: [...conceptIds],
    predictionPrompt: '预测：一份“帮我取订单数据”的请求，最容易让数据研发误解的是业务范围、字段来源、筛选规则、时间窗口还是质量排除？',
    steps: [
      { title: 'R1 修正范围缺失', action: '把“帮我取订单数据”改成“为 2026-08-31 app 渠道 paid 订单复盘取订单明细”。', observe: 'business_question 与 decision_context 变具体。', explanation: '数据同事先知道服务哪次讨论。', proves: '能证明目的和范围被明确提出。', cannotProve: '不能证明数据已经取出或结论成立。' },
      { title: 'R2 修正字段来源缺失', action: '补 base_table=orders 和 required_fields。', observe: 'order_id、user_id、status、channel、paid_amount、paid_at、is_test 都进入需求。', explanation: '字段清单让取数输入可复核。', proves: '能证明字段假设完整。', cannotProve: '不能证明真实生产表字段完全一致。' },
      { title: 'R3 修正筛选规则缺失', action: '写 filter_rules: status="paid"; channel="app"。', observe: '“有效订单”被翻译成字段和值。', explanation: '筛选规则必须能转成 WHERE。', proves: '能证明行保留规则明确。', cannotProve: '不能证明状态枚举最终口径。' },
      { title: 'R4 修正时间窗口歧义', action: '写 time_window: paid_at >= "2026-08-31 00:00:00" AND paid_at < "2026-09-01 00:00:00"。', observe: 'O1014 这样的 9 月 1 日 0 点行被标记为边界确认。', explanation: '闭开边界避免当天口径误入下一天。', proves: '能证明时间条件可复核。', cannotProve: '不能证明时区和入库延迟。' },
      { title: 'R5 修正质量排除缺失', action: '补 quality_exclusions: exclude is_test=1; flag O1018 duplicate; flag NULL/0 amount。', observe: 'TEST1、O1018、O1016、O1017、O1008 成为复核问题。', explanation: '质量风险要进入需求单。', proves: '能证明 W3D4 风险被交接。', cannotProve: '不能证明风险已修复。' },
      { title: 'R6 形成合格取数需求单', action: '补 expected_output、sample_sql_or_pseudocode、review_questions、can_prove、cannot_prove、next_sql_task。', observe: 'data-request.md 字段齐全，可交给数据研发复核。', explanation: '需求单以可复现口径和明确未知收束。', proves: '能证明本地教学需求单结构合格。', cannotProve: '不能证明真实生产取数完成、指标正确或 W3D6 查询答案正确。' },
    ],
    recordPrompts: [
      '记录 R1/R2：写出业务目的、范围、base_table 和 required_fields。',
      '记录 R3/R4：写出 filter_rules、status_scope、time_window 和边界问题。',
      '记录 R5：写出 TEST1、O1018、NULL、0 元的排除或标注规则。',
      '记录 R6：写出 expected_output、review_questions、can_prove、cannot_prove 和 next_sql_task。',
    ],
    comparePrompt: '对照 W3D3 basic-query-log.md 与 W3D4 data-quality-checklist.md：你的取数需求是否把查询条件和质量风险都变成了明确口径，而不是只列字段？',
    passCriteria: ['六条取数需求确认路径都完成并记录。', '每条都有业务问题、缺口、修正字段、数据研发确认问题、能证明和不能证明。', '需求单必须包含表、字段、筛选、时间、排除、输出和复核问题。', '不能把教学模拟写成真实生产、指标、GROUP BY、JOIN 或 W3D6 查询结论。'],
  },
  independentLab: {
    title: '独立变式：给数据同事写一条 app paid 明细取数需求',
    scenario: '你要请数据同事取 2026-08-31 app 渠道 paid 订单明细。W3D4 已经发现 TEST1、O1018、NULL user_id、NULL paid_amount、0 元订单和日期边界行。',
    conceptIds: [...conceptIds],
    changedConditions: ['只写“帮我取 app 订单”，没有业务目的。', '写了 fields，但没有 base_table 和字段用途。', '写了 8 月 31 日，但没有 paid_at 闭开边界。', '写了 paid，但没有说明 cancelled/refunded/pending 是否排除。', '发现 TEST1/O1018/NULL 后，没有 review_questions。'],
    task: '任选一个缺口，把它修成 data-request.md 的完整条目，必须包含取数目的、字段来源、筛选时间、质量排除、输出形状和证据边界。',
    predictionPrompt: '先预测这个缺口会让数据研发产生哪种误解。',
    evidenceRequirements: ['必须引用 orders 表字段和至少三个 W3D4 风险样本。', '必须写明只证明取数需求结构合格，不证明真实生产、指标、GROUP BY、JOIN 或 W3D6 查询答案。'],
    passCriteria: ['能把模糊请求改成可复核取数目的。', '字段、筛选、时间、质量排除和输出形状齐全。', 'review_questions 至少包含四个待确认问题。', 'next_sql_task 只指向 W3D6，不提前完成 W3D6。'],
    remediation: { label: '回看取数需求单口径确认链', sectionId: 'diagram', anchor: 'demonstration-conclusion' },
  },
  exercises: [
    exercise('w3d5-purpose-scope', ['概念与边界', '工作场景'], ['data-request-purpose', 'business-question-scope'], '“帮我取订单数据”最大的问题是什么？', ['缺少要支持的业务问题、范围和不能证明的结论', 'SQL 没有写 GROUP BY', '没有先做 JOIN'], 0, '取数需求先说明目的和范围；GROUP BY 与 JOIN 都不是本日首学内容。'),
    exercise('w3d5-field-source', ['机制推演', '证据判断'], ['field-source-assumption', 'expected-output-shape'], '哪组字段最适合支持 app paid 订单明细复核？', ['orders 表的 order_id,user_id,status,channel,paid_amount,paid_at,is_test，并说明输出明细', '只写 amount 字段', '让数据同事自己决定所有字段'], 0, '字段要绑定来源、用途和输出形状，不能只给泛称。'),
    exercise('w3d5-time-quality', ['证据判断', '综合变式'], ['time-window-contract', 'exclusion-rule-contract'], '取 2026-08-31 当天 paid 明细时，哪条需求最稳妥？', ['paid_at >= 起点且 < 下一天起点，并确认 TEST1/O1018/NULL/0 元处理', 'paid_at = "2026-08-31" 且不管测试数据', '把 9 月 1 日 0 点一起算进去'], 0, '时间和质量排除必须同时写清，避免边界行和风险行被默认处理。'),
    exercise('w3d5-review-boundary', ['工作场景', '综合变式'], ['review-question-boundary'], 'data-request.md 结尾最应该写什么？', ['复核问题、can_prove、cannot_prove 和 next_sql_task=W3D6', '直接给出真实指标结论', '声称生产数据已经修复'], 0, '结尾要暴露未知并收束边界，不声称生产和指标结论。'),
  ],
  deliverable: {
    title: '取数需求单',
    conceptIds: [...conceptIds],
    purpose: '让学习者用 data-request.md 把业务目的、字段来源、筛选时间、质量排除、输出形状和复核问题写成数据研发能执行的口径确认单；本课所有内容都是教学模拟。',
    whenToUse: '当产品经理需要数据同事协助取数、复核口径或准备后续 SQL 业务查询前使用。',
    audience: '数据研发、数据分析同事、导师，以及未来在 W3D6 继续回答业务问题的自己。',
    fields: [
      { name: 'request_id', meaning: '取数需求编号，例如 R6-qualified-data-request。', source: '本课六条确认路径' },
      { name: 'business_question', meaning: '本次取数要回答的具体业务问题。', source: '业务场景' },
      { name: 'decision_context', meaning: '数据将用于哪次复盘、评审或排查。', source: '产品讨论背景' },
      { name: 'base_table', meaning: '假设数据来源表，本课为 orders。', source: 'W3D1 表预览' },
      { name: 'required_fields', meaning: '需要输出或用于筛选/排除的字段。', source: 'orders 表字段' },
      { name: 'filter_rules', meaning: '可执行筛选条件，如 status="paid" AND channel="app"。', source: 'W3D3 基础查询' },
      { name: 'time_window', meaning: '时间字段、起点、终点和时区待确认。', source: 'W3D3/W3D4 日期边界' },
      { name: 'status_scope', meaning: '纳入和排除哪些 status。', source: '状态覆盖检查' },
      { name: 'quality_exclusions', meaning: 'TEST1、O1018、NULL、0 元等排除或标注规则。', source: 'W3D4 质量检查表' },
      { name: 'expected_output', meaning: '明细或样本、列名、排序、格式。', source: '产品交付需要' },
      { name: 'sample_sql_or_pseudocode', meaning: '用于沟通口径的样例 SQL 或伪代码。', source: '本课教学模拟' },
      { name: 'review_questions', meaning: '需要数据研发确认的问题。', source: '未知口径清单' },
      { name: 'can_prove', meaning: '这份需求单能证明的协作事实。', source: '字段和口径完整性' },
      { name: 'cannot_prove', meaning: '不能证明的生产、指标、GROUP BY、JOIN 或查询答案。', source: '证据边界自检' },
      { name: 'next_sql_task', meaning: '下一步只进入 W3D6 业务查询集。', source: '课程路线' },
    ],
    badExample: 'request_id: R1\nbusiness_question: 帮我取订单数据\nrequired_fields: 订单字段\nfilter_rules: 有效订单\ntime_window: 8月31日\nexpected_output: 随便导出\ncan_prove: 拿到数据后就能证明业务表现很好。',
    badReasons: ['业务问题和决策场景不清楚。', '没有 base_table、required_fields 的具体字段和用途。', '筛选、时间、状态和质量排除都是口语。', '没有 review_questions 和 cannot_prove，且越界成业务结论。'],
    revisionSteps: ['先写清本次取数服务哪次复盘或评审。', '指定 base_table=orders 和必需字段。', '把 paid、app、2026-08-31 写成可执行筛选和闭开时间窗口。', '把 TEST1、O1018、NULL、0 元和边界行写进 quality_exclusions 与 review_questions。', '用 can_prove/cannot_prove 收束到需求单完整性，不声称真实指标正确。'],
    goodExample: 'request_id: R6-qualified-data-request\nbusiness_question: 为 2026-08-31 app 渠道 paid 订单复盘，取可人工复核的订单明细\ndecision_context: 运营复盘前先确认订单明细口径，暂不计算 GMV、用户数或转化率\nbase_table: orders\nrequired_fields: order_id,user_id,status,channel,paid_amount,paid_at,is_test\nfilter_rules: status = "paid" AND channel = "app"\ntime_window: paid_at >= "2026-08-31 00:00:00" AND paid_at < "2026-09-01 00:00:00"; timezone 待数据研发确认\nstatus_scope: include paid; exclude cancelled/refunded/pending unless data reviewer says otherwise\nquality_exclusions: exclude is_test=1/TEST1 by default; flag duplicate O1018; flag NULL user_id, NULL paid_amount and paid_amount=0 for review\nexpected_output: order-level CSV; columns order_id,user_id,status,channel,paid_amount,paid_at AS paid_time,is_test; ORDER BY paid_at DESC\nsample_sql_or_pseudocode: SELECT order_id,user_id,status,channel,paid_amount,paid_at AS paid_time,is_test FROM orders WHERE status = "paid" AND channel = "app" AND paid_at >= "2026-08-31 00:00:00" AND paid_at < "2026-09-01 00:00:00" ORDER BY paid_at DESC;\nreview_questions: 1. is_test=1 和 TEST1 是否必须排除；2. O1018 是否按 order_id 去重；3. NULL user_id/paid_amount 是否保留并标注；4. 0 元订单是否纳入 paid 明细；5. paid_at 是否北京时间\ncan_prove: 能证明本地教学中的取数目的、字段、筛选、时间、质量排除和输出形状已经写成可复核需求\ncannot_prove: 不能证明真实生产数据已取出、生产口径已批准、数据质量已修复、指标正确、GROUP BY、JOIN 或 W3D6 查询答案正确\nnext_sql_task: W3D6 再用确认后的口径回答真实业务问题\n',
    guidedPrompts: ['写 request_id。', '写 business_question 和 decision_context。', '写 base_table 和 required_fields。', '写 filter_rules、time_window 和 status_scope。', '写 quality_exclusions。', '写 expected_output。', '写 sample_sql_or_pseudocode。', '写 review_questions、can_prove、cannot_prove 和 next_sql_task。'],
    blankTemplate: 'request_id:\nbusiness_question:\ndecision_context:\nbase_table:\nrequired_fields:\nfilter_rules:\ntime_window:\nstatus_scope:\nquality_exclusions:\nexpected_output:\nsample_sql_or_pseudocode:\nreview_questions:\ncan_prove:\ncannot_prove:\nnext_sql_task:\n',
    standardTemplate: 'request_id: R6-qualified-data-request\nbusiness_question: 为 2026-08-31 app 渠道 paid 订单复盘，取可人工复核的订单明细\ndecision_context: 运营复盘前确认订单明细口径，暂不计算 GMV、用户数或转化率\nbase_table: orders\nrequired_fields: order_id,user_id,status,channel,paid_amount,paid_at,is_test\nfilter_rules: status = "paid" AND channel = "app"\ntime_window: paid_at >= "2026-08-31 00:00:00" AND paid_at < "2026-09-01 00:00:00"; timezone 待确认\nstatus_scope: include paid; exclude cancelled/refunded/pending unless reviewer confirms otherwise\nquality_exclusions: exclude TEST1/is_test=1; flag O1018 duplicate; flag NULL user_id, NULL paid_amount and paid_amount=0\nexpected_output: order-level CSV; paid_at AS paid_time; ORDER BY paid_at DESC\nsample_sql_or_pseudocode: SELECT order_id,user_id,status,channel,paid_amount,paid_at AS paid_time,is_test FROM orders WHERE status = "paid" AND channel = "app" AND paid_at >= "2026-08-31 00:00:00" AND paid_at < "2026-09-01 00:00:00" ORDER BY paid_at DESC;\nreview_questions: 请确认 TEST1 是否排除、O1018 是否去重、NULL 与 0 元如何标注、paid_at 是否北京时间\ncan_prove: 能证明本地教学取数需求已写清目的、字段、筛选、时间、排除、输出和复核问题\ncannot_prove: 不能证明真实生产数据已取出、口径已批准、数据质量已修复、指标正确、GROUP BY、JOIN 或 W3D6 查询答案正确\nnext_sql_task: W3D6 再用确认后的口径回答真实业务问题\n',
    checklist: ['request_id、business_question 和 decision_context 齐全。', 'base_table 固定为 orders，required_fields 写出关键字段。', 'filter_rules、time_window 和 status_scope 能转成 WHERE 条件。', 'quality_exclusions 覆盖 TEST1、O1018、NULL、0 元和日期边界。', 'expected_output 说明明细、列名、排序和格式。', 'review_questions 至少包含四个数据研发确认问题。', 'cannot_prove 明确排除真实生产、指标、GROUP BY、JOIN 和 W3D6 答案。'],
  },
  memory: {
    conceptIds: [...conceptIds],
    anchors: ['取数需求先写目的，不先堆字段。', '字段来源、筛选、时间、排除和输出必须同时可复核。', 'W3D4 的质量风险要进入 quality_exclusions 和 review_questions。', '需求单只能证明口径被清楚提出，不能证明真实结论。'],
    closedBookPrompt: '闭卷解释：怎样把“帮我取订单数据”改写成数据研发能复核的取数需求单？请按目的、范围、字段、筛选、时间、排除、输出和复核边界复述。',
    microOperation: '不看正文，写出 app paid 订单明细需求的 filter_rules、time_window、quality_exclusions 和 review_questions。',
    unresolvedPrompt: '写出你进入 W3D6 前最容易混淆的一处：字段来源、筛选口径、时间边界、质量排除还是证据边界？准备怎么向数据同事确认？',
    reviewStages: [
      { stage: 'D1', task: '闭卷写出 data-request.md 的 15 个字段，并说明前三个字段为什么不能省。' },
      { stage: 'D3', task: '把“帮我取订单数据”改写成带业务问题、表和字段的需求。' },
      { stage: 'D7', task: '写出 2026-08-31 当天 paid_at 的闭开时间窗口和时区复核问题。' },
      { stage: 'D14', task: '列出 TEST1、O1018、NULL、0 元订单分别应该排除还是标注。' },
      { stage: 'D30', task: '给一份缺少输出形状的需求单补 expected_output 和 sample_sql_or_pseudocode。' },
      { stage: 'D60', task: '不看模板重写一份 app paid 明细取数需求单，并写 can_prove/cannot_prove。' },
    ],
  },
  nextLesson: { id: 'W3D6', title: '回答真实业务问题', bridge: '下一课才把确认后的口径用于 12 道业务查询集；W3D5 只完成取数需求单，不提前教学聚合、GROUP BY、JOIN、指标或最终业务结论。' },
}
