import type { DailyCourse, Exercise } from './types'

const conceptIds = [
  'business-query-set',
  'query-contract-reuse',
  'row-level-answer',
  'quality-flagged-answer',
  'sql-file-organization',
  'answer-log-boundary',
  'stakeholder-handoff-note',
  'weekly-sql-review',
] as const

const prerequisiteConceptIds = [
  'terminal-shell',
  'working-directory',
  'file-path',
  'safe-lab-copy',
  'sqlite-database-file',
  'sqlite3-session',
  'setup-sql-script',
  'table-row-column-preview',
  'sql-statement',
  'select-clause',
  'from-clause',
  'where-gate',
  'order-by-stage',
  'limit-stage',
  'execution-order',
  'result-boundary',
  'query-question',
  'where-condition',
  'comparison-operator',
  'text-value-filter',
  'date-range-boundary',
  'order-direction',
  'column-alias',
  'distinct-result',
  'quality-question',
  'null-value',
  'duplicate-row',
  'status-coverage',
  'test-data-flag',
  'time-boundary-risk',
  'amount-anomaly',
  'quality-evidence-boundary',
  'data-request-purpose',
  'business-question-scope',
  'field-source-assumption',
  'filter-rule-contract',
  'time-window-contract',
  'exclusion-rule-contract',
  'expected-output-shape',
  'review-question-boundary',
] as const

function exercise(
  id: string,
  categories: Exercise['categories'],
  ids: string[],
  prompt: string,
  options: string[],
  answerIndex: number,
  referenceAnswer: string,
): Exercise {
  return {
    id,
    kind: 'single-choice',
    categories,
    conceptIds: ids,
    prompt,
    hint: '先确认这是不是一条单表明细查询，再看是否复用了 W3D5 口径、是否标注 W3D4 质量风险、是否写清 can_prove/cannot_prove。',
    options: options.map((label, index) => ({
      label,
      rationale: index === answerIndex ? '这项把业务问题、单表 SQL、观察结果、质量标注和交接边界放在同一条查询记录里。' : '这项要么没有复用口径，要么把明细查询越界说成指标、聚合、JOIN 或真实生产结论。',
      couldBeTrueWhen: index === answerIndex ? '当学习者只基于本地 orders 教学表完成 W3 复盘查询集。' : '只有 W4/W5 后续课程补齐指标口径、聚合或 JOIN 后，才可能支持更强结论。',
    })),
    answerIndex,
    referenceAnswer,
    reasoning: [
      'W3D6 是 W3 综合迁移，任务是把 W3D3 查询、W3D4 风险和 W3D5 需求单合成 12 条可复核明细查询。',
      '每条记录都必须包含 SQL、expected_rows、observed_result、quality_flags、can_prove 和 cannot_prove。',
      '本日仍不教学聚合、GROUP BY、JOIN 或指标计算，也不把本地教学模拟写成生产结论。',
    ],
    rubric: ['业务问题具体', 'SQL 只用单表基础查询', '质量标注可追溯', '交接边界清楚'],
    commonErrors: [
      { error: '只给 SQL，不写业务问题和交接说明', reason: '复盘查询集要让后续自己或同事知道为什么查、看到什么、下一步问什么。' },
      { error: '把明细样本写成指标结论', reason: '没有 W4 指标定义和聚合，本日只能回答行级事实与风险提示。' },
    ],
    remediation: { label: '回看业务查询集的证据边界', sectionId: 'concepts', anchor: `concept-${ids[0]}` },
  }
}

export const w3d6: DailyCourse = {
  id: 'W3D6',
  contentVersion: 'w3d6-business-query-set-day01-v1',
  week: 3,
  day: 6,
  title: '回答真实业务问题',
  subtitle: '把 W3D3 的基础查询、W3D4 的质量风险和 W3D5 的取数口径，整理成 12 道单表业务查询集；本日不提前教学聚合、GROUP BY、JOIN、指标或 W4D1 正式内容。',
  duration: { core: 30, standard: 45, extension: 72, full: 124 },
  coreConceptGroups: [
    {
      id: 'query-set-from-request',
      title: '从一个取数需求到一组查询',
      conceptIds: ['business-query-set', 'query-contract-reuse', 'sql-file-organization'],
      summary: '业务查询集不是多写几条 SQL，而是把同一个需求拆成可追溯、可复跑、可交接的一组单表查询。',
      boundary: '能形成行级查询证据；不能计算指标、汇总收入或完成 JOIN 对账。',
    },
    {
      id: 'row-answer-with-quality',
      title: '行级答案必须带质量标注',
      conceptIds: ['row-level-answer', 'quality-flagged-answer', 'answer-log-boundary'],
      summary: '查询结果回答的是哪些行被留下、列怎样展示、风险行如何标注，而不是业务数字本身。',
      boundary: '能说明 TEST1、O1018、NULL、0 元和边界行如何影响阅读；不能证明生产数据已修复。',
    },
    {
      id: 'handoff-and-review',
      title: '把查询集交给后续复核',
      conceptIds: ['stakeholder-handoff-note', 'weekly-sql-review'],
      summary: '每条查询最后都要写 handoff_note 与 next_review_question，让下一课或数据同事知道还要确认什么。',
      boundary: '能完成 W3 周复盘交接；不能宣称 W4D1、指标、聚合、GROUP BY 或 JOIN 已完成。',
    },
  ],
  prerequisiteConceptIds: [...prerequisiteConceptIds],
  learningPaths: {
    '30': {
      guidedStepIndices: [0, 1, 2, 3, 4, 5],
      guidedRecordIndices: [0, 1, 2, 3, 4, 5],
      exerciseCount: 3,
      deliverablePromptCount: 6,
      deliverableChecklistIndices: [0, 1, 2, 3, 4],
      deliverableMinimumContributionCharacters: 260,
    },
    '45': {
      guidedStepIndices: [0, 1, 2, 3, 4, 5],
      guidedRecordIndices: [0, 1, 2, 3, 4, 5],
      exerciseCount: 4,
      deliverablePromptCount: 8,
      deliverableChecklistIndices: [0, 1, 2, 3, 4, 5, 6],
      deliverableMinimumContributionCharacters: 380,
    },
  },
  primaryGoal: '提交 `business-query-set.sql` 与 `business-query-log.md`：按 12 道业务查询逐条写 query_id、business_question、request_ref、base_table、sql_text、expected_rows、observed_result、quality_flags、can_prove、cannot_prove、handoff_note、next_review_question。',
  scenario: {
    role: '你是完成 W3D1-W3D5 的产品经理实习生。',
    situation: '运营复盘前，你拿着 W3D5 的 data-request.md，需要用本地 orders 教学表整理一份 12 道业务查询集：既能回答“哪些订单行符合条件”，也能把 TEST1、O1018、NULL、0 元和日期边界风险交接出去。',
    question: '怎样用已经学过的单表 SELECT、WHERE、日期边界、ORDER BY、LIMIT、AS、DISTINCT，把一个真实业务问题拆成 12 条可复核查询记录？',
    stakes: '如果只给一条 SQL 或只给一句结论，后续复盘会不知道每条结果来自什么口径、风险在哪里、哪些问题必须留到 W4D1 或数据同事确认。',
  },
  objectives: [
    { id: 'w3d6-objective-set', text: '能把一个取数需求拆成 12 条单表业务查询', evidence: '`business-query-set.sql` 包含 BQ01-BQ12，且都只 FROM orders。' },
    { id: 'w3d6-objective-log', text: '能逐条记录预期、观察、质量标注和证据边界', evidence: '`business-query-log.md` 每条包含 expected_rows、observed_result、quality_flags、can_prove、cannot_prove。' },
    { id: 'w3d6-objective-reuse', text: '能复用 W3D5 取数口径并引用 W3D4 风险', evidence: 'request_ref、quality_flags 和 handoff_note 能看到 W3D3/W3D4/W3D5 来源。' },
    { id: 'w3d6-objective-boundary', text: '能说明下一步只进入 W4D1 指标定义，不提前完成指标', evidence: 'next_review_question 指向 W4D1 要确认分子、分母、时间窗口和排除规则。' },
  ],
  prerequisites: [
    {
      id: 'w3d6-week3-readiness',
      conceptIds: [...prerequisiteConceptIds],
      prompt: '你是否已经能复述 W3D3 的 6 道基础查询、W3D4 的 6 条质量风险，以及 W3D5 的取数需求单字段？',
      passDescription: '能说明 orders 表、status/channel/paid_at 条件、TEST1、O1018、NULL、0 元和 data-request.md 的复核问题。',
      remediationLabel: '回到 W3D3-W3D5 补查询、质量和取数口径',
      remediationTarget: '#/lesson/W3D5',
      remediation: {
        purpose: 'W3D6 可提前阅读；但没有前三课证据时，12 道查询集会退化成 SQL 清单，不能作为复盘交接。',
        steps: ['补齐 W3D3 basic-query-log.md：至少解释 Q1、Q3、Q4、Q6。', '补齐 W3D4 data-quality-checklist.md：至少记录 TEST1、O1018、NULL、0 元和边界行。', '补齐 W3D5 data-request.md：明确 filter_rules、time_window、quality_exclusions 和 review_questions。'],
        successCheck: '能说出 W3D6 的每条查询都必须有 request_ref、quality_flags、handoff_note 和 next_review_question。',
      },
    },
  ],
  concepts: [
    {
      id: 'business-query-set',
      prerequisiteConceptIds: ['query-question', 'data-request-purpose'],
      term: '业务查询集',
      english: 'Business Query Set',
      definition: '业务查询集是一组围绕同一业务问题组织的 SQL，每条都有编号、问题、口径来源、结果观察和边界说明。',
      why: '真实复盘不会只问一个问题；产品经理需要把多个局部问题组织成可复跑的证据链。',
      problemSolved: '回答“这一周学到的 SQL 怎样服务一次完整复盘”。',
      input: 'W3D5 取数需求、orders 表字段和 W3D3/W3D4 记录。',
      output: 'business-query-set.sql 和 business-query-log.md。',
      systemPosition: '位于 W3 周末复盘，承接基础查询、质量检查和取数需求。',
      process: ['先固定同一个 request_ref。', '把问题拆成 12 条行级查询。', '逐条记录能证明和不能证明什么。'],
      owner: '产品经理组织查询集；数据库只执行具体 SQL。',
      notResponsibleFor: '不负责计算指标、聚合、分组、跨表 JOIN 或生产审批。',
      compareWith: 'W3D3 是 6 道基础动作；W3D6 是把这些动作组合成业务复盘查询集。',
      evidence: ['query_id。', 'business_question。', 'sql_text。', 'business-query-log.md。'],
      failureModes: ['只有散乱 SQL，没有共同业务目的。', '把查询集写成指标看板。'],
      pmUse: '把“复盘 app paid 订单”拆成 paid 行、app 行、当天边界、最近样本、风险标注和可交接样本。',
      correctExample: 'BQ01-BQ12 都围绕 R6-qualified-data-request，并各自说明观察和边界。',
      incorrectExample: '随便复制 12 条 SQL，然后写“业务表现很好”。',
    },
    {
      id: 'query-contract-reuse',
      prerequisiteConceptIds: ['filter-rule-contract', 'time-window-contract', 'exclusion-rule-contract'],
      term: '查询口径复用',
      english: 'Query Contract Reuse',
      definition: '查询口径复用是把 W3D5 已写清的筛选、时间和质量规则带入每条 SQL，而不是每题重新猜口径。',
      why: '同一复盘里，paid、app、日期边界和排除规则必须一致，否则结果之间不能相互解释。',
      problemSolved: '回答“这条查询沿用了哪份需求单口径”。',
      input: 'request_ref、filter_rules、time_window、quality_exclusions。',
      output: '每条查询中的 request_ref 和对应 SQL 条件。',
      systemPosition: '连接 W3D5 需求单和 W3D6 查询执行。',
      process: ['写 request_ref。', '复制已确认或待确认的条件。', '偏离口径时在 handoff_note 说明原因。'],
      owner: '产品经理负责复用和标注；数据同事负责确认真实口径。',
      notResponsibleFor: '不负责批准口径或定义指标分子分母。',
      compareWith: '查询问题问这条 SQL 要看什么；口径复用说明它继承了哪个规则。',
      evidence: ['request_ref。', 'sql_text。', 'handoff_note。'],
      failureModes: ['BQ01 用 paid，BQ03 忘记 paid。', '一题写 8 月 31 日，另一题把 9 月 1 日 0 点混入。'],
      pmUse: '每条记录都写 request_ref=R6-qualified-data-request，提醒自己沿用同一个时间窗口。',
      correctExample: 'status="paid" AND channel="app" AND paid_at >= "2026-08-31" AND paid_at < "2026-09-01"。',
      incorrectExample: '每条 SQL 临时想一个条件。',
    },
    {
      id: 'row-level-answer',
      prerequisiteConceptIds: ['result-boundary', 'where-condition', 'order-direction'],
      term: '行级答案',
      english: 'Row-level Answer',
      definition: '行级答案说明哪些订单行被 SQL 留下、按什么顺序展示、样本窗口到哪里停止。',
      why: '在没有聚合和指标定义前，产品经理能可靠交付的是明细行事实，不是业务数字。',
      problemSolved: '回答“这条查询实际留下了哪些行”。',
      input: 'SQL 输出和预期留下行。',
      output: 'expected_rows 与 observed_result。',
      systemPosition: '位于 SQL 执行之后、业务解释之前。',
      process: ['先写 expected_rows。', '再写 observed_result。', '检查是否越界成数量或趋势。'],
      owner: '学习者记录行级结果；后续课程再处理指标。',
      notResponsibleFor: '不负责汇总、比例、趋势、归因或决策判断。',
      compareWith: '行级答案是明细；指标答案要等 W4D1 先定义口径。',
      evidence: ['expected_rows。', 'observed_result。', 'LIMIT/ORDER BY 边界。'],
      failureModes: ['看到 5 行就说总数是 5。', '未排序却说最新。'],
      pmUse: '写“观察到 O1019、O1014、O1018、O1018、O1013”，而不是写“最近订单增长”。',
      correctExample: 'observed_result: O1018 出现两行，按 paid_at DESC 位于 8 月 31 日末尾。',
      incorrectExample: 'observed_result: 当天订单表现优秀。',
    },
    {
      id: 'quality-flagged-answer',
      prerequisiteConceptIds: ['quality-evidence-boundary', 'test-data-flag', 'duplicate-row', 'null-value', 'amount-anomaly'],
      term: '带质量标注的答案',
      english: 'Quality-flagged Answer',
      definition: '带质量标注的答案是在查询结果旁标出 TEST1、O1018、NULL、0 元、跨天边界等风险，不把它们静默吞掉。',
      why: '明细结果看似能回答问题，但风险行会改变后续解释；产品经理必须把这些不确定性暴露出来。',
      problemSolved: '回答“哪些行会影响这条结果的可信度”。',
      input: 'W3D4 风险样本和当前查询结果。',
      output: 'quality_flags。',
      systemPosition: '位于 observed_result 和 handoff_note 之间。',
      process: ['检查是否含 TEST1。', '检查是否含 O1018。', '检查 NULL、0 元和日期边界。', '写入 quality_flags。'],
      owner: '产品经理标注风险；数据研发确认处理规则。',
      notResponsibleFor: '不负责删除、修复或自动清洗数据。',
      compareWith: 'W3D4 是发现风险；W3D6 是把风险贴到具体业务查询答案上。',
      evidence: ['quality_flags。', 'handoff_note。', 'next_review_question。'],
      failureModes: ['结果包含 TEST1 但未标注。', 'O1018 重复出现却直接当两条订单解释。'],
      pmUse: '在 BQ12 中写 quality_flags: exclude TEST1; flag O1018 duplicate; flag NULL/0 amount for review。',
      correctExample: 'quality_flags: TEST1 excluded; O1018 duplicate flagged; NULL user_id remains review question。',
      incorrectExample: '数据看起来没问题，所以不用标注 TEST1、O1018、NULL 或 0 元风险。',
    },
    {
      id: 'sql-file-organization',
      prerequisiteConceptIds: ['sql-statement', 'safe-lab-copy'],
      term: 'SQL 文件组织',
      english: 'SQL File Organization',
      definition: 'SQL 文件组织是把 12 条查询按编号、注释和执行顺序写进 business-query-set.sql，确保别人能复跑。',
      why: '复盘后的 SQL 如果散在聊天里，很难复查和复用。',
      problemSolved: '回答“查询如何被保存和重新执行”。',
      input: 'BQ01-BQ12 的 SQL 文本。',
      output: '按编号排列的 business-query-set.sql。',
      systemPosition: '属于 W3D6 成果文件之一。',
      process: ['每条查询前写 query_id 注释。', '只使用 FROM orders。', '保存顺序和日志顺序一致。'],
      owner: '产品经理维护查询文件；SQLite 执行文件内容。',
      notResponsibleFor: '不负责连接生产数据库或写自动化报表。',
      compareWith: 'business-query-log.md 解释结果；business-query-set.sql 保存可执行查询。',
      evidence: ['business-query-set.sql。', 'query_id 注释。', 'sql_text。'],
      failureModes: ['SQL 无编号。', '日志编号和 SQL 文件编号对不上。'],
      pmUse: '把 BQ01-BQ12 依次写入文件，后续复盘只需要按编号定位。',
      correctExample: '-- BQ04 recent paid orders followed by SELECT ... ORDER BY paid_at DESC LIMIT 5;',
      incorrectExample: '把 SQL 截图贴在聊天里。',
    },
    {
      id: 'answer-log-boundary',
      prerequisiteConceptIds: ['result-boundary', 'quality-evidence-boundary'],
      term: '答案日志边界',
      english: 'Answer Log Boundary',
      definition: '答案日志边界要求每条查询都写 can_prove 和 cannot_prove，明确本地教学证据最多支持什么。',
      why: 'SQL 输出很容易被误读成业务真相；日志必须主动防止过度解释。',
      problemSolved: '回答“这条查询结果能被怎样引用”。',
      input: '业务问题、SQL、观察结果和质量标注。',
      output: 'can_prove、cannot_prove。',
      systemPosition: '位于每条查询记录的结论部分。',
      process: ['先写能证明的行级事实。', '再写不能证明的生产、质量、指标和后续主题。', '留下复核问题。'],
      owner: '产品经理负责边界；审核人判断是否可引用。',
      notResponsibleFor: '不负责把一次练习批准为真实业务结论。',
      compareWith: 'can_prove 是有限证据；cannot_prove 是防止误用。',
      evidence: ['can_prove。', 'cannot_prove。', 'next_review_question。'],
      failureModes: ['只写“查询通过”。', '没有说明不能证明什么。'],
      pmUse: '把“能证明本地样本中 app paid 明细可筛出”与“不能证明真实转化率或收入”分开写。',
      correctExample: 'cannot_prove: 不能证明真实生产、指标、GROUP BY、JOIN 或下一课已经完成。',
      incorrectExample: 'can_prove: 指标已经正确。',
    },
    {
      id: 'stakeholder-handoff-note',
      prerequisiteConceptIds: ['review-question-boundary', 'exclusion-rule-contract'],
      term: '交接说明',
      english: 'Stakeholder Handoff Note',
      definition: '交接说明是写给后续自己、导师或数据同事的一句话，说明这条查询结果应如何使用、哪些风险要确认。',
      why: '产品经理的查询不是给数据库看的，而是给后续协作和复盘看的。',
      problemSolved: '回答“看到这条结果的人下一步该注意什么”。',
      input: 'observed_result、quality_flags 和 cannot_prove。',
      output: 'handoff_note。',
      systemPosition: '位于每条日志记录末尾，连接后续复核。',
      process: ['指出可用场景。', '指出质量风险。', '指出不能引用成什么。'],
      owner: '产品经理写交接；接收人决定下一步复核。',
      notResponsibleFor: '不负责替接收人做最终批准。',
      compareWith: 'review_questions 问什么；handoff_note 告诉别人怎么读这条结果。',
      evidence: ['handoff_note。', 'next_review_question。'],
      failureModes: ['只贴结果不解释。', '没有提醒 TEST1/O1018/NULL。'],
      pmUse: '给运营同事说明“这只是本地教学明细样本，风险行已标注，不能直接做活动复盘结论”。',
      correctExample: 'handoff_note: 可用于检查筛选逻辑；请在引用前确认测试和重复处理。',
      incorrectExample: 'handoff_note: 可以直接发周报。',
    },
    {
      id: 'weekly-sql-review',
      prerequisiteConceptIds: ['business-query-set', 'review-question-boundary'],
      term: '周 SQL 复盘',
      english: 'Weekly SQL Review',
      definition: '周 SQL 复盘是把 W3 的环境、基础查询、质量风险、取数需求和业务查询集连成一条学习证据链。',
      why: '综合日不是再学新语法，而是检验前五天是否能迁移到一个完整业务问题。',
      problemSolved: '回答“W3 学完后，我能独立做到哪一步，下一周该问什么”。',
      input: 'W3D1-W3D5 成果和 W3D6 查询集。',
      output: 'next_review_question 与进入 W4D1 的边界。',
      systemPosition: 'W3 收束，连接 W4 指标口径。',
      process: ['列出已完成证据。', '列出不能证明的指标问题。', '把下一步问题指向 W4D1。'],
      owner: '学习者做复盘；后续课程继续定义指标。',
      notResponsibleFor: '不负责启动 W4D1、计算指标或做 JOIN。',
      compareWith: '单题记录关注一条查询；周复盘关注整周能力链。',
      evidence: ['business-query-log.md。', 'next_review_question。', 'memory review stages。'],
      failureModes: ['把 W3D6 当成 W4D1 已完成。', '没有说明指标定义还没开始。'],
      pmUse: '写“下一步 W4D1 要定义 paid 明细如何变成指标：分子、分母、去重、时间窗口、排除规则”。',
      correctExample: 'next_review_question: W4D1 需要先定义指标口径，再决定是否计算。',
      incorrectExample: 'next_review_question: 指标已经正确，可以上线。',
    },
  ],
  diagram: {
    title: '12 道业务查询集的证据链',
    caption: '同一个取数需求先复用口径，再生成行级答案，随后贴质量标注和交接边界。',
    nodes: [
      { id: 'request', label: 'W3D5 取数口径', description: 'request_ref 固定同一个业务目的、筛选、时间和排除规则。', input: 'data-request.md', output: 'request_ref', owner: '产品经理', evidence: 'R6-qualified-data-request' },
      { id: 'sql', label: 'business-query-set.sql', description: '按 BQ01-BQ12 保存单表 SELECT。', input: 'orders 表字段', output: '12 条可复跑 SQL', owner: '产品经理学习者', evidence: 'query_id + sql_text' },
      { id: 'rows', label: '行级观察', description: '记录 expected_rows 与 observed_result。', input: 'SQL 输出', output: '订单行或取值', owner: 'SQLite 教学模拟', evidence: 'O1001/O1018/TEST1/NULL/0 元' },
      { id: 'flags', label: '质量标注', description: '把 W3D4 风险贴回每条答案。', input: 'observed_result', output: 'quality_flags', owner: '产品经理', evidence: 'TEST1、O1018、NULL、0 元、日期边界' },
      { id: 'handoff', label: '交接边界', description: '写 can_prove、cannot_prove、handoff_note 和 next_review_question。', input: '结果与风险标注', output: 'business-query-log.md', owner: '产品经理学习者', evidence: '不能证明 + W4D1 问题' },
    ],
    branches: [
      { from: 'request', to: 'sql', label: '复用口径', kind: 'normal' },
      { from: 'sql', to: 'rows', label: '运行查询', kind: 'normal' },
      { from: 'rows', to: 'flags', label: '标注风险', kind: 'normal' },
      { from: 'flags', to: 'handoff', label: '交接复核', kind: 'normal' },
      { from: 'rows', to: 'handoff', label: '把明细误写成指标', kind: 'failure' },
    ],
    evidenceNotes: [
      '所有查询都来自本地教学模拟的 orders 表和 W3 已学单表 SQL。',
      '能证明 12 条查询的行级结果、质量标注和交接边界可复核；不能证明生产数据、聚合、GROUP BY、JOIN 或指标正确。',
      'W4D1 只是下一课入口，不在 W3D6 中提前完成。',
    ],
  },
  demonstration: {
    title: '教师示范：把一个复盘问题写成 BQ12 查询记录',
    businessProblem: '运营想看 2026-08-31 app 渠道 paid 订单中，排除 TEST1 后哪些明细可以先拿去人工复核。',
    finalConclusion: 'BQ12 实际看到 O1017、O1011、O1007、O1004、O1001；其中 O1017 的 paid_amount 为 NULL，必须在 quality_flags 中标注。可以说这条查询能筛出本地教学表中符合 app、paid、日期窗口且非测试的明细样本。',
    conclusionLimit: '不能证明真实生产订单、收入、用户数、渠道表现、数据质量已修复、指标正确、GROUP BY、JOIN 或下一课已经完成。',
    steps: [
      { title: '固定口径来源', action: '写 request_ref=R6-qualified-data-request，并说明复用 W3D5 的 app paid 明细口径。', reason: '复盘查询要能追溯到同一个取数需求。', evidence: 'request_ref。', proves: '能证明这条查询不是临时猜条件。', limitation: '不证明真实口径已批准。' },
      { title: '写完整 SQL', action: 'SELECT order_id, user_id, channel, paid_amount, paid_at AS paid_time FROM orders WHERE status = "paid" AND channel = "app" AND is_test = 0 AND paid_at >= "2026-08-31" AND paid_at < "2026-09-01" ORDER BY paid_at DESC LIMIT 5;。', reason: '只用 W3 已学单表查询动作，形成可复跑明细。', evidence: 'sql_text。', proves: '能证明筛选、时间、别名、排序和样本窗口都写清。', limitation: '不计算指标。' },
      { title: '写清预期留下的行', action: 'expected_rows 写“非测试 app paid 且 paid_at 在 2026-08-31 的订单，倒序展示 5 行”。', reason: '先写预期，才能对照实际是否偏离。', evidence: 'expected_rows 字段已写清。', proves: '能证明查询目标明确。', limitation: '不证明结果已观察。' },
      { title: '记录实际结果', action: 'observed_result 写 O1017、O1011、O1007、O1004、O1001。', reason: '行级结果必须具体到样本行。', evidence: 'observed_result。', proves: '能证明本地教学查询有可见输出。', limitation: '不代表生产全量。' },
      { title: '补齐结果质量标注', action: 'quality_flags 写“TEST1 已被 is_test=0 排除；O1017 paid_amount 为 NULL；仍需确认 NULL 金额处理”。', reason: 'W3D4 风险必须贴回结果。', evidence: 'quality_flags 字段已写清。', proves: '能证明风险没有被静默忽略。', limitation: '不证明风险已修复。' },
      { title: '收束交接问题', action: '写 can_prove、cannot_prove、handoff_note 和 next_review_question。', reason: '最终答案要说明能被怎样引用，以及 W4D1 还要定义什么指标口径。', evidence: 'business-query-log.md。', proves: '能证明查询记录可交接。', limitation: '不提前完成 W4D1。' },
    ],
  },
  guidedLab: {
    title: '12 道业务查询练习台',
    goal: '用 BQ01-BQ12 把 W3 周能力串起来：每条都有业务问题、SQL、预期行、实际观察、质量标注、能证明、不能证明、交接说明和下一步复核问题。',
    safety: '教学模拟 · 只读取本地 SQLite 教学表 orders 和 W3 已完成记录；不连接真实数据库、不读取公司数据、不打开生产系统、不提前教学 W4D1 指标。',
    conceptIds: [...conceptIds],
    predictionPrompt: '预测：12 道业务查询里，最容易越界的是把 DISTINCT 当指标、把 LIMIT 当全量、忽略 TEST1/O1018/NULL，还是把 W4D1 指标说成已经完成？',
    steps: [
      { title: 'BQ01 paid 明细', action: '写 bq01-paid-app-orders，筛出 status="paid" AND channel="app" 的样本。', observe: '实际会看到 O1001、O1004、O1007、O1009、O1011。', explanation: '复用 W3D3 的文本筛选。', proves: '能证明 app paid 条件可复跑。', cannotProve: '不能证明真实 app paid 总量或收入。' },
      { title: 'BQ02 当天 paid', action: '写 bq02-20260831-paid-orders，用 paid_at >= "2026-08-31" AND paid_at < "2026-09-01"。', observe: '实际会看到 O1001、O1002、O1004、O1006、O1007。', explanation: '复用 W3D3 日期边界。', proves: '能证明当天窗口可复跑。', cannotProve: '不能证明时区和延迟。' },
      { title: 'BQ03 边界之后', action: '写 bq03-boundary-after-midnight，查看 paid_at >= "2026-09-01" 的 paid 行。', observe: '实际看到 O1014、O1019。', explanation: '把 W3D4 日期边界风险变成观察。', proves: '能证明跨天边界行存在于教学样本。', cannotProve: '不能决定这些行是否属于 8 月 31 日业务日。' },
      { title: 'BQ04 最近 paid', action: '写 bq04-recent-paid-orders，用 ORDER BY paid_at DESC LIMIT 5。', observe: '实际看到 O1019、O1014、O1018、O1018、O1013。', explanation: '复用排序和 LIMIT 边界。', proves: '能证明展示顺序可解释。', cannotProve: '不能证明趋势或总量。' },
      { title: 'BQ05 app 非 paid', action: '写 bq05-app-nonpaid-orders，查看 channel="app" AND status!="paid"。', observe: '实际看到 O1003。', explanation: '用反向条件检查范围边界。', proves: '能证明 app 中有非 paid 样本。', cannotProve: '不能判断取消原因。' },
      { title: 'BQ06 channel 取值', action: '写 bq06-distinct-channel-values，SELECT DISTINCT channel。', observe: '实际看到 app、miniapp、web。', explanation: 'DISTINCT 只做取值观察。', proves: '能证明本地样本出现过的渠道值。', cannotProve: '不能证明渠道订单数或用户数。' },
    ],
    recordPrompts: [
      '记录 BQ01/BQ02：写 request_ref、base_table、sql_text、expected_rows、observed_result、quality_flags。',
      '记录 BQ03/BQ04：重点写日期边界、ORDER BY、LIMIT 和 cannot_prove。',
      '记录 BQ05/BQ06：说明反向条件和 DISTINCT 取值不能变成指标。',
      '记录 BQ07/BQ08：标注 TEST1 和 O1018 风险，不要静默忽略。',
      '记录 BQ09/BQ10：处理 0 元、NULL amount 和 paid_time 别名。',
      '记录 BQ11/BQ12：补 handoff_note 与 next_review_question，BQ12 使用 bq12-review-ready-app-paid，下一步只问 W4D1 指标口径。',
    ],
    comparePrompt: '对照 business-query-set.sql 与 business-query-log.md：12 条编号、SQL、观察、质量标注和边界是否一一对应？',
    passCriteria: ['BQ01-BQ12 十二道查询都运行并记录。', '每条都有 query_id、business_question、request_ref、base_table、sql_text、expected_rows、observed_result、quality_flags、can_prove、cannot_prove、handoff_note、next_review_question。', '只使用 orders 单表基础查询。', '不得把本地教学模拟写成真实生产、聚合、GROUP BY、JOIN、指标或下一课已经完成。'],
  },
  independentLab: {
    title: '独立变式：把一条复盘问题补成可交接查询记录',
    scenario: '导师给你一句“看看 app paid 订单有没有异常”，你要从 BQ01-BQ12 中任选一条，补全 SQL、观察结果、质量标注和交接问题。',
    conceptIds: [...conceptIds],
    changedConditions: ['只有 SQL，没有 business_question。', '没有 request_ref，无法追溯 W3D5 取数需求。', 'observed_result 写“正常”，没有具体订单行。', 'quality_flags 漏掉 TEST1、O1018、NULL 或 0 元。', 'handoff_note 直接写成业务结论。'],
    task: '任选一个缺口，把它修成完整 business-query-log.md 记录，必须包含 12 个成果字段。',
    predictionPrompt: '先预测这个缺口会让复盘读者误用哪类结果。',
    evidenceRequirements: ['必须引用至少一条 BQ 编号和一条具体订单行。', '必须写明不能证明真实生产、聚合、GROUP BY、JOIN、指标或下一课已经完成。'],
    passCriteria: ['12 个字段齐全。', 'SQL 只查询 orders 单表。', 'quality_flags 至少标注一种 W3D4 风险。', 'next_review_question 指向 W4D1 的指标口径问题。'],
    remediation: { label: '回看 12 道业务查询练习台', sectionId: 'diagram', anchor: 'demonstration-conclusion' },
  },
  exercises: [
    exercise('w3d6-query-set-purpose', ['概念与边界', '工作场景'], ['business-query-set', 'query-contract-reuse'], 'W3D6 为什么要做 12 道业务查询集，而不是只交一条 SQL？', ['真实复盘需要多个行级问题共用同一口径并留下边界', '为了提前完成 GROUP BY 指标', '为了练习 JOIN 对账'], 0, 'W3D6 的目标是组织单表查询证据链，不是进入后续聚合或 JOIN。'),
    exercise('w3d6-quality-flags', ['证据判断', '综合变式'], ['quality-flagged-answer', 'answer-log-boundary'], 'BQ12 看到 O1017 paid_amount 为 NULL，最稳妥的记录是什么？', ['quality_flags 标注 NULL 金额，并在 cannot_prove 里说明不能证明收入', '直接把 NULL 当 0 计算收入', '删除这一行并说数据已修复'], 0, 'W3D6 只标注风险和交接问题，不修数据、不算收入。'),
    exercise('w3d6-file-organization', ['机制推演', '工作场景'], ['sql-file-organization', 'stakeholder-handoff-note'], 'business-query-set.sql 和 business-query-log.md 的关系是什么？', ['前者保存可执行 SQL，后者保存观察、质量标注和交接边界', '两个文件内容完全一样', 'log 只写最终业务结论'], 0, 'SQL 文件负责复跑，日志负责解释和边界。'),
    exercise('w3d6-week-review-boundary', ['概念与边界', '综合变式'], ['weekly-sql-review', 'row-level-answer'], 'W3D6 结束时，next_review_question 最应该指向什么？', ['W4D1 先定义指标的分子、分母、去重、时间窗口和排除规则', '指标已经正确，可以上线', 'JOIN 已经完成，可以对账'], 0, 'W3D6 只完成 W3 周查询集，下一步才进入指标定义。'),
  ],
  deliverable: {
    title: '12 道业务查询集',
    conceptIds: [...conceptIds],
    purpose: '让学习者用 business-query-set.sql 保存 BQ01-BQ12 的单表 SQL，用 business-query-log.md 逐条记录业务问题、口径来源、预期、观察、质量标注、能证明、不能证明和交接问题。',
    whenToUse: '在 W3 周结束时，把本地 SQL 学习迁移成一次可复查的产品复盘查询包，并准备进入 W4D1 指标口径定义。',
    audience: '未来继续学习 W4D1 的自己、导师、数据同事或需要复核查询证据的产品伙伴。',
    fields: [
      { name: 'query_id', meaning: 'BQ01-BQ12 查询编号。', source: 'business-query-set.sql 注释' },
      { name: 'business_question', meaning: '这条查询要回答的行级业务问题。', source: '复盘问题拆解' },
      { name: 'request_ref', meaning: '沿用的 W3D5 取数需求编号。', source: 'data-request.md' },
      { name: 'base_table', meaning: '本日只允许 orders。', source: 'W3D1 setup.sql' },
      { name: 'sql_text', meaning: '完整可执行单表 SQL。', source: 'business-query-set.sql' },
      { name: 'expected_rows', meaning: '运行前预期会留下哪些行或取值。', source: '查询问题和口径' },
      { name: 'observed_result', meaning: '本地教学模拟实际看到的订单行或取值。', source: 'sqlite3 输出' },
      { name: 'quality_flags', meaning: 'TEST1、O1018、NULL、0 元、日期边界等风险标注。', source: 'W3D4 检查表' },
      { name: 'can_prove', meaning: '当前查询能证明的有限行级事实。', source: 'SQL 与观察结果' },
      { name: 'cannot_prove', meaning: '不能证明的生产、质量修复、指标、GROUP BY、JOIN 或 W4D1 完成状态。', source: '证据边界自检' },
      { name: 'handoff_note', meaning: '给后续自己或数据同事的阅读提示。', source: '交接说明' },
      { name: 'next_review_question', meaning: '下一步要在 W4D1 或复核中确认的问题。', source: 'W3 周复盘' },
    ],
    badExample: 'query_id: BQ12\nbusiness_question: 看 app 订单\nsql_text: SELECT * FROM orders LIMIT 5;\nobserved_result: 有 5 行，说明 app 表现不错，把明细样本误写成指标结论和下一课完成。',
    badReasons: ['业务问题和 request_ref 不清楚。', 'SQL 没有复用 app paid 日期口径。', '没有 expected_rows、quality_flags、handoff_note 和 next_review_question。', '把明细样本越界说成指标和 W4D1 完成。'],
    revisionSteps: ['先把 BQ01-BQ12 写成带编号的查询清单。', '每条只使用 orders 单表和已学 SQL。', '写 expected_rows 后再记录 observed_result。', '把 TEST1、O1018、NULL、0 元和日期边界写入 quality_flags。', '用 can_prove/cannot_prove/handoff_note/next_review_question 收束边界。'],
    goodExample: 'query_id: BQ12-review-ready-app-paid\nbusiness_question: 查看 2026-08-31 app 渠道 paid 且非测试的订单明细，供人工复核\nrequest_ref: R6-qualified-data-request\nbase_table: orders\nsql_text: SELECT order_id,user_id,channel,paid_amount,paid_at AS paid_time FROM orders WHERE status = "paid" AND channel = "app" AND is_test = 0 AND paid_at >= "2026-08-31" AND paid_at < "2026-09-01" ORDER BY paid_at DESC LIMIT 5;\nexpected_rows: 非测试 app paid 且 paid_at 在 2026-08-31 的订单，倒序展示 5 行\nobserved_result: 教学模拟看到 O1017、O1011、O1007、O1004、O1001\nquality_flags: TEST1 已排除；O1017 paid_amount 为 NULL；仍需确认 NULL 金额处理\ncan_prove: 能证明本地 orders 表中这条单表查询可筛出符合口径的明细样本\ncannot_prove: 不能证明真实生产、收入、用户数、指标正确、GROUP BY、JOIN、数据质量已修复或下一课已经完成\nhandoff_note: 可交给导师复核筛选逻辑；引用前必须确认 NULL 金额与测试订单规则\nnext_review_question: W4D1 需要先定义 app paid 指标的分子、分母、去重、时间窗口和排除规则\n',
    guidedPrompts: ['写出 BQ01-BQ12 的 query_id。', '为每条写 business_question。', '写 request_ref=R6-qualified-data-request。', '写 base_table=orders。', '粘贴 sql_text。', '写 expected_rows 与 observed_result。', '写 quality_flags。', '写 can_prove、cannot_prove、handoff_note、next_review_question。'],
    blankTemplate: 'query_id:\nbusiness_question:\nrequest_ref:\nbase_table:\nsql_text:\nexpected_rows:\nobserved_result:\nquality_flags:\ncan_prove:\ncannot_prove:\nhandoff_note:\nnext_review_question:\n',
    standardTemplate: '每完成一题，就复制一段记录；不要先写总报告。\n\nquery_id: BQ01-paid-app-orders\nbusiness_question: 查看本地 orders 表中 app 渠道 paid 订单样本\nrequest_ref: R6-qualified-data-request\nbase_table: orders\nsql_text: SELECT order_id,user_id,status,channel,paid_at FROM orders WHERE status = "paid" AND channel = "app" LIMIT 5;\nexpected_rows: status 为 paid 且 channel 为 app 的订单行\nobserved_result: 教学模拟看到 O1001、O1004、O1007、O1009、O1011\nquality_flags: O1009/TEST1 为测试数据，需要按 W3D5 口径确认是否排除\ncan_prove: 能证明 app paid 文本筛选在本地 orders 表可复跑\ncannot_prove: 不能证明真实生产、收入、用户数、指标正确、GROUP BY、JOIN、数据质量已修复或下一课已经完成\nhandoff_note: 可用于检查筛选逻辑；引用前确认测试数据处理\nnext_review_question: W4D1 如何定义 app paid 指标的分子、分母和排除规则\n\n下一题生成提示：BQ02 写 2026-08-31 paid 边界；BQ03 写 2026-09-01 边界行；BQ04 写 ORDER BY paid_at DESC；BQ05 写 app 非 paid；BQ06 写 DISTINCT channel；BQ07-BQ12 逐条补 TEST1、O1018、0 元、paid_time、NULL user_id 和 review-ready app paid。\n',
    checklist: ['business-query-set.sql 包含 BQ01-BQ12，且都只 FROM orders。', 'business-query-log.md 每条都有 12 个字段。', 'request_ref 能追溯到 W3D5。', 'expected_rows 先于 observed_result。', 'quality_flags 覆盖 TEST1、O1018、NULL、0 元和日期边界。', 'cannot_prove 排除真实生产、指标、GROUP BY、JOIN 和 W4D1 已完成。', 'next_review_question 指向 W4D1 指标口径定义。'],
  },
  memory: {
    conceptIds: [...conceptIds],
    anchors: ['查询集先统一 request_ref，再逐条写 SQL。', 'W3D6 只能回答行级事实，不计算指标。', 'quality_flags 必须贴回 TEST1、O1018、NULL、0 元和日期边界。', 'handoff_note 告诉别人怎么读，next_review_question 指向 W4D1。'],
    closedBookPrompt: '闭卷解释：怎样把 W3D5 的取数需求变成 12 道业务查询集？请按 query_id、request_ref、sql_text、expected_rows、observed_result、quality_flags、can_prove/cannot_prove、handoff_note 复述。',
    microOperation: '不看正文，写出 BQ12 的 SQL、quality_flags、cannot_prove 和 next_review_question。',
    unresolvedPrompt: '写出你进入 W4D1 前最容易混淆的一处：行级答案、质量标注、交接说明还是指标口径？准备怎么复核？',
    reviewStages: [
      { stage: 'D1', task: '闭卷写出 business-query-log.md 的 12 个字段，并说明 request_ref 的作用。' },
      { stage: 'D3', task: '复原 BQ04 最近 paid 订单查询，并说明 ORDER BY 和 LIMIT 的边界。' },
      { stage: 'D7', task: '给 BQ07/BQ08 写 quality_flags：TEST1 和 O1018 分别怎样标注。' },
      { stage: 'D14', task: '解释 DISTINCT channel 能证明什么，不能证明什么。' },
      { stage: 'D30', task: '把 BQ12 的 observed_result 改写成 handoff_note 和 next_review_question。' },
      { stage: 'D60', task: '不看模板，按 BQ01-BQ12 复述完整业务查询集和进入 W4D1 的边界。' },
    ],
  },
  nextLesson: { id: 'W4D1', title: '指标不是一个数字', bridge: '下一课才开始定义指标分子、分母、去重、时间窗口和排除规则；W3D6 只完成单表业务查询集和交接边界，不创建或完成 W4D1。' },
}
