import type { DailyCourse, Exercise } from './types'

const conceptIds = [
  'metric-decision-purpose',
  'metric-signal',
  'metric-numerator',
  'metric-denominator',
  'metric-grain',
  'metric-time-window',
  'metric-exclusion-rule',
  'metric-contract-table',
] as const

const prerequisiteConceptIds = [
  'terminal-shell',
  'working-directory',
  'file-path',
  'safe-lab-copy',
  'sqlite-database-file',
  'sqlite3-session',
  'setup-sql-script',
  'table-row-column-preview',
  'sql-statement',
  'select-clause',
  'from-clause',
  'where-gate',
  'order-by-stage',
  'limit-stage',
  'execution-order',
  'result-boundary',
  'query-question',
  'where-condition',
  'comparison-operator',
  'text-value-filter',
  'date-range-boundary',
  'order-direction',
  'column-alias',
  'distinct-result',
  'quality-question',
  'null-value',
  'duplicate-row',
  'status-coverage',
  'test-data-flag',
  'time-boundary-risk',
  'amount-anomaly',
  'quality-evidence-boundary',
  'data-request-purpose',
  'business-question-scope',
  'field-source-assumption',
  'filter-rule-contract',
  'time-window-contract',
  'exclusion-rule-contract',
  'expected-output-shape',
  'review-question-boundary',
  'business-query-set',
  'query-contract-reuse',
  'row-level-answer',
  'quality-flagged-answer',
  'sql-file-organization',
  'answer-log-boundary',
  'stakeholder-handoff-note',
  'weekly-sql-review',
] as const

function exercise(
  id: string,
  categories: Exercise['categories'],
  ids: string[],
  prompt: string,
  options: string[],
  answerIndex: number,
  referenceAnswer: string,
): Exercise {
  return {
    id,
    kind: 'single-choice',
    categories,
    conceptIds: ids,
    prompt,
    hint: '先问这个指标服务什么决策，再检查信号、分子、分母、粒度、时间窗口、排除规则和不能证明事项是否齐全。',
    options: options.map((label, index) => ({
      label,
      rationale: index === answerIndex ? '这项先定义指标契约，尚未进入聚合 SQL 或业务结论。' : '这项要么只给数字名称，要么提前计算、聚合或宣称真实生产结论。',
      couldBeTrueWhen: index === answerIndex ? '当学习者正在编写 W4D1 指标口径表。' : '只有后续 W4D2-W4D6 补齐聚合、分组、复现和复核后，才可能支撑更强判断。',
    })),
    answerIndex,
    referenceAnswer,
    reasoning: [
      'W4D1 是指标周的第一课，任务是把行级查询交接问题转成可审核指标口径。',
      '一个指标必须先说明服务的决策、反映的信号、分子、分母、去重粒度、时间窗口和排除规则。',
      '本日不写 COUNT/SUM/GROUP BY/HAVING，不计算真实指标，也不把 W3 教学表样本写成生产结论。',
    ],
    rubric: ['决策目的清楚', '分子分母可解释', '时间和排除规则明确', '证据边界不过界'],
    commonErrors: [
      { error: '只写“支付转化率”四个字', reason: '名称不能说明分子、分母、时间窗口、排除规则和使用场景。' },
      { error: '直接写 SQL 算出一个数字', reason: 'W4D1 先定义口径，W4D2 才开始聚合计算。' },
    ],
    remediation: { label: '回看指标口径表字段', sectionId: 'deliverable', anchor: 'w4d1-metric-contract-fields' },
  }
}

export const w4d1: DailyCourse = {
  id: 'W4D1',
  contentVersion: 'w4d1-metric-contract-day01-v1',
  week: 4,
  day: 1,
  title: '指标不是一个数字',
  subtitle: '把 W3D6 的行级查询交接问题，改写成可审核的指标口径表；本日只定义决策、信号、分子、分母、粒度、时间窗口和排除规则，不提前教学聚合 SQL。',
  duration: { core: 30, standard: 45, extension: 70, full: 118 },
  coreConceptGroups: [
    {
      id: 'metric-before-calculation',
      title: '先定义指标，再计算指标',
      conceptIds: ['metric-decision-purpose', 'metric-signal', 'metric-contract-table'],
      summary: '指标不是孤立数字，而是为某个决策服务的信号定义；先写清口径表，后续 SQL 才知道算什么。',
      boundary: '能形成指标契约；不能计算聚合结果、趋势或真实生产结论。',
    },
    {
      id: 'metric-shape',
      title: '分子、分母和粒度决定数字含义',
      conceptIds: ['metric-numerator', 'metric-denominator', 'metric-grain'],
      summary: '同一个“支付率”会因为分子、分母和去重粒度不同变成完全不同的指标。',
      boundary: '能说明行如何进入分子或分母；不能用 COUNT/DISTINCT/SUM 真正计算。',
    },
    {
      id: 'metric-boundary',
      title: '时间窗口和排除规则决定能否复核',
      conceptIds: ['metric-time-window', 'metric-exclusion-rule'],
      summary: '业务日边界、测试数据、重复行、NULL 和退款状态都必须在计算前写进指标口径。',
      boundary: '能定义排除与保留规则；不能证明真实数据已清洗或指标正确。',
    },
  ],
  prerequisiteConceptIds: [...prerequisiteConceptIds],
  learningPaths: {
    '30': {
      guidedStepIndices: [0, 1, 2, 3, 4, 5],
      guidedRecordIndices: [0, 1, 2, 3, 4, 5],
      exerciseCount: 3,
      deliverablePromptCount: 6,
      deliverableChecklistIndices: [0, 1, 2, 3, 4],
      deliverableMinimumContributionCharacters: 240,
    },
    '45': {
      guidedStepIndices: [0, 1, 2, 3, 4, 5],
      guidedRecordIndices: [0, 1, 2, 3, 4, 5],
      exerciseCount: 4,
      deliverablePromptCount: 8,
      deliverableChecklistIndices: [0, 1, 2, 3, 4, 5, 6],
      deliverableMinimumContributionCharacters: 360,
    },
  },
  primaryGoal: '提交 `metric-contract-table.md`：至少为 app paid 订单数和支付转化率各写一条 metric_id、decision_purpose、signal、numerator、denominator、grain、time_window、exclusion_rules、quality_risks、can_prove、cannot_prove、next_sql_task。',
  scenario: {
    role: '你是刚完成 W3 SQL 复盘查询集的产品经理。',
    situation: '运营同学问“8 月 31 日 app 支付转化怎么样”。你手里只有 W3D6 的订单明细查询和质量标注，不能直接把几行样本说成指标。你需要先写指标口径表，让后续聚合 SQL 有明确分子、分母、去重、时间和排除规则。',
    question: '怎样在计算之前，把“支付转化”定义成别人能复核、能质疑、能后续计算的指标口径？',
    stakes: '如果没有口径表，后续 SQL 可能把测试订单、重复订单、NULL 金额、跨天边界或不同分母混在一起，最后得到一个看似精确但不可解释的数字。',
  },
  objectives: [
    { id: 'w4d1-objective-purpose', text: '能说明一个指标服务的具体产品决策', evidence: 'metric-contract-table.md 中 decision_purpose 不写“看看数据”，而写清要支持的复盘或取舍。' },
    { id: 'w4d1-objective-formula', text: '能把指标拆成分子、分母和去重粒度', evidence: 'numerator、denominator、grain 三项能对应到 W3D6 的行级证据。' },
    { id: 'w4d1-objective-boundary', text: '能写出时间窗口、排除规则和质量风险', evidence: 'time_window、exclusion_rules、quality_risks 覆盖 TEST1、O1018、NULL 和跨天边界。' },
    { id: 'w4d1-objective-no-calc', text: '能说明 W4D1 只定义口径，不提前计算指标', evidence: 'cannot_prove 与 next_sql_task 指向 W4D2 聚合计算，而不是本日给出指标数字。' },
  ],
  prerequisites: [
    {
      id: 'w4d1-w3d6-readiness',
      conceptIds: [...prerequisiteConceptIds],
      prompt: '你是否能复述 W3D6 的 12 道业务查询集，以及其中 TEST1、O1018、NULL、0 元和跨天边界为什么不能直接变成指标？',
      passDescription: '能说明 W3D6 只给行级查询证据和 next_review_question，下一步才定义指标口径。',
      remediationLabel: '回到 W3D6 补业务查询集和交接边界',
      remediationTarget: '#/lesson/W3D6',
      remediation: {
        purpose: 'W4D1 可提前阅读；但没有 W3D6 的行级证据，指标口径会变成凭空命名，后续无法复核。',
        steps: ['补齐 W3D6 business-query-log.md 中 BQ01、BQ02、BQ07、BQ08、BQ11、BQ12。', '找出 TEST1、O1018、NULL、0 元和 O1014 跨天边界。', '把 W3D6 的 next_review_question 改写成“要先定义哪些指标口径”。'],
        successCheck: '能说出 W4D1 不计算 COUNT/SUM，而是先写分子、分母、粒度、时间窗口和排除规则。',
      },
    },
  ],
  concepts: [
    {
      id: 'metric-decision-purpose',
      prerequisiteConceptIds: ['stakeholder-handoff-note'],
      term: '指标决策目的',
      english: 'Metric Decision Purpose',
      definition: '指标决策目的是这个指标要帮助谁做什么判断或取舍，而不是“看起来重要”的数字名称。',
      why: '没有决策目的，团队会为了数字而数字，后续分子、分母和排除规则都没有取舍依据。',
      problemSolved: '回答“为什么要定义这个指标”。',
      input: '业务问题、复盘场景、使用者和待决策动作。',
      output: 'decision_purpose。',
      systemPosition: '位于指标口径表第一步，先于分子分母和 SQL。',
      process: ['写清指标使用者是谁。', '写清要判断的具体问题。', '写这个指标会影响的下一步动作。'],
      owner: '产品经理负责定义决策目的；数据同事可挑战是否可计算。',
      notResponsibleFor: '不负责证明真实业务已经改善。',
      compareWith: '业务问题问想知道什么；决策目的说明知道以后要做什么。',
      evidence: ['decision_purpose。', 'stakeholder。', 'next_action。'],
      failureModes: ['写“观察转化率”但没有决策。', '把指标目的写成指标名称。'],
      pmUse: '写“判断 app 渠道当天支付链路是否需要排查或复盘”，而不是写“看支付率”。',
      correctExample: 'decision_purpose: 判断 2026-08-31 app 渠道支付链路是否需要进一步排查。',
      incorrectExample: 'decision_purpose: 看一个转化数字。',
    },
    {
      id: 'metric-signal',
      prerequisiteConceptIds: ['row-level-answer'],
      term: '指标信号',
      english: 'Metric Signal',
      definition: '指标信号是指标变化被解释为什么业务现象，例如支付意愿、支付链路健康度或样本质量风险。',
      why: '同一个数字下降可能来自用户行为、技术故障、口径变化或质量问题；先写信号能避免误判。',
      problemSolved: '回答“这个指标变化代表什么，不代表什么”。',
      input: '决策目的、业务假设和行级证据。',
      output: 'signal 与 signal_limit。',
      systemPosition: '连接决策目的和指标公式。',
      process: ['写希望观察的业务现象。', '写可疑替代解释。', '写不能由本指标单独证明的结论。'],
      owner: '产品经理负责解释信号边界。',
      notResponsibleFor: '不负责归因、证明因果或证明策略已经有效。',
      compareWith: '指标值是数字；指标信号是数字背后的有限解释。',
      evidence: ['signal。', 'cannot_prove。', 'quality_risks。'],
      failureModes: ['支付率低就说产品差。', '忽略 NULL、测试订单和重复行。'],
      pmUse: '把 app paid 订单数定位为“支付样本规模信号”，而不是“收入正确”。',
      correctExample: 'signal: app 渠道当天符合口径的支付订单规模；不能单独证明收入或原因。',
      incorrectExample: 'signal: 证明 app 运营策略成功。',
    },
    {
      id: 'metric-numerator',
      prerequisiteConceptIds: ['query-contract-reuse'],
      term: '分子',
      english: 'Numerator',
      definition: '分子是指标公式中被计入“达成”的对象集合，必须写清哪些行进入、哪些状态算达成。',
      why: '没有分子定义，后续 COUNT/SUM 会把不同状态和质量风险混在一起。',
      problemSolved: '回答“哪些对象算成功”。',
      input: '目标行为、状态字段、质量标注和筛选规则。',
      output: 'numerator 字段和对应的达成集合说明。',
      systemPosition: '位于指标公式上半部分，后续才会映射成聚合 SQL。',
      process: ['列出达成条件。', '贴回字段和值。', '标注排除或待确认风险。'],
      owner: '产品经理定义口径，数据同事后续落 SQL。',
      notResponsibleFor: '不负责在 W4D1 写 COUNT 或 SUM。',
      compareWith: 'WHERE 条件是行级筛选动作；分子是业务口径中“达成集合”的定义。',
      evidence: ['numerator。', 'included_status。', 'source_query_ref。'],
      failureModes: ['把 refunded 和 paid 都算进分子。', '没有说明测试订单是否排除。'],
      pmUse: '写“status=paid 且 channel=app 且非测试订单”。',
      correctExample: 'numerator: 非测试 app 渠道 paid 订单，按 order_id 去重后计入。',
      incorrectExample: 'numerator: app 订单。',
    },
    {
      id: 'metric-denominator',
      prerequisiteConceptIds: ['business-question-scope'],
      term: '分母',
      english: 'Denominator',
      definition: '分母是指标公式中“有机会达成”的对象集合，必须说明谁被纳入比较基准。',
      why: '支付转化率的分母如果一会儿是访问用户、一会儿是下单订单，数字完全不能比较。',
      problemSolved: '回答“成功是相对于谁而言”。',
      input: '业务入口、候选对象、状态范围和数据可得性。',
      output: 'denominator。',
      systemPosition: '与分子共同组成比例指标口径。',
      process: ['定义有机会达成的对象。', '说明状态范围。', '说明暂缺字段或要数据同事确认的问题。'],
      owner: '产品经理提出分母假设；数据同事确认字段是否存在。',
      notResponsibleFor: '不负责创造不存在的数据字段。',
      compareWith: '分子回答达成；分母回答达成机会。',
      evidence: ['denominator。', 'missing_field。', 'review_question。'],
      failureModes: ['只有分子没有分母。', '把订单数和用户数混用。'],
      pmUse: '支付转化率分母先写“app 渠道进入支付尝试的订单或用户，需确认来源表”。',
      correctExample: 'denominator: app 渠道支付尝试订单，需 W4D2 前确认 attempt 表或字段。',
      incorrectExample: 'denominator: 全部用户，先这么算。',
    },
    {
      id: 'metric-grain',
      prerequisiteConceptIds: ['distinct-result', 'duplicate-row'],
      term: '指标粒度与去重',
      english: 'Metric Grain',
      definition: '指标粒度说明指标按订单、用户、会话还是天来计数，并写清重复对象如何处理。',
      why: 'O1018 这样的重复行会让同一订单被多计；用户指标和订单指标也不能混用。',
      problemSolved: '回答“数的是谁，一人/一单/一次会话算几次”。',
      input: 'order_id、user_id、session_id、日期和重复风险。',
      output: 'grain 与 dedupe_rule。',
      systemPosition: '位于分子分母之后、时间窗口之前，决定后续 DISTINCT 或去重策略。',
      process: ['选择订单、用户或会话等业务对象。', '写清对应唯一键和去重字段。', '写重复对象出现时的保留或复核规则。'],
      owner: '产品经理定义业务粒度；数据同事确认技术唯一键。',
      notResponsibleFor: '不负责在本日执行 DISTINCT 计算。',
      compareWith: 'DISTINCT 是 SQL 动作；粒度与去重是指标口径。W4D1 只定义后者。',
      evidence: ['grain。', 'dedupe_rule。', 'quality_risks。'],
      failureModes: ['订单指标里按 user_id 去重。', '看到 O1018 重复却不写规则。'],
      pmUse: '写“订单粒度，order_id 去重；重复行进入质量风险复核”。',
      correctExample: 'grain: order_id；dedupe_rule: 同一 order_id 多行先标记，后续计算前确认保留规则。',
      incorrectExample: 'grain: 看 SQL 怎么方便。',
    },
    {
      id: 'metric-time-window',
      prerequisiteConceptIds: ['time-window-contract', 'time-boundary-risk'],
      term: '指标时间窗口',
      english: 'Metric Time Window',
      definition: '指标时间窗口说明统计从什么时候开始、什么时候结束，以及业务日、时区和边界行如何处理。',
      why: 'O1014 在 2026-09-01 00:00:00，是否归入 8 月 31 日取决于业务日规则，不能靠直觉。',
      problemSolved: '回答“这个指标统计哪段时间”。',
      input: 'paid_at、业务日定义、时区和边界样本。',
      output: 'time_window。',
      systemPosition: '位于指标契约中，后续映射成日期条件。',
      process: ['写闭开边界。', '写时区或业务日假设。', '列出边界行和待确认问题。'],
      owner: '产品经理提出业务时间假设；数据同事确认字段语义。',
      notResponsibleFor: '不负责修正历史入库时间。',
      compareWith: '日期 WHERE 是查询写法；时间窗口是业务口径。',
      evidence: ['time_window。', 'boundary_cases。', 'review_question。'],
      failureModes: ['写“8 月 31 日”但不写起止。', '把 0 点边界行自动归到前一天。'],
      pmUse: '写 paid_at >= 2026-08-31 00:00:00 且 paid_at < 2026-09-01 00:00:00，时区待确认。',
      correctExample: 'time_window: 2026-08-31 00:00:00 <= paid_at < 2026-09-01 00:00:00，业务时区待确认。',
      incorrectExample: 'time_window: 8 月 31 日全天。',
    },
    {
      id: 'metric-exclusion-rule',
      prerequisiteConceptIds: ['quality-flagged-answer', 'test-data-flag', 'null-value', 'amount-anomaly'],
      term: '指标排除规则',
      english: 'Metric Exclusion Rule',
      definition: '指标排除规则说明测试数据、取消/退款、NULL、0 元、重复行和异常金额在计算前如何处理。',
      why: '排除规则不写清，指标会把质量问题伪装成业务变化。',
      problemSolved: '回答“哪些对象不能进入计算，哪些必须标记复核”。',
      input: 'W3D4/W3D6 质量风险和业务规则。',
      output: 'exclusion_rules 与 quality_risks。',
      systemPosition: '指标计算前的最后一道质量边界。',
      process: ['列出明确排除项。', '列出待复核项。', '说明排除会影响什么。'],
      owner: '产品经理记录业务排除规则；数据治理或研发确认处理方案。',
      notResponsibleFor: '不负责真实清洗数据或证明质量问题已经修复。',
      compareWith: '质量标注是观察；排除规则是后续计算采用的口径决定。',
      evidence: ['exclusion_rules。', 'quality_risks。', 'cannot_prove。'],
      failureModes: ['把 TEST1 算进真实指标。', 'NULL 金额直接当 0 且不说明。'],
      pmUse: '写“is_test=1 排除；NULL 金额和重复 order_id 进入复核，不直接证明收入”。',
      correctExample: 'exclusion_rules: 排除 is_test=1；重复 order_id 和 NULL paid_amount 先标记，计算前确认。',
      incorrectExample: 'exclusion_rules: 数据应该没问题。',
    },
    {
      id: 'metric-contract-table',
      prerequisiteConceptIds: ['data-request-purpose'],
      term: '指标口径表',
      english: 'Metric Contract Table',
      definition: '指标口径表是把决策目的、信号、分子、分母、粒度、时间、排除规则和证据边界写在一起的工作契约。',
      why: '它让产品、数据和研发在计算前先对“算什么”达成可复核的一致。',
      problemSolved: '回答“这份指标定义怎样被后续 SQL 和评审引用”。',
      input: 'W3D6 查询集、业务问题和质量风险。',
      output: 'metric-contract-table.md。',
      systemPosition: '承接 W3 行级证据，开启 W4 指标计算前置定义。',
      process: ['逐条填写口径字段。', '先写一版可被批评的差稿。', '按质量风险逐项修订。', '把下一步明确指向 W4D2 聚合计算。'],
      owner: '产品经理维护口径表，后续由数据同事或自己在 W4D2 计算。',
      notResponsibleFor: '不负责在本日交付指标数字。',
      compareWith: '取数需求单请求明细；指标口径表定义要计算的指标。',
      evidence: ['metric-contract-table.md。', 'field checklist。', 'next_sql_task。'],
      failureModes: ['字段缺一半。', '写出口径后直接说指标已正确。'],
      pmUse: '先写 app_paid_order_count 和 app_payment_conversion_rate 两条口径，下一步再计算。',
      correctExample: 'next_sql_task: W4D2 用已审核口径学习 COUNT、DISTINCT、SUM 或 GROUP BY。',
      incorrectExample: 'next_sql_task: 指标已经算完，直接上线。',
    },
  ],
  diagram: {
    title: '指标口径定义链',
    caption: 'W4D1 的链路是：决策目的 → 信号 → 分子/分母 → 粒度/时间 → 排除规则 → 指标口径表 → W4D2 再计算。',
    nodes: [
      { id: 'purpose', label: '决策目的', description: '说明为什么要看这个指标。', input: '业务问题', output: 'decision_purpose', owner: '产品经理', evidence: '复盘或取舍动作' },
      { id: 'signal', label: '指标信号', description: '说明指标变化代表的有限业务现象。', input: '决策目的', output: 'signal', owner: '产品经理', evidence: 'signal_limit' },
      { id: 'formula', label: '分子/分母', description: '定义达成集合和机会集合。', input: 'W3 行级证据', output: 'numerator/denominator', owner: '产品经理+数据同事', evidence: '字段和值' },
      { id: 'boundary', label: '粒度/时间/排除', description: '定义去重、统计窗口和质量规则。', input: '质量风险', output: 'grain/time_window/exclusion_rules', owner: '产品经理', evidence: 'TEST1/O1018/NULL/O1014' },
      { id: 'contract', label: '指标口径表', description: '沉淀为后续计算前的契约。', input: '全部定义', output: 'metric-contract-table.md', owner: '产品经理', evidence: 'cannot_prove + next_sql_task' },
    ],
    branches: [
      { from: 'purpose', to: 'signal', label: '目的决定解释', kind: 'normal' },
      { from: 'signal', to: 'formula', label: '信号落到公式', kind: 'normal' },
      { from: 'formula', to: 'boundary', label: '公式必须加边界', kind: 'normal' },
      { from: 'boundary', to: 'contract', label: '边界写入口径表', kind: 'normal' },
      { from: 'formula', to: 'contract', label: '缺分母会导致比例无意义', kind: 'failure' },
    ],
    evidenceNotes: ['W4D1 只证明指标定义完整。', '不能证明聚合结果、真实生产指标、原因或业务效果。'],
  },
  demonstration: {
    title: '把 BQ12 改写成 app 支付指标口径',
    businessProblem: '运营想看 2026-08-31 app 渠道支付表现。W3D6 只有订单明细查询，不足以直接回答指标。',
    finalConclusion: '先定义两条口径：app_paid_order_count 与 app_payment_conversion_rate；其中转化率分母仍需确认支付尝试对象来源。',
    conclusionLimit: '这只证明口径可复核，不能证明指标已计算、真实生产结果正确或原因成立。',
    steps: [
      { title: '固定决策目的', action: '写要判断 app 支付链路是否需要排查。', reason: '目的决定后续分子分母取舍。', evidence: 'decision_purpose。', proves: '能证明指标服务一个具体决策。', limitation: '不能证明问题已经存在。' },
      { title: '定义指标信号', action: '写指标反映 app 支付订单规模或转化表现。', reason: '信号限制解释范围。', evidence: 'signal 与 signal_limit。', proves: '能避免把数字直接当原因。', limitation: '不能证明策略有效或无效。' },
      { title: '拆分分子集合', action: '把非测试 app paid 订单写入 numerator。', reason: '分子定义成功集合。', evidence: 'status=paid、channel=app、is_test=0。', proves: '能说明哪些行可能进入达成集合。', limitation: '本日不执行 COUNT 聚合计算。' },
      { title: '提出分母假设', action: '把 app 支付尝试订单写为 denominator，并标记来源待确认。', reason: '没有分母就不是转化率。', evidence: 'denominator + review_question。', proves: '能暴露数据缺口。', limitation: '不能凭 orders 表创造支付尝试数据。' },
      { title: '加粒度和时间', action: '写 order_id 去重与 2026-08-31 闭开时间窗口。', reason: '防止重复和跨天边界改变数字。', evidence: 'grain、dedupe_rule、time_window。', proves: '能说明后续计算边界。', limitation: '不能证明时区已确认。' },
      { title: '写排除和下一步', action: '排除 TEST1，标记 O1018、NULL 金额和 O1014 边界，next_sql_task 指向 W4D2。', reason: '把质量风险放到计算前。', evidence: 'exclusion_rules、quality_risks、cannot_prove、next_sql_task。', proves: '能形成可审核口径表。', limitation: '不能证明后续指标计算结果或真实生产结论。' },
    ],
  },
  guidedLab: {
    title: '指标口径六路径观察器',
    goal: '用六条教学模拟路径，把一个模糊指标改成可审核口径表。',
    safety: '教学模拟 · 只使用 W3D6 本地查询记录作为素材；不连接真实数据库，不写聚合 SQL，不计算真实指标。',
    conceptIds: [...conceptIds],
    predictionPrompt: '预测：最容易让指标失真的缺口，是没有决策目的、缺分母、粒度混乱、时间窗口模糊、测试数据未排除，还是过早计算？',
    steps: [
      { title: 'purpose-missing', action: '观察“app 支付率”只有名称，没有使用者和决策。', observe: 'decision_purpose 为空。', explanation: '没有目的时无法判断分子分母怎么取舍。', proves: '能识别指标命名不是口径。', cannotProve: '不能证明指标值。' },
      { title: 'denominator-missing', action: '观察只有 numerator=paid app orders，没有 denominator。', observe: '比例指标缺比较基准。', explanation: '没有分母就不能叫转化率。', proves: '能识别分母缺口。', cannotProve: '不能计算支付率。' },
      { title: 'grain-ambiguous', action: '观察 order_id 与 user_id 混用。', observe: '同一口径无法判断按单还是按人。', explanation: '粒度决定去重键。', proves: '能识别对象粒度。', cannotProve: '不能执行 DISTINCT。' },
      { title: 'time-window-ambiguous', action: '观察“8 月 31 日全天”没有起止和时区。', observe: 'O1014 这样的 0 点边界无法归属。', explanation: '时间窗口要写闭开边界和业务日假设。', proves: '能识别边界行风险。', cannotProve: '不能确认真实时区。' },
      { title: 'exclusion-missing', action: '观察 TEST1、O1018、NULL 金额未进入排除或风险。', observe: '质量问题会混入后续计算。', explanation: '排除规则必须在计算前写清。', proves: '能把 W3D4/W3D6 风险转入口径。', cannotProve: '不能证明数据已清洗。' },
      { title: 'qualified-metric-contract', action: '补齐 purpose、signal、numerator、denominator、grain、time_window、exclusion_rules 和 cannot_prove。', observe: '口径表可交给 W4D2 计算。', explanation: '合格口径先定义，后续才计算。', proves: '能证明定义完整。', cannotProve: '不能证明指标已计算或正确。' },
    ],
    recordPrompts: [
      '记录 purpose-missing：缺字段、为什么影响决策、怎么修订。',
      '记录 denominator-missing：分子是什么、分母缺什么、要向谁确认。',
      '记录 grain-ambiguous：按 order_id、user_id 还是 session_id，为什么。',
      '记录 time-window-ambiguous：写出闭开时间窗口和 O1014 边界。',
      '记录 exclusion-missing：TEST1、O1018、NULL、0 元如何处理。',
      '记录 qualified-metric-contract：哪些字段已齐，next_sql_task 如何指向 W4D2。',
    ],
    comparePrompt: '比较预测和实际：哪类缺口最容易把指标变成不可复核数字？你准备在口径表里怎么防止？',
    passCriteria: ['六条路径都有记录。', '没有写 COUNT/SUM/GROUP BY。', '至少一条口径包含分子、分母、粒度、时间和排除规则。', 'cannot_prove 明确排除真实生产和指标正确。', 'next_sql_task 只指向 W4D2 聚合计算。'],
  },
  independentLab: {
    title: '把另一个指标改成口径表',
    scenario: '运营新增问题：想看“app 渠道付费用户数”。你要把它从名称改成口径，不计算。',
    conceptIds: [...conceptIds],
    changedConditions: ['从订单数改为用户数', '从支付率改为支付用户规模', '保留同一时间窗口', '分母暂缺，只写待确认问题'],
    task: '写一条 app_paid_user_count 口径：决策目的、信号、分子、分母/不适用说明、grain=user_id、time_window、exclusion_rules、quality_risks、cannot_prove、next_sql_task。',
    predictionPrompt: '先预测：把订单指标改成用户指标后，最容易忘的是 grain 还是 denominator？',
    evidenceRequirements: ['写出 metric_id 和 decision_purpose。', 'grain 必须是 user_id 并说明去重规则。', '说明 TEST1 与 NULL user_id 的处理。', '不得计算 COUNT(DISTINCT user_id)。', 'next_sql_task 明确指向 W4D2。'],
    passCriteria: ['字段齐全且不是只有指标名称。', '用户粒度和去重键清楚。', '质量风险可追溯到 W3D4/W3D6。', '没有提前计算或宣称指标正确。'],
    remediation: { label: '回看粒度与去重', sectionId: 'concepts', anchor: 'concept-metric-grain' },
  },
  exercises: [
    exercise('w4d1-purpose-vs-name', ['概念与边界', '工作场景'], ['metric-decision-purpose', 'metric-signal'], '哪句话最像合格的指标决策目的？', ['判断 app 支付链路是否需要排查，并决定是否进入数据复核', '看一下支付率', '算出一个更好看的数字'], 0, '合格目的必须说明使用场景和后续动作。'),
    exercise('w4d1-denominator', ['机制推演', '证据判断'], ['metric-numerator', 'metric-denominator'], '“app 支付转化率”只有 paid app orders 作为分子时，最先缺什么？', ['有机会支付的 app 订单或用户分母', '更复杂的 JOIN', '一个漂亮图表'], 0, '比例指标必须有分母，否则无法解释转化。'),
    exercise('w4d1-grain', ['概念与边界', '综合变式'], ['metric-grain'], '要定义“付费用户数”，grain 最应该写什么？', ['user_id，并说明 NULL user_id 如何复核', 'order_id，因为订单表里有订单', 'paid_amount，因为金额最重要'], 0, '用户数按用户粒度，不按订单或金额粒度。'),
    exercise('w4d1-boundary', ['证据判断', '综合变式'], ['metric-time-window', 'metric-exclusion-rule'], '哪条 W4D1 结论没有越界？', ['口径已定义，下一步 W4D2 再聚合计算；本日不能证明指标正确', '指标已经算出并证明生产正确', 'GROUP BY 和 JOIN 已经完成'], 0, 'W4D1 的证据停在指标口径定义。'),
  ],
  deliverable: {
    title: '指标口径表',
    conceptIds: [...conceptIds],
    purpose: '把模糊指标名转成后续可计算、可复核、可质疑的口径契约；本课成果仍是教学模拟。',
    whenToUse: '在任何指标计算、看板、AB 实验或复盘之前使用。',
    audience: '未来继续学习 W4D2 的自己、数据同事、运营复盘参与者和评审者。',
    fields: [
      { name: 'metric_id', meaning: '指标唯一编号，例如 app_paid_order_count。', source: '指标命名' },
      { name: 'decision_purpose', meaning: '指标服务的决策或复盘动作。', source: '工作场景' },
      { name: 'signal', meaning: '指标变化代表的有限业务信号和解释边界。', source: '指标信号概念' },
      { name: 'numerator', meaning: '达成集合定义，写清字段、状态和值。', source: '分子概念' },
      { name: 'denominator', meaning: '机会集合定义；计数指标可写不适用并说明原因。', source: '分母概念' },
      { name: 'grain', meaning: '按订单、用户、会话或天统计，以及对应去重键。', source: '粒度与去重概念' },
      { name: 'time_window', meaning: '统计时间的闭开边界、业务日和时区假设。', source: '时间窗口' },
      { name: 'exclusion_rules', meaning: '测试、退款、重复、NULL、0 元等处理规则。', source: '排除规则' },
      { name: 'quality_risks', meaning: '仍需复核的数据质量风险。', source: 'W3D4/W3D6' },
      { name: 'source_query_ref', meaning: '引用 W3D6 的 BQ 编号或记录。', source: '业务查询集' },
      { name: 'can_prove', meaning: '这份口径能证明哪些定义已经齐全。', source: '证据边界' },
      { name: 'cannot_prove', meaning: '不能证明指标已计算、真实生产正确或原因成立。', source: '证据边界' },
      { name: 'next_sql_task', meaning: '下一步只进入 W4D2 聚合计算。', source: '课程边界' },
    ],
    badExample: 'metric_id: app_payment_rate\n说明: 看 app 支付率，先用 paid 订单除全部用户，测试数据应该不影响。指标已可用。',
    badReasons: ['没有写清指标服务的决策目的。', '分子、分母和统计粒度混在一起。', '没有写明时间窗口和排除规则。', '把口径定义越界说成指标已经可用。'],
    revisionSteps: ['补 decision_purpose 和 signal。', '拆 numerator、denominator 和 grain。', '写 time_window 和 exclusion_rules。', '把 TEST1、O1018、NULL、O1014 写进 quality_risks。', 'cannot_prove 排除真实生产和指标正确，next_sql_task 指向 W4D2。'],
    goodExample: '教学模拟 · metric_id: app_paid_order_count\ndecision_purpose: 判断 2026-08-31 app 渠道支付订单规模是否需要进一步复核\nsignal: app 渠道符合口径的支付订单规模信号，不能单独解释原因\nnumerator: status=paid AND channel=app AND is_test=0 的订单\ndenominator: 不适用；这是计数指标，不是转化率\ngrain: order_id；重复 order_id 先标记，计算前确认去重规则\ntime_window: 2026-08-31 00:00:00 <= paid_at < 2026-09-01 00:00:00，业务时区待确认\nexclusion_rules: 排除 is_test=1；refunded/cancelled 不计入 paid；NULL paid_at 不进入本指标\nquality_risks: O1018 重复、NULL paid_amount、O1014 跨天边界需复核\nsource_query_ref: W3D6 BQ01/BQ02/BQ12\ncan_prove: 能证明这条指标口径字段完整，可交给 W4D2 学习聚合计算\ncannot_prove: 不能证明真实生产订单数、收入、指标正确、原因、GROUP BY/JOIN 已完成或 W4D2 已完成\nnext_sql_task: W4D2 再按该口径学习 COUNT、DISTINCT 和 GROUP BY\n',
    guidedPrompts: ['先写第一条 metric_id 和业务对象。', '补写 decision_purpose，说明指标服务什么决策。', '补写 signal 和 signal_limit，限制解释范围。', '补写 numerator，说明哪些行进入达成集合。', '补写 denominator 或不适用原因。', '补写 grain 和 dedupe_rule，说明数谁和如何去重。', '补写 time_window，使用闭开时间边界。', '补写 exclusion_rules、quality_risks、cannot_prove 和 next_sql_task。'],
    blankTemplate: 'metric_id:\ndecision_purpose:\nsignal:\nnumerator:\ndenominator:\ngrain:\ntime_window:\nexclusion_rules:\nquality_risks:\nsource_query_ref:\ncan_prove:\ncannot_prove:\nnext_sql_task:\n',
    standardTemplate: 'metric-contract-table.md\n\nmetric_id: app_paid_order_count\ndecision_purpose: \nsignal: \nnumerator: \ndenominator: \ngrain: \ntime_window: \nexclusion_rules: \nquality_risks: \nsource_query_ref: W3D6 BQ01/BQ02/BQ12\ncan_prove: \ncannot_prove: 不能证明真实生产指标、收入、原因、GROUP BY、JOIN、指标正确或 W4D2 已完成\nnext_sql_task: W4D2 再按该口径学习聚合计算\n\nmetric_id: app_payment_conversion_rate\ndecision_purpose: \nsignal: \nnumerator: \ndenominator: \ngrain: \ntime_window: \nexclusion_rules: \nquality_risks: \nsource_query_ref: W3D6 BQ12 + 待确认支付尝试分母来源\ncan_prove: \ncannot_prove: 不能证明分母来源已存在、真实生产转化率、原因、GROUP BY、JOIN、指标正确或 W4D2 已完成\nnext_sql_task: W4D2 先确认分母来源，再学习 COUNT/DISTINCT 聚合\n',
    checklist: ['至少写出两条可复核指标口径。', '每条都有 decision_purpose 和 signal。', '比例指标必须有 numerator 与 denominator。', 'grain 写清 order_id 或 user_id 等去重键。', 'time_window 必须使用闭开时间边界。', 'exclusion_rules 覆盖 TEST1、O1018、NULL 或跨天边界。', 'cannot_prove 不宣称真实生产、指标正确、GROUP BY、JOIN 或 W4D2 已完成。'],
  },
  memory: {
    conceptIds: [...conceptIds],
    anchors: ['指标先服务决策，再进入公式。', '分子是达成集合，分母是机会集合。', '粒度回答数谁，时间窗口回答数哪段，排除规则回答谁不能进。', 'W4D1 只定义口径，W4D2 才计算。'],
    closedBookPrompt: '闭卷写出 app_payment_conversion_rate 的决策目的、信号、分子、分母、粒度、时间窗口、排除规则和不能证明事项。',
    microOperation: '不看模板，把“支付率”改写成一条包含 13 个字段的 metric-contract-table.md 记录。',
    unresolvedPrompt: '写出你进入 W4D2 前最担心的数据缺口：分母来源、去重键、时间窗口、测试数据还是 NULL/重复行？准备怎样确认？',
    reviewStages: [
      { stage: 'D1', task: '闭卷复述指标口径表 13 个字段，并解释为什么不能先算。' },
      { stage: 'D3', task: '把一个新指标名拆成决策目的、信号、分子、分母和粒度。' },
      { stage: 'D7', task: '检查一条口径是否写清 TEST1、O1018、NULL 和跨天边界。' },
      { stage: 'D14', task: '比较 app_paid_order_count 与 app_payment_conversion_rate 的分母差异。' },
      { stage: 'D30', task: '从 W3D6 查询集倒推一条可计算指标口径。' },
      { stage: 'D60', task: '不看模板，说明 W4D1 与 W4D2 的边界：定义口径 vs 聚合计算。' },
    ],
  },
  nextLesson: { id: 'W4D2', title: '聚合与分组入门', bridge: '下一课才开始把已定义口径映射到 COUNT、DISTINCT、SUM、GROUP BY 等聚合 SQL；W4D1 不提前计算。' },
}
