import type { DailyCourse, Exercise } from './types'

const conceptIds = [
  'aggregation-input-set',
  'count-aggregate',
  'distinct-aggregate',
  'sum-aggregate',
  'avg-aggregate',
  'group-by-bucket',
  'having-group-filter',
  'aggregation-logic-map',
] as const

const prerequisiteConceptIds = [
  'query-question',
  'where-condition',
  'date-range-boundary',
  'distinct-result',
  'null-value',
  'duplicate-row',
  'test-data-flag',
  'quality-evidence-boundary',
  'business-query-set',
  'quality-flagged-answer',
  'metric-decision-purpose',
  'metric-signal',
  'metric-numerator',
  'metric-denominator',
  'metric-grain',
  'metric-time-window',
  'metric-exclusion-rule',
  'metric-contract-table',
] as const

function exercise(
  id: string,
  categories: Exercise['categories'],
  ids: string[],
  prompt: string,
  options: string[],
  answerIndex: number,
  referenceAnswer: string,
): Exercise {
  return {
    id,
    kind: 'single-choice',
    categories,
    conceptIds: ids,
    prompt,
    hint: '先看输入行集合是否已经按 W4D1 口径过滤，再判断是数行、数唯一对象、求和、求均值、按组汇总还是过滤分组结果。',
    options: options.map((label, index) => ({
      label,
      rationale: index === answerIndex ? '这项把口径、输入行集合、聚合函数、分组和证据边界连起来。' : '这项要么跳过口径过滤，要么把聚合结果越界说成真实生产结论或 JOIN 对账。',
      couldBeTrueWhen: index === answerIndex ? '当学习者正在完成 W4D2 聚合逻辑图。' : '只有后续 W4D3-W5D6 补齐指标计算、误导案例、评审和 JOIN 后，才可能支持更强判断。',
    })),
    answerIndex,
    referenceAnswer,
    reasoning: [
      'W4D2 承接 W4D1 的口径表，第一次把 COUNT、COUNT(DISTINCT)、SUM、AVG、GROUP BY 和 HAVING 放到可执行 SQL 链路里。',
      'WHERE 先形成输入行集合，聚合函数再把多行压成一个数，GROUP BY 把输入行拆成多个桶后分别聚合。',
      '本日只基于 W4 本地 events 教学表做聚合逻辑图，不做 JOIN、不证明真实生产指标正确、不完成 W4D3 指标计算 SQL。',
    ],
    rubric: ['先固定输入行', '聚合函数职责正确', '分组和过滤组不混', '证据边界不过界'],
    commonErrors: [
      { error: '直接写 COUNT(*)，没有先说明 WHERE 输入行', reason: '聚合计算的对象不是整张表，而是口径过滤后的行集合。' },
      { error: '把 HAVING 当成行过滤', reason: 'HAVING 过滤的是 GROUP BY 之后的组，不替代 WHERE。' },
    ],
    remediation: { label: '回看聚合逻辑图', sectionId: 'diagram', anchor: 'w4d2-aggregation-logic' },
  }
}

export const w4d2: DailyCourse = {
  id: 'W4D2',
  contentVersion: 'w4d2-aggregation-logic-day01-v1',
  week: 4,
  day: 2,
  title: '聚合与分组入门',
  subtitle: '把 W4D1 的指标口径映射成 COUNT、DISTINCT、SUM、AVG、GROUP BY 和 HAVING 的执行逻辑；本日只完成本地教学聚合逻辑图，不做 JOIN 或生产指标结论。',
  duration: { core: 30, standard: 45, extension: 76, full: 126 },
  coreConceptGroups: [
    {
      id: 'aggregate-after-filter',
      title: '先确定输入行，再聚合',
      conceptIds: ['aggregation-input-set', 'count-aggregate', 'distinct-aggregate'],
      summary: 'WHERE 和口径规则先决定哪些事件行进入计算；COUNT 数行，COUNT(DISTINCT) 数唯一对象。',
      boundary: '能解释本地 events 表的样本数和去重人数；不能证明真实生产规模或口径已批准。',
    },
    {
      id: 'amount-summary',
      title: '金额聚合要看 SUM 与 AVG 的差异',
      conceptIds: ['sum-aggregate', 'avg-aggregate'],
      summary: 'SUM 回答总量，AVG 回答平均水平；异常大单会强烈影响平均值，因此需要和中位数或样本一起看。',
      boundary: '能观察教学表中 O06 9999 元如何推高均值；不能完成 W4D4 的误导案例分析。',
    },
    {
      id: 'group-and-having',
      title: 'GROUP BY 先分桶，HAVING 再过滤组',
      conceptIds: ['group-by-bucket', 'having-group-filter', 'aggregation-logic-map'],
      summary: 'GROUP BY 把输入行按字段分成多个组，每组各自聚合；HAVING 只筛选聚合后的组。',
      boundary: '能画出分组聚合顺序；不能提前进入 JOIN、跨表对账或真实看板发布。',
    },
  ],
  prerequisiteConceptIds: [...prerequisiteConceptIds],
  learningPaths: {
    '30': {
      guidedStepIndices: [0, 1, 2, 3, 4, 5],
      guidedRecordIndices: [0, 1, 2, 3, 4, 5],
      exerciseCount: 3,
      deliverablePromptCount: 6,
      deliverableChecklistIndices: [0, 1, 2, 3, 4],
      deliverableMinimumContributionCharacters: 260,
    },
    '45': {
      guidedStepIndices: [0, 1, 2, 3, 4, 5],
      guidedRecordIndices: [0, 1, 2, 3, 4, 5],
      exerciseCount: 4,
      deliverablePromptCount: 6,
      deliverableChecklistIndices: [0, 1, 2, 3, 4, 5],
      deliverableMinimumContributionCharacters: 380,
    },
  },
  primaryGoal: '提交 `aggregation-logic.md`：用本地 W4 events 教学表写清 input_rows、where_rule、aggregate_function、distinct_key、group_key、having_rule、result_value、can_prove、cannot_prove 和 next_sql_task。',
  scenario: {
    role: '你是刚完成 W4D1 指标口径表的产品经理。',
    situation: '运营同学希望看到曝光到支付、结算到支付和结算后 24 小时转化。你已经知道分子、分母、粒度、时间窗口和排除规则，现在要把它们变成第一批可复核聚合 SQL 逻辑。',
    question: '怎样从一张事件明细表中，正确数人数、去重订单、求金额、按组汇总，并说明这个结果最多能证明到哪里？',
    stakes: '如果没有先固定输入行和去重键，COUNT 会把测试用户、重复支付事件或错误时间窗口算进去；如果把 AVG 当成总体代表，又会被 9999 元异常大单误导。',
  },
  objectives: [
    { id: 'w4d2-objective-input', text: '能把指标口径转成聚合前的输入行集合', evidence: '`aggregation-logic.md` 写出 input_rows、where_rule、time_window 和 exclusions。' },
    { id: 'w4d2-objective-count', text: '能区分 COUNT、COUNT(DISTINCT)、SUM 与 AVG', evidence: '练习记录中分别解释 exposed_users、unique_paid_orders、average_amount 和 total_amount 的差异。' },
    { id: 'w4d2-objective-group', text: '能说明 GROUP BY 和 HAVING 的先后责任', evidence: '聚合逻辑图写出 group_key 先分桶，having_rule 只过滤组结果。' },
    { id: 'w4d2-objective-boundary', text: '能说明本地聚合结果的证据边界', evidence: 'cannot_prove 明确排除真实生产指标正确、JOIN、归因、趋势和 W4D3 已完成。' },
  ],
  prerequisites: [
    {
      id: 'w4d2-w4d1-readiness',
      conceptIds: [...prerequisiteConceptIds],
      prompt: '你是否能把 W3D1-W4D1 的前置串起来：终端、安全副本、SELECT 顺序、基础查询、质量风险、取数需求、业务查询、指标口径，最后再进入 W4D2 聚合？',
      passDescription: '能说明 W3D1-W3D6 的本地 SQL 学习链路，以及 W4D1 口径表如何把分子、分母、粒度、时间窗口和排除规则交给 W4D2。',
      remediationLabel: '回到 W4D1 补指标口径表',
      remediationTarget: '#/lesson/W4D1',
      remediation: {
        purpose: 'W4D2 可以提前阅读；但没有 W3D1-W4D1 的完整链路，COUNT 和 GROUP BY 只会变成机械公式。',
        steps: ['补齐 W3D1-W3D6 的查询与质量边界，再回看 W4D1 的 metric_id、numerator、denominator、grain、time_window 和 exclusions。', '确认 TEST、重复 order_id、NULL、O06 和 U03 是否进入或排除计算。', '写一句“W4D2 只计算本地教学样本，不证明真实生产指标”。'],
        successCheck: '能把“数什么、怎么分组、怎么去重、怎么过滤组”改写成可交接的聚合逻辑。',
      },
    },
  ],
  concepts: [
    {
      id: 'aggregation-input-set',
      prerequisiteConceptIds: ['metric-time-window', 'metric-exclusion-rule', 'where-condition'],
      term: '聚合输入行集合',
      english: 'Aggregation Input Set',
      definition: '聚合输入行集合是所有 COUNT、SUM、AVG 和 GROUP BY 开始前已经被口径、时间和排除规则筛出的明细行。',
      why: '聚合函数只会处理进入它的行；输入行错了，后面的数字即使 SQL 正确也没有业务意义。',
      problemSolved: '回答“这个数字到底基于哪些事件行”。',
      input: 'events 教学表里经过 WHERE、时间窗口和排除规则筛过的明细事件行。',
      output: '一批可继续进入 COUNT、SUM、AVG 或 GROUP BY 的候选输入行集合。',
      systemPosition: '位于 FROM/WHERE 之后、聚合函数之前。',
      process: ['从口径表取出时间窗口。', '写 WHERE 过滤事件名和测试数据。', '保留需要聚合的字段。'],
      owner: '产品经理负责确认口径；SQL 执行器只按条件筛行。',
      notResponsibleFor: '不负责决定后续函数、分组或真实生产结论。',
      compareWith: 'W4D1 定义口径；W4D2 把口径落实成聚合前的输入行。',
      evidence: ['WHERE event_name="coupon_exposure"。', 'is_test=0。', 'event_time 的闭开边界。'],
      failureModes: ['忘记排除 TEST。', '把 24 小时窗口写成固定次日午夜。'],
      pmUse: '先写“非测试 coupon_exposure 行”，再讨论 COUNT(DISTINCT user_id)。',
      correctExample: 'input_rows: events WHERE event_name="coupon_exposure" AND is_test=0。',
      incorrectExample: '直接 COUNT(*) FROM events，然后说这就是曝光人数。',
    },
    {
      id: 'count-aggregate',
      prerequisiteConceptIds: ['aggregation-input-set'],
      term: 'COUNT 计数',
      english: 'COUNT',
      definition: 'COUNT 是把输入行集合压成行数或非空值数量的聚合函数；COUNT(*) 数行，COUNT(column) 数非空值。',
      why: '很多指标先从“多少行、多少事件”开始，但 COUNT 不会自动理解用户、订单或业务对象。',
      problemSolved: '回答“符合条件的记录有多少”。',
      input: '已经筛好的事件行集合，以及决定是否数行还是数非空值的字段。',
      output: '一个可回溯到输入行集合的计数结果。',
      systemPosition: '位于输入行集合之后，是最基础的聚合函数。',
      process: ['确认输入行。', '决定数所有行还是数非空字段。', '写出结果和不能证明事项。'],
      owner: 'SQL 负责计数；产品经理负责解释这个数代表什么对象。',
      notResponsibleFor: '不负责自动去重、求金额或分组。',
      compareWith: 'COUNT 数记录；DISTINCT 去掉重复对象后再数。',
      evidence: ['COUNT(*) 数所有输入行。', 'COUNT(user_id) 数非空 user_id。', '结果列名和输入行集合。'],
      failureModes: ['把重复支付事件当成订单数。', 'COUNT(column) 被 NULL 影响却没说明。'],
      pmUse: '用 COUNT(*) 看 payment_success 事件条数，再检查是否需要按 order_id 去重。',
      correctExample: 'COUNT(*) AS payment_events。',
      incorrectExample: 'COUNT(*) 一定等于支付用户数。',
    },
    {
      id: 'distinct-aggregate',
      prerequisiteConceptIds: ['metric-grain', 'distinct-result'],
      term: 'COUNT(DISTINCT) 去重计数',
      english: 'COUNT DISTINCT',
      definition: 'COUNT(DISTINCT key) 先按 key 去掉重复值，再计数；它把指标粒度落到用户、订单或其他唯一对象上。',
      why: '同一个用户或订单可能有多条事件。没有 DISTINCT，转化率和支付订单数会被重复事件放大。',
      problemSolved: '回答“唯一用户/唯一订单有多少”。',
      input: '输入行集合、待去重键和重复样本。',
      output: '去掉重复值后的唯一对象数量。',
      systemPosition: '位于 COUNT 与指标粒度之间。',
      process: ['选择去重键。', '确认 NULL 是否会被排除。', '记录重复样本。'],
      owner: '产品经理确认数谁，SQL 用 DISTINCT 执行。',
      notResponsibleFor: '不负责修复重复数据或证明生产去重规则已批准。',
      compareWith: 'DISTINCT 是 SQL 去重动作；grain 是业务口径里的数谁。',
      evidence: ['COUNT(DISTINCT user_id) 数唯一用户。', 'COUNT(DISTINCT order_id) 数唯一订单。', 'O05 重复支付事件处理。'],
      failureModes: ['按 user_id 去重却解释成订单数。', '忘记 O05/E13/E14 是同一订单。'],
      pmUse: '计算 exposure_to_pay 时用 DISTINCT user_id；计算支付订单数时用 DISTINCT order_id。',
      correctExample: 'COUNT(DISTINCT CASE WHEN event_name="payment_success" THEN user_id END)。',
      incorrectExample: '把 payment_success 事件数直接当支付人数。',
    },
    {
      id: 'sum-aggregate',
      prerequisiteConceptIds: ['aggregation-input-set'],
      term: 'SUM 求和',
      english: 'SUM',
      definition: 'SUM 把输入行中的数值字段加总，常用于金额、次数或时长总量。',
      why: '总金额和订单数回答的是不同问题；求和前必须确认重复订单、测试数据和 NULL 金额是否进入。',
      problemSolved: '回答“总量是多少，以及总量来自哪些输入行”。',
      input: '数值字段、已过滤的输入行和是否先去重的规则。',
      output: '一个总量数字和对应的边界说明。',
      systemPosition: '位于金额类指标的聚合函数层。',
      process: ['确认数值字段。', '排除测试和重复。', '写 SUM 结果及边界。'],
      owner: 'SQL 计算总量，产品经理解释用途和限制。',
      notResponsibleFor: '不负责说明用户平均水平或分布。',
      compareWith: 'SUM 是总量；AVG 是平均水平。',
      evidence: ['SUM(amount) 计算总量。', '先按 order_id 去重再求和。', 'unique_paid_orders。'],
      failureModes: ['重复支付成功事件导致金额翻倍。', '把教学表总额说成真实 GMV。'],
      pmUse: '先按 order_id 去重，再用 SUM(amount) 看教学样本支付总额。',
      correctExample: 'SUM(amount) AS total_paid_amount FROM unique_paid_orders。',
      incorrectExample: '直接 SUM(events.amount)，不处理重复支付事件。',
    },
    {
      id: 'avg-aggregate',
      prerequisiteConceptIds: ['sum-aggregate'],
      term: 'AVG 平均值',
      english: 'AVG',
      definition: 'AVG 用输入行的总和除以非空样本数，表达平均水平，但容易被极端值拉动。',
      why: 'W4 教学表中的 9999 元大单会把平均支付金额推高；PM 必须同时看样本和护栏。',
      problemSolved: '回答“平均每个对象是多少”，并提醒异常值风险。',
      input: '数值字段、样本数和异常值标注。',
      output: '一个平均值以及必须对照的样本护栏。',
      systemPosition: '位于金额分布观察的第一层，后续 W4D4 才系统分析误导。',
      process: ['确认输入样本。', '计算 AVG。', '对照 min/max 或中位数附近样本。'],
      owner: 'SQL 给出平均值；产品经理判断是否需要补充护栏。',
      notResponsibleFor: '不负责单独代表分布或证明策略效果。',
      compareWith: 'AVG 容易受异常值影响；中位数更接近排序中间样本。',
      evidence: ['AVG(amount) 会受极端值影响。', 'max_amount=9999。', 'median_amount=89。'],
      failureModes: ['只看平均值，忽略异常大单。', '把平均支付金额写成客单价最终结论。'],
      pmUse: '看到 average_amount=2077 时，主动补 median_amount 和异常样本说明。',
      correctExample: 'AVG=2077 受 O06 9999 元影响，不能单独代表典型订单。',
      incorrectExample: '平均值 2077，说明用户通常支付 2077 元。',
    },
    {
      id: 'group-by-bucket',
      prerequisiteConceptIds: ['aggregation-input-set'],
      term: 'GROUP BY 分组',
      english: 'GROUP BY',
      definition: 'GROUP BY 按指定字段把输入行拆成多个组，然后让每个组分别执行聚合函数。',
      why: '产品分析常要比较渠道、状态或日期；分组能让同一口径下的多个类别并列出现。',
      problemSolved: '回答“每个类别各自是多少”。',
      input: '输入行集合、分组键、组内聚合函数和每组的行集。',
      output: '每个组一行的聚合结果，以及可以继续过滤的组级数据。',
      systemPosition: '位于 WHERE 之后、SELECT 聚合结果输出之前。',
      process: ['确定 group_key。', '每个组内执行 COUNT/SUM/AVG。', '输出组名和聚合值。'],
      owner: 'SQL 分组计算；产品经理确认分组键是否符合业务问题。',
      notResponsibleFor: '不负责跨表补维度或 JOIN。',
      compareWith: 'WHERE 过滤行；GROUP BY 把剩余行分桶。',
      evidence: ['GROUP BY event_name 先分桶。', 'GROUP BY date(event_time) 先按日期分组。'],
      failureModes: ['忘记分组键导致全表只有一个数字。', '把分组结果当成不同用户画像因果。'],
      pmUse: '按 event_name 看曝光、结算、支付三个阶段各有多少唯一用户。',
      correctExample: 'GROUP BY event_name 后每个事件类型各有一行。',
      incorrectExample: 'GROUP BY 已经说明转化原因。',
    },
    {
      id: 'having-group-filter',
      prerequisiteConceptIds: ['group-by-bucket'],
      term: 'HAVING 组过滤',
      english: 'HAVING',
      definition: 'HAVING 是在 GROUP BY 和聚合之后过滤组结果的条件，常用于只保留样本数足够或结果超过阈值的组。',
      why: '有些条件要等组内 COUNT/SUM 算完后才知道；这类条件不能写在 WHERE 里。',
      problemSolved: '回答“哪些分组结果达到继续查看门槛”。',
      input: '分组聚合结果和组级阈值。',
      output: '被保留的分组行和被筛掉的组级说明。',
      systemPosition: '位于 GROUP BY 聚合之后、最终输出之前。',
      process: ['先按 group_key 把输入行分成多个组。', '再在每个组里计算 COUNT、SUM 或 AVG。', '最后用 HAVING 只保留达到门槛的组。'],
      owner: '产品经理定义阈值理由，SQL 执行组过滤。',
      notResponsibleFor: '不负责过滤原始行或证明组差异原因。',
      compareWith: 'WHERE 过滤明细行；HAVING 过滤聚合后的组。',
      evidence: ['HAVING COUNT(DISTINCT user_id) >= 2。', '被过滤组清单和保留理由。'],
      failureModes: ['把 COUNT 条件写进 WHERE。', '用 HAVING 后忘记说明小样本被隐藏。'],
      pmUse: '只展示样本数达到门槛的事件阶段，同时记录被隐藏组不能用于结论。',
      correctExample: 'GROUP BY event_name HAVING COUNT(DISTINCT user_id) >= 2。',
      incorrectExample: 'WHERE COUNT(DISTINCT user_id) >= 2。',
    },
    {
      id: 'aggregation-logic-map',
      prerequisiteConceptIds: ['count-aggregate', 'distinct-aggregate', 'sum-aggregate', 'avg-aggregate', 'group-by-bucket', 'having-group-filter'],
      term: '聚合逻辑图',
      english: 'Aggregation Logic Map',
      definition: '聚合逻辑图是把业务问题、口径输入行、聚合函数、分组键、结果值和证据边界写在同一张可复核记录里。',
      why: '零散 SQL 很难审阅；逻辑图让产品、数据和未来的自己知道每个数字从哪来、能说明什么。',
      problemSolved: '回答“这条聚合 SQL 如何从口径变成有限数字”。',
      input: 'W4D1 口径表、events 教学表和一段可读的聚合 SQL。',
      output: 'aggregation-logic.md，可被复核和交接的聚合逻辑记录。',
      systemPosition: '位于 W4D2 成果层，承接 W4D1，交给 W4D3 继续写指标计算 SQL。',
      process: ['写业务问题与 metric_ref。', '写输入行和 where_rule。', '写聚合函数、去重键和分组键。', '写结果、边界和下一步。'],
      owner: '产品经理负责解释、交接和有限结论；SQL 负责产生本地结果。',
      notResponsibleFor: '不负责发布看板、归因、趋势、JOIN 或真实生产验收。',
      compareWith: '指标口径表定义算什么；聚合逻辑图说明这次怎样算出教学样本数字。',
      evidence: ['aggregation_id。', 'metric_ref。', 'sql_snippet。', 'result_value。', 'can_prove/cannot_prove。'],
      failureModes: ['只有数字没有输入行说明。', '把教学样本直接写成真实业务结论。'],
      pmUse: '把 exposure_to_pay=0.4000 写成一条可复核逻辑，而不是孤立百分比。',
      correctExample: 'A3: exposed_users=10, paid_same_day_users=4, exposure_to_pay=0.4000, cannot_prove=真实生产转化率。',
      incorrectExample: '支付转化率 40%，所以运营效果不好。',
    },
  ],
  diagram: {
    title: '聚合 SQL 从口径到结果的顺序',
    caption: 'W4D2 的链路是：口径表 → 输入行集合 → 聚合函数 → 分组桶 → HAVING 组过滤 → 本地教学结果 → W4D3 再写完整指标 SQL。',
    nodes: [
      { id: 'contract', label: 'W4D1 口径', description: '定义分子、分母、粒度、时间和排除规则。', input: 'metric-contract-table.md', output: '可执行规则', owner: '产品经理' },
      { id: 'input', label: '输入行集合', description: '用 WHERE 和排除规则固定进入计算的事件行。', input: 'events 明细', output: 'filtered rows', owner: 'SQL 查询', evidence: 'event_name、is_test、event_time' },
      { id: 'aggregate', label: '聚合函数', description: 'COUNT、DISTINCT、SUM、AVG 把多行压成数字。', input: 'filtered rows', output: 'count/sum/avg', owner: '数据库执行器' },
      { id: 'group', label: 'GROUP BY 分组桶', description: 'GROUP BY 让每个类别分别计算。', input: 'group_key', output: '每组聚合结果', owner: '数据库执行器' },
      { id: 'having', label: 'HAVING 组过滤器', description: 'HAVING 只保留符合组级门槛的结果。', input: 'grouped metrics', output: 'filtered groups', owner: '数据库执行器' },
      { id: 'boundary', label: '证据边界', description: '写明教学样本能证明和不能证明什么。', input: 'result_value', output: 'can/cannot_prove', owner: '产品经理' },
    ],
    branches: [
      { from: 'contract', to: 'input', label: '转成 WHERE', kind: 'normal' },
      { from: 'input', to: 'aggregate', label: '进入函数', kind: 'normal' },
      { from: 'aggregate', to: 'group', label: '需要分类比较时', kind: 'normal' },
      { from: 'group', to: 'having', label: '过滤组结果', kind: 'normal' },
      { from: 'having', to: 'boundary', label: '交付有限结论', kind: 'normal' },
      { from: 'input', to: 'boundary', label: '输入行不清导致结果不可解释', kind: 'failure' },
    ],
    evidenceNotes: ['COUNT 不自动去重。', 'AVG 会被异常值拉动。', 'HAVING 过滤组，不过滤原始行。', '本地教学结果不能证明真实生产指标正确。'],
  },
  demonstration: {
    title: '教师示范：把曝光到支付转化率拆成两次计数和一次除法',
    businessProblem: '运营想知道 2026-09-07 优惠券曝光到支付转化。你要用 W4D1 的口径先数非测试曝光用户，再数自然日非测试支付用户，最后解释 0.4000 的边界。',
    finalConclusion: '教学表中 exposed_users=10、paid_same_day_users=4，exposure_to_pay=0.4000；这只证明本地教学口径下的计算路径，不证明真实生产转化率或原因。',
    conclusionLimit: '本日不做 JOIN，不发布看板，不证明业务趋势，也不完成 W4D3 的正式指标计算 SQL。',
    steps: [
      { title: '先读取 W4D1 口径表与聚合问题', action: '确认 W4D1 口径、W3D6 质量风险和 W4D2 要解决的聚合问题。', reason: '聚合必须服务先前已经定义好的口径，而不是反过来。', evidence: 'metric_ref、input_rows、result_value。', proves: '知道要把哪些口径映射成聚合逻辑。', limitation: '还没有形成输入行。' },
      { title: '形成分母输入行', action: 'WHERE event_name="coupon_exposure" AND is_test=0。', reason: '先把测试数据排除。', evidence: '10 个唯一 user_id。', proves: '分母集合可复核。', limitation: '不证明这些用户都看到真实生产曝光。' },
      { title: '形成分子输入行', action: 'WHERE event_name="payment_success" AND is_test=0 AND event_time 在自然日内。', reason: '自然日窗口决定 U03 是否进入。', evidence: '4 个自然日支付用户。', proves: '分子集合可复核。', limitation: '不证明 24 小时窗口结果。' },
      { title: '选择唯一去重键并保住粒度', action: '使用 COUNT(DISTINCT user_id) 或 COUNT(DISTINCT order_id) 保护粒度。', reason: '转化率按用户粒度，支付订单数按订单粒度，不按事件条数。', evidence: '重复支付事件不会重复计入用户或订单。', proves: '去重键符合口径。', limitation: '不证明重复事件根因。' },
      { title: '计算并命名结果', action: 'ROUND(1.0 * paid_same_day_users / exposed_users, 4) AS exposure_to_pay。', reason: '除法前先保证两个集合含义一致。', evidence: '0.4000。', proves: '本地教学样本的口径计算路径。', limitation: '不能解释为什么高或低。' },
      { title: '写出下一步交接到 W4D3', action: '把完整逻辑放进 aggregation-logic.md，next_sql_task 指向 W4D3 指标计算 SQL。', reason: 'W4D3 才把多个指标写成完整 SQL 产物。', evidence: 'can_prove、cannot_prove、next_sql_task。', proves: '交接不过界。', limitation: '不替代真实生产验收。' },
    ],
  },
  guidedLab: {
    title: '教学聚合台：同一漏斗的六条聚合路径',
    goal: '在本地 W4 events 教学表中观察 COUNT、DISTINCT、SUM、AVG、GROUP BY 和 HAVING 如何改变结果，并记录证据边界。',
    safety: '这是本地教学模拟，不连接真实数据库、不读取公司数据、不生成生产指标。',
    conceptIds: [...conceptIds],
    predictionPrompt: '如果同一订单出现两条 payment_success，COUNT(*) 和 COUNT(DISTINCT order_id) 会不会一样？先写出预测和理由。',
    steps: [
      { title: 'exposed-users-count', action: '用 COUNT(DISTINCT user_id) 统计非测试曝光用户。', observe: 'exposed_users=10。', explanation: '输入行先排除 TEST，再按 user_id 去重。', proves: '能把分母口径转成计数。', cannotProve: '不能证明真实曝光用户数。' },
      { title: 'same-day-payment-rate', action: '统计自然日支付用户并除以曝光用户。', observe: 'paid_same_day_users=4，exposure_to_pay=0.4000。', explanation: '自然日窗口只包含 2026-09-07 当天支付。', proves: '能计算本地教学自然日转化。', cannotProve: '不能证明原因或趋势。' },
      { title: 'rolling-24h-window', action: '从每个 checkout_view 向后滚动 24 小时匹配 payment_success。', observe: 'paid_within_24h_users=4，U03 不计入。', explanation: '滚动窗口不是统一次日午夜，U03 超过 24 小时。', proves: '能区分自然日和滚动窗口。', cannotProve: '不能证明生产时区规则已批准。' },
      { title: 'unique-paid-orders', action: '按 order_id 去重 payment_success。', observe: 'unique_paid_orders=5。', explanation: 'O05 有两条成功事件，只能按订单粒度计一次。', proves: '能用 DISTINCT 保护粒度。', cannotProve: '不能修复重复事件根因。' },
      { title: 'average-vs-median', action: '计算 AVG(amount)，并对照中位数和最大值。', observe: 'average_amount=2077.00，median_amount=89.00，max_amount=9999.00。', explanation: '异常大单会拉高平均值，不能单看 AVG。', proves: '能识别均值护栏。', cannotProve: '不能完成 W4D4 误导案例分析。' },
      { title: 'group-having-gate', action: '按 event_name 分组后，用 HAVING 保留样本数足够的组。', observe: 'GROUP BY 先生成组，HAVING 再过滤组。', explanation: 'WHERE 过滤行，HAVING 过滤组结果。', proves: '能画出分组和组过滤顺序。', cannotProve: '不能完成 JOIN 或跨表对账。' },
    ],
    recordPrompts: [
      '记录 exposed-users-count 的 input_rows、function、distinct_key、result_value。',
      '记录 same-day-payment-rate 的 numerator、denominator、rate 和 cannot_prove。',
      '记录 rolling-24h-window 中 U03 为什么不计入。',
      '记录 unique-paid-orders 如何处理 O05 重复 payment_success。',
      '记录 average_amount 与 median_amount 差异说明。',
      '记录 GROUP BY 与 HAVING 的先后和下一步 W4D3。',
    ],
    comparePrompt: '对照六条记录，找出哪条最容易因为输入行、去重键、时间窗口或异常值而被误读。',
    passCriteria: ['六条聚合路径都有记录。', 'COUNT、DISTINCT、SUM、AVG、GROUP BY、HAVING 都出现。', '记录里明确写出 aggregation_id、metric_ref、input_rows、where_rule、aggregate_function、distinct_key、group_key、having_rule、result_value 和 edge_case。', 'U03、O05、TEST 和 O06 异常大单至少各解释一次。', 'cannot_prove 不宣称真实生产、JOIN、归因、趋势或 W4D3 已完成。'],
  },
  independentLab: {
    title: '独立变式：把结算到支付 24 小时口径画成聚合逻辑图',
    scenario: '运营改问“看过结算页后 24 小时内支付的用户占比”。你要从 checkout_view 分母、payment_success 分子、user_id 去重、滚动 24 小时窗口和 U03 边界重新画逻辑图。',
    conceptIds: ['aggregation-input-set', 'distinct-aggregate', 'group-by-bucket', 'having-group-filter', 'aggregation-logic-map'],
    changedConditions: ['分母改为 checkout_view 用户。', '分子改为结算后 24 小时内支付用户。', 'U03 支付晚于 24 小时 59 分钟，不计入。', '仍排除 TEST。'],
    task: '写出 input_rows、join/match rule 的教学说明、COUNT(DISTINCT user_id)、result_value=0.5714、cannot_prove 和 next_sql_task。',
    predictionPrompt: '你预测结算后 24 小时转化率和自然日结算到支付转化率是否一样？为什么？',
    evidenceRequirements: ['必须写 checkout_users=7。', '必须写 paid_within_24h_users=4。', '必须说明 U03 不计入。', '必须区分 WHERE 行过滤和 HAVING 组过滤。', '必须写不能证明真实生产转化率或原因。'],
    passCriteria: ['口径、函数、去重键、时间窗口和结果齐全。', '记录里明确写出 aggregation_id、metric_ref、input_rows、where_rule、aggregate_function、distinct_key、group_key、having_rule、result_value 和 edge_case。', '没有把滚动 24 小时写成次日午夜。', '没有提前完成 W4D3、JOIN 或真实看板发布。'],
    remediation: { label: '回看滚动 24 小时与 HAVING 边界', sectionId: 'concepts', anchor: 'concept-having-group-filter' },
  },
  exercises: [
    exercise('w4d2-input-set', ['概念与边界', '工作场景'], ['aggregation-input-set', 'count-aggregate'], '统计曝光用户前，最先应该确认什么？', ['输入行只包含非测试 coupon_exposure，并按 user_id 去重', '先 GROUP BY 任意字段', '直接把 events 全表行数当曝光用户'], 0, '聚合前先固定输入行集合，曝光用户要排除 TEST 并按 user_id 去重。'),
    exercise('w4d2-distinct-key', ['机制推演'], ['distinct-aggregate'], 'O05 有两条 payment_success，计算唯一支付订单数最稳妥的写法是什么？', ['COUNT(DISTINCT order_id) 或先按 order_id 去重', 'COUNT(*)', 'AVG(amount)'], 0, '订单粒度指标要按 order_id 去重，COUNT(*) 会把重复事件算两次。'),
    exercise('w4d2-avg-boundary', ['证据判断'], ['avg-aggregate', 'sum-aggregate'], 'average_amount=2077.00 时，哪条解释不过界？', ['平均值受 O06 9999 元影响，应同时查看中位数和样本', '典型用户都会支付 2077 元', '运营策略已证明成功'], 0, 'AVG 能计算平均值，但不能单独代表典型样本或证明策略效果。'),
    exercise('w4d2-having', ['综合变式'], ['group-by-bucket', 'having-group-filter'], 'HAVING 和 WHERE 的核心区别是什么？', ['WHERE 过滤明细行，HAVING 过滤分组聚合后的组', 'HAVING 先于 WHERE 执行', 'HAVING 用来连接两张表'], 0, 'HAVING 只在 GROUP BY 聚合之后筛选组结果，不替代 WHERE，也不是 JOIN。'),
    exercise('w4d2-proof-boundary', ['证据判断', '工作场景'], ['aggregation-logic-map'], '哪条 W4D2 结论最合适？', ['本地教学样本中可以复核聚合顺序，但不能证明真实生产指标、JOIN、归因或 W4D3 已完成', '0.4000 已经证明运营效果', 'GROUP BY 已经证明原因'], 0, 'W4D2 的证据只停在本地教学聚合逻辑和边界说明。'),
  ],
  deliverable: {
    title: '聚合逻辑图',
    conceptIds: [...conceptIds],
    purpose: '把 W4D1 指标口径如何进入 COUNT、DISTINCT、SUM、AVG、GROUP BY 和 HAVING 写成可复核记录。',
    whenToUse: '当你需要向数据同事或未来的自己解释“这个指标数字从哪些行和函数来”时使用。',
    audience: '未来继续学习 W4D3 的自己、数据同事、运营复盘参与者和评审者。',
    fields: [
      { name: 'aggregation_id', meaning: '本条聚合逻辑编号。', source: '实验路径编号' },
      { name: 'metric_ref', meaning: '引用 W4D1 的 metric_id 或口径。', source: 'metric-contract-table.md' },
      { name: 'business_question', meaning: '本条数字要回答的问题。', source: 'W4D2 聚合场景' },
      { name: 'input_rows', meaning: '进入聚合前的事件行集合。', source: 'WHERE/口径' },
      { name: 'where_rule', meaning: '明细行过滤规则。', source: '教学 SQL 规则' },
      { name: 'aggregate_function', meaning: 'COUNT、DISTINCT、SUM 或 AVG。', source: '聚合函数' },
      { name: 'distinct_key', meaning: '按哪个字段去重；无则写不适用。', source: '指标粒度' },
      { name: 'group_key', meaning: 'GROUP BY 字段；无分组则写不适用。', source: '分组逻辑' },
      { name: 'having_rule', meaning: '组级过滤规则；无则写不适用。', source: 'HAVING' },
      { name: 'result_value', meaning: '本地教学表计算结果。', source: '本地结果观察器' },
      { name: 'edge_case', meaning: 'U03、O05、TEST、O06 等边界样本。', source: '实验观察' },
      { name: 'can_prove', meaning: '这条聚合在本地教学中能证明什么。', source: '证据边界' },
      { name: 'cannot_prove', meaning: '不能证明真实生产、JOIN、归因、趋势或 W4D3 完成。', source: '证据边界' },
      { name: 'next_sql_task', meaning: '下一步只指向 W4D3 指标计算 SQL。', source: '课程边界' },
    ],
    badExample: 'aggregation_id: A1\nbusiness_question: 看转化率\nsql: SELECT COUNT(*) FROM events;\nresult_value: 27，所以支付转化率已经证明，运营策略有问题。',
    badReasons: ['没有引用 W4D1 口径。', '没有 input_rows、where_rule、去重键或时间窗口。', 'COUNT(*) 把所有事件和 TEST 混在一起。', '把教学样本越界成真实业务结论。'],
    revisionSteps: ['补 metric_ref 和 business_question。', '先写 input_rows 与 where_rule。', '选择 COUNT(DISTINCT user_id) 或 COUNT(DISTINCT order_id)。', '补 GROUP BY/HAVING 是否适用。', '写 edge_case 和 cannot_prove。', 'next_sql_task 只指向 W4D3。'],
    goodExample: 'aggregation-logic.md\n\naggregation_id: A3-exposure-to-pay\nmetric_ref: app_exposure_to_pay_rate / W4D1 metric-contract-table.md\nbusiness_question: 2026-09-07 教学样本中，非测试曝光用户有多少在自然日内支付\ninput_rows: events 中 is_test=0 的 coupon_exposure 与自然日 payment_success 用户集合\nwhere_rule: event_name IN ("coupon_exposure","payment_success") AND is_test=0 AND event_time >= "2026-09-07 00:00:00" AND event_time < "2026-09-08 00:00:00"\naggregate_function: COUNT(DISTINCT user_id) 后做分子/分母除法\ndistinct_key: user_id\ngroup_key: 不适用\nhaving_rule: 不适用\nresult_value: exposed_users=10; paid_same_day_users=4; exposure_to_pay=0.4000\nedge_case: TEST 被排除；U03 支付在 2026-09-08 11:00，不计入自然日支付\ncan_prove: 能证明本地教学 events 表按该口径可得到 0.4000，也能把 W3D6 业务查询集中的结算到支付样本继续交给 W4D3\ncannot_prove: 不能证明真实生产转化率、原因、趋势、JOIN 对账、看板可发布或 W4D3 已完成\nnext_sql_task: W4D3 再把多条聚合逻辑整理成指标计算 SQL\n',
    guidedPrompts: ['写 A1 exposed_users。', '写 A2 paid_same_day_users。', '写 A3 exposure_to_pay。', '写 A4 checkout_to_pay_24h。', '写 A5 unique_paid_orders。', '写 A6 average_vs_median。'],
    blankTemplate: 'aggregation-logic.md\n\naggregation_id: \nmetric_ref: \nbusiness_question: \ninput_rows: \nwhere_rule: \naggregate_function: \ndistinct_key: \ngroup_key: \nhaving_rule: \nresult_value: \nedge_case: \ncan_prove: \ncannot_prove: \nnext_sql_task: \n',
    standardTemplate: 'aggregation-logic.md\n\naggregation_id: A1-exposed-users\nmetric_ref: app_exposure_to_pay_rate / W4D1\nbusiness_question: 统计非测试优惠券曝光用户数\ninput_rows: events WHERE event_name="coupon_exposure" AND is_test=0\nwhere_rule: event_name="coupon_exposure" AND is_test=0\naggregate_function: COUNT(DISTINCT user_id)\ndistinct_key: user_id\ngroup_key: 不适用\nhaving_rule: 不适用\nresult_value: exposed_users=10\nedge_case: TEST 曝光被排除\ncan_prove: 能证明本地教学表按该口径有 10 个曝光用户，并把这条 W3D6 口径交给 W4D3 继续看 COUNT、DISTINCT、GROUP BY\ncannot_prove: 不能证明真实生产曝光、转化原因、趋势、JOIN、看板可发布或 W4D3 已完成\nnext_sql_task: W4D3 指标计算 SQL\n\naggregation_id: A6-average-vs-median\nmetric_ref: paid_amount_summary / W4D1\nbusiness_question: 支付金额平均值是否能代表典型订单\ninput_rows: 非测试 payment_success 按 order_id 去重后的订单\nwhere_rule: event_name="payment_success" AND is_test=0; GROUP BY order_id\naggregate_function: AVG(amount) + 中位数对照\ndistinct_key: order_id\ngroup_key: 不适用\nhaving_rule: 不适用\nresult_value: unique_paid_orders=5; average_amount=2077.00; median_amount=89.00; max_amount=9999.00\nedge_case: O05 重复支付事件去重；O06 9999 元拉高均值\ncan_prove: 能证明本地教学样本中平均值受异常大单影响，并可回看 W3D6 的支付订单样本\ncannot_prove: 不能证明真实客单价、异常根因、运营效果、JOIN、趋势或 W4D3 已完成\nnext_sql_task: W4D3 指标计算 SQL\n',
    checklist: ['至少写 6 条聚合逻辑记录。', '每条都有 input_rows、where_rule、aggregate_function、distinct_key、group_key、having_rule 和 result_value。', 'COUNT、COUNT(DISTINCT)、SUM 或 AVG、GROUP BY、HAVING 至少各出现一次。', 'U03、O05、TEST、O06 四类边界至少各解释一次。', 'cannot_prove 明确排除真实生产、JOIN、归因、趋势、看板发布或 W4D3 已完成。', 'next_sql_task 只指向 W4D3。'],
  },
  memory: {
    conceptIds: [...conceptIds],
    anchors: ['先 WHERE 固定输入行，再聚合。', 'COUNT 不等于 DISTINCT。', 'SUM 是总量，AVG 会被异常值拉动。', 'GROUP BY 分桶，HAVING 过滤组。'],
    closedBookPrompt: '闭卷画出 W4D2 聚合顺序：口径表 → 输入行 → 聚合函数 → GROUP BY → HAVING → 结果边界。',
    microOperation: '不看答案，写一条 COUNT(DISTINCT user_id) 的输入行、去重键、结果和 cannot_prove。',
    unresolvedPrompt: '写出你进入 W4D3 前最担心的一个聚合误读：输入行、去重键、滚动 24 小时、异常值还是 HAVING？准备怎样检查？',
    reviewStages: [
      { stage: 'D1', task: '闭卷解释 COUNT(*)、COUNT(column) 和 COUNT(DISTINCT key) 的区别。' },
      { stage: 'D3', task: '重新说明 U03 为什么不进入结算后 24 小时集合。' },
      { stage: 'D7', task: '写出 AVG 被 O06 9999 元影响时，为什么要看中位数和样本。' },
      { stage: 'D14', task: '不看模板，画出 GROUP BY 与 HAVING 的顺序。' },
      { stage: 'D30', task: '把一条 W4D1 口径改写成 W4D2 聚合逻辑图。' },
      { stage: 'D60', task: '说明 W4D2 与 W4D3 的边界：聚合逻辑图 vs 完整指标计算 SQL。' },
    ],
  },
  nextLesson: { id: 'W4D3', title: '活跃、转化与客单价', bridge: '下一课才把多条聚合逻辑整理成完整指标计算 SQL；W4D2 只首教聚合函数、分组顺序和教学样本边界。' },
}
