import type { DailyCourse, Exercise } from './types'

const conceptIds = [
  'metric-sql-base-cte',
  'active-user-sql',
  'same-day-conversion-sql',
  'rolling-window-conversion-sql',
  'unique-paid-order-sql',
  'aov-sql',
  'median-outlier-guard-sql',
  'metric-calculation-note',
] as const

const prerequisiteConceptIds = [
  'query-question',
  'where-condition',
  'date-range-boundary',
  'distinct-result',
  'null-value',
  'duplicate-row',
  'test-data-flag',
  'quality-evidence-boundary',
  'business-query-set',
  'quality-flagged-answer',
  'metric-decision-purpose',
  'metric-signal',
  'metric-numerator',
  'metric-denominator',
  'metric-grain',
  'metric-time-window',
  'metric-exclusion-rule',
  'metric-contract-table',
  'aggregation-input-set',
  'count-aggregate',
  'distinct-aggregate',
  'sum-aggregate',
  'avg-aggregate',
  'group-by-bucket',
  'having-group-filter',
  'aggregation-logic-map',
] as const

function exercise(
  id: string,
  categories: Exercise['categories'],
  ids: string[],
  prompt: string,
  options: string[],
  answerIndex: number,
  referenceAnswer: string,
): Exercise {
  return {
    id,
    kind: 'single-choice',
    categories,
    conceptIds: ids,
    prompt,
    hint: '先看 metric_ref 和 base CTE，再检查活跃、转化、支付订单、AOV 是否各自使用正确分母、去重键、时间窗口和边界说明。',
    options: options.map((label, index) => ({
      label,
      rationale: index === answerIndex ? '这项把 W4D1 口径、W4D2 聚合逻辑和 W4D3 的指标 SQL 输出连起来。' : '这项要么缺少分母或去重键，要么把教学结果越界说成真实生产结论。',
      couldBeTrueWhen: index === answerIndex ? '当学习者正在写 metric-calculation.md。' : '只有后续 W4D4-W5D6 补充分布误导、评审和 JOIN 对账后，才可能支撑更强判断。',
    })),
    answerIndex,
    referenceAnswer,
    reasoning: [
      'W4D3 不再只画聚合逻辑，而是把同一批 W4 events 教学数据写成可执行指标 SQL 记录。',
      '活跃用户、自然日转化、滚动 24 小时转化、唯一支付订单和 AOV 必须分别保留分母、分子、去重键和边界样本。',
      '本日仍是本地教学模拟，不连接真实数据库，不发布看板，不证明真实生产指标正确。',
    ],
    rubric: ['metric_ref 清楚', '分母分子不混', '去重键和窗口明确', '结果边界不过界'],
    commonErrors: [
      { error: '用 payment_success 人数当活跃用户', reason: '活跃用户要先定义活动事件集合；支付只是活跃集合中的一个行为。' },
      { error: '只写 AVG(amount) 就说客单价上涨', reason: 'AOV 必须先按 order_id 去重，并对照 O06 异常大单和中位数。' },
    ],
    remediation: { label: '回看指标计算 SQL 字段', sectionId: 'deliverable', anchor: 'w4d3-metric-calculation-fields' },
  }
}

export const w4d3: DailyCourse = {
  id: 'W4D3',
  contentVersion: 'w4d3-metric-calculation-day01-v1',
  week: 4,
  day: 3,
  title: '活跃、转化与客单价',
  subtitle: '用 W4 本地 events 教学表写出活跃用户、曝光到支付转化率、结算后 24 小时转化率、唯一支付订单和 AOV 的指标计算 SQL；本日只证明本地教学口径可复核，不做 JOIN、趋势或看板发布。',
  duration: { core: 30, standard: 45, extension: 82, full: 132 },
  coreConceptGroups: [
    {
      id: 'metric-sql-base-layer',
      title: '先用 CTE 固定同一批教学输入',
      conceptIds: ['metric-sql-base-cte', 'active-user-sql'],
      summary: 'base CTE 把 is_test=0、事件日期和活动事件集合统一起来，活跃用户只从这批可复核输入中计数。',
      boundary: '能计算教学表的 active_users；不能证明真实 DAU、真实埋点覆盖或产品使用质量。',
    },
    {
      id: 'conversion-sql-layer',
      title: '转化率同时写分母、分子和窗口',
      conceptIds: ['same-day-conversion-sql', 'rolling-window-conversion-sql'],
      summary: '自然日转化按统一日期边界，滚动 24 小时从每个 checkout_view 的发生时刻起算；U03 是窗口差异的关键样本。',
      boundary: '能解释 exposure_to_pay=0.4000 与 checkout_to_pay_24h=0.5714；不能证明原因、归因或趋势。',
    },
    {
      id: 'amount-sql-layer',
      title: '客单价先去重，再看均值护栏',
      conceptIds: ['unique-paid-order-sql', 'aov-sql', 'median-outlier-guard-sql', 'metric-calculation-note'],
      summary: '支付订单先按 order_id 去重，再计算总额、AOV、中位数和最大值，最后写入可交接的 metric-calculation.md。',
      boundary: '能看见 O05 重复和 O06 9999 元如何影响结果；不能完成 W4D4 的三种上涨假象分析。',
    },
  ],
  prerequisiteConceptIds: [...prerequisiteConceptIds],
  learningPaths: {
    '30': {
      guidedStepIndices: [0, 1, 2, 3, 4, 5],
      guidedRecordIndices: [0, 1, 2, 3, 4, 5],
      exerciseCount: 3,
      deliverablePromptCount: 6,
      deliverableChecklistIndices: [0, 1, 2, 3, 4],
      deliverableMinimumContributionCharacters: 280,
    },
    '45': {
      guidedStepIndices: [0, 1, 2, 3, 4, 5],
      guidedRecordIndices: [0, 1, 2, 3, 4, 5],
      exerciseCount: 4,
      deliverablePromptCount: 6,
      deliverableChecklistIndices: [0, 1, 2, 3, 4, 5],
      deliverableMinimumContributionCharacters: 400,
    },
  },
  primaryGoal: '提交 `metric-calculation.md`：至少写出 active_users、exposure_to_pay、checkout_to_pay_24h、unique_paid_orders、total_amount、aov_amount、median_amount、max_amount，并为每个结果保留 metric_ref、sql_snippet、result_value、sample_check、can_prove、cannot_prove 和 next_review_task。',
  scenario: {
    role: '你是刚完成 W4D2 聚合逻辑图的产品经理。',
    situation: '运营同学要在周会上看“活跃、转化与客单价”。你已经有 W4D1 口径表和 W4D2 聚合顺序，现在必须把它们落成可执行 SQL 输出，并明确每个数字的分母、去重键、窗口和边界样本。',
    question: '怎样把同一张 events 教学表算成一组可复核指标，而不是一串互相不能比较的数字？',
    stakes: '如果 SQL 没有共同 base CTE，活跃用户会混入测试事件；如果转化率混用自然日和 24 小时窗口，U03 会改变结论；如果 AOV 不先按订单去重，O05 和 O06 会让客单价解释失真。',
  },
  objectives: [
    { id: 'w4d3-objective-base', text: '能用 base CTE 固定本次指标计算输入', evidence: '`metric-calculation.md` 写出 base_events、is_test=0、event_time 日期边界和活动事件集合。' },
    { id: 'w4d3-objective-conversion', text: '能分别计算自然日转化率和滚动 24 小时转化率', evidence: '成果中同时出现 exposed_users=10、paid_same_day_users=4、checkout_users=7、paid_within_24h_users=4、0.4000 和 0.5714。' },
    { id: 'w4d3-objective-aov', text: '能先按 order_id 去重再计算 AOV 与护栏', evidence: '成果写出 unique_paid_orders=5、total_amount=10385.00、aov_amount=2077.00、median_amount=89.00、max_amount=9999.00。' },
    { id: 'w4d3-objective-boundary', text: '能说明本地指标 SQL 的证据边界', evidence: 'cannot_prove 明确排除真实生产指标、JOIN、归因、趋势、看板发布和 W4D4 误导分析已完成。' },
  ],
  prerequisites: [
    {
      id: 'w4d3-w4d2-readiness',
      conceptIds: [...prerequisiteConceptIds],
      prompt: '你是否能把 W3 查询、W4D1 口径表和 W4D2 聚合逻辑串起来：先固定输入行，再选择 COUNT/DISTINCT/SUM/AVG/GROUP BY/HAVING，最后才写指标 SQL 输出？',
      passDescription: '能说明 W4D3 承接 W4D2，不重新首教聚合函数，而是把活跃、转化和 AOV 写成完整 SQL 结果记录。',
      remediationLabel: '回到 W4D2 补聚合逻辑图',
      remediationTarget: '#/lesson/W4D2',
      remediation: {
        purpose: 'W4D3 可提前阅读；但没有 W4D2 的聚合顺序，指标 SQL 会变成背公式，无法解释分母、去重键和窗口。',
        steps: ['补齐 W4D2 aggregation-logic.md 中 input_rows、aggregate_function、distinct_key、group_key 和 having_rule。', '复述 TEST、O05、O06、U03 分别会影响哪类计算。', '写一句“W4D3 只计算本地教学指标，不证明真实生产看板可发布”。'],
        successCheck: '能把“活跃用户、转化率、支付订单数、AOV”拆成同一张 events 表上的可复核 SQL 输出。',
      },
    },
  ],
  concepts: [
    {
      id: 'metric-sql-base-cte',
      prerequisiteConceptIds: ['aggregation-input-set', 'metric-time-window', 'metric-exclusion-rule'],
      term: '指标 SQL 基础 CTE',
      english: 'Metric SQL Base CTE',
      definition: '指标 SQL 基础 CTE 是在正式计算前先命名的一层公共输入，把测试数据排除、时间窗口和必要字段统一固定。',
      why: '同一份周报里的活跃、转化和金额指标必须站在同一批教学输入上，否则每个数字都可能使用不同边界。',
      problemSolved: '回答“这些指标是不是从同一个可复核数据底座算出来”。',
      input: 'events 表、is_test、event_time、event_name、user_id、order_id 和 amount。',
      output: 'base_events 或 filtered_events 这样的可复用 CTE。',
      systemPosition: '位于 SELECT 指标列之前，是 W4D3 全部指标计算的共同入口。',
      process: ['先写 WITH base_events AS (...)。', '在 CTE 内排除 is_test=1。', '保留后续指标都要用到的字段和时间边界。'],
      owner: '产品经理确认口径一致，SQL 执行器按 CTE 固定输入。',
      notResponsibleFor: '不负责跨表补字段、JOIN 对账或证明真实埋点完整。',
      compareWith: 'W4D2 的 input_rows 是单条聚合的输入；base CTE 是多条指标共用的输入层。',
      evidence: ['WITH base_events AS (...)。', 'is_test=0。', 'event_time >= 2026-09-07。'],
      failureModes: ['每个指标各写一套 WHERE，边界不一致。', '忘记排除 TEST 事件。'],
      pmUse: '在交给数据同事前先标明：本组指标都来自非测试 W4 events 教学样本。',
      correctExample: 'WITH base_events AS (SELECT * FROM events WHERE is_test=0)。',
      incorrectExample: '每个 SELECT 随手写 WHERE，算完再解释。',
    },
    {
      id: 'active-user-sql',
      prerequisiteConceptIds: ['metric-sql-base-cte', 'distinct-aggregate'],
      term: '活跃用户 SQL',
      english: 'Active User SQL',
      definition: '活跃用户 SQL 是按已定义活动事件集合统计唯一 user_id 的查询，本课使用 coupon_exposure、checkout_view、payment_success 作为教学活动事件。',
      why: '活跃不是“任意一行事件”，必须先定义哪些行为代表用户在本场景中活跃，再用 DISTINCT 保护用户粒度。',
      problemSolved: '回答“教学样本里当天参与漏斗的唯一用户有多少”。',
      input: 'base_events 中的活动事件名、user_id 和自然日边界。',
      output: 'active_users 指标列。',
      systemPosition: '位于指标输出的规模基线层，后续转化率解释需要先知道样本规模。',
      process: ['定义活动事件集合。', '排除测试事件。', 'COUNT(DISTINCT user_id) 输出 active_users。'],
      owner: '产品经理定义活动事件，SQL 负责去重计数。',
      notResponsibleFor: '不负责证明真实 DAU、访问质量或埋点覆盖率。',
      compareWith: '曝光用户是分母指标；活跃用户是更宽的参与样本基线。',
      evidence: ['COUNT(DISTINCT user_id)。', 'event_name IN (...)。', 'active_users=10。'],
      failureModes: ['把 payment_success 用户当全部活跃。', '把 TEST 用户计入活跃。'],
      pmUse: '周报先写“教学 active_users=10，来自三类漏斗事件”，再解释转化率。',
      correctExample: 'COUNT(DISTINCT CASE WHEN event_name IN ("coupon_exposure","checkout_view","payment_success") THEN user_id END) AS active_users。',
      incorrectExample: 'SELECT COUNT(*) FROM events 就是活跃人数。',
    },
    {
      id: 'same-day-conversion-sql',
      prerequisiteConceptIds: ['metric-sql-base-cte', 'metric-denominator', 'metric-numerator'],
      term: '自然日转化率 SQL',
      english: 'Same-day Conversion SQL',
      definition: '自然日转化率 SQL 是在同一日期边界内分别统计分母用户和分子用户，再用分子除以分母。',
      why: '转化率必须同时看到 exposed_users 和 paid_same_day_users，只有一个支付人数不能叫转化率。',
      problemSolved: '回答“2026-09-07 教学样本中曝光用户有多少当天支付”。',
      input: 'coupon_exposure 用户集合、自然日 payment_success 用户集合和 user_id 去重键。',
      output: 'exposure_to_pay=0.4000。',
      systemPosition: '位于漏斗指标输出层，承接 W4D1 的分子分母口径。',
      process: ['计算 exposed_users。', '计算同一自然日 paid_same_day_users。', '用 NULLIF 防止分母为 0 后做除法。'],
      owner: '产品经理确认自然日口径；SQL 负责条件计数和除法。',
      notResponsibleFor: '不负责解释为什么转化高低或证明运营策略效果。',
      compareWith: 'W4D2 解释 COUNT/DISTINCT；W4D3 把两个计数组合成命名转化率。',
      evidence: ['exposed_users=10。', 'paid_same_day_users=4。', 'ROUND(...,4)=0.4000。'],
      failureModes: ['只给 0.4000，不给分子分母。', '把次日支付也塞进自然日分子。'],
      pmUse: '在周报中把“40%”写成 exposed_users=10、paid_same_day_users=4、口径为自然日。',
      correctExample: 'ROUND(1.0 * paid_same_day_users / NULLIF(exposed_users,0), 4) AS exposure_to_pay。',
      incorrectExample: '支付用户 4 人，所以转化率是 4。',
    },
    {
      id: 'rolling-window-conversion-sql',
      prerequisiteConceptIds: ['same-day-conversion-sql', 'metric-time-window'],
      term: '滚动窗口转化 SQL',
      english: 'Rolling-window Conversion SQL',
      definition: '滚动窗口转化 SQL 从每个用户自己的 checkout_view 时刻向后计算 24 小时，而不是统一截到次日午夜。',
      why: 'U03 在 2026-09-07 10:01 看结算页，2026-09-08 11:00 才支付，超过 24 小时 59 分钟，不能进入 24 小时分子。',
      problemSolved: '回答“结算后 24 小时内支付”与自然日支付为什么可能不同。',
      input: 'checkout_view 用户、payment_success 用户、同一 user_id 和 datetime(checkout_time, "+24 hours")。',
      output: 'checkout_to_pay_24h=0.5714。',
      systemPosition: '位于转化指标的时间窗口层，用来暴露窗口定义对结果的影响。',
      process: ['提取 checkouts CTE。', '提取 payments CTE。', '按 user_id 匹配并限定 payment_time < checkout_time + 24 hours。'],
      owner: '产品经理解释窗口含义；SQL 负责时间比较。',
      notResponsibleFor: '不负责证明生产时区、埋点延迟或跨设备归因已经处理。',
      compareWith: '自然日窗口共享一个日期边界；滚动窗口给每个用户单独起算。',
      evidence: ['checkout_users=7。', 'paid_within_24h_users=4。', 'U03 不计入。'],
      failureModes: ['把 24 小时写成次日 23:59:59。', '忘记 payment_time 必须晚于 checkout_time。'],
      pmUse: '当周报出现两个转化率时，先说明一个是自然日，一个是结算后 24 小时。',
      correctExample: 'p.payment_time < datetime(c.checkout_time, "+24 hours")。',
      incorrectExample: '只要第二天支付都算 24 小时内。',
    },
    {
      id: 'unique-paid-order-sql',
      prerequisiteConceptIds: ['distinct-aggregate', 'metric-grain'],
      term: '唯一支付订单 SQL',
      english: 'Unique Paid Order SQL',
      definition: '唯一支付订单 SQL 是对 payment_success 先按 order_id 去重，再统计订单数量的查询。',
      why: 'O05 同一订单有 E13/E14 两条支付成功事件，直接 COUNT(*) 会把一单算成两单。',
      problemSolved: '回答“非测试支付成功里到底有几笔唯一订单”。',
      input: 'base_events 中 event_name=payment_success 的 order_id 和 amount。',
      output: 'unique_paid_orders=5。',
      systemPosition: '位于金额指标计算之前，是 AOV 的分母基础。',
      process: ['筛出 payment_success。', '排除测试事件。', 'GROUP BY order_id 或 COUNT(DISTINCT order_id)。'],
      owner: '产品经理确认订单粒度；SQL 执行去重。',
      notResponsibleFor: '不负责修复重复埋点或判定生产订单状态最终正确。',
      compareWith: '支付事件数会受重复事件影响；唯一支付订单数按 order_id 保护粒度。',
      evidence: ['O05 只计一次。', 'unique_paid_orders=5。', 'is_test=0。'],
      failureModes: ['COUNT(*) 把 E13/E14 算成两笔订单。', '按 user_id 去重却解释成订单数。'],
      pmUse: '讨论 AOV 前先问“支付订单是否已按 order_id 去重”。',
      correctExample: 'SELECT order_id, MAX(amount) AS amount FROM base_events WHERE event_name="payment_success" GROUP BY order_id。',
      incorrectExample: 'COUNT(*) AS paid_orders FROM payment_success。',
    },
    {
      id: 'aov-sql',
      prerequisiteConceptIds: ['unique-paid-order-sql', 'sum-aggregate', 'avg-aggregate'],
      term: '客单价 SQL',
      english: 'AOV SQL',
      definition: '客单价 SQL 是在唯一支付订单集合上计算总支付金额除以订单数，通常可用 AVG(amount) 表达教学样本的平均订单金额。',
      why: 'AOV 的分母是订单，不是用户或支付事件；分母错了，客单价会被解释成另一个指标。',
      problemSolved: '回答“教学样本中每笔唯一支付订单平均金额是多少”。',
      input: 'w4_unique_paid_orders 里的 order_id 与 amount。',
      output: 'total_amount=10385.00 与 aov_amount=2077.00。',
      systemPosition: '位于金额指标输出层，依赖唯一支付订单集合。',
      process: ['先获得去重订单集合。', 'SUM(amount) 计算总额。', 'AVG(amount) 或 SUM/COUNT 计算 AOV。'],
      owner: 'SQL 计算金额，产品经理解释分母和异常值限制。',
      notResponsibleFor: '不负责证明真实 GMV、收入入账或用户价值提升。',
      compareWith: 'SUM 是总额；AOV 是每笔唯一订单的平均金额。',
      evidence: ['unique_paid_orders=5。', 'total_amount=10385.00。', 'aov_amount=2077.00。'],
      failureModes: ['把支付事件数当 AOV 分母。', '没有说明是否排除测试订单。'],
      pmUse: '写“教学 AOV=2077，但必须看中位数和最大值后再解释”。',
      correctExample: 'ROUND(AVG(amount), 2) AS aov_amount FROM w4_unique_paid_orders。',
      incorrectExample: '直接 SUM(amount) 就是客单价。',
    },
    {
      id: 'median-outlier-guard-sql',
      prerequisiteConceptIds: ['aov-sql'],
      term: '中位数与异常值护栏 SQL',
      english: 'Median and Outlier Guard',
      definition: '中位数与异常值护栏 SQL 是在 AOV 旁边同时输出 median_amount、min_amount 和 max_amount，帮助识别平均值是否被极端订单拉动。',
      why: 'O06 的 9999 元会把平均值拉到 2077，而排序中间的订单金额只有 89；只看均值会误导产品判断。',
      problemSolved: '回答“2077 是否能代表典型订单”。',
      input: '按 amount 排序的唯一支付订单集合。',
      output: 'median_amount=89.00、max_amount=9999.00 和中位数附近样本。',
      systemPosition: '位于 AOV 输出之后，是进入 W4D4 误导分析前的最小护栏。',
      process: ['用 ROW_NUMBER 给订单金额排序。', '取中间位次得到 median_amount。', '同时输出 max_amount 和附近样本。'],
      owner: '产品经理要求护栏列；SQL 负责排序和取样。',
      notResponsibleFor: '不负责完整分布分析、幸存者偏差或上涨假象诊断。',
      compareWith: 'AOV 给平均水平；中位数和最大值提醒平均值是否失真。',
      evidence: ['median_amount=89.00。', 'max_amount=9999.00。', 'O06 异常大单。'],
      failureModes: ['看到 AOV 上升就说业务变好。', '没有展示中位数附近样本。'],
      pmUse: '对运营说“平均值很高，但典型订单不高，下一课再分析上涨假象”。',
      correctExample: '输出 average_amount、median_amount、max_amount 三列一起解读。',
      incorrectExample: 'AOV=2077，所以典型订单就是 2077。',
    },
    {
      id: 'metric-calculation-note',
      prerequisiteConceptIds: ['median-outlier-guard-sql'],
      term: '指标计算记录',
      english: 'Metric Calculation Note',
      definition: '指标计算记录是把每个指标的口径引用、SQL 片段、结果值、样本核对和证据边界写进同一份 metric-calculation.md。',
      why: '只有 SQL 没有记录，别人无法判断分母、时间窗口、去重键和异常样本是否符合口径。',
      problemSolved: '回答“这组指标计算如何被产品、数据和未来的自己复核”。',
      input: 'W4D1 口径、W4D2 聚合逻辑、W4D3 SQL 输出和边界样本。',
      output: 'metric-calculation.md。',
      systemPosition: '位于 W4D3 成果层，交给 W4D4 继续分析上涨假象。',
      process: ['逐项写 metric_name、metric_ref 和 sql_snippet。', '写 result_value 与 sample_check。', '写 can_prove、cannot_prove 和 next_review_task。'],
      owner: '产品经理负责交接说明，数据同事可复核 SQL。',
      notResponsibleFor: '不负责真实生产发布、JOIN 对账、归因或趋势解释。',
      compareWith: 'aggregation-logic.md 解释函数顺序；metric-calculation.md 交付可复核指标输出。',
      evidence: ['metric-calculation.md。', 'sql_snippet。', 'sample_check。', 'cannot_prove。'],
      failureModes: ['只贴 SQL，不写口径引用。', '只贴结果，不写样本核对和不能证明事项。'],
      pmUse: '把 active_users、转化率和 AOV 放在一份记录里，附上 TEST、U03、O05、O06 的边界说明。',
      correctExample: 'next_review_task: W4D4 检查分母变化、幸存者偏差和异常大单造成的上涨假象。',
      incorrectExample: '指标 SQL 跑通，所以看板可以发布。',
    },
  ],
  diagram: {
    title: '指标 SQL 从公共输入到周会数字的路径',
    caption: 'W4D3 的链路是：W4D1 口径 → W4D2 聚合逻辑 → base CTE → 活跃用户 → 转化率 → 唯一支付订单 → AOV 与护栏 → metric-calculation.md → W4D4 误导分析。',
    nodes: [
      { id: 'contract', label: 'W4D1 口径引用', description: '每个指标先指向口径表中的分子、分母、粒度、窗口和排除规则。', input: 'metric-contract-table.md', output: 'metric_ref', owner: '产品经理' },
      { id: 'base', label: 'base_events CTE', description: '统一排除 TEST，保留事件、用户、订单、金额和时间。', input: 'events', output: 'filtered rows', owner: 'SQL 查询', evidence: 'is_test=0' },
      { id: 'activity', label: '活跃用户', description: '从活动事件集合中按 user_id 去重。', input: 'base_events', output: 'active_users=10', owner: '数据库执行器' },
      { id: 'conversion', label: '转化率指标', description: '分别输出自然日和滚动 24 小时的分母、分子和比率。', input: 'exposure/checkout/payment', output: '0.4000 / 0.5714', owner: '数据库执行器', evidence: 'U03' },
      { id: 'orders', label: '唯一支付订单', description: '用 order_id 去重后再进入金额计算。', input: 'payment_success', output: 'unique_paid_orders=5', owner: '数据库执行器', evidence: 'O05' },
      { id: 'amount', label: 'AOV 与护栏', description: '同时输出总额、均值、中位数和最大值。', input: 'unique orders', output: '2077 / 89 / 9999', owner: '数据库执行器', evidence: 'O06' },
      { id: 'note', label: '指标计算记录', description: '写清 SQL、结果、样本核对、能证明和不能证明。', input: 'metric outputs', output: 'metric-calculation.md', owner: '产品经理' },
    ],
    branches: [
      { from: 'contract', to: 'base', label: '落成公共输入', kind: 'normal' },
      { from: 'base', to: 'activity', label: '计算规模基线', kind: 'normal' },
      { from: 'base', to: 'conversion', label: '计算分母分子', kind: 'normal' },
      { from: 'base', to: 'orders', label: '保护订单粒度', kind: 'normal' },
      { from: 'orders', to: 'amount', label: '进入金额指标', kind: 'normal' },
      { from: 'amount', to: 'note', label: '交付有限记录', kind: 'normal' },
      { from: 'base', to: 'note', label: '公共输入不一致会让全部指标不可比', kind: 'failure' },
    ],
    evidenceNotes: ['活跃用户必须说明活动事件集合。', '转化率必须同时写分母和分子。', '滚动 24 小时不是次日午夜。', 'AOV 必须先按 order_id 去重，并对照中位数和最大值。'],
  },
  demonstration: {
    title: '教师示范：把 W4 events 算成四类指标输出',
    businessProblem: '运营要看 2026-09-07 教学样本里的活跃、曝光到支付转化、结算后 24 小时转化和客单价。你要写一份可以被数据同事复核的 metric-calculation.md。',
    finalConclusion: '教学表中 active_users=10、exposed_users=10、paid_same_day_users=4、exposure_to_pay=0.4000、checkout_users=7、paid_within_24h_users=4、checkout_to_pay_24h=0.5714、unique_paid_orders=5、aov_amount=2077.00、median_amount=89.00、max_amount=9999.00。',
    conclusionLimit: '这些结果只证明 W4 本地教学表按指定口径可复核；不能证明真实生产指标、原因、趋势、JOIN 对账、看板可发布或 W4D4 误导分析完成。',
    steps: [
      { title: '引用口径与聚合逻辑', action: '先写 metric_ref，标明来自 W4D1 口径表和 W4D2 聚合逻辑图。', reason: '指标 SQL 必须有上游口径和函数选择依据。', evidence: 'metric_ref、aggregation_ref。', proves: '知道本日是在落 SQL 输出。', limitation: '还没有计算任何结果。' },
      { title: '建立 base_events', action: '用 WITH base_events AS (...) 排除 is_test=1，并保留 event_name、event_time、user_id、order_id、amount。', reason: '活跃、转化和金额都要站在同一批输入上。', evidence: 'TEST 被排除。', proves: '公共输入可复核。', limitation: '不能证明生产埋点完整。' },
      { title: '计算活跃用户', action: '在活动事件集合 coupon_exposure、checkout_view、payment_success 中 COUNT(DISTINCT user_id)。', reason: '活跃必须按用户粒度去重。', evidence: 'active_users=10。', proves: '教学样本参与漏斗用户规模。', limitation: '不能证明真实 DAU。' },
      { title: '计算两种转化率', action: '分别计算自然日曝光到支付和结算后 24 小时支付。', reason: '两个窗口含义不同，U03 会暴露差异。', evidence: '0.4000 与 0.5714；U03 不进入 24 小时分子。', proves: '窗口变化会改变指标解释。', limitation: '不能证明转化原因。' },
      { title: '计算唯一支付订单', action: '从 payment_success 中按 order_id 去重，O05 只计一次。', reason: 'AOV 分母必须是唯一订单，不是支付事件。', evidence: 'unique_paid_orders=5。', proves: '订单粒度被保护。', limitation: '不能修复重复事件根因。' },
      { title: '输出 AOV 和护栏', action: '计算 total_amount、aov_amount、median_amount、max_amount，并标记 O06。', reason: 'O06 9999 元会拉高均值，需要护栏防止误读。', evidence: 'total_amount=10385.00; aov_amount=2077.00; median_amount=89.00; max_amount=9999.00。', proves: '平均值需要分布线索辅助解释。', limitation: '不替代 W4D4 上涨假象分析。' },
    ],
  },
  guidedLab: {
    title: '指标计算台：同一数据集的六个 SQL 输出',
    goal: '用 W4 events 教学表依次跑出 active_users、两种转化率、唯一支付订单、AOV 与中位数护栏，并把每个结果写进 metric-calculation.md。',
    safety: '这是本地教学模拟，不连接真实数据库、不读取公司数据、不生成生产看板。',
    conceptIds: [...conceptIds],
    predictionPrompt: '如果 O05 有两条 payment_success，U03 超过结算后 24 小时才支付，O06 金额为 9999，你预测活跃、转化和 AOV 哪些会受影响？先写理由。',
    steps: [
      { title: 'base-events-cte', action: '写 base_events，统一排除 TEST 并保留事件字段。', observe: '后续指标共用同一批非测试事件。', explanation: '公共 CTE 让多指标结果可比较。', proves: '能固定本地教学输入。', cannotProve: '不能证明真实埋点覆盖。' },
      { title: 'active-users', action: '按活动事件集合统计 COUNT(DISTINCT user_id)。', observe: 'active_users=10。', explanation: '本教学表所有非测试用户至少有一次漏斗活动。', proves: '能计算教学活跃用户。', cannotProve: '不能证明真实 DAU。' },
      { title: 'same-day-conversion', action: '统计 exposed_users、paid_same_day_users 和 exposure_to_pay。', observe: '10、4、0.4000。', explanation: '自然日口径使用同一日期边界。', proves: '能计算自然日转化。', cannotProve: '不能证明原因或趋势。' },
      { title: 'rolling-24h-conversion', action: '从 checkout_view 向后匹配 24 小时内 payment_success。', observe: 'checkout_users=7、paid_within_24h_users=4、checkout_to_pay_24h=0.5714，U03 不计入。', explanation: '24 小时窗口由每个用户自己的 checkout_time 起算。', proves: '能区分窗口口径。', cannotProve: '不能证明生产时区规则已批准。' },
      { title: 'unique-paid-orders', action: '按 order_id 去重 payment_success，再统计订单数。', observe: 'unique_paid_orders=5，O05 只算一单。', explanation: '订单指标不能被重复事件放大。', proves: '能保护订单粒度。', cannotProve: '不能修复重复事件。' },
      { title: 'aov-and-guards', action: '计算 total_amount、aov_amount、median_amount 和 max_amount。', observe: '10385.00、2077.00、89.00、9999.00。', explanation: 'O06 会拉高均值，必须用中位数和最大值做护栏。', proves: '能识别 AOV 解释风险。', cannotProve: '不能完成 W4D4 的误导案例分析。' },
    ],
    recordPrompts: [
      '记录 base-events-cte：base CTE 过滤了什么，保留了哪些字段。',
      '记录 active-users：活动事件集合、distinct_key 和 active_users。',
      '记录 same-day-conversion：分母、分子、rate 和自然日边界。',
      '记录 rolling-24h-conversion：checkout_users、paid_within_24h_users、U03 为什么不计入。',
      '记录 unique-paid-orders：O05 重复事件如何处理。',
      '记录 aov-and-guards：AOV、中位数、最大值和 O06 的解释限制。',
    ],
    comparePrompt: '对照六条记录，找出哪一个指标最容易因为分母、去重键、窗口或异常值被误读，并写出复核动作。',
    passCriteria: ['六个 SQL 输出都有记录。', 'active_users、exposure_to_pay、checkout_to_pay_24h、unique_paid_orders、aov_amount、median_amount 都出现。', '记录里明确写出 metric_name、metric_ref、aggregation_ref、base_cte、sql_snippet、denominator、numerator、distinct_key、time_window、result_value、sample_check、can_prove、cannot_prove 和 next_review_task。', 'TEST、U03、O05、O06 至少各解释一次。', 'cannot_prove 不宣称真实生产、JOIN、归因、趋势、看板发布或 W4D4 已完成。'],
  },
  independentLab: {
    title: '独立变式：把“结算后 24 小时转化”写成可交接指标记录',
    scenario: '运营只要一个指标：看过结算页的用户，24 小时内有多少完成支付。你要用 W4D3 的 SQL 记录格式，写清分母、分子、时间窗口、U03 边界和结果。',
    conceptIds: ['metric-sql-base-cte', 'rolling-window-conversion-sql', 'same-day-conversion-sql', 'metric-calculation-note'],
    changedConditions: ['分母固定为 checkout_view 用户。', '分子只保留 checkout 后 24 小时内的 payment_success 用户。', 'U03 支付晚于 24 小时 59 分钟，不计入。', '仍排除 TEST，并保留 user_id 去重。'],
    task: '写出 metric_name=checkout_to_pay_24h、metric_ref、sql_snippet、result_value=0.5714、sample_check=U03 excluded、cannot_prove 和 next_review_task=W4D4。',
    predictionPrompt: '你预测 checkout_to_pay_24h 和自然日 checkout_to_pay 是否一定相同？为什么？',
    evidenceRequirements: ['必须写 checkout_users=7。', '必须写 paid_within_24h_users=4。', '必须说明 U03 不计入。', '必须写 result_value=0.5714。', '必须写不能证明真实生产转化率或原因。'],
    passCriteria: ['分母、分子、去重键、窗口和结果齐全。', '没有把滚动 24 小时写成次日午夜。', 'sample_check 至少解释 U03。', '没有提前完成 W4D4、JOIN 或真实看板发布。'],
    remediation: { label: '回看滚动窗口转化 SQL', sectionId: 'concepts', anchor: 'concept-rolling-window-conversion-sql' },
  },
  exercises: [
    exercise('w4d3-active-users', ['概念与边界', '工作场景'], ['metric-sql-base-cte', 'active-user-sql'], '计算本课 active_users 前，最应该先写清什么？', ['活动事件集合、base_events 过滤和 user_id 去重', '只看 payment_success 行', '直接 COUNT(*) FROM events'], 0, '活跃用户要先定义活动事件集合，并在非测试 base_events 上按 user_id 去重。'),
    exercise('w4d3-window-rate', ['机制推演'], ['same-day-conversion-sql', 'rolling-window-conversion-sql'], 'U03 为什么不进入 checkout_to_pay_24h 的分子？', ['U03 从 checkout 到 payment 超过 24 小时 59 分钟', 'U03 没有 coupon_exposure', 'U03 是 TEST 用户'], 0, '滚动 24 小时从每个 checkout_view 起算，U03 支付时间晚于 24 小时窗口。'),
    exercise('w4d3-aov-guard', ['证据判断'], ['unique-paid-order-sql', 'aov-sql', 'median-outlier-guard-sql'], 'AOV=2077.00 时，哪条解释最稳妥？', ['它受 O06 9999 元影响，需同时看 median_amount=89.00 和 max_amount=9999.00', '典型订单就是 2077 元', '已经证明客单价真实上涨'], 0, 'AOV 是平均值，必须和中位数、最大值、样本一起解释。'),
    exercise('w4d3-note-boundary', ['综合变式', '证据判断'], ['metric-calculation-note'], '哪条 metric-calculation.md 结论没有越界？', ['本地教学表可复核该 SQL 输出；不能证明真实生产、JOIN、归因、趋势或 W4D4 已完成', '指标 SQL 跑通，所以看板可发布', 'AOV 高，说明运营策略成功'], 0, 'W4D3 的证据只停在本地教学指标计算和边界记录。'),
    exercise('w4d3-denominator', ['工作场景', '机制推演'], ['same-day-conversion-sql', 'active-user-sql'], '看到“支付人数 4”时，为什么还不能说转化率？', ['还缺分母、窗口和去重口径', '因为必须先 JOIN 用户表', '因为 SQL 不能算比例'], 0, '转化率必须有分母；支付人数只是分子候选集合。'),
  ],
  deliverable: {
    title: '指标计算 SQL',
    conceptIds: [...conceptIds],
    purpose: '把教学模拟中的活跃、转化、支付订单和 AOV 的 SQL 输出写成可复核记录，说明每个数字从哪来、能证明什么、不能证明什么。',
    whenToUse: '当你要把 W4 本地教学指标交给数据同事复核，或在周会前解释一组数字口径时使用。',
    audience: '未来学习 W4D4 的自己、数据同事、运营复盘参与者和指标评审者。',
    fields: [
      { name: 'metric_name', meaning: '本条指标名称，如 active_users、exposure_to_pay、checkout_to_pay_24h、aov_amount。', source: 'W4D3 指标输出' },
      { name: 'metric_ref', meaning: '引用 W4D1 的 metric_id 或口径说明。', source: 'metric-contract-table.md' },
      { name: 'aggregation_ref', meaning: '引用 W4D2 的聚合逻辑编号。', source: 'aggregation-logic.md' },
      { name: 'business_question', meaning: '这条指标回答的业务问题。', source: '运营复盘问题' },
      { name: 'base_cte', meaning: '公共输入 CTE 如何排除 TEST、保留字段和时间。', source: 'base_events SQL' },
      { name: 'sql_snippet', meaning: '本条指标的核心 SQL 片段。', source: 'exercises.sql 或答案对照' },
      { name: 'denominator', meaning: '比例指标的分母；计数或金额指标写不适用并说明。', source: '口径表与 SQL' },
      { name: 'numerator', meaning: '比例指标的分子；计数或金额指标写不适用并说明。', source: '口径表与 SQL' },
      { name: 'distinct_key', meaning: '按哪个字段去重。', source: 'user_id 或 order_id' },
      { name: 'time_window', meaning: '自然日或滚动 24 小时窗口。', source: 'event_time 条件' },
      { name: 'result_value', meaning: '本地教学表计算出的结果。', source: 'W4 events 教学表' },
      { name: 'sample_check', meaning: 'TEST、U03、O05、O06 等样本核对。', source: '实验观察' },
      { name: 'can_prove', meaning: '这条 SQL 在本地教学中能证明什么。', source: '证据边界' },
      { name: 'cannot_prove', meaning: '不能证明真实生产、JOIN、归因、趋势、看板发布或 W4D4 已完成。', source: '证据边界' },
      { name: 'next_review_task', meaning: '下一步只指向 W4D4 三种上涨假象分析。', source: '课程边界' },
    ],
    badExample: 'metric_name: 转化率\nsql_snippet: SELECT COUNT(*) FROM events;\nresult_value: 27，所以转化很好，周会可以直接发布。',
    badReasons: ['没有 metric_ref 和 aggregation_ref。', '没有 base_cte、分母、分子、去重键或窗口。', 'COUNT(*) 把 TEST 和不同事件混在一起。', '把教学样本越界成真实业务结论。'],
    revisionSteps: ['补 metric_ref 与 aggregation_ref。', '写 base_cte 和 sql_snippet。', '比例指标必须补 denominator、numerator、distinct_key 和 time_window。', '金额指标必须先写 unique_paid_orders。', '补 sample_check、can_prove、cannot_prove。', 'next_review_task 只指向 W4D4。'],
    goodExample: 'metric-calculation.md\n\nmetric_name: checkout_to_pay_24h\nmetric_ref: checkout_to_pay_24h / W4D1 metric-contract-table.md\naggregation_ref: W4D2 rolling-24h-window\nbusiness_question: 2026-09-07 教学样本中，看过结算页的非测试用户有多少在 24 小时内支付\nbase_cte: base_events 排除 is_test=1，保留 event_name、event_time、user_id、order_id、amount\nsql_snippet: checkouts CTE JOIN payments CTE ON user_id，WHERE payment_time >= checkout_time AND payment_time < datetime(checkout_time, "+24 hours")\ndenominator: checkout_users=7，COUNT(DISTINCT checkout user_id)\nnumerator: paid_within_24h_users=4，COUNT(DISTINCT paid user_id)\ndistinct_key: user_id\ntime_window: 每个 checkout_view 发生后滚动 24 小时\nresult_value: checkout_to_pay_24h=0.5714\nsample_check: U03 在 2026-09-07 10:01 checkout，2026-09-08 11:00 payment，超过 24 小时，不计入；TEST 排除\ncan_prove: 能证明本地 W4 events 教学表按该 SQL 口径可得到 0.5714\ncannot_prove: 不能证明真实生产转化率、原因、趋势、JOIN 对账、看板可发布或 W4D4 已完成\nnext_review_task: W4D4 检查分母变化、幸存者偏差和异常大单造成的上涨假象\n',
    guidedPrompts: ['写 active_users。', '写 exposure_to_pay。', '写 checkout_to_pay_24h。', '写 unique_paid_orders。', '写 aov_amount。', '写 median_outlier_guard。'],
    blankTemplate: 'metric-calculation.md\n\nmetric_name: \nmetric_ref: \naggregation_ref: \nbusiness_question: \nbase_cte: \nsql_snippet: \ndenominator: \nnumerator: \ndistinct_key: \ntime_window: \nresult_value: \nsample_check: \ncan_prove: \ncannot_prove: \nnext_review_task: \n',
    standardTemplate: 'metric-calculation.md\n\nmetric_name: active_users\nmetric_ref: active_user / W4D1\naggregation_ref: W4D2 count-distinct-user\nbusiness_question: 统计 2026-09-07 教学样本中参与漏斗活动的非测试唯一用户\nbase_cte: base_events 排除 TEST/is_test=1，保留 coupon_exposure、checkout_view、payment_success 等事件\nsql_snippet: COUNT(DISTINCT CASE WHEN event_name IN ("coupon_exposure","checkout_view","payment_success") THEN user_id END)\ndenominator: 不适用；这是用户计数指标\nnumerator: 不适用；这是用户计数指标\ndistinct_key: user_id\ntime_window: 2026-09-07 教学自然日\nresult_value: active_users=10\nsample_check: TEST 被排除\ncan_prove: 能证明本地教学表按活动事件集合有 10 个唯一活跃用户\ncannot_prove: 不能证明真实生产 DAU、真实埋点覆盖、JOIN、归因、趋势、看板可发布或 W4D4 已完成\nnext_review_task: W4D4 检查指标上涨是否可能来自分母或样本变化\n\nmetric_name: aov_amount\nmetric_ref: paid_order_aov / W4D1\naggregation_ref: W4D2 average-vs-median\nbusiness_question: 支付金额平均值能否代表典型订单\nbase_cte: base_events 排除 TEST/is_test=1\nsql_snippet: 先用 w4_unique_paid_orders 按 order_id 去重，再 ROUND(AVG(amount),2)\ndenominator: unique_paid_orders=5\nnumerator: total_amount=10385.00\ndistinct_key: order_id\ntime_window: payment_success 教学样本\nresult_value: aov_amount=2077.00; median_amount=89.00; max_amount=9999.00\nsample_check: O05 重复支付事件只算一单；O06 9999 元拉高均值\ncan_prove: 能证明本地教学样本中 AOV 受异常大单影响，需要护栏列\ncannot_prove: 不能证明真实客单价、异常根因、运营效果、JOIN、趋势、看板可发布或 W4D4 已完成\nnext_review_task: W4D4 分析三种上涨假象\n',
    checklist: ['至少写 5 条指标计算记录。', '每条都有 metric_name、metric_ref、aggregation_ref、base_cte、sql_snippet 和 result_value。', '活跃、转化、支付订单、AOV 与中位数护栏至少各出现一次。', 'TEST、U03、O05、O06 四类边界至少各解释一次。', 'cannot_prove 明确排除真实生产、JOIN、归因、趋势、看板发布或 W4D4 已完成。', 'next_review_task 只指向 W4D4。'],
  },
  memory: {
    conceptIds: [...conceptIds],
    anchors: ['先写 base CTE，保证多指标使用同一批输入。', '活跃用户按活动事件集合和 user_id 去重。', '转化率必须同时写分母、分子和窗口。', 'AOV 先按 order_id 去重，再用中位数和最大值做护栏。'],
    closedBookPrompt: '闭卷复述 W4D3 指标计算链路：W4D1 口径 → W4D2 聚合逻辑 → base CTE → active_users → conversion rates → unique paid orders → AOV guards → metric-calculation.md。',
    microOperation: '不看答案，写一条 checkout_to_pay_24h 的 denominator、numerator、time_window、result_value 和 cannot_prove。',
    unresolvedPrompt: '写出进入 W4D4 前你最担心被误读的一个指标：active_users、转化率、unique_paid_orders 还是 AOV？准备怎样检查上涨假象？',
    reviewStages: [
      { stage: 'D1', task: '闭卷写出 metric-calculation.md 的 15 个字段，并说明 base_cte 的作用。' },
      { stage: 'D3', task: '复原 checkout_to_pay_24h 的分母、分子、窗口和 U03 边界。' },
      { stage: 'D7', task: '解释 O05 为什么影响支付订单数，O06 为什么影响 AOV。' },
      { stage: 'D14', task: '不看模板，写出 active_users 与 exposure_to_pay 的 SQL 思路。' },
      { stage: 'D30', task: '把一条 W4D2 聚合逻辑改写成 W4D3 指标计算记录。' },
      { stage: 'D60', task: '说明 W4D3 与 W4D4 的边界：指标计算 SQL vs 上涨假象分析。' },
    ],
  },
  nextLesson: { id: 'W4D4', title: '三种上涨假象', bridge: '下一课才分析分母变化、幸存者偏差和异常大单造成的误导；W4D3 只交付本地教学指标计算 SQL 和证据边界。' },
}
