import type { DailyCourse, Exercise } from './types'

const conceptIds = [
  'rise-claim-audit',
  'denominator-shift-trap',
  'survivorship-bias-trap',
  'outlier-average-trap',
  'composition-mix-shift',
  'distribution-guard-check',
  'misleading-rise-case-table',
  'metric-rise-decision-boundary',
] as const

const prerequisiteConceptIds = [
  'query-question',
  'where-condition',
  'date-range-boundary',
  'distinct-result',
  'null-value',
  'duplicate-row',
  'test-data-flag',
  'quality-evidence-boundary',
  'business-query-set',
  'quality-flagged-answer',
  'metric-decision-purpose',
  'metric-signal',
  'metric-numerator',
  'metric-denominator',
  'metric-grain',
  'metric-time-window',
  'metric-exclusion-rule',
  'metric-contract-table',
  'aggregation-input-set',
  'count-aggregate',
  'distinct-aggregate',
  'sum-aggregate',
  'avg-aggregate',
  'group-by-bucket',
  'having-group-filter',
  'aggregation-logic-map',
  'metric-sql-base-cte',
  'active-user-sql',
  'same-day-conversion-sql',
  'rolling-window-conversion-sql',
  'unique-paid-order-sql',
  'aov-sql',
  'median-outlier-guard-sql',
  'metric-calculation-note',
] as const

function exercise(
  id: string,
  categories: Exercise['categories'],
  ids: string[],
  prompt: string,
  options: string[],
  answerIndex: number,
  referenceAnswer: string,
): Exercise {
  return {
    id,
    kind: 'single-choice',
    categories,
    conceptIds: ids,
    prompt,
    hint: '先把上涨声明拆成 old_value、new_value、denominator_check、survivor_check、outlier_check 和 decision_limit；不要只看一个更高的结果值。',
    options: options.map((label, index) => ({
      label,
      rationale: index === answerIndex ? '这项先检查上涨是否来自口径、样本或分布变化，再写有限结论。' : '这项要么只相信涨幅，要么把教学样本越界解释成真实原因。',
      couldBeTrueWhen: index === answerIndex ? '当学习者正在写 misleading-rise-review.md。' : '只有后续评审、生产数据对账和原因分析完成后，才可能支撑更强判断。',
    })),
    answerIndex,
    referenceAnswer,
    reasoning: [
      'W4D4 承接 W4D3 的指标计算结果，任务是审查“上涨”是否可能是误导。',
      '三类核心假象是分母变化、幸存者偏差和异常大单拉动；样本构成变化与分布护栏用来补充证据。',
      '本日仍是本地教学模拟，只能输出误导风险表，不能证明真实生产增长或策略有效。',
    ],
    rubric: ['上涨声明被拆解', '三类假象逐项检查', '样本证据具体', '结论边界不过界'],
    commonErrors: [
      { error: '看到 rate 上升就说产品变好', reason: 'rate 上升可能来自分母变小，而不是分子真的改善。' },
      { error: '看到 AOV 上升就说典型订单变贵', reason: 'O06 9999 元异常大单会拉高均值，但 median_amount 仍是 89。' },
    ],
    remediation: { label: '回看上涨审查表字段', sectionId: 'deliverable', anchor: 'w4d4-rise-review-fields' },
  }
}

export const w4d4: DailyCourse = {
  id: 'W4D4',
  contentVersion: 'w4d4-misleading-rise-day01-v1',
  week: 4,
  day: 4,
  title: '三种上涨假象',
  subtitle: '用 W4 本地 events 教学表审查指标上涨是否可能来自分母变化、幸存者偏差或异常大单拉动；本日只交付误导案例分析，不做 JOIN、归因、趋势发布或真实生产结论。',
  duration: { core: 30, standard: 45, extension: 80, full: 130 },
  coreConceptGroups: [
    {
      id: 'rise-claim-first',
      title: '先审查上涨声明，不急着解释原因',
      conceptIds: ['rise-claim-audit', 'metric-rise-decision-boundary'],
      summary: '上涨声明必须先写 old_value、new_value、计算口径和证据边界；没有审查前，不能把更高数字说成业务变好。',
      boundary: '能判断教学样本中的上涨声明是否可疑；不能证明真实增长、原因、归因或看板可发布。',
    },
    {
      id: 'three-rise-traps',
      title: '三种最常见上涨假象',
      conceptIds: ['denominator-shift-trap', 'survivorship-bias-trap', 'outlier-average-trap'],
      summary: '分母变小会抬高比例，幸存者偏差会只留下高意愿样本，异常大单会把平均值拉高。',
      boundary: '能拆解 exposure_to_pay、checkout_to_pay_24h 和 aov_amount 的误导风险；不能完成生产级因果分析。',
    },
    {
      id: 'distribution-and-case-table',
      title: '用样本构成和分布护栏写成审查表',
      conceptIds: ['composition-mix-shift', 'distribution-guard-check', 'misleading-rise-case-table'],
      summary: '把渠道、事件集合、样本数、median_amount、max_amount 和风险标签写进 misleading-rise-review.md，让上涨结论可被复核。',
      boundary: '能形成本地教学误导案例表；不能替代后续指标评审、JOIN 对账或真实业务复盘。',
    },
  ],
  prerequisiteConceptIds: [...prerequisiteConceptIds],
  learningPaths: {
    '30': {
      guidedStepIndices: [0, 1, 2, 3, 4, 5],
      guidedRecordIndices: [0, 1, 2, 3, 4, 5],
      exerciseCount: 3,
      deliverablePromptCount: 6,
      deliverableChecklistIndices: [0, 1, 2, 3, 4],
      deliverableMinimumContributionCharacters: 280,
    },
    '45': {
      guidedStepIndices: [0, 1, 2, 3, 4, 5],
      guidedRecordIndices: [0, 1, 2, 3, 4, 5],
      exerciseCount: 4,
      deliverablePromptCount: 6,
      deliverableChecklistIndices: [0, 1, 2, 3, 4, 5],
      deliverableMinimumContributionCharacters: 400,
    },
  },
  primaryGoal: '提交 `misleading-rise-review.md`：至少分析 denominator_shift、survivorship_bias、outlier_average 三个上涨假象，逐条写出 metric_name、old_value、new_value、claimed_rise、risk_type、sample_check、guardrail_metric、can_prove、cannot_prove 和 next_review_task。',
  scenario: {
    role: '你是刚完成 W4D3 指标计算 SQL 的产品经理。',
    situation: '周会前，有人看到 exposure_to_pay、checkout_to_pay_24h 或 aov_amount 比另一个口径更高，就想写“指标上涨，活动有效”。你手里只有 W4 本地 events 教学表和 W4D3 的计算记录，必须先判断这是不是分母变化、幸存者偏差或异常大单造成的上涨假象。',
    question: '怎样把“上涨了”拆成可审查案例，避免把口径变化、样本幸存和异常值误写成业务变好？',
    stakes: '如果不审查分母，少数高意愿用户会让转化率看起来变好；如果只看支付样本，未结算用户被悄悄排除；如果只看 AOV，O06 的 9999 元会让典型订单被误读。',
  },
  objectives: [
    { id: 'w4d4-objective-denominator', text: '能识别分母变化造成的比例上涨假象', evidence: '`misleading-rise-review.md` 写出 denominator_before、denominator_after、exposed_users=10、checkout_users=7 和风险判断。' },
    { id: 'w4d4-objective-survivor', text: '能说明幸存者偏差如何只保留高意愿样本', evidence: '成果中解释 checkout_to_pay_24h=0.5714 高于 exposure_to_pay=0.4000，可能来自只看进入结算页的用户。' },
    { id: 'w4d4-objective-outlier', text: '能用中位数和最大值检查 AOV 上涨假象', evidence: '成果写出 aov_amount=2077.00、median_amount=89.00、max_amount=9999.00 和 O06 异常大单。' },
    { id: 'w4d4-objective-boundary', text: '能把误导风险和业务结论分开', evidence: 'cannot_prove 明确排除真实生产增长、活动有效、JOIN 对账、归因、趋势和看板发布。' },
  ],
  prerequisites: [
    {
      id: 'w4d4-w4d3-readiness',
      conceptIds: [...prerequisiteConceptIds],
      prompt: '你是否能复述 W4D3 的 active_users、exposure_to_pay、checkout_to_pay_24h、unique_paid_orders、aov_amount、median_amount 和 max_amount，并说明每个数字的分母、去重键、窗口和边界样本？',
      passDescription: '能说明 W4D4 不重新计算指标，而是拿 W4D3 的本地教学指标结果审查上涨误导。',
      remediationLabel: '回到 W4D3 补指标计算 SQL',
      remediationTarget: '#/lesson/W4D3',
      remediation: {
        purpose: 'W4D4 可提前阅读；但没有 W4D3 的指标结果、分母、窗口和异常样本，三种上涨假象会变成凭感觉判断。',
        steps: ['补齐 W4D3 metric-calculation.md 中 active_users、exposure_to_pay、checkout_to_pay_24h、unique_paid_orders、aov_amount、median_amount、max_amount。', '复述 TEST、U03、O05、O06 分别影响哪些指标解释。', '写一句“W4D4 只审查本地教学上涨假象，不证明真实生产增长”。'],
        successCheck: '能把“更高的指标”拆成分母、幸存样本、异常值和分布护栏四类检查。',
      },
    },
  ],
  concepts: [
    {
      id: 'rise-claim-audit',
      prerequisiteConceptIds: ['metric-calculation-note'],
      term: '上涨声明审查',
      english: 'Rise Claim Audit',
      definition: '上涨声明审查是把“指标变高了”拆成旧值、新值、口径、样本、护栏和可证明边界的检查动作。',
      why: '指标上升可能来自用户行为改善，也可能来自口径换了、样本缩了或异常值拉动；先审查才能避免过早下结论。',
      problemSolved: '回答“这个上涨能不能先被当成可信业务信号”。',
      input: 'W4D3 的 metric-calculation.md、指标值、分母分子、样本边界和异常样本。',
      output: '一条 rise_review 记录，标注风险类型和下一步复核动作。',
      systemPosition: '位于指标计算之后、业务结论之前，是 W4D4 的入口动作。',
      process: ['写出 old_value 与 new_value。', '标注 claimed_rise 和比较口径。', '逐项检查分母、幸存样本和异常值。'],
      owner: '产品经理负责阻止过早结论，数据同事可补生产口径和对账。',
      notResponsibleFor: '不负责证明真实增长、归因或策略有效。',
      compareWith: 'W4D3 计算指标；W4D4 审查更高的指标是否可能误导。',
      evidence: ['old_value/new_value。', 'risk_type。', 'cannot_prove。'],
      failureModes: ['只贴上涨百分比，不写比较口径。', '把教学样本上涨直接写成真实业务成功。'],
      pmUse: '周会前把“转化率更高”改写成“该上涨声明先通过三类误导检查”。',
      correctExample: 'claimed_rise: checkout_to_pay_24h 高于 exposure_to_pay；risk_type: survivorship_bias。',
      incorrectExample: '转化率上涨，所以活动已经有效，可以直接写进周会。',
    },
    {
      id: 'denominator-shift-trap',
      prerequisiteConceptIds: ['metric-denominator', 'same-day-conversion-sql'],
      term: '分母变化假象',
      english: 'Denominator Shift Trap',
      definition: '分母变化假象是比例指标因为比较基准变小、变窄或换对象而上升，看起来像改善，实际只是分母不同。',
      why: 'exposed_users=10 与 checkout_users=7 不是同一个机会集合，分母缩小后比率可能自然变高。',
      problemSolved: '回答“上涨是否只是因为拿不同分母比较”。',
      input: '比例指标的 denominator_before、denominator_after、numerator 和窗口。',
      output: 'denominator_shift 风险判断和补查问题。',
      systemPosition: '位于所有转化率解读之前，是比例指标的第一道护栏。',
      process: ['列出比较前后的分母。', '检查分母是否同对象、同窗口、同去重键。', '如果分母变小，先标记上涨可疑。'],
      owner: '产品经理负责追问分母，SQL 结果负责提供人数。',
      notResponsibleFor: '不负责证明分母变化的业务原因。',
      compareWith: '分子变大可能是更多人达成；分母变小可能只是机会集合变窄。',
      evidence: ['exposed_users=10。', 'checkout_users=7。', 'denominator_after < denominator_before。'],
      failureModes: ['把 4/10 与 4/7 当同一指标趋势。', '忽略分母从曝光用户变成结算页用户。'],
      pmUse: '看到转化率从 0.4000 到 0.5714，先问分母是不是从曝光用户换成结算用户。',
      correctExample: 'denominator_check: 10 exposed users vs 7 checkout users，不能直接说转化改善。',
      incorrectExample: '0.5714 大于 0.4000，所以转化率上涨。',
    },
    {
      id: 'survivorship-bias-trap',
      prerequisiteConceptIds: ['rolling-window-conversion-sql', 'metric-denominator'],
      term: '幸存者偏差假象',
      english: 'Survivorship Bias Trap',
      definition: '幸存者偏差假象是只观察已经进入后续阶段的样本，忽略没有进入该阶段的人，导致指标看起来更好。',
      why: '能进入 checkout_view 的用户本来就更有购买意愿，只看这 7 人会忽略没有结算的曝光用户。',
      problemSolved: '回答“样本是不是只剩下高意愿人群”。',
      input: '原始入口用户、后续阶段用户、被排除人群和转化结果。',
      output: 'survivor_check 与 excluded_population 说明。',
      systemPosition: '位于漏斗后段指标解释层，保护 PM 不把后段高转化当全量用户表现。',
      process: ['找出被观察样本是从哪一步开始的。', '列出没有进入该步的人是否被排除。', '把结论限定为幸存样本内部。'],
      owner: '产品经理负责说明样本选择，数据同事可补完整漏斗人数。',
      notResponsibleFor: '不负责证明用户为什么没有进入后续阶段。',
      compareWith: '分母变化强调基准换了；幸存者偏差强调只剩下通过前置筛选的人。',
      evidence: ['checkout_users=7。', 'exposed_users=10。', '未进入 checkout 的 3 人被排除。'],
      failureModes: ['只看结算页用户，忽略曝光后未结算用户。', '把高意愿样本的转化率推广到全部用户。'],
      pmUse: '对“结算后 24 小时转化更高”补一句：这只描述进入结算页的幸存样本。',
      correctExample: 'survivor_check: 仅分析 checkout_users=7，不能代表全部 exposed_users=10。',
      incorrectExample: '结算页转化高，所以所有曝光用户购买意愿都提高。',
    },
    {
      id: 'outlier-average-trap',
      prerequisiteConceptIds: ['aov-sql', 'median-outlier-guard-sql'],
      term: '异常值均值假象',
      english: 'Outlier Average Trap',
      definition: '异常值均值假象是少数极端金额把平均值拉高，让人误以为典型样本也变高。',
      why: 'W4 教学表中 O06=9999 会把 aov_amount 拉到 2077，但 median_amount 只有 89。',
      problemSolved: '回答“平均值上涨是否代表典型订单上涨”。',
      input: '唯一支付订单、amount、aov_amount、median_amount、max_amount 和异常订单。',
      output: 'outlier_average 风险标签和分布护栏。',
      systemPosition: '位于金额指标解释层，是 AOV 进入业务结论前的必要检查。',
      process: ['先确认订单已按 order_id 去重。', '对照 AVG、median 和 max。', '标记是否存在单笔大单拉动均值。'],
      owner: '产品经理要求分布护栏，SQL 负责输出均值、中位数和最大值。',
      notResponsibleFor: '不负责判断异常订单是否真实有效或应被剔除。',
      compareWith: 'AVG 对极端值敏感；median 更接近排序中间的典型样本。',
      evidence: ['aov_amount=2077.00。', 'median_amount=89.00。', 'max_amount=9999.00。'],
      failureModes: ['只展示 AOV，不展示中位数。', '把大单拉动的均值解释成典型订单金额。'],
      pmUse: '看到 AOV 很高时，先补 median_amount 和 max_amount，再写有限结论。',
      correctExample: 'outlier_check: O06=9999 拉高 AOV，median_amount=89 不支持典型订单变贵。',
      incorrectExample: 'AOV=2077，所以用户通常每单花 2077。',
    },
    {
      id: 'composition-mix-shift',
      prerequisiteConceptIds: ['group-by-bucket', 'metric-grain'],
      term: '样本构成变化',
      english: 'Composition Mix Shift',
      definition: '样本构成变化是总体指标因为渠道、阶段、用户类型或订单类型占比改变而变化，并不一定代表每个组都变好。',
      why: '如果高金额订单或高意愿用户占比上升，总体指标会上升，但低金额组或低意愿组可能没有改善。',
      problemSolved: '回答“上涨是不是由样本结构变化带来的”。',
      input: 'group_key、各组样本数、各组指标和总体指标。',
      output: 'composition_check 与需要补充的分组复核任务。',
      systemPosition: '位于 GROUP BY 之后，是解释总体指标前的结构检查。',
      process: ['列出可能影响指标的 group_key。', '比较每组样本数和指标。', '避免只用总体均值覆盖各组差异。'],
      owner: '产品经理提出分组视角，SQL 后续补充组内结果。',
      notResponsibleFor: '不负责完成完整分层趋势和生产归因。',
      compareWith: '异常值关注少数极端样本；构成变化关注不同组占比改变。',
      evidence: ['group_key。', 'bucket_count。', 'group_metric。'],
      failureModes: ['只看总体 AOV，不问高金额组占比。', '没有说明渠道或阶段样本是否变化。'],
      pmUse: '在审查表写“下一步按渠道或阶段分组检查，防止总体上涨掩盖组内不变”。',
      correctExample: 'composition_check: 需要按 event_stage 或 order_amount_bucket 比较样本占比。',
      incorrectExample: '总体涨了，所以每个用户群都涨了。',
    },
    {
      id: 'distribution-guard-check',
      prerequisiteConceptIds: ['outlier-average-trap'],
      term: '分布护栏检查',
      english: 'Distribution Guard Check',
      definition: '分布护栏检查是在均值旁边放样本数、中位数、最大值、最小值或分位点，确认均值是否有代表性。',
      why: '平均值是一个压缩结果，没有样本数和分布护栏时，PM 看不到少数样本是否正在操纵解释。',
      problemSolved: '回答“这个平均值有没有足够护栏进入讨论”。',
      input: 'sample_size、avg、median、min、max、outlier_id 和排序样本。',
      output: 'guardrail_metric 与代表性判断。',
      systemPosition: '位于金额和时长等均值指标的解释旁边，是成果表的护栏列。',
      process: ['写出样本数。', '写出 median 和 max。', '标记异常样本对均值的影响。'],
      owner: '产品经理负责要求护栏列，数据同事负责补分布统计。',
      notResponsibleFor: '不负责自动剔除异常样本或批准生产口径。',
      compareWith: '指标值回答多少；分布护栏回答这个多少是否容易误导。',
      evidence: ['unique_paid_orders=5。', 'median_amount=89。', 'max_amount=9999。'],
      failureModes: ['均值旁边没有样本数。', '只写 max 不解释它对 AVG 的影响。'],
      pmUse: '给 AOV 结论加护栏：“样本 5 单、median 89、max 9999，不能代表典型订单”。',
      correctExample: 'guardrail_metric: sample_size=5; median_amount=89; max_amount=9999。',
      incorrectExample: 'guardrail_metric: 无；均值足够说明问题。',
    },
    {
      id: 'misleading-rise-case-table',
      prerequisiteConceptIds: ['rise-claim-audit', 'denominator-shift-trap', 'survivorship-bias-trap', 'outlier-average-trap', 'composition-mix-shift', 'distribution-guard-check'],
      term: '上涨误导案例表',
      english: 'Misleading Rise Case Table',
      definition: '上涨误导案例表是把每个可疑上涨写成一条记录，包含指标、比较值、风险类型、样本核对、护栏指标和下一步复核。',
      why: '会议里最危险的不是数字错，而是数字还没审查就被写成原因和决策；案例表能让每条上涨都可追问。',
      problemSolved: '回答“这条上涨声明如何交给别人复核”。',
      input: '指标计算记录、三类假象检查、样本构成检查和分布护栏。',
      output: 'misleading-rise-review.md。',
      systemPosition: '位于 W4D4 成果层，衔接后续指标评审和对账课程。',
      process: ['每条记录选一个 risk_type。', '写 sample_check 和 guardrail_metric。', '写 can_prove、cannot_prove 和 next_review_task。'],
      owner: '产品经理维护审查表，评审人根据表追问证据。',
      notResponsibleFor: '不负责给出最终生产判定或修复数据。',
      compareWith: 'metric-calculation.md 保存计算结果；misleading-rise-review.md 保存误导风险判断。',
      evidence: ['risk_type=denominator_shift。', 'sample_check=O06。', 'next_review_task。'],
      failureModes: ['只写“有风险”不写具体风险类型。', '没有样本核对和下一步复核。'],
      pmUse: '把“上涨了”整理成三条可复核案例，而不是把一句口号发进周报。',
      correctExample: 'case_id: MR03; metric_name: aov_amount; risk_type: outlier_average; guardrail_metric: median_amount=89。',
      incorrectExample: '上涨原因：用户更愿意付费。',
    },
    {
      id: 'metric-rise-decision-boundary',
      prerequisiteConceptIds: ['misleading-rise-case-table'],
      term: '上涨结论边界',
      english: 'Metric Rise Decision Boundary',
      definition: '上涨结论边界是把“能证明误导风险存在”和“不能证明真实业务变好”明确分开的结论写法。',
      why: 'W4D4 的目标是阻止误读，不是替代生产评审；边界写清后，团队知道下一步该补什么证据。',
      problemSolved: '回答“这份审查表能支持什么决策，不能支持什么决策”。',
      input: '风险类型、样本核对、护栏指标和未完成的复核任务。',
      output: '有限结论、cannot_prove 和 next_review_task。',
      systemPosition: '位于成果提交和复盘排程之前，保护课程证据不越界。',
      process: ['先写 can_prove。', '再写 cannot_prove。', '最后把下一步限定为评审、对账或补分组。'],
      owner: '产品经理负责结论边界，评审人决定是否进入生产验证。',
      notResponsibleFor: '不负责批准指标发布或宣布活动成功。',
      compareWith: '风险标签指出可能误导；结论边界说明还不能做什么决定。',
      evidence: ['can_prove。', 'cannot_prove。', 'next_review_task。'],
      failureModes: ['把误导风险写成确定原因。', '把本地教学样本写成生产决策依据。'],
      pmUse: '周会里说“这条上涨需要复核分母和异常值”，而不是说“策略已成功”。',
      correctExample: 'can_prove: 本地教学样本存在上涨误导风险；cannot_prove: 不能证明真实增长或原因。',
      incorrectExample: '已经证明上涨来自活动优化。',
    },
  ],
  diagram: {
    title: '从指标上涨到误导风险的审查路径',
    caption: 'W4D4 的链路是：W4D3 指标计算记录 → 上涨声明 → 分母检查 → 幸存样本检查 → 异常值与分布护栏 → 样本构成检查 → misleading-rise-review.md → 后续评审。',
    nodes: [
      { id: 'calculation', label: 'W4D3 指标结果', description: '提供 active_users、转化率、AOV、中位数和最大值。', input: 'metric-calculation.md', output: 'metric values', owner: '产品经理' },
      { id: 'claim', label: '上涨声明', description: '把“更高”写成 old_value/new_value 和 claimed_rise。', input: 'metric values', output: 'rise claim', owner: '产品经理' },
      { id: 'denominator', label: '分母变化', description: '检查 exposed_users=10 与 checkout_users=7 是否被直接比较。', input: 'ratio metrics', output: 'denominator_shift', owner: '产品经理', evidence: '10 vs 7' },
      { id: 'survivor', label: '幸存者偏差', description: '检查是否只剩下进入 checkout 的高意愿用户。', input: 'funnel users', output: 'survivorship_bias', owner: '产品经理', evidence: 'checkout_users=7' },
      { id: 'outlier', label: '异常值均值', description: '检查 O06 9999 元是否拉高 AOV。', input: 'unique paid orders', output: 'outlier_average', owner: '产品经理', evidence: 'median=89 max=9999' },
      { id: 'composition', label: '样本构成', description: '记录需要按渠道、阶段或金额桶继续分组复核。', input: 'group_key', output: 'composition_check', owner: '产品经理' },
      { id: 'review', label: '上涨误导案例表', description: '写清风险类型、样本核对、护栏和结论边界。', input: 'checks', output: 'misleading-rise-review.md', owner: '产品经理' },
    ],
    branches: [
      { from: 'calculation', to: 'claim', label: '提出可审查声明', kind: 'normal' },
      { from: 'claim', to: 'denominator', label: '先查比例分母', kind: 'normal' },
      { from: 'denominator', to: 'survivor', label: '再查幸存样本', kind: 'normal' },
      { from: 'claim', to: 'outlier', label: '金额指标查分布', kind: 'normal' },
      { from: 'outlier', to: 'composition', label: '补样本结构', kind: 'normal' },
      { from: 'composition', to: 'review', label: '交付有限审查表', kind: 'normal' },
      { from: 'claim', to: 'review', label: '跳过检查会把上涨误写成原因', kind: 'failure' },
    ],
    evidenceNotes: ['比例上涨先看分母是否换了。', '后段漏斗指标可能只剩幸存样本。', 'AOV 必须对照 median_amount 和 max_amount。', '总体上涨还要提示样本构成可能变化。'],
  },
  demonstration: {
    title: '教师示范：把三个上涨说法改写成误导案例',
    businessProblem: '周会材料里出现三句话：结算后 24 小时转化率高于曝光到支付转化率、AOV 看起来很高、总体表现似乎变好。你要用 W4D4 的审查表把它们改写成有限结论。',
    finalConclusion: '教学样本中可以标记三类误导风险：denominator_shift（10 个曝光用户 vs 7 个结算用户）、survivorship_bias（只看 checkout_users=7 的高意愿样本）、outlier_average（O06=9999 拉高 aov_amount=2077.00，median_amount=89.00）。',
    conclusionLimit: '这只能证明本地教学样本中的上涨声明存在误导风险；不能证明真实生产增长、活动有效、原因、趋势、JOIN 对账、看板可发布或后续评审已完成。',
    steps: [
      { title: '摘出上涨声明', action: '把“0.5714 比 0.4000 高”写成 claimed_rise，而不是直接写成功结论。', reason: '审查从声明开始，先不要解释原因。', evidence: 'old_value=0.4000; new_value=0.5714。', proves: '能把口号拆成可检查记录。', limitation: '还不能判断上涨真假。' },
      { title: '检查分母变化', action: '对照 exposed_users=10 和 checkout_users=7。', reason: '分母从曝光用户变成结算用户，比较基准已经改变。', evidence: 'denominator_before=10; denominator_after=7。', proves: '能识别 denominator_shift。', limitation: '不能证明为什么分母变小。' },
      { title: '检查幸存样本', action: '标记 checkout_users 是已经进入结算页的后段用户。', reason: '后段用户通常比全部曝光用户意愿更强。', evidence: 'excluded_population=未进入 checkout 的 3 个曝光用户。', proves: '能识别 survivorship_bias 风险。', limitation: '不能代表全部曝光用户。' },
      { title: '检查异常大单', action: '把 AOV 与 median_amount、max_amount、O06 放在同一条记录。', reason: '均值可能被少数极端值拉动。', evidence: 'aov_amount=2077.00; median_amount=89.00; max_amount=9999.00。', proves: '能识别 outlier_average。', limitation: '不能判断 O06 是否应剔除。' },
      { title: '补样本构成提醒', action: '写 next_review_task：按渠道、阶段或金额桶补 GROUP BY 检查。', reason: '总体上涨还可能来自样本构成变化。', evidence: 'composition_check=pending_group_review。', proves: '知道总体指标需要分层复核。', limitation: '本日不做完整生产分层趋势。' },
      { title: '写出有限结论', action: '把 can_prove 与 cannot_prove 分开。', reason: '误导风险不是业务原因。', evidence: 'cannot_prove 包含真实增长、归因、JOIN、趋势、看板发布。', proves: '能安全交付误导案例分析。', limitation: '后续仍要进入评审和对账。' },
    ],
  },
  guidedLab: {
    title: '上涨误导审查台：三类假象六路径',
    goal: '用 W4D3 的教学指标结果逐项审查 denominator_shift、survivorship_bias、outlier_average、composition_mix 和 distribution_guard，并把 denominator_check、survivor_check、outlier_check 写入 misleading-rise-review.md 后交给 W4D5。',
    safety: '这是本地教学模拟，不连接真实数据库、不读取公司数据、不生成生产看板，也不证明活动有效。',
    conceptIds: [...conceptIds],
    predictionPrompt: '如果 checkout_to_pay_24h=0.5714 高于 exposure_to_pay=0.4000，且 aov_amount=2077.00 但 median_amount=89.00，你预测最可能出现哪几类上涨假象？先写理由。',
    steps: [
      { title: 'rise-claim-audit', action: '把上涨话术拆成 old_value、new_value、claimed_rise。', observe: '数字更高先成为待审查声明。', explanation: '没有声明拆解，就无法检查分母和样本。', proves: '能建立上涨审查入口。', cannotProve: '不能证明上涨真实有效。' },
      { title: 'denominator-shift', action: '比较 exposed_users=10 与 checkout_users=7。', observe: '分母变小会让 4/7 高于 4/10。', explanation: '分母不同的比例不能直接当趋势。', proves: '能识别分母变化假象。', cannotProve: '不能证明真实转化改善。' },
      { title: 'survivorship-bias', action: '标记只观察 checkout_users=7。', observe: '未进入结算页的 3 个曝光用户不在后段指标里。', explanation: '后段样本是经过前置筛选后的幸存样本。', proves: '能识别幸存者偏差。', cannotProve: '不能代表所有曝光用户。' },
      { title: 'outlier-average', action: '检查 aov_amount、median_amount、max_amount 和 O06。', observe: '2077.00 与 89.00 差距很大，max_amount=9999。', explanation: '异常大单会让平均值不像典型订单。', proves: '能识别异常值均值假象。', cannotProve: '不能判断异常订单是否无效。' },
      { title: 'composition-mix', action: '写出需要按渠道、阶段或金额桶继续分组。', observe: '总体指标可能被组占比改变影响。', explanation: '总体上涨不等于每组都上涨。', proves: '能提出样本构成复核。', cannotProve: '不能完成生产分层趋势。' },
      { title: 'case-table', action: '把风险写入 misleading-rise-review.md。', observe: '每条案例都有 risk_type、sample_check、guardrail_metric 和 cannot_prove。', explanation: '案例表让上涨声明可复核而不过界。', proves: '能交付本地误导案例分析。', cannotProve: '不能证明看板可发布或原因成立。' },
    ],
    recordPrompts: [
      '记录 rise-claim-audit：old_value、new_value 和 claimed_rise 分别是什么。',
      '记录 denominator-shift：exposed_users=10 与 checkout_users=7 为什么不能直接比较。',
      '记录 survivorship-bias：哪些用户被排除在 checkout_to_pay_24h 的分母之外。',
      '记录 outlier-average：O06、aov_amount、median_amount、max_amount 如何共同解释风险。',
      '记录 composition-mix：下一步按什么 group_key 复核样本构成。',
      '记录 case-table：risk_type、sample_check、guardrail_metric、can_prove 和 cannot_prove。',
    ],
    comparePrompt: '对照三类上涨假象，找出哪一条最容易被写成错误周会结论，并写出你会在 W4D5 前追问的 denominator_check、survivor_check、outlier_check 或护栏证据。',
    passCriteria: ['六条上涨审查路径都有记录。', 'denominator_shift、survivorship_bias、outlier_average 至少各出现一次。', 'exposure_to_pay、checkout_to_pay_24h、aov_amount、median_amount、max_amount 都有解释。', 'exposed_users=10、checkout_users=7、O06=9999 至少各解释一次。', 'cannot_prove 不宣称真实增长、活动有效、JOIN、归因、趋势或看板发布。'],
  },
  independentLab: {
    title: '独立变式：审查 AOV 上涨是否来自异常大单',
    scenario: '运营只给一句话：AOV=2077.00，很高，说明用户愿意买更贵。你要用 W4D4 的审查格式判断这是否可能是异常值均值假象。',
    conceptIds: ['rise-claim-audit', 'outlier-average-trap', 'distribution-guard-check', 'metric-rise-decision-boundary'],
    changedConditions: ['metric_name 固定为 aov_amount。', 'guardrail_metric 必须包含 median_amount=89.00 和 max_amount=9999.00。', 'sample_check 必须解释 O06。', '结论只能说存在 outlier_average 风险，不能说真实客单价上涨。'],
    task: '写出 case_id=MR03、metric_name=aov_amount、old_value 或 comparison_value、new_value=2077.00、risk_type=outlier_average、sample_check=O06、guardrail_metric=median_amount=89.00; max_amount=9999.00、distribution_guard、cannot_prove 和 next_review_task。',
    predictionPrompt: '你预测 AOV=2077.00 能否代表典型订单？为什么必须同时看 median_amount 和 max_amount？',
    evidenceRequirements: ['必须写 aov_amount=2077.00。', '必须写 median_amount=89.00。', '必须写 max_amount=9999.00 和 O06。', '必须说明不能证明真实客单价上涨或活动有效。'],
    passCriteria: ['风险类型明确为 outlier_average。', '护栏指标包含 median_amount 和 max_amount。', 'sample_check 至少解释 O06。', '没有提前完成 JOIN、归因、趋势或真实看板发布。'],
    remediation: { label: '回看异常值均值假象', sectionId: 'concepts', anchor: 'concept-outlier-average-trap' },
  },
  exercises: [
    exercise('w4d4-denominator-shift', ['概念与边界', '机制推演'], ['denominator-shift-trap', 'rise-claim-audit'], '看到 4/7 高于 4/10 时，最稳妥的第一句判断是什么？', ['先标记 denominator_shift，因为分母从 exposed_users=10 换成 checkout_users=7', '转化率已经真实上涨', '说明活动已经有效'], 0, '4/7 和 4/10 的分母不同，只能先标记分母变化风险。'),
    exercise('w4d4-survivor', ['证据判断'], ['survivorship-bias-trap'], '为什么 checkout_to_pay_24h 不能代表全部曝光用户？', ['它只观察进入 checkout_view 的 7 个用户，未进入结算页的曝光用户被排除', '因为 SQL 不能计算 24 小时窗口', '因为所有支付都是测试事件'], 0, '结算后转化率只覆盖后段幸存样本，不能推广到全部曝光用户。'),
    exercise('w4d4-outlier', ['工作场景'], ['outlier-average-trap', 'distribution-guard-check'], 'AOV=2077.00 时，哪条周会表述最稳妥？', ['AOV 受 O06=9999 影响，median_amount=89，不能直接代表典型订单', '典型订单就是 2077 元', '客单价已经证明真实上涨'], 0, '均值必须与中位数和最大值一起解释，不能单独代表典型订单。'),
    exercise('w4d4-composition', ['综合变式', '证据判断'], ['composition-mix-shift', 'misleading-rise-case-table'], '总体指标上涨但没有分组信息时，下一步最应该补什么？', ['按渠道、阶段或金额桶补 group_key 与组内指标，检查 composition_mix', '直接发布看板', '删除异常订单后宣布成功'], 0, '总体上涨可能来自样本构成变化，需要补分组复核任务。'),
    exercise('w4d4-boundary', ['综合变式', '概念与边界'], ['metric-rise-decision-boundary', 'misleading-rise-case-table'], '哪条 misleading-rise-review.md 结论没有越界？', ['本地教学样本存在分母、幸存样本和异常值误导风险；不能证明真实增长、JOIN、归因、趋势或看板可发布', '三类风险已经证明活动失败', 'AOV 高说明运营策略成功'], 0, 'W4D4 的成果只证明误导风险需要复核，不证明真实原因或业务结果。'),
  ],
  deliverable: {
    title: '上涨误导案例分析',
    conceptIds: [...conceptIds],
    purpose: '把教学模拟中的可疑上涨写成可复核案例，逐条说明分母变化、幸存者偏差、异常大单、样本构成和分布护栏如何限制结论。',
    whenToUse: '当周会、复盘或需求评审中有人把更高的指标值直接解释成业务变好时使用。',
    audience: '未来学习 W4D5 的自己、数据同事、运营复盘参与者和指标评审者。',
    fields: [
      { name: 'case_id', meaning: '上涨误导案例编号，如 MR01、MR02、MR03。', source: 'misleading-rise-review.md' },
      { name: 'metric_name', meaning: '被审查的指标名称，如 exposure_to_pay、checkout_to_pay_24h、aov_amount。', source: 'W4D3 指标计算记录' },
      { name: 'old_value', meaning: '被比较的原值或较低口径结果。', source: 'metric-calculation.md' },
      { name: 'new_value', meaning: '看起来更高的新值或另一口径结果。', source: 'metric-calculation.md' },
      { name: 'claimed_rise', meaning: '原始上涨说法，必须保留为待审查声明。', source: '周会材料或运营口头说法' },
      { name: 'risk_type', meaning: '风险类型：denominator_shift、survivorship_bias、outlier_average 或 composition_mix。', source: 'W4D4 三类假象检查' },
      { name: 'denominator_check', meaning: '分母是否变化，写 exposed_users、checkout_users 或不适用。', source: 'W4D3 分母结果' },
      { name: 'survivor_check', meaning: '是否只看后段幸存样本，写被排除人群。', source: '漏斗阶段样本' },
      { name: 'outlier_check', meaning: '是否有极端值拉动均值，写 O06 或不适用。', source: '支付订单样本' },
      { name: 'guardrail_metric', meaning: '护栏指标，如 median_amount、max_amount、sample_size 或 group_key。', source: '分布和样本构成检查' },
      { name: 'sample_check', meaning: '具体样本核对，如 exposed_users=10、checkout_users=7、O06=9999。', source: '教学样本观察' },
      { name: 'can_prove', meaning: '这条案例在本地教学中能证明什么误导风险。', source: '证据边界' },
      { name: 'cannot_prove', meaning: '不能证明真实增长、活动有效、JOIN、归因、趋势或看板可发布。', source: '证据边界' },
      { name: 'next_review_task', meaning: '下一步复核任务，如补分组、查生产口径或交给 W4D5 指标评审。', source: '课程边界' },
    ],
    badExample: 'misleading-rise-review.md\n\n指标都涨了，checkout_to_pay_24h=0.5714 比 0.4000 高，AOV=2077，所以活动有效，可以发周报。',
    badReasons: ['没有 case_id、old_value、new_value 和 risk_type。', '没有检查 exposed_users=10 与 checkout_users=7 的分母变化。', '没有解释 O06=9999、median_amount=89 和 max_amount=9999。', '把本地教学样本越界成真实业务结论。'],
    revisionSteps: ['补 case_id、metric_name、old_value、new_value 和 claimed_rise。', '为每条案例选择 denominator_shift、survivorship_bias 或 outlier_average。', '补 denominator_check、survivor_check、outlier_check 和 guardrail_metric。', '写 sample_check、can_prove、cannot_prove。', 'next_review_task 只指向补分组、生产口径确认或 W4D5 指标评审。'],
    goodExample: 'misleading-rise-review.md\n\ncase_id: MR01\nmetric_name: checkout_to_pay_24h vs exposure_to_pay\nold_value: exposure_to_pay=0.4000\nnew_value: checkout_to_pay_24h=0.5714\nclaimed_rise: 结算后 24 小时转化率更高，所以转化表现变好\nrisk_type: denominator_shift + survivorship_bias\ndenominator_check: old denominator exposed_users=10; new denominator checkout_users=7，分母从全部曝光用户换成后段结算用户\nsurvivor_check: 只观察进入 checkout_view 的 7 个用户，未进入结算页的 3 个曝光用户被排除\noutlier_check: 不适用，本条是比例指标\nguardrail_metric: 同时展示 exposed_users、checkout_users、paid_same_day_users=4、paid_within_24h_users=4\nsample_check: 4/10=0.4000 与 4/7=0.5714 不能直接当同一趋势比较\ncan_prove: 能证明本地教学样本中该上涨声明存在分母变化和幸存者偏差风险\ncannot_prove: 不能证明真实生产增长、活动有效、JOIN 对账、归因、趋势或看板可发布\nnext_review_task: W4D5 指标评审前补同口径转化比较和分组复核\n\ncase_id: MR03\nmetric_name: aov_amount\nold_value: comparison_value=median_amount=89.00\nnew_value: aov_amount=2077.00\nclaimed_rise: AOV 很高，所以典型订单金额上涨\nrisk_type: outlier_average + distribution_guard\ndenominator_check: unique_paid_orders=5，订单粒度已按 order_id 去重\nsurvivor_check: 不适用，本条先检查金额分布\noutlier_check: O06=9999 拉高 AVG\nguardrail_metric: sample_size=5; median_amount=89.00; max_amount=9999.00\nsample_check: aov_amount=2077.00 与 median_amount=89.00 差距过大\ncan_prove: 能证明本地教学样本中 AOV 受异常大单影响，不能单独代表典型订单\ncannot_prove: 不能证明真实客单价上涨、异常订单有效性、活动原因、JOIN、趋势或看板可发布\nnext_review_task: 补金额分布和生产订单有效性确认\n',
    guidedPrompts: ['写 MR01 分母变化案例。', '写 MR02 幸存者偏差案例。', '写 MR03 异常值均值案例。', '补 composition_mix 下一步。', '补 guardrail_metric。', '补 can_prove/cannot_prove。'],
    blankTemplate: 'misleading-rise-review.md\n\ncase_id: \nmetric_name: \nold_value: \nnew_value: \nclaimed_rise: \nrisk_type: \ndenominator_check: \nsurvivor_check: \noutlier_check: \nguardrail_metric: \nsample_check: \ncan_prove: \ncannot_prove: \nnext_review_task: \n',
    standardTemplate: 'misleading-rise-review.md\n\ncase_id: MR01\nmetric_name: checkout_to_pay_24h vs exposure_to_pay\nold_value: exposure_to_pay=0.4000\nnew_value: checkout_to_pay_24h=0.5714\nclaimed_rise: 结算后 24 小时转化率更高，所以转化表现变好\nrisk_type: denominator_shift + survivorship_bias\ndenominator_check: exposed_users=10 vs checkout_users=7，分母从曝光用户换成结算用户\nsurvivor_check: 只看 checkout_users=7，未进入 checkout 的曝光用户被排除\noutlier_check: 不适用\nguardrail_metric: exposed_users=10; checkout_users=7; paid_same_day_users=4; paid_within_24h_users=4\nsample_check: 4/10=0.4000 与 4/7=0.5714 不能直接当同一趋势比较\ncan_prove: 能证明本地教学样本中该上涨声明有分母变化和幸存者偏差风险\ncannot_prove: 不能证明真实生产增长、活动有效、JOIN、归因、趋势或看板可发布\nnext_review_task: W4D5 指标评审前补同口径比较和分组复核\n\ncase_id: MR02\nmetric_name: composition_mix\nold_value: group_key before review\nnew_value: group_key after review\nclaimed_rise: 总体指标更高，所以每个组都变好了\nrisk_type: composition_mix\ndenominator_check: 需要按渠道、阶段或金额桶复核\nsurvivor_check: 不适用\noutlier_check: 不适用\nguardrail_metric: group_key; bucket_count; sample_size\nsample_check: 需要先补分组后再比较总体与组内差异\ncan_prove: 能证明总体上涨可能来自样本构成变化\ncannot_prove: 不能证明每个用户群都上涨或真实生产结论成立\nnext_review_task: W4D5 指标评审前补分组复核\n\ncase_id: MR03\nmetric_name: aov_amount\nold_value: median_amount=89.00\nnew_value: aov_amount=2077.00\nclaimed_rise: AOV 很高，所以典型订单金额上涨\nrisk_type: outlier_average + distribution_guard\ndenominator_check: unique_paid_orders=5，订单粒度已按 order_id 去重\nsurvivor_check: 不适用\noutlier_check: O06=9999 拉高平均值\nguardrail_metric: sample_size=5; median_amount=89.00; max_amount=9999.00\nsample_check: aov_amount=2077.00 与 median_amount=89.00 差距过大\ncan_prove: 能证明本地教学样本中 AOV 受异常大单影响，不能单独代表典型订单\ncannot_prove: 不能证明真实客单价上涨、异常订单有效性、活动原因、JOIN、趋势或看板可发布\nnext_review_task: 补金额分布和生产订单有效性确认\n',
    checklist: ['至少写 3 条上涨误导案例。', '每条都有 case_id、metric_name、old_value、new_value、claimed_rise 和 risk_type。', 'denominator_shift、survivorship_bias、outlier_average 至少各出现一次。', 'exposed_users=10、checkout_users=7、aov_amount=2077.00、median_amount=89.00、max_amount=9999.00 和 O06 至少各解释一次。', 'cannot_prove 明确排除真实生产增长、活动有效、JOIN、归因、趋势或看板发布。', 'next_review_task 指向 W4D5 指标评审、同口径比较或分组复核。'],
  },
  memory: {
    conceptIds: [...conceptIds],
    anchors: ['上涨先作为声明审查，不先写原因。', '比例上涨先查分母是否换了。', '后段高转化可能来自幸存者偏差。', '均值上涨必须看 median、max 和异常样本。', '审查表只能证明误导风险，不能证明真实增长。'],
    closedBookPrompt: '闭卷复述 W4D4 上涨审查链路：W4D3 指标结果 → rise claim → denominator_shift → survivorship_bias → outlier_average → distribution_guard → misleading-rise-review.md。',
    microOperation: '不看答案，写一条 AOV 异常值案例的 risk_type、sample_check、guardrail_metric、can_prove 和 cannot_prove。',
    unresolvedPrompt: '写出进入 W4D5 前你最担心被误写进周会的一条上涨结论，并说明要补哪一个评审问题。',
    reviewStages: [
      { stage: 'D1', task: '闭卷写出 misleading-rise-review.md 的 14 个字段，并说明三类 risk_type。' },
      { stage: 'D3', task: '复原 4/10 与 4/7 的分母变化和幸存者偏差解释。' },
      { stage: 'D7', task: '解释 O06 为什么能拉高 AOV，但 median_amount=89 限制典型订单结论。' },
      { stage: 'D14', task: '不看模板，写出 denominator_check、survivor_check 和 outlier_check。' },
      { stage: 'D30', task: '把一个“指标上涨”口号改写成三条误导风险案例。' },
      { stage: 'D60', task: '说明 W4D4 与 W4D5 的边界：误导案例分析 vs 指标评审。' },
    ],
  },
  nextLesson: { id: 'W4D5', title: '指标评审会预告', bridge: '下一课才把误导案例带进指标评审会，形成评审问题、修改建议和发布门禁；W4D4 只交付本地教学上涨假象分析。' },
}
