import type { DayId } from './types'
import type { Day01FrameworkPlan } from './day01Framework'

export const w4d4Framework: Day01FrameworkPlan = {
  dayId: 'W4D4',
  label: '三种上涨假象',
  chapters: [
    {
      id: 'chapter-1',
      number: 1,
      session: 1,
      timeMinutes: 8,
      title: '建立任务：先审查上涨声明',
      lead: 'W4D4 承接 W4D3 的指标计算结果，把“上涨了”这类 rise claim 先拆成可审查案例，不急着写业务原因。',
      conceptIds: ['rise-claim-audit'],
      semanticSections: ['scenario', 'objectives', 'prerequisites'],
      practice: {
        prompt: '看到 checkout_to_pay_24h 高于 exposure_to_pay 时，W4D4 最先做什么？',
        options: ['写入 misleading-rise-review.md，先审查 old_value、new_value、claimed_rise 和风险类型', '宣布活动有效', '发布生产看板'],
        answerIndex: 0,
        explanation: 'W4D4 的入口是上涨声明审查，只能先形成待复核案例。',
      },
      retellPrompt: '用两三句话说明：为什么 W4D4 不能把“更高”直接写成业务变好？',
      retellRubric: ['提到上涨声明', '提到 old_value/new_value', '提到至少一种误导风险', '提到 cannot_prove', '没有写成真实增长结论'],
    },
    {
      id: 'chapter-2',
      number: 2,
      session: 1,
      timeMinutes: 13,
      title: '模型一：分母变化会制造上涨',
      lead: '4/7 高于 4/10，不一定是转化改善；先检查分母是否从 exposed_users=10 换成 checkout_users=7。',
      conceptIds: ['denominator-shift-trap'],
      semanticSections: ['concepts'],
      practice: {
        prompt: '哪条判断最符合 denominator_shift？',
        options: ['0.5714 和 0.4000 的比较基准不同，先标记分母变化风险', '0.5714 更高，所以转化真实变好', '分母越小越能代表全量用户'],
        answerIndex: 0,
        explanation: '比例指标上涨必须先查分母是否同对象、同窗口、同去重键。',
      },
      retellPrompt: '闭卷解释 exposed_users=10 与 checkout_users=7 为什么不能直接当趋势比较。',
      retellRubric: ['说清 10 和 7', '说清分母变化', '说明不能直接下趋势结论'],
    },
    {
      id: 'chapter-3',
      number: 3,
      session: 1,
      timeMinutes: 14,
      title: '模型二：幸存样本和异常均值',
      lead: '后段漏斗只剩更高意愿用户，AOV 又可能被 O06=9999 拉高；这两类上涨都要先加护栏。',
      conceptIds: ['survivorship-bias-trap', 'outlier-average-trap'],
      semanticSections: ['concepts', 'diagram'],
      practice: {
        prompt: 'AOV=2077.00、median_amount=89.00、max_amount=9999.00 时，最稳妥的解释是什么？',
        options: ['均值可能被 O06 异常大单拉高，不能代表典型订单', '典型订单就是 2077 元', '客单价已证明真实上涨'],
        answerIndex: 0,
        explanation: '均值必须和中位数、最大值一起解释，才能避免异常值均值假象。',
      },
      retellPrompt: '按“幸存样本、O06、median、max”复述两类误导风险。',
      retellRubric: ['提到 checkout_users=7', '提到被排除用户', '提到 O06=9999', '提到 median/max 护栏'],
    },
    {
      id: 'chapter-4',
      number: 4,
      session: 1,
      timeMinutes: 10,
      title: '第一次复述检查：上涨不是结论',
      lead: '这一章不增加新术语。你要把 rise claim、分母、幸存样本、异常值和 cannot_prove 连成一条安全复述。',
      conceptIds: ['rise-claim-audit', 'denominator-shift-trap', 'survivorship-bias-trap', 'outlier-average-trap'],
      semanticSections: ['concepts', 'diagram'],
      practice: {
        prompt: '哪条 W4D4 表述没有越界？',
        options: ['本地教学样本存在 denominator_shift、survivorship_bias 和 outlier_average 风险', '已经证明活动有效', '已经证明真实增长'],
        answerIndex: 0,
        explanation: 'W4D4 只证明上涨声明存在误导风险，不证明真实业务结果。',
      },
      retellPrompt: '用“rise claim -> 三类检查 -> cannot_prove”复述今天前半段。',
      retellRubric: ['rise claim 先行', '三类检查清楚', '结论边界不过界'],
    },
    {
      id: 'chapter-5',
      number: 5,
      session: 2,
      timeMinutes: 16,
      title: '操作模型：分布护栏与案例表',
      lead: '把样本数、中位数、最大值、group_key 和风险标签写进 misleading-rise-review.md，让每条上涨都能被复核。',
      conceptIds: ['composition-mix-shift', 'distribution-guard-check', 'misleading-rise-case-table'],
      semanticSections: ['demonstration', 'guided-lab'],
      practice: {
        prompt: '总体指标上涨但没有分组信息时，下一步最应该补什么？',
        options: ['按渠道、阶段或金额桶补 group_key 与组内指标', '直接宣布每组都上涨', '只保留均值'],
        answerIndex: 0,
        explanation: '总体上涨可能来自样本构成变化，需要用分组和分布护栏补证据。',
      },
      retellPrompt: '解释 guardrail_metric 和 misleading-rise-review.md 如何让上涨案例可复核。',
      retellRubric: ['提到 sample_size/median/max', '提到 group_key', '提到案例字段', '没有替代生产评审'],
    },
    {
      id: 'chapter-6',
      number: 6,
      session: 2,
      timeMinutes: 12,
      title: '责任与证据边界：风险不是原因',
      lead: 'denominator_shift、survivorship_bias 和 outlier_average 只能说明上涨声明可疑，不能自动解释业务原因。',
      conceptIds: ['metric-rise-decision-boundary'],
      semanticSections: ['independent-lab', 'feedback'],
      practice: {
        prompt: '哪条 cannot_prove 最符合 W4D4？',
        options: ['不能证明真实生产增长、活动有效、JOIN、归因、趋势或看板可发布', '已经证明活动失败', '已经完成指标评审'],
        answerIndex: 0,
        explanation: '误导风险是审查结论，不是业务因果结论。',
      },
      retellPrompt: '用“能证明／不能证明／下一步”说明上涨审查边界。',
      retellRubric: ['能证明误导风险', '不能证明真实增长', '下一步指向 W4D5 或补复核'],
    },
    {
      id: 'chapter-7',
      number: 7,
      session: 2,
      timeMinutes: 18,
      title: '实验、misleading-rise-review.md 与最终复述',
      lead: '最后完成六条上涨审查路径、针对性练习和成果门禁：每条案例都要有字段、样本证据、护栏和有限结论。',
      conceptIds: [
        'rise-claim-audit',
        'denominator-shift-trap',
        'survivorship-bias-trap',
        'outlier-average-trap',
        'composition-mix-shift',
        'distribution-guard-check',
        'misleading-rise-case-table',
        'metric-rise-decision-boundary',
      ],
      semanticSections: ['exercises', 'deliverable', 'memory', 'completion'],
      practice: {
        prompt: '一份合格 misleading-rise-review.md 最关键的组合是什么？',
        options: ['case_id、risk_type、sample_check、guardrail_metric、can_prove、cannot_prove 和 next_review_task', '一句“涨了”', '真实生产归因报告'],
        answerIndex: 0,
        explanation: '成果必须可复核、不过界，并把下一步交给 W4D5 指标评审。',
      },
      retellPrompt: '最终复述三种上涨假象，并说明 misleading-rise-review.md 能证明什么、不能证明什么。',
      retellRubric: ['三类假象齐全', '字段齐全', '提到 W4D5', '不把风险写成原因'],
    },
  ],
}

export function getW4D4FrameworkPlan(dayId: DayId): Day01FrameworkPlan | undefined {
  return dayId === 'W4D4' ? w4d4Framework : undefined
}
