import type { DailyCourse, Exercise } from './types'

const conceptIds = [
  'join-key-matching',
  'join-preserve-rule',
  'inner-join-filter',
  'left-join-preserve-left',
  'right-join-preserve-right',
  'full-join-preserve-both',
  'join-grain-amplification',
  'anti-join-gap-audit',
  'join-audit-map',
] as const

const prerequisiteConceptIds = [
  'row-level-answer',
  'quality-flagged-answer',
  'metric-grain',
  'null-value',
  'duplicate-row',
  'test-data-flag',
  'quality-evidence-boundary',
  'distinct-result',
] as const

function exercise(
  id: string,
  categories: Exercise['categories'],
  ids: string[],
  prompt: string,
  options: string[],
  answerIndex: number,
  referenceAnswer: string,
): Exercise {
  return {
    id,
    kind: 'single-choice',
    categories,
    conceptIds: ids,
    prompt,
    hint: '先看哪一边的行必须被保留，再判断未匹配行会不会变成 NULL、哪一步会放大行数、哪一步需要先聚合再连接。',
    options: options.map((label, index) => ({
      label,
      rationale: index === answerIndex
        ? '这项把保留规则、匹配键、粒度和证据边界连起来。'
        : '这项要么保留规则说错了，要么把放大、缺口或对账边界越界成生产结论。',
      couldBeTrueWhen: index === answerIndex
        ? '当学习者正在完成 W5D2 的 JOIN 对照图。'
        : '只有后续 W5D3-W5D6 再做更完整的 JOIN 复盘、分析和报告，才可能支撑更强判断。',
    })),
    answerIndex,
    referenceAnswer,
    reasoning: [
      'W5D2 的第一目标不是把三张表拼起来，而是先能说清 INNER、LEFT、RIGHT、FULL 各自保留谁。',
      '同一条订单在一对多 JOIN 后会被复制，所以唯一订单数和总金额必须先对账。',
      '本日只在本地教学库里做 JOIN 对照和缺口识别，不证明真实生产分析正确。',
    ],
    rubric: ['保留规则说清楚', '连接键说清楚', '放大与缺口分开说明', '证据边界不过界说明'],
    commonErrors: [
      { error: '把 LEFT JOIN 写成一定丢左表行', reason: 'LEFT JOIN 保留左表，丢失的是右表未匹配行。' },
      { error: '把 WHERE 里的右表条件当成 ON 里的条件', reason: '对外连接来说，这会把 NULL 行过滤掉，改变保留规则。' },
    ],
    remediation: { label: '回看 JOIN 对照图', sectionId: 'diagram', anchor: 'w5d2-join-audit-map' },
  }
}

export const w5d2: DailyCourse = {
  id: 'W5D2',
  contentVersion: 'w5d2-join-contrast-day01-v2',
  week: 5,
  day: 2,
  title: '四种 JOIN 保留规则',
  subtitle: '先看 INNER、LEFT、RIGHT、FULL 的保留规则，再用 users、orders 和 order_items 的本地教学库画出 JOIN 对照图、找到一对多放大点和未匹配键；本日不提前写完整分析报告。',
  duration: { core: 30, standard: 45, extension: 78, full: 128 },
  coreConceptGroups: [
    {
      id: 'join-key-and-preserve-side',
      title: '先说清连接键和保留哪一边',
      conceptIds: ['join-key-matching', 'join-preserve-rule', 'inner-join-filter'],
      summary: 'JOIN 不是把表简单叠起来，而是先用连接键找匹配，再按类型决定保留左表、右表、两边还是只留匹配行。',
      boundary: '能解释 INNER JOIN 为什么只保留匹配行；不能证明真实生产表结构已经完全正确。',
    },
    {
      id: 'outer-join-rules',
      title: '四种 JOIN 的保留规则不同',
      conceptIds: ['left-join-preserve-left', 'right-join-preserve-right', 'full-join-preserve-both'],
      summary: 'LEFT JOIN 保留左表，RIGHT JOIN 保留右表，FULL JOIN 保留两边；未匹配的一侧会补 NULL。',
      boundary: '能判断未匹配行落在哪一边；不能把 NULL 自动解释成业务结论。',
    },
    {
      id: 'join-audit-and-grain',
      title: '一对多放大要先审查粒度，再写对账',
      conceptIds: ['join-grain-amplification', 'anti-join-gap-audit', 'join-audit-map'],
      summary: '一条订单如果对应多条明细，JOIN 会复制订单级字段；要先把明细聚合回订单粒度，再做对账和缺口检查。',
      boundary: '能写出 rows_before、rows_after、unique_keys 和 amount_gap；不能直接把 JOIN 后的金额当最终 GMV。',
    },
  ],
  prerequisiteConceptIds: [...prerequisiteConceptIds],
  learningPaths: {
    '30': {
      guidedStepIndices: [0, 1, 2, 3, 4, 5],
      guidedRecordIndices: [0, 1, 2, 3, 4, 5],
      exerciseCount: 3,
      deliverablePromptCount: 6,
      deliverableChecklistIndices: [0, 1, 2, 3, 4],
      deliverableMinimumContributionCharacters: 260,
    },
    '45': {
      guidedStepIndices: [0, 1, 2, 3, 4, 5],
      guidedRecordIndices: [0, 1, 2, 3, 4, 5],
      exerciseCount: 5,
      deliverablePromptCount: 6,
      deliverableChecklistIndices: [0, 1, 2, 3, 4, 5],
      deliverableMinimumContributionCharacters: 390,
    },
  },
  primaryGoal: '提交 `reconciliation.md`：按 users、orders 和 order_items 的 JOIN 对账记录列出 join_case_id、left_table、right_table、join_type、preserve_rule、join_key、rows_before、rows_after、unique_keys、unmatched_keys、amount_gap、can_prove、cannot_prove、next_sql_task。',
  scenario: {
    role: '你是刚完成 W4 指标口径、准备进入 JOIN 对账的产品经理。',
    situation: '现在有三张教学表：users、orders 和 order_items。有人把 orders 直接 JOIN 到明细表后，GMV 看起来被放大了；也有人担心未匹配订单和未匹配明细被静默吞掉。',
    question: '怎样把“JOIN 后数字变了”拆成保留规则、连接键、粒度放大、未匹配缺口和重算后的对账记录？',
    stakes: '如果不先说清哪一边被保留、哪一边会补 NULL，分析就会把一对多放大、缺失记录和真实业务变化混在一起。',
  },
  objectives: [
    { id: 'w5d2-objective-rule', text: '能说清四种 JOIN 各自保留哪一边', evidence: 'JOIN 对照图中能把 INNER、LEFT、RIGHT、FULL 的保留规则和 NULL 补位写出来。' },
    { id: 'w5d2-objective-gap', text: '能找出未匹配键并解释它们落在哪一边', evidence: 'reconciliation.md 中能分别列出缺 user 的订单和缺 order 的明细。' },
    { id: 'w5d2-objective-grain', text: '能识别一对多 JOIN 的放大点', evidence: '对账记录里能写出 joined_rows、unique_orders 和 wrong_gmv=740。' },
    { id: 'w5d2-objective-boundary', text: '能说明 JOIN 对照图的证据边界', evidence: 'cannot_prove 里明确写出不能直接证明真实生产 GMV、原因、趋势或分析报告已完成。' },
  ],
  prerequisites: [
    {
      id: 'w5d2-week4-readiness',
      conceptIds: [...prerequisiteConceptIds],
      prompt: '你能把“行级答案、质量标注、粒度、NULL、重复和证据边界”串起来吗？',
      passDescription: '能说明为什么一条订单在明细表里会被复制，为什么缺失记录不等于业务消失。',
      remediationLabel: '回到 W4D4 补粒度和证据边界',
      remediationTarget: '#/lesson/W4D4',
      remediation: {
        purpose: 'W5D2 可以提前阅读，但没有 W4 的粒度和质量边界，JOIN 对照只会变成表连接演示。',
        steps: ['复述 W4D4 的 unique_paid_orders、aov_amount、median_amount 和 max_amount。', '复述 W4D4 的 denominator_shift、survivorship_bias 和 outlier_average。', '把“数谁”和“缺谁”两件事分开写。'],
        successCheck: '能把 JOIN 的保留规则、放大点和缺口拆成可复核记录。',
      },
    },
  ],
  concepts: [
    {
      id: 'join-key-matching',
      prerequisiteConceptIds: ['metric-grain', 'distinct-result'],
      term: '连接键匹配',
      english: 'Join Key Matching',
      definition: '连接键匹配是用两张表都存在的字段值把行配对；键值相同不代表业务一定相同，只代表可以被 JOIN 到一起。',
      why: '没有先确认连接键，JOIN 很容易把不同粒度的行拼错，或者把一对多关系误看成一对一。',
      problemSolved: '回答“这两张表到底凭什么连在一起”。',
      input: 'users.user_id、orders.user_id、orders.order_id、order_items.order_id 这样的共享字段。',
      output: '匹配成功的行对，以及没法配对的剩余行。',
      systemPosition: '位于 JOIN 的最前面，是所有保留规则的前提。',
      process: ['先找共同字段。', '确认字段值是否能唯一定位一行。', '记录不唯一与不匹配样本。'],
      owner: '产品经理先问连接键，SQL 再负责执行匹配。',
      notResponsibleFor: '不负责证明两个字段语义天然一致。',
      compareWith: '连接键回答“怎么连”；粒度回答“连完会不会被放大”。',
      evidence: ['users.user_id。', 'orders.user_id。', 'order_items.order_id。'],
      failureModes: ['把 user_id 当成 order_id。', '把不同表里同名字段误以为同一粒度。'],
      pmUse: '先说“用 order_id 连订单和明细，用 user_id 连订单和用户”。',
      correctExample: 'orders o JOIN order_items i ON o.order_id = i.order_id。',
      incorrectExample: '把订单表和明细表随便 INNER JOIN 一下。',
    },
    {
      id: 'join-preserve-rule',
      prerequisiteConceptIds: ['join-key-matching'],
      term: 'JOIN 保留规则',
      english: 'Join Preserve Rule',
      definition: 'JOIN 保留规则决定哪些未匹配行仍然出现在结果中，以及哪一边的空值会被补成 NULL。',
      why: '四种 JOIN 的差别，不在于能不能连，而在于没有匹配到时谁还要留下。',
      problemSolved: '回答“这次连接后谁会被保留，谁会被丢掉”。',
      input: '左表、右表、连接键和 JOIN 类型。',
      output: '匹配行、未匹配左行、未匹配右行和 NULL 补位。',
      systemPosition: '位于连接键之后、结果解释之前。',
      process: ['先明确 JOIN 类型。', '再说明保留哪一边。', '最后检查 NULL 行是否仍然在结果里。'],
      owner: '产品经理解释保留规则，SQL 负责执行。',
      notResponsibleFor: '不负责自动判断业务应该选哪一种 JOIN。',
      compareWith: '保留规则回答“留下谁”；连接键回答“怎么配”。',
      evidence: ['INNER JOIN 只留匹配。', 'LEFT JOIN 留左表全部行。', 'FULL JOIN 留两边未匹配行。'],
      failureModes: ['把 LEFT JOIN 说成只留匹配。', '把 NULL 行静默当成数据丢失。'],
      pmUse: '在评审里先说“这次要保留订单表全部行，再看用户是否缺失”。',
      correctExample: 'LEFT JOIN 会保留左表所有订单，右表没匹配到的用户字段补 NULL。',
      incorrectExample: 'LEFT JOIN 就是 INNER JOIN 的另一个名字。',
    },
    {
      id: 'inner-join-filter',
      prerequisiteConceptIds: ['join-preserve-rule'],
      term: 'INNER JOIN 只保留匹配行',
      english: 'Inner Join Filter',
      definition: 'INNER JOIN 只输出两边都匹配上的行，任何一边缺失都会被过滤掉。',
      why: '当你只关心两个集合的交集时，INNER JOIN 最直接；但它会主动丢掉未匹配样本。',
      problemSolved: '回答“为什么有些订单或明细在结果里消失了”。',
      input: '两个表以及它们的连接键。',
      output: '只包含两边都匹配成功的结果集，不保留任一侧缺口。',
      systemPosition: '位于保留规则的最严格一端。',
      process: ['找到可配对的记录。', '过滤掉任何一侧缺失的记录。', '记录被过滤掉的样本。'],
      owner: 'SQL 执行器负责过滤；产品经理负责提醒丢失的是谁。',
      notResponsibleFor: '不负责保留未匹配行，也不负责解释缺口产生原因。',
      compareWith: 'INNER JOIN 比 LEFT JOIN 更严格，比 FULL JOIN 更少结果。',
      evidence: ['只保留匹配行。', '未匹配用户不会出现在结果中。', '未匹配明细不会出现在结果中。'],
      failureModes: ['把消失的行误判成数据删除。', '忘记 INNER JOIN 会吞掉缺口样本。'],
      pmUse: '做交集类统计时才用 INNER JOIN；否则先问要不要保留缺口。',
      correctExample: 'orders INNER JOIN users ON orders.user_id = users.user_id。',
      incorrectExample: '用 INNER JOIN 也能看见所有缺失记录。',
    },
    {
      id: 'left-join-preserve-left',
      prerequisiteConceptIds: ['join-preserve-rule', 'inner-join-filter'],
      term: 'LEFT JOIN 保留左表',
      english: 'Left Join Preserve Left',
      definition: 'LEFT JOIN 会保留左表的所有行；右表匹配不上时，对应列会变成 NULL。',
      why: '当左表是你想完整保留的主表时，LEFT JOIN 能让缺失关系显性化，而不是被直接过滤掉。',
      problemSolved: '回答“为什么订单还在，但用户字段变成 NULL”。',
      input: '左表订单、右表用户或明细、以及连接键。',
      output: '左表全量行加上可匹配的右表信息。',
      systemPosition: '位于保留左侧事实的一端。',
      process: ['先决定左表是不是必须保留。', '连接右表并允许 NULL 补位。', '把未匹配样本单独标出来。'],
      owner: '产品经理决定是否以左表为主视角。',
      notResponsibleFor: '不负责自动修复右表缺失。',
      compareWith: 'LEFT JOIN 比 INNER JOIN 保留更多行，比 RIGHT JOIN 保留左侧更多信息。',
      evidence: ['订单表的全部行保留。', '用户缺失时 user_id 对应字段为 NULL。', 'O05 user U99 缺失。'],
      failureModes: ['在 WHERE 里筛掉右表字段，导致 LEFT JOIN 变成内连接。', '把 NULL 当作空白字符串。'],
      pmUse: '看订单是否完整时，优先 LEFT JOIN 用户表，再观察哪些订单找不到用户。',
      correctExample: 'orders LEFT JOIN users ON orders.user_id = users.user_id。',
      incorrectExample: 'LEFT JOIN 后再 WHERE users.user_id IS NOT NULL 才算保留左表。',
    },
    {
      id: 'right-join-preserve-right',
      prerequisiteConceptIds: ['join-preserve-rule', 'left-join-preserve-left'],
      term: 'RIGHT JOIN 保留右表',
      english: 'Right Join Preserve Right',
      definition: 'RIGHT JOIN 会保留右表的所有行；左表匹配不上时，左侧列补 NULL。',
      why: '如果右表才是你要完整盘点的一侧，RIGHT JOIN 只是把左 JOIN 的视角换了一边。',
      problemSolved: '回答“为什么明细还在，但订单字段变成 NULL”。',
      input: '右表订单或明细、左表关联表、连接键。',
      output: '右表全量行加上可匹配的左表信息。',
      systemPosition: '位于保留右侧事实的一端。',
      process: ['先决定右表是不是必须保留。', '连接左表并允许 NULL 补位。', '把未匹配样本单独标出来。'],
      owner: 'SQL 可以直接写 RIGHT JOIN，也可以换表顺序改成 LEFT JOIN。',
      notResponsibleFor: '不负责让右表缺失自动消失。',
      compareWith: 'RIGHT JOIN 和 LEFT JOIN 只是视角互换，保留规则对称。',
      evidence: ['右表全量行保留。', '左表缺失时左侧字段为 NULL。', 'SQLite 支持 RIGHT JOIN。'],
      failureModes: ['以为 RIGHT JOIN 比 LEFT JOIN 更“高级”。', '忘记它只是换了方向。'],
      pmUse: '当右表是主表时，把 LEFT JOIN 反过来或直接写 RIGHT JOIN。',
      correctExample: 'users RIGHT JOIN orders ON users.user_id = orders.user_id。',
      incorrectExample: 'RIGHT JOIN 会比 LEFT JOIN 多出新的业务能力。',
    },
    {
      id: 'full-join-preserve-both',
      prerequisiteConceptIds: ['left-join-preserve-left', 'right-join-preserve-right'],
      term: 'FULL JOIN 保留两边',
      english: 'Full Join Preserve Both',
      definition: 'FULL JOIN 会保留左右两边所有行；两边都没有匹配到时，各自缺失的一侧补 NULL。',
      why: '当你既想看左表缺了什么，也想看右表缺了什么时，FULL JOIN 最适合做缺口对照。',
      problemSolved: '回答“双方各自缺了哪些行”。',
      input: '两个都需要盘点的表和它们的连接键。',
      output: '匹配行、左侧缺口、右侧缺口和 NULL 补位。',
      systemPosition: '位于完整缺口对照的一端。',
      process: ['把左右两边都视为要保留的对象。', '连接并检查两个方向的未匹配样本。', '把缺口分别写出来。'],
      owner: '产品经理用 FULL JOIN 先看缺口，再决定补哪边。',
      notResponsibleFor: '不负责自动解决缺口，只负责把缺口摊开。',
      compareWith: 'FULL JOIN 比 LEFT/RIGHT JOIN 更适合做全量缺口盘点。',
      evidence: ['左右两边未匹配都能看到。', 'NULL 不是丢数据，而是缺口标记。', '可直接盘点两边缺失。'],
      failureModes: ['把 FULL JOIN 写成左右都必须完全一致。', '看到 NULL 就删行。'],
      pmUse: '当你要同时看订单缺用户、用户缺订单时，用 FULL JOIN 先把缺口摊开。',
      correctExample: 'orders FULL JOIN users ON orders.user_id = users.user_id。',
      incorrectExample: 'FULL JOIN 只会保留一边的行。',
    },
    {
      id: 'join-grain-amplification',
      prerequisiteConceptIds: ['join-key-matching', 'inner-join-filter'],
      term: '一对多放大',
      english: 'Join Grain Amplification',
      definition: '一对多放大是指左表一行匹配到右表多行时，左表字段会被复制多次，导致行数、金额或计数被放大。',
      why: 'O02 有两条明细，O01 也有两条明细；如果直接 SUM(orders.paid_amount)，订单级金额就会重复累加。',
      problemSolved: '回答“为什么 JOIN 后 GMV 变成 740 而不是 440”。',
      input: '订单表、订单明细表、连接键和粒度。',
      output: '放大后的 joined_rows、unique_orders 和 wrong_gmv。',
      systemPosition: '位于连接之后、对账之前。',
      process: ['先看左表一行能匹配右表几行。', '计算放大倍数。', '把订单级金额与明细级行数分开看。'],
      owner: 'SQL 负责把复制现象显影；产品经理负责避免把复制后的金额当结论。',
      notResponsibleFor: '不负责把放大误读成收入增长。',
      compareWith: '放大不是数据变多，而是同一订单被复制到多行里。',
      evidence: ['correct_gmv=440。', 'wrong_gmv=740。', 'O01 和 O02 都被重复复制。'],
      failureModes: ['把 joined_rows 当成唯一订单数。', '把重复复制的订单金额当 GMV。'],
      pmUse: '看到 JOIN 后金额翻倍时，先看是不是订单级字段被明细行复制了。',
      correctExample: 'orders JOIN order_items 后再 SUM(orders.paid_amount) 会放大。',
      incorrectExample: 'JOIN 后行数变多，就说明业务收入真的涨了。',
    },
    {
      id: 'anti-join-gap-audit',
      prerequisiteConceptIds: ['left-join-preserve-left', 'full-join-preserve-both'],
      term: 'Anti Join 缺口审查',
      english: 'Anti Join Gap Audit',
      definition: 'Anti Join 缺口审查是先做 LEFT JOIN，再筛出右表键为 NULL 的行，用来找出没有匹配到的左表样本。',
      why: '没有匹配记录不等于业务没发生，可能只是维表缺失、埋点没到或连接键错了。',
      problemSolved: '回答“哪些订单没有用户记录，哪些明细没有订单记录”。',
      input: 'LEFT JOIN 结果和右表 NULL 列。',
      output: 'unmatched_orders 和 unmatched_items。',
      systemPosition: '位于对账阶段，是发现缺口的最直接方法。',
      process: ['先保留左表全部行。', '再筛出右表 NULL。', '把缺口行单独列出来。'],
      owner: '产品经理用它定位缺口，SQL 负责把缺口行显形。',
      notResponsibleFor: '不负责证明缺口原因，只负责先找到缺口。',
      compareWith: 'Anti Join 是缺口搜索；FULL JOIN 是双向缺口盘点。',
      evidence: ['O05 对应的 user 缺失。', 'I08 的 order_id=MISSING。', 'NULL 行可以被单独列出。'],
      failureModes: ['把 NULL 缺口直接删掉。', '把缺口当成业务不存在。'],
      pmUse: '先找没有用户记录的订单，再找没有订单记录的明细。',
      correctExample: 'orders LEFT JOIN users ON orders.user_id = users.user_id WHERE users.user_id IS NULL。',
      incorrectExample: '看到 NULL 就代表这条记录没价值。',
    },
    {
      id: 'join-audit-map',
      prerequisiteConceptIds: ['join-grain-amplification', 'anti-join-gap-audit'],
      term: 'JOIN 对账记录',
      english: 'Join Audit Map',
      definition: 'JOIN 对账记录是把每次连接前后的行数、唯一键、放大倍数、未匹配键和金额差异写在一张可复核表里。',
      why: '只有结果，没有对账，就不知道数字是因为 JOIN 变了，还是因为业务真的变了。',
      problemSolved: '回答“这次连接能证明到哪里，不能证明到哪里”。',
      input: 'JOIN 前后的 row count、unique_keys、unmatched keys 和 amount_gap。',
      output: 'reconciliation.md。',
      systemPosition: '位于本日成果层，交给后续分析继续复用。',
      process: ['写清 join_case_id。', '记录前后行数和唯一键。', '写出 can_prove / cannot_prove。'],
      owner: '产品经理负责对账结论，SQL 负责提供数值。',
      notResponsibleFor: '不负责把对账记录冒充成分析报告。',
      compareWith: 'JOIN 对账记录比单个 SQL 结果更能解释放大和缺口。',
      evidence: ['rows_before。', 'rows_after。', 'unique_orders。', 'amount_gap。'],
      failureModes: ['只留最终数字，不写对账过程。', '把对账表写成结论表。'],
      pmUse: '把正确 GMV、错误 GMV 和未匹配键放在同一张对账记录里。',
      correctExample: 'reconciliation.md 里同时写 rows_before、rows_after、unique_orders、unmatched_keys 和 amount_gap。',
      incorrectExample: 'JOIN 结果看起来对了，所以不用再记录过程。',
    },
  ],
  diagram: {
    title: 'JOIN 对照图：先看保留规则，再看放大和缺口',
    caption: 'W5D2 的链路是：连接键 → 保留规则 → INNER/LEFT/RIGHT/FULL → 一对多放大 → Anti Join 缺口 → JOIN 对账记录。',
    nodes: [
      { id: 'key', label: '连接键匹配', description: '先确认哪两个字段负责把行配对。', input: 'users.user_id / orders.user_id / order_items.order_id', output: '可匹配或不可匹配的行对', owner: '产品经理', evidence: 'user_id / order_id' },
      { id: 'inner', label: 'INNER JOIN', description: '只保留匹配行。', input: '两个表都存在的键值', output: '交集结果', owner: 'SQL 执行器' },
      { id: 'left', label: 'LEFT JOIN', description: '保留左表全部行，右表缺失补 NULL。', input: 'orders + users', output: '订单全量 + 用户补位', owner: 'SQL 执行器' },
      { id: 'right', label: 'RIGHT JOIN', description: '保留右表全部行，左表缺失补 NULL。', input: 'users + orders', output: '用户全量 + 订单补位', owner: 'SQL 执行器' },
      { id: 'full', label: 'FULL JOIN', description: '左右两边都保留，双向缺口都可见。', input: 'orders + users', output: '完整缺口对照', owner: 'SQL 执行器' },
      { id: 'amplify', label: '一对多放大', description: '一个订单连到多条明细时，订单级字段会被复制。', input: 'orders JOIN order_items', output: 'wrong_gmv=740', owner: 'SQL 执行器', evidence: 'O01 / O02' },
      { id: 'audit', label: 'JOIN 对账记录', description: '记录行数、唯一键、未匹配键和金额差异。', input: 'JOIN 前后结果', output: 'reconciliation.md', owner: '产品经理', evidence: '440 vs 740' },
    ],
    branches: [
      { from: 'key', to: 'inner', label: '只留匹配行', kind: 'normal' },
      { from: 'key', to: 'left', label: '保留左表', kind: 'normal' },
      { from: 'key', to: 'right', label: '保留右表', kind: 'normal' },
      { from: 'key', to: 'full', label: '保留两边', kind: 'normal' },
      { from: 'left', to: 'amplify', label: '一对多复制订单字段', kind: 'failure' },
      { from: 'amplify', to: 'audit', label: '先对账再解释', kind: 'normal' },
      { from: 'full', to: 'audit', label: '缺口显形后再写记录', kind: 'normal' },
    ],
    evidenceNotes: [
      'INNER JOIN 会主动丢掉未匹配行。',
      'LEFT JOIN 的 NULL 是缺口，不是自动报错。',
      'orders JOIN order_items 会放大订单级金额。',
      'JOIN 对账记录必须写出正确 GMV、错误 GMV 和未匹配键。',
    ],
  },
  demonstration: {
    title: '教师示范：先把三张表的 JOIN 保留规则讲清',
    businessProblem: '有人把 orders 直接 JOIN 到 order_items 之后说 GMV 涨了，你要先判断是保留规则还是一对多放大导致的。',
    finalConclusion: 'users 有 6 行、orders 有 6 行、order_items 有 9 行；非测试 paid 订单的正确 GMV 是 440，orders JOIN order_items 后如果直接 SUM(orders.paid_amount) 会变成 740；O05 的 user U99 缺失，I08 的 order_id=MISSING，说明缺口要单独列出。',
    conclusionLimit: '这些结果只证明本地教学 JOIN 对照和对账可以复核；不能证明真实生产 GMV、原因、趋势、报告结论或后续课程已完成。',
    steps: [
      { title: '先数三张输入表', action: '分别记录 users、orders、order_items 的行数和唯一键。', reason: '先确认每一张表“一行代表什么”。', evidence: '6、6、9 与唯一键数。', proves: '知道输入的基线大小。', limitation: '不能证明 JOIN 正确。' },
      { title: '先算不 JOIN 的基线', action: '只在 orders 上计算非测试 paid 订单的正确 GMV=440。', reason: 'JOIN 前要有订单粒度的对照线。', evidence: 'correct_gmv=440。', proves: '知道正确基线。', limitation: '还没看到放大点。' },
      { title: '做会放大的 JOIN', action: '把 orders JOIN 到 order_items，再直接 SUM(orders.paid_amount)。', reason: '订单级字段会被明细行复制。', evidence: 'wrong_gmv=740。', proves: '一对多会放大金额。', limitation: '不能证明收入真的变了。' },
      { title: '找出未匹配缺口', action: 'LEFT JOIN orders 到 users，筛出用户键为 NULL 的订单；再 LEFT JOIN order_items 到 orders，筛出订单键为 NULL 的明细。', reason: '缺口要单独列出来，不能静默吞掉。', evidence: 'O05 / I08。', proves: '缺失关系被显影。', limitation: '不能证明缺口原因。' },
      { title: '先聚合再连接', action: '把 order_items 先聚合到 order_id，再和 orders 对账。', reason: '订单粒度要先保护，再解释金额差异。', evidence: 'amount_gap=0。', proves: '重算后可对回订单粒度。', limitation: '不能证明生产数据已修复。' },
      { title: '写成对账记录', action: '把行数、唯一键、未匹配键和金额差异写进 reconciliation.md。', reason: '只有可复核记录，后续分析才站得住。', evidence: '440 vs 740 与缺口键。', proves: 'JOIN 过程可回看。', limitation: '不能替代后续完整分析报告。' },
    ],
  },
  guidedLab: {
    title: 'JOIN 对照台：先看保留规则，再看放大和缺口',
    goal: '用 W5-JOIN对账 教学库依次记录三张表的行数、正确 GMV、错误 GMV、未匹配键和订单粒度对账结果。',
    safety: '这是本地教学模拟，不连接真实数据库、不读取公司数据、不生成生产报表。',
    conceptIds: [...conceptIds],
    predictionPrompt: '先预测：users、orders 和 order_items 里，哪一张表在 JOIN 后最容易放大金额，哪一张表会暴露未匹配缺口？',
    steps: [
      { title: 'table-counts', action: '分别记录 users、orders、order_items 的行数和唯一键。', observe: '6、6、9。', explanation: '先确认每一张表的粒度和唯一性。', proves: '能看出输入基线。', cannotProve: '不能证明 JOIN 结果。' },
      { title: 'paid-baseline', action: '只在 orders 上算非测试 paid 订单的正确 GMV。', observe: 'correct_gmv=440。', explanation: '先有订单粒度基线，后面才能看放大。', proves: '能得到正确对照线。', cannotProve: '不能证明 JOIN 是否放大。' },
      { title: 'join-amplification', action: '把 orders JOIN 到 order_items，再直接 SUM(orders.paid_amount)。', observe: 'wrong_gmv=740。', explanation: '订单级字段被明细行复制。', proves: '能把一对多放大显形。', cannotProve: '不能证明收入真的涨了。' },
      { title: 'unmatched-orders', action: 'LEFT JOIN orders 到 users，筛出 users.user_id IS NULL 的订单。', observe: 'O05 / U99。', explanation: '订单还在，但用户维表缺失。', proves: '能找到缺 user 的订单。', cannotProve: '不能证明订单真的没用户。' },
      { title: 'unmatched-items', action: 'LEFT JOIN order_items 到 orders，筛出 orders.order_id IS NULL 的明细。', observe: 'I08 / MISSING。', explanation: '明细还在，但订单表没有对应主键。', proves: '能找到缺 order 的明细。', cannotProve: '不能证明明细一定无效。' },
      { title: 'reconciled-orders', action: '先把 order_items 聚合到 order_id，再和 orders 对账。', observe: 'amount_gap=0。', explanation: '先聚合再连接，订单粒度才能回到 1:1。', proves: '能把订单粒度对回去。', cannotProve: '不能证明生产数据已修复。' },
    ],
    recordPrompts: [
      '记录 users、orders、order_items 的行数和唯一键。',
      '记录非测试 paid 订单的正确 GMV=440。',
      '记录 JOIN 后错误 GMV=740，以及哪一张表放大了金额。',
      '记录缺 user 的订单键和缺 order 的明细键。',
      '记录聚合回订单粒度后的 amount_gap。',
      '记录这份对照最多能证明什么、不能证明什么。',
    ],
    comparePrompt: '对比 JOIN 前后的行数、唯一键和金额，找出第一个放大点和第一个缺口点。',
    passCriteria: [
      '能先预测哪一步会放大。',
      '能写出 440 和 740 的差异。',
      '能列出 O05 和 I08 两类缺口。',
      '能说明先聚合再连接的必要性。',
    ],
  },
  independentLab: {
    title: '独立变式：换一条保留规则，重写一次对账',
    scenario: '把 users 与 orders 的连接从 LEFT JOIN 改成 INNER JOIN，再把右表条件从 ON 挪到 WHERE，观察哪些订单被吞掉。',
    conceptIds: ['join-preserve-rule', 'left-join-preserve-left', 'anti-join-gap-audit', 'join-audit-map'],
    changedConditions: [
      '把 LEFT JOIN 改成 INNER JOIN。',
      '把 users.is_test=0 从 ON 挪到 WHERE。',
      '把 order_items 先聚合后再 JOIN。',
    ],
    task: '先预测哪一步会丢订单，再写出 row_count、unique_keys 和 missing_keys 的变化。',
    predictionPrompt: '如果把右表条件从 ON 挪到 WHERE，哪些 NULL 行会消失？先写预测，再执行。',
    evidenceRequirements: [
      '保留规则写清楚。',
      'row_count 和 unique_keys 都有记录。',
      'missing_keys 被单独列出。',
      '不能把 JOIN 后的数字当生产结论。',
    ],
    passCriteria: [
      '能说出 INNER 和 LEFT 的差别。',
      '能说明 WHERE 会改变外连接保留规则。',
      '能列出至少一个未匹配键。',
      '能写出有限结论和不能证明事项。',
    ],
    remediation: { label: '回看 JOIN 对照图', sectionId: 'diagram', anchor: 'w5d2-join-audit-map' },
  },
  exercises: [
    exercise(
      'w5d2-preserve-rule',
      ['概念与边界'],
      ['join-preserve-rule', 'inner-join-filter'],
      '哪句话最准确地描述 INNER JOIN？',
      ['只保留两边都匹配上的行', '保留左表所有行', '保留右表所有行', '保留两边所有行'],
      0,
      'INNER JOIN 只留下匹配行，任何一侧缺失都会被过滤掉。',
    ),
    exercise(
      'w5d2-left-where',
      ['机制推演', '证据判断'],
      ['left-join-preserve-left', 'anti-join-gap-audit'],
      '为什么 LEFT JOIN 后在 WHERE 里写 users.is_test = 0 可能让未匹配订单消失？',
      ['WHERE 会把补成 NULL 的右表行过滤掉', 'LEFT JOIN 变成了 FULL JOIN', 'LEFT JOIN 会自动修复 NULL', '只有数字字段才会发生'],
      0,
      '外连接先补 NULL，再执行 WHERE；NULL 被 WHERE 过滤后，保留规则就被改变了。',
    ),
    exercise(
      'w5d2-gmv',
      ['工作场景'],
      ['join-grain-amplification'],
      '订单表一行一单，明细表一行一商品。直接 JOIN 后再 SUM(orders.paid_amount) 最可能发生什么？',
      ['金额会按明细行数被重复累加', '金额一定更准确', '订单会自动去重', '只会丢失订单不会放大金额'],
      0,
      '一对多 JOIN 会复制订单级字段，所以 SUM 订单金额会被放大。',
    ),
    exercise(
      'w5d2-gap-audit',
      ['证据判断'],
      ['anti-join-gap-audit'],
      '要找“没有用户记录的订单”，最直接的思路是什么？',
      ['LEFT JOIN 后筛选 users.user_id IS NULL', 'INNER JOIN users', '只查 users 表', '直接删除空值行'],
      0,
      '这是典型 Anti Join：先保留左表，再筛出右表键为 NULL 的缺口行。',
    ),
    exercise(
      'w5d2-reconcile',
      ['综合变式'],
      ['join-audit-map', 'full-join-preserve-both'],
      '一份可信的 JOIN 对账记录最关键应包含什么？',
      ['只有最终 GMV 数字', '连接前后行数、唯一键、未匹配键和金额差异', '一张更好看的图', '运营口头确认即可'],
      1,
      'JOIN 对账要能复核保留规则、放大点和缺口，不能只留一个数字。',
    ),
  ],
  deliverable: {
    title: 'JOIN 对账记录',
    conceptIds: ['join-preserve-rule', 'join-grain-amplification', 'anti-join-gap-audit', 'join-audit-map'],
    purpose: '把 W5-JOIN对账 教学库里的 users、orders 和 order_items JOIN 过程写进 reconciliation.md，明确哪一步保留了谁、哪一步放大了谁、哪一步暴露了缺口。',
    whenToUse: '当需要向数据同事或产品评审解释 JOIN 对照图里为什么金额、行数或唯一键和基线不同。',
    audience: '产品经理、数据分析师、SQL 审阅者。',
    fields: [
      { name: 'join_case_id', meaning: '每条对账记录的唯一编号。', source: '实验步骤和 table 名称' },
      { name: 'left_table', meaning: '当前 JOIN 左侧的表。', source: 'SQL FROM / LEFT JOIN' },
      { name: 'right_table', meaning: '当前 JOIN 右侧的表。', source: 'SQL FROM / JOIN' },
      { name: 'join_type', meaning: 'INNER、LEFT、RIGHT 或 FULL。', source: '本日保留规则' },
      { name: 'preserve_rule', meaning: '这次 JOIN 保留哪一边、丢掉哪一边。', source: 'JOIN 类型' },
      { name: 'join_key', meaning: '用于连接的字段。', source: 'user_id 或 order_id' },
      { name: 'rows_before', meaning: 'JOIN 前的行数。', source: 'table_counts' },
      { name: 'rows_after', meaning: 'JOIN 后的行数。', source: 'join 结果' },
      { name: 'unique_keys', meaning: 'JOIN 后仍应保护的唯一键数。', source: 'order_id / item_id' },
      { name: 'unmatched_keys', meaning: '没有匹配到的一侧键。', source: 'Anti Join 结果' },
      { name: 'amount_gap', meaning: '重算前后的金额差异。', source: 'correct_gmv vs wrong_gmv' },
      { name: 'can_prove', meaning: '这条记录能证明什么。', source: '本地教学对账' },
      { name: 'cannot_prove', meaning: '这条记录不能证明什么。', source: '证据边界' },
      { name: 'next_sql_task', meaning: '下一步该做什么 SQL。', source: 'W5D3 及以后' },
    ],
    badExample: 'join_case_id: J-01\njoin_type: INNER\namount_gap: 740\ncan_prove: JOIN 后数字变大了',
    badReasons: [
      '只写结果，不写保留规则和基线。',
      '没有说明 740 是错误 GMV，而不是最终结论。',
      '没有写 unmatched_keys 和 next_sql_task。',
    ],
    revisionSteps: [
      '先补 left_table、right_table、join_key 和 preserve_rule。',
      '再写 rows_before、rows_after、unique_keys 与 amount_gap。',
      '最后写 can_prove、cannot_prove 和 next_sql_task。',
    ],
    goodExample: 'join_case_id: J-02\nleft_table: orders\nright_table: order_items\njoin_type: LEFT\npreserve_rule: 保留订单\njoin_key: order_id\nrows_before: 6\nrows_after: 9\nunique_keys: 5\nunmatched_keys: I08 / MISSING；O05 / U99\namount_gap: 300（正确 GMV=440，错误 GMV=740）\ncan_prove: JOIN 放大了订单级金额\ncannot_prove: 不能证明真实生产收入变化\nnext_sql_task: 先聚合明细再回连订单',
    guidedPrompts: [
      '先写 join_case_id、left_table、right_table 和 join_type。',
      '再写 preserve_rule、join_key、rows_before 和 rows_after。',
      '补 unique_keys 和 unmatched_keys。',
      '补 amount_gap、can_prove 和 cannot_prove。',
      '最后写 next_sql_task。',
      '整份记录至少要能被别人复算一次。',
      '对照正确 GMV=440 与错误 GMV=740。',
      '把 O05 和 I08 两类缺口写进记录。',
    ],
    blankTemplate: '```md\n# JOIN 对账记录\n\n- join_case_id:\n- left_table:\n- right_table:\n- join_type:\n- preserve_rule:\n- join_key:\n- rows_before:\n- rows_after:\n- unique_keys:\n- unmatched_keys:\n- amount_gap:\n- can_prove:\n- cannot_prove:\n- next_sql_task:\n```',
    standardTemplate: '# JOIN 对账记录\n\n- join_case_id:\n- left_table:\n- right_table:\n- join_type:\n- preserve_rule:\n- join_key:\n- rows_before:\n- rows_after:\n- unique_keys:\n- unmatched_keys:\n- amount_gap:\n- can_prove:\n- cannot_prove:\n- next_sql_task:\n',
    checklist: [
      '已写清保留哪一边。',
      '已写清 join_key 和粒度。',
      '已记录 rows_before 与 rows_after。',
      '已列出未匹配键。',
      '已写出 amount_gap 和不能证明事项。',
      '已说明下一步先聚合再连接。',
    ],
  },
  memory: {
    conceptIds: ['join-key-matching', 'join-preserve-rule', 'left-join-preserve-left', 'join-grain-amplification', 'anti-join-gap-audit', 'join-audit-map'],
    anchors: [
      '连接键先行，再谈保留规则。',
      'INNER 只保留两边匹配行。',
      'LEFT 保留左表并补 NULL。',
      '一对多会放大订单级字段。',
      '先对账再解释业务结论。',
    ],
    closedBookPrompt: '闭卷解释连接键、保留规则、一对多放大和 Anti Join 缺口审查的差别，并各给一个 orders/users/order_items 的例子。',
    microOperation: '看到 JOIN 后 GMV 变化时，先写 rows_before、rows_after、unique_orders 和 unmatched_keys。',
    unresolvedPrompt: '如果 right_table 的字段在 WHERE 里被筛掉了，这个 JOIN 还算哪一种？',
    reviewStages: [
      { stage: 'D1', task: '重写一次 JOIN 保留规则和连接键。' },
      { stage: 'D3', task: '复述 LEFT JOIN 和 RIGHT JOIN 的保留侧。' },
      { stage: 'D7', task: '用 O05 / I08 回看一对多放大和缺口。' },
      { stage: 'D14', task: '把 JOIN 对账记录再复算一遍。' },
      { stage: 'D30', task: '闭卷说明为什么先聚合再连接。' },
      { stage: 'D60', task: '回头检查 FULL JOIN 与 Anti Join 的边界。' },
    ],
  },
  nextLesson: {
    id: 'W5D3',
    title: '一对多放大与缺口诊断',
    bridge: '继续把 JOIN 对照图落到更完整的对账诊断和分析边界。',
  },
}
