import type { DailyCourse, Exercise } from './types'

const conceptIds = [
  'source-table-map',
  'join-chain-grain',
  'step-row-count-audit',
  'step-unique-key-audit',
  'step-amount-audit',
  'null-link-gap-audit',
  'exercise-boundary',
  'multi-table-sql-log',
] as const

const prerequisiteConceptIds = [
  'metric-grain',
  'quality-evidence-boundary',
  'join-key-matching',
  'join-preserve-rule',
  'join-grain-amplification',
  'anti-join-gap-audit',
  'left-join-preserve-left',
  'full-join-preserve-both',
] as const

function exercise(
  id: string,
  categories: Exercise['categories'],
  ids: string[],
  prompt: string,
  options: string[],
  answerIndex: number,
  referenceAnswer: string,
): Exercise {
  return {
    id,
    kind: 'single-choice',
    categories,
    conceptIds: ids,
    prompt,
    hint: '先看这一步在连接哪两张表，再判断行数、唯一键和金额会怎样变化，最后把边界写清。',
    options: options.map((label, index) => ({
      label,
      rationale: index === answerIndex
        ? '这项把表角色、连接顺序、逐步记录和证据边界连起来。'
        : '这项要么把行数、唯一键或金额写乱了，要么把中间结果直接当成生产结论。',
      couldBeTrueWhen: index === answerIndex
        ? '当学习者正在完成 W5D3 的多表 SQL 逐步记录。'
        : '只有后续 W5D4-W5D6 再做更完整的复盘、分析和报告，才可能支撑更强判断。',
    })),
    answerIndex,
    referenceAnswer,
    reasoning: [
      'W5D3 的第一目标不是直接拿最终结果，而是先说清 users、events、orders 各自的角色与连接顺序。',
      '多表 JOIN 会改变行数、唯一键和金额，必须每一步分别记录，不能只看最终 SQL 输出。',
      '本日只在本地教学包里做多表 SQL 逐步记录，不证明真实生产分析正确。',
    ],
    rubric: ['表角色说清楚', '逐步记录说清楚', '行数唯一键和金额分开说明', '证据边界不过界说明'],
    commonErrors: [
      { error: '把最后一条 SQL 当成全部证据', reason: 'W5D3 要记录每一步的行数、唯一键和金额，不能只看最终结果。' },
      { error: '把 amount 变化直接当成业务结果', reason: '金额变化可能来自粒度放大或连接缺口，不等于真实生产结论。' },
    ],
    remediation: { label: '回看多表 SQL 记录', sectionId: 'diagram', anchor: 'w5d3-multi-table-sql-log' },
  }
}

export const w5d3: DailyCourse = {
  id: 'W5D3',
  contentVersion: 'w5d3-multi-table-sql-day01-v1',
  week: 5,
  day: 3,
  title: '连接用户、行为与订单',
  subtitle: '先把 users、events、orders 这三张本地教学表连成一条可复核链路，再逐步记录每一步的 row count、unique key 和 amount；本日不提前写完整分析报告，也不把最后结果直接当成真实生产结论。',
  duration: { core: 30, standard: 45, extension: 82, full: 136 },
  coreConceptGroups: [
    {
      id: 'table-map-and-chain',
      title: '先说清表角色和连接链路',
      conceptIds: ['source-table-map', 'join-chain-grain'],
      summary: '先分清 users、events、orders 各自扮演什么角色，再决定连接顺序和数据粒度如何一路传递。',
      boundary: '能解释为什么要先定表角色和连接顺序；不能证明真实生产的三张表结构已经完全正确。',
    },
    {
      id: 'stepwise-audit',
      title: '每一步都要记行数、唯一键和金额',
      conceptIds: ['step-row-count-audit', 'step-unique-key-audit', 'step-amount-audit'],
      summary: '每一次连接都要同时写 rows_before、rows_after、unique_keys、amount_before 和 amount_after，才能看出是哪一步改变了结果。',
      boundary: '能写出逐步数值和变化方向；不能把最终 SQL 的一行结果当成全部证据。',
    },
    {
      id: 'gap-and-boundary',
      title: '缺口和答案边界要单独写',
      conceptIds: ['null-link-gap-audit', 'exercise-boundary', 'multi-table-sql-log'],
      summary: '缺失链接要和放大点分开记录，exercise.sql、answers.sql 和最终日志也要分清边界。',
      boundary: '能写出缺口、练习和答案的边界；不能提前打开 answers.sql 当作已完成。',
    },
  ],
  prerequisiteConceptIds: [...prerequisiteConceptIds],
  learningPaths: {
    '30': {
      guidedStepIndices: [0, 1, 2, 3, 4, 5],
      guidedRecordIndices: [0, 1, 2, 3, 4, 5],
      exerciseCount: 3,
      deliverablePromptCount: 6,
      deliverableChecklistIndices: [0, 1, 2, 3, 4],
      deliverableMinimumContributionCharacters: 260,
    },
    '45': {
      guidedStepIndices: [0, 1, 2, 3, 4, 5],
      guidedRecordIndices: [0, 1, 2, 3, 4, 5],
      exerciseCount: 5,
      deliverablePromptCount: 6,
      deliverableChecklistIndices: [0, 1, 2, 3, 4, 5],
      deliverableMinimumContributionCharacters: 390,
    },
  },
  primaryGoal: '提交 `multi-table-sql-log.md`：按 `setup.sql`、`exercises.sql` 和 `answers.sql` 的三步推演记录 step_id、source_sql_ref、left_table、right_table、join_type、join_key、rows_before、rows_after、unique_keys、amount_before、amount_after、gap_note、can_prove、cannot_prove、next_sql_task。',
  scenario: {
    role: '你是刚学会 JOIN 规则、准备把多表链路写成可复核记录的产品经理。',
    situation: '现在有三张教学表：users、events、orders。有人把 users 先连 events，再连 orders，但只保留了最后一条 SQL，没有记录中间每一步的 row count、unique key 和 amount；结果看起来像对了，实际上看不出是哪一步改变了结果。',
    question: '怎样把“多表 SQL 跑通了”拆成表角色、连接顺序、逐步行数、唯一键、金额和答案边界？',
    stakes: '如果只保存最后一个结果，学习者就看不出哪一步放大了行数、哪一步丢了链接、哪一步改变了金额，也无法区分 exercises.sql 和 answers.sql。',
  },
  objectives: [
    { id: 'w5d3-objective-chain', text: '能把 users、events、orders 的连接顺序说清', evidence: '`multi-table-sql-log.md` 里能写出每一步的 left_table、right_table 和 join_key。' },
    { id: 'w5d3-objective-audit', text: '能逐步记录行数、唯一键和金额', evidence: '日志里能写出 rows_before、rows_after、unique_keys、amount_before 和 amount_after。' },
    { id: 'w5d3-objective-boundary', text: '能区分 exercises.sql、answers.sql 和最终日志', evidence: 'cannot_prove 里明确写出不能提前打开 answers.sql，也不能把最后结果当成生产结论。' },
    { id: 'w5d3-objective-gap', text: '能把缺口和放大分开说明', evidence: 'gap_note 里能分别写出缺失链接、行数变化和金额变化。' },
  ],
  prerequisites: [
    {
      id: 'w5d3-join-readiness',
      conceptIds: [...prerequisiteConceptIds],
      prompt: '你能把粒度、保留侧、连接键和证据边界先说清吗？',
      passDescription: '能说明为什么不同表的粒度不能乱连，为什么中间结果不能直接当成生产结论。',
      remediationLabel: '回到 W4D4/W5D2 补粒度和 JOIN 规则',
      remediationTarget: '#/lesson/W4D4',
      remediation: {
        purpose: 'W5D3 可以提前阅读，但没有 W4D4 的粒度和 W5D2 的 JOIN 规则，三表链路只会变成表连接演示。',
        steps: ['复述 W4D4 的 metric_grain、quality_evidence_boundary 和异常值边界。', '复述 W5D2 的 join-key-matching、join-preserve-rule 和 join-grain-amplification。', '把“连接谁”和“记录什么”两件事分开写。'],
        successCheck: '能把表角色、连接顺序和逐步记录拆成可复核说明。',
      },
    },
    {
      id: 'w5d3-audit-readiness',
      conceptIds: ['join-grain-amplification', 'anti-join-gap-audit', 'left-join-preserve-left', 'full-join-preserve-both'],
      prompt: '你能把缺口、放大和未匹配行分开说吗？',
      passDescription: '能说明哪一步会放大、哪一步会丢链接、哪一步需要补 NULL。',
      remediationLabel: '回看 W5D2 的 JOIN 对账边界',
      remediationTarget: '#/lesson/W5D2',
      remediation: {
        purpose: '先能区分放大和缺口，才不会把中间结果直接解释成最终答案。',
        steps: ['复述 W5D2 的 join-grain-amplification 和 anti-join-gap-audit。', '说清 LEFT JOIN、RIGHT JOIN、FULL JOIN 各自会留下什么。', '把缺口键和放大点分成两类记录。'],
        successCheck: '能明确说出 row count、unique key 和 amount 要分别看。',
      },
    },
  ],
  concepts: [
    {
      id: 'source-table-map',
      prerequisiteConceptIds: ['metric-grain', 'quality-evidence-boundary'],
      term: '表角色地图',
      english: 'Source Table Map',
      definition: '表角色地图是先说明 users、events、orders 各自代表什么、哪张表提供用户、哪张表提供行为、哪张表提供金额，再开始写多表 SQL。',
      why: '如果不先分清表角色，JOIN 链路就会乱接，后面的行数、唯一键和金额也会失去解释前提。',
      problemSolved: '回答“这三张表各自负责哪一段信息”。',
      input: 'users、events、orders 的字段、主键和业务含义。',
      output: '一张能被读懂的表角色地图和连接顺序草图。',
      systemPosition: '位于 W5D3 的最前面，是多表 SQL 的起点。',
      process: ['先看每张表的主键和外键。', '再标出谁提供用户、行为和订单。', '最后写出连接顺序。'],
      owner: '产品经理先画表角色，SQL 再负责跑出结果。',
      notResponsibleFor: '不负责证明每张表都绝对完整。',
      compareWith: '表角色地图回答“谁是谁”；连接键匹配回答“怎么连”。',
      evidence: ['users 提供 user_id。', 'events 提供行为轨迹。', 'orders 提供 amount 和 order_id。'],
      failureModes: ['把 events 当成订单表。', '把金额字段误认为来自 users。'],
      pmUse: '先说“users 是人，events 是行为，orders 是交易”。',
      correctExample: '先从 users 连到 events，再连到 orders。',
      incorrectExample: '三张表随便按名字连起来。',
    },
    {
      id: 'join-chain-grain',
      prerequisiteConceptIds: ['source-table-map', 'join-key-matching'],
      term: '连接链路与粒度',
      english: 'Join Chain Grain',
      definition: '连接链路与粒度是指每一步 JOIN 之后都要重新确认一行代表什么，以及用户粒度、行为粒度和订单粒度是否发生变化。',
      why: '多表 SQL 最容易出错的地方不是语法，而是连完之后“一行代表什么”已经变了却没有人记录。',
      problemSolved: '回答“每一步 JOIN 后这一行到底代表谁”。',
      input: 'users→events→orders 的连接顺序和每一步粒度。',
      output: '每一步连接后该行代表谁、粒度是否变化、是否还能继续追踪到下一张表，以及是否被后续步骤复制。',
      systemPosition: '位于连接顺序之后、具体数值记录之前。',
      process: ['先写出第一步代表什么。', '再写出第二步是否改变粒度。', '最后把粒度变化写进日志。'],
      owner: '产品经理负责说清粒度，SQL 负责体现粒度变化。',
      notResponsibleFor: '不负责自动修复粒度错误，也不负责把重复键伪装成唯一键。',
      compareWith: '粒度回答“这一行是谁”；表角色地图回答“表在讲什么”。',
      evidence: ['users 一行代表一个用户。', 'events 一行可能代表一条行为。', 'orders 一行代表一笔订单。'],
      failureModes: ['把行为粒度当成订单粒度。', '把订单粒度直接拿去算行为数。'],
      pmUse: '每次连接前先问“这一行现在代表谁”。',
      correctExample: 'users LEFT JOIN events 后，再确认是否还在用户粒度。',
      incorrectExample: '连完以后默认还是原来的粒度。',
    },
    {
      id: 'step-row-count-audit',
      prerequisiteConceptIds: ['join-chain-grain'],
      term: '逐步行数审计',
      english: 'Row Count Audit',
      definition: '逐步行数审计是把每一步 JOIN 前后的行数都记下来，才能看出是增加、减少还是保持不变。',
      why: '只看最终结果，不知道是哪一步改变了行数；逐步行数能把变化点拆开。',
      problemSolved: '回答“哪一步让结果行数变了”。',
      input: 'rows_before 和 rows_after。',
      output: '可比对的行数变化记录，以及每一步 JOIN 前后规模变化的差值说明。',
      systemPosition: '位于每一步连接之后，是最基础的数值审计。',
      process: ['连接前先记行数。', '连接后再记行数。', '把变化写成差值。'],
      owner: 'SQL 输出行数，产品经理负责读出变化。',
      notResponsibleFor: '不负责解释为什么一定变化。',
      compareWith: '行数审计和最终结果不一样；前者看过程，后者只看终点。',
      evidence: ['rows_before。', 'rows_after。', 'step_id。'],
      failureModes: ['只写一边行数。', '把最终行数当成全部证据。'],
      pmUse: '每一步都写 rows_before 和 rows_after，别等到最后才补。',
      correctExample: 'step 2 记录 rows_before=6，rows_after=10。',
      incorrectExample: '最后一行有 10 条，所以整个链路没问题。',
    },
    {
      id: 'step-unique-key-audit',
      prerequisiteConceptIds: ['step-row-count-audit', 'join-grain-amplification'],
      term: '逐步唯一键审计',
      english: 'Unique Key Audit',
      definition: '逐步唯一键审计是每一步都记录仍然应该保持唯一的键，比如 user_id、event_id 或 order_id，看看连接有没有把它们复制。',
      why: '行数变化不一定说明问题，唯一键变化更能揭示重复、放大和丢失。',
      problemSolved: '回答“哪一类唯一键被复制或丢失了”。',
      input: 'user_id、event_id、order_id。',
      output: '每一步保留的唯一键数量与重复风险清单。',
      systemPosition: '位于行数审计旁边，用来补充粒度观察。',
      process: ['先选当前步骤应保持唯一的键。', '再统计是否仍然唯一。', '最后把重复键单独列出。'],
      owner: '产品经理负责挑键，SQL 负责统计。',
      notResponsibleFor: '不负责把重复自动消掉，也不负责把放大误写成正常现象。',
      compareWith: '唯一键审计比单看行数更能说明粒度是否变粗。',
      evidence: ['unique_keys。', 'user_id / event_id / order_id。', '重复键样本。'],
      failureModes: ['忘记标唯一键。', '把重复键直接删掉后当没发生。'],
      pmUse: '看一条链路时，先问“哪个键本该唯一”。',
      correctExample: 'orders 这一步应保持 order_id 唯一。',
      incorrectExample: '只要行数差不多，就说明唯一键没有问题。',
    },
    {
      id: 'step-amount-audit',
      prerequisiteConceptIds: ['step-row-count-audit', 'step-unique-key-audit'],
      term: '逐步金额审计',
      english: 'Amount Audit',
      definition: '逐步金额审计是每一步都记录金额前后变化，尤其要区分订单金额、行为数量和最终汇总值，避免把放大后的值当真相。',
      why: '金额在多表链路里最容易被复制；只有和行数、唯一键一起看，才能判断是对账还是放大。',
      problemSolved: '回答“金额在哪一步被改变”。',
      input: 'amount_before 和 amount_after。',
      output: '每一步金额变化、差值以及是否出现重复累计的线索。',
      systemPosition: '位于行数和唯一键之后，帮助判断是否发生放大。',
      process: ['先确认金额来自哪张表。', '再看 JOIN 后是否重复。', '最后把差值写进日志。'],
      owner: 'SQL 负责算数，产品经理负责不误读数值。',
      notResponsibleFor: '不负责证明真实收入变化，也不负责把放大后的数值当作结论。',
      compareWith: '金额审计和行数审计要一起看，单独看金额很容易被骗。',
      evidence: ['amount_before。', 'amount_after。', '正确与错误金额对照。'],
      failureModes: ['把 final amount 当成唯一判断。', '把 JOIN 后多出来的金额说成增长。'],
      pmUse: '每一步都写 amount_before 和 amount_after，不只记最后汇总。',
      correctExample: 'orders JOIN events 后，amount_after 可能和 amount_before 不一样。',
      incorrectExample: '只看总金额，不看中间步骤。',
    },
    {
      id: 'null-link-gap-audit',
      prerequisiteConceptIds: ['left-join-preserve-left', 'full-join-preserve-both'],
      term: '缺失链接审查',
      english: 'Null Link Gap Audit',
      definition: '缺失链接审查是把连接不上去的 user、event 或 order 单独列出来，说明哪些键是 NULL、哪些链接没接上。',
      why: '缺口和放大不是一回事；缺口说明哪一边没连上，放大说明哪一边被复制。',
      problemSolved: '回答“哪一步出现了未匹配链接”。',
      input: 'LEFT JOIN 或 FULL JOIN 后的 NULL 键。',
      output: '缺失 user、缺失 event、缺失 order 的样本，以及各自对应的 NULL 键记录。',
      systemPosition: '位于对账和记录阶段，是补充过程证据的关键。',
      process: ['先保留可能缺失的一边。', '再筛出 NULL 键。', '把缺口单独列成记录。'],
      owner: '产品经理负责看缺口，SQL 负责显影。',
      notResponsibleFor: '不负责判断缺口原因，也不负责把缺口自动解释成业务消失。',
      compareWith: '缺口审查和行数审计不同；前者找没连上，后者找变了多少。',
      evidence: ['NULL user_id。', 'NULL event_id。', 'NULL order_id。'],
      failureModes: ['看到 NULL 就删。', '把缺口当成不存在。'],
      pmUse: '先把没连上的键列出来，再讨论要不要补数据。',
      correctExample: 'users LEFT JOIN events 后筛出 events.event_id IS NULL。',
      incorrectExample: 'NULL 一定说明这条记录没价值。',
    },
    {
      id: 'exercise-boundary',
      prerequisiteConceptIds: ['quality-evidence-boundary', 'null-link-gap-audit'],
      term: '练习与答案边界',
      english: 'Exercise Boundary',
      definition: '练习与答案边界是指 exercises.sql 只负责出题，answers.sql 只负责对照，学习者自己的多表 SQL 记录才是今天真正要交的东西。',
      why: '如果把答案提前打开，学习者就看不到自己怎么一步步判断行数、唯一键和金额。',
      problemSolved: '回答“今天哪些文件能看，哪些文件只能最后对照”。',
      input: 'setup.sql、exercises.sql、answers.sql 和自己的记录草稿。',
      output: '清楚的查看顺序和不能证明事项。',
      systemPosition: '位于实验最后一步和成果之间。',
      process: ['先做题，再记录。', '最后才对照答案。', '把边界写到 cannot_prove。'],
      owner: '产品经理守边界，SQL 只负责复核。',
      notResponsibleFor: '不负责把 answers.sql 变成前置资料。',
      compareWith: '边界回答“什么时候能看什么”；日志回答“我看到了什么”。',
      evidence: ['setup.sql。', 'exercises.sql。', 'answers.sql。'],
      failureModes: ['把 answers.sql 提前当教程。', '把做题过程省略掉。'],
      pmUse: '先做 exercises.sql，再最后用 answers.sql 对照。',
      correctExample: '做完自己的记录后，再打开 answers.sql 对照。',
      incorrectExample: '先看 answers.sql 再开始写记录。',
    },
    {
      id: 'multi-table-sql-log',
      prerequisiteConceptIds: ['step-row-count-audit', 'step-unique-key-audit', 'step-amount-audit', 'exercise-boundary'],
      term: '多表 SQL 记录',
      english: 'Multi-table SQL Log',
      definition: '多表 SQL 记录是把每一步多表连接的 row count、unique key、amount、缺口和答案边界都写在一份可复核日志里。',
      why: '只有最终 SQL 没法复盘过程；只有过程没有边界又会把答案提前泄露。',
      problemSolved: '回答“这份多表 SQL 到底能证明到哪里”。',
      input: '逐步数值、缺口键、答案边界和下一步 SQL 任务。',
      output: 'multi-table-sql-log.md。',
      systemPosition: '位于本日的最终成果层，承载可复核的多表 SQL 过程账本。',
      process: ['写 step_id。', '写 row、key、amount 和 gap。', '写 can_prove / cannot_prove / next_sql_task。'],
      owner: '产品经理负责日志，SQL 负责提供数值。',
      notResponsibleFor: '不负责把日志冒充成最终分析报告。',
      compareWith: '日志比单条 SQL 更能解释过程。',
      evidence: ['setup.sql。', 'exercises.sql。', 'answers.sql。', 'multi-table-sql-log.md。'],
      failureModes: ['只写最后的查询结果。', '把答案直接抄进日志。'],
      pmUse: '把每一步 rows_before、rows_after、unique_keys 和 amount 都写进日志。',
      correctExample: 'multi-table-sql-log.md 里清楚写出 step_id、source_sql_ref、rows_before、rows_after、unique_keys、amount_before 和 amount_after。',
      incorrectExample: 'SQL 跑通了，所以不用记录中间步骤。',
    },
  ],
  diagram: {
    title: '多表 SQL 链路图：先看表角色，再看逐步审计',
    caption: 'W5D3 的链路是：表角色地图 → 连接链路和粒度 → 逐步行数、唯一键和金额审计 → 缺口审查 → 多表 SQL 记录。',
    nodes: [
      { id: 'map', label: '表角色地图', description: '先分清 users、events、orders 各自负责什么。', input: 'setup.sql 里的三张表', output: '表角色草图', owner: '产品经理', evidence: 'users / events / orders' },
      { id: 'chain', label: '连接链路', description: '先连 users 再连 events，再连 orders。', input: 'user_id / event_id / order_id', output: '链路结果', owner: 'SQL 执行器' },
      { id: 'rows', label: '逐步行数审计', description: '每一步都记 rows_before 和 rows_after。', input: '每一步 JOIN 前后', output: 'row count 变化', owner: '产品经理' },
      { id: 'keys', label: '逐步唯一键审计', description: '每一步都记 unique_keys，避免把重复当唯一。', input: 'user_id / event_id / order_id', output: '唯一键变化', owner: 'SQL 执行器' },
      { id: 'amount', label: '逐步金额审计', description: '每一步都记 amount_before 和 amount_after。', input: '订单金额与聚合结果', output: '金额变化', owner: 'SQL 执行器', evidence: '440 vs 740' },
      { id: 'gap', label: '缺失链接审查', description: '把缺失 user、event、order 单独列出。', input: 'NULL 键', output: '缺口样本', owner: '产品经理', evidence: 'O05 / I08' },
      { id: 'log', label: '多表 SQL 记录', description: '把步骤、边界和下一步 SQL 任务写成日志。', input: '逐步记录', output: 'multi-table-sql-log.md', owner: '产品经理', evidence: 'setup.sql / exercises.sql / answers.sql' },
    ],
    branches: [
      { from: 'map', to: 'chain', label: '先定表角色再连', kind: 'normal' },
      { from: 'chain', to: 'rows', label: '每步都记行数', kind: 'normal' },
      { from: 'rows', to: 'keys', label: '再看唯一键是否被复制', kind: 'normal' },
      { from: 'keys', to: 'amount', label: '最后看金额是否放大', kind: 'normal' },
      { from: 'chain', to: 'gap', label: '缺口单独列出', kind: 'failure' },
      { from: 'amount', to: 'log', label: '把逐步证据写进日志', kind: 'normal' },
      { from: 'gap', to: 'log', label: '把缺口和边界写进日志', kind: 'normal' },
    ],
    evidenceNotes: [
      'users、events、orders 的角色必须先分清。',
      '每一步都要有 rows_before 和 rows_after。',
      'unique_keys 能看出是否复制了键。',
      'amount_before 和 amount_after 不能只看最后一行。',
      'setup.sql、exercises.sql、answers.sql 的边界要写进 cannot_prove。',
    ],
  },
  demonstration: {
    title: '教师示范：把 users、events、orders 逐步连起来',
    businessProblem: '有人只把最后一个多表 SQL 结果贴出来，说自己已经把用户行为和订单连通了，但没说明每一步的行数、唯一键和金额如何变化。',
    finalConclusion: '先把 users、events、orders 的角色和连接顺序写清，再分步记录 rows_before、rows_after、unique_keys、amount_before 和 amount_after；这样才能看出是哪一步改变了结果。多表 SQL 记录能证明本地教学链路可复核，但不能证明真实生产已经被正确分析。',
    conclusionLimit: '这些结果只证明本地教学包的多表 SQL 过程可复盘；不能证明真实生产行为、转化、收入、报告或 answers.sql 已经被提前掌握。',
    steps: [
      { title: '先看表角色地图', action: '先从 setup.sql 标出 users、events、orders 各自的主键、外键和业务含义。', reason: '没有表角色，连接顺序就没法解释，也看不出哪张表在提供什么信息。', evidence: 'users、events、orders 的角色和连接顺序。', proves: '能说清谁提供什么信息。', limitation: '不能证明 JOIN 正确。' },
      { title: '先写连接链路顺序', action: '按 users → events → orders 的顺序写出 join_key。', reason: '先定链路，后面才能看粒度，也才能知道哪一步在接哪张表。', evidence: 'user_id / event_id / order_id。', proves: '能说明连接顺序。', limitation: '不能证明结果无放大。' },
      { title: '先记每步行数变化', action: '每一步都记录 rows_before 和 rows_after。', reason: '行数变化最先暴露哪一步改了结果，单看最后一行看不出过程。', evidence: 'row count 变化与差值。', proves: '能复盘每一步的规模变化。', limitation: '不能单独证明唯一性。' },
      { title: '再记唯一键是否被复制', action: '每一步都记录 unique_keys，看看 user_id、event_id、order_id 是否被复制。', reason: '唯一键变化能说明粒度是否被放大，也能暴露重复链路。', evidence: 'unique_keys 变化。', proves: '能发现重复或复制。', limitation: '不能单独证明金额是否正确。' },
      { title: '再记金额前后变化', action: '每一步都记录 amount_before 和 amount_after，尤其要看订单金额是否被重复累加。', reason: '金额是最容易被误读的数值，必须和行数与唯一键一起看。', evidence: '440 与 740 的对照。', proves: '能看到金额变化。', limitation: '不能证明真实收入变化。' },
      { title: '写日志边界和交接', action: '把 step_id、source_sql_ref、can_prove、cannot_prove 和 next_sql_task 写进 multi-table-sql-log.md。', reason: '只有边界清楚，日志才不会冒充答案，也不会把中间结果伪装成结论。', evidence: 'setup.sql / exercises.sql / answers.sql。', proves: '能把过程留下。', limitation: '不能证明 answers.sql 已提前暴露。' },
    ],
  },
  guidedLab: {
    title: '多表 SQL 逐步记录台',
    goal: '用本地教学包的 users、events、orders 依次记录行数、唯一键和金额，把每一步的变化写进 multi-table-sql-log.md。',
    safety: '教学模拟 · 只读取本地 setup.sql、exercises.sql 和 answers.sql 的教学包，不连接真实数据库、不读取公司数据、不提前打开 answers.sql。',
    conceptIds: [...conceptIds],
    predictionPrompt: '先预测：users→events→orders 这条链路里，哪一步最可能改变行数，哪一步最可能改变 unique_keys，哪一步最可能改变 amount？',
    steps: [
      { title: 'table-map', action: '先从 setup.sql 里写出 users、events、orders 的角色和连接键。', observe: '看到 user_id、event_id、order_id 和 amount 的位置。', explanation: '先分清表角色，再开始连接。', proves: '能说清三张表的责任。', cannotProve: '不能证明最终答案。' },
      { title: 'join-users-events', action: '先把 users 连到 events，记录 rows_before、rows_after 和 unique_keys。', observe: '用户粒度和行为粒度开始分开。', explanation: '第一步最容易暴露行为表是否一人多条。', proves: '能记录第一步行数变化。', cannotProve: '不能证明订单部分已经正确。' },
      { title: 'join-events-orders', action: '再把 orders 接进来，继续记录 rows_before、rows_after 和 unique_keys。', observe: '订单表开始影响金额。', explanation: '第二步最容易暴露订单粒度。', proves: '能记录第二步行数变化。', cannotProve: '不能证明金额已经稳定。' },
      { title: 'record-amount', action: '对照 amount_before 和 amount_after，把正确与错误金额都写出来。', observe: '正确值和放大值会分开。', explanation: '金额必须和行数、唯一键一起看。', proves: '能把金额变化显影。', cannotProve: '不能证明真实收入。' },
      { title: 'gap-check', action: '把 NULL 键和缺失链接单独列出。', observe: '缺 user、缺 event、缺 order 可以分别看到。', explanation: '缺口和放大是两件不同的事。', proves: '能把缺口写出来。', cannotProve: '不能证明缺口原因。' },
      { title: 'write-log', action: '把 step_id、source_sql_ref、gap_note 和 next_sql_task 一起写进日志。', observe: 'multi-table-sql-log.md 形成闭环。', explanation: '日志要能复核，而不是只给结论。', proves: '能留下可复查记录。', cannotProve: '不能证明答案已经提前暴露。' },
    ],
    recordPrompts: [
      '记录 users、events、orders 的角色和连接键。',
      '记录第一步和第二步的 rows_before、rows_after。',
      '记录每一步的 unique_keys。',
      '记录 amount_before 和 amount_after。',
      '记录缺失链接和 gap_note。',
      '记录 can_prove、cannot_prove 和 next_sql_task。',
    ],
    comparePrompt: '对比 setup.sql、exercises.sql 和 answers.sql：你是否先完成了自己的记录，再去对照答案？',
    passCriteria: [
      '能说清 users、events、orders 各自的角色。',
      '能写出每一步 rows_before 和 rows_after。',
      '能写出 unique_keys 和 amount 的变化。',
      '能把缺口和边界单独写出来。',
    ],
  },
  independentLab: {
    title: '独立变式：改一处连接顺序，重算一次记录',
    scenario: '把 users→events→orders 改成 users→orders→events，再观察 row count、unique_keys 和 amount 发生什么变化。',
    conceptIds: ['join-chain-grain', 'step-row-count-audit', 'step-unique-key-audit', 'step-amount-audit', 'null-link-gap-audit', 'exercise-boundary', 'multi-table-sql-log'],
    changedConditions: [
      '把连接顺序从 users→events→orders 改成 users→orders→events。',
      '把第一步的 LEFT JOIN 改成 INNER JOIN。',
      '先不看 answers.sql，只靠自己的记录重写一次日志。',
    ],
    task: '先预测哪一步会改变 row count、unique_keys 和 amount，再把变化写进日志。',
    predictionPrompt: '如果连接顺序换了，哪一步最可能先改变 unique_keys？先写预测，再执行。',
    evidenceRequirements: [
      '连接顺序写清楚。',
      '每一步都有 row count 和 unique_keys。',
      'amount_before / amount_after 都有记录。',
      '不能把答案提前打开。',
    ],
    passCriteria: [
      '能说出新的连接顺序。',
      '能说明哪一步改变了粒度。',
      '能写出至少一个缺口或放大点。',
      '能写出有限结论和不能证明事项。',
    ],
    remediation: { label: '回看多表 SQL 记录', sectionId: 'diagram', anchor: 'w5d3-multi-table-sql-log' },
  },
  exercises: [
    exercise(
      'w5d3-table-role',
      ['概念与边界'],
      ['source-table-map', 'exercise-boundary'],
      '哪句话最适合先写进 W5D3 的记录？',
      ['users、events、orders 的角色和连接顺序先写清', '先打开 answers.sql 再决定怎么写', '只贴最后一条 SQL 就够了'],
      0,
      '先分清表角色，再开始连接和记录，才能解释后面的行数、唯一键和金额。',
    ),
    exercise(
      'w5d3-row-count',
      ['机制推演'],
      ['step-row-count-audit', 'join-chain-grain'],
      '哪一项最适合判断是哪一步改变了结果规模？',
      ['每一步的 rows_before 和 rows_after', '只看最后一行的数量', '只看 SQL 有几个 JOIN 关键字'],
      0,
      '逐步行数审计能把变化点拆开，单看最终行数看不出哪里变了。',
    ),
    exercise(
      'w5d3-unique-key',
      ['证据判断'],
      ['step-unique-key-audit', 'join-grain-amplification'],
      '为什么要在每一步记录 unique_keys？',
      ['它能看出键有没有被复制或放大', '它只是为了让表格更漂亮', '它能自动修复重复行'],
      0,
      '唯一键能揭示粒度是否变粗，比只看行数更接近真正的审计。',
    ),
    exercise(
      'w5d3-amount',
      ['工作场景'],
      ['step-amount-audit', 'join-grain-amplification'],
      '多表 SQL 里，amount_before 和 amount_after 为什么不能只记最后一个？',
      ['因为每一步都可能改变金额，要看变化点', '因为最后一个数字看起来最整齐', '因为金额只和答案有关'],
      0,
      '金额在多表链路里最容易被放大，必须和步骤一起看。',
    ),
    exercise(
      'w5d3-boundary',
      ['综合变式'],
      ['exercise-boundary', 'multi-table-sql-log'],
      '哪句 cannot_prove 最符合 W5D3？',
      ['不能证明真实生产行为、收入、报告或 answers.sql 已提前暴露', '已经证明真实生产已经完全正确', '已经证明最后一条 SQL 就等于分析结论'],
      0,
      'W5D3 只能证明本地多表 SQL 记录可复核，不能越界到真实生产结论。',
    ),
  ],
  deliverable: {
    title: '多表 SQL 记录',
    conceptIds: ['source-table-map', 'step-row-count-audit', 'step-unique-key-audit', 'step-amount-audit', 'null-link-gap-audit', 'exercise-boundary', 'multi-table-sql-log'],
    purpose: '把 W5 多表教学包里的 users、events 和 orders JOIN 过程写进 multi-table-sql-log.md，明确每一步的 row count、unique_keys、amount 和缺口。',
    whenToUse: '当需要向数据同事或产品评审解释多表 SQL 的过程、放大点和答案边界时。',
    audience: '产品经理、数据分析师、SQL 审阅者。',
    fields: [
      { name: 'step_id', meaning: '每一步连接或审计的编号。', source: '实验步骤和 exercise.sql' },
      { name: 'source_sql_ref', meaning: '这一步参考的是 setup.sql、exercises.sql 还是 answers.sql。', source: '教学包文件名' },
      { name: 'left_table', meaning: '当前步骤左侧的表。', source: 'SQL FROM / JOIN' },
      { name: 'right_table', meaning: '当前步骤右侧的表。', source: 'SQL FROM / JOIN' },
      { name: 'join_type', meaning: 'INNER、LEFT、RIGHT 或 FULL。', source: '本日连接顺序' },
      { name: 'join_key', meaning: '用于连接的字段。', source: 'user_id、event_id 或 order_id' },
      { name: 'rows_before', meaning: '本步骤前的行数。', source: 'stepwise join 之前' },
      { name: 'rows_after', meaning: '本步骤后的行数。', source: 'stepwise join 之后' },
      { name: 'unique_keys', meaning: '本步骤后的唯一键数量。', source: 'user_id、event_id、order_id' },
      { name: 'amount_before', meaning: '本步骤前的金额或汇总值。', source: '订单粒度对照线' },
      { name: 'amount_after', meaning: '本步骤后的金额或汇总值。', source: 'JOIN 结果' },
      { name: 'gap_note', meaning: '缺口、放大或 NULL 链接的说明。', source: 'NULL / mismatch / amplification' },
      { name: 'can_prove', meaning: '这一步能证明什么。', source: '本地教学记录' },
      { name: 'cannot_prove', meaning: '这一步不能证明什么。', source: '证据边界' },
      { name: 'next_sql_task', meaning: '下一步该做什么 SQL。', source: 'W5D4 及以后' },
    ],
    badExample: 'step_id: step-2\njoin_type: LEFT\nrows_after: 740\ncan_prove: SQL 已经跑通了',
    badReasons: [
      '只写最终结果，不写每一步行数、唯一键和金额。',
      '没有说明 740 是放大后的数字，而不是最终结论。',
      '没有写 gap_note、cannot_prove 和 next_sql_task。',
    ],
    revisionSteps: [
      '先补 source_sql_ref、left_table、right_table 和 join_key。',
      '再写 rows_before、rows_after、unique_keys、amount_before、amount_after。',
      '最后写 gap_note、can_prove、cannot_prove 和 next_sql_task。',
    ],
    goodExample: 'step_id: step-2\nsource_sql_ref: setup.sql + exercises.sql\nleft_table: users\nright_table: events\njoin_type: LEFT\njoin_key: user_id\nrows_before: 6\nrows_after: 10\nunique_keys: 6\namount_before: 440\namount_after: 440\ngap_note: events 里有部分 user_id 为空\ncan_prove: 本地教学链路能复核每一步的行数和唯一键\ncannot_prove: 不能证明真实生产行为或收入\nnext_sql_task: 先连 orders，再最后对照 answers.sql',
    guidedPrompts: [
      '先写 step_id 和 source_sql_ref。',
      '再写 left_table、right_table、join_type 和 join_key。',
      '补 rows_before、rows_after 和 unique_keys。',
      '补 amount_before、amount_after 和 gap_note。',
      '再写 can_prove、cannot_prove 和 next_sql_task。',
      '最后对照 exercises.sql，而不是先看 answers.sql。',
    ],
    blankTemplate: '```md\n# 多表 SQL 记录\n\n- step_id:\n- source_sql_ref:\n- left_table:\n- right_table:\n- join_type:\n- join_key:\n- rows_before:\n- rows_after:\n- unique_keys:\n- amount_before:\n- amount_after:\n- gap_note:\n- can_prove:\n- cannot_prove:\n- next_sql_task:\n```',
    standardTemplate: '# 多表 SQL 记录\n\n- step_id:\n- source_sql_ref:\n- left_table:\n- right_table:\n- join_type:\n- join_key:\n- rows_before:\n- rows_after:\n- unique_keys:\n- amount_before:\n- amount_after:\n- gap_note:\n- can_prove:\n- cannot_prove:\n- next_sql_task:\n',
    checklist: [
      '已写清三张表的角色。',
      '已写清每一步的 rows_before 与 rows_after。',
      '已写清 unique_keys 和 amount。',
      '已写清 gap_note。',
      '已写清 cannot_prove 和 next_sql_task。',
      '未提前打开 answers.sql。',
    ],
  },
  memory: {
    conceptIds: ['source-table-map', 'join-chain-grain', 'step-row-count-audit', 'step-unique-key-audit', 'step-amount-audit', 'null-link-gap-audit', 'exercise-boundary', 'multi-table-sql-log'],
    anchors: [
      '先分清 users、events、orders 的角色。',
      '每一步都记 rows_before 和 rows_after。',
      'unique_keys 能看出是否被复制。',
      'amount_before 和 amount_after 要一起看。',
      'answers.sql 只能最后对照。',
    ],
    closedBookPrompt: '闭卷解释表角色、连接链路、逐步行数、唯一键、金额和答案边界的差别，并各给一个 users/events/orders 的例子。',
    microOperation: '看到多表 SQL 后，先写 step_id、rows_before、rows_after、unique_keys、amount_before 和 amount_after。',
    unresolvedPrompt: '如果一条 event 没有对应 order，你会把它写进 gap_note 还是 amount？',
    reviewStages: [
      { stage: 'D1', task: '重写一次 users→events→orders 的连接顺序。' },
      { stage: 'D3', task: '复述每一步的 row count 和 unique_keys。' },
      { stage: 'D7', task: '用一个缺失 event 重新解释 gap_note。' },
      { stage: 'D14', task: '把 multi-table-sql-log.md 再复算一遍。' },
      { stage: 'D30', task: '闭卷说明 amount_before 和 amount_after 为什么要一起记。' },
      { stage: 'D60', task: '回头检查 exercises.sql 和 answers.sql 的边界。' },
    ],
  },
  nextLesson: {
    id: 'W5D4',
    title: '重复放大与数据缺口',
    bridge: '继续把多表 SQL 中的放大点和缺口拆开，只看过程证据，不直接下生产结论。',
  },
}
