import type { DailyCourse, Exercise } from './types'

const conceptIds = [
  'python-runtime-boundary',
  'statement-sequence',
  'input-output-boundary',
  'variable-assignment',
  'type-conversion-boundary',
  'branch-condition',
  'loop-iteration',
  'function-boundary',
] as const

const prerequisiteConceptIds = [
  'execution-order',
  'result-boundary',
  'network-evidence-boundary',
  'answer-log-boundary',
]

function exercise(
  id: string,
  categories: Exercise['categories'],
  conceptIdsForExercise: string[],
  prompt: string,
  options: string[],
  answerIndex: number,
  referenceAnswer: string,
  remediationLabel: string,
): Exercise {
  return {
    id,
    kind: 'single-choice',
    categories,
    conceptIds: conceptIdsForExercise,
    prompt,
    hint: '先把这一步放回脚本顺序里，再判断它是输入、赋值、分支、循环还是函数边界。',
    options: options.map((label, index) => ({
      label,
      rationale: index === answerIndex
        ? '这项把脚本步骤、输入输出和证据边界分开，最适合作为 W8D1 的结构判断。'
        : '这项要么把输出当证明，要么把类型、顺序和边界混成一件事。',
      couldBeTrueWhen: index === answerIndex
        ? '当脚本结构标注明确写出能证明什么、不能证明什么时。'
        : '只有在补齐后续清洗、异常处理或真实运行证据后，才可能重新判断。',
    })),
    answerIndex,
    referenceAnswer,
    reasoning: [
      'W8D1 先教脚本如何表达步骤，再看变量、类型、分支、循环和函数如何改变步骤。',
      '输入与输出只是脚本的边界；看到 print 不等于证明前面每一步都正确。',
      '本日成果只能把结构标注清楚，不能替代后续清洗、异常处理或自动摘要。',
    ],
    rubric: ['顺序和边界清楚', '输入输出不混淆', '没有越界到后续课程'],
    commonErrors: [
      { error: '把 print 当成完整证明', reason: '输出只能证明脚本走到了输出点，不能证明前面处理都正确。' },
      { error: '把 int() 当成最终结果', reason: '类型转换只是一步，不等于脚本已经完成了整条流程。' },
    ],
    remediation: {
      label: remediationLabel,
      sectionId: 'concepts',
      anchor: 'concept-python-runtime-boundary',
    },
  }
}

export const w8d1: DailyCourse = {
  id: 'W8D1',
  contentVersion: 'w8d1-python-step-structure-day01-v1',
  week: 8,
  day: 1,
  title: '程序如何表达步骤',
  subtitle: '把重复的产品工作写成 Python 脚本前，先看懂入口、语句顺序、输入输出、变量、类型、分支、循环和函数边界；本日只做代码结构标注，不提前进入 JSON、CSV、异常或文件批处理。',
  duration: { core: 30, standard: 45, extension: 60, full: 110 },
  coreConceptGroups: [
    {
      id: 'runtime-and-sequence',
      title: '先看运行边界和语句顺序',
      conceptIds: ['python-runtime-boundary', 'statement-sequence'],
      summary: 'Python 脚本先被解释器逐行读取，再按语句顺序执行；入口、退出和临时状态只在这次运行里存在。',
      boundary: '能说明脚本怎样开始、怎样结束、怎样按顺序前进；不能证明真实生产自动化已经完成。',
    },
    {
      id: 'io-variable-and-type',
      title: '输入、变量和类型如何把步骤连起来',
      conceptIds: ['input-output-boundary', 'variable-assignment', 'type-conversion-boundary'],
      summary: '输入把外部数据带进来，变量把当前值接住，类型转换把文本和数字分开，输出则把处理结果送出去。',
      boundary: '能标出 input、赋值和 int/str 转换的职责；不能把一次输出误写成数据正确或脚本稳定。 ',
    },
    {
      id: 'control-and-reuse',
      title: '分支、循环和函数把步骤变成可复用结构',
      conceptIds: ['branch-condition', 'loop-iteration', 'function-boundary'],
      summary: 'if 决定走哪条路，for 重复处理每条记录，def 把一段重复步骤收起来，让脚本更容易修改和复核。',
      boundary: '能判断某一步是在分流、重复还是封装；不能因为结构更清晰就自动证明业务结论。',
    },
  ],
  prerequisiteConceptIds,
  learningPaths: {
    '30': {
      guidedStepIndices: [0, 1, 2, 3],
      guidedRecordIndices: [0, 1, 2],
      exerciseCount: 3,
      deliverablePromptCount: 4,
      deliverableChecklistIndices: [0, 1, 2, 3],
      deliverableMinimumContributionCharacters: 180,
    },
    '45': {
      guidedStepIndices: [0, 1, 2, 3],
      guidedRecordIndices: [0, 1, 2],
      exerciseCount: 4,
      deliverablePromptCount: 5,
      deliverableChecklistIndices: [0, 1, 2, 3, 4],
      deliverableMinimumContributionCharacters: 260,
    },
  },
  primaryGoal: '提交一份 `code-structure-annotation.md`：把一段 Python 脚本的入口、语句顺序、输入输出、变量、类型转换、分支、循环和函数边界逐行标注清楚。',
  scenario: {
    role: '你是准备把重复产品工作自动化的产品经理。',
    situation: '团队每天下午都要把一份脱敏的业务输入整理成说明文字。你手里有一个 Python 教学脚本，但现在你最需要的不是立刻改出新功能，而是先看懂它一行一行是怎么表达步骤的。',
    question: '当一段 Python 脚本要把输入、变量、分支、循环和函数串起来时，怎样先看懂结构，再决定该改哪一行？',
    stakes: '如果把输出当证明、把类型转换当结果、把函数边界当业务结论，就会在修改脚本时误判风险，甚至把错误输入写成可信结论。',
  },
  objectives: [
    { id: 'w8d1-objective-sequence', text: '能按顺序标出 Python 脚本的入口、语句、分支、循环和函数边界。', evidence: '在 `code-structure-annotation.md` 中写出至少 4 个按顺序排列的步骤。' },
    { id: 'w8d1-objective-boundary', text: '能区分输入、变量、类型转换和输出分别负责什么。', evidence: '标注里能分开写 input、赋值、int/str 转换和 print/write 的作用。' },
    { id: 'w8d1-objective-evidence', text: '能说明脚本结构能证明和不能证明什么。', evidence: '每个结构标注都包含 can_prove 与 cannot_prove。' },
    { id: 'w8d1-objective-deliverable', text: '能交出可复核的代码结构标注。', evidence: '成果文件包含 step_id、statement_or_block、boundary、next_step 等字段。' },
  ],
  prerequisites: [
    {
      id: 'w8d1-order-readiness',
      conceptIds: ['execution-order', 'result-boundary'],
      prompt: '你能把一段脚本或查询的书写顺序和执行/结果边界分开说吗？',
      passDescription: '能说明“写在哪里”和“最后看到什么”不是一件事。',
      remediationLabel: '补学 W3D2：执行顺序图',
      remediationTarget: '#/lesson/W3D2',
      remediation: {
        purpose: '先会看顺序，才不会把代码里靠前的行和真实执行顺序混在一起。',
        steps: [
          '回看 W3D2 的 FROM → WHERE → SELECT → ORDER BY → LIMIT 顺序。',
          '用一条查询解释“书写顺序不等于结果证明”。',
        ],
        successCheck: '能把“先写了什么”和“实际证明了什么”分开。',
      },
    },
    {
      id: 'w8d1-evidence-readiness',
      conceptIds: ['network-evidence-boundary', 'answer-log-boundary'],
      prompt: '你能把运行看到的输出和你准备写入说明的结论区分开吗？',
      passDescription: '能用观察证据写出有限结论，而不是把输出直接写成真相。',
      remediationLabel: '补学 W1D5 / W3D6：证据边界',
      remediationTarget: '#/lesson/W3D6',
      remediation: {
        purpose: '脚本标注和自动化说明都要先守住“看到什么、不能证明什么”的边界。',
        steps: [
          '回看一条 Network 观察记录。',
          '回看一条业务查询交接说明。',
          '把观察结果改写成有限结论。',
        ],
        successCheck: '能写出一条不越界的脚本结构观察。',
      },
    },
  ],
  concepts: [
    {
      id: 'python-runtime-boundary',
      prerequisiteConceptIds: [],
      term: 'Python 运行边界',
      english: 'Python Runtime Boundary',
      definition: 'Python 运行边界是脚本被解释器逐行读取、执行并在当前进程里留下临时状态的边界；它决定这次运行从哪里开始、在哪里结束，以及输入、输出和临时变量怎样存在。',
      why: '如果不先看运行边界，就会把编辑器里的源码、命令行的执行、终端的输出和后续可复跑的结果混成一件事。',
      problemSolved: '回答“这段脚本究竟在什么环境里一步一步跑起来”。',
      input: 'Python 解释器、`.py` 脚本、命令行参数、当前工作目录和本次运行的外部数据。',
      output: '脚本执行后的打印结果、写出的文件、终端报错和当前进程里的临时状态。',
      systemPosition: '位于 Python 脚本和用户可见结果之间，是所有后续步骤的起点和终点。',
      process: [
        '解释器读取脚本。',
        '按语句顺序执行。',
        '在当前进程里维护临时变量。',
        '遇到输出或错误时把结果呈现给用户。',
      ],
      owner: '写脚本的人负责保持边界清楚；产品经理负责判断这次运行能证明到哪一步。',
      notResponsibleFor: '运行边界不负责证明业务价值、生产稳定或自动化已经上线。',
      compareWith: '源码文件是静态文本；运行边界是脚本被执行时才出现的临时过程。',
      evidence: [
        '命令行启动一次脚本会出现本次输出。',
        '刷新终端或重新运行后，临时变量不会自动保留。',
      ],
      failureModes: [
        '把编辑器里看到的代码误当成已经执行过的结果。',
        '把脚本运行成功误当成后续业务自动化已经上线。',
      ],
      pmUse: '先问“这一步是在脚本里、解释器里，还是输出里”，再决定改哪一段。',
      correctExample: '一个脚本从命令行启动后，先读取输入参数，再逐行处理并打印摘要；这只能证明本次运行按顺序执行。',
      incorrectExample: '我在编辑器里看见了代码，所以自动化已经完成了。',
    },
    {
      id: 'statement-sequence',
      prerequisiteConceptIds: ['python-runtime-boundary'],
      term: '语句顺序',
      english: 'Statement Sequence',
      definition: '语句顺序是 Python 默认的执行方式：先执行上面的语句，再执行下面的语句，除非分支、循环或函数调用改变了控制流。',
      why: '初学者最容易把“代码排版顺序”误当成“真实运行顺序”，导致修改时误判影响范围。',
      problemSolved: '回答“这行代码在脚本里什么时候发生”。',
      input: '一段按行排列的 Python 语句，以及它们之间的依赖关系。',
      output: '按步骤推进的执行路径，或被分支/循环/函数改变后的新路径。',
      systemPosition: '位于运行边界内部，是脚本最基础的推进规则。',
      process: [
        '从第一条可执行语句开始。',
        '执行当前语句的副作用或赋值。',
        '遇到分支、循环或函数时切换控制流。',
      ],
      owner: '脚本作者负责把顺序写得可读；产品经理负责按顺序复述。',
      notResponsibleFor: '语句顺序不负责证明每个值都正确，也不负责证明外部数据可信。',
      compareWith: '它不同于自然语言说明；脚本的顺序必须可执行、可复跑。',
      evidence: [
        '逐行标注后能说出第一步、第二步和第三步。',
        '改动某一行后，只受影响的后续步骤会变化。',
      ],
      failureModes: [
        '把最后一行 print 当成第一步。',
        '忽略分支、循环或函数会改变执行顺序。',
      ],
      pmUse: '读脚本时先画出执行顺序，再讨论逻辑对不对。',
      correctExample: '先读取原始输入，再进行转换，最后打印结果；如果中间有 if，只有条件满足时才进入对应分支。',
      incorrectExample: '写在文件最下面的 print 一定最后执行，所以前面的步骤可以不看。',
    },
    {
      id: 'input-output-boundary',
      prerequisiteConceptIds: ['python-runtime-boundary', 'statement-sequence'],
      term: '输入输出边界',
      english: 'Input/Output Boundary',
      definition: '输入输出边界是脚本和外部世界打交道的地方：`input()`、文件读取、命令行参数把数据带进来，`print()`、文件写出和返回值把处理结果送出去。',
      why: '只有先分清边界，才能知道脚本哪部分在读，哪部分在写，哪部分只是中间处理。',
      problemSolved: '回答“脚本从哪里拿数据，又把什么东西交出去”。',
      input: '用户键入、文本文件、CSV、环境变量、命令行参数或前一步的返回值。',
      output: '打印文本、写入文件、返回值或用于下一步的中间结果。',
      systemPosition: '连接脚本和外部文件、终端或下一个函数的接口处。',
      process: [
        '读取外部输入。',
        '在脚本内部加工。',
        '把结果打印或写回外部。',
      ],
      owner: '脚本作者要把输入输出写清；产品经理要知道输出能证明什么。',
      notResponsibleFor: '输出边界不负责证明数据质量、业务正确性或后续自动化是否稳定。',
      compareWith: '输入是脚本吸收的材料，输出是脚本交出的结果；两者都不是中间计算本身。',
      evidence: [
        'input() 返回的是当前读到的文本。',
        'print() 只能说明结果被送到终端。',
      ],
      failureModes: [
        '把打印结果当成输入已经合法。',
        '把写文件当成业务结果已经正确。',
      ],
      pmUse: '当脚本看起来“跑完了”时，先问它只是输出了什么，还是确实处理了什么。',
      correctExample: '脚本从命令行读取一个文件路径，再打印汇总文本；这说明读到了输入，也说明有输出。',
      incorrectExample: '看到了打印摘要，所以源文件内容一定都处理对了。',
    },
    {
      id: 'variable-assignment',
      prerequisiteConceptIds: ['statement-sequence', 'input-output-boundary'],
      term: '变量赋值',
      english: 'Variable Assignment',
      definition: '变量赋值是把当前值绑定到一个名字上，后续语句可以继续使用这个名字；重新赋值会让名字指向新的值。',
      why: 'Python 脚本里很多步骤其实就是“取值、改名、再继续用”；如果看不懂赋值，就看不懂脚本状态怎样被传下去。',
      problemSolved: '回答“这一行把什么值放到哪里，后面又怎么被用到”。',
      input: '右侧表达式计算出的值，以及左侧的变量名。',
      output: '一个在后续语句中可重复引用的名字。',
      systemPosition: '位于语句顺序内部，常常是脚本状态向前传递的基本方式。',
      process: [
        '先计算右侧值。',
        '再把值绑定给变量名。',
        '后续语句读取这个名字。',
      ],
      owner: '脚本作者负责让变量名有意义；产品经理负责看懂名字指向什么。',
      notResponsibleFor: '变量名只是当前值的标签，不自动证明业务状态永久不变。',
      compareWith: '赋值不是保存历史；它只表示当前运行中的名字指向哪个值。',
      evidence: [
        '重赋值后，后续语句会读取新的值。',
        '同一个名字在当前运行中可以多次指向不同值。',
      ],
      failureModes: [
        '把变量名当成固定事实。',
        '忽略重新赋值会改变后续步骤。',
      ],
      pmUse: '改脚本时先看变量名有没有表达当前用途，再看值有没有被更新。',
      correctExample: 'raw_count 先接住字符串 "12"，再被转换成整数 count，后续 if 用的是 count。',
      incorrectExample: '变量叫 count，所以它从一开始就是数字。',
    },
    {
      id: 'type-conversion-boundary',
      prerequisiteConceptIds: ['variable-assignment'],
      term: '类型转换边界',
      english: 'Type Conversion Boundary',
      definition: '类型转换边界是把一种数据形态改成另一种形态的地方，例如把文本转成数字、把数字转成字符串；这一步只改变类型，不自动改变业务含义。',
      why: 'Python 里 `input()` 常常返回字符串，很多脚本必须先转型才能比较、计算或拼接。',
      problemSolved: '回答“为什么这段脚本不能直接拿文本去做数字比较”。',
      input: '原始文本、数字字符串、列表项或文件里读出的值。',
      output: '新的值类型，例如 int、float 或格式化后的字符串。',
      systemPosition: '位于输入之后、比较或计算之前，是最容易出错的步骤之一。',
      process: [
        '检查当前值的类型。',
        '执行转换函数。',
        '在后续运算里使用转换后的值。',
      ],
      owner: '脚本作者负责在合适的位置转换；产品经理负责知道转换前后证明的东西不同。',
      notResponsibleFor: '类型转换不负责证明输入合法，也不负责证明脚本整体正确。',
      compareWith: '文本和数字看起来都像“12”，但能参与的运算完全不同。',
      evidence: [
        '`input()` 的结果默认是字符串。',
        '`int("08")` 会把文本变成数字 8。',
      ],
      failureModes: [
        '把字符串直接拿去做数字比较。',
        '把转换成功误当成整条流程都正确。',
      ],
      pmUse: '看到脚本报类型错时，先找转换边界，而不是立刻怀疑所有逻辑。',
      correctExample: '先把 raw_count 从字符串转成整数，再比较是否大于阈值 10。',
      incorrectExample: '只要输入是 "08"，脚本就已经知道这是 8。',
    },
    {
      id: 'branch-condition',
      prerequisiteConceptIds: ['type-conversion-boundary'],
      term: '条件分支',
      english: 'Branch Condition',
      definition: '条件分支是脚本根据一个判断结果走不同路径的结构，常见写法是 if/elif/else。条件本身只是决定走哪条路，不自动生成结果。',
      why: '自动化脚本常常需要在“有值、没值、超阈值、异常值”之间做选择，分支就是这个选择点。',
      problemSolved: '回答“当条件成立或不成立时，脚本会走哪条路径”。',
      input: '一个比较结果、布尔值或异常检查结果。',
      output: '被执行的分支代码，或跳过某段步骤后的新状态。',
      systemPosition: '位于脚本中间，控制后续步骤是否继续执行。',
      process: [
        '先计算条件。',
        '条件真时执行 if 分支。',
        '条件假时执行 else 分支或跳过。',
      ],
      owner: '脚本作者负责把条件写得清楚；产品经理负责知道每条路径的边界。',
      notResponsibleFor: '分支本身不负责证明选中的路径就是业务上正确的。',
      compareWith: '分支是控制流选择，不是结果证明。',
      evidence: [
        '同一个输入在不同条件下会走不同路径。',
        '分支改变了后续是否执行某一步。',
      ],
      failureModes: [
        '把 if 的存在误当成脚本已经验证完毕。',
        '忽略 else 分支可能是最重要的异常路径。',
      ],
      pmUse: '评审脚本时，先确认哪些条件会分流，再确认每条分流后的结果写给谁看。',
      correctExample: 'count > 10 时打印 high，否则打印 normal。',
      incorrectExample: '只要写了 if，脚本就已经自动处理了所有情况。',
    },
    {
      id: 'loop-iteration',
      prerequisiteConceptIds: ['statement-sequence', 'branch-condition'],
      term: '循环迭代',
      english: 'Loop Iteration',
      definition: '循环迭代是对一组输入重复执行同一段步骤的结构，例如对多条记录逐条处理。循环改变的是重复次数和每次迭代的当前对象。',
      why: '自动化最常见的价值就是把“对每一条都做一次”的重复工作收起来。',
      problemSolved: '回答“脚本怎样重复处理多条记录而不手工复制代码”。',
      input: '一个列表、文件中的多行、查询结果或其他可迭代对象。',
      output: '每次迭代后的局部结果，以及累积起来的最终结果。',
      systemPosition: '位于处理流程中段，让脚本把同样的逻辑应用到多个对象。',
      process: [
        '取得第一个对象。',
        '执行一次处理。',
        '继续下一个对象，直到结束。',
      ],
      owner: '脚本作者负责写出稳定的迭代边界；产品经理负责知道每条记录是否都被覆盖。',
      notResponsibleFor: '循环本身不证明每条记录都合法，也不证明累计结果一定正确。',
      compareWith: '循环是重复执行，不是一次性结论。',
      evidence: [
        '同一段逻辑会被多条记录重复调用。',
        '每次迭代都能留下单独的观察点。',
      ],
      failureModes: [
        '把第一条结果当作全部结果。',
        '循环里混入对单条异常的假设，导致全批中断。',
      ],
      pmUse: '当脚本要处理多条数据时，先确认循环是否会漏掉空值、异常值或边界项。',
      correctExample: 'for row in rows 会逐条处理每一行，再把有效结果收集起来。',
      incorrectExample: '有了 for 循环，所以所有数据一定都处理成功。',
    },
    {
      id: 'function-boundary',
      prerequisiteConceptIds: ['loop-iteration', 'statement-sequence'],
      term: '函数边界',
      english: 'Function Boundary',
      definition: '函数边界是把一组重复步骤包起来、提供输入并返回结果的边界。函数让脚本中的一段逻辑可以被反复调用，而不必每次重写。',
      why: '当步骤开始重复、逻辑开始变长时，函数能把“做什么”和“何时做”分开。',
      problemSolved: '回答“哪一段代码应该被重复调用，哪一段只定义一次”。',
      input: '传给函数的参数，以及函数内部可能读取的外部值。',
      output: '函数返回值、局部副作用或抛出的错误。',
      systemPosition: '位于脚本内部的可复用单元，通常包着一个稳定的处理步骤。',
      process: [
        '定义输入参数。',
        '在函数体内执行步骤。',
        '返回结果或产生明确副作用。',
      ],
      owner: '脚本作者负责把复用逻辑收拢；产品经理负责知道函数输入输出是否说清。',
      notResponsibleFor: '函数边界不负责证明业务结果已成立，只负责把重复逻辑变得可读、可测和可复用。',
      compareWith: '循环是重复同一段步骤；函数是把这段步骤命名后再重复调用。',
      evidence: [
        '同一段逻辑可以被多个地方调用。',
        '函数输入和返回值清楚时更容易复核。',
      ],
      failureModes: [
        '把函数名当成业务结论。',
        '函数内部偷偷改外部状态，导致边界不清。',
      ],
      pmUse: '看见 def 时先问“它输入什么、输出什么、复用什么步骤”。',
      correctExample: 'def build_line(raw_text): ... return cleaned_line 会把清洗步骤封装起来。',
      incorrectExample: '函数名叫 build_line，所以 line 一定已经生成好了。',
    },
  ],
  diagram: {
    title: '一段 Python 脚本的步骤链',
    caption: '从入口读到输出，先分清输入、赋值、类型转换、分支、循环和函数边界，再写有限结论。',
    nodes: [
      { id: 'entry', label: '脚本入口', description: '解释器开始执行脚本。', input: 'py 文件和命令行', output: '本次运行', owner: 'Python 解释器' },
      { id: 'input', label: '输入收集', description: '读取命令行、文本或文件。', input: '外部文本或路径', output: 'raw 值', owner: '脚本作者' },
      { id: 'transform', label: '赋值与转换', description: '把当前值绑到变量，并在需要时转换类型。', input: 'raw 值', output: '可继续处理的值', owner: '脚本作者' },
      { id: 'control', label: '分支与循环', description: '决定是否分流、重复或进入函数。', input: '条件或记录集合', output: '多条路径', owner: '脚本逻辑' },
      { id: 'output', label: '输出结果', description: '打印、写文件或返回值。', input: '处理后的值', output: '可见结果', owner: '脚本作者' },
    ],
    branches: [
      { from: 'entry', to: 'input', label: '开始执行', kind: 'normal' },
      { from: 'input', to: 'transform', label: '读到输入', kind: 'normal' },
      { from: 'transform', to: 'control', label: '进入判断/重复/复用', kind: 'normal' },
      { from: 'transform', to: 'output', label: '类型错误或路径错误', kind: 'failure' },
      { from: 'control', to: 'output', label: '完成处理并输出', kind: 'normal' },
    ],
    evidenceNotes: [
      'print 只能证明脚本走到了输出点，不能证明前面的步骤都正确。',
      'int() 只能证明发生了类型转换，不能证明输入内容本身可信。',
      'for 和 def 改变的是控制流和复用方式，不等于业务结论已经成立。',
    ],
  },
  demonstration: {
    title: '把脚本拆成可标注的步骤',
    businessProblem: '产品团队每天要把脱敏输入整理成一段摘要。你手里有一份教学脚本，需要先标出它的结构，才能决定下一步怎么改成可复用工具。',
    finalConclusion: '这段脚本的步骤可以被拆成入口、输入、赋值、转换、分支、循环、函数和输出；标注这些边界后，才能安全讨论如何自动化。',
    conclusionLimit: '本次示范只证明脚本结构可读、边界可标注；不能证明真实业务已经自动化、输出已经正确或数据已经清洗完成。',
    steps: [
      {
        title: '先找脚本入口',
        action: '把脚本第一条可执行语句和命令行输入标出来。',
        reason: '入口决定本次运行从哪里开始，也决定这次处理依赖哪些外部值。',
        evidence: '看到 `python app.py summary.txt` 和脚本首行的读取语句。',
        proves: '能定位运行边界和输入起点。',
        limitation: '不能证明 summary.txt 内容本身正确。',
      },
      {
        title: '再看赋值和转换',
        action: '把 `raw_text = ...`、`count = int(raw_count)` 之类的行拆开标注。',
        reason: '变量和类型转换决定当前值是文本还是数字。',
        evidence: '看到 `raw_count` 接住字符串，`count` 接住整数。',
        proves: '能解释值是怎样在脚本里传下去的。',
        limitation: '不能证明原始输入一定合法。',
      },
      {
        title: '标出分支和循环',
        action: '把 if/for 的条件和重复对象写出来。',
        reason: '这两类结构会改变控制流，决定后续哪一步会执行多少次。',
        evidence: '看到 `if count > 10` 和 `for row in rows`。',
        proves: '能说清脚本为什么会走不同路径。',
        limitation: '不能证明分支选择本身就是正确业务决定。',
      },
      {
        title: '最后找函数边界和输出',
        action: '把 def 包住的重复步骤和 print/write 的出口一起标注。',
        reason: '函数让重复逻辑可复用，输出则把处理结果交出去。',
        evidence: '看到 `def build_summary(...)` 和 `print(summary)`。',
        proves: '能区分复用边界和输出边界。',
        limitation: '不能证明输出就代表结果可信。',
      },
      {
        title: '写清有限结论',
        action: '把结构标注整理成 code-structure-annotation.md。',
        reason: '产品经理需要的是可复核的结构判断，而不是把输出直接当结论。',
        evidence: '能写出入口、赋值、分支、循环、函数和输出各自的职责。',
        proves: '能交出一份可审阅的结构标注。',
        limitation: '不能证明自动化已经上线。',
      },
    ],
  },
  guidedLab: {
    title: '代码结构标注观察器',
    goal: '给一段脱敏 Python 伪代码贴上入口、赋值、类型转换、分支、循环和函数边界。',
    safety: '只看教学模拟，不执行真实脚本，不读取真实文件或账号数据。',
    conceptIds: ['python-runtime-boundary', 'statement-sequence', 'input-output-boundary', 'variable-assignment', 'type-conversion-boundary', 'branch-condition', 'loop-iteration', 'function-boundary'],
    predictionPrompt: '先预测：entry-input、assignment-conversion、branch-condition、loop-iteration、function-output、qualified-annotation 这六条路径分别会影响哪些步骤？如果把 `raw_count` 从 "12" 改成 "08"，哪些步骤会变，哪些步骤不会变？',
    steps: [
      {
        title: '找入口和输入',
        action: '把脚本入口、命令行输入和第一条读取语句圈出来。',
        observe: '入口先发生，输入先进入脚本。',
        explanation: '先确认运行边界，再看后面的结构。',
        proves: '能定位起点。',
        cannotProve: '不能证明后续处理一定正确。',
      },
      {
        title: '标赋值和转换',
        action: '把变量赋值和 int/str 转换标成单独步骤。',
        observe: '同一个名字会接住不同形态的值。',
        explanation: '赋值传递当前状态，转换改变值类型。',
        proves: '能解释变量怎样继续传下去。',
        cannotProve: '不能证明输入本身可信。',
      },
      {
        title: '找分支和循环',
        action: '把 if/for 的条件和重复对象写出来。',
        observe: '条件决定路径，循环决定重复次数。',
        explanation: '这两类结构改变控制流。',
        proves: '能说明为什么脚本会走不同路径。',
        cannotProve: '不能证明路径选择就是正确结论。',
      },
      {
        title: '标函数和输出',
        action: '把 def 的边界和 print/write 的出口圈出来。',
        observe: '函数封装一组步骤，输出送出结果。',
        explanation: '复用边界和输出边界不是同一个东西。',
        proves: '能分开复用与输出。',
        cannotProve: '不能证明输出已代表真实业务正确。',
      },
    ],
    recordPrompts: [
      '哪一行最先接住外部输入？',
      '哪一行改变了值的类型或控制流？',
      '哪一行只是输出，不足以证明前面都正确？',
    ],
    comparePrompt: '把 entry-input、assignment-conversion、branch-condition、loop-iteration、function-output、qualified-annotation 六条路径分别标成不同颜色，再比较哪些步骤只改值、哪些步骤改路径。',
    passCriteria: [
      '能把入口、输入、赋值、分支、循环和函数都标出来。',
      '能写出至少 3 条记录，并说清能证明什么、不能证明什么。',
      '改动输入后，能指出哪几步需要重新判断。',
    ],
  },
  independentLab: {
    title: '独立变式：把一段脚本改成更稳的步骤图',
    scenario: '同一份脚本要把一条摘要改成多条记录处理：先从 "12" 解析数字，再在阈值处分支，最后对三条脱敏记录循环输出。现在把输入改成 "08" 并加上一条缺字段记录，看看哪些步骤会变。',
    conceptIds: ['python-runtime-boundary', 'statement-sequence', 'input-output-boundary', 'variable-assignment', 'type-conversion-boundary', 'branch-condition', 'loop-iteration', 'function-boundary'],
    changedConditions: [
      '把 raw_count 从 "12" 改成 "08"',
      '把输入文件路径换成另一个脱敏路径',
      '在记录列表里加入一条缺字段样本',
    ],
    task: '写出改动后的代码结构标注，并说明 entry-input、assignment-conversion、branch-condition、loop-iteration、function-output、qualified-annotation 哪一步会变、哪一步不变、哪一步需要补防护。',
    predictionPrompt: '先预测：路径变化、类型变化和缺字段变化分别会影响哪些步骤？',
    evidenceRequirements: [
      '至少写出 2 个会变的步骤',
      '至少写出 1 个不会变的边界',
      '写出一条 can_prove / cannot_prove',
    ],
    passCriteria: [
      'changed_condition 与预测匹配。',
      '结构标注里有入口、转换、分支、循环和函数边界。',
      '结论没有越界到真实自动化或生产结果。',
    ],
    remediation: {
      label: '回看代码结构标注模板',
      sectionId: 'deliverable',
      anchor: 'w8d1-code-structure-fields',
    },
  },
  exercises: [
    exercise(
      'w8d1-sequence-boundary',
      ['概念与边界'],
      ['python-runtime-boundary', 'statement-sequence'],
      '哪句话最符合 W8D1 的结构边界？',
      ['print 只能证明脚本跑到了输出点，不能证明前面的步骤都正确', '只要 print 了结果，说明数据一定没问题', '脚本能运行一次，就说明自动化已经上线'],
      0,
      '输出只能证明脚本走到了出口，不能证明前面的输入、赋值和类型转换都正确。',
      '回到运行边界',
    ),
    exercise(
      'w8d1-conversion-order',
      ['机制推演'],
      ['variable-assignment', 'type-conversion-boundary'],
      '关于 `raw = input(); count = int(raw); if count > 10:`，哪条顺序最准确？',
      ['先读到字符串，再转换成数字，最后用数字决定是否进入分支', '先比较再转换，所以字符串也能直接做数字判断', '只要有 int()，脚本就自动把所有输入都判对了'],
      0,
      '先得到原始文本，再赋值给变量，再做类型转换，最后才进入分支判断。',
      '回看赋值和类型转换',
    ),
    exercise(
      'w8d1-evidence-log',
      ['证据判断', '工作场景'],
      ['input-output-boundary', 'network-evidence-boundary', 'answer-log-boundary'],
      '脚本报错 `ValueError: invalid literal for int()` 时，最稳妥的做法是什么？',
      ['先记下输入值、转换位置和错误信息，再判断是类型边界还是路径问题', '直接把这个报错写成“脚本已经证明输入正确”', '先改 print 文案就能消除所有错误'],
      0,
      '报错只是说明类型转换点失败，应该先记录输入值、错误位置和可复现条件，再决定下一步。',
      '回看证据边界',
    ),
    exercise(
      'w8d1-control-flow-variant',
      ['综合变式', '工作场景'],
      ['branch-condition', 'loop-iteration', 'function-boundary'],
      '如果把重复处理逻辑封成 `def`，同时让循环跳过缺字段记录，哪条说法最稳妥？',
      ['函数让复用更清晰，循环让重复更明确，但仍不能证明业务结论已正确', '有了 def 和 for，脚本就已经等于自动化上线', '只要脚本更短，所有风险都会消失'],
      0,
      '函数和循环只是把步骤组织得更清楚，真正能证明的仍然只有脚本结构与局部边界。',
      '回看控制流与复用边界',
    ),
  ],
  deliverable: {
    title: '代码结构标注',
    conceptIds: ['python-runtime-boundary', 'statement-sequence', 'input-output-boundary', 'variable-assignment', 'type-conversion-boundary', 'branch-condition', 'loop-iteration', 'function-boundary'],
    purpose: '把一段 Python 脚本的入口、赋值、转换、分支、循环、函数和输出边界逐行标清，让后续修改有据可依。',
    whenToUse: '当你要把重复产品工作改成脚本，或者要向别人解释脚本为什么这样写时。',
    audience: '未来要修改这段脚本的产品经理、研发同学和自己。',
    fields: [
      { name: 'step_id', meaning: '步骤编号，便于逐行引用。', source: '脚本顺序' },
      { name: 'statement_or_block', meaning: '这一行或这一块代码具体做什么。', source: '代码正文' },
      { name: 'role', meaning: '它是入口、赋值、转换、分支、循环、函数还是输出。', source: '结构判断' },
      { name: 'input', meaning: '这一行读取了什么或依赖什么值。', source: '输入边界' },
      { name: 'output', meaning: '这一行产生了什么结果或状态。', source: '输出边界' },
      { name: 'boundary', meaning: '这一步的职责边界和不能证明的内容。', source: '证据边界' },
      { name: 'can_prove', meaning: '当前结构能证明到哪一层。', source: '结构观察' },
      { name: 'cannot_prove', meaning: '当前结构还不能证明什么。', source: '有限结论' },
      { name: 'next_step', meaning: '下一课或下一次修改建议。', source: '课程衔接' },
    ],
    badExample: '我把脚本贴上去，下面只写“会自动生成摘要，所以 Python 很方便”。这没有说明入口、赋值、转换、分支、循环和函数各自做什么。',
    badReasons: [
      '没有把脚本拆成可引用的逐步标注。',
      '把输出结果直接当成了完整证明。',
      '没有写出每一步仍然不能证明什么。',
    ],
    revisionSteps: [
      '先把脚本拆成 step_id。',
      '再把每步的 role、input、output 和 boundary 写清楚。',
      '最后补上 can_prove、cannot_prove 和 next_step。',
    ],
    goodExample: `code-structure-annotation.md\n\nstep_id: 1\nstatement_or_block: raw_count = input("count: ").strip()\nrole: 输入收集\ninput: 命令行文本\noutput: 原始字符串 raw_count\nboundary: 这里只是读取输入，还不能证明内容合法\ncan_prove: 脚本拿到了一个字符串，已确认输入结构\ncannot_prove: 不能证明这个字符串已经可计算\nnext_step: 如需比较，先做 int(raw_count)\n\nstep_id: 2\nstatement_or_block: count = int(raw_count)\nrole: 类型转换\ninput: 原始字符串\noutput: 数字 count\nboundary: 这里只是把文本转成数字，不代表业务结论\ncan_prove: 已发生类型转换，结构可以继续向下推进\ncannot_prove: 不能证明后续分支一定正确\nnext_step: 再看 if count > 10`,
    guidedPrompts: [
      '先写入口和第一条输入语句。',
      '再把每个赋值和类型转换改成“旧值 → 新值”。',
      '把 if、for 和 def 分别标成控制流边界。',
      '每一行都写出能证明什么和不能证明什么。',
      '最后把 next_step 只指向 W8D2，不提前写 JSON、CSV 或报错诊断。',
    ],
    blankTemplate: `code-structure-annotation.md\n\nstep_id: \nstatement_or_block: \nrole: \ninput: \noutput: \nboundary: \ncan_prove: \ncannot_prove: \nnext_step: \n`,
    standardTemplate: `code-structure-annotation.md\n\nmode: 教学模拟\n\nstep_id: 1\nstatement_or_block: raw_count = input("count: ").strip()\nrole: 输入收集\ninput: 命令行文本\noutput: 原始字符串 raw_count\nboundary: 这里只是读取输入，还不能证明内容合法\ncan_prove: 脚本拿到了一个字符串，已确认输入结构\ncannot_prove: 不能证明这个字符串已经可计算\nnext_step: 如需比较，先做 int(raw_count)\n\nstep_id: 2\nstatement_or_block: count = int(raw_count)\nrole: 类型转换\ninput: 原始字符串\noutput: 数字 count\nboundary: 这里只是把文本转成数字，不代表业务结论\ncan_prove: 已发生类型转换，结构可以继续向下推进\ncannot_prove: 不能证明后续分支一定正确\nnext_step: 再看 if count > 10\n\nstep_id: 3\nstatement_or_block: if count > 10:\nrole: 条件分支\ninput: 数字 count\noutput: 高值路径或普通路径\nboundary: 条件只决定走哪条路，不自动证明结论\ncan_prove: 分支路径已被选择，结构进入下一步\ncannot_prove: 不能证明选择本身正确\nnext_step: W8D2 再把完整输入到输出流程图画出来\n`,
    checklist: [
      '入口、输入和输出都已标出。',
      '至少三步写出了能证明和不能证明。',
      '分支、循环和函数边界没有混在一起。',
      'next_step 明确指向 W8D2。',
      '明确写出教学模拟边界，不声称真实自动化或生产结果已完成。',
    ],
  },
  memory: {
    conceptIds: ['python-runtime-boundary', 'statement-sequence', 'input-output-boundary', 'variable-assignment', 'type-conversion-boundary', 'branch-condition', 'loop-iteration', 'function-boundary'],
    anchors: [
      '脚本入口与运行边界',
      '语句顺序与输入输出',
      '变量赋值与类型转换',
      '控制流与函数复用',
    ],
    closedBookPrompt: '闭卷复述：Python 脚本如何从入口、顺序、输入输出、变量、类型转换、分支、循环和函数边界表达步骤？',
    microOperation: '在任意 5 行 Python 伪代码旁边标出入口、赋值、转换、分支、循环、函数和输出。',
    unresolvedPrompt: '如果你只能先学一个边界，你最想先区分输入边界、类型边界还是输出边界？',
    reviewStages: [
      { stage: 'D1', task: '重画一条脚本的入口、赋值和输出顺序。' },
      { stage: 'D3', task: '解释一次类型转换为什么不能直接当作结果。' },
      { stage: 'D7', task: '闭卷说出 if、for 和 def 的不同边界。' },
      { stage: 'D14', task: '拿一段新脚本重新做结构标注，不看答案。' },
      { stage: 'D30', task: '用一段自动化脚本解释输入、转换和输出的关系。' },
      { stage: 'D60', task: '说明 W8D1 与 W8D2 的边界：结构标注 vs 输入到输出流程图。' },
    ],
  },
  nextLesson: {
    id: 'W8D2',
    title: '从输入到输出',
    bridge: '下一课才把步骤结构串成完整的输入→处理→输出流程图；W8D1 只做代码结构标注，不提前进入 JSON、CSV、文件写出或报错诊断。',
  },
}
