import type { DayId } from './types'
import type { Day01FrameworkPlan } from './day01Framework'

export const w8d1Framework: Day01FrameworkPlan = {
  dayId: 'W8D1',
  label: '程序如何表达步骤',
  chapters: [
    {
      id: 'chapter-1',
      number: 1,
      session: 1,
      timeMinutes: 8,
      title: '建立任务：先看脚本怎样表达步骤',
      lead: 'W8D1 不急着处理 JSON、CSV、异常或文件批处理。先把 Python 脚本的入口、输入、顺序和输出看明白，再决定哪一行值得修改。',
      conceptIds: ['python-runtime-boundary', 'statement-sequence'],
      semanticSections: ['scenario', 'objectives', 'prerequisites'],
      practice: {
        prompt: '同事说“脚本都写完了，直接看最后一行就行”。你最先纠正什么？',
        options: ['先看入口、顺序和中间步骤，再看最后一行输出', '直接跳到 print 就够了', '先判断业务结论是否已正确'],
        answerIndex: 0,
        explanation: 'W8D1 先看脚本怎样表达步骤，不能把输出当成全部证据。',
      },
      retellPrompt: '用两三句话说明：为什么 W8D1 先看运行边界和语句顺序，而不是直接看输出？',
      retellRubric: ['提到入口和顺序', '提到输出不是证明', '没有越界到后续课程'],
    },
    {
      id: 'chapter-2',
      number: 2,
      session: 1,
      timeMinutes: 14,
      title: '模型一：运行边界和语句顺序',
      lead: 'Python 解释器先读取脚本，再按语句顺序执行；运行边界决定这次处理从哪里开始、在哪里结束，以及临时状态怎样存在。',
      conceptIds: ['python-runtime-boundary', 'statement-sequence', 'input-output-boundary'],
      semanticSections: ['concepts'],
      practice: {
        prompt: '哪句话最符合 Python 的默认执行方式？',
        options: ['先执行上面的语句，再执行下面的语句，除非分支、循环或函数改变控制流', '写在文件底部的语句一定最后执行，所以前面都不用看', 'print 一出现就代表前面所有步骤都正确'],
        answerIndex: 0,
        explanation: 'Python 默认按语句顺序执行，只有控制流结构会改变路径。',
      },
      retellPrompt: '闭卷解释“运行边界”和“语句顺序”分别在脚本里负责什么。',
      retellRubric: ['区分边界和顺序', '说清解释器先读后跑', '不把输出当结论'],
    },
    {
      id: 'chapter-3',
      number: 3,
      session: 1,
      timeMinutes: 14,
      title: '模型二：输入、变量和类型边界',
      lead: '输入把外部数据带进来，变量接住当前值，类型转换把文本和数字分开，输出则把处理结果送出去。',
      conceptIds: ['variable-assignment', 'type-conversion-boundary'],
      semanticSections: ['concepts', 'diagram'],
      practice: {
        prompt: '为什么 `input()` 的结果不能直接当数字比较？',
        options: ['因为 `input()` 默认返回字符串，先转型才适合比较', '因为 Python 不支持任何比较', '因为变量名叫 count，所以一定已经是数字'],
        answerIndex: 0,
        explanation: '输入边界先给出字符串，比较前通常要先做类型转换。',
      },
      retellPrompt: '用“输入→赋值→类型转换→输出”复述这一章。',
      retellRubric: ['说清输入输出', '说清变量与转换', '没有混淆字符串和数字'],
    },
    {
      id: 'chapter-4',
      number: 4,
      session: 1,
      timeMinutes: 10,
      title: '第一次复述检查：结构标注不等于结果证明',
      lead: '这一章不增加新术语。你要把入口、语句顺序、输入输出、赋值和类型转换连成一条线，再说清它们还不能证明什么。',
      conceptIds: ['python-runtime-boundary', 'statement-sequence', 'input-output-boundary', 'variable-assignment', 'type-conversion-boundary'],
      semanticSections: ['concepts', 'diagram'],
      practice: {
        prompt: '哪条说法没有越界？',
        options: ['print 只能证明脚本走到了出口，不能证明前面每一步都正确', '只要打印了摘要，就已经证明输入合法', '看到 int() 就代表整条脚本都正确'],
        answerIndex: 0,
        explanation: '结构标注只能说明脚本怎样走，不等于业务结论已经成立。',
      },
      retellPrompt: '用“看到／可以判断／不能判断”复述 W8D1 前半段。',
      retellRubric: ['看懂入口和顺序', '区分输入和输出', '不把结果写成证明'],
    },
    {
      id: 'chapter-5',
      number: 5,
      session: 2,
      timeMinutes: 16,
      title: '操作模型：把脚本拆成可标注的步骤',
      lead: '把一段脚本拆成入口、赋值、转换、分支、循环和函数边界，才能安全讨论该改哪一行。',
      conceptIds: ['python-runtime-boundary', 'statement-sequence', 'input-output-boundary', 'variable-assignment', 'type-conversion-boundary', 'branch-condition'],
      semanticSections: ['demonstration', 'guided-lab'],
      practice: {
        prompt: '当脚本里出现 `if count > 10:` 时，最准确的作用是什么？',
        options: ['它根据条件决定走哪条路径', '它已经证明 count 一定正确', '它只是把 print 提前而已'],
        answerIndex: 0,
        explanation: '分支只决定路径，不负责证明路径本身正确。',
      },
      retellPrompt: '解释分支、循环和函数边界分别改变了什么。',
      retellRubric: ['说清条件分支', '说清循环重复', '说清函数复用'],
    },
    {
      id: 'chapter-6',
      number: 6,
      session: 2,
      timeMinutes: 12,
      title: '责任与证据边界：重复和复用不等于结论',
      lead: 'for 会重复处理多条记录，def 会把重复步骤包起来；这两种结构让脚本更清楚，但不会自动把输出升级成业务结论。',
      conceptIds: ['branch-condition', 'loop-iteration', 'function-boundary'],
      semanticSections: ['independent-lab', 'feedback'],
      practice: {
        prompt: '哪条说法最稳妥？',
        options: ['函数和循环让结构更清楚，但不能证明业务结论已正确', '有了 for 和 def，脚本就等于自动化上线', '只要脚本更短，风险就消失了'],
        answerIndex: 0,
        explanation: '循环和函数改变组织方式，不等于结果就可信。',
      },
      retellPrompt: '用“能证明／不能证明／下一步”说明循环和函数边界。',
      retellRubric: ['提到重复处理', '提到函数复用', '提到有限结论'],
    },
    {
      id: 'chapter-7',
      number: 7,
      session: 2,
      timeMinutes: 18,
      title: '实验、代码结构标注与最终复述',
      lead: '最后完成结构标注、针对性练习和代码结构标注文件：每一段都要写清入口、输入、输出、边界和下一步。',
      conceptIds: [
        'python-runtime-boundary',
        'statement-sequence',
        'input-output-boundary',
        'variable-assignment',
        'type-conversion-boundary',
        'branch-condition',
        'loop-iteration',
        'function-boundary',
      ],
      semanticSections: ['exercises', 'deliverable', 'memory', 'completion'],
      practice: {
        prompt: '一份合格的代码结构标注最关键的组合是什么？',
        options: ['step_id、statement_or_block、boundary、can_prove、cannot_prove 和 next_step', '只写“脚本能跑”', '直接贴原始代码不标注'],
        answerIndex: 0,
        explanation: '成果必须可复核、有限定边界，并指向下一步。',
      },
      retellPrompt: '最终复述 Python 脚本怎样从入口、顺序、输入输出、变量、类型、分支、循环和函数边界表达步骤。',
      retellRubric: ['八个概念都能说到', '字段齐全', '没有越界到后续课程'],
    },
  ],
}

export function getW8D1FrameworkPlan(dayId: DayId): Day01FrameworkPlan | undefined {
  return dayId === 'W8D1' ? w8d1Framework : undefined
}
