import type { DailyCourse, Exercise } from './types'

const conceptIds = [
  'script-input-contract',
  'raw-value-capture',
  'intermediate-state-flow',
  'transformation-step',
  'decision-path',
  'output-contract',
  'flow-trace',
  'execution-flow-diagram',
] as const

const prerequisiteConceptIds = [
  'python-runtime-boundary',
  'statement-sequence',
  'input-output-boundary',
  'variable-assignment',
  'type-conversion-boundary',
  'branch-condition',
  'loop-iteration',
  'function-boundary',
]

function exercise(
  id: string,
  categories: Exercise['categories'],
  conceptIdsForExercise: string[],
  prompt: string,
  options: string[],
  answerIndex: number,
  referenceAnswer: string,
  remediationLabel: string,
): Exercise {
  return {
    id,
    kind: 'single-choice',
    categories,
    conceptIds: conceptIdsForExercise,
    prompt,
    hint: '先把输入、变量、判断和输出依次摆回脚本顺序，再决定哪一句话越界了。',
    options: options.map((label, index) => ({
      label,
      rationale: index === answerIndex
        ? '这项把原始值、变量接力和输出契约分开，最适合作为 W8D2 的流程判断。'
        : '这项要么把流程图当结果，要么把分支、转换和输出混成一件事。',
      couldBeTrueWhen: index === answerIndex
        ? '当脚本只要求先追踪输入到输出的路径，而不要求证明真实业务结论时。'
        : '只有补齐真实数据、更多分支或后续课程后，才可能重新判断。',
    })),
    answerIndex,
    referenceAnswer,
    reasoning: [
      'W8D2 先把输入、变量接力、判断路径和输出契约串起来，再画执行流程图。',
      '原始值、转换步骤和分支路径都只是流程中的一段，不等于最终业务真相。',
      '本日成果只能证明路径被画清，不能证明 JSON、CSV 或文件批处理已经完成。',
    ],
    rubric: ['路径和契约清楚', '原始值与变量分开', '没有提前越过 W8D3'],
    commonErrors: [
      { error: '把输出当成全量证明', reason: '输出只能说明脚本走到了出口，不能证明中间每一步都可信。' },
      { error: '把 raw value 当成最终结论', reason: '原始值只是起点，不是业务判断结果。' },
    ],
    remediation: {
      label: remediationLabel,
      sectionId: 'concepts',
      anchor: 'concept-flow-trace',
    },
  }
}

export const w8d2: DailyCourse = {
  id: 'W8D2',
  contentVersion: 'w8d2-input-output-flow-day01-v1',
  week: 8,
  day: 2,
  title: '从输入到输出',
  subtitle: '沿变量变化读懂一段业务脚本；先把输入契约、原始值、变量接力、判断路径和输出契约串起来，再画执行流程图，不提前进入 JSON、CSV、文件批处理或报错诊断。',
  duration: { core: 30, standard: 45, extension: 40, full: 110 },
  coreConceptGroups: [
    {
      id: 'input-and-capture',
      title: '先定输入契约和原始值',
      conceptIds: ['script-input-contract', 'raw-value-capture'],
      summary: '先说清外部输入要给脚本什么，再把原始值原样接住，避免一开始就把结论写进变量。',
      boundary: '能说明输入字段、原始值和首个变量如何接力；不能证明来源数据本身就真实或完整。',
    },
    {
      id: 'state-and-transform',
      title: '中间状态与转换步骤',
      conceptIds: ['intermediate-state-flow', 'transformation-step'],
      summary: '变量之间的接力和类型/格式转换决定脚本下一步能不能继续跑；这一步只是在处理，不是在下结论。',
      boundary: '能标出状态如何变化、哪一步做了转换；不能把转换本身写成最终业务判断。',
    },
    {
      id: 'paths-and-output',
      title: '判断路径和输出契约',
      conceptIds: ['decision-path', 'output-contract', 'flow-trace', 'execution-flow-diagram'],
      summary: '分支决定脚本走哪条路，输出契约决定最后交出去的是什么；流程图要把路径和出口都画出来。',
      boundary: '能描述条件改变会怎样影响路径和输出；不能把一张流程图当成真实业务结果证明。',
    },
  ],
  prerequisiteConceptIds,
  learningPaths: {
    '30': {
      guidedStepIndices: [0, 1, 2, 3],
      guidedRecordIndices: [0, 1, 2],
      exerciseCount: 3,
      deliverablePromptCount: 4,
      deliverableChecklistIndices: [0, 1, 2, 3],
      deliverableMinimumContributionCharacters: 200,
    },
    '45': {
      guidedStepIndices: [0, 1, 2, 3],
      guidedRecordIndices: [0, 1, 2],
      exerciseCount: 5,
      deliverablePromptCount: 5,
      deliverableChecklistIndices: [0, 1, 2, 3, 4],
      deliverableMinimumContributionCharacters: 280,
    },
  },
  primaryGoal: '提交一份 `execution-flow-diagram.md`：把一段业务脚本的输入、原始值、变量接力、判断路径和输出契约画成可复核的流程图。',
  scenario: {
    role: '你是要把一段业务脚本讲给同事听的产品经理。',
    situation: '运营脚本每天都要接收一小段表单或命令行输入，再把中间状态整理成给业务同事看的输出。你手里只有脚本的步骤描述，不想一上来就把结果当成真相。',
    question: '当一段脚本要把输入转成输出时，怎样沿着变量变化把每一步画清楚，而不是把最后一行当成全部结论？',
    stakes: '如果把原始值、变量接力、判断路径和输出契约混在一起，就会把错误输入、错误转换和错误出口统统误写成正确结果。',
  },
  objectives: [
    { id: 'w8d2-objective-input', text: '能区分输入契约和原始值，不把字段名、变量名和业务结论混在一起。', evidence: '在流程图里写出 input_source、raw_value 和 state_variable。' },
    { id: 'w8d2-objective-flow', text: '能沿着变量变化看懂中间状态是怎样被传下去的。', evidence: '能说明哪个变量接住了哪个值，哪个步骤改变了它。' },
    { id: 'w8d2-objective-path', text: '能区分判断路径和输出契约。', evidence: '能写出 decision_path、output_target 和 cannot_prove。' },
    { id: 'w8d2-objective-deliverable', text: '能交出一份可复核的执行流程图。', evidence: '成果文件包含 flow_id、transform_step、next_step 等字段。' },
  ],
  prerequisites: [
    {
      id: 'w8d2-input-readiness',
      conceptIds: ['python-runtime-boundary', 'input-output-boundary', 'variable-assignment', 'type-conversion-boundary'],
      prompt: '你能把脚本的输入边界和变量接住的值分开说吗？',
      passDescription: '能说明“从哪里来”和“先落到哪里”不是同一件事。',
      remediationLabel: '补学 W8D1：输入与变量边界',
      remediationTarget: '#/lesson/W8D1',
      remediation: {
        purpose: '先确认输入边界和变量赋值，后面才不会把原始值和结果混成一条线。',
        steps: [
          '回看 W8D1 的输入输出边界。',
          '把一条输入读到变量的过程说清楚。',
          '再判断它与最终输出的区别。',
        ],
        successCheck: '能说出输入、变量和输出各自负责什么。',
      },
    },
    {
      id: 'w8d2-path-readiness',
      conceptIds: ['statement-sequence', 'branch-condition', 'loop-iteration', 'function-boundary'],
      prompt: '你能把顺序、分支和函数对脚本路径的影响分开吗？',
      passDescription: '能说出哪一步只是接力，哪一步会改路径。',
      remediationLabel: '补学 W8D1：步骤和路径',
      remediationTarget: '#/lesson/W8D1',
      remediation: {
        purpose: '先会看路径变化，才不会把最后一行或某个函数名误写成结论。',
        steps: [
          '回看 W8D1 的语句顺序。',
          '把一个分支和一个函数边界说给自己听。',
          '再把它们放回一条脚本里复述。',
        ],
        successCheck: '能把路径变化和输出结果分开。',
      },
    },
  ],
  concepts: [
    {
      id: 'script-input-contract',
      prerequisiteConceptIds: ['input-output-boundary'],
      term: '脚本输入契约',
      english: 'Script Input Contract',
      definition: '脚本输入契约是外部数据进入流程前的约定：哪些字段必须存在，什么格式算可读，缺了什么要先停下来。它不是业务真相本身，而是脚本开始处理前必须满足的入口条件。',
      why: '如果不先写清输入契约，脚本读到的每一段文本都可能被误当成同一种有效输入，后续步骤就会在错误前提上继续推进。',
      problemSolved: '回答“这段脚本到底需要什么输入才可以开始”。',
      input: '表单字段、命令行参数、文本摘要、金额字符串或一个待处理的记录对象。',
      output: '一组可被脚本继续处理的输入条件，或者一条说明缺少字段的停步信息。',
      systemPosition: '位于外部来源和第一条本地变量之间，是流程的入口约束。',
      process: [
        '先列出必填字段和可选字段。',
        '再检查格式和最小长度。',
        '最后决定继续还是停步。',
      ],
      owner: '脚本作者负责把契约写进代码；产品经理负责知道哪些输入能进流程，哪些必须先补齐。',
      notResponsibleFor: '输入契约不负责证明数据是真的，只负责说明什么样的数据可以进入脚本。',
      compareWith: '契约像门口的通行规则，原始输入像刚递进来的包裹；前者是约定，后者是内容。',
      evidence: [
        '缺少一个必填字段时，脚本会先进入停步分支。',
        '只要格式变化，脚本的后续变量就会跟着不同。',
      ],
      failureModes: [
        '把备注文本也当成结构化字段。',
        '把“能进来”误写成“已经正确”。',
      ],
      pmUse: '先判断输入是否满足流程，再谈输出该长什么样。',
      correctExample: '脚本要求 order_id 和 order_total 都存在，才会开始生成摘要。',
      incorrectExample: '只要脚本收到了任何文字，就说明输入契约已经满足。',
    },
    {
      id: 'raw-value-capture',
      prerequisiteConceptIds: ['python-runtime-boundary', 'input-output-boundary'],
      term: '原始值捕获',
      english: 'Raw Value Capture',
      definition: '原始值捕获是脚本第一次把外部数据放进本地变量时的动作。它保留的是最初收到的样子，通常还没有清洗、转换或判断，目的是让后续步骤能看见最开始的输入长什么样。',
      why: '如果一开始就把值改掉，后面就再也看不见原始输入了；一旦结果有争议，也很难回头说明问题从哪一步开始出现。',
      problemSolved: '回答“脚本第一眼看到的值是什么”。',
      input: '原样进入的文本、数字字符串、空值标记或命令行参数。',
      output: '一个保存原始值的本地变量，或者一条说明字段不完整的停步记录。',
      systemPosition: '位于输入契约之后、任何转换之前，是流程中的第一块本地接收垫。',
      process: [
        '把外部输入落到本地变量。',
        '保留原始形态不做结论。',
        '给后续步骤留下可追踪的起点。',
      ],
      owner: '写脚本的人要保证原始值能被保留下来；产品经理要知道它只是起点，不是结论。',
      notResponsibleFor: '原始值捕获不负责把数据修好，也不负责判断数据是不是业务上正确。',
      compareWith: '它像一份未签字的原件；后续转换后的值才是复印件上的加工结果。',
      evidence: [
        '原始字符串和转型后的数值可以同时被对照。',
        '回头看日志时，原始值能解释后续分支为什么会变。',
      ],
      failureModes: [
        '把原始值覆盖掉，只留下加工后的结果。',
        '把原始值直接当成可比较的最终值。',
      ],
      pmUse: '先保存原始值，再决定要不要比较、拆分或转换。',
      correctExample: 'raw_amount = "0080" 先把原始字符串接住，后面再看要不要转成数字。',
      incorrectExample: '一开始就把原始文本改成结论，所以后面无需追踪。',
    },
    {
      id: 'intermediate-state-flow',
      prerequisiteConceptIds: ['variable-assignment'],
      term: '中间状态接力',
      english: 'Intermediate State Flow',
      definition: '中间状态接力是脚本把一个变量的当前值传给下一个变量或下一个步骤的过程。每一次接力都会留下一个正在被处理的状态，但那个状态还不是最终输出。',
      why: '很多脚本不是一步到终点，而是一路换手；如果不看接力，就会以为只有最后的结果才重要，忽略了中间哪一段把值弄歪了。',
      problemSolved: '回答“当前值是怎么一路传下去的”。',
      input: '上一步留下的变量值、临时字段和正在处理的状态对象。',
      output: '一个更接近可判断状态的中间变量，或者下一步要继续使用的值。',
      systemPosition: '位于原始值和最终判断之间，是脚本内部的换手带。',
      process: [
        '读取上一步留下的状态。',
        '把状态交给下一个变量。',
        '在每次换手后保留可追踪痕迹。',
      ],
      owner: '脚本作者负责接力写清楚；产品经理负责知道当前值处于哪一段，不把中间状态当终点。',
      notResponsibleFor: '接力本身不负责证明结果对不对，只负责让状态能一路被追踪。',
      compareWith: '它像接力棒；每次交接都在变位置，但还没有冲过终点线。',
      evidence: [
        '同一条记录在多个变量里留下了不同形态的值。',
        '中间状态能解释为什么后面会进入某个分支。',
      ],
      failureModes: [
        '把中间状态直接写成最终摘要。',
        '忽略变量换手，导致看不见问题出现在哪一步。',
      ],
      pmUse: '看脚本时先问“这个值现在被谁接住了”。',
      correctExample: 'clean_amount 接住了原始金额后的中间状态，后来才送去判断。',
      incorrectExample: '变量一旦出现，就代表业务结论已经生成。',
    },
    {
      id: 'transformation-step',
      prerequisiteConceptIds: ['type-conversion-boundary'],
      term: '转换步骤',
      english: 'Transformation Step',
      definition: '转换步骤是脚本把原始值改写成另一种更适合判断或输出的形态：可能是去空格、转数字、改单位、拼字段，也可能是拆分后再重组。它只负责把值变得可继续处理，不负责替最终结论背书。',
      why: '如果不把转换单独标出来，字符串、数字、格式化文本和业务结论就会被揉成一团，出了问题也看不出是哪一次转换造成的。',
      problemSolved: '回答“脚本在什么时候把值改了形态”。',
      input: '原始字符串、临时变量、待解析字段或一个可转换的值。',
      output: '更适合判断、排序、计算或输出的新值。',
      systemPosition: '位于原始值之后、判断路径之前，是处理链里最容易被忽略的一环。',
      process: [
        '识别要改哪一种形态。',
        '执行去空格、转数字或拆分。',
        '保留转换前后的对应关系。',
      ],
      owner: '脚本作者负责写出转换；产品经理负责知道哪一段只是加工，不是结论。',
      notResponsibleFor: '转换步骤不负责证明原值合法，也不负责证明结果一定正确。',
      compareWith: '它像给原料换了一个更适合加工的容器；容器变了，物料未必就已经合格。',
      evidence: [
        '同一个值在转换前后表现出不同类型。',
        '只有转换后，后面的判断才有意义。',
      ],
      failureModes: [
        '把转换前的文本当成数字。',
        '把一次格式化误写成完整结论。',
      ],
      pmUse: '先找转换，再谈判断；不要把字符串外观看成数字事实。',
      correctExample: '脚本先把 " 12 " 去空格再转成数字，才继续比较。',
      incorrectExample: '看见有 int()，就说明整条脚本已经正确。',
    },
    {
      id: 'decision-path',
      prerequisiteConceptIds: ['branch-condition'],
      term: '判断路径',
      english: 'Decision Path',
      definition: '判断路径是脚本遇到条件时选择的下一段执行路线。它说明流程为什么走向某个出口，但并不自动证明这条出口就是业务上最对的出口。',
      why: '同一份输入在不同条件下可能走向不同分支；如果不先画路径，就会把“被选中的路”误当成“唯一正确的路”。',
      problemSolved: '回答“为什么脚本走了这条路而不是另一条”。',
      input: '条件表达式、阈值、空值检查或一个需要比较的状态值。',
      output: '一条分支后的执行路线，或者一个提示为什么停步的说明。',
      systemPosition: '位于转换步骤之后、输出之前，是流程中决定方向的闸门。',
      process: [
        '读取当前状态。',
        '比较条件或阈值。',
        '选择下一段执行路线。',
      ],
      owner: '脚本作者负责把判断写成可读条件；产品经理负责识别路径变化带来的业务影响。',
      notResponsibleFor: '判断路径不负责证明条件本身正确，也不负责证明输出一定可信。',
      compareWith: '它像路口的红绿灯；灯变了路就变，但不代表目的地一定最好。',
      evidence: [
        '改变一个条件后，脚本会进入不同分支。',
        '同一条输入能产生不同路径而不是同一出口。',
      ],
      failureModes: [
        '把某个分支写成唯一真理。',
        '把条件判断误解成结果证明。',
      ],
      pmUse: '看见 if 时先问“如果条件反过来，路径会怎样变”。',
      correctExample: '当 amount > 1000 时，脚本给出人工复核路径；否则走自动摘要。',
      incorrectExample: '只要进入某个分支，就说明业务结论已经成立。',
    },
    {
      id: 'output-contract',
      prerequisiteConceptIds: ['input-output-boundary', 'statement-sequence'],
      term: '输出契约',
      english: 'Output Contract',
      definition: '输出契约是脚本最后交出去的内容约定：交给下游的是一段文本、一条状态、一个返回值，还是写入文件的记录。它负责说明出口长什么样，不负责把所有中间过程自动变成真相。',
      why: '如果只盯着最后输出，就会把“交出的形式”误当成“已经证明的事实”，从而高估脚本的可信度。',
      problemSolved: '回答“脚本最后交出去的东西是什么”。',
      input: '处理后的变量、分支结果、格式化文本或一个返回值。',
      output: '终端文本、文件内容、返回值、下一步任务标记或状态消息。',
      systemPosition: '位于执行链的出口处，是与下游交换信息的最后一站。',
      process: [
        '把处理后的状态整理成出口格式。',
        '通过 print、return 或写文件交出去。',
        '保留出口与中间过程的区别。',
      ],
      owner: '脚本作者负责定义出口；产品经理负责知道出口能证明什么、不能证明什么。',
      notResponsibleFor: '输出契约不负责证明流程每一步都正确，也不负责证明下游一定接受。',
      compareWith: '它像快递单上的收件说明；交付形式清楚，不等于货物里面的每一层都已核验。',
      evidence: [
        '输出格式可以被下游读取或展示。',
        '出口变化通常意味着上游步骤也发生了变化。',
      ],
      failureModes: [
        '把输出样式当成业务结论。',
        '把写文件当成全链路成功。',
      ],
      pmUse: '先看最后交出去的是什么，再看它能说明到哪一步。',
      correctExample: '脚本输出一条“待复核”状态消息，而不是直接宣布业务完成。',
      incorrectExample: '看到了输出，所以所有中间处理都已经被证明正确。',
    },
    {
      id: 'flow-trace',
      prerequisiteConceptIds: ['statement-sequence', 'variable-assignment', 'branch-condition'],
      term: '流程痕迹',
      english: 'Flow Trace',
      definition: '流程痕迹是把输入、变量接力、转换步骤、判断路径和输出出口连起来的一串可复核记录。它不是自动生成的结果报告，而是把脚本怎么走过来说明清楚的轨迹。',
      why: '只有轨迹被写出来，读脚本的人才知道哪一步改了值、哪一步改了路、哪一步把内容交出去了。',
      problemSolved: '回答“这条脚本路径是怎么被走出来的”。',
      input: '步骤顺序、变量变化、分支条件和输出结果。',
      output: '一条可复核的流程线索，或者一个说明当前路径的痕迹表。',
      systemPosition: '位于观察者和脚本之间，把运行过程翻译成可读证据。',
      process: [
        '记录每一步接住了什么值。',
        '标出每一次转换和判断。',
        '把这些片段串成一条线。',
      ],
      owner: '产品经理负责整理痕迹；脚本作者负责让痕迹可被复核。',
      notResponsibleFor: '流程痕迹不负责自动判对错，只负责让路径透明。',
      compareWith: '它像脚印，不是奖牌；能说明走过哪儿，不能说明一定走得对。',
      evidence: [
        '能把输入到输出的每个变化点串起来。',
        '换一个条件后，痕迹会跟着变。',
      ],
      failureModes: [
        '只记录最后输出，不记录中间变化。',
        '把痕迹写成结果宣传稿。',
      ],
      pmUse: '先看痕迹是否完整，再判断脚本是否值得继续改。',
      correctExample: '流程痕迹里能看到 raw_value、state_variable、decision_path 和 output_target 的对应关系。',
      incorrectExample: '只要有一张表，就等于已经证明业务正确。',
    },
    {
      id: 'execution-flow-diagram',
      prerequisiteConceptIds: ['script-input-contract', 'raw-value-capture', 'intermediate-state-flow', 'transformation-step', 'decision-path', 'output-contract', 'flow-trace'],
      term: '执行流程图',
      english: 'Execution Flow Diagram',
      definition: '执行流程图是把输入契约、原始值、变量接力、转换步骤、判断路径和输出契约放在同一张图里的成果。它的目标是让人沿着变量变化看懂脚本怎么走，而不是把最后结果包装成绝对真相。',
      why: '如果没有这张图，脚本一长就很难知道哪一步在接力、哪一步在转换、哪一步在分支；有了图，才知道下一次应该改哪一段。',
      problemSolved: '回答“这段脚本从输入到输出到底是怎么走的”。',
      input: '全部已知步骤、变量名、条件和输出出口。',
      output: '一张可以复核的流程图，或者一份可读的执行路径说明。',
      systemPosition: '位于阅读、复述和交接之间，是把脚本变成业务语言的中间成果。',
      process: [
        '把输入和原始值画成起点。',
        '把变量接力和转换画成中段。',
        '把判断路径和输出契约画成出口。',
      ],
      owner: '产品经理负责把流程画成能复核的版本；脚本作者负责保证图上的每一步都能回到真实脚本。',
      notResponsibleFor: '流程图不负责证明生产结论，只负责让路径透明、边界可查。',
      compareWith: '它像路线图；能告诉你从哪里出发、在哪拐弯、最后停在哪儿，但不能替你把路上每个车况都证明完。',
      evidence: [
        '图中可以逐步指回脚本的变量变化。',
        '换一个输入后，流程图上的分支会变。',
      ],
      failureModes: [
        '把流程图写成结果海报。',
        '把一张图当成真实业务已完成的证据。',
      ],
      pmUse: '先画流程图，再决定要不要继续进入 JSON、CSV 或文件批处理。',
      correctExample: '一张图清楚标出 raw_value → state_variable → decision_path → output_target 的变化。',
      incorrectExample: '流程图一画完，就说明业务处理已经自动完成。',
    },
  ],
  diagram: {
    title: '一段业务脚本的输入到输出路径',
    caption: '先看输入契约，再追踪原始值、变量接力、转换、判断和出口；流程图只说明路径，不替真实业务结果背书。',
    nodes: [
      { id: 'entry', label: '输入入口', description: '脚本收到表单或命令行数据。', input: '外部字段', output: '待接收输入', owner: '脚本入口' },
      { id: 'capture', label: '原始值捕获', description: '第一个本地变量先把原始值接住。', input: '原始文本或数字字符串', output: 'raw value', owner: '脚本作者' },
      { id: 'state', label: '中间状态', description: '变量接力把当前值送到下一步。', input: 'raw value', output: 'state variable', owner: '脚本逻辑' },
      { id: 'decision', label: '判断路径', description: '条件决定继续哪条路。', input: 'state variable', output: 'branch path', owner: '脚本逻辑' },
      { id: 'output', label: '输出出口', description: '把结果交给终端、文件或下游。', input: 'branch result', output: 'output target', owner: '脚本作者' },
    ],
    branches: [
      { from: 'entry', to: 'capture', label: '接住输入', kind: 'normal' },
      { from: 'capture', to: 'state', label: '保留原始值', kind: 'normal' },
      { from: 'state', to: 'decision', label: '进入判断', kind: 'normal' },
      { from: 'decision', to: 'output', label: '符合出口条件', kind: 'normal' },
      { from: 'state', to: 'output', label: '缺字段或格式不对', kind: 'failure' },
    ],
    evidenceNotes: [
      '原始值和转换后变量要分开看，不能混写成一个结论。',
      '判断路径只说明选路，不说明结果已经被证明。',
      '输出契约只说明交出去的形式，不说明真实业务已经完成。',
    ],
  },
  demonstration: {
    title: '把输入到输出拆成可追踪路径',
    businessProblem: '运营同事每天会给一段脱敏记录，脚本要把它整理成一条状态说明。你需要先画出输入到输出的路，而不是直接把输出结果当成业务证明。',
    finalConclusion: '这段脚本可以被拆成输入契约、原始值、变量接力、转换、判断和输出契约；画出这些边界后，才知道下一次该改哪一步。',
    conclusionLimit: '本次示范只证明路径和边界可以被画清；不能证明真实业务已经处理正确、JSON/CSV 已完成或文件批处理已经上线。',
    steps: [
      {
        title: '先写输入契约',
        action: '把脚本需要的字段和格式先列出来。',
        reason: '入口条件决定脚本能不能继续往下走。',
        evidence: '看到必填字段和可选字段被单独标注。',
        proves: '能先区分什么能进来、什么要停步。',
        limitation: '不能证明输入内容是真的。',
      },
      {
        title: '再抓住原始值',
        action: '把外部值原样放进第一个变量，不急着改。',
        reason: '保留原始值才能知道问题最早从哪里出现。',
        evidence: '原始字符串和本地变量同时可见。',
        proves: '能追到第一眼看到的数据长什么样。',
        limitation: '不能证明原始值已经可用。',
      },
      {
        title: '标变量接力和转换',
        action: '把变量换手和类型/格式变化写成两步。',
        reason: '接力和转换常常决定脚本后面能不能继续判断。',
        evidence: '看到变量从文本变成更适合比较的值。',
        proves: '能解释中间状态怎样被推进。',
        limitation: '不能证明转换后的值就是最终结论。',
      },
      {
        title: '画出判断路径',
        action: '把 if/else 的分流条件和出口写出来。',
        reason: '条件只决定走哪条路，不替结论背书。',
        evidence: '看到某个条件成立时走复核，不成立时走自动输出。',
        proves: '能说清为什么会出现不同路径。',
        limitation: '不能证明分支选择一定是业务上最优。',
      },
      {
        title: '收口到输出契约',
        action: '把最后交出的文本、状态或返回值单独标出来。',
        reason: '输出契约让人知道脚本交出了什么，而不是把中间过程混掉。',
        evidence: '看到终端文本、文件内容或返回值被单独列出。',
        proves: '能把出口和中间状态分开。',
        limitation: '不能证明真实业务结果已经成立。',
      },
    ],
  },
  guidedLab: {
    title: '输入到输出流程图观察器',
    goal: '给一段脱敏业务脚本贴上输入、原始值、变量接力、判断路径和输出契约。',
    safety: '只做教学模拟，不运行真实脚本，不读取真实文件、账号或生产数据。',
    conceptIds: ['script-input-contract', 'raw-value-capture', 'intermediate-state-flow', 'transformation-step', 'decision-path', 'output-contract', 'flow-trace', 'execution-flow-diagram'],
    predictionPrompt: '先预测：raw-input、state-flow、transform-step、decision-path、output-target、qualified-flow-map 这六条路径分别会影响哪一段流程？如果把原始金额从 "0080" 改成 "0008"，哪些步骤会变，哪些步骤不会变？',
    steps: [
      {
        title: '找输入契约',
        action: '把输入字段和最早的原始值圈出来。',
        observe: '入口先决定能不能继续处理。',
        explanation: '先确认脚本接住了什么，再看后面的变化。',
        proves: '能定位输入边界。',
        cannotProve: '不能证明业务结果已经正确。',
      },
      {
        title: '标原始值和接力',
        action: '把原始值和接住它的变量分开标。',
        observe: '原始值先被保留，再进入下一段。',
        explanation: '原始值和中间状态不是同一个东西。',
        proves: '能解释值怎样被传下去。',
        cannotProve: '不能证明原始输入本身可信。',
      },
      {
        title: '找转换和判断',
        action: '把去空格、转数字和分支条件写出来。',
        observe: '转换改变值形态，条件决定路径。',
        explanation: '转换和判断分别承担不同职责。',
        proves: '能说清哪一步改了值，哪一步改了路。',
        cannotProve: '不能证明条件选择一定是最优业务结果。',
      },
      {
        title: '标输出出口',
        action: '把 print、return 或写文件的出口单独圈出来。',
        observe: '出口只交付最终形式。',
        explanation: '出口说明输出契约，不说明全部过程都正确。',
        proves: '能把输出与中间变量分开。',
        cannotProve: '不能证明真实生产结论。',
      },
    ],
    recordPrompts: [
      '输入字段和原始值是什么？',
      '中间变量怎样接住原始值？',
      '哪个判断决定了输出出口？',
    ],
    comparePrompt: '把输入、转换、判断和输出放在同一张图里，对照哪一步只是接力，哪一步已经开始分流。',
    passCriteria: [
      '能先写输入契约，再写原始值。',
      '能把变量接力和转换分开。',
      '能把判断路径和输出契约分开。',
    ],
  },
  independentLab: {
    title: '独立变式：换一个输入，流程图怎么变',
    scenario: '同一个脚本把会员等级、订单金额和备注整理成一条业务提示。你要把一个输入条件改掉，再画一次执行流程图。',
    conceptIds: ['script-input-contract', 'raw-value-capture', 'intermediate-state-flow', 'transformation-step', 'decision-path', 'output-contract', 'flow-trace', 'execution-flow-diagram'],
    changedConditions: [
      '备注字段从有文字变为空字符串',
      '金额字段从字符串变成数字类型',
      '会员等级从 VIP 变成普通用户',
    ],
    task: '画出新的执行流程图，并写一段有限结论，说明哪些变量、判断和出口发生了变化。',
    predictionPrompt: '先预测：改动上面一个条件后，脚本会不会走到同一个输出？为什么？',
    evidenceRequirements: [
      '写出 raw_value 和 state_variable 的变化。',
      '指出至少一个 decision_path 的变化。',
      '说明 output_target 为什么变了或没变。',
    ],
    passCriteria: [
      '流程图里有输入、转换、判断和输出。',
      '结论里明确写出能证明什么。',
      '结论里明确写出不能证明什么。',
    ],
    remediation: {
      label: '补学 W8D1：路径和变量接力',
      sectionId: 'concepts',
      anchor: '#concept-flow-trace',
    },
  },
  exercises: [
    exercise(
      'w8d2-q1',
      ['概念与边界'],
      ['script-input-contract', 'raw-value-capture'],
      '脚本最先要确认的是什么？',
      ['输入契约和原始值能否被分开接住', '最后的输出文字长什么样', '条件分支已经证明结果正确'],
      0,
      '先确认输入契约，再抓住原始值，才能知道后续变量接住的到底是什么。',
      '输入契约',
    ),
    exercise(
      'w8d2-q2',
      ['机制推演'],
      ['intermediate-state-flow', 'transformation-step'],
      '为什么原始值不应该立刻被改成结论？',
      ['因为中间状态和转换步骤还要被追踪，改太早会丢失起点', '因为原始值一定是错的', '因为输出契约只看最后一行'],
      0,
      '原始值要保留给流程中的后续判断和转换，不然就看不出问题最早出现在哪一步。',
      '原始值与中间状态',
    ),
    exercise(
      'w8d2-q3',
      ['证据判断'],
      ['flow-trace', 'output-contract'],
      '哪条说法最符合证据边界？',
      ['流程痕迹只能说明路径被走过，不能证明真实业务已完成', '只要有输出，就说明整个脚本都已正确', '看到分支就等于结果已证明'],
      0,
      '流程痕迹和输出契约都只是在说明路径和出口，不是在宣布业务真相。',
      '流程痕迹',
    ),
    exercise(
      'w8d2-q4',
      ['工作场景'],
      ['decision-path', 'output-contract'],
      '订单金额低于阈值时，脚本改走自动摘要。这个变化说明了什么？',
      ['判断路径变了，输出契约也可能跟着变，但并不代表业务结论自动成立', '说明所有输入都已经合法', '说明数据已经清洗完成'],
      0,
      '条件变化会改路径，也可能改出口，但不能替代对真实业务的验证。',
      '判断路径',
    ),
    exercise(
      'w8d2-q5',
      ['综合变式'],
      ['execution-flow-diagram', 'flow-trace'],
      '一份合格的 execution-flow-diagram.md 最关键的组合是什么？',
      ['input_source、raw_value、state_variable、decision_path、output_target、can_prove、cannot_prove、next_step', '只写“脚本已经输出了”', '直接把 W8D3 的 JSON/CSV 结果写进去'],
      0,
      '流程图文件必须把输入到输出的路径、边界和下一步写清楚，不能提前冒充后续课程成果。',
      '执行流程图',
    ),
  ],
  deliverable: {
    title: '执行流程图',
    conceptIds: ['script-input-contract', 'raw-value-capture', 'intermediate-state-flow', 'transformation-step', 'decision-path', 'output-contract', 'flow-trace', 'execution-flow-diagram'],
    purpose: '把脚本的输入、原始值、变量接力、转换步骤、判断路径和输出契约整理成一份能复核的流程图。',
    whenToUse: '当你要把一段业务脚本讲给同事、评审或后续实现者听，并且需要说明流程是怎样从输入走到输出时。',
    audience: '准备继续改脚本、接手脚本或复查脚本的人。',
    fields: [
      { name: 'flow_id', meaning: '这条流程的唯一编号，方便和脚本版本对应。', source: '脚本名称、日期或业务场景编号。' },
      { name: 'input_source', meaning: '输入从哪里来，像表单、命令行还是上一段返回值。', source: '输入契约和脚本入口。' },
      { name: 'raw_value', meaning: '第一次接住的原始值，保留未加工形态。', source: '第一条本地变量。' },
      { name: 'state_variable', meaning: '中间状态由哪个变量接住，怎么一路被传下去。', source: '变量接力记录。' },
      { name: 'transform_step', meaning: '哪一步做了去空格、转数字、拆分或重组。', source: '转换语句或处理步骤。' },
      { name: 'decision_path', meaning: '条件如何决定下一段执行路线。', source: '分支条件和出口选择。' },
      { name: 'output_target', meaning: '最后交出去的是终端、文件、返回值还是状态消息。', source: '输出契约。' },
      { name: 'can_prove', meaning: '这张图能证明到哪一层。', source: '流程痕迹和出口说明。' },
      { name: 'cannot_prove', meaning: '这张图不能证明什么。', source: '证据边界说明。' },
      { name: 'next_step', meaning: '下一步应该去做什么。', source: '当前流程的边界和下一课程。' },
    ],
    badExample: [
      '# execution-flow-diagram.md',
      '',
      'flow_id: done',
      'input_source: 任何输入都行',
      'raw_value: 结论',
      'state_variable: 已完成',
      'transform_step: 见结果',
      'decision_path: 正确',
      'output_target: 成功',
      'can_prove: 业务已经证明',
      'cannot_prove: 没有不能证明的部分',
      'next_step: 结束',
    ].join('\n'),
    badReasons: [
      '把输入契约和原始值混成结论。',
      '把 output_target 写成成功口号，而不是出口类型。',
      '没有交代不能证明什么，也没有留下下一步。',
    ],
    revisionSteps: [
      '先把输入、原始值和变量接力分开写。',
      '再把判断路径和输出契约分别写出来。',
      '最后补上 can_prove、cannot_prove 和 next_step。',
    ],
    goodExample: [
      '# execution-flow-diagram.md',
      '',
      'flow_id: w8d2-order-summary-flow',
      'input_source: command line and form payload',
      'raw_value: "0080"',
      'state_variable: clean_amount',
      'transform_step: trim then parse number',
      'decision_path: amount > threshold',
      'output_target: summary text and status flag',
      'can_prove: this 教学模拟 chart proves the path from input to output',
      'cannot_prove: it cannot prove the real business result is already correct',
      'next_step: W8D3',
    ].join('\n'),
    guidedPrompts: [
      '这张图的起点是什么输入源？',
      '原始值和中间变量分别是谁？',
      '哪一步真正改变了路径？',
      '输出契约最后交出了什么？',
      '这张图不能证明什么？',
    ],
    blankTemplate: [
      '# execution-flow-diagram.md',
      '',
      'flow_id:',
      'input_source:',
      'raw_value:',
      'state_variable:',
      'transform_step:',
      'decision_path:',
      'output_target:',
      'can_prove:',
      'cannot_prove:',
      'next_step: W8D3',
    ].join('\n'),
    standardTemplate: [
      '# execution-flow-diagram.md',
      '',
      'flow_id: w8d2-<scene>',
      'input_source: <where the input comes from>',
      'raw_value: <raw text or number>',
      'state_variable: <the variable that carries the state>',
      'transform_step: <what changes the shape>',
      'decision_path: <which branch is chosen>',
      'output_target: <terminal, file, return value, or status>',
      'can_prove: <what this 教学模拟 can prove>',
      'cannot_prove: <what this teaching simulation cannot prove>',
      'next_step: W8D3',
    ].join('\n'),
    checklist: [
      '输入源和原始值分开写清。',
      '变量接力和转换步骤都被标出来。',
      '判断路径和输出契约都被写清。',
      '不能证明和下一步都已补上。',
      'next_step 只指向 W8D3，不提前写 JSON/CSV 已完成。',
    ],
  },
  memory: {
    conceptIds: ['script-input-contract', 'raw-value-capture', 'intermediate-state-flow', 'transformation-step', 'decision-path', 'output-contract', 'flow-trace', 'execution-flow-diagram'],
    anchors: [
      '输入契约先看字段和格式。',
      '原始值要和中间状态分开。',
      '判断路径只说明走哪条路。',
      '输出契约不等于业务真相。',
    ],
    closedBookPrompt: '闭卷解释一遍：脚本怎样从输入契约开始，经过原始值、变量接力、转换和判断，最后交到输出契约；再说清这张图能证明什么、不能证明什么。',
    microOperation: '拿一段五行伪代码，把输入、原始值、变量接力、判断和输出各圈一遍。',
    unresolvedPrompt: '如果输入格式变了，哪一步最先变化？如果输出形式变了，哪一步最先变化？',
    reviewStages: [
      { stage: 'D1', task: '回看输入契约和原始值，确认它们不是同一个东西。' },
      { stage: 'D3', task: '复述变量接力、转换和判断怎样改变路径。' },
      { stage: 'D7', task: '用一段新脚本再画一次执行流程图。' },
      { stage: 'D14', task: '对比两个不同输入，说明哪些分支会变。' },
      { stage: 'D30', task: '说出流程图能证明什么，不能证明什么。' },
      { stage: 'D60', task: '说明 W8D2 与 W8D3 的边界：流程图 vs JSON/CSV 处理。' },
    ],
  },
  nextLesson: {
    id: 'W8D3',
    title: '处理JSON和CSV',
    bridge: 'W8D2 先只把输入到输出的变量路径画清；W8D3 才进入 JSON 和 CSV 的结构读取与写出。',
  },
}

export function getW8D2(dayId: string): DailyCourse | undefined {
  return dayId === 'W8D2' ? w8d2 : undefined
}
