import type { DayId } from './types'
import type { Day01FrameworkPlan } from './day01Framework'

export const w8d2Framework: Day01FrameworkPlan = {
  dayId: 'W8D2',
  label: '从输入到输出',
  chapters: [
    {
      id: 'chapter-1',
      number: 1,
      session: 1,
      timeMinutes: 8,
      title: '建立任务：先看输入怎样进入脚本',
      lead: 'W8D2 不急着进入 JSON、CSV、文件批处理或报错诊断。先把输入契约、原始值和第一个变量看清，再决定流程图怎么画。',
      conceptIds: [],
      semanticSections: ['scenario', 'objectives', 'prerequisites'],
      practice: {
        prompt: '同事说“只要输出有了，输入怎么来的不重要”。你最先纠正什么？',
        options: ['先看输入契约、原始值和变量接力，再看输出契约', '直接宣布结果可信', '先跳到 JSON 解析'],
        answerIndex: 0,
        explanation: 'W8D2 先把输入到输出的路径画清，不能把输出当成全部证据。',
      },
      retellPrompt: '用两三句话说明：为什么 W8D2 先看输入契约和原始值，而不是直接看最后输出？',
      retellRubric: ['提到输入契约', '提到原始值和变量接力', '没有越界到 W8D3'],
    },
    {
      id: 'chapter-2',
      number: 2,
      session: 1,
      timeMinutes: 14,
      title: '模型一：输入契约和原始值',
      lead: '脚本先接住外部输入，再把原始值放进第一个变量；这一步只是在入口和起点上站稳，不是在下结论。',
      conceptIds: ['script-input-contract', 'raw-value-capture'],
      semanticSections: ['concepts'],
      practice: {
        prompt: '哪句话最符合输入契约和原始值捕获的关系？',
        options: ['输入契约先说清字段和格式，原始值先原样接住', '原始值一进来就等于结果', '输出契约可以省略'],
        answerIndex: 0,
        explanation: '入口约定和原始值接收是两件事，不能混成一个结论。',
      },
      retellPrompt: '闭卷解释输入契约、原始值和第一个变量各自负责什么。',
      retellRubric: ['区分契约和原始值', '说清变量接住什么', '不把输入当结果'],
    },
    {
      id: 'chapter-3',
      number: 3,
      session: 1,
      timeMinutes: 14,
      title: '模型二：变量接力和转换步骤',
      lead: '变量会接住状态，转换会改值的形态；你要能看见哪一步只是接力，哪一步真的改变了内容。',
      conceptIds: ['intermediate-state-flow', 'transformation-step'],
      semanticSections: ['concepts', 'diagram'],
      practice: {
        prompt: '为什么原始字符串和转成数字的值要分开看？',
        options: ['因为中间状态和转换步骤会影响后续路径', '因为字符串一定没用', '因为输出看起来更像结果'],
        answerIndex: 0,
        explanation: '接力和转换决定后面的判断是否成立，不能合并成一个步骤。',
      },
      retellPrompt: '用“输入→接力→转换→输出”复述这一章。',
      retellRubric: ['说清接力和转换', '说清中间状态', '没有混淆结果和过程'],
    },
    {
      id: 'chapter-4',
      number: 4,
      session: 1,
      timeMinutes: 10,
      title: '第一次复述检查：路径不是结果证明',
      lead: '这一章不增加新术语。你要把输入契约、原始值、变量接力和转换串成一条线，再说清它们还不能证明什么。',
      conceptIds: ['script-input-contract', 'raw-value-capture', 'intermediate-state-flow', 'transformation-step'],
      semanticSections: ['concepts', 'diagram'],
      practice: {
        prompt: '哪条说法没有越界？',
        options: ['流程图只说明路径和出口，不等于真实业务结果已证明', '只要变量变了，就说明结论已经对了', '看见输出就可以跳过输入'],
        answerIndex: 0,
        explanation: '执行流程图只负责把路径说清，不负责把业务真相替你证明完。',
      },
      retellPrompt: '用“看到／可以判断／不能判断”复述 W8D2 前半段。',
      retellRubric: ['提到路径和出口', '区分过程和结论', '没有越界到 JSON/CSV'],
    },
    {
      id: 'chapter-5',
      number: 5,
      session: 2,
      timeMinutes: 16,
      title: '操作模型：把脚本拆成执行流程图',
      lead: '把输入契约、原始值、判断路径和输出契约拆开，才知道脚本哪一步在接力、哪一步在分流。',
      conceptIds: ['script-input-contract', 'raw-value-capture', 'intermediate-state-flow', 'transformation-step', 'decision-path', 'output-contract'],
      semanticSections: ['diagram', 'demonstration', 'guided-lab'],
      practice: {
        prompt: '当脚本出现 if amount > threshold 时，最准确的作用是什么？',
        options: ['它根据条件决定下一条路径', '它已经证明金额一定正确', '它只是把输出提前而已'],
        answerIndex: 0,
        explanation: '分支只负责选路，不负责证明路径本身正确。',
      },
      retellPrompt: '解释输入契约、转换步骤、判断路径和输出契约分别改变了什么。',
      retellRubric: ['说清输入契约', '说清判断路径', '说清输出边界'],
    },
    {
      id: 'chapter-6',
      number: 6,
      session: 2,
      timeMinutes: 12,
      title: '责任与证据边界：路径透明不等于结果成立',
      lead: '看见流程痕迹，只能说明路径被走过；看见输出契约，只能说明出口被交付，不能自动把真实业务结论抬高。',
      conceptIds: ['decision-path', 'output-contract', 'flow-trace'],
      semanticSections: ['independent-lab', 'feedback'],
      practice: {
        prompt: '哪条说法最稳妥？',
        options: ['路径透明和出口清楚，不代表业务真相已经成立', '有了输出契约，脚本就等于完成上线', '只要分支更短，结果就一定对'],
        answerIndex: 0,
        explanation: '流程和出口是证据，真相还要靠后续验证。',
      },
      retellPrompt: '用“能证明／不能证明／下一步”说明流程痕迹和输出契约。',
      retellRubric: ['说明路径透明', '说明出口边界', '不提前讲 W8D3'],
    },
    {
      id: 'chapter-7',
      number: 7,
      session: 2,
      timeMinutes: 18,
      title: '实验、执行流程图.md 与最终复述',
      lead: '最后完成输入到输出观察器、针对性练习和 execution-flow-diagram.md：字段齐全，教学模拟和真实边界分开，下一步只进入 W8D3。',
      conceptIds: ['script-input-contract', 'raw-value-capture', 'intermediate-state-flow', 'transformation-step', 'decision-path', 'output-contract', 'flow-trace', 'execution-flow-diagram'],
      semanticSections: ['guided-lab', 'exercises', 'feedback', 'deliverable', 'memory', 'completion'],
      practice: {
        prompt: '一份合格 execution-flow-diagram.md 最关键的组合是什么？',
        options: ['输入源、原始值、变量接力、转换步骤、判断路径、输出契约和 cannot_prove', '只写“脚本已经输出了”', '直接贴 W8D3 的 JSON/CSV 结果'],
        answerIndex: 0,
        explanation: '执行流程图必须可复核、可重画、不过界；它不替后续课程完成任务。',
      },
      retellPrompt: '最终复述八个首次教学概念，并说明 execution-flow-diagram.md 能证明什么、不能证明什么。',
      retellRubric: ['八个概念进入同一流程链', '字段齐全', '不伪造 W8D3 或外部结果'],
    },
  ],
}

export function getW8D2FrameworkPlan(dayId: DayId): Day01FrameworkPlan | undefined {
  return dayId === 'W8D2' ? w8d2Framework : undefined
}
