import type { DayId } from './types'
import type { Day01FrameworkPlan } from './day01Framework'

const w8d6Framework: Day01FrameworkPlan = {
  dayId: 'W8D6',
  label: '生成每日业务摘要',
  chapters: [
    {
      id: 'chapter-1',
      number: 1,
      session: 1,
      timeMinutes: 8,
      title: '建立任务：先看输入怎样进入摘要脚本',
      lead: 'W8D6 不急着写结论。先把输入契约、原始记录和第一批停步条件看清，再决定摘要草稿怎么生成。',
      conceptIds: [],
      semanticSections: ['scenario', 'objectives', 'prerequisites'],
      practice: {
        prompt: '同事说“摘要一页写完就行，输入怎么来的不重要”。你最先纠正什么？',
        options: ['先看输入契约、清洗规则和证据边界', '直接宣布摘要正确', '先跳到模板排版'],
        answerIndex: 0,
        explanation: 'W8D6 先把输入到输出的摘要路径画清，不能把摘要当成全部证据。',
      },
      retellPrompt: '用两三句话说明：为什么 W8D6 先看输入契约和原始记录，而不是直接看最后摘要？',
      retellRubric: ['提到输入契约', '提到清洗和快照', '没有越界到真实上线'],
    },
    {
      id: 'chapter-2',
      number: 2,
      session: 1,
      timeMinutes: 14,
      title: '模型一：输入契约和源记录清洗',
      lead: '脚本先接住外部输入，再把原始记录整理成可统计的样子；这一步只是在入口和整理台上站稳，不是在下结论。',
      conceptIds: ['summary-input-contract', 'source-record-normalization', 'fallback-on-schema-mismatch'],
      semanticSections: ['concepts'],
      practice: {
        prompt: '哪句话最符合输入契约和归一化的关系？',
        options: ['输入契约先说清字段，归一化再整理记录形状', '原始记录一进来就等于摘要', '输出模板可以省略'],
        answerIndex: 0,
        explanation: '入口约定和记录整理是两件事，不能混成一个结论。',
      },
      retellPrompt: '闭卷解释输入契约、清洗规则和停步分支各自负责什么。',
      retellRubric: ['区分契约和清洗', '说清缺口怎么处理', '不把输入当结果'],
    },
    {
      id: 'chapter-3',
      number: 3,
      session: 1,
      timeMinutes: 14,
      title: '模型二：指标快照和文本模板',
      lead: '快照负责把一天的数据压成可复核数字，模板负责把这些数字组织成读得懂的摘要；你要能看见哪一步只是加工，哪一步真的改变了输出形态。',
      conceptIds: ['metric-snapshot-assembly', 'text-template-assembly'],
      semanticSections: ['concepts', 'diagram'],
      practice: {
        prompt: '为什么快照数字和摘要段落要分开看？',
        options: ['因为中间快照和模板填充会影响后续判断', '因为数字一定不重要', '因为摘要看起来更像结论'],
        answerIndex: 0,
        explanation: '快照和模板决定后面的摘要怎么形成，不能把两者合并成一个步骤。',
      },
      retellPrompt: '用“输入→清洗→快照→模板→输出”复述这一章。',
      retellRubric: ['说清快照和模板', '说清中间状态', '没有混淆结果和过程'],
    },
    {
      id: 'chapter-4',
      number: 4,
      session: 1,
      timeMinutes: 10,
      title: '第一次复述检查：摘要不是业务真相证明',
      lead: '这一章不增加新术语。你要把输入契约、清洗规则、指标快照和模板拼装串成一条线，再说清它们还不能证明什么。',
      conceptIds: ['summary-input-contract', 'source-record-normalization', 'metric-snapshot-assembly', 'text-template-assembly'],
      semanticSections: ['concepts', 'diagram'],
      practice: {
        prompt: '哪条说法没有越界？',
        options: ['摘要只说明路径和边界，不等于真实业务已经证明', '只要快照有数字，结论就一定对', '看见输出就可以跳过输入'],
        answerIndex: 0,
        explanation: '自动摘要脚本只负责把路径说清，不负责把业务真相替你证明完。',
      },
      retellPrompt: '用“看到／可以判断／不能判断”复述 W8D6 前半段。',
      retellRubric: ['提到路径和边界', '区分过程和结论', '没有越界到真实生产'],
    },
    {
      id: 'chapter-5',
      number: 5,
      session: 2,
      timeMinutes: 16,
      title: '操作模型：把清洗、统计和文本拼起来',
      lead: '把输入契约、归一化、快照、模板和输出边界拆开，才知道脚本哪一步在整理材料、哪一步在生成摘要。',
      conceptIds: ['summary-input-contract', 'source-record-normalization', 'metric-snapshot-assembly', 'text-template-assembly', 'daily-summary-script'],
      semanticSections: ['diagram', 'demonstration', 'guided-lab'],
      practice: {
        prompt: '当脚本出现 schema mismatch 时，最准确的作用是什么？',
        options: ['它根据字段缺口决定停步、跳过还是降级', '它已经证明摘要完全正确', '它只是把输出提前而已'],
        answerIndex: 0,
        explanation: '格式不匹配只负责选路和留痕，不负责证明结果本身正确。',
      },
      retellPrompt: '解释输入契约、清洗规则、指标快照和模板分别改变了什么。',
      retellRubric: ['说清输入契约', '说清摘要路径', '说清输出边界'],
    },
    {
      id: 'chapter-6',
      number: 6,
      session: 2,
      timeMinutes: 12,
      title: '责任与证据边界：可复跑不等于已上线',
      lead: '看见运行命令和输出路径，只能说明摘要脚本可复跑；看见证据边界，只能说明我们没有把教学模拟写成生产承诺。',
      conceptIds: ['repeatable-run-command', 'evidence-limit-boundary'],
      semanticSections: ['independent-lab', 'feedback'],
      practice: {
        prompt: '哪条说法最稳妥？',
        options: ['命令可复跑和边界清楚，不代表生产自动化已经成立', '有了输出文件，脚本就等于上线', '只要模板更短，结果就一定对'],
        answerIndex: 0,
        explanation: '脚本和边界是证据，生产真相还要靠后续验证。',
      },
      retellPrompt: '用“能证明／不能证明／下一步”说明摘要脚本和输出边界。',
      retellRubric: ['说明可复跑', '说明边界限制', '不提前讲 W9D1 细节'],
    },
    {
      id: 'chapter-7',
      number: 7,
      session: 2,
      timeMinutes: 18,
      title: '实验、daily-summary-script.py 与最终复述',
      lead: '最后完成输入到输出观察器、针对性练习和 daily-summary-script.py：字段齐全，教学模拟和真实边界分开，下一步只进入 W9D1。',
      conceptIds: ['summary-input-contract', 'source-record-normalization', 'metric-snapshot-assembly', 'text-template-assembly', 'repeatable-run-command', 'evidence-limit-boundary', 'fallback-on-schema-mismatch', 'daily-summary-script'],
      semanticSections: ['guided-lab', 'exercises', 'feedback', 'deliverable', 'memory', 'completion'],
      practice: {
        prompt: '一份合格 daily-summary-script.py 最关键的组合是什么？',
        options: ['输入源、清洗规则、指标快照、文本模板、run_command、can_prove 和 cannot_prove', '只写“摘要已经输出了”', '直接贴 W9D1 的后续结果'],
        answerIndex: 0,
        explanation: '自动摘要脚本必须可解释、可复核、不过界；它不替后续课程完成任务。',
      },
      retellPrompt: '最终复述八个首次教学概念，并说明 daily-summary-script.py 能证明什么、不能证明什么。',
      retellRubric: ['八个概念进入同一流程链', '字段齐全', '不伪造生产上线'],
    },
  ],
}

export function getW8D6FrameworkPlan(dayId: DayId): Day01FrameworkPlan | undefined {
  return dayId === 'W8D6' ? w8d6Framework : undefined
}
