import type { DayId } from './types'
import type { Day01FrameworkPlan } from './day01Framework'

const w9d3Framework: Day01FrameworkPlan = {
  dayId: 'W9D3',
  label: '清洗订单',
  chapters: [
    {
      id: 'chapter-1',
      number: 1,
      session: 1,
      timeMinutes: 8,
      title: '建立任务：先看订单怎么脏了',
      lead: 'W9D3 不急着写 clean 表。先把输入契约、原始订单和第一批停步条件看清，再决定清洗脚本怎么开始。',
      conceptIds: [],
      semanticSections: ['scenario', 'objectives', 'prerequisites'],
      practice: {
        prompt: '同事说“脏订单先删再说”。你最先纠正什么？',
        options: ['先看输入契约、六维体检和 quarantine 边界', '直接宣布 clean 表正确', '先跳到报告排版'],
        answerIndex: 0,
        explanation: 'W9D3 先把输入到输出的清洗路径画清，不能把 clean 表当成全部证据。',
      },
      retellPrompt: '用两三句话说明：为什么 W9D3 先看输入契约和六维体检，而不是直接看 clean 表？',
      retellRubric: ['提到输入契约', '提到六维体检和 quarantine', '没有越界到真实生产'],
    },
    {
      id: 'chapter-2',
      number: 2,
      session: 1,
      timeMinutes: 14,
      title: '模型一：输入契约和质量六维',
      lead: '脚本先接住 orders_dirty.csv，再把原始订单整理成可体检的样子；这一步只是在入口和体检台上站稳，不是在下结论。',
      conceptIds: ['orders-data-contract', 'data-quality-snapshot', 'pandas-copy-and-coerce'],
      semanticSections: ['concepts'],
      practice: {
        prompt: '哪句话最符合输入契约和六维体检的关系？',
        options: ['输入契约先说清字段，六维体检再整理质量快照', '原始订单一进来就等于 clean', 'quarantine 可以省略'],
        answerIndex: 0,
        explanation: '入口约定和质量体检是两件事，不能混成一个结论。',
      },
      retellPrompt: '闭卷解释输入契约、六维体检和类型转换各自负责什么。',
      retellRubric: ['区分契约和体检', '说清缺口怎么处理', '不把输入当结果'],
    },
    {
      id: 'chapter-3',
      number: 3,
      session: 1,
      timeMinutes: 14,
      title: '模型二：问题标记和 clean/quarantine 分流',
      lead: '问题标记负责把缺失、重复、异常金额和未知状态写成布尔列，分流负责把行拆成 clean 与 quarantine；你要能看见哪一步只是标记，哪一步真的改变了输出形态。',
      conceptIds: ['issue-flag-columns', 'clean-vs-quarantine-split', 'rule-impact-log'],
      semanticSections: ['concepts', 'diagram'],
      practice: {
        prompt: '为什么问题标记列和分流要分开看？',
        options: ['因为先标记再分流，后续才知道哪条规则影响了多少行', '因为删行更快', '因为 clean 表看起来更整齐'],
        answerIndex: 0,
        explanation: '标记和分流决定后面的清洗怎么形成，不能把两者合并成一个步骤。',
      },
      retellPrompt: '用“输入→体检→标记→分流→输出”复述这一章。',
      retellRubric: ['说清标记和分流', '说清中间状态', '没有混淆结果和过程'],
    },
    {
      id: 'chapter-4',
      number: 4,
      session: 1,
      timeMinutes: 10,
      title: '第一次复述检查：clean 不是证据全部',
      lead: '这一章不增加新术语。你要把输入契约、六维体检、问题标记和 clean/quarantine 分流串成一条线，再说清它们还不能证明什么。',
      conceptIds: ['orders-data-contract', 'data-quality-snapshot', 'issue-flag-columns', 'clean-vs-quarantine-split'],
      semanticSections: ['concepts', 'diagram'],
      practice: {
        prompt: '哪条说法没有越界？',
        options: ['clean 只说明可继续使用的部分，不等于真实业务已经证明', '只要 clean 表有行，结论就一定对', '看见输出就可以跳过 quarantine'],
        answerIndex: 0,
        explanation: '订单清洗脚本只负责把路径说清，不负责把业务真相替你证明完。',
      },
      retellPrompt: '用“看到／可以判断／不能判断”复述 W9D3 前半段。',
      retellRubric: ['提到路径和边界', '区分过程和结论', '没有越界到真实生产'],
    },
    {
      id: 'chapter-5',
      number: 5,
      session: 2,
      timeMinutes: 16,
      title: '操作模型：把标记、分流和对账拼起来',
      lead: '把输入契约、体检、标记、分流、规则日志和对账拆开，才知道脚本哪一步在整理材料、哪一步在生成 clean 与 quarantine。',
      conceptIds: ['orders-data-contract', 'pandas-copy-and-coerce', 'issue-flag-columns', 'clean-vs-quarantine-split', 'rule-impact-log', 'reconciliation-check'],
      semanticSections: ['diagram', 'demonstration', 'guided-lab'],
      practice: {
        prompt: '当脚本出现未知状态时，最准确的作用是什么？',
        options: ['它根据问题标记决定隔离、保留还是降级', '它已经证明 clean 表完全正确', '它只是把输出提前而已'],
        answerIndex: 0,
        explanation: '未知状态只负责选路和留痕，不负责证明结果本身正确。',
      },
      retellPrompt: '解释输入契约、问题标记、规则日志和对账分别改变了什么。',
      retellRubric: ['说清输入契约', '说清清洗路径', '说清对账边界'],
    },
    {
      id: 'chapter-6',
      number: 6,
      session: 2,
      timeMinutes: 12,
      title: '责任与证据边界：可复跑不等于已批准',
      lead: '看见运行命令和输出路径，只能说明 clean_orders.py 可复跑；看见证据边界，只能说明我们没有把教学模拟写成生产承诺。',
      conceptIds: ['rule-impact-log', 'reconciliation-check'],
      semanticSections: ['independent-lab', 'feedback'],
      practice: {
        prompt: '哪条说法最稳妥？',
        options: ['命令可复跑和边界清楚，不代表生产数据已经完全可信', '有了 clean.csv，脚本就等于上线', '只要 report 更短，结果就一定对'],
        answerIndex: 0,
        explanation: '脚本和边界是证据，生产真相还要靠后续验证。',
      },
      retellPrompt: '用“能证明／不能证明／下一步”说明清洗脚本和输出边界。',
      retellRubric: ['说明可复跑', '说明边界限制', '不提前讲 W9D4 细节'],
    },
    {
      id: 'chapter-7',
      number: 7,
      session: 2,
      timeMinutes: 18,
      title: '实验、clean_orders.py 与最终复述',
      lead: '最后完成输入到输出观察器、针对性练习和 clean_orders.py：字段齐全，教学模拟和真实边界分开，下一步只进入 W9D4。',
      conceptIds: ['orders-data-contract', 'data-quality-snapshot', 'pandas-copy-and-coerce', 'issue-flag-columns', 'clean-vs-quarantine-split', 'rule-impact-log', 'reconciliation-check', 'order-cleaning-script'],
      semanticSections: ['guided-lab', 'exercises', 'feedback', 'deliverable', 'memory', 'completion'],
      practice: {
        prompt: '一份合格 clean_orders.py 最关键的组合是什么？',
        options: ['输入源、质量规则、issue flags、clean/quarantine、rule_log、reconciliation_summary、can_prove 和 cannot_prove', '只写“清洗已经完成了”', '直接贴 W9D4 的后续结果'],
        answerIndex: 0,
        explanation: '订单清洗脚本必须可解释、可复核、不过界；它不替后续课程完成规则影响分析。',
      },
      retellPrompt: '最终复述八个首次教学概念，并说明 clean_orders.py 能证明什么、不能证明什么。',
      retellRubric: ['八个概念进入同一流程链', '字段齐全', '不伪造生产批准'],
    },
  ],
}

export function getW9D3FrameworkPlan(dayId: DayId): Day01FrameworkPlan | undefined {
  return dayId === 'W9D3' ? w9d3Framework : undefined
}
